mui/mui-x

- packages/demo-app/src/app/demos/grid/components/settings-panel.tsx
- packages/demo-app/src/app/demos/grid/real-data-grid.demo.tsx
- packages/grid/x-grid-modules/src/components/styled-wrappers/columns-container.tsx
- packages/grid/x-grid-modules/src/components/styled-wrappers/data-container.tsx
- packages/grid/x-grid-modules/src/components/styled-wrappers/footer.tsx
- packages/grid/x-grid-modules/src/components/styled-wrappers/grid-root.tsx
- packages/grid/x-grid-modules/src/components/styled-wrappers/window-overlay.tsx
- packages/grid/x-grid-modules/src/components/styled-wrappers/window.tsx
Use the helper everywhere it's interesting. Next step will be to rename it clsx and bundle the dependency.
#6
> [core] Use the classnames helper

- packages/grid/x-grid-modules/lib/autosizer/types.d.ts
- packages/grid/x-grid-modules/src/gridComponent.tsx
- packages/grid/x-grid-modules/src/gridComponentProps.ts
- packages/grid/x-grid-modules/src/models/api/apiRef.ts
- packages/grid/x-grid-modules/src/models/api/columnApi.ts
- packages/grid/x-grid-modules/src/models/api/gridApi.ts
- packages/grid/x-grid-modules/src/models/api/paginationApi.ts
- packages/grid/x-grid-modules/src/models/api/rowApi.ts
- packages/grid/x-grid-modules/src/models/api/selectionApi.ts
- packages/grid/x-grid-modules/src/models/api/sortApi.ts
- packages/grid/x-grid-modules/src/models/api/virtualizationApi.ts
- packages/grid/x-grid-modules/src/models/colDef/colDef.ts
- packages/grid/x-grid-modules/src/models/containerProps.ts
- packages/grid/x-grid-modules/src/models/elementSize.ts
- packages/grid/x-grid-modules/src/models/gridComponentOverridesProp.tsx
- packages/grid/x-grid-modules/src/models/gridOptions.tsx
- packages/grid/x-grid-modules/src/models/params/cellClickedParams.ts
- packages/grid/x-grid-modules/src/models/params/colParams.ts
- packages/grid/x-grid-modules/src/models/params/columnSortedParams.ts
- packages/grid/x-grid-modules/src/models/params/componentParams.ts
- packages/grid/x-grid-modules/src/models/params/pageChangedParams.ts
- packages/grid/x-grid-modules/src/models/params/rowClickedParams.ts
- packages/grid/x-grid-modules/src/models/params/rowSelectedParams.ts
- packages/grid/x-grid-modules/src/models/renderContextProps.ts
- packages/grid/x-grid-modules/src/models/rows.ts
- packages/grid/x-grid-modules/src/models/sortModel.ts
> [docs] Improve the JSDoc

- packages/grid/x-grid-modules/src/gridComponent.tsx
- packages/grid/x-grid-modules/src/models/gridOptions.tsx
> [DataGrid] Set default logLevel to warn

- .eslintrc.js
- .gitignore
- packages/grid/data-grid/package.json
- packages/grid/x-grid-data-generator/package.json
- packages/grid/x-grid-modules/src/models/gridOptions.tsx
- packages/grid/x-grid/package.json
- packages/license/package.json
- packages/license/src/verifyLicense.ts
- [core] Define minimum node version on public packages be9bc05: to match the supported platform spec https://material-ui.com/getting-started/supported-platforms/.
- [core] Sort gitignore ASC 5a68d81
- [test] Avoid deprecated APIs c03ec6f: apply https://github.com/mui-org/material-ui/pull/21974#discussion_r462484116
- [docs] Fix JSDoc a7fc11a
- [core] Add missing yargs dependency 1be7915: it's a dependency in the prettier script. Spot it trying yarn v2 out. It shoundn't be ambiguous (no transitive dependency).
- [test] done() is unnecessarily redundant when using async: 5b95124: Extracted from https://github.com/mui-org/material-ui-x/pull/115/files#r460569059.
- [core] Top level function convention a69064f
Done in pair with https://github.com/mui-org/material-ui/pull/22020
> [core] Batch small changes

- packages/grid/x-grid-modules/src/constants/eventsConstants.ts
- packages/grid/x-grid-modules/src/hooks/features/usePagination.ts
- packages/grid/x-grid-modules/src/hooks/features/useSelection.ts
- packages/grid/x-grid-modules/src/hooks/root/useEvents.ts
- packages/grid/x-grid-modules/src/hooks/root/useKeyboard.ts
- packages/grid/x-grid-modules/src/hooks/virtualization/useVirtualRows.ts
- packages/grid/x-grid/test/XGrid.test.tsx
1. Bug with blur event 
=> press CTRL/CMD key + click to select multiple rows then press T to create a new tab, back to grid and click another row
issue -> multiple selection still on
expected -> one row selected
2. Bug with checkbox selection
=> click to select a row, click again should deselect it
3. Events name refactoring
> Fix selection

- packages/grid/x-grid-modules/src/hooks/root/useEvents.ts
> [core] Removing polluting warning

- test/karma.tests.js
- test/utils/consoleError.js
This is a continuation of https://github.com/mui-org/material-ui/pull/22075, it's meant to avoid problems like #150 this to land in production. The CI should fail. Once we fix #150, we can rebase this pull request and merge.
> [test] CI part of #150

- packages/grid/x-grid-modules/src/components/icons/index.tsx
- packages/grid/x-grid-modules/src/models/gridOptions.tsx
Better provide the right svg shape upfront. For #8
For context, I have generated the svg path with Sketch + SVGOMG
> [DataGrid] Avoid inline style

- .eslintrc.js
- packages/grid/x-grid-data-generator/src/useDemoData.ts
- packages/grid/x-grid-modules/src/gridComponent.tsx
- packages/grid/x-grid-modules/src/hooks/features/useApiRef.ts
- packages/grid/x-grid-modules/src/hooks/root/useNativeEventListener.ts
- packages/grid/x-grid-modules/src/hooks/utils/useScrollFn.ts
- packages/storybook/src/components/feed-grid.tsx
- packages/storybook/src/components/pricing-grid.tsx
> [core] Fail CI if wrong effect dependencies

- docs/src/pages/components/data-grid/pagination/AutoPaginationGrid.js
- docs/src/pages/components/data-grid/pagination/AutoPaginationGrid.tsx
- docs/src/pages/components/data-grid/pagination/BasicPaginationGrid.js
- docs/src/pages/components/data-grid/pagination/BasicPaginationGrid.tsx
- docs/src/pages/components/data-grid/pagination/ControlledPaginationGrid.js
- docs/src/pages/components/data-grid/pagination/ControlledPaginationGrid.tsx
- docs/src/pages/components/data-grid/pagination/SizePaginationGrid.js
- docs/src/pages/components/data-grid/pagination/SizePaginationGrid.tsx
- docs/src/pages/components/data-grid/pagination/pagination.md
- docs/src/pages/components/data-grid/rendering/CustomPaginationGrid.js
- docs/src/pages/components/data-grid/rendering/CustomPaginationGrid.tsx
- docs/src/pages/components/data-grid/rendering/rendering.md
A new iteration on the pagination feature.
> [docs] Migration of the pagination

- .codesandbox/ci.json
- package.json
I want to make sure I don't break the release in #225
Part of #37
> [test] Add codesandbox-ci

- docs/src/pages/components/data-grid/getting-started/getting-started.md
- docs/src/pages/components/data-grid/overview/overview.md
- packages/x-license/src/licenseErrorMessageUtils.ts
The pricing page is still a WIP with the design agency, for now, we can link the fulfillment page.
> [docs] Add pricing links

- docs/pages/components/data-grid/group-pivot.js
- docs/src/pages/components/data-grid/columns/columns.md
- docs/src/pages/components/data-grid/overview/overview.md
- docs/src/pages/components/data-grid/pagination/pagination.md
- docs/src/pages/components/data-grid/rows/rows.md
- docs/src/pages/components/data-grid/selection/selection.md
- yarn.lock
Depends on https://github.com/mui-org/material-ui/pull/22574
> [docs] Disable ads on Enterprise features

- docs/src/pages/components/data-grid/overview/overview.md
> [docs] Add Resources section

- docs/src/pages/components/data-grid/getting-started/getting-started.md
- docs/src/pages/components/data-grid/group-pivot/group-pivot.md
> [docs] Fix short description warning

- packages/grid/data-grid/package.json
- packages/grid/x-grid/package.json
> [DataGrid] Add npm keywords

- packages/grid/x-grid-modules/src/components/cell.tsx
- packages/grid/x-grid-modules/src/hooks/root/useEvents.ts
- packages/grid/x-grid-modules/src/hooks/root/useKeyboard.ts
- packages/grid/x-grid-modules/src/utils/domUtils.ts
- packages/grid/x-grid/src/XGrid.test.tsx
- packages/storybook/integration/helper-fn.ts
- packages/storybook/src/data/data-service.ts
- packages/storybook/src/hooks/useData.ts
- packages/storybook/src/stories/grid-pagination.stories.tsx
- packages/storybook/src/stories/grid-selection.stories.tsx
The flakiness rate seems to be above 10%. It's too much for a pleasant DX. It should be fixed. The fix is to make `useData` systematically resolve when wrapped with `act()`: https://reactjs.org/docs/test-utils.html#act, it requires to remove the usage of the promise.
I have also worked on it to signal that skipping is almost always the wrong answer :D.
> [test] Fix flaky test

- docs/src/pages/components/data-grid/overview/overview.md
I will apply the same change to all the other pages cc @mbrookes
> [docs] Swap words to better match users' query

- docs/src/pages/components/data-grid/columns/ColumnTypesGrid.js
- docs/src/pages/components/data-grid/columns/ColumnTypesGrid.tsx
- docs/src/pages/components/data-grid/columns/CustomColumnTypesGrid.js
- docs/src/pages/components/data-grid/columns/CustomColumnTypesGrid.tsx
- docs/src/pages/components/data-grid/getting-started/getting-started.md
- docs/src/pages/components/data-grid/rendering/RenderCellGrid.js
- docs/src/pages/components/data-grid/rendering/RenderCellGrid.tsx
- docs/src/pages/components/data-grid/rendering/RenderHeaderGrid.js
- docs/src/pages/components/data-grid/rendering/RenderHeaderGrid.tsx
- docs/src/pages/components/data-grid/rendering/StylingCellsGrid.js
- docs/src/pages/components/data-grid/rendering/StylingCellsGrid.tsx
- docs/src/pages/components/data-grid/rendering/StylingHeaderGrid.js
- docs/src/pages/components/data-grid/rendering/StylingHeaderGrid.tsx
- docs/src/pages/components/data-grid/rendering/ValueFormatterGrid.js
- docs/src/pages/components/data-grid/rendering/ValueFormatterGrid.tsx
- docs/src/pages/components/data-grid/rendering/ValueGetterGrid.js
- docs/src/pages/components/data-grid/rendering/ValueGetterGrid.tsx
- docs/src/pages/components/data-grid/rendering/rendering.md
- docs/src/pages/components/data-grid/rows/ComparatorSortingGrid.js
- docs/src/pages/components/data-grid/rows/ComparatorSortingGrid.tsx
- packages/grid/data-grid/src/DataGrid.test.tsx
- packages/grid/x-grid/src/XGrid.test.tsx
- packages/storybook/src/documentation/pages/demos/error/customError.demo.tsx
- packages/storybook/src/documentation/pages/demos/error/exception.demo.tsx
- packages/storybook/src/documentation/pages/demos/error/serverError.demo.tsx
- packages/storybook/src/documentation/pages/demos/error/serverErrorState.demo.tsx
> [docs] Remove id columns

- packages/storybook/.storybook/main.js
- packages/storybook/.storybook/preview.js
Linting working since this fix: https://github.com/mui-org/material-ui/pull/22975
> [core] Run prettier

- docs/public/_redirects
- yarn.lock
The current setup doesn't work. There is an infinite redirection loop.
Closes #499
> [docs] Fix the Netlify proxy for localization of X

- CHANGELOG.md
Changelog for release 4.0.0-alpha.9
- @material-ui/x-grid-data-generator@4.0.0-alpha.9
- @material-ui/x-license@4.0.0-alpha.9
- @material-ui/data-grid@4.0.0-alpha.9
- @material-ui/x-grid@4.0.0-alpha.9
lerna success published 4 packages
> [docs] Update changelog for v4.0.0-alpha.9

- docs/src/pages/components/data-grid/columns/columns.md
> [docs] Fix typo in columns.md

- packages/grid/data-grid/package.json
- packages/grid/x-grid/package.json
- packages/x-grid-data-generator/package.json
- packages/x-license/package.json
Seems they shouldn't be present: https://github.com/lerna/lerna/issues/1880.
> [core] Remove gitHead

- packages/grid/_modules_/grid/components/panel/ColumnsPanel.tsx
> [DataGrid] Fix keyboard navigation in column picker

- packages/grid/_modules_/grid/lib/createDetectElementResize/index.js
> [DataGrid] Fix collision with react-virtualized

- docs/next.config.js
- docs/pages/_app.js
- yarn.lock
See https://github.com/mui-org/material-ui/pull/22616 for the why.
> [docs] Enable codesandbox preview in PRs

- docs/src/pages/components/data-grid/overview/DataGridDemo.js
- docs/src/pages/components/data-grid/overview/DataGridDemo.tsx
- docs/src/pages/components/data-grid/pagination/SizePaginationGrid.js
- docs/src/pages/components/data-grid/pagination/SizePaginationGrid.tsx
- docs/src/pages/components/data-grid/rendering/AntDesignGrid.js
- docs/src/pages/components/data-grid/rows/ComparatorSortingGrid.js
- docs/src/pages/components/data-grid/rows/ComparatorSortingGrid.tsx
- docs/src/pages/components/data-grid/rows/OrderSortingGrid.js
- docs/src/pages/components/data-grid/rows/OrderSortingGrid.tsx
- docs/src/pages/components/data-grid/rows/ServerSortingGrid.js
- docs/src/pages/components/data-grid/rows/ServerSortingGrid.tsx
- yarn.lock
It's healthy to update it frequently.
> [core] Update monorepository

- CHANGELOG.md
> [CHANGELOG] Prepare v4.0.0-alpha.13

- packages/grid/x-grid/src/XGrid.tsx
> [XGrid] Fix support for custom class name generators

- packages/grid/_modules_/grid/hooks/features/rows/useRows.ts
- packages/grid/data-grid/src/tests/sorting.DataGrid.test.tsx
- packages/storybook/src/stories/grid-sorting.stories.tsx
These changes fix #753 and fix #792.
> [DataGrid] Fix wrong initial sort order

- docs/pages/api-docs/data-grid.md
- docs/pages/api-docs/x-grid.md
- docs/src/pages/components/data-grid/columns/ColumnSelectorGrid.js
- docs/src/pages/components/data-grid/columns/ColumnSelectorGrid.tsx
- docs/src/pages/components/data-grid/columns/columns.md
- packages/grid/_modules_/grid/components/panel/Panel.tsx
- packages/grid/_modules_/grid/hooks/features/preferencesPanel/usePreferencesPanel.ts
- packages/grid/_modules_/grid/models/gridOptions.tsx
Part 1 (docs) of 2 that is needed to wrap up #345
> [DataGrid] Add docs for Column selector

- packages/grid/_modules_/grid/GridComponent.tsx
- packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
> [DataGrid] Fix error handling

- .github/workflows/issue-mark-duplicate.yml
Leverage https://github.com/mui-org/material-ui/pull/24184, motivated by #876.
> [core] Automation for duplicate issues

- .dependabot/config.yml
Per https://github.com/mui-org/material-ui-x/pull/918#issuecomment-767455078
> [core] Batch storybook updates

- packages/grid/_modules_/grid/GridComponent.tsx
- packages/grid/_modules_/grid/components/containers/GridRoot.tsx
- packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
- packages/grid/_modules_/grid/components/containers/GridWindow.tsx
- packages/grid/_modules_/grid/hooks/utils/useResizeContainer.ts
- packages/grid/_modules_/grid/utils/getTotalHeight.ts
- packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
- packages/grid/x-grid/src/tests/layout.XGrid.test.tsx
- packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx
- packages/storybook/src/stories/grid-options.stories.tsx
- packages/storybook/src/style/grid-stories.css
This is an alternative attempt at #604, using the information explored from #930. The effort has been ongoing for a couple of days and the state of the pull-request didn't seem to go in the best possible direction. I wanted to test my hypothesis, it seemed to be a simple problem so I gave it a try this evening after diner. I have spent 1 hour on this, I can't guarantee it's a solid solution, but so-far seemed all good, e.g. #344 is still fixed. It was a bit more challenging than expected, the tests were failing in strict mode, I had to leverage #933.
If the solution is accepted, @DanailH could you continue it and add the missing test case, regression case for #344, story :)?
The reproduction of the issue with this attempt: https://codesandbox.io/s/material-demo-forked-svpkn
Fixes #604
> [DataGrid] Fix autoHeight, v2

- docs/pages/api-docs/data-grid.md
- docs/pages/api-docs/x-grid.md
- docs/src/pages/components/data-grid/rendering/rendering.md
- packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnMenu.tsx
- packages/grid/_modules_/grid/components/menu/columnMenu/index.ts
- packages/grid/_modules_/grid/models/gridSlotsComponent.ts
- packages/storybook/src/stories/playground/customize-components.stories.tsx
> [docs] Api page update with component slots

- docs/src/pages/components/data-grid/filtering/CustomRatingOperator.js
- docs/src/pages/components/data-grid/filtering/CustomRatingOperator.tsx
- docs/src/pages/components/data-grid/filtering/ExtendNumericOperator.js
- docs/src/pages/components/data-grid/filtering/ExtendNumericOperator.tsx
> [docs] Fix immutability with filter operator demos

- packages/grid/_modules_/grid/hooks/features/rows/useRows.ts
- packages/grid/_modules_/grid/models/api/rowApi.ts
- packages/grid/_modules_/grid/models/rows.ts
- packages/grid/x-grid/src/tests/apiRef.XGrid.test.tsx
- packages/storybook/src/stories/playground/real-data-demo.stories.tsx
> [DataGrid] Add streaming delete row api

- CHANGELOG.md
As far as I saw there were no breaking changes for this release.
> [CHANGELOG] 4.0.0-alpha.19

- docs/src/pages/components/data-grid/rows/rows.md
> [docs] Update streaming docs

- packages/grid/_modules_/grid/components/CheckboxRenderer.tsx
- packages/grid/_modules_/grid/hooks/features/filter/filterSelector.ts
- packages/grid/_modules_/grid/hooks/features/filter/useFilter.ts
- packages/grid/data-grid/src/tests/toolbar.DataGrid.test.tsx
- packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
- packages/grid/x-grid/src/tests/reorder.XGrid.test.tsx
- packages/storybook/src/stories/grid-filter.stories.tsx
- test/utils/helperFn.ts
> [DataGrid] Fix controllable filters and select all rows with filters

- packages/grid/_modules_/grid/components/panel/filterPanel/FilterPanel.tsx
- packages/grid/_modules_/grid/hooks/features/filter/useFilter.ts
- packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
- packages/storybook/src/stories/grid-filter.stories.tsx
> [XGrid] Fix server-side multi filters

- packages/grid/_modules_/grid/components/panel/filterPanel/FilterForm.tsx
- packages/grid/_modules_/grid/components/panel/filterPanel/FilterInputValue.tsx
- packages/grid/_modules_/grid/components/panel/filterPanel/FilterInputValueProps.ts
- packages/grid/_modules_/grid/constants/localeTextConstants.ts
- packages/grid/_modules_/grid/locales/bgBG.ts
- packages/grid/_modules_/grid/models/api/localeTextApi.ts
- packages/grid/_modules_/grid/utils/getLocalization.ts
This completely fixed that discussion -> https://github.com/mui-org/material-ui-x/discussions/1012
> [DataGrid] Add last of the missing translations

- packages/grid/_modules_/grid/hooks/features/sorting/useSorting.ts
- packages/grid/data-grid/src/tests/sorting.DataGrid.test.tsx
> [DataGrid] Fix reset of sortModel in controllable mode

- test/karma.conf.js
Same as https://github.com/mui-org/material-ui/pull/24935
> [test] Link CircleCI URL in BS

- docs/src/pages/components/data-grid/rendering/RenderCellGrid.tsx
- docs/src/pages/components/data-grid/rendering/rendering.md
An issue found with Damien looking at the different types
> [docs] Fix usage of the wrong type

- packages/grid/_modules_/grid/constants/localeTextConstants.ts
- packages/grid/_modules_/grid/locales/bgBG.ts
- packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
Fixes #1075 
Once this is merged https://github.com/mui-org/material-ui-x/pull/1079 and https://github.com/mui-org/material-ui-x/pull/1077 will be unblocked
> [DataGrid] Fix missing translation filterOperatorAfter key

- test/karma.conf.js
Apply the same PR ashttps://github.com/mui-org/material-ui/pull/25049
> [test] Improve BrowserStack configuration

- packages/storybook/src/stories/grid-pagination.stories.tsx
> [core] Fix storybook pagination stories

- docs/src/pages/components/data-grid/localization/localization.md
- packages/grid/_modules_/grid/constants/localeTextConstants.ts
- packages/grid/_modules_/grid/locales/enUS.ts
- packages/grid/_modules_/grid/locales/frFR.ts
- packages/grid/_modules_/grid/locales/index.ts
- packages/grid/data-grid/src/tests/toolbar.DataGrid.test.tsx
The build should fail as I have translated a key that isn't listed `filterOperatorAfter` (#1075). We can rebase once fixed.
> [DataGrid] Add frFR locale

- .circleci/config.yml
The build is failing on master, it should fix it https://github.com/mui-org/material-ui/pull/25080.
> [core] Pin playwright image to known working version

- docs/src/pages/components/data-grid/rendering/RenderExpandCellGrid.js
- docs/src/pages/components/data-grid/rendering/RenderExpandCellGrid.tsx
- docs/src/pages/components/data-grid/rendering/rendering.md
- packages/storybook/src/stories/grid-rows.stories.tsx
Add expand cell story
https://deploy-preview-1070--material-ui-x.netlify.app/storybook/?path=/story/x-grid-tests-rows--expend-row-cell
https://codesandbox.io/s/expandcelldemo-enbw7
> [docs] Add expand cell renderer

- docs/pages/api-docs/data-grid.md
- docs/pages/api-docs/x-grid.md
- packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterInputValue.tsx
- packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
- packages/grid/_modules_/grid/models/api/filterApi.ts
- packages/grid/_modules_/grid/models/params/gridFilterModelParams.ts
- packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
Fix a leaking state bug surfaced with `onFilterModelChange` in #1106
> [DataGrid] Fix issue with visible rows state

- docs/src/pages/components/data-grid/columns/ColumnSizingGrid.js
- docs/src/pages/components/data-grid/columns/ColumnSizingGrid.tsx
- docs/src/pages/components/data-grid/columns/ColumnTypesGrid.js
- docs/src/pages/components/data-grid/columns/ColumnTypesGrid.tsx
- test/regressions/TestViewer.js
- test/regressions/index.js
- test/regressions/index.test.js
I won't be surprised if we find more problems going forward.
> [test] Fix visual regression flakiness

- packages/grid/data-grid/README.md
- packages/grid/x-grid/README.md
Fix what I could notice on https://www.npmjs.com/package/@material-ui/data-grid
> [docs] Improve the description of the individual packages

- docs/src/pages/components/data-grid/rendering/CustomPaginationGrid.js
- docs/src/pages/components/data-grid/rendering/CustomPaginationGrid.tsx
This pull request fixes #1152 .
> [DataGrid] Fix rendering docs to solve custom pagination issue

- .eslintignore
Fix eslint build after running the visual regression tests.
> [core] Add build in ignore

- CHANGELOG.md
> [CHANGELOG] Release 4.0.0-alpha.22

- packages/grid/_modules_/grid/utils/keyboardUtils.ts
> [DataGrid] add shift as multiple key

- docs/src/pages/components/data-grid/columns/columns.md
> [docs] Reinforce that columns are definitions

- packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
- packages/grid/_modules_/grid/utils/utils.ts
> [core] Remove dead code

- CHANGELOG.md
CHANGELOG changes for the `v4.0.0-alpha-23` release
> [CHANGELOG] v4.0.0-alpha-23

- docs/src/pages/components/data-grid/localization/localization.md
- packages/grid/_modules_/grid/locales/index.ts
- packages/grid/_modules_/grid/locales/jaJP.ts
Adding localization files for jaJP.
> [DataGrid] Add jaJP locale

- packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx
- packages/grid/data-grid/src/tests/toolbar.DataGrid.test.tsx
> [DataGrid] Fix page shift after toggling column

- packages/grid/_modules_/grid/constants/localeTextConstants.ts
- packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
- packages/grid/_modules_/grid/locales/frFR.ts
- packages/grid/_modules_/grid/locales/ptBR.ts
- packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
- packages/grid/_modules_/grid/models/colDef/gridCheckboxSelection.tsx
Closes #1112
Preview https://deploy-preview-1379--material-ui-x.netlify.app/components/data-grid/demo/#data-grid-demo
> [DataGrid] Make "Checkbox selection" translatable

- docs/src/pages/components/data-grid/rendering/ValueGetterGrid.tsx
- packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
- packages/grid/_modules_/grid/models/gridSortModel.ts
- packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx
> [DataGrid] Fix performance issue when sorting columns

- packages/grid/data-grid/README.md
- packages/grid/data-grid/package.json
- packages/grid/x-grid-data-generator/package.json
- packages/grid/x-grid/README.md
- packages/grid/x-grid/package.json
- packages/x-license/package.json
> [DataGrid] Update min version of React to 17

- packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
- packages/grid/_modules_/grid/utils/keyboardUtils.ts
Following issue mentioned in #1287
> [DataGrid] Fix printable keys to match ag

- packages/grid/_modules_/grid/components/cell/GridCell.tsx
close https://github.com/mui-org/material-ui-x/issues/1424
> [DataGrid] Fix support for falsy value from valueFormatter

- CHANGELOG.md
- docs/src/pages/components/data-grid/accessibility/accessibility.md
- docs/src/pages/components/data-grid/selection/selection.md
- docs/src/pages/components/data-grid/sorting/sorting.md
> [docs] Add Shift key as option to enable multi-sorting

- packages/grid/x-grid-data-generator/package.json
> [docs] Fix x-grid-data-generator dependencies

- packages/grid/_modules_/grid/components/menu/columnMenu/HideGridColMenuItem.tsx
Fixes #1306 
Should we write a test case for this?
> [DataGrid] Remove 'Hide' menu item with `disableColumnSelector`

- CHANGELOG.md
- docs/package.json
- docs/src/pages/components/data-grid/editing/BasicEditingGrid.js
- docs/src/pages/components/data-grid/editing/BasicEditingGrid.tsx
- docs/src/pages/components/data-grid/editing/editing.md
- lerna.json
- package.json
- packages/grid/data-grid/package.json
- packages/grid/x-grid-data-generator/package.json
- packages/grid/x-grid/package.json
- packages/storybook/package.json
- scripts/README.md
I have used the opportunity to sync the release steps with the ones of the main repo (they work better).
> v4.0.0-alpha.26

- docs/src/pages/components/data-grid/localization/localization.md
- packages/grid/_modules_/grid/locales/index.ts
- packages/grid/_modules_/grid/locales/ruRU.ts
> [DataGrid] Add Russian (ruRU) locale

- package.json
- test/e2e/index.test.ts
- test/regressions/index.test.js
Add a test case for a regression of #1421.
> [test] Improve test coverage of roving tabindex

- docs/src/pages/components/data-grid/editing/editing.md
- docs/src/pages/components/data-grid/filtering/filtering.md
- docs/src/pages/components/data-grid/pagination/pagination.md
- docs/src/pages/components/data-grid/rows/rows.md
> [docs] No ads for commercial license

- packages/x-license/src/verifyLicense.ts
> [license] No need to test the location

- packages/grid/_modules_/grid/components/GridCheckboxRenderer.tsx
- packages/grid/_modules_/grid/components/GridRow.tsx
- packages/grid/_modules_/grid/components/GridRowCount.tsx
- packages/grid/_modules_/grid/components/GridStickyContainer.tsx
- packages/grid/_modules_/grid/components/Watermark.tsx
- packages/grid/_modules_/grid/components/cell/GridCell.tsx
- packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
- packages/grid/_modules_/grid/components/menu/GridMenu.tsx
- packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnsMenuItem.tsx
- packages/grid/_modules_/grid/components/menu/columnMenu/GridFilterMenuItem.tsx
- packages/grid/_modules_/grid/components/menu/columnMenu/HideGridColMenuItem.tsx
- packages/grid/_modules_/grid/components/menu/columnMenu/SortGridMenuItems.tsx
- packages/grid/_modules_/grid/components/toolbar/GridColumnsToolbarButton.tsx
- packages/grid/_modules_/grid/models/colDef/gridCheckboxSelection.tsx
- packages/storybook/src/components/feed-grid.tsx
- packages/storybook/src/components/pricing-grid.tsx
- packages/storybook/src/stories/grid-style.stories.tsx
> [core] Remove React.FC

- packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
- packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
> [DataGrid] Fix delete key for uneditable cells

- packages/grid/_modules_/grid/hooks/root/useGridContainerProps.ts
- packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
> [DataGrid] Fix autoPageSize with small dataset

- docs/src/pages/components/data-grid/selection/DisableClickSelectionGrid.js
- docs/src/pages/components/data-grid/selection/DisableClickSelectionGrid.tsx
- docs/src/pages/components/data-grid/selection/selection.md
Fixes #1406 
Looked important to me to document it correctly as users are not aware of this prop.
Check comments https://github.com/mui-org/material-ui-x/issues/947#issuecomment-783918218, https://github.com/mui-org/material-ui-x/issues/1197#issuecomment-806423439
> [docs] Better document how to disable row selection

- docs/src/pages/components/data-grid/getting-started/getting-started.md
Fix https://github.com/mui-org/material-ui-x/issues/1462
> [docs] Fix Data grid feature comparison

- packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts
I minor optimization looking at the source, it shouldn't have any real impacts.
> [core] Reduce work in data grid

- docs/src/pages/components/data-grid/getting-started/getting-started.md
Fixes #1462 
Preview: https://deploy-preview-1525--material-ui-x.netlify.app/components/data-grid/getting-started/#feature-comparison
> [docs] Fix Feature comparison 404 links

- .mocharc.js
Copy the config we have in the core. This is motivated for fixing https://app.circleci.com/pipelines/github/mui-org/material-ui-x/4369/workflows/174e32d8-2ead-4b8d-a869-1e21271523e8/jobs/20584.
> [test] Increase timeout on jsdom

- packages/grid/_modules_/grid/models/api/gridApi.ts
See https://github.com/microsoft/TypeScript/wiki/Performance#preferring-interfaces-over-intersections
> [core] Improve GridApi type structure

- SECURITY.md
https://github.com/mui-org/material-ui-x/security
**Before**
**After**
> [core] Add security policy

- packages/grid/_modules_/grid/components/cell/GridEditBooleanCell.tsx
- packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx
- packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx
> [DataGrid] Fix broken checkbox in Material-UI v5

- packages/grid/_modules_/grid/locales/deDE.ts
> [DataGrid] Fix deDe localization

- packages/grid/_modules_/grid/models/colDef/checkboxSelection.tsx
> [XGrid] Disable checkbox column resizing

- packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx
- packages/grid/_modules_/grid/utils/utils.ts
> [DataGrid] Fix incorrect date selection

- docs/pages/api-docs/data-grid.md
- docs/pages/api-docs/x-grid.md
- docs/src/pages/components/data-grid/selection/DisableRowSelection.js
- docs/src/pages/components/data-grid/selection/DisableRowSelection.tsx
- docs/src/pages/components/data-grid/selection/selection.md
- packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx
- packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
- packages/grid/_modules_/grid/models/gridOptions.tsx
- packages/grid/data-grid/src/tests/selection.DataGrid.test.tsx
- packages/grid/x-grid/src/tests/selection.XGrid.test.tsx
- packages/storybook/src/stories/grid-selection.stories.tsx
Closes #1434
Preview: https://deploy-preview-1659--material-ui-x.netlify.app/components/data-grid/selection/#disable-selection-on-certain-rows
TODO
> [DataGrid] Add `isRowSelectable` prop

- docs/src/pages/components/data-grid/filtering/BasicFilteringGrid.js
- docs/src/pages/components/data-grid/filtering/BasicFilteringGrid.tsx
- docs/src/pages/components/data-grid/filtering/ColumnTypeFilteringGrid.js
- docs/src/pages/components/data-grid/filtering/ColumnTypeFilteringGrid.tsx
- docs/src/pages/components/data-grid/filtering/CustomRatingOperator.js
- docs/src/pages/components/data-grid/filtering/CustomRatingOperator.tsx
- docs/src/pages/components/data-grid/filtering/FilterOperators.js
- docs/src/pages/components/data-grid/filtering/FilterOperators.tsx
- docs/src/pages/components/data-grid/filtering/filtering.md
- packages/grid/x-grid-data-generator/src/employees.columns.tsx
- packages/grid/x-grid-data-generator/src/services/random-generator.ts
Fixes the documentation part in https://github.com/mui-org/material-ui-x/issues/1118#issuecomment-819500943.
Preview: https://deploy-preview-1671--material-ui-x.netlify.app/components/data-grid/filtering/
> [docs] Improve Filtering page

- test/regressions/TestViewer.js
Implement https://github.com/mui-org/material-ui-x/pull/1691#issuecomment-843088088, it's actually very likely to happen again, and trivial to hedge.
> [test] Catch broken demos

- packages/grid/_modules_/grid/hooks/utils/useResizeContainer.ts
- packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
fix #799 
Preview: https://deploy-preview-1686--material-ui-x.netlify.app/components/data-grid/
> [DataGrid] Improve performance of width resizing

- packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts
- packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
fix #1614 
follow up from https://github.com/mui-org/material-ui-x/issues/1614#issuecomment-841839943
> [DataGrid] Fix rowCount prop updates

- packages/grid/_modules_/grid/locales/deDE.ts
> [DataGrid] Improve deDe translation of "errorOverlayDefaultLabel"

- docs/src/pages/components/data-grid/pagination/pagination.md
Fix the broken link in https://material-ui.com/components/data-grid/pagination/#rendering.
> [docs] Fix 404 link

- .github/dependabot.yml
> [core] Batch updates of storybook

- docs/pages/api-docs/data-grid.md
- docs/pages/api-docs/x-grid.md
- docs/src/pages/components/data-grid/style/StylingAllCells.js
- docs/src/pages/components/data-grid/style/StylingAllCells.tsx
- docs/src/pages/components/data-grid/style/StylingCellsGrid.js
- docs/src/pages/components/data-grid/style/StylingCellsGrid.tsx
- docs/src/pages/components/data-grid/style/StylingHeaderGrid.js
- docs/src/pages/components/data-grid/style/StylingHeaderGrid.tsx
- docs/src/pages/components/data-grid/style/style.md
- packages/grid/_modules_/grid/components/GridViewport.tsx
- packages/grid/_modules_/grid/components/cell/GridCell.tsx
- packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
- packages/grid/_modules_/grid/models/gridCellClass.ts
- packages/grid/_modules_/grid/models/gridOptions.tsx
- packages/grid/data-grid/src/tests/cells.DataGrid.test.tsx
Closes #1626
Preview: https://deploy-preview-1687--material-ui-x.netlify.app/components/data-grid/style/#styling-cells
> [DataGrid] Add `getCellClassName` prop

- docs/pages/api-docs/data-grid.md
- docs/pages/api-docs/x-grid.md
- packages/grid/_modules_/grid/GridComponent.tsx
- packages/grid/_modules_/grid/GridComponentProps.ts
- packages/grid/_modules_/grid/components/containers/GridRoot.tsx
- packages/grid/_modules_/grid/constants/localeTextConstants.ts
- packages/grid/_modules_/grid/locales/bgBG.ts
- packages/grid/_modules_/grid/locales/deDE.ts
- packages/grid/_modules_/grid/locales/elGR.ts
- packages/grid/_modules_/grid/locales/esES.ts
- packages/grid/_modules_/grid/locales/frFR.ts
- packages/grid/_modules_/grid/locales/jaJP.ts
- packages/grid/_modules_/grid/locales/nlNL.ts
- packages/grid/_modules_/grid/locales/plPL.ts
- packages/grid/_modules_/grid/locales/ptBR.ts
- packages/grid/_modules_/grid/locales/skSK.ts
- packages/grid/_modules_/grid/locales/trTR.ts
- packages/grid/_modules_/grid/locales/ukUA.ts
- packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
> [DataGrid] Add customisable `aria-label`, `aria-labelledby` field

- docs/src/pages/components/data-grid/editing/RenderRatingEditCellGrid.js
- docs/src/pages/components/data-grid/editing/RenderRatingEditCellGrid.tsx
Fix the root cause of #1658. The rationale is explained in https://github.com/mui-org/material-ui-x/issues/1658#issuecomment-841328114.
> [docs] Improve Custom edit component demo

- packages/grid/_modules_/grid/components/toolbar/GridToolbarExport.tsx
Fixes #1866
Hi @oliviertassinari! How does this look?
Let me know if this needs any changes! thanks
> [DataGrid] Fix aria-label grid toolbar export

- packages/grid/_modules_/grid/locales/frFR.ts
Fixed a bad copy/paste on filterOperatorOnOrBefore.
> [DataGrid] Fix typo frFR locale

- packages/grid/_modules_/grid/models/gridOptions.tsx
A follow-up on https://github.com/mui-org/material-ui-x/pull/1856#event-4863752387. The API pages will ultimately be generated from the JSDoc.
> [docs] Polish disableDensitySelector description

- packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
- packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
Fixes #1857 
Solution from https://github.com/mui-org/material-ui-x/issues/1857#issuecomment-857054361
https://deploy-preview-1899--material-ui-x.netlify.app/components/data-grid/
> [DataGrid] Escape regular expression characters in filters

- docs/src/pages/components/data-grid/editing/StartEditButtonGrid.js
- docs/src/pages/components/data-grid/editing/StartEditButtonGrid.tsx
Noticed working on #1772 (when rendering the JS demo)
> [docs] Fix prop-type warning

- packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
The pipeline broke after the merge of #1872.
> [test] Fix tests

- packages/grid/_modules_/grid/components/GridStickyContainer.tsx
- packages/grid/_modules_/grid/hooks/root/useGridContainerProps.ts
- packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
- packages/storybook/src/stories/grid-rendering.stories.tsx
Add a test case for https://github.com/mui-org/material-ui-x/pull/1831#issuecomment-863122707. We could have easily missed it. I have added a visual and function test base the functional test is flaky to catch the issue. The order of resolution between the two effects varies.
> [test] Test vertical scrollbar

- packages/grid/_modules_/grid/hooks/features/columnReorder/useGridColumnReorder.tsx
- packages/grid/x-grid/src/tests/reorder.XGrid.test.tsx
- test/e2e/fixtures/DataGrid/ColumnReorder.tsx
- test/e2e/index.test.ts
Fixes #1579
Fixes #1762 
Preview https://deploy-preview-1952--material-ui-x.netlify.app/components/data-grid/demo/
> [DataGrid] Ignore drag events when disableColumnReorder is true

- packages/grid/_modules_/grid/models/colDef/gridNumericColDef.ts
- packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts
- packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
A reproduction:
1. Open https://codesandbox.io/s/material-demo-forked-3vkgp?file=/demo.js
2. Edit one cell with the age
3. Log the rows
#1955 spark me the idea to fix it.
> [DataGrid] Fix number edit cell output

- .github/workflows/issue-mark-duplicate.yml
Mostly interested in https://github.com/actions-cool/issues-helper/blob/afb2d0f2e50aefc5f85343883a8084307351f125/src/base.js#L221
> [core] Upgrade actions-cool/issues-helper

- docs/src/pages/components/data-grid/demo/FullFeaturedDemo.js
- docs/src/pages/components/data-grid/demo/FullFeaturedDemo.tsx
Changing the dataset in https://material-ui.com/components/data-grid/demo/ from Employee to Commodity is not working.
Preview: https://deploy-preview-1965--material-ui-x.netlify.app/components/data-grid/demo/
> [docs] Fix changing Dataset not working

- packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
- packages/storybook/src/stories/grid-filter.stories.tsx
~Fix #1709~
~Let me know if this solution works and is fine.~
~Existing: https://material-ui.com/components/data-grid/#commercial-version After improvement: https://deploy-preview-1760--material-ui-x.netlify.app/components/data-grid/#commercial-version~
> [core] Polish filtering internals

- packages/grid/_modules_/grid/utils/getGridLocalization.ts
Fixes #1993 
Before: https://codesandbox.io/s/material-demo-forked-iml3y?file=/demo.js
After: https://codesandbox.io/s/material-demo-forked-499wt?file=/demo.js
> [DataGrid] Add fallback for pagination translations

- packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx
- packages/grid/_modules_/grid/constants/localeTextConstants.ts
- packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts
- packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
- packages/grid/_modules_/grid/locales/bgBG.ts
- packages/grid/_modules_/grid/locales/csCZ.ts
- packages/grid/_modules_/grid/locales/deDE.ts
- packages/grid/_modules_/grid/locales/elGR.ts
- packages/grid/_modules_/grid/locales/esES.ts
- packages/grid/_modules_/grid/locales/frFR.ts
- packages/grid/_modules_/grid/locales/itIT.ts
- packages/grid/_modules_/grid/locales/jaJP.ts
- packages/grid/_modules_/grid/locales/nlNL.ts
- packages/grid/_modules_/grid/locales/plPL.ts
- packages/grid/_modules_/grid/locales/ptBR.ts
- packages/grid/_modules_/grid/locales/ruRU.ts
- packages/grid/_modules_/grid/locales/skSK.ts
- packages/grid/_modules_/grid/locales/trTR.ts
- packages/grid/_modules_/grid/locales/ukUA.ts
- packages/grid/_modules_/grid/models/colDef/gridBooleanOperators.ts
- packages/grid/_modules_/grid/models/colDef/gridDateOperators.ts
- packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts
- packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
- packages/grid/_modules_/grid/models/gridFilterOperator.ts
- packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
- packages/storybook/src/stories/grid-filter.stories.tsx
Closes #1165 
Closes #1961
Preview: https://deploy-preview-1997--material-ui-x.netlify.app/storybook/?path=/story/x-grid-tests-filter--commodity-with-empty-cells&globals=measureEnabled:false
> [DataGrid] Add "is empty" and "is not empty" operators

- docs/src/pages/components/data-grid/pagination/CursorPaginationGrid.js
- docs/src/pages/components/data-grid/pagination/CursorPaginationGrid.tsx
- docs/src/pages/components/data-grid/pagination/pagination.md
Closes #1906 
Preview: https://deploy-preview-1991--material-ui-x.netlify.app/components/data-grid/pagination/#cursor-based-pagination
> [docs] Add new cursor-based pagination paragraph

- package.json
- packages/storybook/package.json
- yarn.lock
> [core] Remove styled-components

- docs/src/pages/components/data-grid/getting-started/getting-started.md
Preview: https://deploy-preview-2036--material-ui-x.netlify.app/components/data-grid/getting-started/#license-key-installation
Try to solve this pain point:
```
Hi,
my company, XXX, just bought PRO licences of MaterialUI.
We received an email with the key and an expiry date in one year.
As developers we need to know how to integrate this key in our apps but we do not know what will occur in one year if we strictly follow the instructions in the "licence key installation" documentation.
Can you please elaborate on what will occur so that we can elaborate a strategy to integrate the key in pour apps.
Thanks.
```
They had already found https://material-ui.com/components/data-grid/getting-started/#license-key-installation
> [docs] Better explain what happens in the future

- packages/grid/_modules_/grid/components/cell/GridEditDateCell.tsx
- packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx
- packages/grid/_modules_/grid/models/colDef/gridDateColDef.ts
- packages/grid/_modules_/grid/utils/utils.ts
- packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
Fixes #1920
Preview: https://deploy-preview-2051--material-ui-x.netlify.app/components/data-grid/editing/
The TODO comments can be addressed once #1955 is merged.
> [DataGrid] Fix manual entry in date fields

- packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx
> [XGrid] Column sorting in GridPanel is experimental 

- docs/package.json
- yarn.lock
Remove some of the changes of #2069. We don't need to pin
> [core] No need to pin dependencies

- .gitignore
- packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts
- packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
- test/utils/helperFn.ts
> [DataGrid] Emit `GRID_PAGE_SIZE_CHANGE` when autoPageSize is set and the grid size changes

- packages/grid/_modules_/grid/utils/domUtils.ts
- packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
Fixes #1953 
Hey @oliviertassinari! How does this look?
Let me know if this needs any changes! Thanks
> [DataGrid] Fix crash when id has a single-quote

- packages/grid/_modules_/grid/components/toolbar/GridToolbarColumnsButton.tsx
- packages/grid/_modules_/grid/components/toolbar/GridToolbarDensitySelector.tsx
- packages/grid/_modules_/grid/components/toolbar/GridToolbarExport.tsx
- packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx
> [DataGrid] Make GridToolbarXXX props overridable

- docs/scripts/buildApi.ts
- yarn.lock
Sync with the latest commit of the HEAD in the core repo. It's good to do it every few weeks, to keep the feedback loop short and benefit from the latest improvements.
> [core] Upgrade dependencies

- yarn.lock
Use the fix https://github.com/mui-org/material-ui/pull/27262 of @m4theushw in to fix:
> [docs] Fix broken env

- packages/grid/x-grid-data-generator/src/renderer/renderEditProgress.tsx
Fixes #2163 
Part of this bug is already fixed in #2012
> [docs] Replace fade with muiStyleAlpha

- packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx
As requested in https://github.com/mui-org/material-ui-x/pull/2084#discussion_r670349564
> [DataGrid] Improve GridToolbarXXX props flexibility

- docs/src/pages/components/data-grid/filtering/QuickFilteringGrid.js
- docs/src/pages/components/data-grid/filtering/QuickFilteringGrid.tsx
- docs/src/pages/components/data-grid/filtering/filtering.md
- packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
- packages/grid/_modules_/grid/utils/utils.ts
closes #2037 
Preview: https://deploy-preview-2149--material-ui-x.netlify.app/components/data-grid/filtering/#quick-filter
> [DataGrid] Add quick filter demo

- packages/grid/data-grid/src/DataGrid.tsx
- packages/grid/data-grid/src/tests/selection.DataGrid.test.tsx
Fixes #2193 
Preview: https://codesandbox.io/s/material-demo-n3l5c
> [DataGrid] Fix `Controlled selection` console error

- packages/grid/_modules_/grid/components/cell/GridEditBooleanCell.tsx
- packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
Fixes #2206 
Preview: https://deploy-preview-2215--material-ui-x.netlify.app/components/data-grid/demo/
> [DataGrid] Fix id passed to setEditCellValue

- packages/grid/_modules_/grid/locales/trTR.ts
- Missing translations are added.
- Redundant conditions are removed.
> [DataGrid] Improve translations to the Turkish locale

- renovate.json
Update packages as soon as an in-range new version is available (instead of waiting for our of range updates), see https://github.com/mui-org/material-ui/pull/27455
> [core] Receive patch and minor dependency updates

- packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
- packages/grid/x-grid/src/tests/layout.XGrid.test.tsx
Two more test cases to prevent a possible regression in https://github.com/mui-org/material-ui-x/pull/2176#issuecomment-888312648.
> [test] Test support for theme translations

- packages/grid/x-grid/src/tests/columns.XGrid.test.tsx
> [core] Add tests for column resizing

- packages/grid/_modules_/grid/components/GridRenderingZone.tsx
- packages/grid/_modules_/grid/components/containers/GridDataContainer.tsx
- packages/grid/_modules_/grid/hooks/root/useGridContainerProps.ts
- packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
- packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
Fixes #2133 
Preview: https://deploy-preview-2159--material-ui-x.netlify.app/components/data-grid/components/
> [DataGrid] Add minHeight to the rendering zone

- packages/grid/_modules_/grid/hooks/features/export/serializers/csvSerializer.ts
- packages/grid/x-grid/src/tests/export.XGrid.test.tsx
Closes #2156 
CSV export does not work when row ID are numbers and some rows are selected
> [DataGrid] Fix CSV export when selected row id is number

- packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
- packages/grid/_modules_/grid/models/gridOptions.tsx
https://github.com/mui-org/material-ui-x/pull/2246#issuecomment-890365505
> [DataGrid] Remove default value of columnTypes prop

- packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
- packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
- packages/storybook/src/stories/grid-columns.stories.tsx
> [DataGrid] Allow non-integer column width for flex columns

- docs/src/pages/components/data-grid/getting-started/getting-started.md
- packages/grid/data-grid/package.json
- packages/grid/x-grid/package.json
Related to #2238 
@material-ui/styles 4.9.10 is the version required by @material-ui/core 4.9.12.
> [DataGrid] Add @material-ui/styles as peer dependency

- CHANGELOG.md
Act on https://github.com/mui-org/material-ui-x/pull/2233#issuecomment-894646815
> [CHANGELOG] Make it easier to follow

- docs/src/pages/components/data-grid/localization/localization.md
- packages/grid/_modules_/grid/locales/arSD.ts
- packages/grid/_modules_/grid/locales/index.ts
> [DataGrid] Add Sudanese Arabic (arSD) locale

- packages/grid/_modules_/grid/models/colDef/gridBooleanOperators.ts
- packages/grid/_modules_/grid/models/colDef/gridDateOperators.ts
- packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts
- packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
- packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
Closes #1165 
Do we want to also handle it for boolean cells ?
> [DataGrid] Add isEmpty and isNotEmpty filter operators for date and number columns

- packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
- packages/grid/x-grid/src/tests/columns.XGrid.test.tsx
- packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
- packages/grid/x-grid/src/tests/state.XGrid.test.tsx
*I'm too lazy to explain why, waiting for somebody to ask.*
> [test] Use .not.to.equal on assertions

- packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts
- packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx
See https://github.com/mui-org/material-ui-x/pull/2279/files#r688988720 for why. I didn't add a test case, but if somebody want to, please go ahead.
> [DataGrid] Fix keyboard navigation header regression

- packages/grid/_modules_/grid/hooks/features/columnResize/useGridColumnResize.tsx
Based on this comment https://github.com/mui-org/material-ui/pull/27724#issuecomment-898614730
> [core] Update `doesSupportTouchActionNone` implementation using `CSS.supports`

- docs/public/_redirects
https://github.com/mui-org/material-ui-x/pull/2382#issuecomment-901806951
Preview: https://deploy-preview-2389--material-ui-x.netlify.app/api/data-grid/x-grid/
> [docs] Add redirect from XGrid to DataGridPro

- packages/grid/_modules_/grid/components/GridFooter.tsx
- packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
I'll automerge this one
- `apiRef` is never null
- React element are camel cased
> [core] Small fixes

- docs/public/_redirects
- docs/src/pages/components/data-grid/export/export.md
- docs/src/pages/components/data-grid/overview/overview.md
TODO
We receive a weekly summary of the SEO ranking of some of the important SEO queries. This week, we lost one place in the [SERP for "react data grid"](https://analytics.moz.com/pro/analytics/analyze-keyword/15825137/2462013/28a898d7b6ef4f3f29721681e42a8b21). Diving a bit into how we could improve it:
It seems that we had no exact match. The changes in this PR fixes `Exact Keyword Used in Document at Least Once` and `Keywords in the Meta Description`.
---
Regarding `Use Keywords in your URL`, I have mentioned the potential to move from
https://material-ui.com/components/data-grid/ to https://mui.com/react/data-grid/  in [Notion](https://www.notion.so/mui-org/Sitemap-and-URL-structure-rearrange-ca604f628c17438db2d987961fcb8ffe). It's shorter and clearer, it seems to be two clear wins …
> [docs] Improve SEO ranking

- .github/ISSUE_TEMPLATE/1.bug.yml
- .github/ISSUE_TEMPLATE/2.feature.yml
- .github/ISSUE_TEMPLATE/3.pro-support.yml
A follow-up on #2468, based on https://github.com/mui-org/material-ui/pull/28038
> [core] Polish issue template

- packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts
- packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
> [DataGrid] The numeric filter operators are not handling '0' correctly

- .circleci/config.yml
- test/karma.conf.js
See https://github.com/mui-org/material-ui/pull/28041
https://app.circleci.com/pipelines/github/mui-org/material-ui-x/7489/workflows/da42dead-9bbc-44e4-b8ef-6d9319c9ed82/jobs/41123
Working fine
> [test] Disable browserstack for PRs

- packages/x-license/LICENSE.md
The license is for MUI X Pro, not MUI X.
> [docs] Clarify confusion

- packages/grid/_modules_/grid/components/containers/GridToolbarContainer.tsx
- test/e2e/fixtures/DataGrid/SelectEditCell.tsx
- test/utils/index.tsx
- test/utils/licenseRelease.ts
#2462 was merged containing the old imports.
> [core] Replace remaining @material-ui usages

- docs/package.json
- docs/pages/index.js
- docs/src/pages.js
- package.json
- yarn.lock
Open https://mui.com/api/data-grid/data-grid-pro/, try to search for XGrid => no results. There was a bug in the Algolia search, @siriwatknp fixed it.
> [docs] Fix Algolia search

- docs/pages/api-docs/data-grid/data-grid-pro.md
- docs/src/pages/components/data-grid/export/export.md
Open https://mui.com/api/css-baseline/ and search for XGrid, not very helpful. This should fix https://twitter.com/CarlosNeisa1/status/1439641133320179714
> [docs] Make sure the seach results are helpful

- packages/grid/_modules_/grid/locales/itIT.ts
Add some missing localized strings
> [DataGrid] Fix Italian localization

- docs/src/pages/components/data-grid/columns/ColumnTypesGrid.js
- docs/src/pages/components/data-grid/columns/ColumnTypesGrid.tsx
> [docs] Fix demo throwing error

- docs/pages/api-docs/data-grid/data-grid-pro.md
- docs/pages/api-docs/data-grid/data-grid.md
- docs/pages/api-docs/data-grid/grid-scroll-api.json
- docs/scripts/buildApi.ts
- docs/src/pages/components/data-grid/virtualization/VirtualizationApiNoSnap.js
- docs/src/pages/components/data-grid/virtualization/virtualization.md
- packages/grid/_modules_/grid/hooks/features/index.ts
- packages/grid/_modules_/grid/hooks/features/scroll/index.ts
- packages/grid/_modules_/grid/hooks/features/scroll/useGridScroll.ts
- packages/grid/_modules_/grid/hooks/features/virtualization/index.ts
- packages/grid/_modules_/grid/hooks/features/virtualization/useGridNoVirtualization.ts
- packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualization.ts
- packages/grid/_modules_/grid/hooks/root/useGridContainerProps.ts
- packages/grid/_modules_/grid/hooks/utils/useGridScrollFn.ts
- packages/grid/_modules_/grid/models/api/gridApi.ts
- packages/grid/_modules_/grid/models/api/gridScrollApi.ts
- packages/grid/_modules_/grid/models/api/gridVirtualizationApi.ts
- packages/grid/_modules_/grid/models/api/index.ts
- packages/grid/_modules_/grid/models/gridOptions.tsx
- packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx
- packages/grid/data-grid/src/useDataGridComponent.tsx
- packages/grid/x-grid/src/tests/rows.DataGridPro.test.tsx
- packages/grid/x-grid/src/useDataGridProComponent.tsx
- packages/storybook/src/stories/grid-rows.stories.tsx
> [DataGrid] Add `disableVirtualization` prop (#2326)

- packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts
- packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx
> [DataGrid] Fix navigation between column headers with rows filtered

- docs/pages/api-docs/data-grid/data-grid-pro.md
- packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx
- packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
- packages/grid/_modules_/grid/models/gridOptions.tsx
- packages/grid/data-grid/src/DataGrid.tsx
- packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
- packages/grid/data-grid/src/tests/selection.DataGrid.test.tsx
- packages/grid/x-grid/src/DataGridPro.tsx
- packages/grid/x-grid/src/tests/selection.DataGridPro.test.tsx
- test/utils/helperFn.ts
Cherry-picks 02f93918 and 4b557d22
> [DataGridPro] Only apply checkboxSelectionVisibleOnly when pagination is enabled

- packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterInputValue.tsx
- packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
> [DataGrid] Fix `undefined` in filter panel

- packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaders.tsx
- packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeadersItemCollection.tsx
- packages/grid/_modules_/grid/constants/eventsConstants.ts
> [core] Stop using selector for pro features on React components

- packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts
- packages/grid/_modules_/grid/models/params/gridCellParams.ts
- packages/grid/data-grid/src/tests/cells.DataGrid.test.tsx
Closes #2684 
See https://github.com/mui-org/material-ui-x/issues/2684#issuecomment-926917130
> [DataGrid] Pass row id to `valueFormatter`

- packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
- packages/grid/x-grid/src/tests/sorting.DataGridPro.test.tsx
> [DataGrid] onSortModelChange should not been called on initialization and on prop model change

- docs/pages/components/data-grid/scrolling.js
- docs/src/pages.js
- docs/src/pages/components/data-grid/scrolling/ScrollApiNoSnap.js
- docs/src/pages/components/data-grid/scrolling/ScrollPlayground.js
- docs/src/pages/components/data-grid/scrolling/ScrollPlayground.tsx
- docs/src/pages/components/data-grid/scrolling/scrolling.md
See https://github.com/mui-org/material-ui-x/pull/2326#discussion_r689522393 for context.
Preview: https://deploy-preview-2634--material-ui-x.netlify.app/components/data-grid/scrolling/
> [docs] Add page for scrolling API

- docs/src/pages/components/data-grid/localization/localization.md
- packages/grid/_modules_/grid/locales/heIL.ts
- packages/grid/_modules_/grid/locales/index.ts
- scripts/exportsSnapshot.json
Hi,
I added localization for the DataGrid. I followed the instructions on Mui site:
https://mui.com/components/data-grid/localization/#locale-text
> [DataGrid] Add hebrew localization (he-IL)

- packages/grid/data-grid/LICENSE
- packages/grid/x-grid-data-generator/LICENSE
Apply https://github.com/mui-org/material-ui-x/pull/2676/files#r720686645
> [DataGrid] Revert year change in the MIT license

- docs/tsconfig.json
- yarn.lock
> [core] Upgrade monorepo

- README.md
- scripts/exportsSnapshot.json
> [core] Invert Codesandbox examples on README

- packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts
- packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
> [DataGrid] Fix filtering of nullish numeric cells

- docs/src/pages/components/data-grid/editing/editing.md
I got confused when reading the sentence. I thought we had a section about validation, but no.
> [docs] Fix the client-side validation link clarity

- packages/grid/x-data-grid-pro/package.json
- packages/grid/x-data-grid/package.json
- yarn.lock
Reverts mui-org/material-ui-x#3109
It broke the build: https://github.com/reduxjs/reselect/issues/543
> Revert "Bump reselect to ^4.1.2"

- test/e2e/index.test.ts
Another attempt to fix `test:e2e`.
> [test] Use interval for `waitFor` in test:e2e

- .gitignore
- docs/pages/playground.example.tsx
- docs/pages/playground.tsx
A new tradeoff, if you want to use the playground, you can copy the example file. I hope it will help more people 😁 
I was previously using Next.js's page over Storybook simply because I felt that I could go from a problem to trying a change out a lot faster (spoiler alert, I hate the DX in Storybook). With https://www.youtube.com/watch?v=dMBYI7pTR4Q&t=517s, this seems to be even better now.
---
On the topic of productivity, I'm upgrading my laptop with an M1 chip, it seems to be 100% faster on a single-core benchmark, even with the MacBook Air 13" of 2020 compared to my current MacBook Pro 13" of 2019.
> [core] Improve playground

- packages/grid/rollup.x-data-grid.config.js
> [DataGrid] Fix the `@mui/x-data-grid` type entrypoint

- CHANGELOG.md
- Link the blog post
- "here" is not a helpful link text. I have used the opportunity to improve this page: https://www.notion.so/mui-org/Technical-documentation-7e55b517ac2e489a9ddb6d0f6dd765de.
- Fix git diff formating
> [CHANGELOG] Polish v5

- packages/grid/_modules_/grid/locales/elGR.ts
Add translation for missing locale strings.
> [DataGrid] Update elGR locale

- packages/grid/_modules_/grid/hooks/features/columnHeaders/useGridColumnHeaders.tsx
> [DataGrid] Do not skip column header renderContext update when the column to render have changed

- packages/grid/_modules_/grid/locales/koKR.ts
I believe `/` is the best translation. #3211
> [l10n] Improve ko_KR locale

- docs/src/pages/components/data-grid/columns/columns.md
- docs/src/pages/components/data-grid/getting-started/getting-started.md
- docs/src/pages/components/data-grid/rows/rows.md
A follow-up on https://github.com/mui-org/material-ui-x/issues/2795#issuecomment-966721303
> [docs] Include row pinning

- packages/grid/_modules_/grid/locales/ruRU.ts
> [l10n] Improve Update ruRU locale

- scripts/README.md
> [docs] Update branch to deploy docs

- docs/src/pages/components/data-grid/localization/localization.md
Done at the same time as https://github.com/mui-org/material-ui/pull/30040
> [docs] Avoid 301 links

- package.json
> [core] Fix yarn prettier script

- CHANGELOG.md
I wrote the wrong month in #3312. 🙊
> [core] Fix release month in CHANGELOG

- yarn.lock
Fixes the tests by applying https://github.com/mui-org/material-ui/pull/29556/files#diff-f586e02f621d51853745b9353a884a736c8d52d343f40d15a1d3c32a4c8dc24bR355-R362
> [core] Update monorepo

- docs/src/pages/components/data-grid/overview/overview.md
"column pinning" was in the "Features" and "Upcoming features" lists
> [docs] Remove column pinning from "Upcoming features"

- packages/grid/_modules_/grid/locales/itIT.ts
This PR adds the missing column pinning translations for the Italian (it-IT) locale.
> [l10n] Improve Italian (it-IT) locale

- packages/grid/_modules_/grid/components/GridRow.tsx
- packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx
- packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx
- packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx
Fix #3397
@m4theushw I copied your tests from #3455 to be sure the bug is corrected
> [DataGrid] Fix scrolling bug when an action is focused

- docs/src/pages/components/data-grid/editing/FullFeaturedCrudGrid.js
- docs/src/pages/components/data-grid/editing/FullFeaturedCrudGrid.tsx
- docs/src/pages/components/data-grid/editing/RenderRatingEditCellGrid.js
- docs/src/pages/components/data-grid/editing/RenderRatingEditCellGrid.tsx
- docs/src/pages/components/data-grid/editing/StartEditButtonGrid.js
- docs/src/pages/components/data-grid/editing/StartEditButtonGrid.tsx
> [docs] Make demos compatible with `preProcessEditCellProps`

- packages/grid/_modules_/grid/locales/viVN.ts
I add additional text for vi-VN locale
> [l10n] Improve Vietnamese (viVN) locale

- packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx
- packages/grid/x-data-grid-pro/src/tests/editRows.DataGridPro.test.tsx
Fixes #3478
Preview: https://deploy-preview-3491--material-ui-x.netlify.app/components/data-grid/demo/
> [DataGrid] Fix can't enter 0 on numeric column

- packages/grid/_modules_/grid/hooks/features/focus/useGridFocus.ts
- packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx
> [DataGrid] Avoid rerender when pressing key inside already focused cell

- yarn.lock
I can't help myself when seeing 😁
> [core] Update dependency on the core

- docs/pages/api-docs/data-grid/data-grid-pro.json
- docs/pages/api-docs/data-grid/data-grid.json
- docs/translations/api-docs/data-grid/data-grid-pro-pt.json
- docs/translations/api-docs/data-grid/data-grid-pro-zh.json
- docs/translations/api-docs/data-grid/data-grid-pro.json
- docs/translations/api-docs/data-grid/data-grid-pt.json
- docs/translations/api-docs/data-grid/data-grid-zh.json
- docs/translations/api-docs/data-grid/data-grid.json
- packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
- packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderSeparator.tsx
- packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
- packages/grid/_modules_/grid/gridClasses.ts
- packages/grid/_modules_/grid/hooks/features/columnResize/useGridColumnResize.tsx
- packages/grid/x-data-grid-pro/src/DataGridProColumnHeaders.tsx
- packages/grid/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx
- packages/grid/x-data-grid-pro/src/tests/columns.DataGridPro.test.tsx
- scripts/x-data-grid-pro.exports.json
- scripts/x-data-grid.exports.json
Closes #3395 
Preview: https://deploy-preview-3502--material-ui-x.netlify.app/components/data-grid/columns/#column-pinning
> [DataGridPro] Fix resizing of right pinned columns

- packages/grid/_modules_/grid/locales/fiFI.ts
> [l10n] Improve Finnish (fiFI) locale

- docs/src/pages/components/data-grid/overview/overview.md
Closes #3605
https://deploy-preview-3606--material-ui-x.netlify.app/components/data-grid/
> [docs] Include header badges as in the other components

- packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx
- packages/grid/x-data-grid-pro/src/tests/editRows.DataGridPro.test.tsx
- packages/grid/x-data-grid-pro/src/tests/events.DataGridPro.test.tsx
Related to https://github.com/mui-org/material-ui-x/issues/3480#issuecomment-997914367
> [DataGrid] Add debounce to text input

- benchmark/browser/README.md
- benchmark/browser/scripts/benchmark.js
- docs/src/pages/components/data-grid/rows/InfiniteLoadingGrid.js
- docs/src/pages/components/data-grid/rows/InfiniteLoadingGrid.tsx
- test/utils/helperFn.ts
So we get a comparison point the next time we run the script. Regarding the measure itself, I'm not so convinced about how it correlates with UX performance, but this is another discussion.
> [benchmark] Log the output of the script

- packages/grid/_modules_/grid/locales/csCZ.ts
- packages/grid/_modules_/grid/locales/skSK.ts
Updated csCZ and skSK locales with new keys
> [DataGrid] csCZ and skSK locale update

- test/regressions/index.test.js
> [test] Improve test detection

- docs/src/pages/components/data-grid/columns/columns.md
> [docs] Fix typo in column visibility example

- CHANGELOG.md
Fixes https://github.com/mui-org/material-ui-x/pull/3682#discussion_r790927168
I'll update the release page as well
> [docs] Improve v5.3.0 release notes

- packages/grid/_modules_/grid/locales/frFR.ts
Not fan of the `tous`, if you have a better suggestion
> [l10n] Improve French (frFR) locale

- packages/grid/_modules_/grid/locales/csCZ.ts
> [core] Fix `l10n` script not updating csCZ locale

- packages/grid/x-data-grid/src/tests/cells.DataGrid.test.tsx
The CI broke after the merge of #3486.
> [test] Skip test on Firefox

- packages/grid/x-data-grid/src/tests/components.DataGrid.test.tsx
I forgot to remove one last @ts-expect-error when merging #3663
> [test] Remove last @ts-expect-error

- .github/ISSUE_TEMPLATE/3.pro-support.yml
- docs/src/pages/components/data-grid/getting-started/getting-started.md
https://deploy-preview-3530--material-ui-x.netlify.app/components/data-grid/getting-started/#support
To make it clearer.
> [docs] Update to the kind of support provided

- packages/grid/_modules_/grid/locales/heIL.ts
> [I10n] Improve Hebrew (he-IL) locale

- packages/grid/_modules_/grid/locales/trTR.ts
Based on https://github.com/mui-org/material-ui-x/issues/3838#issuecomment-1029895942
> [l10n] Improve tr-TR locale

- .circleci/config.yml
- codecov.yml
Related to #37
https://app.codecov.io/gh/mui/mui-x/commit/26fd73efa9b5a22b1def94a09ff41e3eecadd659
> [test] Add codecov

- packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx
- packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx
Fixes #2998 
Preview: https://deploy-preview-3835--material-ui-x.netlify.app/components/data-grid/demo/
> [DataGrid] Stop checkbox ripple on blur

- docs/data/data-grid/filtering/CustomSelectionOperator.js
- docs/data/data-grid/filtering/CustomSelectionOperator.tsx
- docs/data/data-grid/filtering/CustomSelectionOperator.tsx.preview
- docs/data/data-grid/filtering/filtering.md
Part of #3895
I took the example of #3895 but if you have a better idea of how we can document how to re-use built in operators to add custom behavior.
> [docs] Add example of custom filtering operator based on built-in ones

- docs/data/data-grid/export/export.md
- docs/data/data-grid/rows/rows.md
- docs/data/data-grid/scrolling/scrolling.md
> [docs] Fix 301

- package.json
- scripts/l10n.ts
- yarn.lock
I add @octokit/plugin-retry as encouraged by GitHub 
> Many common request errors can be easily remediated by retrying the request
https://octokit.github.io/rest.js/v18#automatic-retries
> [core] Retry l10n CI if 502 returned

- docs/data/data-grid/virtualization/ColumnVirtualizationGrid.js
- docs/data/data-grid/virtualization/ColumnVirtualizationGrid.tsx
That's the last occurrence I found of a column "id" with hidden parameter
> [docs] Remove useless hide id column

- docs/src/pages/components/data-grid/getting-started/getting-started.md
- packages/grid/data-grid/README.md
- packages/grid/x-grid/README.md
Act on https://mui.zendesk.com/agent/tickets/2486, so the packages installed are correct. https://v4.mui.com/components/data-grid/getting-started/#installation. This change is marginal, It brings almost no value, but it doesn't harm 😅
> [docs] Ensure correct npm install version on v4

- packages/storybook/src/stories/grid-filter.stories.tsx
Add screenshot such that Argos can catch the following regression:
- https://github.com/mui/mui-x/pull/4069#discussion_r817547492
- https://github.com/mui/mui-x/pull/3915#pullrequestreview-885905172
> [test] Add screenshot of the filter panel

- packages/grid/x-data-grid-pro/src/tests/cellEditing.DataGridPro.test.tsx
- packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx
Follow up of https://github.com/mui/mui-x/pull/3624#discussion_r817668116
> [test] Only test custom input keyboard event in edit mode

- test/e2e-website/data-grid-new.spec.ts
I'm working on a new search experience that could break the e2e-test-website CI in other PRs.
> [docs] Neglect e2e tests related to search

- packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts
- packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx
> [DataGrid] Fix extending built-in column types

- docs/pages/api-docs/data-grid/data-grid-pro.json
- docs/pages/api-docs/data-grid/data-grid.json
- docs/pages/x/api/data-grid/data-grid-pro.json
- docs/pages/x/api/data-grid/data-grid.json
- docs/translations/api-docs/data-grid/data-grid-pro-pt.json
- docs/translations/api-docs/data-grid/data-grid-pro-zh.json
- docs/translations/api-docs/data-grid/data-grid-pro.json
- docs/translations/api-docs/data-grid/data-grid-pt.json
- docs/translations/api-docs/data-grid/data-grid-zh.json
- docs/translations/api-docs/data-grid/data-grid.json
- packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx
- packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts
- packages/grid/x-data-grid/src/constants/gridClasses.ts
> [DataGrid] Display column's filter icon if a filter is applied

- test/utils/createDOM.js
- test/utils/setup.js
- yarn.lock
Mainly to have https://github.com/mui/material-ui/pull/31275 in our docs as well
Preview: https://deploy-preview-4149--material-ui-x.netlify.app/components/data-grid/
> [core] Upgrade `@mui/monorepo`

- docs/data/data-grid/editing/ValidateRowModelControlGrid.js
- docs/data/data-grid/editing/ValidateRowModelControlGrid.tsx
- docs/data/data-grid/editing/ValidateRowModelControlGrid.tsx.preview
- Add type to `preProcessEditCellProps`
- define `columns`/`rows` before using them
> [docs] Clean ValidateRowModelControlGrid demo

- packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaders.tsx
- packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts
Fix #4187 
Preview: https://codesandbox.io/s/datagridpro-v5-quick-start-forked-nge3q3?file=/src/App.tsx:1253-1257
> [DataGridPro] Fix pinned columns edge overflow with custom borderRadius

- packages/grid/x-data-grid/src/locales/arSD.ts
Previsous transation was not completed and was full of errors.  I hope you accept this PR. this is a much cleaner translation, accurate and full transaliton.
> [l10n] Improve ar-SD translations

- docs/data/data-grid/group-pivot/RowGroupingControlled.js
- docs/data/data-grid/group-pivot/RowGroupingControlled.tsx
- docs/data/data-grid/group-pivot/RowGroupingControlled.tsx.preview
- docs/data/data-grid/group-pivot/RowGroupingInitialState.js
- docs/data/data-grid/group-pivot/RowGroupingInitialState.tsx
- docs/data/data-grid/group-pivot/RowGroupingInitialState.tsx.preview
- docs/data/data-grid/state/UseGridSelector.js
- docs/data/data-grid/state/UseGridSelector.tsx
- docs/data/data-grid/state/UseGridSelector.tsx.preview
> [docs] Remove useless `apiRef` from demos

- packages/grid/x-data-grid/src/locales/faIR.ts
Farsi (Persian) is my native language, and I'm glad to help to improve this package :)
> [l10n] Improve Persian (fa-IR) locale

- docs/data/data-grid/editing/editing.md
Found on [ahrefs](https://app.ahrefs.com/site-audit/2944028/41/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CcontentType%2Cdepth%2ClinksInternal4xx%2ClinksInternal5xx%2ClinksCountInternal4xx%2ClinksCountInternal5xx%2ClinksExternal4xx%2ClinksExternal5xx%2ClinksCountExternal4xx%2ClinksCountExternal5xx&filterCollapsed=true&filterId=2ba916be8a15982c0bb9bdae70ab1991&issueId=c64daf06-d0f4-11e7-8ed1-001e67ed4656&udUrl=https%3A%2F%2Fmui.com%2Fx%2Freact-data-grid%2Fediting%2F) audit
> [docs] Fix wrong url

- packages/x-date-pickers/src/LocalizationProvider/index.ts
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
> [pickers] Export MuiPickersAdapterContext

- docs/data/data-grid/editing/editing.md
- packages/x-date-pickers-pro/package.json
- packages/x-date-pickers/package.json
- packages/x-license-pro/package.json
Same spirit as https://github.com/mui/material-ui/pull/32212
There are more issues like this, I don't have the time to take care of them all.
> [docs] Fix small external links issue

- renovate.json
> [core] Don't upgrade CircleCI node

- packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerToolbar.tsx
- packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerView.tsx
- packages/x-date-pickers/src/DatePicker/shared.ts
- packages/x-date-pickers/src/internals/hooks/date-helpers-hooks.tsx
> [core] Small fixes TS on pickers

- docs/data/data-grid/localization/localization.md
- packages/grid/x-data-grid/src/locales/huHU.ts
- packages/grid/x-data-grid/src/locales/index.ts
- scripts/x-data-grid-pro.exports.json
- scripts/x-data-grid.exports.json
Hi,
Here's the Hungarian translation for the Data Grid. MUI Core already has Hungarian locale support but this repo didn't have any.
This is my first PR on any of the MUI projects--hope I did everything correctly. If not, please tell me.
> [l10n] Add Hungarian (hu-HU) locale

- docs/pages/_app.js
Preview: https://deploy-preview-4570--material-ui-x.netlify.app/x/react-date-pickers/date-range-picker/
> [docs] Fix CodeSandbox links for demo with pickers

- packages/grid/x-data-grid-pro/README.md
- packages/grid/x-data-grid/README.md
- packages/x-date-pickers-pro/README.md
- packages/x-date-pickers/README.md
> Fix the README of the X packages

- packages/x-date-pickers-pro/src/DesktopDateRangePicker/DesktopDateRangePicker.test.tsx
- packages/x-date-pickers-pro/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx
- packages/x-date-pickers-pro/src/MobileDateRangePicker/MobileDateRangePicker.tsx
- packages/x-date-pickers/src/internals/components/wrappers/DesktopTooltipWrapper.tsx
fix https://github.com/mui/mui-x/issues/4503
currently I am using free version of DateRangePicker from @mui/lab ^5.0.0-alpha.69
can I push the fix to old mui lab ?
> [DateRangePicker] Fix missing clearable and clearText props

- packages/grid/x-data-grid/src/locales/deDE.ts
I am a German native speaker and discussed the changes with some of my friends (just to make sure they are acceptable).
If you find that anything is missing, please feel free to get back to me, and many thanks for providing this awesome package!
> [l10n] Translate missing German keys

- docs/data/date-pickers/date-time-picker/ResponsiveDateTimePickers.js
- docs/data/date-pickers/date-time-picker/ResponsiveDateTimePickers.tsx
Preview: https://deploy-preview-4667--material-ui-x.netlify.app/x/react-date-pickers/date-time-picker/#responsiveness
Add same labels in https://mui.com/x/react-date-pickers/date-picker/#responsiveness to https://mui.com/x/react-date-pickers/date-time-picker/#responsiveness
> [docs] Add label to each demo

- docs/data/data-grid/pagination/pagination.md
- docs/data/data-grid/row-grouping/row-grouping.md
> [docs] Small typo

- packages/grid/x-data-grid/src/utils/createSelector.ts
- packages/x-date-pickers/src/ClockPicker/ClockPicker.tsx
- packages/x-date-pickers/src/internals/hooks/validation/useTimeValidation.ts
- packages/x-date-pickers/src/internals/utils/time-utils.ts
- packages/x-date-pickers/src/internals/utils/utils.ts
The old value was way to complicated to read for me
> [TimePicker] Refacto `isTimeDisabled` method

- packages/x-date-pickers/src/internals/utils/text-field-helper.test.ts
- packages/x-date-pickers/src/internals/utils/text-field-helper.ts
Part of #4487
I customize the error message depending on the main problems encountered in the issue
I'm wondering if we should write a doc page to explain how format and mask can be customized
> [pickers] Add details in invalid mask error

- packages/grid/x-data-grid-pro/src/tests/detailPanel.DataGridPro.test.tsx
- packages/grid/x-data-grid/src/hooks/features/scroll/useGridScroll.ts
- packages/grid/x-data-grid/src/tests/columnSpanning.DataGrid.test.tsx
- packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx
Fixes https://github.com/mui/mui-x/issues/4513 Codesandbox: https://codesandbox.io/s/basiccolumnsgrid-material-demo-forked-2fpvlz
Fixes https://github.com/mui/mui-x/issues/4514 Codesandbox: https://codesandbox.io/s/basicdetailpanels-material-demo-tbhslz
> [DataGrid] Fix scroll jump when using keyboard navigation

- packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx
- packages/grid/x-data-grid-pro/src/tests/detailPanel.DataGridPro.test.tsx
Fixes #4607
Codesandbox: https://codesandbox.io/s/basicdetailpanels-material-demo-npttjb
> [DataGridPro] Fix detail panel not taking full width

- packages/grid/x-data-grid-generator/src/hooks/useMovieData.ts
Extracted from #4208 to avoid Argos diff on the main PR
Will automerge
> [docs] Set type number to movie column year

- packages/grid/x-data-grid-premium/src/hooks/features/export/serializer/excelSerializer.ts
Fixes https://github.com/mui/mui-x/pull/4750/files#r865759432
Codesandbox: https://codesandbox.io/s/datagridpremiumdemo-material-demo-forked-qz67bd
> [DataGridPremium] Fix Excel date serialization when row grouping is enabled

- packages/x-date-pickers/package.json
Added missing peerDependencies in order to not break projects using yarn pnp, issue #4761.
> PR for #4761: Added missing peerDependencies

- packages/x-date-pickers/src/DateTimePicker/shared.ts
- packages/x-date-pickers/src/internals/components/CalendarOrClockPicker/CalendarOrClockPicker.tsx
- packages/x-date-pickers/src/internals/hooks/usePickerState.ts
> [DateTimePicker] Toolbar should be visible by default on mobile

- docs/data/date-pickers/time-picker/time-picker.md
- docs/pages/x/api/date-pickers/date-time-picker.json
- docs/pages/x/api/date-pickers/desktop-date-time-picker.json
- docs/pages/x/api/date-pickers/desktop-time-picker.json
- docs/pages/x/api/date-pickers/mobile-date-time-picker.json
- docs/pages/x/api/date-pickers/mobile-time-picker.json
- docs/pages/x/api/date-pickers/static-date-time-picker.json
- docs/pages/x/api/date-pickers/static-time-picker.json
- docs/pages/x/api/date-pickers/time-picker.json
- packages/x-date-pickers/src/DateTimePicker/DateTimePicker.tsx
- packages/x-date-pickers/src/DateTimePicker/shared.ts
- packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
- packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.tsx
- packages/x-date-pickers/src/MobileDateTimePicker/MobileDateTimePicker.tsx
- packages/x-date-pickers/src/MobileTimePicker/MobileTimePicker.tsx
- packages/x-date-pickers/src/StaticDateTimePicker/StaticDateTimePicker.tsx
- packages/x-date-pickers/src/StaticTimePicker/StaticTimePicker.tsx
- packages/x-date-pickers/src/TimePicker/TimePicker.tsx
- packages/x-date-pickers/src/TimePicker/shared.ts
> [docs] Fix documentation on `ampm`

- packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.test.tsx
- packages/x-date-pickers/src/internals/components/PickersPopper.tsx
> [DatePicker] Ignore escape key when the picker is already closed

- packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx
- packages/grid/x-data-grid/src/hooks/features/editRows/useGridRowEditing.new.ts
- packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts
Preview: https://deploy-preview-4831--material-ui-x.netlify.app/x/react-data-grid/editing/#full-featured-crud-component
1. Open https://master--material-ui-x.netlify.app/x/react-data-grid/editing/#full-featured-crud-component
2. Click "Add record"
3. Click in the "X" button to delete the newly created record
4. Look at the console "No row with id #id found"
> [DataGrid] Prevent crash if row is removed with click

- docs/pages/_app.js
Preview: https://deploy-preview-4818--material-ui-x.netlify.app/x/advanced-components/
Same as https://github.com/mui/material-ui/pull/32399
https://github.com/mui/material-ui/pull/32399 has a good description explaining the change.
> [docs] Don't redirect to localized doc on deploy preview

- docs/data/data-grid/filtering/QuickFilteringCustomLogic.js
- docs/data/data-grid/filtering/QuickFilteringCustomLogic.tsx
- docs/data/data-grid/filtering/QuickFilteringCustomizedGrid.js
- docs/data/data-grid/filtering/QuickFilteringCustomizedGrid.tsx
- docs/data/data-grid/filtering/QuickFilteringGrid.js
- docs/data/data-grid/filtering/QuickFilteringGrid.tsx
i'm not aware we ever add blank lines in imports.
> [core] Small code style edit

- packages/grid/x-data-grid-premium/package.json
https://unpkg.com/browse/@mui/x-data-grid-premium@5.11.0/LICENSE
> [core] Fix link to the LICENSE file

- CHANGELOG.md
I have tried a few polishes and deployed them to https://github.com/mui/mui-x/releases/tag/v5.11.0. It seems to work better.
> [CHANGELOG] Small polishes

- packages/grid/x-data-grid-premium/src/hooks/features/export/serializer/excelSerializer.ts
- packages/grid/x-data-grid-premium/src/tests/exportExcel.DataGridPremium.test.tsx
> [DataGridPremium] Support column spanning in Excel export

- docs/data/data-grid/getting-started/getting-started.md
Preview: https://deploy-preview-4918--material-ui-x.netlify.app/x/react-data-grid/getting-started/#feature-comparison
> [docs] Update feature comparison table

- packages/grid/x-data-grid-premium/package.json
Quick fix for https://github.com/mui/mui-x/issues/4924#issuecomment-1131398698
> [DataGridPremium] Add exceljs to the dependencies

- docs/public/_redirects
Fix links broken by the columns page splitting
> [docs] Add 301 redirect for columns page

- docs/data/data-grid/accessibility/accessibility.md
- docs/data/data-grid/overview/overview.md
- docs/data/date-pickers/getting-started/getting-started-pt.md
- docs/data/date-pickers/getting-started/getting-started-zh.md
- docs/data/date-pickers/getting-started/getting-started.md
- packages/x-date-pickers-pro/src/StaticDateRangePicker/StaticDateRangePicker.test.tsx
- packages/x-date-pickers/src/CalendarPicker/CalendarPicker.test.tsx
This changed with https://twitter.com/w3c_wai/status/1527321803634274310 last week.
> [docs] New WAI-ARIA guidelines location

- docs/data/data-grid/rows/rows.md
> [docs] Fix typo on rows docs

- .github/workflows/check-if-pr-has-label.yml
For reference -> https://github.com/mui/material-ui/pull/32886
> [core] Enforce a minimum of 1 label in a PR

- packages/grid/x-data-grid-pro/src/tests/cellEditing.DataGridPro.new.test.tsx
- packages/grid/x-data-grid-pro/src/tests/rowEditing.DataGridPro.new.test.tsx
- packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts
- packages/grid/x-data-grid/src/hooks/features/editRows/useGridRowEditing.new.ts
Preview: https://deploy-preview-5016--material-ui-x.netlify.app/x/react-data-grid/editing/#persistence
Fixes #4953
> [DataGrid] Allow other attempts to stop edit mode if the first fails

- packages/grid/x-data-grid/src/locales/ruRU.ts
Added some translations:
+ toolbarExportExcel
+ filterOperatorIsAnyOf
+ master/detail expand and collapse
> [l10n ] Improve Russian (ru-RU) locale

- docs/data/data-grid/rows/rows.md
I noticed a few small typos in this section on the new Dynamic row height feature, and wanted to quickly clean them up so we can put our best foot forward when promoting this on social media in the next few days. 😁 I'll return to this doc at a later date for a full grammar and style review.
> [docs] Small grammar and format fixes for Dynamic row height section

- packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx
> [test] Fix dynamic row height test failing on Chrome

- docsTech/README.md
> [core] Stop using `GridEvents` in technical doc

- docs/data/data-grid/demo/FullFeaturedDemo.js
- docs/data/data-grid/demo/FullFeaturedDemo.tsx
- docs/data/data-grid/selection/CheckboxSelectionCustom.js
- docs/data/data-grid/selection/CheckboxSelectionCustom.tsx
- docs/data/data-grid/selection/CheckboxSelectionCustom.tsx.preview
- docs/data/data-grid/selection/selection.md
- packages/grid/x-data-grid-premium/src/hooks/features/rowGrouping/useGridRowGroupingPreProcessors.ts
- packages/grid/x-data-grid-pro/src/hooks/features/treeData/useGridTreeDataPreProcessors.tsx
- packages/grid/x-data-grid/src/colDef/gridCheckboxSelectionColDef.tsx
- packages/grid/x-data-grid/src/hooks/features/selection/useGridSelectionPreProcessors.ts
- scripts/x-data-grid-premium.exports.json
- scripts/x-data-grid-pro.exports.json
- scripts/x-data-grid.exports.json
Preview: https://deploy-preview-5161--material-ui-x.netlify.app/x/react-data-grid/selection/#custom-checkbox-column
Closes #3420
- Avoid hardcoding the `__check__` field
- Create a new doc section showing how to custimize the checkbox column
> [docs] Add example with custom checkbox column

- packages/grid/x-data-grid-premium/src/hooks/features/rowGrouping/useGridRowGrouping.tsx
- packages/grid/x-data-grid-pro/src/hooks/features/columnPinning/useGridColumnPinning.tsx
- packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts
- packages/grid/x-data-grid/src/hooks/features/columns/useGridColumns.tsx
- packages/grid/x-data-grid/src/hooks/features/filter/useGridFilter.tsx
- packages/grid/x-data-grid/src/hooks/features/sorting/useGridSorting.ts
> [core] Remove unused props from plugin typing

- packages/grid/x-data-grid/src/colDef/gridDateOperators.ts
- packages/grid/x-data-grid/src/colDef/gridNumericColDef.ts
- packages/grid/x-data-grid/src/models/colDef/gridColDef.ts
> [DataGrid] Fix `GridColTypeDef` value type

- .github/ISSUE_TEMPLATE/1.bug.yml
Came here from PR: https://github.com/mui/material-ui/pull/33086 as @oliviertassinari suggested.
> [core] Improve inline code rendering within the details tag

- docs/data/data-grid/editing/EditingWithDatePickers.js
- docs/data/data-grid/editing/EditingWithDatePickers.tsx
Fixes [failing `test_types` on master](https://app.circleci.com/pipelines/github/mui/mui-x/19746/workflows/045ea005-d634-43d2-89c5-d5d6a888d89f/jobs/114720) after merging https://github.com/mui/mui-x/pull/5053 and https://github.com/mui/mui-x/pull/5167
> [docs] Fix `GridColTypeDef` usage in grid + pickers demo

- packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx
Two tests started to fail again after merging https://github.com/mui/mui-x/pull/5135.
See https://app.circleci.com/pipelines/github/mui/mui-x/19776/workflows/9429cd15-68a8-44cf-8596-05e3474c4626/jobs/114880
> [test] Add `waitFor` before asserting height

- packages/grid/x-data-grid-premium/src/hooks/features/export/serializer/excelSerializer.ts
> [DataGridPremium] Fix Excel import with Remix/Vite

- docs/data/data-grid/localization/localization.md
- docs/data/date-pickers/localization/localization.md
- packages/grid/x-data-grid/src/locales/index.ts
- packages/grid/x-data-grid/src/locales/svSE.ts
- packages/x-date-pickers/src/locales/index.ts
- packages/x-date-pickers/src/locales/svSE.ts
- scripts/x-data-grid-premium.exports.json
- scripts/x-data-grid-pro.exports.json
- scripts/x-data-grid.exports.json
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
Swedish locale already exists in Core.  
10M speakers.
> [l10n] Add Swedish (sv-SE) locale

- packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.test.tsx
- packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePickerKeyboard.test.tsx
Fixes https://github.com/mui/mui-x/pull/5221#discussion_r903142621
> [test] Fix `inputFormat` when testing with different date adapters

- docs/data/data-grid/row-grouping/row-grouping.md
Part of https://github.com/mui/mui-x/issues/5235
> [docs] Add waiting for upvote section for row group panel

- packages/grid/x-data-grid/src/components/panel/GridColumnsPanel.tsx
- packages/grid/x-data-grid/src/tests/columnsVisibility.DataGrid.test.tsx
> [data grid] Don't hide non-hideable column when pressing Hide All button

- docs/pages/x/react-data-grid/demo.js
follow up on: https://github.com/mui/mui-x/pull/5292#issuecomment-1164326437
Perhaps we can merge it before 5.12.3
Preview: https://deploy-preview-5301--material-ui-x.netlify.app/x/react-data-grid/demo/
> [docs] Disable ad on main demo page

- packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerViewDesktop.tsx
- packages/x-date-pickers/src/CalendarPicker/DayPicker.tsx
- packages/x-date-pickers/src/internals/index.ts
> [DayPicker] Remove empty space at the bottom of the day view

- docs/data/data-grid/localization/localization.md
- packages/grid/x-data-grid/src/locales/index.ts
- packages/grid/x-data-grid/src/locales/roRO.ts
- scripts/x-data-grid-premium.exports.json
- scripts/x-data-grid-pro.exports.json
- scripts/x-data-grid.exports.json
Add Romanian locale to data grid.
> [l10n] Add Romanian (ro-RO) locale

- docs/data/data-grid/row-grouping/RowGroupingGetRowGroupChildren.js
- docs/data/data-grid/row-grouping/RowGroupingGetRowGroupChildren.tsx
I missed one demo (that was in a PR) when moving `useKeepGroupedColumnsHiddren` to our package.
Will automerge
> [docs] Use `useKeepGroupedColumnsHiddren` from the grid package on remaining demo

- packages/grid/x-data-grid/src/locales/nlNL.ts
> [DataGrid] Improve Dutch (nl-NL) locale

- packages/grid/x-data-grid-premium/src/hooks/features/export/serializer/excelSerializer.ts
- packages/grid/x-data-grid-premium/src/tests/exportExcel.DataGridPremium.test.tsx
- packages/grid/x-data-grid/src/hooks/features/columns/useGridColumnSpanning.ts
- packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
- packages/grid/x-data-grid/src/models/api/gridColumnSpanning.ts
Fixes #5353
Codesandbox: https://codesandbox.io/s/excelcustomexport-demo-mui-x-forked-qt3tw0
> [DataGridPremium] Fix crash when exporting all columns to Excel

- docs/data/date-pickers/localization/localization.md
- packages/x-date-pickers/src/locales/index.ts
- packages/x-date-pickers/src/locales/nbNO.ts
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
Following up on #3211, I'd like to provide Norwegian (Bokmål) translations for the Date Picker component.
> [pickers] Add Norwegian (nb-NO) locale

- packages/grid/x-data-grid/src/locales/zhCN.ts
- packages/x-date-pickers/src/locales/index.ts
- packages/x-date-pickers/src/locales/zhCN.ts
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
Add simplified Chinese locale to data grid and date picker.
> [l10n] Add simplified Chinese (zh-CN) locale to pickers and complet data grid

- packages/grid/x-data-grid/src/locales/deDE.ts
Adds missing de-DE translations from #3211.
> [DataGrid] Improve German (de-DE) locale

- packages/grid/x-data-grid/src/components/toolbar/GridToolbarDensitySelector.tsx
- packages/grid/x-data-grid/src/components/toolbar/GridToolbarExportContainer.tsx
Preview: https://deploy-preview-5503--material-ui-x.netlify.app/x/react-data-grid/components/#toolbar
Fixes #5484
> [DataGrid] Toggle open state when clicking on buttons in Toolbar

- packages/grid/x-data-grid/src/locales/koKR.ts
update ko-KR translation for #3211
> [DataGrid] Improve Korean (ko-KR) locale

- .github/FUNDING.yml
Not needed, we have a global one now https://github.com/mui/.github/blob/master/FUNDING.yml.
> [core] Remove duplicated FUNDING.yml file

- docs/pages/x/api/date-pickers/month-picker.json
- docs/pages/x/api/date-pickers/year-picker.json
- docs/translations/api-docs/date-pickers/month-picker-pt.json
- docs/translations/api-docs/date-pickers/month-picker-zh.json
- docs/translations/api-docs/date-pickers/month-picker.json
- docs/translations/api-docs/date-pickers/year-picker-pt.json
- docs/translations/api-docs/date-pickers/year-picker-zh.json
- docs/translations/api-docs/date-pickers/year-picker.json
- packages/x-date-pickers/src/CalendarPicker/CalendarPicker.tsx
- packages/x-date-pickers/src/MonthPicker/MonthPicker.tsx
- packages/x-date-pickers/src/YearPicker/YearPicker.tsx
> [pickers] Support `disableHighlightToday` on MonthPicker and YearPicker

- packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts
- packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx
> [DataGrid] Catch error if rows freezing is not supported

- docs/data/data-grid/row-height/row-height.md
> [docs] Fix typo on the row height page

- docs/data/date-pickers/localization/localization.md
- packages/x-date-pickers/src/locales/index.ts
- packages/x-date-pickers/src/locales/plPL.ts
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
I’d like to provide Polish (pl-PL) translations for the date picker component (#3211).
> [pickers] Add Polish (pl-PL) locale

- scripts/releaseChangelog.js
A few improvements we can do to make easier to write the CHANGELOG.
> [core] Small changes to the release script

- test/regressions/index.js
- test/utils/licenseKey.ts
An idea based after https://mui.zendesk.com/agent/tickets/4574 to be clearer.
> [core] Clarify the scope of this license key

- packages/grid/x-data-grid/src/components/base/GridBody.tsx
Fixes https://github.com/mui/mui-x/issues/5887
The use case for it is pretty exotic, but why not support it.
> [DataGrid] Handle `disableVirtualization` prop change

- docs/data/data-grid/master-detail/master-detail.md
Signed-off-by: wettopa <109089747+wettopa@users.noreply.github.com>
> [docs] Fix typo

- docs/pages/x/api/data-grid/data-grid-premium.json
- docs/pages/x/api/data-grid/data-grid-pro.json
- docs/pages/x/api/data-grid/data-grid.json
- docs/translations/api-docs/data-grid/data-grid-premium-pt.json
- docs/translations/api-docs/data-grid/data-grid-premium-zh.json
- docs/translations/api-docs/data-grid/data-grid-premium.json
- docs/translations/api-docs/data-grid/data-grid-pro-pt.json
- docs/translations/api-docs/data-grid/data-grid-pro-zh.json
- docs/translations/api-docs/data-grid/data-grid-pro.json
- docs/translations/api-docs/data-grid/data-grid-pt.json
- docs/translations/api-docs/data-grid/data-grid-zh.json
- docs/translations/api-docs/data-grid/data-grid.json
- packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanelPreProcessors.ts
- packages/grid/x-data-grid-pro/src/tests/detailPanel.DataGridPro.test.tsx
- packages/grid/x-data-grid/src/components/GridRow.tsx
- packages/grid/x-data-grid/src/constants/gridClasses.ts
- packages/grid/x-data-grid/src/hooks/core/pipeProcessing/gridPipeProcessingApi.ts
Closes #5017
Preview: https://deploy-preview-5924--material-ui-x.netlify.app/x/react-data-grid/master-detail/
> [DataGridPro] Add class name to row with open detail panel

- packages/grid/x-data-grid-pro/src/tests/editComponents.DataGridPro.old.test.tsx
- packages/grid/x-data-grid/src/components/cell/GridCell.tsx
- packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts
Fixes #4333
Preview: https://deploy-preview-5980--material-ui-x.netlify.app/x/react-data-grid/editing/
> [DataGrid] Fix cells being focused on mouseUp

- CHANGELOG.md
- docs/data/data-grid/editing-legacy/editing.md
- docs/data/data-grid/getting-started/getting-started.md
Some anchors have been modified. Found during #6102
> [docs] Fix broken links

- .circleci/config.yml
- packages/grid/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx
> [test] Fix logic to skip column pinning tests

- docs/data/date-pickers/localization/localization.md
- packages/x-date-pickers/src/locales/index.ts
- packages/x-date-pickers/src/locales/isIS.ts
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
closes #6123
Did not modify
mui/mui-x/scripts/x-date-pickers-pro.exports.json, 
mui/mui-x/scripts/x-date-pickers.exports.json
because they look like they could be auto-generated.
> [pickers] Add Icelandic (is-IS) locale

- packages/x-date-pickers/src/locales/deDE.ts
Resolves part of #3211.
Add missing de-DE translations for pickers.
> [pickers] Improve German (de-DE) locale

- docs/data/date-pickers/localization/localization.md
- packages/x-date-pickers/src/locales/index.ts
- packages/x-date-pickers/src/locales/isIS.ts
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
Port #6124 because it is a user contribution
Will automerge
> [pickers] Add Icelandic (is-IS) locale (target master)

- docs/data/date-pickers/date-time-range-picker/date-time-range-picker.md
> [docs] Fix typo in linked issue

- docs/data/data-grid/style/style.md
Avoid the 301 that redirects https://mui.com/system/the-sx-prop/ to https://mui.com/system/getting-started/the-sx-prop/
> [docs] Fix broken link

- docs/data/date-pickers/localization/localization.md
- packages/grid/x-data-grid/src/locales/faIR.ts
- packages/x-date-pickers/src/locales/faIR.ts
- packages/x-date-pickers/src/locales/index.ts
- packages/x-date-pickers/src/locales/isIS.ts
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
> [l10n] Add Persian (fa-IR) locale

- packages/x-date-pickers/src/internals/hooks/useUtils.ts
> [pickers] Improve error message when no adapter context is found

- package.json
- yarn.lock
Based on https://github.com/mui/mui-x/pull/6180#discussion_r973601419
> [core] Restore monorepo to the main release line

- docs/data/date-pickers/localization/localization.md
- packages/grid/x-data-grid/src/locales/fiFI.ts
- packages/x-date-pickers/src/locales/fiFI.ts
- packages/x-date-pickers/src/locales/index.ts
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
Cherry picked from next (see #6219)
Will auto merge
> [I10n] Add Finnish (fi-FI) locale to Datepicker (#6219)

- packages/x-date-pickers/src/internals/models/muiPickersAdapter.d.ts
Cherry-picked from #6229
Will auto merge
> [pickers] Fix usage with Typescript 4.8 (#6229)

- packages/grid/x-data-grid/src/locales/plPL.ts
Cherry-picked from #6245
Will auto merge
> [l10n] Improve Polish (pl-PL) locale on the data grid (#6245)

- CHANGELOG.md
> [core] Add v5.17.3 changelog to next branch

- packages/x-date-pickers/src/internals/hooks/validation/useDateTimeValidation.ts
Based on https://github.com/mui/mui-x/pull/6064#discussion_r978451391
> [DateTimePicker] Fix validation with `shouldDisableMonth` and `shouldDisableYear`

- docs/data/date-pickers/date-field/ControlledSelectedSections.js
- docs/data/date-pickers/date-field/ControlledSelectedSections.tsx
- docs/data/date-pickers/date-field/date-field.md
- packages/x-date-pickers-pro/src/SingleInputDateRangeField/useSingleInputDateRangeField.ts
- packages/x-date-pickers/src/DateField/useDateField.ts
- packages/x-date-pickers/src/internals/hooks/useField/useField.interfaces.ts
- packages/x-date-pickers/src/internals/hooks/useField/useField.ts
Follow up on #6209
The props were mis-named since we can now store other thing than indexes in them.
Will auto-merge
> [pickers] Allow to control the selected sections - follow up

- packages/x-date-pickers/src/CalendarPicker/CalendarPicker.test.tsx
- packages/x-date-pickers/src/CalendarPicker/useCalendarState.tsx
- packages/x-date-pickers/src/internals/utils/date-utils.ts
> [DatePicker] Open in a valid month

- packages/grid/x-data-grid-premium/src/themeAugmentation/index.js
- packages/grid/x-data-grid-premium/src/themeAugmentation/index.ts
- packages/grid/x-data-grid-premium/src/themeAugmentation/overrides.ts
- packages/grid/x-data-grid-premium/src/themeAugmentation/props.ts
Backport of https://github.com/mui/mui-x/pull/6270
> [DataGridPremium] Add missing `themeAugmentation` module

- docs/data/date-pickers/localization/localization.md
- packages/x-date-pickers/src/locales/index.ts
- packages/x-date-pickers/src/locales/jaJP.ts
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
Add japanese translations to pickers.
> [I10n] Add Japanese (ja-JP) locale to pickers

- docs/data/date-pickers/date-range-picker/CustomDateRangePickerDay.js
- docs/data/date-pickers/date-range-picker/CustomDateRangePickerDay.tsx
Cherry picked from master (see https://github.com/mui/mui-x/pull/6342)
> [docs] Fix customized day rendering demo style (#6342)

- packages/grid/x-data-grid-pro/src/themeAugmentation/props.ts
- packages/grid/x-data-grid/src/themeAugmentation/props.ts
Backport of https://github.com/mui/mui-x/pull/6269 to master
> [DataGrid] Pass generics to the components in the theme augmentation

- packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx
> [core] Fix tests for pasting on fields

- docs/data/date-pickers/date-field/date-field.md
- docs/data/date-pickers/date-time-field/date-time-field.md
- docs/data/date-pickers/time-field/time-field.md
Fixes #6500
Will auto merge and will cherry pick on the doc branch
> [docs] Fix broken links on field pages

- packages/x-date-pickers/src/PickersDay/PickersDay.tsx
> [DateRangePicker] Fix calendar day outside of month layout shifting on hover (pick #6448)

- docs/data/date-pickers/date-picker/date-picker.md
- docs/data/date-pickers/date-range-picker/date-range-picker.md
- docs/data/date-pickers/date-time-picker/date-time-picker.md
- docs/data/date-pickers/time-picker/time-picker.md
If the core release is today, maybe better to include this commit in #6497
> [docs] Fix 404 errors

- dangerfile.js
Same as https://github.com/mui/material-ui/pull/34688, a small time saver. See ⬇️
> [core] Link Netlify in the danger comment

- packages/grid/x-data-grid/src/components/panel/GridColumnsPanel.tsx
- packages/grid/x-data-grid/src/tests/toolbar.DataGrid.test.tsx
Closes https://github.com/mui/mui-x/issues/6453
> [DataGrid] Add `searchPredicate` prop to `GridColumnsPanel` component

- packages/grid/x-data-grid/src/locales/trTR.ts
- packages/x-date-pickers/src/locales/trTR.ts
> [l10n] Improve Turkish (tr-TR) locale on the data grid and pickers (#6542)

- packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx
- packages/grid/x-data-grid/src/hooks/features/rows/gridRowsState.ts
- packages/grid/x-data-grid/src/hooks/features/rows/gridRowsUtils.ts
- packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts
Backport of https://github.com/mui/mui-x/pull/5982 to `master`
> [DataGrid] Fix grid not updating state on `rowCount` prop change

- packages/grid/x-data-grid/src/locales/bgBG.ts
Noticed a small typo with the translation of one of the words which I changed.
> [l10n] Improve Bulgarian (bg-BG) locale

- packages/grid/x-data-grid-premium/LICENSE
- packages/grid/x-data-grid-pro/LICENSE
- packages/x-date-pickers-pro/LICENSE
- packages/x-license-pro/LICENSE
This change is triggered by the problem raised in https://github.com/mui/mui-x/issues/6450#issuecomment-1275124818. The current content https://unpkg.com/browse/@mui/x-data-grid-pro/LICENSE mentions the existing of a free trial plan that is now different.
> [license] Improve the license content

- docs/next.config.js
Add tokens for feedbacks to go on server + slack
> [docs] Add feedback in next doc

- packages/x-date-pickers/src/internals/hooks/useMaskedInput.tsx
> [pickers] Update input when `inputFormat` is modified

- docs/data/data-grid/demo/PopularFeaturesDemo.js
- docs/data/data-grid/demo/PopularFeaturesDemo.tsx
Fixes #6615 
Below is the screenshot after the changes.
> [docs] Fix typo in DataGrid demo page

- docs/data/data-grid/demo/PopularFeaturesDemo.js
- docs/data/data-grid/demo/PopularFeaturesDemo.tsx
> [docs] Fix typo in DataGrid demo page (#6632)

- packages/grid/x-data-grid/src/locales/bgBG.ts
Fixes #6628 
Back-port of #6578 to master
> [l10n] Improve Bulgarian (bg-BG) locale (#6578)

- packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx
- packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts
Backport of https://github.com/mui/mui-x/pull/6493 to `master` branch
> [DataGrid] Fix `setRows` method not persisting new rows data after `loading` prop change

- docs/package.json
- docs/pages/_app.js
- yarn.lock
Backport of https://github.com/mui/mui-x/pull/6560 to `master` branch
> [docs] Disable translations

- docs/data/data-grid/getting-started/getting-started.md
https://deploy-preview-6660--material-ui-x.netlify.app/x/react-data-grid/getting-started/#feature-comparison
> [docs] Mark data grid column group as available

- docs/data/data-grid/getting-started/getting-started.md
https://deploy-preview-6659--material-ui-x.netlify.app/x/react-data-grid/getting-started/#feature-comparison
> [docs] Mark data grid column group available

- packages/grid/x-data-grid/src/components/cell/GridActionsCell.tsx
- packages/grid/x-data-grid/src/components/cell/GridCell.tsx
- packages/grid/x-data-grid/src/components/columnSelection/GridCellCheckboxRenderer.tsx
- packages/grid/x-data-grid/src/tests/cells.DataGrid.test.tsx
Port of https://github.com/mui/mui-x/pull/6622 to the `next` branch
> [DataGrid] Fix cell focus causing scroll jump when virtualization enabled

- packages/x-date-pickers/src/DatePicker/DatePickerToolbar.tsx
- packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx
- packages/x-date-pickers/src/internals/components/PickersToolbar.tsx
> [pickers] Fix pickers toolbar styling (#6793)

- .github/workflows/scorecards.yml
Fix https://github.com/mui/mui-x/security/code-scanning/10. To help a bit with https://mui.zendesk.com/agent/tickets/5635.
> [core] Remove scorecard default permissions

- docs/data/data-grid/row-grouping/row-grouping.md
- packages/grid/x-data-grid-pro/src/components/GridTreeDataGroupingCell.tsx
> [DataGridPremium] Allow to customise the indent of group expansion toggle

- docs/pages/x/api/date-pickers/date-range-calendar.json
- docs/translations/api-docs/date-pickers/date-range-calendar-pt.json
- docs/translations/api-docs/date-pickers/date-range-calendar-zh.json
- docs/translations/api-docs/date-pickers/date-range-calendar.json
- packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx
- packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.types.ts
- packages/x-date-pickers-pro/src/MultiInputDateRangeField/MultiInputDateRangeField.tsx
- packages/x-date-pickers-pro/src/MultiInputDateTimeRangeField/MultiInputDateTimeRangeField.tsx
- packages/x-date-pickers-pro/src/MultiInputTimeRangeField/MultiInputTimeRangeField.tsx
- packages/x-date-pickers-pro/src/internal/models/index.ts
> [pickers] Fix typing and prop drilling on `DateRangeCalendar` and multi input range fields

- packages/grid/x-data-grid-pro/src/tests/detailPanel.DataGridPro.test.tsx
- packages/grid/x-data-grid/src/components/GridRow.tsx
Backport of https://github.com/mui/mui-x/pull/6707 to the `master` branch
> [DataGridPro] Fix detail panel not working with `getRowSpacing` prop

- docs/data/data-grid/row-pinning/row-pinning.md
Closes https://github.com/mui/mui-x/issues/6782#issuecomment-1310749601
TODO:
> [docs] Clarify DataGrid Row Pinning docs

- docs/package.json
- yarn.lock
Fixes #6910 
Preview: https://deploy-preview-6911--material-ui-x.netlify.app/x/react-data-grid/getting-started/
> [docs] Upgrade to Next 13

- .circleci/config.yml
Signed-off-by: Piotr Wysocki <86244209+piwysocki@users.noreply.github.com>
> [core] Upgrade node to v14.21

- .circleci/config.yml
> [core] Upgrade node to v14.21 (#6916)

- packages/x-date-pickers/src/internals/components/PickersPopper.tsx
- packages/x-date-pickers/src/internals/components/wrappers/DesktopTooltipWrapper.tsx
- packages/x-date-pickers/src/internals/utils/utils.ts
> [pickers] Fix usage with Shadow DOM #6952

- docs/data/data-grid/events/events.json
- docs/data/date-pickers/date-picker/CustomInput.js
- docs/data/date-pickers/date-picker/CustomInput.tsx
- docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md
- packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts
- packages/grid/x-data-grid-pro/src/tests/events.DataGridPro.test.tsx
- packages/grid/x-data-grid/src/components/GridScrollArea.tsx
- packages/grid/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx
- packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
- packages/grid/x-data-grid/src/models/events/gridEventLookup.ts
> [DataGrid] Rename `rowsScroll` event to `scrollPositionChange`

- packages/grid/x-data-grid/src/locales/ukUA.ts
- packages/x-date-pickers/src/locales/ukUA.ts
Updating UA locales for pickers and grid
> [l10n] Improve Ukrainian (uk-UA) locale

- packages/x-date-pickers/src/internals/hooks/useField/useField.ts
- packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts
> [core] Remove useless type casting in field hooks

- docs/data/data-grid/localization/localization.md
Remove the statement of support to RTL and add a link to upvote the Github issue.
RTL is currently not fully supported as per #230.
> [Data Grid] Remove the statement of support to RTL

- CHANGELOG.md
- docs/package.json
- package.json
- packages/grid/x-data-grid-generator/package.json
- packages/grid/x-data-grid-premium/package.json
- packages/grid/x-data-grid-pro/package.json
- packages/grid/x-data-grid/package.json
- packages/x-date-pickers-pro/package.json
- packages/x-date-pickers/package.json
The following steps must be proposed as a pull request.
```bash
```
```sh
```
You can follow the deployment process [on the Netlify …
> v6.0.0-alpha.10

- packages/x-date-pickers/src/MonthPicker/MonthPicker.test.tsx
- packages/x-date-pickers/src/MonthPicker/MonthPicker.tsx
- packages/x-date-pickers/src/YearPicker/YearPicker.test.tsx
- packages/x-date-pickers/src/YearPicker/YearPicker.tsx
> [pickers] Initialize date without time when selecting year or month

- docs/data/data-grid/aggregation/AggregationSelectorsNoSnap.js
- docs/data/data-grid/aggregation/aggregation.md
- docs/pages/x/api/data-grid/selectors.json
- packages/grid/x-data-grid-premium/src/hooks/features/aggregation/gridAggregationSelectors.ts
Backport of https://github.com/mui/mui-x/pull/7148 to the `master` branch
> [docs] Document aggregation selectors

- packages/x-date-pickers/src/DateField/tests/selection.DateField.test.tsx
- packages/x-date-pickers/src/internals/hooks/useField/useField.ts
Fixes a broken test on `next` introduced by #7153
Will automerge
> [core] Fix broken test

- packages/x-date-pickers/src/StaticNextDateTimePicker/StaticNextDateTimePicker.tsx
> [pickers] Fix wrong component name on `StaticNextDateTime`

- packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
- packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx
Fixes https://github.com/mui/mui-x/issues/6595
Before: https://codesandbox.io/s/laughing-hopper-0mv8ll
After: https://codesandbox.io/s/jolly-leakey-h8b3jq
TODO:
> [DataGrid] Fix flickering on mount

- docs/data/date-pickers/date-picker/CustomDay.js
- docs/data/date-pickers/date-picker/CustomDay.tsx
- docs/data/date-pickers/date-picker/CustomInput.js
- docs/data/date-pickers/date-picker/CustomInput.tsx
- docs/data/date-pickers/date-picker/ViewsDatePicker.js
- docs/data/date-pickers/date-picker/ViewsDatePicker.tsx
- docs/data/date-pickers/date-range-picker/CustomInputs.js
- docs/data/date-pickers/date-range-picker/CustomInputs.tsx
- docs/data/date-pickers/legacy-date-picker/CustomDay.js
- docs/data/date-pickers/legacy-date-picker/CustomDay.tsx
- docs/data/date-pickers/legacy-time-picker/SecondsTimePicker.js
- docs/data/date-pickers/legacy-time-picker/SecondsTimePicker.tsx
- docs/data/date-pickers/time-picker/SecondsTimePicker.js
- docs/data/date-pickers/time-picker/SecondsTimePicker.tsx
- docs/data/date-pickers/time-picker/SecondsTimePicker.tsx.preview
- docs/src/modules/components/PickersInstallationInstructions.js
- docs/src/modules/components/PickersRenderingInstructions.js
Fixes errors and warning being thrown in console (mostly relevant only in dev mode).
Fixes mobile minutes and seconds demo:
**Before**:
**After**:
> [docs] Fix errors and warning in demos

- docs/data/date-pickers/localization/data.json
- packages/x-date-pickers/src/locales/koKR.ts
> [pickers] Improve Korean (ko-KR) locale @hanbin9775

- packages/grid/x-data-grid-premium/src/hooks/features/export/serializer/excelSerializer.ts
> [DataGridPremium] Fix `exceljs` import with parcel

- SECURITY.md
> [docs] Drop security fixes support for v4

- packages/grid/x-data-grid/src/hooks/features/clipboard/useGridClipboard.ts
Port of https://github.com/mui/mui-x/pull/6593 to the `master` branch
> [DataGrid] Fix selected text in cell input not being copied in Firefox

- packages/grid/x-data-grid-pro/src/tests/rowEditing.DataGridPro.new.test.tsx
- packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx
- packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
- packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx
Backport of https://github.com/mui/mui-x/pull/6892 to the `master` branch
> [DataGrid] Fix rows not rendering properly after height change

- packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaders.tsx
Fixes https://github.com/mui/mui-x/pull/7001#discussion_r1048406008 in v5
Before: https://codesandbox.io/s/strange-sea-6ul544?file=/demo.tsx
After: https://codesandbox.io/s/kind-moon-xrne4h
> [DataGridPro] Fix missing column headers border with top-pinned rows

- docs/data/data-grid/localization/data.json
- packages/grid/x-data-grid/src/locales/esES.ts
Some translation for spanish locale.
> Improve Spanish (es-ES) locale

- docs/data/data-grid/localization/data.json
- packages/grid/x-data-grid/src/locales/esES.ts
> Improve Spanish (es-ES) locale (from @Anderssxn)

- docs/data/date-pickers/localization/data.json
- packages/x-date-pickers/src/locales/beBY.ts
- packages/x-date-pickers/src/locales/index.ts
- scripts/localeNames.js
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
Back-ports #7395
Will auto-merge.
> [pickers] Add Belarusian (be-BY) locale

- packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx
- packages/x-date-pickers/src/DateCalendar/DateCalendar.types.ts
- packages/x-date-pickers/src/DateCalendar/index.ts
- packages/x-date-pickers/src/DateCalendar/useCalendarState.tsx
- packages/x-date-pickers/src/DatePicker/shared.ts
- packages/x-date-pickers/src/DateTimePicker/shared.ts
- packages/x-date-pickers/src/MonthCalendar/MonthCalendar.tsx
- packages/x-date-pickers/src/MonthCalendar/MonthCalendar.types.ts
- packages/x-date-pickers/src/MonthCalendar/index.ts
- packages/x-date-pickers/src/NextDatePicker/shared.tsx
- packages/x-date-pickers/src/NextDateTimePicker/shared.tsx
- packages/x-date-pickers/src/NextTimePicker/shared.tsx
- packages/x-date-pickers/src/TimeClock/TimeClock.tsx
- packages/x-date-pickers/src/TimeClock/TimeClock.types.ts
- packages/x-date-pickers/src/TimeClock/index.ts
- packages/x-date-pickers/src/TimePicker/shared.ts
- packages/x-date-pickers/src/YearCalendar/YearCalendar.tsx
- packages/x-date-pickers/src/YearCalendar/YearCalendar.types.ts
- packages/x-date-pickers/src/YearCalendar/index.ts
- packages/x-date-pickers/src/internals/components/CalendarOrClockPicker/CalendarOrClockPicker.tsx
- packages/x-date-pickers/src/internals/index.ts
> [core] Move interfaces of UI views to dedicated files

- packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts
> [core] Move default closeOnSelect to prop definition

- docs/data/date-pickers/localization/data.json
- packages/x-date-pickers/src/locales/itIT.ts
Added inputModeToggleButtonAriaLabel and Toolbar titles missing translations in Italian language 🇮🇹
Signed-off-by: Marika Mella <116084393+marikadeveloper@users.noreply.github.com>
> [l10n] Imporve Italian (it-IT) locale

- docs/data/date-pickers/localization/data.json
- packages/x-date-pickers/src/locales/itIT.ts
> [l10n] Imporve Italian (it-IT) locale (from @marikadeveloper)

- packages/x-date-pickers-pro/src/dateRangeViewRenderers/dateRangeViewRenderers.tsx
> [pickers] Add missing `slots` and `slotProps` on the date range view renderer

- docs/data/data-grid/localization/data.json
- packages/grid/x-data-grid/src/locales/svSE.ts
> [l10n] Update Swedish (svSE) locale (from @MaanTyringe)

- docs/data/data-grid/localization/data.json
- packages/grid/x-data-grid/src/locales/svSE.ts
Justerat unpin, detailPanelToggle
Lagt till Aggregation
Signed-off-by: MaanTyringe <122359493+MaanTyringe@users.noreply.github.com>
> [l10n] Update Swedish (svSE) locale

- packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
Fixes https://github.com/mui/mui-x/issues/5354
Before: https://codesandbox.io/s/crazy-pond-reu568
After: https://codesandbox.io/s/epic-shockley-p8pr7v
Fixes https://github.com/mui/mui-x/issues/7204
Before: https://codesandbox.io/s/divine-frost-1pl6uf
After: https://codesandbox.io/s/adoring-wilson-0i237j
TODO:
> [DataGrid] Fix flickering on grid scroll

- CHANGELOG.md
> [core] Fix typo in `CHANGELOG`

- docs/data/data-grid/localization/data.json
- packages/grid/x-data-grid/src/locales/jaJP.ts
> [l10n] Improve Japanese (ja-JP) locale (from @makoto14)

- docs/data/data-grid/localization/data.json
- docs/data/date-pickers/localization/data.json
- packages/grid/x-data-grid/src/locales/jaJP.ts
- packages/x-date-pickers/src/locales/jaJP.ts
Adds missing translations for Japanese (ja-JP) locale - https://github.com/mui/mui-x/issues/3211.
> [l10n] Improve Japanese (ja-JP) locale

- docs/data/data-grid/localization/data.json
- docs/data/date-pickers/localization/data.json
- packages/grid/x-data-grid/src/locales/esES.ts
- packages/x-date-pickers/src/locales/esES.ts
> [l10n] Improve Spanish (es-ES) locale

- docs/data/data-grid/localization/data.json
- packages/grid/x-data-grid/src/locales/viVN.ts
Signed-off-by: Ţrần Bình Ąn <36723955+SpacerZ@users.noreply.github.com>
> [l10n] Improve Vietnamese (vi-VN) locale

- docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md
- packages/x-codemod/README.md
- packages/x-codemod/src/v6.0.0/data-grid/preset-safe/actual.spec.js
- packages/x-codemod/src/v6.0.0/data-grid/preset-safe/expected.spec.js
- packages/x-codemod/src/v6.0.0/data-grid/preset-safe/index.ts
- packages/x-codemod/src/v6.0.0/data-grid/rename-rowsPerPageOptions-prop/actual.spec.js
- packages/x-codemod/src/v6.0.0/data-grid/rename-rowsPerPageOptions-prop/expected.spec.js
- packages/x-codemod/src/v6.0.0/data-grid/rename-rowsPerPageOptions-prop/index.ts
- packages/x-codemod/src/v6.0.0/data-grid/rename-rowsPerPageOptions-prop/rename-rowsPerPageOptions-prop.test.ts
Part of #7086 
Codemod for breaking change done in https://github.com/mui/mui-x/pull/7147
> [codemod] Rename `rowsPerPageOptions` prop to `pageSizeOptions`

- docs/data/date-pickers/localization/data.json
- packages/x-date-pickers/src/locales/csCZ.ts
- packages/x-date-pickers/src/locales/index.ts
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
- yarn.lock
> [l10n] Add Czech (cs-CZ) locale 

- packages/x-date-pickers/src/themeAugmentation/components.d.ts
- packages/x-date-pickers/src/themeAugmentation/themeAugmentation.spec.ts
- yarn.lock
> [pickers] Add missing components to `themeAugmentation`

- CHANGELOG.md
- docs/data/migration/migration-pickers-v5/migration-pickers-v5.md
- packages/x-codemod/README.md
- packages/x-codemod/src/util/removeProps.ts
- packages/x-codemod/src/v6.0.0/pickers/migrate-to-components-componentsProps/actual.spec.js
- packages/x-codemod/src/v6.0.0/pickers/migrate-to-components-componentsProps/expected.spec.js
- packages/x-codemod/src/v6.0.0/pickers/migrate-to-components-componentsProps/index.ts
- packages/x-codemod/src/v6.0.0/pickers/migrate-to-components-componentsProps/migrate-to-components-componentsProps.test.ts
- packages/x-codemod/src/v6.0.0/pickers/preset-safe/actual.spec.js
- packages/x-codemod/src/v6.0.0/pickers/preset-safe/expected.spec.js
- packages/x-codemod/src/v6.0.0/pickers/preset-safe/index.ts
- packages/x-codemod/src/v6.0.0/pickers/replace-arrows-button-slot/actual.spec.js
- packages/x-codemod/src/v6.0.0/pickers/replace-arrows-button-slot/expected.spec.js
- packages/x-codemod/src/v6.0.0/pickers/replace-arrows-button-slot/index.ts
- packages/x-codemod/src/v6.0.0/pickers/replace-arrows-button-slot/replace-tabs-props.test.ts
> [codemod] Basics migration to components props

- docs/data/date-pickers/localization/data.json
- packages/x-date-pickers/src/locales/index.ts
- packages/x-date-pickers/src/locales/ruRU.ts
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
> [l10n] Add Russian (ru-RU) locale

- packages/x-codemod/src/v6.0.0/data-grid/row-selection-props-rename/actual.spec.js
- packages/x-codemod/src/v6.0.0/data-grid/row-selection-props-rename/expected.spec.js
- packages/x-codemod/src/v6.0.0/data-grid/row-selection-props-rename/index.ts
Codemod for prop `headerHeight -> columnHeaderHeight` prop rename done in https://github.com/mui/mui-x/pull/7001
Part of #7086
> [codemod] Add `headerHeight` prop update to `row-selection-props-rename` codemod

- packages/grid/x-data-grid/src/locales/beBY.ts
- packages/grid/x-data-grid/src/locales/coreLocales.ts
Context: https://github.com/mui/mui-x/pull/7646#issuecomment-1405153939
> [l10n] Add missing core locales for `MuiTablePagination`

- docs/data/data-grid/recipes-row-grouping/RowGroupingPinning.js
- docs/data/data-grid/recipes-row-grouping/RowGroupingPinning.tsx
- docs/data/data-grid/recipes-row-grouping/RowGroupingPinning.tsx.preview
- docs/data/data-grid/recipes-row-grouping/recipes-row-grouping.md
> [docs] Add recipe for pinning grouped column

- packages/grid/x-data-grid/src/lib/createDetectElementResize/index.js
Cherrypick of https://github.com/mui/mui-x/pull/7298
> [DataGrid] Fix scrolling on resize for data grids inside shadow root

- docs/data/date-pickers/custom-components/custom-components.md
> [docs] Add info callout about available component `slots`

- docs/data/data-grid/layout/layout.md
Signed-off-by: Stuart Baker <stuartbaker7@gmail.com>
> [docs] Fix a typo in data grid layout page

- docs/data/migration/migration-pickers-v5/migration-pickers-v5.md
- packages/x-codemod/README.md
- packages/x-codemod/src/v6.0.0/pickers/preset-safe/actual.spec.js
- packages/x-codemod/src/v6.0.0/pickers/preset-safe/expected.spec.js
- packages/x-codemod/src/v6.0.0/pickers/preset-safe/index.ts
- packages/x-codemod/src/v6.0.0/pickers/rename-inputFormat-prop/actual-props.spec.js
- packages/x-codemod/src/v6.0.0/pickers/rename-inputFormat-prop/expected-props.spec.js
- packages/x-codemod/src/v6.0.0/pickers/rename-inputFormat-prop/index.ts
- packages/x-codemod/src/v6.0.0/pickers/rename-inputFormat-prop/rename-inputFormat-prop.test.ts
> [codemod] Add pickers `rename-inputFormat-prop` codemod

- docs/data/data-grid/localization/data.json
- packages/grid/x-data-grid/src/locales/index.ts
- packages/grid/x-data-grid/src/locales/urPK.ts
- scripts/x-data-grid-premium.exports.json
- scripts/x-data-grid-pro.exports.json
- scripts/x-data-grid.exports.json
>  [l10n] Add Urdu (ur-PK) locale

- packages/grid/x-data-grid/src/locales/frFR.ts
> [l10n] Improve French (fr-FR) locale

- docs/tslint.json
- renovate.json
This package was probably removed some time ago, but config file as well as renovate rule has been left behind. 🙈
> [core] Remove `tslint` package leftovers

- packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx
- packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts
Part of https://github.com/mui/mui-x/pull/7834#pullrequestreview-1285351956
> [fields] Allow to select year 2000 on 2-digit year section

- packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx
- packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts
- packages/x-date-pickers/src/internals/hooks/useField/useFieldCharacterEditing.ts
Fixes first point (video) in https://github.com/mui/mui-x/pull/7834#pullrequestreview-1285351956.
> [fields] Fix year editing on `day.js`

- packages/x-date-pickers-pro/src/tests/describeRangeValidation/describeRangeValidation.tsx
- packages/x-date-pickers/src/tests/describeValidation/describeValidation.tsx
- packages/x-date-pickers/src/tests/describeValue/describeValue.tsx
Follow up on https://github.com/mui/material-ui/pull/35300 (I totally forgot :grimacing: )
> [core] Use `createDescribes` for `describeValue` and `describeValidation`

- packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx
- packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
- packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx
Cherry-pick of https://github.com/mui/mui-x/pull/7857
> [DataGrid] Avoid unnecessary rerenders after `updateRows`

- packages/x-codemod/src/v6.0.0/data-grid/rename-linkOperators-logicOperators/index.ts
> [codemod] Fix import path

- packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
Fixes https://github.com/mui/mui-x/pull/7857#issuecomment-1431734946
Preview: https://deploy-preview-7946--material-ui-x.netlify.app/x/react-data-grid/column-pinning/
> [DataGrid] Fix virtual scroller not updating layout after pinning the column

- docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md
https://deploy-preview-7861--material-ui-x.netlify.app/x/migration/migration-data-grid-v5/
- Add some code examples
- Reorder items for clarity
- Fix a few typos
> [docs] Improve `DataGrid` migration guide

- packages/grid/x-data-grid-premium/src/hooks/features/rowGrouping/createGroupingColDef.tsx
- packages/grid/x-data-grid-premium/src/tests/rowGrouping.DataGridPremium.test.tsx
Cherry pick #7950 
Before: https://codesandbox.io/s/hasfocus-for-row-grouping-leaves-tuw57o?file=/demo.tsx
After (v5): https://codesandbox.io/s/hasfocus-for-row-grouping-leaves-forked-61g5z6
> [DataGridPremium] Fix `leafField` to have correct focus value

- docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md
> [docs] Fix inconsistency in DataGrid migration guide

- packages/x-date-pickers-pro/src/internal/hooks/useMultiInputRangeField/useMultiInputDateRangeField.ts
- packages/x-date-pickers-pro/src/internal/hooks/useMultiInputRangeField/useMultiInputDateTimeRangeField.ts
- packages/x-date-pickers-pro/src/internal/hooks/useMultiInputRangeField/useMultiInputTimeRangeField.ts
- packages/x-date-pickers/src/internals/hooks/useField/useField.ts
- packages/x-date-pickers/src/internals/hooks/useField/useField.types.ts
- packages/x-date-pickers/src/tests/describeValue/testControlledUnControlled.tsx
> [pickers] Fix `textField` slot `error` prop propagation

- docs/data/date-pickers/date-range-field/BasicDateRangeField.js
- docs/data/date-pickers/date-range-field/BasicDateRangeField.tsx
- docs/data/date-pickers/date-range-field/BasicDateRangeField.tsx.preview
- docs/data/date-pickers/date-time-range-field/BasicDateTimeRangeField.js
- docs/data/date-pickers/date-time-range-field/BasicDateTimeRangeField.tsx
- docs/data/date-pickers/date-time-range-field/BasicDateTimeRangeField.tsx.preview
- docs/data/date-pickers/date-time-range-field/DateTimeRangeFieldValue.js
- docs/data/date-pickers/date-time-range-field/DateTimeRangeFieldValue.tsx
- docs/data/date-pickers/date-time-range-field/DateTimeRangeFieldValue.tsx.preview
- docs/data/date-pickers/time-range-field/BasicTimeRangeField.js
- docs/data/date-pickers/time-range-field/BasicTimeRangeField.tsx
- docs/data/date-pickers/time-range-field/BasicTimeRangeField.tsx.preview
- docs/data/date-pickers/time-range-field/TimeRangeFieldValue.js
- docs/data/date-pickers/time-range-field/TimeRangeFieldValue.tsx
- docs/data/date-pickers/time-range-field/TimeRangeFieldValue.tsx.preview
Align range field demos to other fields:
- remove inconsistencies between different input-type demos
- add labels to every example to better showcase a standalone example
> [docs] Fine tune range fields demos

- docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md
- packages/x-codemod/src/v6.0.0/data-grid/rename-linkOperators-logicOperators/actual.spec.js
- packages/x-codemod/src/v6.0.0/data-grid/rename-linkOperators-logicOperators/expected.spec.js
- packages/x-codemod/src/v6.0.0/data-grid/rename-linkOperators-logicOperators/index.ts
Final remaining piece of #7086
> [codemod] Add `apiRef.current.getRowIndex` to `DataGrid` renaming codemod

- docs/data/data-grid/accessibility/accessibility.md
An opportunity was encountered at https://mui.zendesk.com/agent/tickets/7043. Going forward, this introduction would be much better moved into a more general page. It's way more general than the data grid.
> [docs] Update Accessibility to be more up to date

- docs/pages/x/api/data-grid/data-grid-premium.json
- docs/pages/x/api/data-grid/data-grid-pro.json
- docs/pages/x/api/data-grid/data-grid.json
- docs/translations/api-docs/data-grid/data-grid-premium.json
- docs/translations/api-docs/data-grid/data-grid-pro.json
- docs/translations/api-docs/data-grid/data-grid.json
- packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx
- packages/grid/x-data-grid/src/material/index.ts
- packages/grid/x-data-grid/src/models/gridSlotsComponent.ts
- packages/grid/x-data-grid/src/models/gridSlotsComponentsProps.ts
- scripts/x-data-grid-premium.exports.json
- scripts/x-data-grid-pro.exports.json
- scripts/x-data-grid.exports.json
This is necessary for Joy UI integration
> [data grid] Extract `BaseInputLabel` slot

- docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md
- docs/data/migration/migration-pickers-v5/migration-pickers-v5.md
Update migration guide and adapt instructions to match stable release
> [docs] Update migration guide for stable release

- docs/data/data-grid/localization/data.json
- packages/grid/x-data-grid/src/locales/csCZ.ts
> [l10n] Import Czech (cs-CZ) locale (from @BlastyCZ)

- docs/data/date-pickers/localization/data.json
- packages/x-date-pickers/src/locales/frFR.ts
translating to French the toolbar titles
> [l10n] Import French (fr-FR) locale

- docs/data/date-pickers/localization/data.json
- packages/x-date-pickers/src/locales/heIL.ts
- packages/x-date-pickers/src/locales/index.ts
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
Fix #8217
Added Hebrew/Israel locale to x-date-pickers
> [l10n] Add Hebrew (he-IL) locale to pickers

- dangerfile.js
Small fix on generated previews:
```diff
-x//path-to-see/...
+x/path-to-see/...
```
> [core] remove duplicated `/`

- docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md
- docs/data/migration/migration-pickers-v5/migration-pickers-v5.md
https://mui-org.slack.com/archives/C041SDSF32L/p1678829876178899
> [docs] Improve migration diff

- packages/x-date-pickers/src/internals/hooks/useField/useField.ts
> [fields] Fix editing in shadow dom

- packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx
- packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts
> [fields] Allow to reset the value from the outside

- docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md
- docs/data/migration/migration-pickers-v5/migration-pickers-v5.md
I think that it's important that we give the developer a reason why they should upgrade as a counterweight on the same page where we tell them why they shouldn't upgrade (the BCs).
To close https://github.com/mui/material-ui/pull/36354#discussion_r1118797093
> [docs] Give an incentive to upgrade

- benchmark/package.json
- yarn.lock
Closes #8209 
The package does not seem to be used anywhere.
> [core] Remove unused `visx` chart package

- packages/grid/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx
Fixes #8202 
Before: https://codesandbox.io/s/mui-data-grid-column-grouping-bug-w2ezdf?file=/demo.tsx
After: https://codesandbox.io/s/mui-data-grid-column-grouping-bug-forked-2fd7ug
> [DataGrid] Fix overflow calculation issue in column group headers

- packages/grid/x-data-grid-pro/src/hooks/features/columnReorder/useGridColumnReorder.tsx
Fixes https://github.com/mui/mui-x/issues/8316
Before: https://codesandbox.io/s/gifted-artem-8rd1y2
After: https://codesandbox.io/s/crazy-margulis-zcmszv
> [DataGridPro] Fix column reorder glitches

- packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx
- packages/x-date-pickers/src/TimeField/tests/editing.TimeField.test.tsx
- packages/x-date-pickers/src/internals/hooks/useField/useField.ts
> [fields] Fix editing when all sections are selected

- packages/x-date-pickers/src/internals/hooks/useViews.tsx
Fixes #8354 
Before: https://codesandbox.io/s/update-after-view-change-ubijzb?file=/demo.tsx
After: https://codesandbox.io/s/update-after-view-change-fixed-4qjzj9?file=/demo.tsx
> [pickers] Update `view` when `views` or `openTo` changes

- docs/data/data-grid/localization/data.json
- packages/grid/x-data-grid/src/locales/daDK.ts
Update danish translation strings for @mui-x data grid
> [l10n] Improve Danish (da-DK) locale

- docs/data/data-grid/localization/data.json
- docs/data/date-pickers/localization/data.json
- packages/grid/x-data-grid/src/locales/daDK.ts
- packages/grid/x-data-grid/src/locales/svSE.ts
- packages/x-date-pickers/src/locales/svSE.ts
Added translations to the Swedish locales
---
Related issue: #3211
> [l10n] Improve Swedish (sv-SE) locale

- packages/x-date-pickers/src/AdapterDateFnsJalali/index.ts
> [fields] Add missing tokens to `AdapterDateFnsJalali`

- packages/grid/x-data-grid-pro/src/tests/filtering.DataGridPro.test.tsx
- packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterPanel.tsx
> [DataGrid] Fix filter model buttons' display condition

- packages/x-codemod/src/util/removeObjectProperty.ts
- packages/x-codemod/src/v6.0.0/data-grid/remove-stabilized-experimentalFeatures/actual.spec.js
- packages/x-codemod/src/v6.0.0/data-grid/remove-stabilized-experimentalFeatures/expected.spec.js
> [codemod] Do not fail when props is missing

- docs/data/data-grid/localization/data.json
- packages/grid/x-data-grid/src/locales/esES.ts
Add menu manage column translation, Spanish language.
> [l10n] Improve Spanish (es-ES) locale (#8420

- packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanelPreProcessors.ts
- packages/grid/x-data-grid-pro/src/utils/domUtils.ts
- packages/grid/x-data-grid/src/components/GridRow.tsx
Fixes #7675 
Before (as shared in #8439): https://codesandbox.io/s/relaxed-nova-e0rr6k
After: https://codesandbox.io/s/elastic-sea-s08777?file=/src/App.tsx
> [DataGrid] Remove hardcoded CSS classes' usages

- docs/src/modules/components/ApiPage.js
Fix the [25 new 404 errors](https://app.ahrefs.com/site-audit/3523498/62/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cdepth%2Ccompliant%2CincomingAllLinks%2Corigin&filterId=91013c8aafad4fe1f7a0ad504eccad42&sorting=-pageRating&issueId=c64da643-d0f4-11e7-8ed1-001e67ed4656&filterCollapsed=true)
A follow-up on #8442.
> [docs] Fix 404 links

- docs/next.config.js
No longer relevant since #8442.
> [core] Remove legacy token

- docs/data/date-pickers/localization/data.json
- packages/x-date-pickers/src/locales/index.ts
- packages/x-date-pickers/src/locales/kzKZ.ts
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
> [l10n] Add Kazakh (kz-KZ) locale

- docs/data/data-grid/localization/data.json
- docs/data/date-pickers/localization/data.json
- packages/grid/x-data-grid/src/locales/ptBR.ts
- packages/x-date-pickers/src/locales/ptBR.ts
Updated both `x-date-pickers` and `x-data-grid` pt-BR locale files
#3211
> [l10n] Improve Portuguese (pt-BR) locale

- docs/data/data-grid/localization/data.json
- docs/data/date-pickers/localization/data.json
- packages/grid/x-data-grid/src/locales/nlNL.ts
- packages/x-date-pickers/src/locales/nlNL.ts
> [l10n] Improve Dutch (nl-NL) locale

- docs/data/date-pickers/calendar-systems/AdapterHijri.js
- docs/data/date-pickers/calendar-systems/AdapterHijri.tsx
- docs/data/date-pickers/calendar-systems/AdapterHijri.tsx.preview
- docs/data/date-pickers/calendar-systems/AdapterJalali.js
- docs/data/date-pickers/calendar-systems/AdapterJalali.tsx
- docs/data/date-pickers/calendar-systems/AdapterJalali.tsx.preview
- packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts
- packages/x-date-pickers/src/tests/fieldKeyboardInteraction.test.tsx
> [fields] Fix RTL navigation

- docs/public/_redirects
From https://github.com/mui/mui-x/pull/8460#discussion_r1158731405
> [docs] Fix 301 redirect

- packages/grid/x-data-grid/src/locales/urPK.ts
Update urPK.ts updated translations of Aggregation section
> [l10n] Improve Urdu (ur-PK) locale

- docs/data/date-pickers/date-calendar/CustomDay.js
- docs/data/date-pickers/date-calendar/CustomDay.tsx
> [docs] Fix `Custom day rendering` demo alignment

- docs/data/date-pickers/getting-started/getting-started.md
- docs/translations/api-docs/date-pickers/localization-provider.json
- packages/x-date-pickers/src/LocalizationProvider/LocalizationProvider.tsx
> [docs] Improve section title in Getting Started page

- docs/pages/x/api/date-pickers/date-calendar.json
- docs/pages/x/api/date-pickers/date-field.json
- docs/pages/x/api/date-pickers/date-range-picker.json
- docs/pages/x/api/date-pickers/date-time-field.json
- docs/pages/x/api/date-pickers/desktop-time-picker.json
- docs/pages/x/api/date-pickers/mobile-time-picker.json
- docs/pages/x/api/date-pickers/month-calendar.json
- docs/pages/x/api/date-pickers/single-input-date-range-field.json
- docs/pages/x/api/date-pickers/single-input-date-time-range-field.json
- docs/pages/x/api/date-pickers/single-input-time-range-field.json
- docs/pages/x/api/date-pickers/time-clock.json
- docs/pages/x/api/date-pickers/time-field.json
- docs/pages/x/api/date-pickers/year-calendar.json
- yarn.lock
Applies https://github.com/mui/material-ui/pull/36305
> [docs] Update monorepo to get the test files parsing

- docs/data/date-pickers/date-field/date-field.md
- docs/data/date-pickers/date-picker/date-picker.md
- docs/data/date-pickers/date-time-picker/date-time-picker.md
- docs/data/date-pickers/time-picker/time-picker.md
> [docs] Fix typo on picker page description

- CHANGELOG.md
- packages/x-date-pickers/src/MobileDatePicker/MobileDatePicker.test.tsx
Missed updation during release 🙈
> [docs] Fix `x-codemod` package version in changelog

- docs/data/date-pickers/calendar-systems/AdapterHijri.js
- docs/data/date-pickers/calendar-systems/AdapterHijri.tsx
- docs/data/date-pickers/calendar-systems/AdapterHijri.tsx.preview
> [docs] Fix Hijri demo

- docs/data/data-grid/column-definition/column-definition.md
Add missing commas in code example
> [docs] Fix columns special properties code example

- docs/.link-check-errors.txt
- docs/data/pages.ts
- yarn.lock
Follow up https://github.com/mui/material-ui/pull/36408
> [docs] Add icons for charts menu

- docs/data/data-grid/localization/data.json
- docs/data/date-pickers/localization/data.json
- packages/grid/x-data-grid/src/locales/zhCN.ts
- packages/x-date-pickers/src/locales/zhCN.ts
Adds missing translations for Chinese (zh-CN) locale - https://github.com/mui/mui-x/issues/3211.
> [l10n] Improve Chinese (zh-CN) locale

- docs/data/date-pickers/validation/validation.md
> [docs] Fix error in `minDateTime` `validation` page section

- packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx
- packages/x-date-pickers/src/tests/describeAdapters/describeAdapters.ts
> [core] Use `adapter.lib` instead of `adapterName` in `describeAdapters`

- docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md
- docs/data/migration/migration-pickers-lab/migration-pickers-lab.md
- docs/data/migration/migration-pickers-v5/migration-pickers-v5.md
From docs feedback
>Path of what? Were the component is used? Root of the project?
sent from https://mui.com/x/migration/migration-pickers-lab/ (from section [2. Run the code mod](https://mui.com/x/migration/migration-pickers-lab/#2-run-the-code-mod))
> [docs] clarify what <path> is

- docs/data/data-grid/demo/PopularFeaturesDemo.js
- docs/data/data-grid/demo/PopularFeaturesDemo.tsx
Fix #8619
This column can get a value of type number when the aggregation option is enabled, causing a crash as it expects the number to be a string. Fix by adding a check for the type of `params.value`.
Preview: https://deploy-preview-8617--material-ui-x.netlify.app/x/react-data-grid/demo/
> [docs] Update demo to support agregation on popular feature cell

- packages/x-date-pickers-pro/src/internal/utils/valueManagers.ts
- packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts
- packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts
- test/utils/pickers-utils.tsx
> [pickers] Remove last additional character when using LTR

- packages/grid/x-data-grid/src/components/GridPagination.tsx
Closes #8153 
Based on [this comment](https://github.com/mui/mui-x/issues/8153#issuecomment-1457656258).
Before: https://codesandbox.io/s/elastic-haslett-yc1p45?file=/package.json
After: https://codesandbox.io/s/cool-hill-7vvij9
> [DataGrid] Remove unwarranted warning log

- test/regressions/index.js
- test/utils/mochaHooks.js
The license key used for tests [has expired](https://app.circleci.com/pipelines/github/mui/mui-x/37818/workflows/db8707e1-bda0-4083-ba89-dc7ea3dae32a/jobs/217186) and needs to be updated for pipelines to be happy. 🙈
> [core] Update license key for tests

- docs/data/data-grid/localization/data.json
- packages/grid/x-data-grid/src/locales/deDE.ts
Translate missing strings to German (de-DE)
> [l10n][data grid] Improve German (de-DE) locale

- docs/data/data-grid/joy-ui/GridJoyUISlots.js
- docs/data/data-grid/joy-ui/GridJoyUISlots.tsx
- packages/grid/x-data-grid/src/joy/joySlots.tsx
Preview: https://deploy-preview-8871--material-ui-x.netlify.app/x/react-data-grid/experiments/joy-ui/
> [DataGrid] Add Joy UI pagination slot

- docs/data/data-grid/column-visibility/ColumnSelectorGridSnap.js
- docs/data/data-grid/column-visibility/ColumnSelectorGridSnap.tsx
- docs/data/data-grid/column-visibility/ColumnSelectorGridSnap.tsx.preview
- test/regressions/index.test.js
Fixes https://app.argos-ci.com/mui/mui-x/builds/10804/46814308
Fixes https://app.argos-ci.com/mui/mui-x/builds/10799/46807323
> [test] Fix flaky regression tests

- packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts
> [pickers] Fix trailing zeros inconsistency in `LuxonAdapter`

- docs/data/data-grid/clipboard/clipboard.md
See: https://github.com/mui/mui-x/pull/7389/files#r1192505245
> [docs] Typo fix in clipboard docs

- yarn.lock
> [core] Fix `yarn.lock`

- packages/grid/x-data-grid/src/locales/csCZ.ts
- packages/x-date-pickers/src/locales/csCZ.ts
Update grammar mistakes and improve translations so it's more natural to the czech reader.
> [l10n] Improve czech (cs-CZ) locale

- packages/grid/x-data-grid-generator/src/services/random-generator.ts
Fixes https://github.com/mui/mui-x/issues/9084
Before: https://codesandbox.io/s/strange-villani-19cjym?file=/demo.tsx
After: https://codesandbox.io/s/boring-drake-qlqldp?file=/demo.tsx
> [core] Fix `randomInt` producing values exceeding `max` value

- docs/data/date-pickers/localization/data.json
- packages/x-date-pickers/src/locales/index.ts
- packages/x-date-pickers/src/locales/viVN.ts
- scripts/x-date-pickers-pro.exports.json
- scripts/x-date-pickers.exports.json
> [l10n] Add Vietnamese (vi-VN) locale

- packages/x-date-pickers/src/tests/describeGregorianAdapter/testCalculations.ts
Feel free to merge it if some CI fails because of it
> [core] Fix flacky test on `dateWithTimezone` adapter test

- packages/x-charts/src/BarChart/BarElement.tsx
- packages/x-charts/src/BarChart/BarPlot.tsx
Just add CSS and classnames to bar charts the standard way
> [charts] Add style customization on bar

- docs/data/introduction/overview/overview.md
Address the following feedback: https://mui-org.slack.com/archives/C04U3R2V9UK/p1685723810368219
> [docs] Fix overview page typo
