mui/mui-x

.circleci/config.yml
package.json
scripts/deduplicate.js
yarn.lock

One chunk of #37, copy & paste from the main repository.

[test] Add yarn deduplicate step

---

.circleci/config.yml
package.json
scripts/jsonlint.js

[test] Lint JSON

---

packages/grid/x-grid-modules/src/hooks/utils/useLogger.ts

Fix #98.
I didn't test the changes, I would need #115 for doing such but I hope it's good enough, finger crossed.
This is important so we can document the data grid components.

[DataGrid] Fix SSR support

---

packages/grid/x-grid-modules/src/hooks/features/useApiRef.ts
packages/grid/x-grid-modules/src/hooks/root/useApi.ts
packages/grid/x-grid-modules/src/hooks/root/useEvents.ts

Same as #146
This time, spot in the CI

[DataGrid] Avoid logger noise

---

packages/grid/x-grid-modules/src/hooks/utils/useRafUpdate.ts

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s', 'a useEffect cleanup function'
Fix #150

[DataGrid] Fix set state leak

---

packages/grid/data-grid/README.md
packages/grid/data-grid/package.json
packages/grid/x-grid-data-generator/package.json
packages/grid/x-grid-modules/package.json
packages/grid/x-grid/README.md
packages/grid/x-grid/package.json
packages/storybook/src/documentation/pages/quick-start.stories.mdx

While it won't make any significant difference, it signals that we aim for maximum compatibility between MIT and X.
Closes #21

[DataGrid] Use same React version as core

---

package.json

[core] Improve script commands

---

babel.config.js
docs/babel.config.js
docs/src/pages/components/data-grid/pagination/AutoPaginationGrid.js
docs/src/pages/components/data-grid/pagination/AutoPaginationGrid.tsx
docs/src/pages/components/data-grid/pagination/BasicPaginationGrid.js
docs/src/pages/components/data-grid/pagination/BasicPaginationGrid.tsx
docs/src/pages/components/data-grid/pagination/ControlledPaginationGrid.js
docs/src/pages/components/data-grid/pagination/ControlledPaginationGrid.tsx
docs/src/pages/components/data-grid/pagination/SizePaginationGrid.js
docs/src/pages/components/data-grid/pagination/SizePaginationGrid.tsx
docs/src/pages/components/data-grid/pagination/pagination.md
packages/grid/x-grid-data-generator/package.json
packages/grid/x-grid-data-generator/src/commodities.columns.tsx
packages/grid/x-grid-data-generator/src/employees.columns.tsx
packages/grid/x-grid-data-generator/src/services/random-generator.ts
packages/grid/x-grid-data-generator/src/services/real-data-service.ts
packages/grid/x-grid-data-generator/src/useDemoData.ts
packages/storybook/src/stories/playground/real-data-demo.stories.tsx
tsconfig.json
webpackBaseConfig.js
yarn.lock

I had to solve an issue with the generation of fake data. The page was toooo slow to load. I wanted to keep the demo as simple as possible while retaining acceptable performance. I ended-up switching [faker](https://github.com/Marak/faker.js) to [chance](https://github.com/chancejs/chancejs). This lead to an x20 improvement of runtime to generate the fake data (from 800ms to 40ms) and x5 reduction of bundle size (from 358 to [63 kB](https://bundlephobia.com/result?p=chance) gzipped).
We might have more opportunities to improve the performance in the future, I suspect that once we display 10 grid on the same page of the documentation, we will be able to gain by caching the generated fake rows.

[docs] Move the pagination page

---

packages/grid/x-grid-modules/src/hooks/virtualization/useVirtualColumns.ts
packages/grid/x-grid-modules/src/hooks/virtualization/useVirtualRows.ts

[DataGrid] Fix focus cell visibility 

---

docs/src/pages/components/data-grid/columns/columns.md
docs/src/pages/components/data-grid/export/export.md
docs/src/pages/components/data-grid/getting-started/getting-started.md
docs/src/pages/components/data-grid/group-pivot/group-pivot.md
docs/src/pages/components/data-grid/overview/overview.md
docs/src/pages/components/data-grid/pagination/pagination.md
docs/src/pages/components/data-grid/rows/rows.md
docs/src/pages/components/data-grid/selection/selection.md

More accessible and give a bit more context:

[docs] Add more context on the ⚡️ icons

---

packages/grid/x-grid-modules/src/components/styled-wrappers/GridRootStyles.ts

[DataGrid] Add dark mode scrollbar

---

packages/grid/data-grid/src/DataGrid.test.tsx
packages/grid/x-grid-modules/src/hooks/features/usePagination.ts
packages/grid/x-grid/src/XGrid.test.tsx
packages/storybook/src/stories/grid-pagination.stories.tsx

[DataGrid] Fix setPage not working

---

packages/grid/x-grid-modules/src/components/checkbox-renderer.tsx

[DataGrid] Fix checkbox selection issue

---

docs/pages/api-docs/data-grid.md
docs/pages/api-docs/x-grid.md
docs/src/pages/components/data-grid/rendering/CustomEmptyOverlayGrid.js
docs/src/pages/components/data-grid/rendering/CustomEmptyOverlayGrid.tsx
packages/grid/x-grid-modules/src/components/styled-wrappers/GridOverlay.tsx
packages/grid/x-grid-modules/src/components/styled-wrappers/GridRootStyles.ts

A continuation on https://github.com/mui-org/material-ui-x/pull/268/files#r487562268. I couldn't spot any visual regression. A lighter DOM = faster rendering & easier customizations.

[DataGrid] Remove .MuiDataGrid-overlayContent node

---

README.md
docs/src/pages/components/data-grid/columns/columns.md
docs/src/pages/components/data-grid/getting-started/getting-started.md
docs/src/pages/components/data-grid/overview/overview.md
docs/src/pages/components/data-grid/rows/ServerSortingGrid.js
docs/src/pages/components/data-grid/rows/ServerSortingGrid.tsx

Also rename `Sticky columns` into `Column pinning`.

[docs] Fix layout jump issue

---

docs/src/pages/components/data-grid/columns/columns.md
docs/src/pages/components/data-grid/overview/overview.md
docs/src/pages/components/data-grid/pagination/pagination.md
docs/src/pages/components/data-grid/rendering/rendering.md
docs/src/pages/components/data-grid/rows/rows.md
docs/src/pages/components/data-grid/selection/selection.md

[docs] Avoid double borders

---

packages/grid/_modules_/grid/hooks/root/useRows.ts
packages/grid/_modules_/grid/models/__tests__/rows.tests.ts
packages/grid/_modules_/grid/models/rows.ts
packages/storybook/src/stories/grid-sorting.stories.tsx

[DataGrid] Throw if rows id is missing

---

packages/demo-app/src/app/app.tsx
packages/demo-app/src/app/demos/grid/components/settings-panel.tsx
packages/grid/_modules_/grid/components/checkbox-renderer.tsx
packages/grid/_modules_/grid/components/default-footer.tsx
packages/grid/_modules_/grid/hooks/features/usePagination.ts
packages/grid/_modules_/grid/hooks/features/useSelection.ts
packages/grid/_modules_/grid/hooks/root/useEvents.ts
packages/grid/_modules_/grid/hooks/root/useKeyboard.ts
packages/grid/_modules_/grid/hooks/root/useRows.ts
packages/storybook/src/stories/grid-error.stories.tsx
packages/storybook/src/stories/grid-pagination.stories.tsx
packages/storybook/src/stories/grid-sorting.stories.tsx
packages/x-license/src/useLicenseVerifier.ts

The fewer dependencies in the array, the simpler to understand when it updates. Ref, setState, setReducer never change during a mount lifecycle.

[core] Remove dead-code

---

docs/src/pages/components/data-grid/rendering/rendering.md
packages/grid/_modules_/grid/GridComponent.tsx
packages/grid/_modules_/grid/components/AutoSizer.tsx
packages/grid/data-grid/src/DataGrid.test.tsx

[DataGrid] Improve warning and docs for layouting

---

packages/grid/_modules_/grid/hooks/virtualization/useVirtualRows.ts

This PR fixes an iOS scroll stretching issue that is visible when the user tries to scroll left while the grid is at the left position of 0. The issue occurs because when you scroll on an IOS device a scroll event is fired even if there is no space to scroll in that direction (scroll bouncing).
The fix is achieved by checking the `event.target.scrollLeft` and if it is < 0 prevent the update of the viewport.
Fixes #269

[DataGrid] Fix iOS issue when scrolling left

---

.browserslistrc
test/karma.conf.js

Apply https://github.com/mui-org/material-ui/pull/22814, next, we will need to match the bundling strategy of the core.

[core] Sync supported browser with v5

---

CHANGELOG.md
docs/CHANGELOG.md
packages/demo-app/CHANGELOG.md
packages/eslint-plugin-material-ui/CHANGELOG.md
packages/grid/data-grid/CHANGELOG.md
packages/grid/x-grid/CHANGELOG.md
packages/storybook/CHANGELOG.md
packages/x-grid-data-generator/CHANGELOG.md
packages/x-license/CHANGELOG.md

Final touches needed for the v4.0.0-alpha.7 release.
Updated the root changelog and removed the rest of the nested changelogs.

[CHANGELOG] Add v4.0.0-alpha.7

---

packages/grid/_modules_/grid/GridComponent.tsx
packages/grid/_modules_/grid/components/AutoSizer.tsx
packages/grid/_modules_/grid/components/column-header-item.tsx
packages/grid/_modules_/grid/components/column-header-separator.tsx
packages/grid/_modules_/grid/components/column-headers.tsx
packages/grid/_modules_/grid/components/styled-wrappers/GridRootStyles.ts
packages/grid/_modules_/grid/hooks/features/useColumnResize.tsx
packages/grid/_modules_/grid/utils/material-ui-utils.ts

- Fix #177
- Fix #191
- Fix #209
- Fix initial mouse move width jump
- Fix scrolling on the last column
- Fix alternatives button clicks, e.g. if you click on the previous page button while your mouse is over the dragging area, it fails.
- Fix interaction area, the whole separator should be interactive
- Fix keep resizing even after releasing the mouse

[XGrid] Second iteration on resizing logic

---

packages/grid/data-grid/src/DataGrid.test.tsx

The test was skipped in #412.
@eps1lon In this case, we are only interested in testing that the error boundary reports the problem. It's the same as https://github.com/mui-org/material-ui/blob/db3581f75f88905e2791560c0527010f98a92a9b/packages/material-ui/src/Select/Select.test.js#L849.
Is there a way to ignore the console.error calls? I guess @dtassone has skipped the test because it wasn't obvious, at first sight, what was the solution. But anyway, it's probably an edge case, we can move forward like this :)

[DataGrid] Restore regression test

---

packages/grid/data-grid/package.json
packages/grid/data-grid/src/DataGrid.tsx
packages/grid/x-grid/package.json
packages/grid/x-grid/src/XGrid.tsx
yarn.lock

[DataGrid] Replace require with import

---

packages/grid/_modules_/grid/hooks/features/virtualization/useVirtualRows.ts
packages/grid/_modules_/grid/hooks/utils/useScrollFn.ts

This PR is a refactoring that allows to sync the columns scrolling with the viewport scrolling and execute the scroll together. 
It fixes a slight misalignment that can occur between frames

[DataGrid] Refactor columns scrolling

---

packages/grid/_modules_/grid/hooks/features/useApiRef.ts
packages/grid/_modules_/grid/models/api/coreApi.ts
packages/grid/_modules_/grid/utils/EventEmitter.ts

webpack v5 does no longer polyfill Node.js modules https://webpack.js.org/blog/2020-10-10-webpack-5-release/. This fixes the component under this environment. It replaces https://github.com/browserify/events with a custom version. Help with #447.
It should also remove some bundle size, using a simplified version of the polyfill used by webpack v4.

[DataGrid] Fix webpack v5

---

packages/grid/_modules_/grid/components/ScrollArea.tsx
packages/grid/_modules_/grid/hooks/features/core/useGridState.ts
packages/grid/_modules_/grid/hooks/features/virtualization/renderingState.ts
packages/grid/_modules_/grid/hooks/features/virtualization/useVirtualRows.ts
packages/grid/_modules_/grid/hooks/utils/useRafUpdate.ts
packages/grid/_modules_/grid/hooks/utils/useScrollFn.ts
packages/grid/_modules_/grid/models/api/coreApi.ts
packages/grid/_modules_/grid/models/api/virtualizationApi.ts
packages/grid/_modules_/grid/models/params/index.ts
packages/grid/_modules_/grid/models/params/scrollParams.ts
packages/grid/x-grid/src/XGrid.test.tsx

This PR allows to coordinates all calls to requestAnimationFrame
It fixes the raf violation

[DataGrid] Raf Timer stored in apiRef

---

packages/grid/_modules_/grid/hooks/utils/useScrollFn.ts

Reduce the green flash surface areas reported by Chrome. It was raised in https://twitter.com/XCSme/status/1323303435152838656 by @Cristy94.
For more context: https://developers.google.com/web/fundamentals/performance/rendering/simplify-paint-complexity-and-reduce-paint-areas.

[DataGrid] Avoid paint step

---

packages/grid/_modules_/grid/GridComponent.tsx
packages/grid/_modules_/grid/components/AutoSizer.tsx
packages/grid/_modules_/grid/hooks/features/core/gridState.ts
packages/grid/_modules_/grid/hooks/features/core/useGridReducer.ts
packages/grid/_modules_/grid/hooks/features/core/useGridSelector.ts
packages/grid/_modules_/grid/hooks/features/pagination/paginationReducer.ts
packages/grid/_modules_/grid/hooks/features/virtualization/useVirtualRows.ts
packages/grid/_modules_/grid/hooks/utils/useLogger.ts
packages/grid/_modules_/grid/models/api/virtualizationApi.ts
packages/grid/_modules_/grid/utils/material-ui-utils.ts
packages/grid/data-grid/src/DataGrid.test.tsx

Apply the feedback forgotten from #412

[DataGrid] Apply review from #412

---

packages/grid/_modules_/grid/components/default-footer.tsx
packages/grid/_modules_/grid/components/pagination.tsx
packages/grid/_modules_/grid/components/styled-wrappers/GridRootStyles.ts

Fixes #440 
This PR aims to solve the issue of having the `Total Rows` and  `rows selected` counts hidden on small screens. I didn't change the styling but only made the 2 files visible.

[DataGrid] Fix display of row count and selected rows on mobile

---

docs/next.config.js
yarn.lock

The introduction of a second GitHub repository means that we can no longer hard-code the URL in the documentation, if we do, we won't point to the right position. https://github.com/mui-org/material-ui/pull/23390 allows configuring the underlying repository, and this PR leverage it. For instance, these two links are now correct:
Proof: https://deploy-preview-538--material-ui-x.netlify.app/components/data-grid/rows/

[docs] Fix links to GitHub

---

docs/pages/api-docs/data-grid.md
docs/pages/api-docs/x-grid.md
docs/src/pages/components/data-grid/getting-started/getting-started.md
docs/src/pages/components/data-grid/overview/overview.md
packages/grid/_modules_/grid/components/styled-wrappers/GridRootStyles.ts
packages/grid/_modules_/grid/lib/createDetectElementResize/index.js

- [docs] Duplicate the information 3827157: We have seen some people struggling to find these pages. It will be much better with a link in the header to the WIP pricing page.
- [docs] Add plain string the watermark so it can be searched b191919: We had people struggling to find how to install the license key. I suspect it's also because the email goes into the junk.
- [DataGrid] Improve dark mode scrollbar e8d296f: Leverage the findings from https://github.com/mui-org/material-ui/pull/23407
- [AutoSizer] hedge against CSS leak 7f08c99: The .resize-triggers CSS seemed too generic for my taste.
I have prefixed it with Mui. Also an opportunity to remove dead logic.
- [docs] Fix 404 link 63391b7

[core] Batch small changes

---

docs/src/pages/components/data-grid/getting-started/getting-started.md

This PR fixed the `Getting Started` part of the `DataGrid` documentation, showing that we have the Column Reorder feature available on the enterprise version of the grid.

[docs] Update feature comparison table for Column reorder

---

netlify.toml
packages/grid/x-grid/src/XGrid.test.tsx
test/karma.tests.js
yarn.lock

Also, enable caching for the documentation with Next.js and Netlify, it should build faster.

[test] Share karma setup

---

packages/grid/_modules_/grid/hooks/features/selection/selectionSelector.ts
packages/grid/tsconfig.build.json

Closes #573
What I did:
- Prevent `*.test.*` to go through types generation
- Help createSelector to find its right typings

[DataGrid] Fix type definitions

---

packages/grid/_modules_/grid/GridComponent.tsx
packages/grid/_modules_/grid/utils/getTotalHeight.ts

Fixes #502
This PR aims to fix an issue that occurs when the autoHeight prop is set and a custom header and/or footer is provided. The bug is that the height of the grid, in that case, is not calculated correctly. That results in the last rows being hidden.

[DataGrid] Fix autoHeight computation for custom headers and footers

---

packages/grid/_modules_/grid/GridComponent.tsx
packages/grid/_modules_/grid/hooks/features/sorting/useSorting.ts
packages/grid/data-grid/src/DataGrid.test.tsx
packages/grid/x-grid/src/XGrid.test.tsx
packages/storybook/src/stories/grid-sorting.stories.tsx

[DataGrid] Reset sortedRows state on prop change

---

docs/src/pages.js

https://github.com/mui-org/material-ui-x/issues/568#issuecomment-731592420, same treatment that for the date picker.
Twin with https://github.com/mui-org/material-ui/pull/23643

[docs] DataGrid is in the lab

---

docs/src/pages/components/data-grid/export/export.md

Removed Import reference in titles as there are no other references to imports or import features. It becomes misleading.

[docs] Reduce confusion on /export page

---

packages/grid/_modules_/grid/components/tools/FilterForm.tsx

[DataGrid] Fix filter flex-shrink

---

packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx
packages/grid/_modules_/grid/components/menu/GridMenu.tsx
packages/grid/_modules_/grid/components/menu/columnMenu/ColumnsMenuItem.tsx
packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenu.tsx
packages/grid/_modules_/grid/components/menu/columnMenu/SortMenuItems.tsx
packages/grid/_modules_/grid/components/panel/ColumnsPanel.tsx
packages/grid/_modules_/grid/components/panel/Panel.tsx
packages/grid/_modules_/grid/components/panel/filterPanel/FilterForm.tsx

I didn't describe the bugs I went after, happy to do so if somebody wants the information.
The last items I **didn't** handle:
1. The keyboard navigation on the column menu popup is broken, this API isn't possible, it needs `MenuList > MenuItem` to work:
https://github.com/mui-org/material-ui-x/blob/b844a259edb21e777e1a72719ae8f9e56605e695/packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenu.tsx#L75-L85
2. The distance the mouse has to travel could be reduced:
3. The close icon could be disabled, it lures you into thinking it can be clicked but it does nothing:

[DataGrid] Improve DX popups

---

packages/grid/_modules_/grid/components/default-footer.tsx
packages/grid/_modules_/grid/components/selected-row-count.tsx
packages/grid/_modules_/grid/components/styled-wrappers/GridRootStyles.ts

Fixes #638 with the part around by reducing the breakpoint threshold from `md` to `sm`.
> Footer […] selected rows disappear on adding pagination
**Before**
**After**

[DataGrid] Simplify footer logic

---

packages/grid/data-grid/src/DataGrid.test.tsx
packages/grid/x-grid/src/XGrid.test.tsx
test/utils/index.ts
test/utils/index.tsx

@DanailH Could you test that these changes [allow removing the `strict: false`](https://github.com/mui-org/material-ui-x/pull/606/files#diff-376d9a2f4302fcb871a0a80f03b87f87c3d701f71557a27ceb58d34c1cae8edcR511) from the density pull request? We face the same issue when testing the filters and column selector feature.

[test] Allow running all the tests in strict mode

---

packages/grid/data-grid/src/DataGrid.test.tsx
packages/grid/x-grid/src/XGrid.test.tsx

The regression happened in #682 but no tests were added so far. This test fail when applied on 920f74c0bdc5132f4551033a5f15762d77590807.

[test] Add regression test

---

packages/grid/_modules_/grid/hooks/features/sorting/useSorting.ts
packages/grid/data-grid/src/DataGrid.test.tsx

There seem to be a few cases where applySorting is being called without checking if it's being handled by the server first. This leads to cases where the server response sends sorted rows but the client re-sorts the page before rendering them.
First PR (here) so be easy on me if I missed something. Thanks!

[DataGrid] sortingMode=server not being honored in a few cases

---

docs/pages/api-docs/data-grid.md
docs/pages/api-docs/x-grid.md

I forgot to update the `DataGrid` and `XGrid` API pages in the docs with the new `showToolbar` and `density` props. 
This PR fixes that.

[DataGrid] Update API pages with showToolbar and density props

---

docs/pages/api-docs/data-grid.md
docs/pages/api-docs/x-grid.md
packages/grid/_modules_/grid/GridComponent.tsx
packages/grid/_modules_/grid/GridComponentProps.ts

Resolves #541 
Introduce `nonce` prop for DataGrid and XGrid. Updated docs API as well. Let me know if I missed anything or any change. 
My first PR for the Material-UI organization. You guys do excellent work! Looking forward to contribute more! 
Thanks!

[DataGrid] Add 'nonce' prop to allow inline style if user has CSP

---

docs/pages/api-docs/data-grid.md
docs/pages/api-docs/x-grid.md
packages/grid/_modules_/grid/components/Cell.tsx
packages/grid/_modules_/grid/components/RowCells.tsx
packages/grid/_modules_/grid/components/styled-wrappers/GridRootStyles.ts
packages/grid/_modules_/grid/models/colDef/colDef.ts

Fixes #381 
Tested on storybook to reproduce it before the fix and whether it works properly after the fix.

[DataGrid] Fix row cells leaking CSS 'text-align' from parent

---

packages/grid/_modules_/grid/hooks/features/columns/useColumns.ts

If we don't change the value, we don't need to clone it.

[DataGrid] Remove useless clone

---

packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx

The underlying logic is a setTimeout with no defined duration, so 0ms.
https://github.com/mui-org/material-ui-x/blob/49afdd372e58af45d24d237208457596c522add7/packages/grid/_modules_/grid/hooks/utils/useResizeContainer.ts#L17

[test] We don't need to wait 100ms

---

packages/grid/_modules_/grid/utils/paramsUtils.ts
packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx

Fixes #749 
Render empty row data if column field for `valueGetter` method is incorrect instead of app crashing.
Not sure if throwing error in console instead would be a better idea like:
```js
const col = api.getColumnFromField(field);
if(!col) {
throw new Error(`Material-UI: The field ${field} supplied to valueGetter element is invalid.`);
}
if (!col.valueGetter) {
return rowModel[field];
}
```

[DataGrid] getValueError in valueGetter if incorrect field is supplied

---

yarn.lock

[docs] Sync with docs to fix images

---

packages/grid/_modules_/grid/GridComponent.tsx
packages/grid/_modules_/grid/components/Pagination.tsx
packages/grid/_modules_/grid/components/RowCount.tsx
packages/grid/_modules_/grid/components/SelectedRowCount.tsx
packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderFilterIcon.tsx
packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx
packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderSortIcon.tsx
packages/grid/_modules_/grid/components/menu/columnMenu/ColumnsMenuItem.tsx
packages/grid/_modules_/grid/components/menu/columnMenu/FilterMenuItem.tsx
packages/grid/_modules_/grid/components/menu/columnMenu/HideColMenuItem.tsx
packages/grid/_modules_/grid/components/menu/columnMenu/SortMenuItems.tsx
packages/grid/_modules_/grid/components/panel/ColumnsPanel.tsx
packages/grid/_modules_/grid/components/panel/filterPanel/FilterForm.tsx
packages/grid/_modules_/grid/components/panel/filterPanel/FilterPanel.tsx
packages/grid/_modules_/grid/components/toolbar/ColumnsToolbarButton.tsx
packages/grid/_modules_/grid/components/toolbar/FilterToolbarButton.tsx
packages/grid/_modules_/grid/constants/localeTextConstants.ts
packages/grid/_modules_/grid/models/api/localeTextApi.ts

Fixes #196 
This is the follow up PR with the rest of the text now being converted to use the `getLocaleText` API

[DataGrid] Convert remaining text to use locale text API

---

packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx

The test that we have added in #673 is unrelated to the issue and solves no problems (we could remove the test it wouldn't make a difference). We were relying on the fact that `stopPropagation()` is no longer call. But that's not what we need to assert. We need to make sure the event doesn't prevent default. The updated test should be correct and prevent regressions now.
I have started looking at #794, then, I realized that the whole section inside https://github.com/mui-org/material-ui-x/pull/673/files#diff-2cb5cd44894a9bd734c47410669a07af73de0e7ff1b69f5488453ee1159da470R235 is a dead code. So I kept exploring. Yes, it creates regressions. I'm opening new issues.

[test] Make the test actually test what we need

---

docs/pages/api-docs/data-grid.md
docs/pages/api-docs/x-grid.md
docs/src/pages/components/data-grid/columns/ColumnMenuGrid.js
docs/src/pages/components/data-grid/columns/ColumnMenuGrid.tsx
docs/src/pages/components/data-grid/columns/columns.md
packages/grid/_modules_/grid/models/colDef/colDef.ts
packages/grid/_modules_/grid/models/gridOptions.tsx

Fixes #813 
Added docs and examples for the column menu. It turns out the menu is mentioned on the `Filtering` page but I added a menu specific explanation un the `Columns` page and added a link to the filtering specific usage of the menu.
Also updated the API docs with the new `disableColumnMenu` prop.

[docs] Add documentation for the column menu

---

docs/src/pages/components/data-grid/columns/columns.md
packages/grid/data-grid/src/tests/toolbar.DataGrid.test.tsx

Fixes #345 
Part 2 of "Implement Column selector" - tests

[DataGrid] Add tests for column selector

---

packages/grid/_modules_/grid/hooks/features/pagination/usePagination.ts
packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
yarn.lock

Fix #816, onPageChange firing multiple times

[DataGrid] Fix onPageChange firing too often

---

docs/src/pages/components/data-grid/accessibility/accessibility.md
docs/src/pages/components/data-grid/columns/columns.md
docs/src/pages/components/data-grid/editing/editing.md
docs/src/pages/components/data-grid/export/export.md
docs/src/pages/components/data-grid/filtering/filtering.md
docs/src/pages/components/data-grid/getting-started/getting-started.md
docs/src/pages/components/data-grid/group-pivot/group-pivot.md
docs/src/pages/components/data-grid/localization/localization.md
docs/src/pages/components/data-grid/overview/overview.md
docs/src/pages/components/data-grid/pagination/pagination.md
docs/src/pages/components/data-grid/rendering/rendering.md
docs/src/pages/components/data-grid/rows/rows.md
docs/src/pages/components/data-grid/selection/selection.md

To wrap up #441 
I tried applying the changes mentioned in step 2 from [this comment](https://github.com/mui-org/material-ui-x/pull/855#pullrequestreview-569244937) but there were issues with building the docs that I didn't manage to resolve quickly. Eventually, we would need to spend some more time to make it work and have all the examples in v5.

[DataGrid] Update docs to reflect v5 support

---

packages/grid/_modules_/grid/hooks/features/keyboard/useKeyboard.ts
packages/grid/_modules_/grid/utils/domUtils.ts
packages/grid/_modules_/grid/utils/keyboardUtils.ts
packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx
test/utils/helperFn.ts

[DataGrid] Fix shift+space keyboard regression to select row

---

packages/grid/_modules_/grid/components/Pagination.tsx

Closes https://github.com/mui-org/material-ui-x/issues/847 
I've tried the silution proposed in https://github.com/mui-org/material-ui-x/issues/847#issuecomment-759410424 but there was a problem (when **there is no select** for rows per page, the caption which we want to show is immediately after the `$spacer` and it was hidden).
The only viable difference I could find between the two captions, was that the one which is used as label have `id`, so I used that information. Honestly, it would have been much easier, if the `TablePagination` had different classes for these two elements.
Not sure if this is the best fix, but I am open to other ideas. I was trying to come up with some sibling selector, but I couldn't do it, as the same class is used on both places.
Not sure what's the best way …

[DataGrid] Fix footer count not showing on small screens

---

packages/grid/_modules_/grid/components/Pagination.tsx

Fix input display: 
Visible on grid with width higher than 960px, ie.
https://material-ui-x.netlify.app/storybook/?path=/story/x-grid-tests-pagination--pagination-default

[DataGrid] Fix footer visual regression

---

packages/grid/_modules_/grid/components/containers/GridRootStyles.ts

Noticed in https://github.com/mui-org/material-ui-x/issues/936.
A reproduction:
- Open: https://codesandbox.io/s/material-demo-forked-4sexv?file=/demo.js
- Make sure the iframe is small enough
- Notice the footer:
- Select all the checkboxes, different height

[DataGrid] Fix unstable footer height

---

packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx
packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenuItems.tsx

[DataGrid] Fix the accessibility of the column menu

---

packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderTitle.tsx

The text is already available as a child. AFAIK, the aria-label adds nothing, it's noise. I had a look at https://accessible360.com/accessible360-blog/use-aria-label-screen-reader-text/ regarding the pros & cons of aria-label vs. sr-only text while it doesn't concern us here, it's interesting.

[DataGrid] Remove duplicate aria-label

---

packages/grid/data-grid/src/DataGrid.tsx

See https://github.com/facebook/prop-types for more details, both API works but the latter is true to what's documented, it's also the variant we use in the main repository.

[core] Fix usage of the prop-types API

---

.github/ISSUE_TEMPLATE/1.bug.md
.github/ISSUE_TEMPLATE/2.feature.md

An idea, then, we can write a bot to add the right label on the issue based on the plan the customer has purchased. The main flaw I see is, how do we guarantee that the order id is legit? Not copied from another issue.

[core] Add 'Order id 💳' section in issues

---

docs/src/pages/components/data-grid/filtering/FilterOperators.js
docs/src/pages/components/data-grid/filtering/FilterOperators.tsx
docs/src/pages/components/data-grid/filtering/filtering.md

[Fixing the failed checks right now]
While I started to use MaterialUI's DataGrid I struggled to figure out how to use non-string operators for filtering.
The example about custom filters touches this topic, but was a bit too advanced for my use case.
This is why I think it could be good to have an easy example in the docs to show the different filterOperators in action.
I'm not a born JS/TS developer, so please let me know if you see any issues with the demo :)

[docs] Improve docs of DataGrid about filter operators

---

docs/src/pages/components/data-grid/rendering/AutoHeightGrid.js
docs/src/pages/components/data-grid/rendering/AutoHeightGrid.tsx
packages/grid/_modules_/grid/components/containers/GridWindow.tsx
packages/grid/_modules_/grid/hooks/utils/useResizeContainer.ts
packages/grid/_modules_/grid/utils/getTotalHeight.ts

Sorry, I got more stuff to attent to before I could have a look at the problem:
Closes #977.
I have tried to explain what's going on in the comment. Previously, we had no timing guarantee, we were lucky (no matter where the AutoSizer is in the React tree). After 64ba484c094c3fe728fbfbcbf3ac7c772a728da9 was merged, we lost a rerender which made the last render happen before the ref of the container is resolved. The fix is the first commit, the rest is cleanup.

[DataGrid] Fix timing guarentee

---

packages/grid/data-grid/src/DataGrid.tsx

Apply the same fix as @eps1lon did in the main repo: https://github.com/mui-org/material-ui/pull/24747. It will allow to automatic generation of the documentation and stripping the prop-types from the production bundle once we use [the babel plugin](https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types) dedicated to it (-0.3kB gzipped now and a lot more saving once we generate the docs automatically)

[core] Improve prop-types handling

---

docs/src/pages/components/data-grid/sorting/ServerSortingGrid.js
docs/src/pages/components/data-grid/sorting/ServerSortingGrid.tsx
packages/grid/_modules_/grid/hooks/features/filter/useFilter.ts
packages/grid/x-grid-data-generator/src/useDemoData.ts

Improve the DX when this error occurs, as well as throw **ahead of time** (it should throw when opening the page, without any interaction). The need for the changes was surfaced with #974. It's not OK to mutate the data returned by `useDemoData` as it's stored in a state. Modifications are shared between two renders as well as two different mounts (trough caching).
It works, see https://deploy-preview-979--material-ui-x.netlify.app/components/data-grid/filtering/ that throws with:
#975 should be merged first.

[docs] Catch leaks ahread of time

---

docs/src/pages/components/data-grid/localization/localization.md
packages/grid/_modules_/grid/components/panel/filterPanel/FilterForm.tsx
packages/grid/_modules_/grid/constants/localeTextConstants.ts
packages/grid/_modules_/grid/index.ts
packages/grid/_modules_/grid/locales/bgBG.ts
packages/grid/_modules_/grid/locales/index.ts
packages/grid/_modules_/grid/models/api/localeTextApi.ts
packages/grid/_modules_/grid/models/colDef/dateOperators.ts
packages/grid/_modules_/grid/models/colDef/stringOperators.ts
packages/grid/_modules_/grid/models/filterOperator.ts
packages/grid/_modules_/grid/utils/getLocalization.ts
packages/grid/_modules_/grid/utils/index.ts

Fixes #777 
This PR adds 'bgBG' locale OTB. Currently, if you want to use that locale you would need to provide it to the grid in the following way:
```jsx
import { DataGrid, bgBG } from '@material-ui/data-grid'
...
<DataGrid localeText={bgBG.components.MuiDataGrid.defaultProps.localeText} />
```
The reason is that we want to make it work with `createMuiTheme` and this is the v5 structure https://material-ui.com/guides/localization/#locale-text - #984
In a separate PR I'll add the ability to set the locale using `createMuiTheme` because currently, we are missing an identifier for the grid, a.k.a `MuiDataGrid`.
PS: I found that I missed a couple of labels so I added them as well.

[DataGrid] Add bgBG locale

---

packages/grid/_modules_/grid/hooks/features/useApiRef.ts

Effectively, it means that we can stop documenting `useApiRef`, and replace it completely in the public API with:
```jsx
function MyApp() {
const apiRef = React.useRef();
return <DataGrid apiRef={apiRef} />
}
```
It's a logical follow-up with the direction taken in #933. More details in https://github.com/mui-org/material-ui-x/pull/939#discussion_r567235523. I like the approach, at least, it's sounds and consistent with the rest of the codebase. You can find the same API on, the Tabs for instance (`action` prop).

[DataGrid] Resolve the api ref at the same time as any other ref

---

packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderItem.tsx
packages/grid/_modules_/grid/hooks/features/sorting/useSorting.ts
packages/grid/_modules_/grid/models/colDef/colDef.ts
packages/grid/_modules_/grid/models/colDef/stringColDef.ts
packages/storybook/src/stories/grid-filter.stories.tsx
packages/storybook/src/stories/grid-options.stories.tsx
packages/storybook/src/stories/grid-sorting.stories.tsx
packages/storybook/src/stories/playground/customize-components.stories.tsx

- [DataGrid] Remove `sortDirection` from column definitions. Consolidate around fewer ways of doing the same thing.
```diff
-columns[1] = { ...columns[1], sortDirection: 'asc' };
return (
<div className="grid-container">
-   <DataGrid rows={rows} columns={columns} />
+   <DataGrid rows={rows} columns={columns} sortModel={[{field: columns[1].field, sort: 'asc'}]} />
</div>
```
---
fix #244

[DataGrid] Remove sortDirection from column definitions

---

docs/src/pages/components/data-grid/pagination/ApiRefPaginationGrid.js
docs/src/pages/components/data-grid/pagination/ApiRefPaginationGrid.tsx
docs/src/pages/components/data-grid/pagination/ControlledPaginationGrid.js
docs/src/pages/components/data-grid/pagination/ControlledPaginationGrid.tsx
docs/src/pages/components/data-grid/pagination/ServerPaginationGrid.js
docs/src/pages/components/data-grid/pagination/ServerPaginationGrid.tsx
packages/grid/_modules_/grid/components/Pagination.tsx
packages/grid/_modules_/grid/hooks/features/keyboard/useKeyboard.ts
packages/grid/_modules_/grid/hooks/features/pagination/paginationReducer.ts
packages/grid/_modules_/grid/hooks/features/pagination/usePagination.ts
packages/grid/_modules_/grid/hooks/features/virtualization/useVirtualRows.ts
packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
packages/grid/x-grid/src/tests/pagination.XGrid.test.tsx
packages/storybook/src/stories/grid-pagination.stories.tsx

- [DataGrid] Change page index base, from 1 to 0. This change is done for consistency with `TablePagination` and JavaScript arrays that are 0-based. Material-UI still uses a 1-base page for the `Pagination` component that matches the URL's query.
```diff
-const [page, setPage] = React.useState(1);
+const [page, setPage] = React.useState(0);
return (
<div className="grid-container">
<DataGrid rows={rows} columns={columns} page={page} />
</div>
```
---
fix #852

[DataGrid] Change page index base, from 1 to 0

---

packages/grid/_modules_/grid/constants/envConstants.ts

PR for @oliviertassinari to try out his proposed fix for #836
Fixes #836
Alternative PR to #1028

[DataGrid] Fix process is not defined (EXPERIMENTAL_ENABLED)

---

docs/src/pages/components/data-grid/localization/localization.md
packages/grid/_modules_/grid/components/panel/filterPanel/FilterForm.tsx
packages/grid/_modules_/grid/models/filterOperator.ts

Fixes #777 
The missing docs as mentioned in the last comment.

[docs] Add code snippet for localization docs in the data grid

---

packages/grid/_modules_/grid/components/toolbar/DensitySelector.tsx

I must have added the wrong option to check whether to disable the `DensitySelector` component. This PR fixes that and uses the correct one -> `disableDensitySelector`.

[DataGrid] Use the disableDensitySelector to disable the DensitySelector

---

packages/grid/_modules_/grid/hooks/features/pagination/usePagination.ts
packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
packages/storybook/src/stories/grid-pagination.stories.tsx

Fix #885 
- onPageChange should only fire when the underlying state change, it doesn't change when the component mount.
Fix #848

[DataGrid] Fix onPageChange and onPageSizeChange event trigger

---

.circleci/config.yml

Apply the same fix as https://github.com/mui-org/material-ui/pull/24844. The yarn cache wasn't correctly saved between different builds. It should allow faster builds.

[core] Save/restore actual yarn cache folder

---

packages/grid/_modules_/grid/components/Pagination.tsx

Solve:
Reproduction: https://codesandbox.io/s/material-demo-forked-ozptd?file=/package.json
We have made a change in the core not too long ago. I have found the issue working on https://github.com/mui-org/material-ui/pull/24663.

[DataGrid] Fix warning with v5

---

test/karma.conf.js

Same as https://github.com/mui-org/material-ui/pull/24931

[test] Avoid Rate Limit Exceeded

---

test/karma.conf.js

Leverage https://github.com/mui-org/material-ui/pull/24967
**Before**
- Build: ~18s
- Re-builds: ~2.5s
**After**
- Build: ~18s
- Re-builds: ~500ms
@eps1lon I have tested the changes in this repo, definitely works 😍. We save 2s for each iteration.

[test] Speed-up rebuild in karma

---

packages/grid/_modules_/grid/components/GridCheckboxRenderer.tsx
packages/grid/data-grid/src/tests/selection.DataGrid.test.tsx

[DataGrid] Fix checked checkbox when empty rows

---

docs/src/pages/components/data-grid/rendering/rendering.md

docs: Clarify align is separate from headerAlign
Update DataGrid rendering.md docs to clarify that align is separate from headerAlign. 
Resolves https://github.com/mui-org/material-ui-x/issues/1073

[docs] Clarify align is separate from headerAlign

---

README.md
docs/src/pages/components/data-grid/columns/columns.md
docs/src/pages/components/data-grid/export/export.md
docs/src/pages/components/data-grid/getting-started/getting-started.md
docs/src/pages/components/data-grid/group-pivot/group-pivot.md
docs/src/pages/components/data-grid/overview/overview.md
docs/src/pages/components/data-grid/pagination/pagination.md
docs/src/pages/components/data-grid/rendering/rendering.md
docs/src/pages/components/data-grid/rows/rows.md
docs/src/pages/components/data-grid/selection/selection.md
docs/src/pages/components/data-grid/sorting/sorting.md
packages/grid/x-grid/LICENSE.md
packages/x-license/LICENSE.md

Closes #1078
Interesting perspective from WordPress's founder: https://youtu.be/49HSZ4JQlHY?t=285

[docs] Clarify product split

---

packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
packages/grid/_modules_/grid/hooks/root/useGridContainerProps.ts
packages/storybook/src/stories/grid-rows.stories.tsx

fix small issue on the last row rendering 
https://material-ui-x.netlify.app/storybook/?path=/story/x-grid-tests-rows--scroll-issue

[DataGrid] Fix last row

---

test/regressions/TestViewer.js
test/regressions/index.js

Implement https://github.com/mui-org/material-ui-x/pull/1081#issuecomment-784337549

[test] Fix containers size for screenshots

---

packages/grid/_modules_/grid/components/GridPagination.tsx
packages/grid/_modules_/grid/constants/localeTextConstants.ts
packages/grid/_modules_/grid/locales/bgBG.ts
packages/grid/_modules_/grid/locales/enUS.ts
packages/grid/_modules_/grid/locales/frFR.ts
packages/grid/_modules_/grid/locales/ptBR.ts
packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
packages/grid/_modules_/grid/utils/getGridLocalization.ts
packages/storybook/src/stories/grid-toolbar.stories.tsx

Fixes #1107 
Some context about the discussion:
> The points I wonder about:
> 1. Do we need to duplicate the translation keys for the components? Do developers need to translate a <TablePagination> differently in the context of a data grid? (DataGrid.localeText.footerPaginationRowsPerPage vs. TablePagination.labelRowsPerPage)
> 2. Should we duplicate (seems we need the same translations) the maintenance of the translated locales between the two components?
> 3. Should the data grid ignore the translation of the core components and ask developers to configure them independently? Basically, asking to do https://material-ui.com/guides/localization/#locale-text. And in the future, if we support importing individual translations, to cherry-pick what they need.
> 4. Should the data grid work …

[DataGrid] Add missing TablePagination localizations

---

test/regressions/index.test.js

For this fail: https://app.circleci.com/pipelines/github/mui-org/material-ui-x/3390/workflows/1f1b746f-64b3-42b1-a046-7ba4a479ecb7/jobs/14840.
I have rerun the build to make sure it wasn't a regression with #1025. The second build ran in a reasonable time, so unlikely a regression, but flakiness: https://app.circleci.com/pipelines/github/mui-org/material-ui-x/3390/workflows/d50285d1-f7f6-4bdd-bda8-8303711f0603/jobs/14843.

[test] Increase timeout for XGrid demo

---

docs/src/pages/components/data-grid/localization/localization.md

Noticed a few typos in the first few lines of this documentation.

[docs] Fix typo in localization.md

---

packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts
packages/grid/_modules_/grid/hooks/features/export/useGridCsvExport.tsx
packages/grid/x-grid/src/tests/apiRef.XGrid.test.tsx

[DataGrid] Handle special chars when doing CSV export

---

docs/pages/components/data-grid/demo.js
docs/src/pages/components/data-grid/demo/FullFeaturedDemo.js
docs/src/pages/components/data-grid/demo/FullFeaturedDemo.tsx
docs/src/pages/components/data-grid/filtering/CustomRatingOperator.js
docs/src/pages/components/data-grid/filtering/CustomRatingOperator.tsx
docs/tsconfig.json
package.json
packages/grid/tsconfig.build.json
packages/grid/x-grid-data-generator/src/asyncWorker.ts
packages/grid/x-grid-data-generator/src/services/real-data-service.ts
packages/grid/x-grid-data-generator/src/useDemoData.ts
packages/storybook/tsconfig.json
tsconfig.json
yarn.lock

`requestIdleCallback` is quite effective, 60 FPS will heavy JS load.
Meant to get a smooth demo experience with #1147. The first immediate change you can see is the ripple that does no longer freeze in https://deploy-preview-1147--material-ui-x.netlify.app/components/data-grid/demo/.

[docs] Lazy generate fake data

---

docs/src/pages/components/data-grid/rendering/rendering.md

Should say achieved and not achieve.
Thanks for your great work with this library!

[docs] Fix typo

---

docs/src/pages/components/data-grid/overview/overview.md

Fix #1236.
Wrong link to sorting docs in overview page: https://material-ui.com/components/data-grid/
Sorting & Multi Column Sorting lead to the row page since the sorting content moved to a new page.
Updated the reference to point to the dedicated sorting section.

[docs] Fix linking to sorting component in data-grid overview page

---

packages/grid/_modules_/grid/components/menu/GridMenu.tsx
packages/grid/_modules_/grid/components/panel/GridPanel.tsx

[DataGrid] Fix Popper z-index

---

packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx
packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx

@DanailH see why https://github.com/mui-org/material-ui/pull/24147
I have tried to enable the eslint rule to have the CI fail upfront, but it needed to make a change in the main repo, I was too lazy for doing it:
https://github.com/mui-org/material-ui-x/blob/a46e2a13c5f63adc08e44fa2dc1d51e64275e4ac/.eslintrc.js#L26

[core] No top-level imports

---

docs/src/pages/components/data-grid/localization/localization.md
packages/grid/_modules_/grid/locales/elGR.ts
packages/grid/_modules_/grid/locales/index.ts
packages/grid/_modules_/grid/utils/getGridLocalization.ts

Add Greek language locale for Grid.
**WARNING**
```js
import { elGR as elGRCore } from '@material-ui/core/locale';
```
Locale `elGR` does not exist inside the current published `@material-ui/core` version `4.11.3` which this depends on (`"@material-ui/core": "^4.9.12"`), but of course it does exist inside master https://github.com/mui-org/material-ui/pull/21988.

[DataGrid] Add elGR locale

---

packages/grid/x-grid-data-generator/src/useDemoData.ts

[DataGrid] Fix loader flag from useDemoData hook

---

packages/grid/_modules_/grid/components/GridPagination.tsx
packages/grid/_modules_/grid/components/cell/GridCell.tsx
packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts
packages/grid/_modules_/grid/hooks/features/rows/gridRowsSelector.ts
packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
packages/grid/_modules_/grid/hooks/features/sorting/gridSortingSelector.ts
packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
packages/grid/_modules_/grid/hooks/root/useGridContainerProps.ts
packages/grid/_modules_/grid/models/api/gridSortApi.ts
packages/grid/x-grid/src/tests/events.XGrid.test.tsx
packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
packages/storybook/.storybook/preview.tsx
packages/storybook/src/stories/grid-rows.stories.tsx
packages/storybook/src/stories/playground/real-data-demo.stories.tsx

fix #1309 
fix #1323
fix #481, done as rowIndex depends on sorted rows

[DataGrid] Fix rendering issues

---

docs/src/pages/components/data-grid/columns/columns.md
packages/grid/_modules_/grid/components/GridScrollArea.tsx
packages/grid/_modules_/grid/components/cell/GridCell.tsx
packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaders.tsx
packages/grid/_modules_/grid/constants/eventsConstants.ts
packages/grid/_modules_/grid/hooks/features/columnReorder/useGridColumnReorder.tsx
packages/grid/x-grid/src/tests/reorder.XGrid.test.tsx

Fixes #445.
Preview https://deploy-preview-1250--material-ui-x.netlify.app/components/data-grid/demo/
- [XGrid] Event `GRID_COLUMN_REORDER_DRAG_OVER_HEADER` is no longer emitted
---
My approach here was to turn every cell into a droppable target. If https://github.com/mui-org/material-ui-x/issues/206 gets implemented an additional check may be needed to determine if a column cell or a row cell was dropped. I'm using the value of [`dropEffect`](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect) to determine if the user canceled the reordering (dropping outside or pressing Escape).
Result:

[XGrid] Support column reordering inside the whole grid

---

packages/x-license/package.json
packages/x-license/src/licenseInfo.ts
packages/x-license/src/useLicenseVerifier.ts

This is a follow-up of #1361. 
This is one possible option in order to get the tests run in watch mode in jsdom. It's not the only one. I have pushed this option forward as it seems to bring value for developers ending up with duplicates of `@material-ui/x-license` in their package.
The duplication can happen for multiple reasons. For instance, webpack might decide to optimize the bundle and duplicate the package between two chunks. Or a developer might use two different versions of our components. 
In order to solve these issues, we only have two viable options:
1. We make `@material-ui/x-license` a peer dependency of the other packages. It's has a singleton
2. We share the license info as a global.
I have moved with 2. We usually avoid this option as it can be a pain in the *** when …

[license] Use a global storage rather than a module singleton

---

docs/src/pages/components/data-grid/filtering/ColumnTypeFilteringGrid.js
docs/src/pages/components/data-grid/filtering/ColumnTypeFilteringGrid.tsx
docs/src/pages/components/data-grid/filtering/CustomRatingOperator.js
docs/src/pages/components/data-grid/filtering/CustomRatingOperator.tsx
docs/src/pages/components/data-grid/filtering/ExtendNumericOperator.js
docs/src/pages/components/data-grid/filtering/ExtendNumericOperator.tsx
test/regressions/index.js

This issue was spotted in one of our conversation with customers
The link to https://material-ui.com/components/data-grid/filtering/#server-side-filter is broken. The preference panel traps the focus, which means calls `.focus()` on it when it opens. This moves the body scrollbar position.
The preference panel also closes as soon as a click is performed on the page, meaning, that the change in this PR only improves the UX on the documentation, there are no downsides.
As for improving the demo to have the preference panel open, we could imagine adding a button on the demo, or use a lazy-rendering strategy (only mount the demo once in the viewport, hoping it won't mess the scroll but it seems safe).
The fix in action: https://deploy-preview-1398--material-ui-x.netlify.app/components/data-gri …

[docs] Fix anchor links on the /data-grid/filtering/ page

---

packages/grid/_modules_/grid/components/toolbar/GridFilterToolbarButton.tsx

Fixes #1098 
The fix was easier than anticipated. I did the same we did inside the `GridFilterForm` component.
Preview https://deploy-preview-1367--material-ui-x.netlify.app/components/data-grid/demo/#data-grid-demo

[DataGrid] Add missing filter tooltip translations

---

packages/grid/_modules_/grid/components/GridCheckboxRenderer.tsx
packages/grid/_modules_/grid/components/GridViewport.tsx
packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
packages/grid/_modules_/grid/models/colDef/gridCheckboxSelection.tsx
packages/grid/_modules_/grid/models/gridRows.ts

Related to #1119, #1200, #1315
This is the first batch of changes to satisfy the need of removing `id` from the rowData. In this PR I'm replacing `row.id` with the `id` prop in all places where it's already available. It has no breaking changes. In the next PR I'll do the rest of the work that requires changes in the API too.

[DataGrid] Remove use of row.id when id prop is available

---

packages/grid/_modules_/grid/hooks/root/useGridContainerProps.ts
packages/grid/_modules_/grid/models/gridContainerProps.ts
packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
packages/storybook/src/stories/grid-pagination.stories.tsx

When autoPageSize is enabled, the pageSize prop value should not be used as it should be calculated according to the height of the viewport.
fix #1334

[DataGrid] Fix autoPageSize

---

packages/grid/_modules_/grid/components/GridCheckboxRenderer.tsx
packages/grid/_modules_/grid/components/GridViewport.tsx
packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts
packages/grid/_modules_/grid/hooks/features/export/useGridCsvExport.tsx
packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts
packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts
packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
packages/grid/_modules_/grid/hooks/features/selection/gridSelectionSelector.ts
packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
packages/grid/_modules_/grid/hooks/features/sorting/gridSortingSelector.ts
packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
packages/grid/_modules_/grid/models/api/filterApi.ts
packages/grid/_modules_/grid/models/api/gridRowApi.ts
packages/grid/_modules_/grid/models/api/gridSelectionApi.ts
packages/grid/_modules_/grid/models/gridRows.ts
packages/grid/_modules_/grid/models/params/gridFilterModelParams.ts
packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
packages/grid/data-grid/src/tests/rows.DataGrid.test.tsx
packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
packages/grid/x-grid/src/tests/selection.XGrid.test.tsx

- [DataGrid] `GridFilterModelParams.rows` changed to `Map<GridRowId, GridRowModel>`
- [DataGrid] `GridFilterModelParams.visibleRows` changed to `Map<GridRowId, GridRowModel>`
- [DataGrid] Return of `apiRef.current.getSelectedRows` changed to `Map<GridRowId, GridRowModel>`
- [DataGrid] Return of `apiRef.current.getRowModels` changed to `Map<GridRowId, GridRowModel>`
- [DataGrid] Return of `apiRef.current.getVisibleRowModels` changed to `Map<GridRowId, GridRowModel>`
---
This is a follow up of #1371. Basically I changed all methods that were returning `GridRowModel[]` to `Map<GridRowId, GridRowModel>`. This structure allows to keep the computed id and data of each row isolated while maintaining the order that they were inserted, even for numeric ids. The sorting with 100k rows is freezing, …

[DataGrid] Add support for custom row ids without cloning

---

packages/grid/_modules_/grid/components/GridRow.tsx
packages/grid/_modules_/grid/components/cell/GridCell.tsx
packages/grid/data-grid/src/tests/rows.DataGrid.test.tsx

Closes #1295.
Closes #1305.
This seems to cover all the issues. Assuming we will never add another source, maybe it's enough? Opened as a draft to run the CI and collect feedback.

[DataGrid] Ignore event from portal in cells

---

docs/pages/api-docs/data-grid.md
docs/pages/api-docs/x-grid.md

Fix GitHub references in API docs which are broken in these two pages:
https://material-ui.com/api/data-grid/
https://material-ui.com/api/x-grid/
The files were moved in 0719b02c6bd3f5e67b91299850b17d6ee1b5d050 and it seems an update of the docs were forgotten.
Fix #1281

[docs] Fix GitHub references in API docs

---

packages/grid/_modules_/grid/components/GridViewport.tsx
packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts
packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts
packages/grid/_modules_/grid/hooks/features/selection/gridSelectionSelector.ts
packages/grid/_modules_/grid/hooks/features/selection/gridSelectionState.ts
packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
packages/grid/_modules_/grid/models/api/gridSelectionApi.ts
packages/grid/_modules_/grid/models/colDef/gridCheckboxSelection.tsx
packages/grid/data-grid/src/tests/selection.DataGrid.test.tsx
packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
packages/grid/x-grid/src/tests/selection.XGrid.test.tsx

Fixes #874
I changed to use a `Set`, as it supports numbers and strings and it's faster than a flat array or a object. This PR should be merged after #1377.

[DataGrid] Fix support for numeric ids in selection

---

docs/pages/api-docs/data-grid.md
docs/pages/api-docs/x-grid.md
packages/grid/data-grid/src/DataGrid.tsx
packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
packages/grid/x-grid/src/XGrid.tsx

Fixes #982. The change improves the DX for developers that have ignored the TypeScript lint errors. It's not a bit easier to recover when not provided the right props:
Also, we sort required props to be first as said in this [comment](https://github.com/mui-org/material-ui-x/issues/982#issuecomment-774056422) first point.

[docs] Update PropType to cover required props

---

packages/grid/_modules_/grid/constants/eventsConstants.ts
packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts
packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
packages/grid/_modules_/grid/models/api/gridSortApi.ts
packages/grid/_modules_/grid/utils/keyboardUtils.ts
packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx

Fixes #1204 
There're multiple solutions to this bug:
1. Check if a multiple key was pressed during `click`.
2. Listen for `keydown` events in the document.
3. 1 + remove the `GRID_MULTIPLE_KEY_PRESS_CHANGED` listener and add a 3nd argument to `sortColumn` for when it's called programatically.
~I went with 1, as it's the simplest and has less side effects than 2.~ 3

[XGrid] Fix multi-sorting when focus is not in the grid root

---

packages/grid/_modules_/grid/components/containers/GridDataContainer.tsx
packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
packages/grid/_modules_/grid/hooks/root/gridContainerSizesSelector.ts
packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
packages/storybook/src/stories/grid-rows.stories.tsx

[DataGrid] Fix reset of virtualPage

---

docs/src/pages/components/data-grid/demo/FullFeaturedDemo.js
docs/src/pages/components/data-grid/demo/FullFeaturedDemo.tsx
packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx

The issue: https://codesandbox.io/s/material-demo-forked-zg2fo
It's a follow-up on https://github.com/mui-org/material-ui/pull/24895 by @petyosi
The fix works: https://codesandbox.io/s/material-demo-forked-kol9s?file=/package.json

[DataGrid] Improve support of core v5

---

docs/pages/api-docs/data-grid.md
docs/pages/api-docs/x-grid.md
docs/src/pages/components/data-grid/overview/overview.md
packages/grid/_modules_/grid/GridComponentProps.ts
packages/grid/_modules_/grid/models/api/gridComponentsApi.ts
packages/grid/_modules_/grid/models/gridSlotsComponentsProps.ts

[docs] Fix typos

---

packages/grid/_modules_/grid/locales/plPL.ts

When it comes to quantities, in polish 'liczba' does not equal 'ilość'.
Same as in English:
"Number refers to how many of something there is: how many mice, how many mutations, or how many calcium channels, for example. In other words, number refers to items we can count.
By contrast, amount refers to how much of something there is: how much stimulation, how much resistance, or how much liquid. In effect, amount refers to quantities we can measure but not individually count."
"Amount" is "ilość" and "number of" is "liczba".
In conclusion, I think it's a welcome small change 👍

[l10n] Correct quantities in plPL locale

---

.mocharc.js
packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
packages/grid/_modules_/grid/hooks/utils/useResizeContainer.ts
packages/grid/data-grid/src/tests/components.DataGrid.test.tsx
packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx
packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
packages/grid/data-grid/src/tests/rows.DataGrid.test.tsx
packages/grid/data-grid/src/tests/selection.DataGrid.test.tsx
packages/grid/data-grid/src/tests/sorting.DataGrid.test.tsx
packages/grid/data-grid/src/tests/state.DataGrid.test.tsx
packages/grid/data-grid/src/tests/toolbar.DataGrid.test.tsx
packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
packages/grid/x-grid/src/tests/events.XGrid.test.tsx
packages/grid/x-grid/src/tests/export.XGrid.test.tsx
packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
packages/grid/x-grid/src/tests/pagination.XGrid.test.tsx
packages/grid/x-grid/src/tests/reorder.XGrid.test.tsx
packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
packages/grid/x-grid/src/tests/selection.XGrid.test.tsx
packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx
packages/grid/x-grid/src/tests/state.XGrid.test.tsx
test/utils/index.tsx

Work on #1151:
- Fix the autosize warnings for jsdom
- Workaround jsdom/jsdom#1422 by replacing .scrollTo(x, y) with .scrollLeft and .scrollTop.
- Set more constraints in the CI so we don't introduce unknown regression
We go from 2% of coverage
to 69% of coverage
for tests running in jsdom.
---
Two issues I didn't spend time on here. I'm breaking them down into two new PRs.
```jsx
import { LicenseInfo } from '@material-ui/x-grid';
LicenseInfo.setLicenseKey(
'0f94d8b65161817ca5d7f7af8ac2f042T1JERVI6TVVJLVN0b3J5Ym9vayxFWFBJUlk9MTY1NDg1ODc1MzU1MCxLRVlWRVJTSU9OPTE=',
);
```
I wouldn't be surprised if this impacts developers in their project too. Not great

[test] Run more tests in jsdom

---

packages/grid/data-grid/package.json
packages/grid/x-grid-data-generator/package.json
packages/grid/x-grid/package.json
packages/x-license/package.json

A follow-up on https://github.com/mui-org/material-ui-x/pull/1447#discussion_r619691464. This is a mandatory step toward making the data grid packages tree shakeable. I'm not aware of any module side effects in the code, it should be safe.

[core] Label our packages as side effect free

---

docs/pages/api-docs/data-grid.md
docs/pages/api-docs/x-grid.md

Added missing filterModel prop in data-grid.md and x-grid.md  also fixed getRowId which was not appearing in x-grid.md.
Bundled PR https://github.com/mui-org/material-ui-x/pull/1494 and https://github.com/mui-org/material-ui-x/pull/1514

[docs] Add missing filterModel prop in /api/

---

.browserslistrc
.codesandbox/ci.json
netlify.toml
packages/grid/data-grid/package.json
packages/grid/x-grid-data-generator/package.json
packages/grid/x-grid/package.json
packages/x-license/package.json

**BREAKING CHANGE**
- [core] Increase the minimum Node.js version from 10.x to 12.x
---
Closes #1312 
Also enables to upgrade @material-ui/monorepo and many other packages like in PRs #1484, #1478

[core] Drop support for Node 10

---

docs/src/pages/components/data-grid/editing/StartEditButtonGrid.js
docs/src/pages/components/data-grid/editing/StartEditButtonGrid.tsx

Fixes #1502
Not sure why `onMouseDown` doesn't work 😅 , does it stop event propagation?
Preview: https://deploy-preview-1515--material-ui-x.netlify.app/components/data-grid/editing/#edit-using-external-button

[docs] Fix focus isn't set on the text box in `Edit using external button` demo

---

docs/src/pages/components/data-grid/editing/editing.md

All the headers that touch a controllable prop start with `Controlled`.

[docs] Header convention for controllable prop

---

docs/pages/api-docs/data-grid.md
docs/pages/api-docs/x-grid.md
docs/src/pages/components/data-grid/rows/rows.md

Fixes #1559 
Also fixes another typo `GridRowParams`.
We need to prioritise auto generation of docs!

[docs] Fix typo of `onColumnResizeCommitted` prop

---

docs/pages/api-docs/data-grid.md
docs/pages/api-docs/x-grid.md
packages/grid/_modules_/grid/components/menu/columnMenu/HideGridColMenuItem.tsx
packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx
packages/grid/_modules_/grid/constants/eventsConstants.ts
packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
packages/grid/_modules_/grid/models/api/gridColumnApi.ts
packages/grid/_modules_/grid/models/gridOptions.tsx
packages/grid/_modules_/grid/models/params/gridColumnVisibilityChangeParams.ts

Fixes #1565 
In addition instead of adding a new `apiRef` method, I reworked the existing `toggleColumn` and renamed it to `setColumnVisibility` since it made more sense. I've updated functionality accordingly where it was being used. Technically this is a breaking change.
Also updated the docs.
The params that the `onColumnVisibilityChange` callback gets are as follows:
```ts
/**
* The column of the current header component.
*/
colDef: any;
/**
* API ref that let you manipulate the grid.
*/
api: any;
/**
* The visibility state of the column.
*/
hide: boolean;

[DataGrid] Add `onColumnVisibilityChange` prop

---

docs/pages/api-docs/data-grid.md
docs/pages/api-docs/x-grid.md
packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenu.tsx
packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx
packages/grid/_modules_/grid/models/api/gridComponentsApi.ts
packages/grid/_modules_/grid/models/gridFilterOperator.ts
packages/grid/_modules_/grid/models/gridIconSlotsComponent.ts
packages/grid/_modules_/grid/models/gridSlotsComponent.ts

This is a follow-up on https://github.com/mui-org/material-ui/pull/26081. Base on the [type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts) we have the following:
- React.ElementType: react hosts component + custom components
- React.ComponentType: custom components
- React.JSXElementConstructor: React.ComponentType without the noise (.propTypes, .contextType, .displayName, etc.)

[core] Simplify component type

---

packages/grid/_modules_/grid/models/colDef/gridColDef.ts

Noticed in https://deploy-preview-1529--material-ui-x.netlify.app/api/data-grid/grid-col-def/ when reviewing #1529.

[docs] Fix errors in the docs

---

.github/dependabot.yml

See the issue in: https://github.com/mui-org/material-ui-x/network/updates.
I have copied and paste the config of the core repo as we aim for the same dependencies, more or less.

[core] Fix dependabot config

---

packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx

Closes #1653, the changes:
- the filtering performance test doesn't need 10 columns to fail.
- `it('should render maximum twice', async function test() {` wasn't failing on HEAD, so I have removed it.
- Add a new test that enforces to reduce the number of cell rendering. While I very much agree with this point: https://github.com/mui-org/material-ui-x/pull/1513#discussion_r630923223, end-to-end performance is the only thing that ultimately matters, having intermediary checkpoint might also help. Performance is all about not doing the work, we don't have control over what developers are rendering inside `renderCell`, they might have expensive components, in which case, reducing renders is important. 
I was hesitating to test that sorting only calling `getCellValue` N times, but it seems …

[test] Add constraints on cell render

---

docs/pages/api-docs/data-grid.md
docs/pages/api-docs/x-grid.md
docs/src/pages/components/data-grid/components/CustomColumnMenu.js
docs/src/pages/components/data-grid/components/CustomColumnMenu.tsx
docs/src/pages/components/data-grid/components/CustomFooter.js
docs/src/pages/components/data-grid/components/CustomFooter.tsx
docs/src/pages/components/data-grid/components/CustomSortIcons.js
docs/src/pages/components/data-grid/components/CustomSortIcons.tsx
docs/src/pages/components/data-grid/components/components.md

A follow-up on #1382. Preview: https://deploy-preview-1681--material-ui-x.netlify.app/components/data-grid/components/
- en-US, again
- Use inline demos as much as possible
- Use DataGrid over XGrid as much as possible
- Keep headers consistent with the page
- Improve button visibility and placement
- Only display the column menu when the button is clicked, keep it open, and fix the color flash

[docs] Clean demos components

---

packages/grid/_modules_/grid/models/colDef/gridBooleanOperators.ts
packages/grid/_modules_/grid/models/colDef/gridDateOperators.ts
packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts
packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
packages/storybook/src/stories/grid-filter.stories.tsx

[DataGrid] Fix filter with object as value and value getter

---

packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenu.tsx
packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx
packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx
packages/grid/_modules_/grid/hooks/features/columnResize/useGridColumnResize.tsx
packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts
packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
packages/grid/_modules_/grid/models/api/gridColumnApi.ts
packages/grid/_modules_/grid/models/api/gridRowApi.ts
packages/grid/x-grid/src/tests/events.XGrid.test.tsx
packages/grid/x-grid/src/tests/rows.XGrid.test.tsx

- [XGrid] `apiRef.current.getColumnFromField` was renamed to `apiRef.current.getColumn`.
- [XGrid] `apiRef.current.getRowFromId` was renamed to `apiRef.current.getRow`.
---
Closes #1569

[XGrid] Rename `apiRef` methods

---

packages/storybook/src/stories/playground/customComponents.tsx
test/regressions/TestViewer.js
test/regressions/index.js

Follow up after https://github.com/mui-org/material-ui-x/pull/1627 The same is done for the `withStyles` dependency. I think we will be able to remove them once this one is finished.

[core] Remove `withStyles` dependency on `@material-ui/core/styles`

---

docs/src/pages/components/data-grid/pagination/ApiRefPaginationGrid.js
docs/src/pages/components/data-grid/pagination/ApiRefPaginationGrid.tsx

follow up from #1583 
Preview: https://deploy-preview-1691--material-ui-x.netlify.app/components/data-grid/pagination/#apiref
Just noticed the demo was broken. This PR fixes it.

[docs] Fix docs demo

---

docs/pages/api-docs/data-grid.md
docs/pages/api-docs/x-grid.md

Add missing CSS rules from PR #1660. `GridClasses` interface is not documented. So maybe this could help users.
Preview: https://deploy-preview-1694--material-ui-x.netlify.app/api/data-grid/#css

[docs] Add missing CSS rules

---

packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx

Follow-up from https://github.com/mui-org/material-ui-x/pull/1665#pullrequestreview-661074358. The reason to skip these tests is explained in https://github.com/mui-org/material-ui-x/pull/1665#discussion_r633681113.

[test] Remove skip on Edge

---

packages/grid/_modules_/grid/components/cell/GridCell.tsx
packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts

A web page can have multiple `document`. We have no guarantee that `document.activeElement` is the target the event fired on. This change is important if we assume that the usage of multiple documents (popup/iframe/shadow dom) is frequent in the finance industry.

[core] Help support different documents

---

packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx

I have seen this test fail two times:
- https://app.circleci.com/pipelines/github/mui-org/material-ui-x/4878/workflows/08234063-27f7-448e-864f-d40b3d1c017e/jobs/24007
- https://app.circleci.com/pipelines/github/mui-org/material-ui-x/4879/workflows/8bda36d5-a023-4fef-86f3-c4e39ec570be/jobs/24012

[test] Reduce flakiness

---

packages/grid/data-grid/README.md
packages/grid/data-grid/package.json
packages/grid/x-grid-data-generator/package.json
packages/grid/x-grid/README.md
packages/grid/x-grid/package.json

Fixes #1761 
Note: I updated to `.34` instead of `.33` which was actually [suggested](https://github.com/mui-org/material-ui-x/issues/1761#issuecomment-847112150). Is it fine?

[DataGrid] Increase the minimum version of core v5 supported

---

packages/grid/_modules_/grid/GridComponent.tsx
packages/grid/_modules_/grid/hooks/features/rows/useGridFreezeRows.ts
packages/grid/_modules_/grid/hooks/root/useGridContainerProps.ts
packages/grid/_modules_/grid/hooks/utils/useGridScrollbarSizeDetector.tsx
packages/grid/_modules_/grid/hooks/utils/useOptionsProp.ts
packages/grid/_modules_/grid/utils/material-ui-utils.ts
packages/storybook/src/stories/grid-rows.stories.tsx

fix #1613 
Preview: https://deploy-preview-1703--material-ui-x.netlify.app/components/data-grid/components/

[DataGrid] Fix scroll size detector

---

packages/grid/_modules_/grid/hooks/utils/useGridScrollFn.ts

Following conversation from https://github.com/mui-org/material-ui-x/issues/1812#issuecomment-853267525
Preview: https://deploy-preview-1829--material-ui-x.netlify.app/components/data-grid/#commercial-version
**Before**
https://codesandbox.io/s/material-demo-forked-7s1vw
**After**
https://codesandbox.io/s/material-demo-forked-90ccn

[DataGrid] Fix force reflow on scroll start and end

---

packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx

Closes #223
This PR adds a test case to ensure that when clicking on the next page and there's a `page` prop it will not change the current page. I also fixed the suite to run more tests in JSDOM, when possible.

[test] Improve pagination tests

---

packages/grid/_modules_/grid/components/toolbar/GridToolbarExport.tsx
packages/grid/_modules_/grid/hooks/features/export/useGridCsvExport.tsx
packages/grid/_modules_/grid/models/api/gridCsvExportApi.ts
packages/grid/_modules_/grid/models/gridExport.ts
packages/grid/_modules_/grid/utils/exportAs.ts

This feature allows to:
- set the file name
- set flag utf8WithBom to generate csv file as UTF-8 with BOM
It may be extended with further options in the future
Example how to use:
```tsx
import { GridToolbarExport, GridExportCsvOptions } from '@material-ui/data-grid';
<GridToolbarExport
csvOptions={{
fileName: 'csvWithBom',
utf8WithBom: true,
} as GridExportCsvOptions}
/>
```
It generate file "csvWithBom.csv" with sequence of bytes (0xEF, 0xBB, 0xBF) at the beginning.
One iteration on #1440

[DataGrid] Allow to customize GridToolbarExport's CSV export

---

packages/grid/_modules_/grid/components/GridViewport.tsx
packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
packages/grid/data-grid/src/tests/toolbar.DataGrid.test.tsx

Fixes #1776 
The problem was related to grabbing the height from the state inside `GridRowCells` component which is memoized. Passing it as a prop solves the issue. I extended the existing density tests to cover that case.
Preview: https://deploy-preview-1819--material-ui-x.netlify.app/components/data-grid/accessibility/#density-selector

[DataGrid] Fix cell height after changing grid's density

---

packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts

Fixes #1582 
Reproduction: https://codesandbox.io/s/material-demo-forked-y2xj0 (when the grid loads start resizing the window to make it small to a point where the last column dissapears)
The problem was that when resizing and space was not enough the fluid columns did not default to the base width of `100px`.
https://user-images.githubusercontent.com/5858539/120652536-87ed3c00-c488-11eb-810b-0de3d1a07101.mov

[DataGrid] Fix fluid columns width when available `viewportWidth` < 0

---

packages/grid/_modules_/grid/components/GridFooter.tsx
packages/grid/_modules_/grid/components/GridRowCount.tsx
packages/grid/_modules_/grid/constants/localeTextConstants.ts
packages/grid/_modules_/grid/locales/bgBG.ts
packages/grid/_modules_/grid/locales/csCZ.ts
packages/grid/_modules_/grid/locales/deDE.ts
packages/grid/_modules_/grid/locales/elGR.ts
packages/grid/_modules_/grid/locales/esES.ts
packages/grid/_modules_/grid/locales/frFR.ts
packages/grid/_modules_/grid/locales/itIT.ts
packages/grid/_modules_/grid/locales/jaJP.ts
packages/grid/_modules_/grid/locales/nlNL.ts
packages/grid/_modules_/grid/locales/plPL.ts
packages/grid/_modules_/grid/locales/ptBR.ts
packages/grid/_modules_/grid/locales/ruRU.ts
packages/grid/_modules_/grid/locales/skSK.ts
packages/grid/_modules_/grid/locales/trTR.ts
packages/grid/_modules_/grid/locales/ukUA.ts
packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx

Fixes #1802
Preview: https://deploy-preview-1830--material-ui-x.netlify.app/components/data-grid/filtering/#multi-column-filtering
I'm only displaying the number of filtered rows when the pagination is disabled. 
DataTables also displays it in the pagination:

[XGrid] Display the number of filtered rows in the footer

---

docs/pages/api-docs/data-grid/data-grid.md
docs/pages/api-docs/data-grid/x-grid.md
packages/grid/_modules_/grid/models/gridOptions.tsx

[docs] Add docs for `disableDensitySelector` option

---

packages/grid/_modules_/grid/locales/deDE.ts
packages/grid/_modules_/grid/locales/frFR.ts
packages/grid/_modules_/grid/locales/itIT.ts
packages/grid/_modules_/grid/locales/nlNL.ts
packages/grid/_modules_/grid/locales/ptBR.ts

Add missing export translations.

[DataGrid] Improve ptBR locale

---

docs/pages/api-docs/data-grid/data-grid.md
docs/pages/api-docs/data-grid/x-grid.md

@m4theushw I think that we should flatten the URLs. It's inconsistent and will likely create multiple issues later down the road as we fully integrate with the main repo API generation scripts. For instance, it makes it harder to automatically link API pages from the JSDocs as we do in https://twitter.com/olivtassinari/status/1401611864539283457. How about?
- `/api/data-grid/x-grid/` -> `/api/x-grid/`
- `/api/data-grid/data-grid/` -> `/api/data-grid/`
- `/api/data-grid/` -> `/components/data-grid/api/`

[docs] Fix 404 links

---

packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx

Fixes #1914 
Preview: https://codesandbox.io/s/intelligent-silence-psosd?file=/package.json
When creating the update object to be passed to `updateRows` it was being created only with the id, but `getRowId` requires the entire row to work.

[DataGrid] Fix support for getRowId on cell editing

---

packages/grid/_modules_/grid/models/gridOptions.tsx

Noticed working on #1772. The docs weren't matching the type and the type was too loose.

[DataGrid] Improve type of the blur event

---

packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts

Given `n` total rows and `m` row updates, reduces asymptotic complexity of `updateRows` from `O(n*m)` to `O(n+m)`.
We do this by performing all updates together, instead of each one individually.

[DataGrid] Improve updateRows performance

---

packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualColumns.ts

Noticed when playing around with the [virtualization demo](https://material-ui.com/components/data-grid/virtualization/#column-virtualization) in codesandbox that when I tried 100,000 columns, it would hit codesandbox infinite loop detection. Having worked on my own [toy implementation](https://mui-plus.vercel.app/components/DataGrid/virtualization) of a virtualized Material UI datagrid, I realized it was looping through all possible columns to find viewport intersection. Since it has to search an ordered array, a binary search is possible here and drastically reduces iterations on high column counts. I reviewed the Material UI Datagrid implementation and found that [my implementation](https://github.com/Janpot/mui-plus/blob/03b78402418b9772ccb3bfea52a1e986fc2be520/packages/mui-plus/src/ut …

[DataGrid] Use binary search to find column indexes in virtualization

---

packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx
packages/grid/x-grid/src/tests/selection.XGrid.test.tsx

Fix the double click issue: https://github.com/mui-org/material-ui-x/issues/1141#issuecomment-798547109. In the recording, you can see that I click twice, and the state stays the same. *checked indeterminate* is the **same state** as *unchecked indeterminate*. In core v5 we removed the visual distinction to match screen readers.
Note that the fix is mostly removing code we don't need* (*assuming it's better to not react to clicks on the checkbox when there are no rows).
I worked on this because #1879 didn't seem to go in a rigorous direction. I'm mostly interested in the test case and isolation. I'm a believer that the quality of the tests ultimately drives the quality of the code.

[DataGrid] Fix double-click issue

---

docs/src/pages/components/data-grid/events/events.json
packages/grid/_modules_/grid/constants/eventsConstants.ts
packages/grid/_modules_/grid/hooks/features/filter/visibleGridRowsState.ts
packages/grid/x-grid/src/tests/rows.XGrid.test.tsx

- [DataGrid] Make GRID_ROWS_CLEAR private (#1925) @oliviertassinari 
The `GRID_ROWS_CLEAR` event was always triggered alongside `GRID_ROWS_SET`. You can listen to the latter event only.
---
~See the rationale in https://github.com/mui-org/material-ui-x/pull/1862#discussion_r654370166. When GRID_ROWS_CLEARED triggers, `GRID_ROWS_SET` is also triggered, no need to update the sorting state **twice**.~
~Note that this makes `GRID_ROWS_CLEARED` an orphan, nobody is listening to the event.~
~If I'm missing something and is really required, then it surfaces a hole in the test suite, the CI is green.~

[DataGrid] Make GRID_ROWS_CLEAR private

---

packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
packages/grid/x-grid/src/tests/rows.XGrid.test.tsx

One chunk of #1818
I have updated the logic to match [the one we use](https://github.com/mui-org/material-ui/blob/2c4dc994da164a53b253f03bcd2425a52655f175/packages/material-ui/src/useAutocomplete/useAutocomplete.js#L328-L348) in the Autocomplete component. It wasn't computed correctly.
@m4theushw I have extracted it from #1871 because closing #1818 will be a larger effort. I have also simplified the test case to be virtualization implementation **invariant**.
A live demo of the bug fixed in this PR: https://material-ui.com/components/data-grid/#commercial-version

[DataGrid] Fix scrollToIndexes offscreen row

---

docs/src/pages/components/data-grid/getting-started/getting-started.md

Fix the inconsistency reported in #1961
- docs: can use XGrid for development
- license warning: can't use XGrid fo development
- EULA: can't use XGrid for development
This is meant to match the policy of the existing commercial alternative solutions. We don't need to differentiate on this end. If we want to change the policy in the future, then we need to update it all at once.

[docs] Align docs with EULA (source of truth)

---

packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
packages/grid/x-grid/src/tests/rows.XGrid.test.tsx

This is a follow-up https://github.com/mui-org/material-ui-x/pull/1949#issuecomment-866995274, I'm pushing the quality of the solution one step further, by doing a plain copy & paste of the `Autocomplete`'s logic.
The previous behavior: https://codesandbox.io/s/material-demo-forked-j7i1x?file=/package.json.
https://user-images.githubusercontent.com/3165635/123521590-e8525080-d6b7-11eb-94db-3e259e36a549.mp4
The new behavior: https://codesandbox.io/s/material-demo-forked-nzkwd?file=/package.json
https://user-images.githubusercontent.com/3165635/123521674-63b40200-d6b8-11eb-8e7d-8e945eacefd8.mp4

[DataGrid] Better fix the scrollToIndexes logic

---

docs/pages/api-docs/data-grid/data-grid.md
docs/pages/api-docs/data-grid/x-grid.md
docs/src/pages/components/data-grid/columns/columns.md
docs/src/pages/components/data-grid/events/events.json
packages/grid/_modules_/grid/constants/eventsConstants.ts
packages/grid/_modules_/grid/hooks/features/columnResize/useGridColumnResize.tsx
packages/grid/_modules_/grid/models/gridOptions.tsx

- [DataGrid] Rename `onColumnResizeCommitted` to `onColumnWidthChange`.
```diff
-<DataGrid onColumnResizeCommitted={...} />
+<DataGrid onColumnWidthChange={...} />
```
---
Renamed to match the event name. Related to https://github.com/mui-org/material-ui-x/pull/1862#discussion_r652865464
I don't know what to do with the type in the argument, it's shared with `onColumnResize`. #1036 would touch this part.

[DataGrid] Rename onColumnResizeCommitted to onColumnWidthChange

---

docs/pages/api-docs/data-grid/data-grid.md
docs/pages/api-docs/data-grid/x-grid.md
packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx
packages/grid/_modules_/grid/hooks/features/pagination/gridPaginationSelector.ts
packages/grid/_modules_/grid/models/gridOptions.tsx
packages/grid/data-grid/src/DataGrid.tsx
packages/grid/data-grid/src/tests/selection.DataGrid.test.tsx
packages/grid/x-grid/src/tests/selection.XGrid.test.tsx

Fixes #605 
Added `checkboxSelectionVisibleOnly` that when `true`, Select All will only select rows visible on the current paginated page.
ToDo:

[XGrid] Add option to select only visible rows on the current page

---

packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualColumns.ts
packages/grid/x-grid/src/tests/rows.XGrid.test.tsx

While #1949 fixed the bug in the y-axis, there's a similar problem in the x-axis too. It happens because we consider a column as visible if its left position is inside the viewport, without accounting the width.
In https://material-ui.com/components/data-grid/demo/
Preview: https://deploy-preview-1964--material-ui-x.netlify.app/components/data-grid/demo/

[DataGrid] Fix scrollToIndexes offscreen column

---

packages/grid/_modules_/grid/constants/eventsConstants.ts
packages/grid/_modules_/grid/hooks/features/focus/useGridFocus.ts

What is the use case of this event ? It is never mentioned in an issue and never used internally.
We already have a `GRID_CELL_FOCUS` which gives access to the cell being focused whereas this one just says "the focused cell has changed".

[core] Remove unused event 'cellFocusChange'

---

packages/grid/x-grid-data-generator/package.json

Fixes #1878 
Noticed while debugging #1993 that demos depending in `@material-ui/x-grid-data-generator` won't work with MUI v5 because the version of the lab is fixed in v4. This PR makes the lab a peer dependency.
Before: https://codesandbox.io/s/material-demo-forked-1vzw6?file=/package.json
After: https://codesandbox.io/s/material-demo-forked-nzqjp?file=/package.json
---
I'm aware that clicking in any cell to edit crashes the demo. I'll fix this in another PR. The first step was to make them at least run with v5.

[core] Add @material-ui/lab as peer dependency

---

packages/grid/_modules_/grid/hooks/features/focus/useGridFocus.ts
packages/grid/_modules_/grid/useGridComponent.tsx
packages/grid/x-grid/src/tests/rows.XGrid.test.tsx

[DataGrid] Remove focus on cell when its row is removed from the data

---

test/karma.conf.js

It doesn't seem to be enough
This PR workflows :
- https://app.circleci.com/pipelines/github/mui-org/material-ui-x/5774/workflows/7d39c3e8-0ac0-4b28-b1b5-e7f4e5879518/jobs/29973
#2008 workflows (old timeout) :
- https://app.circleci.com/pipelines/github/mui-org/material-ui-x/5772/workflows/8554a64a-e189-4061-8d37-1caf63b45f6c
- https://app.circleci.com/pipelines/github/mui-org/material-ui-x/5772/workflows/ad3a635c-5ebb-4e12-ad1b-1aef6d2f5a71
- https://app.circleci.com/pipelines/github/mui-org/material-ui-x/5772/workflows/2dda8897-9da8-4ee7-8a37-ed08024f12c6
#2034 workflows (old timeout) :
- https://app.circleci.com/pipelines/github/mui-org/material-ui-x/5753/workflows/f530e51a-5dfb-4460-9005-4e5d232d3c8f/jobs/29824
- https://app.circleci.com/pipelines/github/mui-org/material-ui-x/5753/work …

[test] Increase Browserstack worker timeout from 2.5 to 4 minutes

---

.github/support.yml

I was expecting the bot we have in the core repo to close #2096 as soon as I left the "support" label but it didn't happen. We didn't configure the bot here, so it seems normal.

[core] Add support bot

---

packages/grid/_modules_/grid/hooks/features/columnResize/useGridColumnResize.tsx
packages/grid/x-grid/src/tests/columnHeaders.XGrid.test.tsx
packages/grid/x-grid/src/tests/columns.XGrid.test.tsx

Fixes #2007 
Preview: https://deploy-preview-2089--material-ui-x.netlify.app/components/data-grid/demo/

[XGrid] Fix column resize on touch devices

---

packages/grid/_modules_/grid/utils/domUtils.ts

This is a continuation of https://github.com/mui-org/material-ui-x/pull/2033#discussion_r666030447. `:scope` is documented in https://developer.mozilla.org/en-US/docs/Web/CSS/:scope#direct_children. AFAIK, we don't need it.

[core] Remove implicit :scope

---

packages/grid/_modules_/grid/GridComponentProps.ts
packages/grid/_modules_/grid/components/containers/GridRoot.tsx
packages/grid/x-grid/src/tests/layout.XGrid.test.tsx

If we support the `className` prop, then it makes sense to support the `style` prop too. I got trapped in https://github.com/mui-org/material-ui/pull/27196.

[DataGrid] Support style prop

---

packages/grid/data-grid/package.json
packages/grid/x-grid-data-generator/package.json
packages/grid/x-grid/package.json
packages/storybook/package.json
packages/x-license/package.json

With the rise in supply chain attacks and OSS dependencies being used as a attack vector, Microsoft is working with our ecosystem partners, such as the Linux Foundation's OpenSSF, to enable OSS consumers to track packages back to their public sources.
We've identified that the following packages published to NPM do not report where sources can be found, typically accomplished by including a link to your GitHub repository in your `package.json` REPOSITORY field. This PR was created to add this value, ensuring future releases will include this provenance information.
Published NPM packages with repository information:
*@material-ui/data-grid

[core] Fix missing git source in packages

---

packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts

This was forgotten in #1997, it happens, it's fine. More importantly, the CI should have reported the issue, it didn't because of https://github.com/mui-org/material-ui-x/pull/1913/files#r667394689, we should have never extended any. The test side of things is done in #2117, as you can see from the failing tests.

[DataGrid] Add missing localeText types

---

test/karma.conf.js

We use 5 seconds in the main repository, while we have tests that are slower because they test a bigger component here. This seems like a logical step. I worked on it after seeing: https://app.circleci.com/pipelines/github/mui-org/material-ui-x/6089/workflows/f3da1253-f8e8-4876-aac0-63ffefd32ed5/jobs/32074
> Edge 85.0.564.41 (Windows 10) <DataGrid /> - Toolbar column selector should show all columns when clicking "SHOW ALL" from the column selector FAILED
Error: Timeout of 4000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
We could even do 6s to be honest, no real preferences.

[test] Allow tests to run for up to 5 instead of 4 seconds

---

packages/grid/_modules_/grid/components/GridPagination.tsx
packages/grid/_modules_/grid/components/panel/GridPanel.tsx
packages/grid/_modules_/grid/utils/getGridLocalization.ts
packages/grid/_modules_/grid/utils/utils.ts
yarn.lock

Fixes #2106
A full explanation of the problem can be found here -> https://github.com/mui-org/material-ui-x/issues/2106#issuecomment-876996807
- v4.11.4: https://codesandbox.io/s/material-demo-forked-dtst2?file=/demo.js
- v4.12.1: https://codesandbox.io/s/material-demo-forked-skokv?file=/demo.js
- v5.0.0.beta-0: https://codesandbox.io/s/material-demo-forked-n0qqf?file=/demo.js

[DataGrid] Fix support for `@material-ui/core@4.12`

---

packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
packages/grid/_modules_/grid/utils/sortingUtils.ts

Closes #1968 
Preview: https://deploy-preview-2155--material-ui-x.netlify.app/components/data-grid/#commercial-version
Benchmark: https://material-ui.com/components/data-grid/#commercial-version
localeCompare / Intl.Collator
localeCompare / Intl.Collator

[DataGrid] Use Intl.Collator for string comparison

---

packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
packages/grid/x-grid/src/tests/layout.XGrid.test.tsx
packages/grid/x-grid/src/tests/rows.XGrid.test.tsx

@oliviertassinari this do fail when using a commit older than https://github.com/mui-org/material-ui-x/pull/2034

[core] Correctly test column visibility switch impact on column width

---

package.json

I was running this script on Windows OS and I got `/' was unexpected at this time` error.
Apparently, Windows platforms do not support single quotes on the command line, so escaping it in double quotes.
This works in all OS.

[core] Support `docs:api` script in Windows OS

---

packages/grid/_modules_/grid/constants/eventsConstants.ts
packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts

Fixes #2132 
Preview: https://deploy-preview-2154--material-ui-x.netlify.app/components/data-grid/demo/
This bug is a bit hard to reproduce. It happens almost randomly. It's caused because the `.MuiDataGrid-columnsContainer` div is, sometimes, also scrolling when dragging a column. However, its `scrollLeft` position should always be zero.
To be able to fix it, I had to find a reliable way to reproduce it. What I did was to change the `overflow: hidden` of `.MuiDataGrid-columnsContainer` to `overflow: auto` to see the scrollbar. Then, I did the following movement:
https://user-images.githubusercontent.com/42154031/125847679-7b8abd05-3f0b-4172-85a9-50fba44de21c.mp4

[XGrid] Prevent headers from scrolling during reordering

---

docs/src/pages/components/data-grid/getting-started/getting-started.md

Hello! 👋 
I noticed there were a number of small typos in the documentation so I made a quick PR to address the ones I could find.
Preview: https://deploy-preview-2169--material-ui-x.netlify.app/components/data-grid/getting-started/#feature-comparison
Sidenote: I saw some broken links in that same page section. I'll hopefully be able to make another PR to remove the links that link to non-existent sections.

[docs] Fix small typos in the documentation

---

packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx

After merging #2112, the tests started to fail. The reason is that the `state` prop was being used to set initial values for the filters while the `filterModel` was also set. However, having both won't work with the new controllable state.

[test] Fix singleSelect tests

---

packages/grid/data-grid/src/DataGrid.tsx

Warning text should be `filtering` instead of `sorting` for `disableMultipleColumnsFiltering` prop.

[DataGrid] Fix `disableMultipleColumnsFiltering` console warning

---

.circleci/config.yml
test/karma.conf.js

Sync the Karma config to use the same timeout used in the core: https://github.com/mui-org/material-ui/blob/8039e8506fc0377fac2b7c6772e551e982450037/test/karma.conf.js#L21

[test] Sync Karma config

---

packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx
packages/grid/data-grid/README.md
packages/grid/data-grid/package.json
packages/grid/x-grid/README.md
packages/grid/x-grid/package.json

Fix the warning visible in this reproduction: https://github.com/mui-org/material-ui-x/issues/2222#issuecomment-887474509.
https://codesandbox.io/s/blissful-herschel-xpm45?file=/src/Demo.tsx
It also improves cross-document support. Sebastian has figured out a smart way to remove the need for this `getDoc` prop in v5.

[DataGrid] Fix prop-type warning with v5

---

packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx

closes #2195 
From the [codesandbox reproduction](https://codesandbox.io/s/material-demo-forked-gbxtt?file=/demo.tsx:171-187), the select is hard to see because of default variant changed in core v5 and the style is fixed with `width`
**PR summary**
- force select variant to `standard` ([the default variant changed to `outlined` in core v5](https://next.material-ui.com/guides/migration-v4/#select))
- change `width` to `min-width` for future proof
I think there we should not force the width, instead make it flexible from the input (CSS Grid should do the job). Anyway, it is another step of improvement, wait to see the team's feedback first.
**Storybook screenshots**

[XGrid] Fix width issue in FilterPopup

---

renovate.json

As soon as one renovate PR is merged, all the other ones are rerun. It's not scaling with our CI. Try to force the value.

[core] rebaseWhen=auto does not seem to work

---

packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx

Fixes #2225 
Preview: https://deploy-preview-2246--material-ui-x.netlify.app/components/data-grid/filtering/#extend-filter-operators
The fix is the same idea of #2213: use the props instead of the options.
The bug started to happen because in #1720 the filter hook was changed to get the `filterModel` from the props, instead of the options:
https://github.com/mui-org/material-ui-x/blob/4f52c84e104dd598e454e5d8d0c395c5aa3b7d54/packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts#L323-L326
However, the hydration of the extended columns was still using the options:
https://github.com/mui-org/material-ui-x/blob/4f52c84e104dd598e454e5d8d0c395c5aa3b7d54/packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts#L304-L306

[DataGrid] Fix filter with extended columns

---

packages/grid/_modules_/grid/hooks/features/core/useGridControlState.ts
packages/grid/_modules_/grid/hooks/features/core/useGridState.ts
packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
packages/grid/_modules_/grid/hooks/features/pagination/useGridPage.ts
packages/grid/_modules_/grid/hooks/features/pagination/useGridPageSize.ts
packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
packages/grid/_modules_/grid/models/api/gridControlStateApi.ts
packages/grid/_modules_/grid/models/controlStateItem.ts
packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
packages/grid/data-grid/src/tests/selection.DataGrid.test.tsx
packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
packages/grid/x-grid/src/tests/selection.XGrid.test.tsx

I have used #2200 as an entry to find myself interest in the controlled state. Along the way, I have noticed a couple of anti-patterns that I went on fixing:
- The presence of a onXXX prop shouldn't change the behavior of the state
- Using deepEqual to compare props is no longer relevant since we compare the reference in the useGridControlState
- The user's onXXX prop is supposed to be called after the component has handled the logic. It's how we aim to make it work in the core. It's not always possible, for instance, when we need to do `event.isMuiDefaultPrevented`.
- The event should be triggered, regardless of if the change was persisted in the state or not.
- Change the logic to have fewer branches

[DataGrid] Canonical controlled state behavior

---

packages/grid/_modules_/grid/locales/deDE.ts

Add the missing deDE locale values for exporting and using the "is empty" and "is not empty" operators.

[DataGrid] Add German (deDE) translation for export and isEmpty operator

---

packages/grid/_modules_/grid/components/cell/GridCell.tsx
packages/grid/_modules_/grid/models/colDef/gridBooleanColDef.tsx
packages/grid/data-grid/src/tests/cells.DataGrid.test.tsx

closes #1849
- fix render `0` from renderCell. (`renderCell: () => 0` now show 0 on the screen)
- add default formatter to string for column type boolean. (`renderCell: params => params.formattedValue` now show `'true'` | `'false'` on the screen.
- add tests

[DataGrid] Fix renderCell returning false-ish values

---

packages/grid/x-grid/src/tests/events.XGrid.test.tsx

A leftover from my exploration to understand why https://github.com/mui-org/material-ui-x/pull/2220#discussion_r680947602

[test] Assert that event.defaultMuiPrevented is called

---

docs/src/pages/components/data-grid/components/CustomPaginationGrid.js
docs/src/pages/components/data-grid/components/CustomPaginationGrid.tsx
docs/src/pages/components/data-grid/overview/DataGridDemo.js
docs/src/pages/components/data-grid/overview/DataGridDemo.tsx
docs/src/pages/components/data-grid/pagination/200PaginationGrid.js
docs/src/pages/components/data-grid/pagination/200PaginationGrid.tsx
docs/src/pages/components/data-grid/pagination/ApiRefPaginationGrid.js
docs/src/pages/components/data-grid/pagination/ApiRefPaginationGrid.tsx
docs/src/pages/components/data-grid/pagination/ControlledPaginationGrid.js
docs/src/pages/components/data-grid/pagination/ControlledPaginationGrid.tsx
docs/src/pages/components/data-grid/pagination/CursorPaginationGrid.js
docs/src/pages/components/data-grid/pagination/CursorPaginationGrid.tsx
docs/src/pages/components/data-grid/pagination/ServerPaginationGrid.js
docs/src/pages/components/data-grid/pagination/ServerPaginationGrid.tsx
docs/src/pages/components/data-grid/style/AntDesignGrid.js
docs/src/pages/components/data-grid/style/AntDesignGrid.tsx

We forgot about this in #2014
Open http://0.0.0.0:3001/components/data-grid/ in dev mode:
Our regression tests run all the demos an fail the CI when a warning is raised, unfortunately, we run the regression test in production mode, so no warning is thrown.
---
Next

[docs] Fix page size warnings

---

packages/grid/_modules_/grid/hooks/root/useGridApiContext.ts

Fix on the surface on #2245 
I tried to add the following test case but it is not working. Not sure what am I missing.
```jsx
import { GridApiRef, useGridApiRef, XGrid, ptBR } from '@material-ui/x-grid';
import { GridToolbarFilterButton, GridToolbarDensitySelector } from '@material-ui/data-grid'
--
--
it('should throw error if multiple versions of data grid is being used', () => {
expect(() => {
function CustomToolbar() {
return (
<div>
{/* imported from '@material-ui/data-grid' but using in XGrid */}
<GridToolbarFilterButton />
<GridToolbarDensitySelector />
</div>
);
}
render(
<div style={{ width: 300, height: 300 }}>
<XGrid {...baselineProps} components={{ Toolbar: CustomToolbar }} />
</div>,
);
}).to.throw();
});
```

[DataGrid] Improve error message if using multiple versions of data grid

---

packages/grid/_modules_/grid/models/colDef/gridBooleanColDef.tsx
packages/grid/x-grid/src/tests/export.XGrid.test.tsx

A quick follow-up from https://github.com/mui-org/material-ui-x/pull/2242#discussion_r679944486
Before: https://codesandbox.io/s/material-demo-forked-4bdf7?file=/demo.js
Export to CSV and check the "Is admin" column. It's "true" and "false" when it should be translated.
After: https://codesandbox.io/s/material-demo-forked-rmgvq?file=/demo.js
Export to CSV and check the "Is admin" column. It's correctly translated.

[DataGrid] Translate booleans when exporting to CSV

---

CHANGELOG.md
docs/package.json
lerna.json
package.json
packages/eslint-plugin-material-ui/package.json
packages/grid/data-grid/package.json
packages/grid/x-grid-data-generator/package.json
packages/grid/x-grid/package.json
packages/storybook/package.json
packages/x-license/package.json

The only PR marked as BC is #2188 but it has not migration path. I don't think it will cause any impact. Previously we were using `any` and now it's typed.

v4.0.0-alpha.37

---

packages/grid/_modules_/grid/components/GridRow.tsx
packages/grid/_modules_/grid/components/GridViewport.tsx

- [DataGrid] The CSS classes `.Mui-odd` and `.Mui-even` were removed from the row. Use the `:nth-child(odd|even)` selector to replace them.
---
While looking at bug #2315 which is unexpectedly on a large scope due to virutalization case to be considered for last row, I noticed this line is not being used. 
So removed `Mui-even` and `Mui-odd` classes.
Perhaps it is added so that it can be targeted via CSS like `& .Mui-even`, `& .Mui-odd`. If yes, I think we can rename it to `MuiDataGrid-odd` and `MuiDataGrid-even` and also document it. 
If its relevant, we can close this PR.

[DataGrid] Remove unused row CSS classes

---

packages/grid/data-grid/src/DataGrid.tsx

A follow-up on https://github.com/mui-org/material-ui-x/pull/2176/files#r688138431

[core] Keep prop-types in the same file

---

packages/grid/_modules_/grid/components/containers/GridRootStyles.ts

Fixes #2183
The differences pointed by argos is because the Select (rows per page) and the InputBase (quick filter) set different values for `box-sizing`, but previously these values were being forced to be `border-box`.

[DataGrid] Don't apply `box-sizing: border-box` on everything

---

docs/src/pages/components/data-grid/components/components.md
docs/src/pages/components/data-grid/editing/editing.md
docs/src/pages/components/data-grid/pagination/pagination.md

Just a few small fixes in docs.
Preview: 
https://deploy-preview-2381--material-ui-x.netlify.app/components/data-grid/components
https://deploy-preview-2381--material-ui-x.netlify.app/components/data-grid/editing
https://deploy-preview-2381--material-ui-x.netlify.app/components/data-grid/pagination/#server-side-pagination

[docs] Fix docs links and pagination sentence

---

docs/pages/api-docs/data-grid/data-grid-pro.md
docs/pages/api-docs/data-grid/data-grid.md
packages/grid/_modules_/grid/models/gridOptions.tsx

Noticed while looking at the row editing feature which looks awesome! And yes we need the auto docs generator like the core repo soon. 
Prop was changed in #2143

[docs] Fix docs for `onEditRowsModelChange` prop

---

docs/src/pages/components/data-grid/overview/overview.md

Maybe not that important, but since we are completed with row and cell editing, thought we can promote `Editing` as a feature.
In docs rearranging (part of  #2313), we need to change these as well or maybe there will be a re-direct rule.
Preview: https://deploy-preview-2396--material-ui-x.netlify.app/components/data-grid/#features

[docs] Add `Row & Cell editing` in features list

---

packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts

I have tried to simplify the logic of this hook. It's mostly about renaming the variable to minimize the number of different terms we use. I have also skipped a few branches that seem to be unreachable.
I did this while I was looking into #2344
Closes #2333

[core] Clean up grid column

---

docs/src/pages/components/data-grid/pagination/pagination.md

This small PR improves consistency in the docs. There were two occurrences of the term 'paging' vs 31 ones of 'pagination' on the docs page.

[docs] Replace 'paging' with 'pagination'

---

packages/grid/_modules_/grid/locales/jaJP.ts

[l10n] Improve Japanese (jaJP) locale

---

packages/grid/_modules_/grid/components/GridPagination.tsx

As discussed in https://github.com/mui-org/material-ui-x/issues/1907#issuecomment-861888562
This PR makes the page size controls visible on 'sm' screens.
Fixes #1907

[DataGrid] Show page size controls on narrower screens

---

packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
packages/grid/data-grid/src/tests/selection.DataGrid.test.tsx
packages/grid/x-grid/src/tests/selection.DataGridPro.test.tsx
test/utils/helperFn.ts

It aims at reducing the complexity of the tests to prepare for new tests in #2456

[test] Clean selection tests 

---

packages/grid/_modules_/grid/components/menu/GridMenu.tsx
packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenu.tsx
packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnMenuContainer.tsx
packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnMenuProps.tsx
packages/grid/x-grid/src/tests/columnHeaders.DataGridPro.test.tsx

Found a regression that is a quick win.
Currently pressing the `Escape` key when the `GridColumnHeaderMenu` is opened results in an error in the console and the menu doesn't close. This PR fixes the broken behavior.

[DataGrid] Pressing `Escape` should close `GridColumnHeaderMenu` without errors

---

packages/grid/_modules_/grid/constants/eventsConstants.ts
packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
packages/grid/x-grid/src/tests/state.DataGridPro.test.tsx

I'm starting to work on the tree data and I found it weird to listen to `props.rows` in a `useEffect` to trigger behavior that is based on `state.rows`.
We rely on the fact that when the `useEffect` of `useGridFilter` or `useGridSorting`, the update of the state of `useGridRows` has already been done.
Additionally, the description of the events was suggesting that it was trigger of rows update, not matter why it was updated
```
/**
* Fired when the rows are updated.
* @ignore - do not document.
*/
rowsSet = 'rowsSet',
```

[core] Publish GridEvents.rowsSet when the rows state is modified after props.rows is updated

---

package.json

The `next` branch is the default one on the config of Prettier in the core

[core] Only run Prettier on files different from 'next' instead of 'master'

---

packages/grid/_modules_/grid/components/containers/GridRootStyles.ts

I have noticed this on @siriwatknp's PR https://github.com/mui-org/material-ui/pull/28106, see how the icons are not vertically aligned:
https://deploy-preview-28106--material-ui.netlify.app/branding/x-advanced/
**Before**
**After**

[DataGrid] Vertically align column header icons

---

packages/grid/_modules_/grid/models/gridOptions.tsx

[core] Clean GridSimpleOptions interface

---

docs/pages/_app.js

The demos in https://mui.com/components/data-grid/demo/ are not working in codesandbox because the dependency used is from the `latest` tag. The dependencies that support @mui/material are in the `next` tag.

[docs] Include packages from next tag

---

docs/package.json
yarn.lock

Open https://mui.com/api/css-baseline/ and see how the results are duplicated
Note that I have created a new `docs-v4` branch. I propose that we update the core repo to use it, and kill the `release` branch, used for v4.

[docs] Fix Algolia index

---

packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
packages/grid/x-grid/src/tests/layout.DataGridPro.test.tsx

Based on this https://github.com/mui-org/material-ui-x/issues/2460
A small improvement that frees up column header space when column icons are not visible.
You can check Argos for more visual representation 😉
Before:
After:

[DataGrid] Free up column header space when icons are not visible

---

yarn.lock

After #2649, two versions of `jss` were available: 10.7.1 (docs) and 10.8.0 (root). This caused `jss-rtl` to be installed in the docs folder. Since the monorepo can only see dependencies from the root `node_modules`, the Netlify build [broke](https://app.netlify.com/sites/material-ui-x/deploys/6149c8fe939633b5143e1f68) when trying to import `jss-rtl`.

[core] Upgrade JSS plugins to 10.8.0

---

docs/src/pages/components/data-grid/getting-started/getting-started.md

The `latest` tag on npm is pointing to the v4 version, while the documentation at https://mui.com/getting-started/usage/ is for the v5 version. What happens is that users think that by following the installation instructions it will install a v5-compatible version, when it won't. We had a couple of issues related to this: #2660 and #2654.

[docs] Update installation instructions

---

packages/grid/_modules_/grid/models/colDef/index.ts

Fixes #2666 
Adds "single select" operators to the list of exports.
For more details - please see:
https://github.com/mui-org/material-ui-x/issues/2666

[DataGrid] Export single select operators (#2666)

---

packages/grid/_modules_/grid/components/cell/GridActionsCell.tsx
packages/grid/_modules_/grid/components/menu/GridMenu.tsx
packages/grid/_modules_/grid/components/toolbar/GridToolbarDensitySelector.tsx
packages/grid/_modules_/grid/components/toolbar/GridToolbarExport.tsx

Closes #2720 
https://user-images.githubusercontent.com/3309670/135226242-4e47113b-9436-4a3d-9039-817bc3808f32.mp4

[DataGrid] GridMenu should not remove the anchor before the end of the closing transition

---

docs/pages/index.js
docs/pages/playground.tsx

The bug:
1. open https://mui.com/components/data-grid/
2. click on the homepage link
3. a beautiful hello world page
This happens because Next.js uses client-side navigation in this configuration.

[docs] Fix index, improve playground

---

packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterInputValue.tsx
packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts
packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx

Fixes #2779 
This fix works by not filtering if the value field is empty. To filter empty values there're dedicated operators. The reason to ignore `singleSelect` is because the first option might be `<option value="">Any</option>`, which in this case it should filter when "empty".

[DataGrid] Don't filter numeric column when value is empty

---

test/e2e/index.test.ts

I believe this test fails because it's not waiting for the keyboard commands to take effect. It dispatches the command and immediately runs the assertion. I'm trying to fix it here by adding a `waitFor` which tries to assert a couple of times before giving up and throwing the error. I ran `yarn test:e2e` a good 10 times via SSH on CircleCI and all passed. I might be a little biased because I had to run #3026 more than 10 times to have one failing.
From #3026. The tab roving test begins at frame 59.
https://user-images.githubusercontent.com/42154031/139518181-78c597e2-bc76-49e1-a303-ce8ac4fea72f.mp4
This PR. The tab roving test begins at frame 84.
https://user-images.githubusercontent.com/42154031/139518358-6428fa40-2b3d-43fa-a691-4c965df26cfa.mp4
Both recordings are supposed to be at 60 …

[test] Retry each expect until success

---

packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
scripts/exportsSnapshot.json

Before, for N column with a filter removed, we ran (N+1) `applyFilters` and N `setGridState`.
For instance, if we changed the columns but did not impact any column with a filterItem, we re-applied the filter anyway.
And if we removed 2 columns that had a filter item, we ran the filters 3 times and did 2 `setGridState).
And the best scenario for the end, if you removed all the columns that had a filter item, it was N+2 `applyFilters`.
So if you had 2 filter item, you removed both columns, you ended up with 4 application of the filters.

[core] Run at most one setGridState and one applyFilters when updating the filterModel due to column changes

---

docs/src/pages/components/data-grid/getting-started/Codesandbox.js

What really matters here is that I have moved the owner of the codesandbox from my personal profile to the MUI's org one. This is important so that we can keep the demo up to date without having to do yet another PR like this one.
- Before: https://codesandbox.io/s/d3ex9
- After: https://codesandbox.io/s/datagrid-quick-start-0whfr
Preview: https://deploy-preview-3058--material-ui-x.netlify.app/components/data-grid/getting-started/#demo

[docs] Fix the outdated demo of the docs

---

docs/src/pages/components/data-grid/columns/ValueGetterGrid.js
docs/src/pages/components/data-grid/columns/ValueGetterGrid.tsx
docs/src/pages/components/data-grid/columns/columns.md

Solves #1313
add a paragraph in "column types" section to explain that column of type `"dateTime"` should not be stored with a string value.
I added subsections to separate clearly the two topics:
- the additional properties
- data type
preview: https://deploy-preview-3003--material-ui-x.netlify.app/components/data-grid/columns/#column-types

[docs] Explain how to use valueGetter to transform type

---

renovate.json

This is inspired by https://github.com/mui-org/material-ui/pull/28642. The core packages are all released at once, and depend on each other. It will be more efficient than: 
- #3034
- #3033
- #3032
- #3031
I didn't include `@mui/styles` because it's legacy

[core] Group update of MUI Core

---

.gitignore

Follow-up to #3054 
Nextjs 12 added `incremental` support which generates a xxx.tsbuildinfo file during build.
It matches with https://github.com/mui-org/material-ui/blob/master/.gitignore#L7

[core] Ignore *.tsbuildinfo files

---

packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx

Fixes #3076 
The logic of `currentSelectionSize` is O(n^2). Now it's O(n).

[DataGrid] Fix selecting 100k rows takes too long

---

packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts
packages/grid/_modules_/grid/utils/utils.ts
packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx

Introduced by #2994, was never released, I will merge it before the next release if no review :+1: 
The variable wording was approximate and I did not test enough.
`rowCount` was refering to the index of the last element of the page + 1
A few examples:
- `rows.length: 100, page: 0, pageSize: 10` => `rowCount: 10`
- `rows.length: 100, page: 1, pageSize: 10` => `rowCount: 20`
- `rows.length: 14, page: 1, pageSize: 10` => `rowCount: 14`
I will probably clean those methods later to add explicit comments on each instruction. 
Because `// we go to the current row, first col, or last col!` is not very explicit to me.

[DataGrid] Keyboard navigation broken on page > 0

---

package.json
yarn.lock

Revert to use the official repo instead of my fork.

[core] Use official MUI repo as monorepo dependency

---

packages/grid/_modules_/grid/hooks/core/useGridControlState.ts
packages/grid/_modules_/grid/hooks/features/clipboard/useGridClipboard.ts
packages/grid/_modules_/grid/hooks/features/editRows/useGridEditRows.ts
packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
packages/grid/_modules_/grid/hooks/features/pagination/useGridPage.ts
packages/grid/_modules_/grid/hooks/features/pagination/useGridPageSize.ts
packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
packages/grid/_modules_/grid/hooks/utils/useGridState.ts
packages/grid/_modules_/grid/models/api/gridClipboardApi.ts
packages/grid/_modules_/grid/models/api/gridControlStateApi.ts
packages/grid/_modules_/grid/models/api/gridFilterApi.ts
packages/grid/x-grid/src/tests/clipboard.DataGridPro.test.tsx

This wrong naming was introduced in https://github.com/mui-org/material-ui-x/pull/2985

[core] Use 'unstable_' prefix instead of 'unsafe_'

---

.github/workflows/close-incomplete-inactive.yml

This is identical to https://github.com/mui-org/material-ui/pull/27638. I do believe that it would be a net positive for the efficiency of the team. You can see it used at Ant Design for over 8 months with a [close delay of 3 days](https://github.com/ant-design/ant-design/blob/a0982081fa19b67eaf2064dc2e2845e00942aeba/.github/workflows/issue-close-require.yml).
If this experimentation is successful here, I think that we should move it to the other repositories. In the past, I didn't move forward in the main repository because Sebastian was against giving it a try. 
I saw https://github.com/mui-org/material-ui-x/issues/2559#issuecomment-950734506, it seems to be a waste of time to have to go back to older issues to close them manually. 
I think that the main one is: What happens if a …

[core] Automatically close issues that are incomplete and inactive

---

packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts

Preparing for the unlocking of the `apiRef` on the free plan.
I did not create a `disableMultiRowUpdates` prop with a forced value on the `DataGrid` like for `disableMultipleColumnsFiltering` because I don't see any situation where a user of the pro version would want to limit the updates to one row.
So for me it would only flood the prop list.
We could also add the prop only on `GridComponentProps` and set a forced value at `true` on `DataGrid` and `false` on `DataGridPro`.
But I think checking directly the signature is simpler.

[DataGrid] Block multi-rows updates in `apiRef.current.updateRows` on the free plan

---

packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts

Preview: https://deploy-preview-3127--material-ui-x.netlify.app/components/data-grid/editing/#client-side-validation
A regression from #2996 
When there're more than one instance of the DataGrid, calling `updateRows` will mess with all rows because it reuses the same rows from the other instance. This method is called, for example, on the cell editing to commit the new value.
1. Open https://next--material-ui-x.netlify.app/components/data-grid/editing/#client-side-validation
2. Double-click a cell to edit it
3. Click outside the cell
I didn't add tests because this behavior only happens with multiple instances.

[DataGrid] Fix `updateRows` to not use rows from other instances

---

packages/grid/_modules_/grid/components/Watermark.tsx

Reuse `LicenseStatus` `enum` in `Watermark` component.

[core] Improve `getLicenseErrorMessage` param type

---

packages/grid/_modules_/grid/components/containers/GridRootStyles.ts

Fixes #1805
Instead of modifying the style of the scroll bar, we set `color-scheme` property on the root div according to the palette mode.
- For users with @mui/material (v5.1.0)
They have to remove the `darkScrollbar()` from their theme and use `enableColorScheme` prop. The  `color-scheme` property will be defined twice (once in the `<html>` and once in the `DataGrid` root `<div>`) but It is not a problem.
- For user bellow @mui/material (v5.1.0)
I'm not sure. They can avoid using `darkScrollbar()` in the app style to avoid overriding the native scrollbar style. But this would lead to a page scrollbar unadapted. I'm wondering if they could not simply use
```jsx
MuiCssBaseline: {
styleOverrides: {
html: {
colorScheme: theme.palette.mode 
},
},
},
```
instead of
```jsx
MuiCssBaseline: { …
```

[DataGrid] Use color-scheme to set dark mode on native components

---

packages/grid/_modules_/grid/hooks/features/export/index.ts

This file is never used
And the `index.ts` in the feature hook folders should only contain variable publicly exposed (which is not the case for the feature hooks themselves).

[core] Remove the index.ts of the export hooks

---

docs/src/pages/components/data-grid/accessibility/accessibility.md
docs/src/pages/components/data-grid/selection/selection.md

Some explanations in the doc seems to be wrong/out dated
- Disabling multi rows selection is not necessary to unselect row with ctrl key
- To select a range of rows, "Shift + Arrow Up/Down" is enough. No need of "Space"
- Some key for sorting columns was in the table about "Selection" instead of "Sorting"

[docs] move sentence about disabling multi rows selection

---

packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts

Remove abstractions whenever possible to make the code easier to read
- No key mapping
- No clamping afterwards, we are doing the checks during the switch
- Explicit variables `viewportPageSize` / `firstRowIndexInPage` / `lastRowIndexInPage` / `firstColIndex` / `lastColIndex` to make the switch statement as clear as possible
- A single `goToCell` and `goToHeader` method to abstract the scroll and focus behaviors
On v6 I think we should replace the `cellNavigationKeyDown` and `columnHeaderNavigationKeyDown` with `apiRef` methods.
For me events should  be "hey I did X, do whatever you want with this information" not "hey, could someone listen to me and do X".

[DataGrid] Rework keyboard navigation

---

packages/grid/_modules_/grid/hooks/features/dimensions/useGridDimensions.ts

Fixes #3212, little regression introduced in #3007
We are debouncing the resize event to avoid resizing the grid dozens of time when resizing the window.
But debouncing even the 1st resize event mean that the initialization is debounced, causing a render to squeeze between the column init without there flex size (to now if we need a scrollbar) and there update with there flex size.
- With this PR no-flickering: https://codesandbox.io/s/columnfluidwidthgrid-material-demo-forked-i546y
- On v5.0.1 flickering:  https://codesandbox.io/s/3q8ue?file=/package.json
- On v5.0.0-beta.7 no flickering: https://codesandbox.io/s/columnfluidwidthgrid-material-demo-forked-bvyg6
It revert the only Argos snapshot changes of #3007 because the `onRowScrollEnd` is called on initialization, like before #3007
It …

[DataGrid] Do not debounce the initial resizing of the grid

---

docs/README.md
docs/next.config.js

A follow-up on the change of the default branch from *next* to *master*. Asked in https://mui-org.slack.com/archives/G011VC970AW/p1637339352041900
Note that I also had to update the baseline branch of Argos-CI manually in the DB:

[core] Reflect the change of default branch

---

packages/grid/_modules_/grid/locales/deDE.ts

@m4theushw This is the requested follow-up PR for #3230, which adds the last missing translations found for the de_DE locale.

[l10n] Add missing translation for de_DE locale (2)

---

test/regressions/TestViewer.js
test/regressions/index.test.js

During the migration to react-router v6 in #3119, one of the regression tests was not working correctly. The `setTimeout` was never running, although it should since the clock is mocked. I tried one workaround of waiting a bit but it was not very reliable. This PR contains the proper fix. It turns out that since the same component is used for every route, React doesn't remount the component so the mount effect never run when the route changes. The mount effect was responsible for running all pending timers. It worked with react-router-dom v5 because, in this version, the route component was cloned before, instead of only returned.

[test] Force effect to run on location change

---

packages/grid/x-data-grid-pro/LICENSE
packages/grid/x-data-grid-pro/LICENSE.md
packages/x-license-pro/LICENSE
packages/x-license-pro/LICENSE.md

This change is meant to improve the DX when browsing the license files. The PR removes the `.md` extension.
In https://mui.com/pricing/, we try to explain to the audience how to navigate the license file:
- https://unpkg.com/@mui/material@5.0.1/LICENSE 200
- https://unpkg.com/@mui/x-data-grid@5.0.1/LICENSE 200
- https://unpkg.com/@mui/x-data-grid-pro@5.0.1/LICENSE 404 ❌
I think that I was wrong to make the second link a markdown, it's never interpreted as such.

[DataGridPro] Improve license file

---

packages/grid/_modules_/grid/locales/deDE.ts

This PR adds the missing tree data labels for the de_DE locale.

[l10n] Improve German (de_DE) locale

---

docs/src/pages/components/data-grid/getting-started/getting-started.md

https://mui.com/components/data-grid/getting-started/#support
This got broken in https://github.com/mui-org/material-ui/pull/29431 and got noticed in ahrefs:

[docs] Fix broken images

---

docs/src/pages/components/data-grid/getting-started/migration-v4.md
docs/src/pages/components/data-grid/localization/localization.md
docs/src/pages/components/data-grid/overview/overview.md

Older versions of the documentation are hosted on a subdomain, e.g. https://v4.mui.com/components/data-grid/. Using relative links would help keep the user on the **same version** of the documentation.

[docs] Use relative links

---

docs/src/pages/components/data-grid/accessibility/accessibility.md

> Nesting a `<kbd>` element within another `<kbd>` element represents an actual key or other unit of input as a portion of a larger input.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd#usage_notes
The a11y page might be one where we want to follow the recommendations more closely. We worked on this problem in https://github.com/mui-org/material-ui/pull/24269.

[docs] Key conbinations should have a nested kbd

---

docs/pages/api-docs/data-grid/data-grid-pro.json
packages/grid/_modules_/grid/GridComponentProps.ts
packages/grid/_modules_/grid/hooks/features/treeData/useGridTreeData.ts
packages/grid/x-data-grid-pro/src/DataGridPro.tsx

The format will evolve and we want to avoid breaking changes so we are disabling this feature before releasing it.

[DataGridPro] Temporarily remove the callback version of the `groupingColDef` prop

---

packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
packages/grid/_modules_/grid/models/gridSortModel.ts
packages/grid/x-data-grid/src/tests/sorting.DataGrid.test.tsx
scripts/exportsSnapshot.json

Fixes #3020
It unifies the behavior with the filter. If we have an item that uses a non-existing column, we just ignore it.
This is necessary when the `sortModel` is controlled. When we change the columns, we automatically clean the `sortModel`. But when it is controlled, the update can be async and occurs after the `applySorting` triggered by the row change. So we have an `applySorting` with the new columns but the old `sortModel`, which causes a crash.
Before: https://codesandbox.io/s/datagriddemo-material-demo-forked-r27yc?file=/demo.tsx

[DataGrid] Should not crash when a sort item uses a non-existing column

---

docs/src/pages/components/data-grid/getting-started/getting-started.md
docs/src/pages/components/data-grid/overview/overview.md

Closes #3324
I also moved the equivalent links in `getting-started` to relative paths.

[docs] Fix dead link on the overview page

---

packages/grid/rollup.x-data-grid-pro.config.js
packages/x-license-pro/rollup.config.js

It's a regression from #3278. See how there are no license files in https://unpkg.com/browse/@mui/x-data-grid-pro@5.1.0/.

[core] Fix missing LICENSE file

---

packages/grid/x-data-grid/package.json

Add an incentive for donation to the MUI non-profit, to sustain the MIT effort. We use the same field in MUI Core, you can find the same in https://unpkg.com/react-table@7.7.0/package.json. In practice, I doubt that it will have much impact. Donations are <1% of our funding.

[core] Add funding field

---

docs/src/modules/components/ApiPage.js

I recall fixing this in the main repo https://github.com/mui-org/material-ui/pull/28634. However, we **forked** the component so the fix didn't propagate here:
How did I find this? Looking at the [ahrefs crawl audit](https://app.ahrefs.com/site-audit/2944028/16/data-explorer?columns=pageRating%2Curl%2Ctraffic%2Ctitle%2Cserp_title%2Cis_page_title_used_in_serp%2Ctop_keyword%2Ctop_keyword_position&filterCollapsed=true&filterId=a18e81583b7c422e0270e064cd41b3cf&issueId=d69246c2-225a-11ec-8456-06d2f2f613d8).

[docs] Fix double MUI in the title

---

docs/pages/components/data-grid/events.js
docs/pages/components/data-grid/group-pivot.js
docs/src/pages/components/data-grid/editing/editing.md
docs/src/pages/components/data-grid/group-pivot/group-pivot.md

Take https://mui.com/components/data-grid/events/ as an example:
We display an ad at the top and below the demos:
This is not needed for commercial licensed software.

[docs] Disable the ad when not MIT

---

docs/next-env.d.ts
packages/grid/_modules_/grid/components/cell/GridTreeDataGroupingCell.tsx
packages/grid/_modules_/grid/hooks/features/treeData/gridTreeDataGroupColDef.ts
packages/grid/_modules_/grid/hooks/features/treeData/useGridTreeData.tsx
packages/grid/_modules_/grid/models/colDef/gridColDef.ts
packages/grid/x-data-grid-pro/src/tests/treeData.DataGridPro.test.tsx

Extracted from #3277 
Will be properly documented and tested in the docs of the grouping columns, I don't think it's worth creating an example for the Tree Data.

[DataGridPro] Add new option hideDescendantCount to Tree Data

---

packages/grid/_modules_/grid/hooks/features/treeData/useGridTreeData.tsx

Extracted from #3277
`Shift` + `Space` is selecting / unselecting the row, the children selection should only be applied when pressing `Space` without `Shift`
I also added two small core improvements 
- Do the `groupingColDef` computation in a `useCallback` instead of a  `useMemo` to avoid running the `prop.groupingColDef` callback version on the tree data grouping column when the tree data is not enabled.
- Use the `rowNode` from the params in the `cellKeyDown` event instead of using the `apiRef` (helps us remove an useless check)

[DataGridPro] Do not expand row children when pressing `Shift` + `Space`

---

.github/FUNDING.yml

Same incentive as #3331. This will enable the following button in the header:
This won't have much impact, only to reinforce that MIT is fueled by the contributions of the community. In an ideal world, we wouldn't need a commercial license to push our mission forward on MUI X. 
I'm working on this as a quick follow-up on a bug we had in MUI Core: https://github.com/mui-org/material-ui/commit/e6558bc2ccf47e8330ec1c35ec23d68d35bd8624.

[core] Add link to OpenCollective

---

packages/grid/rollup.x-data-grid-pro.config.js
packages/grid/rollup.x-data-grid.config.js

The `x-data-grid` folder is being bundled with DataGridPro. See https://unpkg.com/browse/@mui/x-data-grid-pro@5.2.0/. I noticed in #3389.

[core] Remove `x-data-grid` folder from DataGridPro bundle

---

docs/pages/_app.js

- Go to https://mui.com/components/data-grid/pagination/#paginate-gt-100-rows
- Click to open the demo in CodeSandbox
- It doesn't run because `@mui/x-data-grid-generator` needs `@mui/x-data-grid`

[docs] Include @mui/x-data-grid as dependency in the CodeSandbox

---

packages/grid/_modules_/grid/locales/deDE.ts

This PR adds the missing column pinning translations for the German (de-DE) locale.

[l10n] Improve German (de-DE) locale 

---

packages/grid/_modules_/grid/locales/nlNL.ts

Fix missing translations dutch, fix incorrect translations of filterOperatorAfter, filterOperatorOnOrAfter, filterOperatorBefore, filterOperatorOnOrBefore #3211

[l10n] Improve Dutch (nl-NL) locale

---

packages/grid/x-data-grid-pro/src/DataGridProVirtualScroller.tsx

There was a performance hit when scrolling because it was filtering the columns on every render.

[DataGridPro] Avoid filtering columns if no column is pinned

---

.circleci/config.yml

I have applied https://github.com/mui-org/material-ui/pull/29040 here. (*a new example to illustrate the pros of mono-repo > multiple-repos*). This is in the scope of the [React infra](https://www.notion.so/mui-org/React-infra-5562c14178aa42af97bc1fa5114000cd) group.
For example, on https://github.com/mui-org/material-ui-x/pull/3437 take the restore cache step of `test_browser`:
It uses 4 GB of storage and takes 2 minutes to happen. Now compare it to the CI build on this PR for `test_browser`:
Better no? 😄

[core] Increase CI efficiency

---

packages/grid/_modules_/grid/locales/frFR.ts

The `Print` option of the `DataGrid` wasn't translated.  
This PR should fix this.

[l10n] Improve French (frFR) locale

---

packages/grid/_modules_/grid/components/cell/GridCell.tsx
packages/grid/_modules_/grid/components/containers/GridRootStyles.ts

Fixes #2859 
A small change to the way we center content in grid cells - the result is to enable multi-lines in grid cells.

[DataGrid] Remove `line-height` from `GridCell`

---

packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx

Fix #1431
Add tests to verify the row can be selected by pressing `Space`. This test must be in e2e test, because the onChange of the checkbox is only fired by click in react-testing-library (https://github.com/testing-library/react-testing-library/issues/156).
I also removed `Space` from the keys entering edit mode, because it was overriding two accessibility keys presented in the [Doc](https://mui.com/components/data-grid/accessibility/#selection)
keys | action
:--: | --
<kbd>Space</kbd> | Navigate to the next scrollable page
<kbd>Shift</kbd> + <kbd>Space</kbd> | Select the current row

[test] Row checkbox selection is handled by click and space key

---

packages/grid/_modules_/grid/components/cell/GridActionsCell.tsx
packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx

Fixes #3489
Preview: https://deploy-preview-3492--material-ui-x.netlify.app/components/data-grid/columns/#special-properties
If we continue to add more column types with interactive elements, then it makes sense to add a per-column `disableSelectionOnClick`.

[DataGrid] Close other actions menus when opening a new one

---

docs/src/pages/components/data-grid/group-pivot/group-pivot.md
packages/grid/_modules_/grid/hooks/features/index.ts
packages/grid/_modules_/grid/hooks/features/treeData/gridTreeDataGroupColDef.ts
packages/grid/_modules_/grid/hooks/features/treeData/index.ts
packages/grid/_modules_/grid/hooks/features/treeData/useGridTreeData.tsx
scripts/x-data-grid-pro.exports.json
scripts/x-data-grid.exports.json

Fixes #3434
I renamed the column internal variables with `GROUPING` instead of `GROUP` to follow the convention of #212.

[DataGridPro] Expose the field of the tree data grouping column as a constant

---

packages/grid/x-data-grid-pro/src/tests/editRows.DataGridPro.test.tsx
test/cli.js

Fixes one test not running in Safari: https://app.circleci.com/pipelines/github/mui-org/material-ui-x/11257/workflows/486e64b7-1fa4-44dc-8afa-e891edf3d561/jobs/65177
The solution is a workaround I proposed in https://github.com/mui-org/material-ui-x/pull/3372#discussion_r766064601. Basically, the unit tests run with a fake clock, which causes `waitFor` to also run with the fake clock. Here I call the native `setTimeout` to make sure that the promise was resolved. With #3558 I think we'll be able to use the fake clock on a per-test case basis, not in the entire suite.
I also took the opportunity to copy `test/cli.js` from the core repo. This allows to debug each unit test using VSCode.

[test] Properly wait for promise to resolve before expect

---

packages/grid/_modules_/grid/locales/ukUA.ts

[l10n] Improve Ukrainian (ukUA) locale

---

packages/grid/_modules_/grid/hooks/features/export/serializers/csvSerializer.ts
packages/grid/x-data-grid-pro/src/tests/export.DataGridPro.test.tsx

Fixes #2860
When cell value contains line break character, CSV export results in broken CSV since part of the value goes to the next line.
Wrapping value into quotes in this case fixes the issue.

[DataGrid] Fix line break characters breaking CSV rows 

---

packages/grid/_modules_/grid/hooks/core/rowGroupsPerProcessing/gridRowGroupsPreProcessingApi.ts
packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
packages/grid/_modules_/grid/utils/tree/buildRowTree.test.ts
packages/grid/_modules_/grid/utils/tree/buildRowTree.ts
packages/grid/x-data-grid-pro/src/tests/treeData.DataGridPro.test.tsx

Part of #3377 
With this enhancement, we should be able to add a working demo with row children lazy loading implemented by users.

[DataGridPro] Keep row children expansion when updating the rows

---

renovate.json

I'm doing https://github.com/mui-org/material-ui-x/pull/3362#issuecomment-986722279. This is done manually, for each major. I have left a note in https://github.com/mui-org/material-ui-x/issues/3287 for MUI X v6. The solution is based on https://github.com/renovatebot/config-help/issues/81
So far, we have [closed 11 times PRs](https://github.com/mui-org/material-ui-x/pulls?q=is%3Apr+%22Bump+Node.js+to%22+is%3Aclosed) that try to upgrade Node manually, this is no good, a distraction and a risk to break the next release.
Closes #3643 
Closes #3638

[core] Renovate should not try to update node

---

packages/grid/_modules_/grid/components/ErrorOverlay.tsx
packages/grid/_modules_/grid/components/base/GridBody.tsx
packages/grid/_modules_/grid/components/base/GridErrorHandler.tsx
packages/grid/_modules_/grid/components/base/GridOverlays.tsx
packages/grid/_modules_/grid/components/containers/GridOverlay.tsx
packages/grid/x-data-grid-pro/src/tests/columnHeaders.DataGridPro.test.tsx
packages/grid/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx
packages/grid/x-data-grid/src/tests/pagination.DataGrid.test.tsx

Fixes #3276
Preview: https://deploy-preview-3558--material-ui-x.netlify.app/components/data-grid/
I don't know why we never tried that. The warning is always triggered inside `GridOverlay` as part of `GridOverlays`. It turns out that `GridOverlays` is rendered before `GridAutoSizer`. That way, subscribing inside a normal effect has no risk of losing any resize event, because React executes the effects sequentially according to the tree.

[DataGrid] Fix potential memory leak warning

---

docs/src/pages/components/data-grid/editing/ConditionalValidationGrid.js
docs/src/pages/components/data-grid/editing/ConditionalValidationGrid.tsx
docs/src/pages/components/data-grid/editing/ValidateRowModelControlGrid.js
docs/src/pages/components/data-grid/editing/ValidateRowModelControlGrid.tsx
docs/src/pages/components/data-grid/editing/ValidateServerNameGrid.js
docs/src/pages/components/data-grid/editing/ValidateServerNameGrid.tsx
packages/storybook/src/stories/grid-rows.stories.tsx

In #3446 we didn't update the demos.
Preview: https://deploy-preview-3567--material-ui-x.netlify.app/components/data-grid/editing/#client-side-validation
Before:
After:

[docs] Make inputs to extend full height of the cell

---

packages/grid/_modules_/grid/components/menu/columnMenu/HideGridColMenuItem.tsx
packages/grid/x-data-grid/src/tests/columnHeaders.DataGrid.test.tsx

Closes #2718 
Preview: https://deploy-preview-3607--material-ui-x.netlify.app/components/data-grid/
https://user-images.githubusercontent.com/13808724/149194518-189a7444-fb9d-423a-8c13-94cac2256d32.mov

[DataGrid] Disable Hide button if there's only one visible column

---

benchmark/browser/README.md

#3527 was created before #3504 so it was merged without running `yarn markdownlint` which broke the CI.

[core] Add language to markdown code block

---

docs/src/pages/components/data-grid/group-pivot/TreeDataLazyLoading.js
docs/src/pages/components/data-grid/group-pivot/TreeDataLazyLoading.tsx
docs/src/pages/components/data-grid/group-pivot/TreeDataLazyLoading.tsx.preview
docs/src/pages/components/data-grid/group-pivot/group-pivot.md

Part of  #3377 
[Doc preview](https://deploy-preview-3657--material-ui-x.netlify.app/components/data-grid/group-pivot/#children-lazy-loading)

[DataGridPro] Add doc example for tree data children lazy loading

---

renovate.json

Same fix as https://github.com/mui-org/material-ui/pull/29303 to avoid these kinds of regressions: https://github.com/mui-org/material-ui-x/pull/3630#pullrequestreview-853778223

[core] Don't bump peer dependency ranges on dependency updates

---

packages/grid/x-data-grid-pro/src/tests/export.DataGrid.test.tsx

`Blob.text()` is only [available](https://developer.mozilla.org/en-US/docs/Web/API/Blob/text) in Safari 14. We test in Safari 13. The CI broke after merging #3623.

[test] Skip tests on Safari

---

packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx
packages/grid/x-data-grid-pro/src/DataGridProVirtualScroller.tsx
packages/grid/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx
test/e2e/fixtures/DataGridPro/KeyboardNavigationFocus.tsx
test/e2e/index.test.ts

Fixes #3613
Preview: https://deploy-preview-3667--material-ui-x.netlify.app/components/data-grid/demo/
The issue exists only in `DataGridPro`.
It turned out that the root cause of the issue was this place:
https://github.com/mui-org/material-ui-x/blob/b9afc07f87e5cdb7b585dfc08f2b570ed53caed8/packages/grid/x-data-grid-pro/src/DataGridProVirtualScroller.tsx#L161-L163
It caused duplicated render zone refresh with wrong scrollTop.
I've traced it's dependencies and saw this:
https://github.com/mui-org/material-ui-x/blob/b9afc07f87e5cdb7b585dfc08f2b570ed53caed8/packages/grid/x-data-grid-pro/src/DataGridProVirtualScroller.tsx#L122-L129
After wrapping it with `React.useCallback` the issue was gone.
It's easier to review with 'Hide whitespace' option enabled …

[DataGridPro] Fix grid cell losing focus when scrolling with keyboard

---

packages/grid/x-data-grid-pro/src/useDataGridProComponent.tsx

Each hook using `GridPreProcessingGroup.hydrateColumns` and called **after** `useGridColumns` causes a full additional pre-processing on mount because the columns need to be pre-processed **before** and **after** the 1st call of the feature hook.
Whereas if the feature hook is before, the pre-processing will only run once when `useGridColumns` is called.
The same applies to other pre-processings but this one is especially heavy when we have a lot of columns and has a lot of hooks hooked to it, so we could quickly run 5 or more useless pre-processings if we don't take care.
To more we move toward event listeners and pre-processors, the more `useGridRows` and `useGridColumns` should be late in the feature hook call order.
Same things as described here …

[core] Call `useGridColumnPinning` before `useGridColumns`

---

packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx
packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
packages/grid/x-data-grid-pro/src/tests/selection.DataGridPro.test.tsx
packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx

Fix #3382
The stop propagation prevents having the selection event dispatched two times when clicking on the checkbox. One time by checkbox change, and the other one by row click event.
The problem is that it also prevents setting the focus on the cell. So now, interacting with the checkbox set the focus on its cell.
I did not add tests to detect the reported bug, because jsdom does not mock correctly, scrolling.

[DataGrid] Fix focus on checkbox cells

---

packages/grid/_modules_/grid/hooks/features/columns/gridColumnsUtils.ts
packages/grid/x-data-grid-pro/src/tests/columnsVisibility.DataGridPro.test.tsx

[DataGrid] Only update the visibility status of the updates columns when calling `apiRef.current.updateRows`

---

docs/src/pages/components/data-grid/localization/localization.md

We probably missed this one during the v5 migration

[docs] Fix broken code example on the localization page

---

packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts

Fixes #3477 by only preventing default for non registered shortcuts. This behavior applies both for cells and column headers.
Preview: https://deploy-preview-3692--material-ui-x.netlify.app/components/data-grid/demo/
When a cell / header cell had focus, no keyboard shortcuts would work. The problem was on the `useGridKeyboardNavigation` hook which was `event.preventDefault()` to any key press.
Only prevent default behavior to shortcuts / keys we are expecting. 
Solution provided by @m4theushw

[DataGrid] Fix browser keyboard shortcuts not working when header cell is focused

---

packages/grid/_modules_/grid/constants/localeTextConstants.ts
packages/grid/_modules_/grid/locales/arSD.ts
packages/grid/_modules_/grid/locales/bgBG.ts
packages/grid/_modules_/grid/locales/csCZ.ts
packages/grid/_modules_/grid/locales/deDE.ts
packages/grid/_modules_/grid/locales/elGR.ts
packages/grid/_modules_/grid/locales/esES.ts
packages/grid/_modules_/grid/locales/faIR.ts
packages/grid/_modules_/grid/locales/fiFI.ts
packages/grid/_modules_/grid/locales/frFR.ts
packages/grid/_modules_/grid/locales/heIL.ts
packages/grid/_modules_/grid/locales/itIT.ts
packages/grid/_modules_/grid/locales/jaJP.ts
packages/grid/_modules_/grid/locales/koKR.ts
packages/grid/_modules_/grid/locales/nlNL.ts
packages/grid/_modules_/grid/locales/plPL.ts
packages/grid/_modules_/grid/locales/ptBR.ts
packages/grid/_modules_/grid/locales/ruRU.ts
packages/grid/_modules_/grid/locales/skSK.ts
packages/grid/_modules_/grid/locales/trTR.ts
packages/grid/_modules_/grid/locales/ukUA.ts
packages/grid/_modules_/grid/locales/viVN.ts
packages/grid/_modules_/grid/locales/zhCN.ts
packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts
packages/grid/_modules_/grid/models/colDef/gridSingleSelectOperators.ts
packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts

Fix #3743
When running `yarn l10n` the csCZ file is not updated. I did it manually
The file is open, but it has an early return due to this condition https://github.com/alexfauquette/material-ui-x/blob/fix-isAnyLabel/scripts/l10n.ts#L266:L268

[DataGrid] Add l10n support for 'is any of'

---

.github/ISSUE_TEMPLATE/3.pro-support.yml
.github/workflows/support-stackoverflow.yml
.github/workflows/support.yml

This change is meant to improve the support workflow. We have:
1. Renamed `support` to `support: StackOverflow` to make it clear about what this is about. It's about fair value sharing. We give MIT components away for free. In exchange, MUI expects developers to give back by contributing. The expectation is not for maintainers to spend even more time to do others' work (when we apply this label), but for maintainers to process new contributions.
2. Renamed `question` to `support: question`. This is similar to the above, but we find the question so *valuable* to answer that we take it in.
3. Add a new `support: commercial` label. It's unlikely that the community will provide a lot of help to each other on the MUI X Pro plan, and will clearly not happen on the MUI X Premium plan. We have to …

[core] Improve GitHub label workflows

---

packages/grid/x-data-grid-generator/src/renderer/renderCountry.tsx
packages/grid/x-data-grid-generator/src/renderer/renderEditCountry.tsx
packages/grid/x-data-grid-generator/src/renderer/renderEditCurrency.tsx

Open https://master--material-ui-x.netlify.app/components/data-grid/demo/. The width of the flag change between no loaded and loaded img:
This creates a layout shift which is distracting. To be clear, this is a low value fix, but I noticed it, knew the solution as I faced it with the Autocomplete's demo already so went for it: small improvements like this compound.
Preview: https://deploy-preview-3773--material-ui-x.netlify.app/components/data-grid/demo/

[docs] Fix flag layout shift

---

benchmark/package.json
docs/scripts/api/buildComponentsDocumentation.ts
docs/src/modules/XWrapper.js
docs/src/modules/components/ApiDocs.js
package.json
test/regressions/TestViewer.js
test/regressions/index.js
yarn.lock

Closes #2991 
The file `@mui/monorepo/docs/pages/_document` still depends on it so we can't remove `@mui/styles` from `docs/package.json` yet.

[core] Remove remaining usages of @mui/styles

---

test/karma.conf.js

The last green build was 5 days ago. Before and after this, Firefox has timed out in the majority of the cases. I want to test if increasing the timeout solves the issue. This is the same value used by the core: https://github.com/mui-org/material-ui/pull/28476

[test] Increase timeout for Firefox

---

docs/src/pages/components/data-grid/localization/localization.md
packages/grid/_modules_/grid/locales/daDK.ts
packages/grid/_modules_/grid/locales/index.ts

[l10n] Add Danish (daDK) locale thanks to @kasperfilstrup

---

packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
packages/grid/_modules_/grid/hooks/features/pagination/useGridPage.ts
packages/grid/_modules_/grid/hooks/features/pagination/useGridPageSize.ts
packages/grid/_modules_/grid/hooks/features/rowGrouping/useGridRowGrouping.tsx
packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts

I think https://github.com/mui-org/material-ui-x/pull/3593 wasn't rebased after https://github.com/mui-org/material-ui-x/pull/3774 was merged. So each PR passed the CI checks, but after merging both browser tests started to fail. https://app.circleci.com/pipelines/github/mui-org/material-ui-x/12556/workflows/bcd9e8a8-e135-47e2-90ee-aac7a9a4551c/jobs/73603
Any ideas how to avoid this kind of things? Force rebase on master before merge? I though Github bot does this automatically, but maybe it wasn't fast enough? 😀

[core] Fix browser tests failing on master

---

docs/src/pages/components/data-grid/rows/RowsGridWithGetRowId.js
docs/src/pages/components/data-grid/rows/RowsGridWithGetRowId.tsx
docs/src/pages/components/data-grid/rows/RowsGridWithGetRowId.tsx.preview
docs/src/pages/components/data-grid/rows/rows.md
packages/grid/_modules_/grid/models/gridRows.ts
packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx

Currently `DataGrid` throws an error if row doesn't have an `id` property.
This is not documented though, and there's `getRowId` prop that can be used instead.
I've updated the error message to mention `getRowId` prop as well.
Preview: https://deploy-preview-3765--material-ui-x.netlify.app/components/data-grid/rows/

[docs] Mention row `id` requirement and document `getRowId` prop

---

docs/src/modules/components/ApiDocs.js

I used the wrong CSS prop in #3769.
In https://master--material-ui-x.netlify.app/components/data-grid/selection/#apiref

[docs] Extend full width

---

scripts/README.md

I have updated https://www.notion.so/mui-org/Releases-7490ef9581b4447ebdbf86b13164272d to be more in sync with what we do, and also to improve a bit the process. In any case, it's not code-related so I'm moving the content out of git.
Same as in https://github.com/mui-org/material-ui/pull/30843 and a continuation of #2997.

[core] Remove none code related instructions from git

---

packages/grid/_modules_/grid/components/cell/GridCell.tsx

Fix #3712 
When a click outside of the grid implies a rerender of the grig, the focus goes back to the previous cell.
The problem is that rows rerendering occur before the `handleDocumentClick` which is responsible for removing the focus in the internal state. So when the click causes a rendering we have:
- The browser focus is moved to the clicked element
- The rows rerender and the internal state is such that one cell will have prop `hasFocus=true`
- The `handleDocumentClick` is run which clean the `state.focus`
I do not understand why the `handleDocumentClick` is executed after.

[DataGrid] Fix focus when blur event rerender the grid

---

packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx
packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx
packages/grid/_modules_/grid/constants/localeTextConstants.ts
packages/grid/_modules_/grid/locales/arSD.ts
packages/grid/_modules_/grid/locales/bgBG.ts
packages/grid/_modules_/grid/locales/csCZ.ts
packages/grid/_modules_/grid/locales/daDK.ts
packages/grid/_modules_/grid/locales/deDE.ts
packages/grid/_modules_/grid/locales/elGR.ts
packages/grid/_modules_/grid/locales/esES.ts
packages/grid/_modules_/grid/locales/faIR.ts
packages/grid/_modules_/grid/locales/fiFI.ts
packages/grid/_modules_/grid/locales/frFR.ts
packages/grid/_modules_/grid/locales/heIL.ts
packages/grid/_modules_/grid/locales/itIT.ts
packages/grid/_modules_/grid/locales/jaJP.ts
packages/grid/_modules_/grid/locales/koKR.ts
packages/grid/_modules_/grid/locales/nlNL.ts
packages/grid/_modules_/grid/locales/plPL.ts
packages/grid/_modules_/grid/locales/ptBR.ts
packages/grid/_modules_/grid/locales/ruRU.ts
packages/grid/_modules_/grid/locales/skSK.ts
packages/grid/_modules_/grid/locales/trTR.ts
packages/grid/_modules_/grid/locales/ukUA.ts
packages/grid/_modules_/grid/locales/viVN.ts
packages/grid/_modules_/grid/locales/zhCN.ts
packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
packages/grid/x-data-grid-pro/src/tests/selection.DataGridPro.test.tsx
packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx
scripts/performance.js

Closes #1457 
See https://github.com/mui-org/material-ui-x/issues/1457#issuecomment-826102508
CodeSandbox without having to wrap `Tooltip` in a div: https://codesandbox.io/s/material-demo-forked-xpydy?file=/demo.tsx

[DataGrid] Allow to translate `checkboxSelection` labels

---

docs/src/pages/components/data-grid/getting-started/CoreV5WithCoreV4.js
docs/src/pages/components/data-grid/getting-started/migration-v4.md

Act on the learnings of https://mui.zendesk.com/agent/tickets/2217
- The iframe is primarily about using MUI Core v4 with v5, not MUI X, it can help a lot more people
- The page is more about MUI X than the data grid
- Fix a theme reference that is undefined
- Mention Material UI not to disorient people too much to link the notion to MUI Core.
- Make the migration structure clearer
- Fix a few syntaxes in the git diff
- Remove the scrollbar in the iframe demo
- Crosslink the MUI Core v5 migration
Before: https://mui.com/components/data-grid/migration-v4/
After: https://deploy-preview-3847--material-ui-x.netlify.app/components/data-grid/migration-v4/

[docs] Clarify a bit the migration to v5

---

packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts
packages/grid/x-data-grid-pro/src/useDataGridProComponent.tsx
packages/grid/x-data-grid/src/useDataGridComponent.tsx

That way the split between `useGridPage` and `useGridPageSize` only occurs inside `hooks/features/pagination`
And outside of this folder we have 1 substate = 1 feature hook

[core] Add hook `useGridPagination` to call `onGridPage` and `onGridPageSize`

---

docs/data/data-grid/getting-started/getting-started.md

cf https://github.com/mui/material-ui/pull/30913
https://deploy-preview-3877--material-ui-x.netlify.app/components/data-grid/getting-started/#feature-comparison

[docs] Fix sorting feature link

---

.eslintrc.js
docs/data/data-grid/group-pivot/TreeDataLazyLoading.js
docs/data/data-grid/group-pivot/TreeDataLazyLoading.tsx
packages/grid/_modules_/grid/components/cell/GridGroupingCriteriaCell.tsx
packages/grid/x-data-grid-generator/src/renderer/renderEditProgress.tsx

Fixes #3899 and #3883
`@mui/base` is transitive dependency not declared in `package.json`.
Yarn PnP requires packages to [only import what they list in dependencies](https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies)
TODO:

[DataGridPro] Avoid imports from `@mui/base`

---

docs/data/data-grid/columns/columns.md
docs/data/data-grid/filtering/filtering.md
docs/data/data-grid/getting-started/migration-v4.md
docs/data/data-grid/group-pivot/group-pivot.md
docs/data/data-grid/pagination/pagination.md
docs/data/data-grid/selection/selection.md

I tried a Grammarly extension to help catch English errors in the doc. @samuelsycamore could you check that I'm not introducing  new ones

[docs] Use Grammarly to fix some typo

---

docs/data/data-grid/export/RemovePrintExport.js
docs/data/data-grid/export/RemovePrintExport.tsx
docs/data/data-grid/export/RemovePrintExport.tsx.preview
docs/data/data-grid/export/export.md

Fix #3756
[preview](https://deploy-preview-3822--material-ui-x.netlify.app/components/data-grid/export/)
I propose the following structure, starting from common properties to export format-specific ones
- Enabling export
- Default Toolbar
- Custom Toolbar
- Customize export selector
- Remove an export option
- Exported columns
- Exported rows
- CSV export
- Exported cells
- File encoding
- Print export
- Customize grid display
- apiRef
- CSV
- Print
- Excel export
- Clipboard
- API

[docs] reorganize export docs to prepare excel export doc

---

scripts/l10n.ts

The intent is to update
to show `### ar-SD` instead of `### arSD`. I'm trying to solve the root cause of https://github.com/mui/mui-x/pull/3831#pullrequestreview-872229983.

[core] Use international locale format

---

packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx

Test added in #3835 doesn't pass on Firefox:

[test] Skip test on Firefox

---

packages/grid/_modules_/grid/locales/heIL.ts

Add missing translations & fixes
I am not sure why the check fails. I ran all required scripts before pushing the changes.

[I10n] Improve Hebrew (he-IL) locale

---

packages/grid/x-data-grid-pro/src/tests/filtering.DataGridPro.test.tsx
packages/grid/x-data-grid/src/internals/components/panel/GridPanel.tsx

Fixes #3809
The reason for this bug is very simple. Without memoizing the modifiers array, its reference changes in every render. Since it's [listed](https://github.com/mui/material-ui/blob/4214d4d1b03586dd0fd5e6733e1ede6bad010787/packages/mui-base/src/PopperUnstyled/PopperUnstyled.js#L155) as dependency in the effect that creates the Popper instance, in `PopperUnstyled`, it's recreated and repositioned every time that a rerender occurs, like when deleting a filter.

[DataGrid] Memoize Popper modifiers passed to panel

---

docs/data/data-grid/group-pivot/group-pivot.md

I fixed a typo in the documentation. I found it while exploring the experiemental features of mui-x.

[docs] Fix typo on row grouping section

---

scripts/README.md

- Add missing GitHub release step to the list
- Make instruction a checklist, so it can be copied to release PR and used as Todo list - example https://github.com/mui/mui-x/pull/3914

[core] Update release instructions

---

yarn.lock

Reverts mui/mui-x#3976
The doc crashes, I'll wait for the core to update since the error is in one for there files

Revert "Bump next from 12.0.10 to 12.1.0"

---

packages/grid/x-data-grid-pro/src/internals/hooks/features/detailPanel/gridDetailPanelToggleColDef.tsx

Currently, export a table with detailed panels exports a column with name: 
`__detail_panel_toggle__`and only values: ` true` or `false` indicating the state.
These are not usefull values and should be disabled by default

[DataGridPro] Disable export for detail panel column

---

docs/data/data-grid/editing/editing.md

In the documentation for [Data Grid/Editing/Client-side validation](https://mui.com/components/data-grid/editing/#client-side-validation), `params` is incorrectly typed. This PR makes the example consistent with the `preProcessEditCellProps` property of [GridColDef](https://mui.com/api/data-grid/grid-col-def/#properties).

[docs] Fix typo in Data Grid/Editing/Client-side validation

---

docs/data/data-grid/filtering/CustomFilterPanelContent.js
docs/pages/api-docs/data-grid/data-grid-pro.json
docs/pages/api-docs/data-grid/data-grid.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
docs/translations/api-docs/data-grid/data-grid-pro-pt.json
docs/translations/api-docs/data-grid/data-grid-pro-zh.json
docs/translations/api-docs/data-grid/data-grid-pro.json
docs/translations/api-docs/data-grid/data-grid-pt.json
docs/translations/api-docs/data-grid/data-grid-zh.json
docs/translations/api-docs/data-grid/data-grid.json
packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx
packages/grid/x-data-grid/src/constants/defaultGridSlotsComponents.ts
packages/grid/x-data-grid/src/models/gridIconSlotsComponent.ts

[DataGrid] Add Filter Panel delete icon slot

---

packages/grid/x-data-grid-pro/src/tests/filtering.DataGridPro.test.tsx
packages/grid/x-data-grid/src/components/panel/GridPanel.tsx

Fixes #4011 
Preview: https://deploy-preview-4067--material-ui-x.netlify.app/components/data-grid/
We weren't resetting `isPlaced` when the panel is closed. Not doing that was making it to be opened, during the second time, as if it was already positioned. When it opens, we try to focus the input element, but since it's not correctly positioned yet it focus while the panel is still at the top-left corner of the page = unwanted scroll. For some reason, this only happens with the `isAnyOf` operator. A hypothesis is that, because the Autocomplete is a heavy component, it takes more time for React to process it than a TextField, delaying the Popper modifier that is responsible for positioning the panel. With the TextField, React only calls the effect below when the panel is already positioned …

[DataGrid] Prevent focus while Popper is not fully positioned

---

packages/grid/x-data-grid-generator/src/columns/commodities.columns.tsx
packages/grid/x-data-grid-generator/src/columns/employees.columns.tsx

1. Open https://master--material-ui-x.netlify.app/components/data-grid/group-pivot/#full-example
2. Scroll all the way to the right
3. 💥
I noticed while reviewing #4030 
A better solution would be to not render the cells in auto-generated rows, but we have the problem where we need to call `getCellParams` to pass to `cellClassName` which calls the value formatter.

[docs] Avoid crash in demos using row grouping and custom formatted cells

---

packages/grid/x-data-grid-pro/src/DataGridPro/useDataGridProComponent.tsx
packages/grid/x-data-grid/src/DataGrid/useDataGridComponent.tsx
packages/grid/x-data-grid/src/hooks/features/pagination/useGridPage.ts
packages/grid/x-data-grid/src/hooks/features/pagination/useGridPageSize.ts
packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts
packages/grid/x-data-grid/src/internals/index.ts

That way the split between `useGridPage` and `useGridPageSize` remains an implementation details of the `hooks/features/pagination` folder.

[core] Merge `page` and `pageSize` state initializer into a single `pagination` state initializer

---

docs/data/data-grid/localization/localization.md
docs/scripts/api/buildComponentsDocumentation.ts
docs/translations/api-docs/data-grid/data-grid-pro-pt.json
docs/translations/api-docs/data-grid/data-grid-pro-zh.json
docs/translations/api-docs/data-grid/data-grid-pro.json
docs/translations/api-docs/data-grid/data-grid-pt.json
docs/translations/api-docs/data-grid/data-grid-zh.json
docs/translations/api-docs/data-grid/data-grid.json
packages/grid/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx
packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx
packages/grid/x-data-grid/src/models/props/DataGridProps.ts

Updated the URL to correctly point the localization URL

[docs] Fix outdated links to localeTextConstants.ts

---

.github/ISSUE_TEMPLATE/4.premium-support.yml

After reading https://groups.google.com/a/mui.com/g/custom-work/c/5RRqH0YkZ6o/m/aWBVaxkrBAAJ?utm_medium=email&utm_source=footer, I recalled the point that @cherniavskii did during our last retrospective that this issue template is only meant for cases where the problem is not a bug nor a feature request. But the current description is not very clear.
To be clear, this PR is modifying https://github.com/mui/mui-x/issues/new/choose

[core] Make is clearer this is only for questions

---

test/e2e-website/data-grid-current.spec.ts

Somehow, the search result changes on the old search (it previously showed the `Components` as the first item). This PR reduces the fragility of the test by using regex instead of a specific url.

[docs] Use regex instead of specific url in e2e-website-tests

---

docs/data/data-grid/columns/columns.md
docs/data/data-grid/editing/editing.md
docs/data/data-grid/filtering/filtering.md
docs/data/data-grid/overview/overview.md
docs/data/data-grid/pagination/pagination.md
docs/data/data-grid/sorting/sorting.md

Open https://mui.com/x/react-data-grid/ and try searching for "edit".
The result from Algolia indicates that the duplicated result does not have `/`.

[docs] Fix links to prevent duplicate search result

---

docs/pages/api-docs/data-grid/data-grid-pro.json
docs/pages/api-docs/data-grid/data-grid.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
packages/grid/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx
packages/grid/x-data-grid-pro/src/tests/cellEditing.DataGridPro.test.tsx
packages/grid/x-data-grid-pro/src/tests/editComponents.DataGridPro.test.tsx
packages/grid/x-data-grid-pro/src/tests/rowEditing.DataGridPro.test.tsx
packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx
packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx
packages/grid/x-data-grid/src/components/cell/GridCell.tsx
packages/grid/x-data-grid/src/models/props/DataGridProps.ts
packages/grid/x-data-grid/src/tests/cells.DataGrid.test.tsx
packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx
packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx

Fixes #3850 
This PR changes to, by default, not fire the warning sent when a cell is clicked with `fireEvent.click` without `fireEvent.mouseUp`. Instead it will only be triggered if the new prop `experimentalFeatures.warnIfFocusStateIsNotSynced` is `true` and `NODE_ENV=test`.

[test] Make focus state out-of-sync warning opt-in

---

packages/grid/x-data-grid/src/locales/plPL.ts

Adds missing translations for Polish (`pl-PL`) locale - https://github.com/mui/mui-x/issues/3211.

[l10n] Improve Polish (pl-PL) locale

---

packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx

Fix #3436 
The problem is the following: To know when the rendered context must be updated, it relies on the top-left cell. If the index of the cell has changed by more than `rowThreshold` or `columnThreshold`, the `renderContext` is updated, which will rerender visible rows/cells and their buffer
This would work if columns/rows have the same size, which is not the case. Here is an example of scrolling on the right.
In purple you have the initial render context and in blue the buffer. From top to bottom we scrolled enough, such that 
- the visible left cell changed from 3 to 4 (a gap of 1)
- the visible right cell changed from 5 to 8 (a gap of 3)
To be sure that visible columns are always rendered, we need to increase verify on the left and the right (same thing for the top/bottom)

[DataGrid] Fix white blank when scrolling

---

packages/x-license-pro/bin/license-decode-script.js
packages/x-license-pro/package.json
packages/x-license-pro/src/cli/license-cli.ts

@mbrookes, with this you would be able to do:
```shell
npm i -g @mui/x-license-pro
npx licensedecode -k xxx
```
I took the same naming strategy as `licensegen` but in a 2nd version I would like to correctly namespace the commands and do:
```shell
npx mui-license gen -o xxx
npx mui-license decode -k xxx
```

[core] Add CLI to decode license key

---

packages/grid/x-data-grid/src/hooks/features/selection/useGridSelection.ts
packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx

[DataGrid] Do not unselect row when shift + click on the last selected row of a range

---

scripts/README.md

See https://github.com/mui/mui-x/pull/3831#discussion_r827443134 for why. A TL:DR of the problem:
1. `git checkout v5.6.1`
2. `yarn lerna changed`
3. LOL WUT?
```
$ yarn lerna changed
yarn run v1.22.17
$ /Users/oliviertassinari/mui-x/node_modules/.bin/lerna changed
lerna notice cli v4.0.0
lerna info Looking for changed packages since v4.0.0-alpha.25
@mui/x-license-pro
@mui/x-data-grid-generator
@mui/x-data-grid-pro
@mui/x-data-grid
lerna success found 4 packages ready to
```
I have discovered this problem trying to make my point on that `@mui/x-license-pro` should almost never be published in the current state of things. We need to use an annotated tag. It's done correctly in https://github.com/mui/material-ui. Sebastian fixed this problem in the core a while ago.

[core] Fix Lerna package change detection

---

packages/grid/x-data-grid/src/locales/koKR.ts

I found that the translation for `filterOperatorIsAnyOf` is missing, so I added☺️

[l10n] Improve Korean (ko-KR) locale

---

docs/data/data-grid/export/export.md

Fix #3378 
Instead of forcing the style to be light during print, we highlight in the doc how to modify colors in print

[docs] Explain how to use `printOptions.pageStyle`

---

docs/data/data-grid/export/export.md

Follow up from https://github.com/mui/material-ui/pull/31807
Preview: https://deploy-preview-4222--material-ui-x.netlify.app/components/data-grid/export/#print-export

[docs] Document Print export `X-Frame-Options` limitation

---

packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaderTitle.tsx

As this gets passed to `Tooltip`s `title` prop, it should match the type I believe. 
ref: https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Tooltip/Tooltip.d.ts#L165

[DataGrid] Adjust type of GridColumnHeaderTitle description prop

---

docs/pages/api-docs/data-grid/data-grid-pro.json
docs/pages/api-docs/data-grid/data-grid.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
docs/translations/api-docs/data-grid/data-grid-pro-pt.json
docs/translations/api-docs/data-grid/data-grid-pro-zh.json
docs/translations/api-docs/data-grid/data-grid-pro.json
docs/translations/api-docs/data-grid/data-grid-pt.json
docs/translations/api-docs/data-grid/data-grid-zh.json
docs/translations/api-docs/data-grid/data-grid.json
packages/grid/x-data-grid/src/components/panel/GridPanel.tsx
packages/grid/x-data-grid/src/constants/gridClasses.ts

[DataGrid] Add missing classes on `gridClasses` and `gridPanelClasses`

---

packages/grid/x-data-grid/src/hooks/features/scroll/useGridScroll.ts

I have found this by looking into #4280 in more detail. This code path is never reached, it seemed to have been here for when we implemented the virtualization without using a native scroll container, so we had to reset the scrollLeft and scrollRight. This is no longer the case.

[core] Remove dead code

---

packages/grid/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx

Fix #4200 
The inconsistency between header and rows comes from the computation of the last column, which should be modified as follow
```diff
-isLastColumn={columnIndex === columns.length - 1}
+isLastColumn={columnIndex === visibleColumns.length - 1}
```
It appears in the issue example because one of the columns was hidden
In #2444 the consistency has been added, and the chosen solution was to remove borders for the last column. I propose to do the opposite for two reasons:
- It seems that at that time if the last column was flex, it displayed a double border. One for the grid container, and one for the cell border. This problem does not occur now
- In the Pro version, we need handlers to resize columns. If `showColumnRightBorder=true` this handlers became invisible, and so we need a …

[DataGrid] Fix last column border inconsistency

---

packages/grid/x-data-grid/src/hooks/features/scroll/useGridScroll.ts
packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx

Fix the following bug: https://github.com/mui/mui-x/pull/4280#discussion_r835798116
- Go in codesandbox.io/s/datagridprodemo-material-demo-forked-8e4l8w
- Click on a column header
- Press <kbd>Arrow Right</kbd> to navigate to the last column
- You are not able to do it because there is no row in the grid

[DataGrid] Allows to use keyboard navigation even with no rows

---

test/regressions/TestViewer.js

On tests that displays the seconds, letting the time tick means that depending on the execution speed, the date visible can vary by one second.
It would be nice to avoid advancing it for the data grid as well, but that would require changing our approach.
The core is only mocking `Date` so all the other async processes are handled out of the box. But in our case it breaks other stuff.

[core] Fix Argos flakyness for pickers tests

---

packages/grid/x-data-grid/src/components/containers/GridRoot.tsx
packages/grid/x-data-grid/src/hooks/features/dimensions/gridDimensionsApi.ts
packages/grid/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts
packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx

Fixes 2nd bug from https://github.com/mui/mui-x/issues/4275#issuecomment-1079451619
CodeSandbox: https://codesandbox.io/s/flamboyant-framework-zcmw34?file=/src/App.js
If the `rows` prop is not empty, `updateGridDimensionsRef` is called at least 3 times. The 2 first calls come from the following effect and the `visibleRowSet` event.
https://github.com/mui/mui-x/blob/e66404d4b15c5bfc524cfb6ab1b39e013cd91167/packages/grid/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts#L247
Additionally, there's a third call after rows hydration. This ensures that in one of these calls `apiRef.current.rootElementRef` will be defined and the scrollbar can be calculated from it.
If `rows=[]` this scenario doesn't repeat. In the rows hydration, `rowsMeta.currentPageTotalHeight` is always `0`, so …

[DataGrid] Fix overlay blocking scrollbar when `rows` is empty

---

docs/data/date-pickers/migration-lab/migration-lab.md
docs/data/pages.ts
docs/pages/x/react-date-pickers/migration-lab.js

@siriwatknp rightfully pointed out that we were missing a dedicated migration page.
[Doc preview](https://deploy-preview-4327--material-ui-x.netlify.app/x/react-date-pickers/migration-lab/)

[docs] New page for the pickers migration from the lab

---

packages/x-date-pickers-pro/README.md
packages/x-date-pickers-pro/package.json
packages/x-date-pickers-pro/src/DateRangePicker/DateRangePicker.tsx
packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx
packages/x-date-pickers-pro/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx
packages/x-date-pickers-pro/src/MobileDateRangePicker/MobileDateRangePicker.tsx
packages/x-date-pickers-pro/src/StaticDateRangePicker/StaticDateRangePicker.tsx
packages/x-date-pickers/README.md
packages/x-date-pickers/package.json
packages/x-date-pickers/src/CalendarPicker/CalendarPicker.tsx
packages/x-date-pickers/src/CalendarPickerSkeleton/CalendarPickerSkeleton.tsx
packages/x-date-pickers/src/DatePicker/DatePicker.tsx
packages/x-date-pickers/src/DateTimePicker/DateTimePicker.tsx
packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.tsx
packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.tsx
packages/x-date-pickers/src/MobileDatePicker/MobileDatePicker.tsx
packages/x-date-pickers/src/MobileDateTimePicker/MobileDateTimePicker.tsx
packages/x-date-pickers/src/MobileTimePicker/MobileTimePicker.tsx
packages/x-date-pickers/src/PickersDay/PickersDay.tsx
packages/x-date-pickers/src/StaticDatePicker/StaticDatePicker.tsx
packages/x-date-pickers/src/StaticDateTimePicker/StaticDateTimePicker.tsx
packages/x-date-pickers/src/StaticTimePicker/StaticTimePicker.tsx
packages/x-date-pickers/src/TimePicker/TimePicker.tsx

The /components/ folder looked wrong, this seems to be a safe change. 
---
Two thoughts:
1. The data grid entry point has a flat folder structure: https://master--material-ui-x.netlify.app/x/react-data-grid/ but the date picker doesn't: https://master--material-ui-x.netlify.app/x/react-date-pickers/getting-started/. The former seems more efficient from an SEO perspective. What if we added an overview page too for the date picker?
2. Where should the npm `@mui/x-date-picker` package "homepage" link to? `/x/react-date-pickers/` or the specific component. I kind of like the former for suggesting it's a broad package, date picker, time picker, etc.

[docs] Fix some links to date picker docs

---

packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx
packages/grid/x-data-grid/src/components/virtualization/GridVirtualScrollerContent.tsx
packages/grid/x-data-grid/src/components/virtualization/GridVirtualScrollerRenderZone.tsx

Preview: https://deploy-preview-4405--material-ui-x.netlify.app/components/data-grid/#commercial-version
Closes #4360 
Before: 
https://user-images.githubusercontent.com/13808724/162418465-d58fa4df-e9a1-4156-9561-f4bbb9f9e885.mov
After:
https://user-images.githubusercontent.com/13808724/162440323-2e888f2d-d7ca-4df2-88fd-da1151f4f7a2.mov

[DataGrid] Fix scrollbar grabbing issue in Safari

---

packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json

```
$ yarn explain peer-requirements pe404c
➤ YN0000: @mui/x-date-pickers@npm:5.0.0-alpha.0 [b95f3] doesn't provide react-dom, breaking the following requirements:
➤ YN0000: react-transition-group@npm:4.4.2 [419ef] → >=16.6.0 ✘
```

[pickers] Add react-dom to pickers peer deps to satisfy react-transition-group

---

packages/grid/x-data-grid/src/components/columnSelection/GridCellCheckboxRenderer.tsx

Fixes
_Screenshot taken from https://mui.com/components/data-grid/demo/_

[DataGrid] Fix `api` prop leaking to DOM

---

CHANGELOG.md

A follow-up on #4328. I already updated the GitHub release.

[CHANGELOG] Fix links on v5.8.0

---

packages/x-date-pickers/src/internals/components/CalendarOrClockPicker/CalendarOrClockPicker.tsx
packages/x-date-pickers/src/internals/hooks/date-helpers-hooks.tsx
packages/x-date-pickers/src/internals/models/props/baseToolbarProps.ts

[pickers] Add TDate generic to CalendarOrClockPicker component

---

packages/grid/x-data-grid-pro/src/tests/rowEditing.DataGridPro.new.test.tsx
packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts

In #4252 I forgot to `clamp` the indexes. This was raised in https://github.com/mui/mui-x/pull/4252#issuecomment-1084673222
I also took the opportunity to improve which cell receives focus when editing the first column of the first row or the last column of the last column. Previously, focus would jump to the last cell or the first cell when these conditions are met. Now we keep focus on the current cell.
1. Open https://codesandbox.io/s/basicroweditinggrid-material-demo-forked-zdftxh?file=/demo.tsx
2. Double-click on the "Last login" cell of the last row
3. Press <kbd>Tab</kbd>
4. 💥
CodeSandbox with the fix: https://codesandbox.io/s/basicroweditinggrid-material-demo-forked-soxqwq?file=/demo.tsx

[DataGrid] Fix focus after stopping row edit mode with pagination enabled

---

docs/pages/_app.js

`@date-io/date-fns` has a peer dependency on `date-fns`.
Preview: https://deploy-preview-4508--material-ui-x.netlify.app/x/react-date-pickers/date-picker/
1. Go to https://mui.com/x/react-date-pickers/date-picker/#basic-usage
2. Click to open the demo in CodeSandbox
3. Fails with "Could not find dependency: 'date-fns' relative..."

[docs] Include `date-fns` dependency when opening demos in CodeSandbox

---

packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.test.tsx
packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.tsx
packages/x-date-pickers/src/MobileTimePicker/MobileTimePicker.tsx
packages/x-date-pickers/src/internals/hooks/usePickerState.ts

Fix #4578
The bug has been introduced in #4398 
When the new value is `null` it can not be merged with the previous date.
I always forget one of the three types of values the components deal with: `Date` | `null` | invalid-date

[TimePicker] Fix bug when time picker clear value

---

packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.test.tsx
packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.test.tsx
packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.tsx

Fix #4504
Migration from https://github.com/mui/material-ui/pull/31350 with tests added

[pickers] Pass `PaperProps` to `DesktopWrapper` component

---

packages/x-date-pickers/src/DateTimePicker/DateTimePicker.test.tsx
packages/x-date-pickers/src/MobileDatePicker/MobileDatePicker.test.tsx

[test] Fix test to not depend on screen resolution

---

packages/grid/x-data-grid-pro/src/tests/columnHeaders.DataGridPro.test.tsx
packages/grid/x-data-grid/src/components/menu/GridMenu.tsx
packages/grid/x-data-grid/src/hooks/features/columnMenu/useGridColumnMenu.ts
packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
packages/grid/x-data-grid/src/models/events/gridEventLookup.ts
packages/grid/x-data-grid/src/models/events/gridEvents.ts
packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx

Fixes #4139 
Preview: https://deploy-preview-4498--material-ui-x.netlify.app/x/react-data-grid/
CodeSandbox: https://codesandbox.io/s/fullfeatureddemo-material-demo-forked-98j7cp?file=/demo.tsx
I implemented the solution from https://github.com/mui/mui-x/issues/4139#issuecomment-1092047815. I chose this one because it also unlocks the possibility to have filters inside the column menu. Previously, we couldn't because the column menu closes when filtering: https://github.com/mui/mui-x/issues/3571#issuecomment-1009524740

[DataGrid] Don't close column menu when updating rows

---

docs/data/pages.ts

Handle https://github.com/mui/mui-x/pull/4591#issuecomment-1107535769. It's a dirty fix, but it works 😁. From my perspective, the notion of `scopePathnames` should not exist in the first place.
https://deploy-preview-4626--material-ui-x.netlify.app/x/react-data-grid/tree-data/

[docs] Quick sidenav fix

---

docs/data/data-grid/getting-started/getting-started.md

I forgot to update it when releasing the feature

[docs] Update the feature table in the Getting Started page of the data grid

---

packages/grid/x-data-grid/src/hooks/utils/useGridApiEventHandler.test.tsx
packages/grid/x-data-grid/src/hooks/utils/useGridApiEventHandler.ts
packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts
packages/grid/x-data-grid/src/internals/index.ts
packages/grid/x-data-grid/src/utils/createSelector.ts
test/karma.tests.js

In https://github.com/mui/mui-x/pull/4031 I ignored karma tests because I was under the assumption that, due to the fact that `FinalizationRegistry` is available, the memory would be cleaned by itself. This is partially correct, the memory is cleaned indeed, but the reference to `FinalizationRegistry` is never garbage-collected. This PR fixes this bug by explicitly setting it to `null`.

[test] Reset cleanup tracking on Karma tests

---

test/karma.tests.js

Apply
https://github.com/mui/mui-x/blob/aefd2fc9b63bf0537a526ccb702e003691193f72/test/utils/setup.js#L76-L80
to karma tests too.
[Before](https://app.circleci.com/pipelines/github/mui/mui-x/17377/workflows/f31b9348-8636-42a1-a1d6-937f92aed1c6/jobs/101321/resources):
[After](https://app.circleci.com/pipelines/github/mui/mui-x/17441/workflows/d8fb5a0d-e9f7-49b4-8af9-a6600e3c01e3/jobs/101697/resources):

[test] Restore sinon sandbox after each karma test

---

packages/grid/x-data-grid-premium/src/components/GridGroupingCriteriaCell.tsx
packages/grid/x-data-grid-premium/src/hooks/features/rowGrouping/useGridRowGrouping.tsx

Part of #4684
This PR demonstrated what I want to do in #4684 but only on `@mui/x-data-grid-premium` to give a small example.
If you are ok with it, I can apply it to all our codebase.

[data grid] Stop using GridEvents enum in `@mui/x-data-grid-premium`

---

docs/pages/_app.js
yarn.lock

X docs will benefit from these improvements:
1. **Code copy**
2. **Callouts**:
in markdown, use this syntax to render callout
```md
:::info
Hello test
:::
:::success
Hello test
:::
:::warning
Hello test
:::
:::error
Hello test
:::
```

[docs] Update mono repo to get copy code block

---

.circleci/config.yml
package.json

Copy of https://github.com/mui/material-ui/pull/24933 which solves the exact same problem on the core
The issue likely comes from the creation of `@mui/x-data-grid-premium` which added an additional parallel run.

[core] Prevent out-of-memory when type-checking in CI

---

packages/grid/x-data-grid-pro/src/components/DataGridProColumnHeaders.tsx
packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx
packages/grid/x-data-grid-pro/src/components/GridRowReorderCell.tsx
packages/grid/x-data-grid-pro/src/components/GridTreeDataGroupingCell.tsx
packages/grid/x-data-grid-pro/src/hooks/features/columnPinning/useGridColumnPinning.tsx
packages/grid/x-data-grid-pro/src/hooks/features/columnReorder/useGridColumnReorder.tsx
packages/grid/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx
packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts
packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanelCache.ts
packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts
packages/grid/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx
packages/grid/x-data-grid-pro/src/hooks/features/treeData/useGridTreeData.tsx
packages/grid/x-data-grid-pro/src/models/dataGridProProps.ts
packages/grid/x-data-grid-pro/src/tests/cellEditing.DataGridPro.new.test.tsx
packages/grid/x-data-grid-pro/src/tests/cellEditing.DataGridPro.old.test.tsx
packages/grid/x-data-grid-pro/src/tests/events.DataGridPro.spec.ts
packages/grid/x-data-grid-pro/src/tests/events.DataGridPro.test.tsx
packages/grid/x-data-grid-pro/src/tests/rowEditing.DataGridPro.new.test.tsx
packages/grid/x-data-grid-pro/src/tests/selection.DataGridPro.test.tsx

Part of #4684 
Follow up on #4685
Will automerge, I don't think it's worth reviewing since it does not change anything concrete and #4685 has been approved.

[data grid] Stop using `GridEvents` enum in `@mui/x-data-grid-pro`

---

docs/data/data-grid/editing-legacy/CatchEditingEventsGrid.js
docs/data/data-grid/editing-legacy/CatchEditingEventsGrid.tsx
docs/data/data-grid/editing-legacy/FullFeaturedCrudGrid.tsx
docs/data/data-grid/editing/FullFeaturedCrudGrid.tsx
docs/data/data-grid/editing/StartEditButtonGrid.tsx
docs/data/data-grid/events/CatalogOfEventsNoSnap.js
docs/data/data-grid/master-detail/FullWidthDetailPanel.js
docs/data/data-grid/master-detail/FullWidthDetailPanel.tsx
docs/data/data-grid/row-grouping/RowGroupingGetRowGroupChildren.js
docs/data/data-grid/row-grouping/RowGroupingGetRowGroupChildren.tsx
docs/data/data-grid/tree-data/TreeDataCustomGroupingColumn.js
docs/data/data-grid/tree-data/TreeDataCustomGroupingColumn.tsx
docs/data/data-grid/tree-data/TreeDataLazyLoading.js
docs/data/data-grid/tree-data/TreeDataLazyLoading.tsx
docs/data/data-grid/tree-data/tree-data.md
packages/storybook/src/stories/grid-rows.stories.tsx

Part of https://github.com/mui/mui-x/issues/4684
Follow up on https://github.com/mui/mui-x/pull/4685
Will automerge, I don't think it's worth reviewing since it does not change anything concrete and https://github.com/mui/mui-x/pull/4685 has been approved.

[docs] Stop using `GridEvents` enum in documentation

---

packages/x-date-pickers/src/internals/components/PickersArrowSwitcher.tsx

Preview: https://deploy-preview-4672--material-ui-x.netlify.app/x/react-date-pickers/date-picker/
An example for #4669 
My goal was to only restore the capability to provide overrides via the theme and add meaningful class names. I didn't add the `classes` prop. 
Some components have "private" class names. Do you agree to make them public? In the DataGrid every new class is public.
https://github.com/mui/mui-x/blob/0d8a55d4f460767942c01398a373028ef2e1e7da/packages/x-date-pickers/src/CalendarPicker/PickersSlideTransition.tsx#L18
Before:
After:

[pickers] Add overrides to `PickersArrowSwitcher`

---

packages/x-date-pickers/src/CalendarPicker/CalendarPicker.test.tsx
packages/x-date-pickers/src/CalendarPicker/PickersCalendarHeader.tsx
packages/x-date-pickers/src/MobileDatePicker/MobileDatePicker.test.tsx
packages/x-date-pickers/src/StaticDatePicker/StaticDatePicker.test.tsx

Fixes mui/mui-x#4463.
Allow changing the order of month and year in PickersCalendarHeader by using `monthAndYear` format instead of using `month` and `year` format separately.
Ref https://github.com/mui/material-ui/pull/31888

[DatePicker] Make month year order changeable in header

---

packages/x-date-pickers/src/CalendarPicker/DayPicker.test.tsx
packages/x-date-pickers/src/CalendarPicker/DayPicker.tsx
packages/x-date-pickers/src/DatePicker/DatePicker.test.tsx

[pickers] Do not apply the current time when no date provided in `DayPicker`

---

packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts

Fix columnHeaderDrag uses cellDragOver and cellDragOver run infinite scroll
https://user-images.githubusercontent.com/8194467/166219804-e2abc8a5-62bf-40d9-b2f1-7206a3ababe0.mov

[DataGrid] Fix columnHeaderDrag uses cellDragOver

---

packages/x-date-pickers/src/ClockPicker/ClockPicker.test.tsx
packages/x-date-pickers/src/ClockPicker/ClockPicker.tsx
packages/x-date-pickers/src/PickersDay/PickersDay.tsx
packages/x-date-pickers/src/internals/hooks/validation/useTimeValidation.ts

Closes #4604
[Example](https://codesandbox.io/s/basictimepicker-material-demo-forked-ml8br3?file=/demo.js)

[TimePicker] Disable and invalidate date with minutes not matching `minutesStep`

---

packages/x-date-pickers-pro/src/DesktopDateRangePicker/DesktopDateRangePicker.test.tsx

[DateRangePicker] Refacto tests

---

packages/grid/x-data-grid-generator/src/services/random-generator.ts
test/regressions/webpack.config.js

Fixes https://github.com/mui/mui-x/issues/4144#issuecomment-1066853139
Vite doesn't make available environment variables other than `process.env.NODE_ENV`.

[core] Check if `process` is available

---

yarn.lock

#4625 broke the master branch, we couldn't develop anymore.
```
./node_modules/@mui/monorepo/docs/packages/markdown/prism.js
Module parse failed: Cannot use 'import.meta' outside a module (87:16)
File was processed with these loaders:
* ../node_modules/next/dist/compiled/@next/react-refresh-utils/loader.js
* ../node_modules/next/dist/build/babel/loader/index.js
You may need an additional loader to handle the result of these loaders.
|                 // still a Refresh Boundary later.
|                 // @ts-ignore importMeta is replaced in the loader
>                 import.meta.webpackHot.accept();
|                 // This field is set when the previous version of this module was a
|                 // Refresh Boundary, letting us know we need to check for invalidation or
```
#4772 …

[core] Update monorepo & version

---

docs/data/data-grid/getting-started/getting-started.md
docs/data/data-grid/selection/selection.md
docs/data/data-grid/tree-data/tree-data.md
docs/data/date-pickers/migration-lab/migration-lab.md
docs/public/_redirects
packages/grid/x-data-grid-premium/LICENSE
packages/grid/x-data-grid-pro/LICENSE
packages/x-date-pickers-pro/LICENSE
packages/x-license-pro/LICENSE
packages/x-license-pro/src/utils/licenseErrorMessageUtils.ts

Goes hand in hand with https://github.com/mui/material-ui/pull/32515
- Fix one regression from https://github.com/mui/mui-x/pull/4441
- Fix https://github.com/mui/material-ui/blob/6eabacaf0e79a52f65f1147bbf4b835c79d4f4d1/docs/public/_redirects#L26 that points to the wrong location after:
https://github.com/mui/mui-store/pull/139
- Add a new code redirection for the LICENSE files: https://unpkg.com/@mui/x-data-grid-pro@5.10.0/LICENSE
- Account for https://github.com/mui/mui-x/pull/4692#issuecomment-1112680762
https://deploy-preview-4711--material-ui-x.netlify.app/

[docs] SEO fixes

---

test/regressions/index.js

Follow-up to #4575
All argos screenshots are different because now they have a fixed width, instead of `100%`. It's weird #4575 didn't generate the base screenshots.

[test] Fix path to detect DataGrid tests

---

docs/data/pages.ts

Quick followup on #4600
Before:
https://user-images.githubusercontent.com/13808724/167468001-5e7c4965-de4b-4155-9cf0-1c2b21faee31.mov
After:
https://user-images.githubusercontent.com/13808724/167468024-3eb3aded-b576-4fe8-ac76-431b46a8e688.mov

[docs] Keep columns section expanded when switching between pages

---

packages/grid/x-data-grid/src/hooks/features/preferencesPanel/useGridPreferencesPanel.ts

Part of #4737
The check in `hidePreferences` to know if the panel is opened was based on the state from the state render.
When calling `hidePreferences` synchronously after `showPreferences`, we could have an outdated state and thus an invalid check leading to an unwanted event publication.

[data grid] Only publish `preferencePanelClose` event once when closing panel by clicking on another panel button

---

packages/x-date-pickers/src/TimePicker/shared.ts
packages/x-date-pickers/src/internals/hooks/usePickerState.ts

Fixes #4751
[Behavior before](https://codesandbox.io/s/date-and-time-pickers-forked-cxyxoq?file=/src/App.tsx)
[Behavior after](https://codesandbox.io/s/date-and-time-pickers-forked-yeomeg?file=/src/App.tsx)
To test it fully:
1. Focus the end of the input
2. Press the back key until you remove the `3`
3. Type `2 AM`
The date logged below should still be in 2018

[TimePicker] Don't merge with previous value when new value is not valid

---

packages/x-date-pickers-pro/src/themeAugmentation/components.d.ts
packages/x-date-pickers-pro/src/themeAugmentation/overrides.d.ts
packages/x-date-pickers-pro/src/themeAugmentation/props.d.ts
packages/x-date-pickers/src/themeAugmentation/overrides.d.ts
packages/x-date-pickers/src/themeAugmentation/props.d.ts

Fix #4762
The error seems to come from reusing the same naming for the exported interface so I renamed them with `Pickers` and `PickersPro` prefix
I set `PickersPro` to be sure that when both pro and community packages are installed, both naming do not collide
I don't know how to test this issue. Maybe using creat-react-app add the lab and pickers package generated by the CI, and run `tsc`. Do you have a better idea?

[core] Fix naming collision

---

packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePickerKeyboard.test.tsx
packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.test.tsx
packages/x-date-pickers/src/internals/utils/text-field-helper.test.ts
packages/x-date-pickers/src/internals/utils/text-field-helper.ts

Fix #4838
The problem comes from the classical mistake of deleting elements from an array and making a mix between the original and filtered array.
The bug occurs as follows:
- User type a full date `01/02/1921`
- The press a letter in the middle. Such as the new value to parse is `01/0g2/1921`
- Since `g` is not a valid character it will be removed.
- when arriving at the last character we rely on it's index in the input string to know if it overflow the mask. SInce it's the case, it's deleted
This is a quick fix for the bug

[pickers] Invalid character does not delete last digit

---

docs/pages/x/react-data-grid/column-pinning.js
docs/pages/x/react-data-grid/events.js
docs/pages/x/react-data-grid/state.js
docs/pages/x/react-date-pickers/date-range-picker.js

Following a discussion on Slack.
I did not remember that we disabled the add on paid-only pages so my recent migration did not respect it.

[docs] Disable ads on paid-only pages

---

docs/data/date-pickers/getting-started/getting-started-pt.md
docs/data/date-pickers/getting-started/getting-started-zh.md
docs/data/date-pickers/getting-started/getting-started.md
packages/x-date-pickers-pro/README.md
packages/x-date-pickers/README.md

[docs] Complet instructions for pickers installation in readme

---

packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerToolbar.tsx
packages/x-date-pickers/src/DatePicker/DatePickerToolbar.tsx
packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx
packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx
packages/x-date-pickers/src/TimePicker/timePickerToolbarClasses.ts
packages/x-date-pickers/src/internals/components/PickersToolbar.tsx
packages/x-date-pickers/src/internals/index.ts

Part of #4669
@m4theushw I am not very familiar yet with the slots so I may have done things wrong.
For instance, I removed the `penIconClassName` in favor of classes inside `PickersToolbar`.

[pickers] Add class slots for toolbar components

---

docs/data/advanced-components/overview.md
docs/data/date-pickers/migration-lab/migration-lab.md

My initial trigger to work on this PR is that the license we share in https://mui.com/x/advanced-components/#license-key-installation is a working one, proof:
https://master--toolpad.mui.com/_toolpad/app/cl1c2j0l512939zo6a43575en/editor/pages/cl2kfa28r00013f69amqv1prv
Now considering #1364, I think that it makes it too easy to cheat and more importantly will lead to many customers to install **the wrong key**. I think that the change I propose here will make things clear. Note that I have used a key that can be quicky double-clicked selected for replacement:
https://user-images.githubusercontent.com/3165635/168492813-72522ed8-68df-47be-b704-043a0fe45231.mp4
e.g. [not like done here](https://www.ag-grid.com/react-data-grid/licensing/#via-grid-packages-2)…
*This PR is a part of a larger …

[docs] Avoid confusion with license key installation

---

packages/grid/x-data-grid-premium/LICENSE
packages/grid/x-data-grid-pro/LICENSE
packages/x-date-pickers-pro/LICENSE
packages/x-license-pro/LICENSE

We are not respecting the 80 chars per line rule on our commercial license file. This leads to a scrollbar in https://unpkg.com/browse/@mui/x-license-pro@5.11.0/LICENSE, I have to scroll horizontally to read everything. It's annoying.
Compare it to the MIT license: https://unpkg.com/browse/@mui/x-data-grid@5.11.0/LICENSE.
With this fix it feels like this 😌:

[docs] LICENSE max 80 char per line

---

packages/x-date-pickers/src/ClockPicker/ClockPicker.test.tsx
packages/x-date-pickers/src/ClockPicker/ClockPicker.tsx

Fixes #4866
When we migrated the project, there was 0 validation on `ClockPicker` if the current time was null.
In #4726 I applied the value validity check (is hours "5" valid).
And in this PR I apply the full date validity (is 24th of May 2022 at 5PM valid)
- Refacto `ClockPicker.test.tsx` to group the validity tests

[TimePicker] Fix time validation when current date is null

---

packages/grid/x-data-grid/src/hooks/core/pipeProcessing/useGridPipeProcessing.ts

While working on the aggregation (#4208) I noticed that the execution order of the pipe-processors was from the oldest-updated-processor to the latest-updated-processor.
We should try to always have execution orders respect the order of initialization (ie the order of the hooks in `useDataGridXXXComponent`).
This unstable execution order was causing a double execution of `hydrateColumns` in some scenario when used with aggregation and row grouping.
If you change a prop triggering an update of the row grouping processor of `hydrateColumns` (for instance switch `rowGroupingColumnModel` from `single` to `multiple`), then the aggregation processor of `hydrateColumns` will be ran before the row grouping one.
But the aggregation needs the new row grouping columns to decide how to aggregate.
So …

[core] Execute the pipe-processors in their initialization order

---

packages/grid/x-data-grid-premium/README.md
packages/grid/x-data-grid-premium/package.json
packages/grid/x-data-grid-pro/README.md
packages/grid/x-data-grid/README.md
packages/x-date-pickers-pro/README.md
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/README.md
packages/x-date-pickers/package.json

[core] Fix React 18 peer dependency

---

packages/grid/x-data-grid-generator/package.json
packages/grid/x-data-grid-premium/package.json
packages/grid/x-data-grid-pro/package.json
packages/grid/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-license-pro/package.json

In #4763, we forgot to fix **all** the packages. This is not only impacting one package but all of them. I could reproduce the reported issue with Yarn PnP (that doesn't seem to be used a lot) with the data grid.

[core] Fix transitive babel dependency

---

packages/grid/x-data-grid/src/components/base/GridOverlays.tsx
packages/grid/x-data-grid/src/hooks/features/rows/gridRowsState.ts
packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts
packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx

Fixes #4788
Before: https://codesandbox.io/s/data-grid-pro-forked-764v9x?file=/src/App.jsx
After: https://codesandbox.io/s/data-grid-pro-forked-98q8be?file=/src/App.jsx

[DataGrid] Fix rendering of the no rows overlay when the `loading` prop is changed

---

packages/grid/x-data-grid/src/hooks/core/useGridApiInitialization.ts
packages/grid/x-data-grid/src/hooks/features/rows/gridRowsState.ts
packages/grid/x-data-grid/src/hooks/features/rows/gridRowsUtils.ts
packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts
packages/grid/x-data-grid/src/models/api/gridCoreApi.ts

While working on #4927, I noticed that our cache structure had some complex legacy structure that was not useful anymore.

[core] Simplify rows cache management

---

docs/data/data-grid/column-spanning/ColumnSpanningFunction.tsx

Change TypeScript type of `subtotal` from number literal `624` to type `number`.

[docs] Fix TS typo in ColumnSpanningFunction example

---

packages/x-license-pro/src/encoding/base64.test.ts
packages/x-license-pro/src/encoding/base64.ts

We always use ASCII for the license key, so no need for this logic. I think that we could go further in bundle size saving, but I don't have time for it: #4894.

[license] Remove support for UTF-8

---

docs/data/date-pickers/localization/localization.md
packages/x-date-pickers/src/locales/deDE.ts
packages/x-date-pickers/src/locales/index.ts
scripts/x-date-pickers-pro.exports.json
scripts/x-date-pickers.exports.json

Following up on https://github.com/mui/mui-x/issues/3211, I'd like to provide German translations for the Date Picker component.

[l10n] Add deDE translations for x-date-pickers

---

packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx

Low-hanging fruit extracted from https://github.com/mui/mui-x/issues/4955#issuecomment-1134543900
If detail panel content needs more space than provided by `getDetailPanelHeight` - it makes more sense to scroll instead of overflow
Before: https://codesandbox.io/s/basicdetailpanels-material-demo-forked-g8zynr
After: https://codesandbox.io/s/basicdetailpanels-material-demo-forked-pbqh6l

[DataGridPro] Allow to scroll detail panel content if it overflows the panel

---

packages/grid/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx

Currently if `props.rowReorder = true`, when dragging a column over a row, we call `setRowIndex` with `rowId === ''`
This does not cause any bug, but `setRowIndex` is doing an useless lookup over the rows to find the index of the non existing row we are trying to move.

[data grid] Should not call setRowIndex when dragging a column over a row

---

packages/x-date-pickers/src/ClockPicker/ClockPicker.test.tsx
packages/x-date-pickers/src/StaticTimePicker/StaticTimePicker.test.tsx

From https://github.com/mui/mui-x/pull/4645#issuecomment-1132887003
Skip tests on Firefox and Safari because they fail without apparent reason

[test] Skip Safari and Firefox on broken tests

---

.github/ISSUE_TEMPLATE/1.bug.yml
.github/ISSUE_TEMPLATE/2.feature.yml
.github/ISSUE_TEMPLATE/3.pro-support.yml
.github/ISSUE_TEMPLATE/4.premium-support.yml

The problem:
https://github.com/mui/material-ui/pull/32742
I had to edit the issue to avoid confusion:

[core] Avoid Order ID to refer to GitHub issues/PRs

---

packages/grid/x-data-grid/src/models/colDef/gridColDef.ts
packages/grid/x-data-grid/src/tests/columns.spec.tsx

Closes #4660 
This adds generic arguments to the `GridActionsColDef` interface. They match those provided to `GridValidRowModel` and feed into it in the definition as well as in the params given to the `getActions` callback.
The immediate benefit here is that it provides an added layer of type safety to `getActions` and anywhere else in the base `GridColDef` that those arguments are used. It should be fully backwards compatible with all existing uses of this interface since the generics are optional and default to `any`. 
I added a simple test that puts the compiler through some very basic paces and also tests a `getActions` callback that makes use of those arguments. I see there is another test that also checks the `getActions` callback params, so maybe this second portion isn't …

[DataGrid] Add generics to `GridActionsColDef` to match `GridColDef`

---

packages/x-license-pro/src/utils/licenseErrorMessageUtils.ts

I only planned to fix one typo: "use on projects" -> "use in projects", but noticed a few other opportunities.

[license] Tweak error messages

---

docs/next.config.js

I've noticed that feedback widget on MUI X docs website doesn't work:
The reason is missing `FEEDBACK_URL` was missing in MUI X env.
Preview: https://deploy-preview-4905--material-ui-x.netlify.app/x/advanced-components/

[docs] Fix docs feedback widget not working

---

docs/data/date-pickers/localization/localization.md

The package x-date-pickers has been moved one folder up and is not under grid anymore.

[docs] Fix broken links to GitHub source

---

packages/grid/x-data-grid-pro/src/tests/filterPanel.DataGridPro.test.tsx
packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts
packages/grid/x-data-grid/src/hooks/features/filter/useGridFilter.tsx

Fixes #4943
I also added it to the single filtering to handle switch between single and multi filtering (even if it's a very marginal use case)

[data grid] Add an id to the filter item created when opening the filter panel

---

packages/grid/x-data-grid-pro/src/tests/columnsVisibility.DataGridPro.test.tsx
packages/grid/x-data-grid/src/components/panel/GridColumnsPanel.tsx
packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsInterfaces.ts
packages/grid/x-data-grid/src/hooks/features/columns/useGridColumns.tsx
packages/grid/x-data-grid/src/models/gridApiCaches.ts
packages/grid/x-data-grid/src/tests/columnsVisibility.DataGrid.test.tsx

Fixes #5047
@m4theushw it's a temporary fix before v6
The problem was that we were updating `colDef.hide` when clicking on "Hide All", even when using the column visibility model.
So the next time the column was updated (when resizing in #5047), it was re-syncinq the column (which had `hide: true`) and the visibility model.
My solution is to update directly the visibility model instead of calling `updateColumns` when we are using the visibility model.
It requires to expose the `isUsingColumnVisibilityModel` ref or to expose a new private method to have this logic internally in `useGridColumns`.
I think exposing the ref is better.
If you can confirm that the logic seems good to you, I'll add a test after.

[data grid] Use column visibility model on Hide All / Show All when enabled

---

renovate.json

We have some dependencies updates that are blocked by nodejs upgrade (https://github.com/mui/mui-x/pull/4999).
I've put them on hold and there's we don't need them updated until the blocker is resolved.

[core] Stop renovate PR updates when PR is on hold

---

packages/grid/x-data-grid-pro/src/tests/columnHeaders.DataGridPro.test.tsx
packages/grid/x-data-grid/src/hooks/features/columnMenu/useGridColumnMenu.ts

Preview: https://deploy-preview-5027--material-ui-x.netlify.app/x/react-data-grid/demo/
Fixes #1873
This bug happens because, when the column menu is closed, the browser puts focus back to the menu button. However, this button only appears on hover. The problem is that as soon as it receives focus it becomes invisible and the focus is moved to the `<body>`. The solution I used is to focus the column header when I detect that the menu button was focused because the column menu was closed (checking `event.relatedTarget`). Like #1873, we also have problem in the panels (columns and filters). We don't restore the focus to any element, making it difficult to navigate via keyboard. I'll open another issue for them.

[DataGrid] Restore focus after dismissing column menu

---

packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerViewDesktop.tsx
packages/x-date-pickers-pro/src/DesktopDateRangePicker/DesktopDateRangePicker.test.tsx

Fixes #5080 
I think the code is self-explanatory
My bad on that one...
We have almost no test for the disabled state (and none at all on `DateRangePicker`).
I added a few tests but we will have to add a lot more later.

[DateRangePicker] Fix usage of `maxDate` / `minDate` / `disableFuture` and `disablePast`

---

packages/grid/x-data-grid-pro/src/components/GridRowReorderCell.tsx

[data grid] Support `getRowId` in row reordering

---

packages/grid/x-data-grid-generator/src/renderer/renderEmail.tsx
packages/grid/x-data-grid-generator/src/renderer/renderLink.tsx

Fix #1465 by putting the focus on links (emails and website)

[docs] Data grid demo implement the focus management on links

---

packages/x-date-pickers/src/locales/index.ts
packages/x-date-pickers/src/locales/ptBR.ts
scripts/x-date-pickers-pro.exports.json
scripts/x-date-pickers.exports.json

More than 210 million people speak Brazilian Portuguese.
More than 70 million people speak European Portuguese.
Supporting pt-BR 'Out of the box' will be nice.
Closes #5099

[l10n] Add Brazilian Portuguese (pt-BR) locale for date pickers

---

docs/data/data-grid/accessibility/accessibility.md

https://mui.com/x/react-data-grid/accessibility/#tab-sequence

[docs] Fix 301 link to render cell

---

docs/data/data-grid/filtering/filtering.md
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
docs/pages/x/api/data-grid/selectors.json
docs/translations/api-docs/data-grid/data-grid-pro-pt.json
docs/translations/api-docs/data-grid/data-grid-pro-zh.json
docs/translations/api-docs/data-grid/data-grid-pro.json
docs/translations/api-docs/data-grid/data-grid-pt.json
docs/translations/api-docs/data-grid/data-grid-zh.json
docs/translations/api-docs/data-grid/data-grid.json
packages/grid/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx
packages/grid/x-data-grid/src/constants/defaultGridSlotsComponents.ts
packages/grid/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts
packages/grid/x-data-grid/src/models/gridIconSlotsComponent.ts
packages/grid/x-data-grid/src/tests/quickFiltering.DataGrid.test.tsx
scripts/x-data-grid-premium.exports.json
scripts/x-data-grid-pro.exports.json
scripts/x-data-grid.exports.json

Fix #4921
I assume the quick filter value is rarely modified from somewhere else. It can be reset by clicking a button, or when putting back a saved state.
From this, I propose to add a prop to the input named `quickFilterFormatter`. This prop is used only if the quick filter state is updated and does not correspond anymore to the input content. In such a case, we use this `quickFilterFormatter` to update the input content.

[DataGrid] Update quick filter input when model is modified

---

packages/grid/x-data-grid/src/locales/jaJP.ts

Adds missing translations for Japanese (ja-JP) locale - https://github.com/mui/mui-x/issues/3211.

[l10n] Improve Japanese (ja-JP) locale

---

docs/data/data-grid/filtering/filtering.md
docs/data/data-grid/rows/rows.md
test/e2e-website/data-grid.spec.ts
yarn.lock

Try https://github.com/mui/material-ui/pull/32939 out. 
An example of a problem this solves: search for "column definition" in Algolia: you will get a duplicate result:
one with the leading slash, the other without, proof: https://www.algolia.com/apps/TZGZ85B9TB/explorer/browse/material-ui?query=column%20definition&searchMode=search 🙃.

[core] Upgrade monorepo

---

packages/grid/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorderPreProcessors.ts

A small fix related to the type of the `apiRef` in the `useGridRowReorderPreProcessors`.

[core] Set correct `apiRef` type in row reorder pre processors

---

benchmark/browser/index.js
packages/grid/x-data-grid-premium/package.json
packages/grid/x-data-grid-pro/package.json
packages/grid/x-data-grid/package.json
test/e2e/index.js
test/performance/index.js
test/regressions/index.js

I was on https://github.com/mui/material-ui/pull/33015#issuecomment-1146631891, having a quick look at what could explain the jump in bundle size in the data grid at version v5.9.0. We went [from 78.1 to 122.1 KB](https://bundlephobia.com/package/@mui/x-data-grid@5.12.0). Compared to react-table [15.7 KB](https://bundlephobia.com/package/react-table@7.8.0) it can be intimidating. I could identify the origin down to #4332, we depend on `react-dom`:
https://github.com/mui/mui-x/blob/23aaa6bad1a0398ebc7677337d1d46226c2b70f6/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx#L2
but we don't list the dependency.

[data grid] Fix implicit dependency on react-dom

---

packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerView.tsx
packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerViewMobile.tsx

[date picker] Fix `shouldDisableDate` in range pickers

---

packages/x-date-pickers-pro/tsconfig.json
packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePickerKeyboard.test.tsx
packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.test.tsx
packages/x-date-pickers/src/MobileDateTimePicker/MobileDateTimePicker.test.tsx
packages/x-date-pickers/src/internals/utils/text-field-helper.test.ts
test/utils/pickers-utils.tsx

Allows to test bugs such as #4890 locally for now
to run unit test with a specific adapter, use `yarn test:unit  --date-adapter moment` (or `luxon`, `day-js`, `date-fns`)

[core] Allows to run tests with different date adapters

---

docs/data/date-pickers/date-picker/LocalizedDatePicker.js
docs/data/date-pickers/date-picker/LocalizedDatePicker.tsx
packages/x-date-pickers-pro/src/DateRangePicker/shared.ts
packages/x-date-pickers-pro/tsconfig.json
packages/x-date-pickers/src/DatePicker/shared.ts
packages/x-date-pickers/src/DateTimePicker/shared.ts
packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePickerKeyboard.test.tsx
packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.test.tsx
packages/x-date-pickers/src/MobileDateTimePicker/MobileDateTimePicker.test.tsx
packages/x-date-pickers/src/TimePicker/shared.ts
packages/x-date-pickers/src/internals/hooks/useMaskedInput.tsx
packages/x-date-pickers/src/internals/utils/text-field-helper.test.ts
packages/x-date-pickers/src/internals/utils/text-field-helper.ts
test/utils/pickers-utils.tsx

Fix #4890 
Fix #4756
The idea is that is mask is not defined, we try to infer it from the `inputFormat` this allows to support at the same time libraries that use uppercase letters for `ampm` and library using lowercase
To run test, I based this PR on #5055
The mask can now be inferred from the `inputFormat`.
This allows supporting different separators like `dd/MM/YYYY`, `dd-MM-YYYY`, `dd.MM.YYYY` and different orders such as `MM-dd-YYYY`, `YYYY-MM-dd` without having to specify the `mask` prop
To be accepted, the input format needs to b made of digits (months  can not be `Jan`, `Fev`, ...) and with fix length (January must be `01` and not `1`).
You can still use `disableMaskedInput` to disable this feature and provide `mask` prop to override the inferred mask.

[pickers] Infer mask from `inputFormat`

---

packages/grid/x-data-grid-generator/src/hooks/useQuery.ts

Fix comment https://github.com/mui/mui-x/pull/4186#discussion_r889694136
I copied the logic from the value generator, but I don't know how to verify it solved the flaky test

[tests] Remove delay on server demo for regression tests 

---

packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts

Fixes #4417
Codesandbox: https://codesandbox.io/s/columnsizinggrid-material-demo-forked-v4buex

[DataGridPro] Fix column resizing on touchscreen

---

packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx

Preview: https://deploy-preview-5164--material-ui-x.netlify.app/x/react-data-grid/layout/#auto-height
The scrollbar is appearing for a brief moment when a new row is added in https://mui.com/x/react-data-grid/layout/. This demo uses `autoHeight`, meaning that it should never have scrollbar so we're safe to apply `overflow-y: hidden`. I noticed this problem in https://deploy-preview-5163--material-ui-x.netlify.app/x/react-data-grid/master-detail/#infer-height-from-the-content
https://user-images.githubusercontent.com/42154031/172937562-c5b8da89-1ee6-4a1d-be93-72fe0162b558.mp4

[DataGrid] Hide vertical scrollbar if `autoHeight` is enabled

---

docs/data/data-grid/column-definition/CustomColumnTypesGrid.js
docs/data/data-grid/column-definition/CustomColumnTypesGrid.tsx
packages/grid/x-data-grid-generator/src/hooks/useMovieData.ts

My locale is configured to be en-US, which is the locale [we use](https://www.notion.so/mui-org/Technical-writing-7e55b517ac2e489a9ddb6d0f6dd765de#9494c1a7521146c2ab571969b21955ce) to write the documentation. In this context, when opening https://mui.com/x/react-data-grid/row-grouping/, you will see:
which I think is wrong:
```jsx
new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(2847246203);
// = $2,847,246,203
```
https://deploy-preview-5034--material-ui-x.netlify.app/x/react-data-grid/row-grouping/

[docs] Fix demo currency format

---

docs/data/data-grid/getting-started/migration-v4.md
docs/data/date-pickers/migration-lab/migration-lab.md

I have found this from https://app.ahrefs.com/site-audit/3523498/13/data-explorer?columns=pageRating%2Curl%2Ctraffic%2Ctitle%2Cserp_title%2Cis_page_title_used_in_serp%2Ctop_keyword%2Ctop_keyword_position&filterCollapsed=true&filterId=207cf10d892e807e0aaeafdf8fc70712&issueId=d69246c2-225a-11ec-8456-06d2f2f613d8
I don't see the logic with heaving MUI X to prefix.

[docs] Fix redundant headers

---

docs/data/data-grid/layout/AutoHeightGrid.js
docs/data/data-grid/layout/AutoHeightGrid.tsx
docs/data/data-grid/layout/AutoHeightGrid.tsx.preview
docs/data/data-grid/layout/layout.md
docs/public/_redirects
packages/grid/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts
packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx

One iteration on https://twitter.com/r12esh/status/1532579218491572226.
- I'm using error instead of warning because it's a critical problem. Related to https://github.com/mui/material-ui/issues/21979
- We should avoid hard links in the code to the docs as much as possible, these links tend to get broken as we improve the docs. See https://github.com/mui/material-ui/pull/16077

[docs] Use redirection in the code

---

docs/data/data-grid/editing/EditingWithDatePickers.js
docs/data/data-grid/editing/EditingWithDatePickers.tsx
docs/data/data-grid/editing/EditingWithDatePickers.tsx.preview
docs/data/data-grid/editing/editing.md

Closes https://github.com/mui/mui-x/issues/4909 until we provide out of the box support for pickers in data grid
Preview: https://deploy-preview-5053--material-ui-x.netlify.app/x/react-data-grid/editing/#usage-with-mui-x-date-pickers

[docs] Using data grid with date pickers

---

packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts

Fixes #5159 
Fix filter badge being cut off when the table's density is set to compact mode.

[DataGrid] Fix for cosmetic bug on column filter badge

---

docs/data/advanced-components/overview.md

* Add warning in the license documentation to instruct about the issue with v2-v1 licenses
https://deploy-preview-5074--material-ui-x.netlify.app/x/advanced-components/#license-key-installation

[docs] Instruction to deal with v2 invalid license message

---

docs/data/advanced-components/overview.md

Updates the License expired section to:
- Explain the behavior of the license in **production**.
- Explain the behavior of the license in **development**.

[docs] Fix outdated license description to match the EULA

---

packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx
packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts

Fixes #5208
[Before before](https://codesandbox.io/s/data-grid-pro-forked-946vlv?file=/package.json)
[Behavior after](https://codesandbox.io/s/data-grid-pro-forked-qr8wpk?file=/package.json)
The username should go from `fault` to `okay` and remain `okay` after the end of the loading.
Since https://github.com/mui/mui-x/pull/4910, we were regenerating the whole row tree whenever `props.loading` changed.
This leads to two issues:
- performance-wise, it's an useless regeneration,what we want to do is just to update the `state.rows.loading` if `props.loading` changed but not `props.rows`
- if you do partial updates with `apiRef.current.updateRows` then changes `props.loading`, then you loose your partial updates

[data grid] Do not regenerate the row tree when props.loading changes

---

docs/data/date-pickers/date-range-picker/BasicDateRangePicker.js
docs/data/date-pickers/date-range-picker/BasicDateRangePicker.tsx
docs/data/date-pickers/date-range-picker/CalendarsDateRangePicker.js
docs/data/date-pickers/date-range-picker/CalendarsDateRangePicker.tsx
docs/data/date-pickers/date-range-picker/CustomDateRangePickerDay.js
docs/data/date-pickers/date-range-picker/CustomDateRangePickerDay.tsx
docs/data/date-pickers/date-range-picker/FormPropsDateRangePickers.js
docs/data/date-pickers/date-range-picker/FormPropsDateRangePickers.tsx
docs/data/date-pickers/date-range-picker/MinMaxDateRangePicker.js
docs/data/date-pickers/date-range-picker/MinMaxDateRangePicker.tsx
docs/data/date-pickers/date-range-picker/ResponsiveDateRangePicker.js
docs/data/date-pickers/date-range-picker/ResponsiveDateRangePicker.tsx
docs/data/date-pickers/date-range-picker/StaticDateRangePickerDemo.js
docs/data/date-pickers/date-range-picker/StaticDateRangePickerDemo.tsx
packages/x-date-pickers-pro/src/AdapterDateFns/index.ts
packages/x-date-pickers-pro/src/AdapterDayjs/index.ts
packages/x-date-pickers-pro/src/AdapterLuxon/index.ts
packages/x-date-pickers-pro/src/AdapterMoment/index.ts

Fixes #5132
My comment on the issue above
> The basic idea was: we don't want to create dozens of folders inside the pro package just re-exporting the community components just to be able to do `import { DatePicker } from '@mui/x-date-pickers-pro/DatePicker'`. Users could do `import { DatePicker } from '@mui/x-date-pickers-pro'` or if they really want dev tree shaking `import { DatePicker } from '@mui/x-date-pickers/DatePicker'`.
>
> But the adapters (I think they are the only one), we don't export them from the root of `@mui/x-date-pickers` and thus they are not re-exported from the root of `@mui/x-date-pickers-pro`.

[pickers] Export adapters from both `@mui/x-date-pickers` and `@mui/x-date-pickers-pro`

---

packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts
packages/grid/x-data-grid/src/tests/filtering.DataGrid.test.tsx

[data grid] Fix the default filter operator fallback on state initialization

---

packages/grid/x-data-grid-premium/src/DataGridPremium/useDataGridPremiumComponent.tsx

Fixes #5262
In #5110 the plugin order was only changed for the pro plan

[data grid] Fix detail panel on DataGridPremium

---

docs/data/date-pickers/getting-started/getting-started.md

Inspired by https://mui.com/material-ui/about-the-lab/#main-content
Part of #5236 (maybe fixes)

[docs] Add section for theme augmentation in the picker doc

---

.circleci/config.yml
packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx

The tests for dynamic row height kept failing after merging #5203. The problem is the same from #5095: all pass in headless mode but some fail in the non-headless Chrome. In this PR I take another approach by replacing `ResizeObserver` for a mocked version. It seem to have worked in https://app.circleci.com/pipelines/github/mui/mui-x/19851/workflows/d4541c25-0fd8-489c-bf0a-acaaf01e2e25/jobs/115292

[test] Use mock for ResizeObserver

---

.gitignore

I most of the time have multiple playground examples:
- One for the feature under development
- On for doing debugging (or answer example) on locale
Ignoring a full folder should simplify switching between PR by keeping examples at different URLs. For example 
- http://localhost:3001/playground/columnGrouping
- http://localhost:3001/playground/datePickerFix

[DX] Allows having multiple playgrounds

---

docs/next.config.js

Redirects only take effect in the development, not production (because of `next export`). I would argue it was never needed in the first place for the migration, and since it's done, not anymore.
I have found this doing a quick review on something unrelated.

[core] Remove dead logic

---

test/utils/pickers-utils.tsx

Follow up on #5055
Before:
```
$ yarn test:unit --date-adapter moments
yarn run v1.22.17
$ cross-env NODE_ENV=test node --expose_gc ./node_modules/.bin/mocha 'packages/**/*.test.{js,ts,tsx}' --exclude '**/node_modules/**' --timeout 3000 --date-adapter moments
including inaccessible elements by default
1335 passing (1m)
195 pending
```
`moments` adapter was not found, so `date-fns` was used by default. There's no indication of adapter used in tests and if you didn't notice the typo ("moment**s**") it looks like tests passed with `moment` adapter
After:
```
$ yarn test:unit --date-adapter moments
yarn run v1.22.17
$ cross-env NODE_ENV=test node --expose_gc ./node_modules/.bin/mocha 'packages/**/*.test.{js,ts,tsx}' --exclude '**/node_modules/**' --timeout 3000 --date-adapter moments …
```

[test] Throw if date adapter is not found

---

packages/grid/x-data-grid/src/locales/skSK.ts

Adds missing translations for Slovak language (sk-SK) locale - https://github.com/mui/mui-x/issues/3211.

[DataGrid][l10n] Improve Slovak (sk-SK) locale

---

docs/data/data-grid/filtering/filtering.md
docs/data/data-grid/pagination/pagination.md
docs/data/data-grid/sorting/sorting.md
packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx
packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts
packages/grid/x-data-grid/src/hooks/utils/useGridApiContext.ts
packages/grid/x-data-grid/src/hooks/utils/useGridRootProps.ts
packages/grid/x-data-grid/src/tests/components.DataGrid.test.tsx

In https://github.com/mui/mui-x/issues/5317#issue-1284430266 I've noticed that `DataGridPremium` is not mentioned in the error message, so I've updated error messages.
I've also noticed that Premium plan is not mentioned on some docs pages, so I've added it there as well.

[DataGrid] Mention Premium plan in error messages and docs warnings

---

docs/data/data-grid/pagination/ServerPaginationGrid.js
docs/data/data-grid/pagination/ServerPaginationGrid.tsx

I've noticed that in our server-side pagination example after changing page the data do not change: https://mui.com/x/react-data-grid/pagination/#basic-implementation
Turned out that cursor pagination was turned on by default and needed to be disabled for this demo.
Preview: https://deploy-preview-5361--material-ui-x.netlify.app/x/react-data-grid/pagination/#server-side-pagination

[docs] Fix server-side pagination demo

---

packages/grid/x-data-grid/src/hooks/features/rows/useGridRowsPreProcessors.tsx

Will be fixed by #4927 in a clean way
The problem is that when the flat tree creator receives a tree from row grouping or tree data it just keeps its nodes, so the depth is wrong.
FIxes #5363

[DataGridPro] Fix the depth of nodes when switching from a non-flat tree to a flat tree

---

packages/x-date-pickers/package.json

The TypeScript declaration files for `@mui/x-date-pickers` import from `@types/react-transition-group` and `@date-io/core`, so those packages should be added as a dependency of `@mui/x-date-pickers`.
```
TS7016: Could not find a declaration file for module 'react-transition-group/CSSTransition'.
1 | import * as React from 'react';
> 2 | import { CSSTransitionProps } from 'react-transition-group/CSSTransition';
|                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3 | export declare type SlideDirection = 'right' | 'left';
4 | export interface SlideTransitionProps extends Omit<CSSTransitionProps, 'timeout'> {
5 |     children: React.ReactElement;
TS2307: Cannot find module '@date-io/core/IUtils' or its corresponding type declarations.
> 1 | import { IUtils } from …
```

[pickers] Add missing type dependencies

---

packages/grid/x-data-grid/src/utils/keyboardUtils.ts

Fixes https://github.com/mui/mui-x/issues/4687
I also need this for fixing the build in https://github.com/mui/material-ui/pull/33196

[DataGrid] Fix broken "start editing" integration with Japanese

---

packages/grid/x-data-grid-pro/src/tests/cellEditing.DataGridPro.new.test.tsx
packages/grid/x-data-grid-pro/src/tests/rowEditing.DataGridPro.new.test.tsx
packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts
packages/grid/x-data-grid/src/hooks/features/editRows/useGridRowEditing.new.ts

Fix #5228
The editing can now be start with 
- <kbd>Shift</kbd> + a letter
- <kbd>Ctrl</kbd> + V

[DataGrid] Start editing with uppercase letter and Ctrl+V

---

docs/tsconfig.json

When using data grid in playground pages TS is complaining about some imports.
Before:
After:

[core] Include playground pages in tsconfig

---

docs/data/introduction/licensing/licensing.md

The issues I'm trying to solve:
1. **A license is not a license key. Instead, we can distinguish an order and a license key.**
2. "or later" can be confused with "or older", I think that it depends on how you consider the direction of time. Instead, we can focus on the version number, not when it was released.
3. Saying "only compatible" is not accurate. It the default behavior, but we can work around it. Instead, we can say it's the default behavior.
https://mui.com/x/advanced-components/#license-key-installation

[docs] Make a clear difference between the license and license key

---

packages/x-date-pickers/src/locales/frFR.ts

Adds missing translations for the French language (fr-FR) locale - #3211

[DatePickers] Improve French (fr-FR) locale

---

docs/data/data-grid/sorting/sorting.md

Fix typo in docs to reflect the correct function name:
https://github.com/mui/mui-x/blob/47bb0c8c0f2e0880aabbe1399442d826fe55ba06/packages/grid/x-data-grid/src/hooks/features/sorting/gridSortingUtils.ts#L170

[docs] FIx typo in the sorting page

---

packages/x-date-pickers-pro/README.md
packages/x-date-pickers/README.md

Closes https://github.com/mui/mui-x/issues/5408 (addresses https://github.com/mui/mui-x/issues/5408#issuecomment-1177306198 specifically)

[docs] Update pickers readme files

---

packages/grid/x-data-grid/src/locales/ptBR.ts

Adds missing translations for Portuguese language (pt-BR) locale - https://github.com/mui/mui-x/issues/3211.

[l10n] Improve Brazilian Portuguese (pt-BR) locale

---

docs/data/data-grid/style/style.md

This PR fixes a mistake introduced in #3882
The description for the "Custom theme" example contains text that is meant for the "Striped rows" example:
While the "Striped rows" example description has a typo ("stripped" instead of "striped"):
The mistake happened in [this commit](https://github.com/mui/mui-x/commit/4f2c9a5a4a88fba0ae6091efcbcdf1c556d9ec3b#diff-cdc05bc9f3c8c0f4cff91c069e3f8959221bf1cf18082e28e8990762735adab4).
- Re-applied the previous (pre-#3882) description for the "Custom theme" example.
- Moved the current "Custom theme" description to "Striped rows".

[docs] Fix description for "Striped rows" example

---

docs/data/date-pickers/localization/localization.md
packages/x-date-pickers/src/locales/esES.ts
packages/x-date-pickers/src/locales/index.ts
scripts/x-date-pickers-pro.exports.json
scripts/x-date-pickers.exports.json

Following up on https://github.com/mui/mui-x/issues/3211, I'd like to provide Spanish translations for the Date Picker component.

[pickers] Add Spanish (es-ES) locale

---

package.json
packages/grid/x-data-grid-pro/src/components/DataGridProColumnHeaders.tsx
packages/grid/x-data-grid-pro/src/tests/accessibility.DataGridPro.test.tsx
yarn.lock

Fixes #5364
I've added `axe-core` to our dependencies and created the first test with a check for one specific accessibility rule.
We can add more rules in the future.

[DataGridPro] Improve pinned column headers accessibility

---

docs/public/_redirects

The link will be initially used on the store's keymailer.
More on: https://github.com/mui/mui-store/pull/187

[core] Add technical support link to _redirects

---

docs/data/date-pickers/localization/localization.md
packages/x-date-pickers/src/locales/index.ts
packages/x-date-pickers/src/locales/itIT.ts
scripts/x-date-pickers-pro.exports.json
scripts/x-date-pickers.exports.json

Following up on https://github.com/mui/mui-x/issues/3211, I'd like to provide Italian translations for the Date Picker component.

[pickers] Add Italian (it-IT) locale

---

docs/data/introduction/overview/overview.md
docs/data/introduction/support/support.md

It's not clear to users that "Professional support" doesn't include MUI Core.
We're seeing MUI X customers expecting to get professional support extended to MUI Core.
Examples:
- https://mui.zendesk.com/agent/tickets/4072
- https://mui.zendesk.com/agent/tickets/3766
https://deploy-preview-5423--material-ui-x.netlify.app/x/introduction/support/#technical-support

[docs] Clarify the scope of support for MUI X

---

packages/grid/x-data-grid-premium/src/components/GridExcelExportMenuItem.tsx
packages/grid/x-data-grid/src/components/toolbar/GridToolbarExport.tsx

Preview: https://deploy-preview-5486--material-ui-x.netlify.app/x/react-data-grid/demo/
Fixes #5476
On 7/12/22 I reported an accessibility issue related to the Export menu in DataGrid Toolbar ([#5476](https://github.com/mui/mui-x/issues/5476)). As a response from the MUI team, I was suggested to forward remaining props to the root element of MenuList to make the Toolbar Export Menu accessible for keyboard users.

[DataGrid] Improve accessibility of Export menu in the toolbar

---

.github/ISSUE_TEMPLATE/1.bug.yml
.github/workflows/support-stackoverflow.yml
CHANGELOG.md
README.md
docs/public/_redirects

A quick follow-up on #5067, tackling the points raised.

[core] Polish on the bug issue template

---

docs/data/data-grid/editing/EditingWithDatePickers.js
docs/data/data-grid/editing/EditingWithDatePickers.tsx
packages/grid/x-data-grid/src/components/cell/GridEditDateCell.tsx

Fixes: https://github.com/mui/mui-x/pull/5053#issuecomment-1160448614
Preview: https://deploy-preview-5304--material-ui-x.netlify.app/x/react-data-grid/editing/
Before: 
After:

[DataGrid] Fix `date`/`dateTime` edit input font size to match view mode

---

docs/data/data-grid/localization/localization.md
packages/grid/x-data-grid/src/locales/index.ts
packages/grid/x-data-grid/src/locales/zhTW.ts
scripts/x-data-grid-premium.exports.json
scripts/x-data-grid-pro.exports.json
scripts/x-data-grid.exports.json

Add Traditional Chinese locale to data grid.
> In this PR, I translate "rows/columns" as "個/欄" to avoid the indefinite translation that could be "列/行" or "行/列" in a different context [1][2].
> [1] [Translations in Localized Microsoft Products](https://www.microsoft.com/en-us/language/Search?&searchTerm=columns&langID=129&Source=true&productid=0)
> [2] [The determinant in linear algebra](https://ccjou.wordpress.com/2012/04/17/)

[l10n] Add Traditional Chinese (zh-TW) locale

---

packages/grid/x-data-grid/src/locales/zhTW.ts

I merged #5498 without rebasing on master so it missed some untranslated comments.
Will auto-merge

[core] Add missing comments on zh-TW translation

---

packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx

Fixes #5085 
Related to #5192
I saw this bug when working in #4155 and one of the tests was failing with React 18 but passing with React 17. By debugging, I noticed that `rootRef.current` was null when the `resize` event is fired. I suppose this is happening because the event is triggered while the ref is unmounted. With React 17, the event is fired after the ref is mounted.
Before: https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-hw2hd1?file=/demo.tsx
After: https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-s2p48r?file=/package.json
How to reproduce:

[DataGrid] Fix container width change on React 18

---

docs/data/data-grid/column-definition/column-definition.md

[docs] Fix internal link to `valueParser`

---

packages/grid/x-data-grid/src/constants/localeTextConstants.ts
packages/grid/x-data-grid/src/locales/arSD.ts
packages/grid/x-data-grid/src/locales/bgBG.ts
packages/grid/x-data-grid/src/locales/csCZ.ts
packages/grid/x-data-grid/src/locales/daDK.ts
packages/grid/x-data-grid/src/locales/deDE.ts
packages/grid/x-data-grid/src/locales/elGR.ts
packages/grid/x-data-grid/src/locales/esES.ts
packages/grid/x-data-grid/src/locales/faIR.ts
packages/grid/x-data-grid/src/locales/fiFI.ts
packages/grid/x-data-grid/src/locales/frFR.ts
packages/grid/x-data-grid/src/locales/heIL.ts
packages/grid/x-data-grid/src/locales/huHU.ts
packages/grid/x-data-grid/src/locales/itIT.ts
packages/grid/x-data-grid/src/locales/jaJP.ts
packages/grid/x-data-grid/src/locales/koKR.ts
packages/grid/x-data-grid/src/locales/nbNO.ts
packages/grid/x-data-grid/src/locales/nlNL.ts
packages/grid/x-data-grid/src/locales/plPL.ts
packages/grid/x-data-grid/src/locales/ptBR.ts
packages/grid/x-data-grid/src/locales/roRO.ts
packages/grid/x-data-grid/src/locales/ruRU.ts
packages/grid/x-data-grid/src/locales/skSK.ts
packages/grid/x-data-grid/src/locales/svSE.ts
packages/grid/x-data-grid/src/locales/trTR.ts
packages/grid/x-data-grid/src/locales/ukUA.ts
packages/grid/x-data-grid/src/locales/viVN.ts
packages/grid/x-data-grid/src/locales/zhCN.ts
packages/grid/x-data-grid/src/locales/zhTW.ts

Apply https://mui-org.notion.site/Style-guide-2a957a4168a54d47b14bae026d06a24b#a08d92bbbb8249ff8b95431514ab9903.
I have noticed it while having a quick look at #5584. It's also what GitHub uses:

[data grid] Fix ellipsis style convention

---

docs/data/data-grid/row-grouping/row-grouping.md

I struggled to understand a warning in [row grouping documentation](https://mui.com/x/react-data-grid/row-grouping/#hide-the-grouped-columns) about `useKeepGroupedColumnsHidden`
> This hook is only compatible with the deprecated column property `hide` or with the controlled `columnVisibilityModel` prop.
>
> You must use the `columnVisibilityModel` in the `initialState` instead.
Not sure my correction is exactly what the hook does

[docs] Add warning clarifications

---

docs/data/data-grid/getting-started/getting-started.md
docs/data/introduction/licensing/licensing.md
docs/public/_redirects

A continuation of https://github.com/mui/mui-store/pull/196. We can merge and deploy this one independently from the previous linked PR and https://github.com/mui/material-ui/pull/33650 as there is already a redirection in place. I think that this /store/ in the URL to link legal content for MUI X was confusing. The store is an implementation detail of how we allow customers to procure the software.

[docs] New location for the legal content

---

docs/next.config.js
docs/public/_redirects

Same as https://github.com/mui/mui-toolpad/pull/661. It will be cleaner going forward, help us scale the shared folder structure of https://mui.com/.
https://github.com/mui/material-ui/pull/33649 needs to be deployed before this PR can be merged, we would break the documentation in production otherwise.
https://deploy-preview-5594--material-ui-x.netlify.app/x/introduction/

[core] Isolate asset loading under /x/

---

packages/grid/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx

[DataGrid] Add `initialOpen` prop to `GridEditSingleSelectCell` to allow overriding default behavior on cell edit mode

---

.circleci/config.yml
.codesandbox/ci.json
netlify.toml
packages/grid/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx
packages/grid/x-data-grid/src/hooks/utils/useGridApiEventHandler.test.tsx

[Node 12 support ended on April 30th](https://nodejs.org/en/blog/release/v12.22.12/)
Node 14 is currently Maintenance LTS, Node 16 - Active LTS (see https://nodejs.org/en/about/releases/)
I didn't update [`engines` entry in our packages](https://github.com/mui/mui-x/blob/814b72284d01b9653995b3e05539d88f8ee7cf81/packages/grid/x-data-grid/package.json#L64), because:
- I'm not sure if it should be considered as breaking change
- technically nothing changes in our packages - we'll just use node v14 in CI and deployment environments

[core] Upgrade node to v14

---

docs/next.config.js
packages/grid/x-data-grid/src/constants/envConstants.ts
packages/storybook/.storybook/main.ts

Fixes #5673
When using cypress with `vite`, envConstants.ts fails cause it assumes `process.env` is defined, where it might be undefined.

[core] Drop usage of `GRID_EXPERIMENTAL_ENABLED` env variable

---

docs/data/data-grid/accessibility/accessibility.md
packages/grid/x-data-grid-pro/src/tests/cellEditing.DataGridPro.new.test.tsx
packages/grid/x-data-grid-pro/src/tests/cellEditing.DataGridPro.old.test.tsx
packages/grid/x-data-grid-pro/src/tests/rowEditing.DataGridPro.new.test.tsx
packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts
packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.old.ts
packages/grid/x-data-grid/src/hooks/features/editRows/useGridRowEditing.new.ts
packages/grid/x-data-grid/src/utils/keyboardUtils.ts

https://deploy-preview-5511--material-ui-x.netlify.app/x/react-data-grid/editing/
This is a quick follow-up on #5405. I'm going after a couple of problems, all focused on the new edit API, I have ignored the legacy one, no time for the past.
1. <kbd>⌥ Option</kbd> + `P` should trigger the edit mode in macOS, it prints: `π` in the cell.
2. <kbd>Backspace</kbd> should empty the cell in macOS, it's the equivalent of `Delete` for Windows https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#editing_keys
3. "alt" is an abbreviation, not an acronym https://en.wikipedia.org/wiki/Alt_key, so did the same change as in #4707
While I was working on it, I found the potential for a follow-up: #5512.

[data grid] Improve start edit UX

---

docs/pages/_app.js

I've noticed that demos in Codesandbox from https://mui.com/x/react-date-pickers/date-range-picker/ are missing `date-fns` dependency.
For `@mui/x-date-pickers` it was added in https://github.com/mui/mui-x/pull/4508
I've reordered if statements and removed duplicated dependencies across them, so that:
- if demo has `@mui/x-date-pickers-pro` dependency - add `@mui/x-date-pickers` dependency
- if demo has `@mui/x-date-pickers` dependency - add `date-fns` and `@mui/material` dependencies
By entering multiple ifs all necessary dependencies will be gathered.
Same for the data grid packages.
Preview: https://deploy-preview-5692--material-ui-x.netlify.app/x/react-date-pickers/date-range-picker/

[docs] Add missing `date-fns` dependency when opening Codesandbox demo

---

.circleci/config.yml
packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx

Some tests are failing on Edge after the merge of #4155

[test] Fix failing dynamic row height tests on Edge

---

docs/pages/x/api/data-grid/grid-export-state-params.md
packages/grid/x-data-grid/src/hooks/features/statePersistence/gridStatePersistenceInterface.ts

See https://github.com/mui/material-ui/pull/33698. This PR is so that we can update the mono repository without the build failing.

[docs] Add description to the GridExportStateParams page

---

docs/next.config.js

Same as https://github.com/mui/material-ui/pull/33845, the warnings were introduced in #5577.

[core] Remove outdated Next.js options

---

.github/ISSUE_TEMPLATE/5.rfc.yml

Added an RFC template to GH issues
This is how it looks like: https://github.com/mui/mui-toolpad/issues/new?assignees=&labels=RFC&template=3.rfc.yml&title=%5BRFC%5D+

[docs] Add RFC GH issue template

---

docs/data/data-grid/demo/FullFeaturedDemo.js
docs/data/data-grid/demo/FullFeaturedDemo.tsx
docs/data/data-grid/editing/editing.md
docs/data/data-grid/overview/DataGridDemo.js
docs/data/data-grid/overview/DataGridDemo.tsx
docs/data/data-grid/overview/DataGridDemo.tsx.preview
docs/data/data-grid/overview/DataGridPremiumDemo.js
docs/data/data-grid/overview/DataGridPremiumDemo.tsx
docs/data/data-grid/overview/DataGridPremiumDemo.tsx.preview
docs/data/data-grid/overview/DataGridProDemo.js
docs/data/data-grid/overview/DataGridProDemo.tsx
docs/data/data-grid/overview/DataGridProDemo.tsx.preview
packages/grid/x-data-grid-generator/src/renderer/renderEditStatus.tsx

Considering how much we are burying the demo of the legacy editing API, and that the legacy API is buggy, e.g. with the <kbd>Escape</kbd> key:
https://user-images.githubusercontent.com/3165635/183312070-6a7daf69-1e53-40ac-b0b3-22bfa5808033.mov
https://mui.com/x/react-data-grid/#mit-version
I believe it would make more sense to demo it on the introduction demos. I believe these demos are used by developers to judge whether they will use or not the component.
One step in this direction #5606.
Preview: https://deploy-preview-5728--material-ui-x.netlify.app/x/introduction/

[docs] Use new edit API in the introduction demos

---

packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.test.tsx
packages/x-date-pickers/src/internals/hooks/usePickerState.ts

Fixes #5690 
Force trigger an `onChange` call when clicking `clear` button with not empty `value`.
Covers case, when date picker has `Invalid date` due to manual entry, but internally the state is saved as `null` already.
Simply adding a check in `setDate` function causes inconsistent behaviour, where simply closing the picker would also reset an invalid value.

[pickers] fix to trigger `onChange` when clearing not empty value

---

packages/x-date-pickers/src/ClockPicker/Clock.tsx

Fixes #5694 
Safari sometimes (like toggling element inspector with keyboard shortcut) shows focus outline on time picker clock numbers.
Explicitly specifying
```css
:focus: {
outline: 'none';
}
```
on clock root element (listbox) avoids this unwanted behaviour.
See the attached video with comparison example.
https://user-images.githubusercontent.com/4941090/184104388-0621ef53-3bd8-460a-a30c-90752c31fb8e.mov

[time picker] set clock focus outline to `none`

---

packages/grid/x-data-grid-pro/src/tests/editComponents.DataGridPro.new.test.tsx
packages/grid/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx

Before: https://codesandbox.io/s/data-grid-community-forked-377psb?file=/src/App.tsx
After: https://codesandbox.io/s/data-grid-community-forked-j4g4y9?file=/src/App.tsx
Fixes #4702

[DataGrid] Fix Enter causing Select to re-open when commiting value

---

packages/grid/x-data-grid/src/components/GridLoadingOverlay.tsx
packages/grid/x-data-grid/src/components/base/GridOverlays.tsx
packages/grid/x-data-grid/src/components/containers/GridOverlay.tsx

Fixes https://github.com/mui/mui-x/issues/5590

[DataGrid] Fix `GridOverlays` bypassing pointer events

---

packages/x-license-pro/src/useLicenseVerifier/useLicenseVerifier.ts
packages/x-license-pro/src/utils/licenseErrorMessageUtils.ts

This is related to #5730. I'm trying to improve the DX from https://codesandbox.io/s/1cm3xe?file=/demo.tsx.
**Before**
**After**

[license] Give more context in the missing license

---

docs/data/introduction/licensing/licensing.md
docs/public/_redirects
packages/x-license-pro/src/utils/licenseErrorMessageUtils.ts

1. https://mui.com/r/x-license-eula#evaluation-trial-licenses is not a permalink. If we change the anchor link, it would break
2. We say "without restrictions" in the docs and "for non-production environments" in the legal area. It's contradictory.
https://deploy-preview-5732--material-ui-x.netlify.app/x/introduction/licensing/#evaluation-trial-licenses

[docs] Fix contradiction in the free trial clause

---

docs/src/modules/components/ApiPage.js

Open https://mui.com/x/api/data-grid/data-grid/#slots and see how the scroll top is wrong:
I broke it in https://github.com/mui/material-ui/pull/32844. The solution is to replace the same changes here.
Preview: https://deploy-preview-5795--material-ui-x.netlify.app/x/api/data-grid/data-grid/#slots

[docs] Fix API anchor link scroll top

---

test/regressions/index.test.js

The print preview is taking too long to load which causes argos to point a difference, e.g.: https://app.argos-ci.com/mui/mui-x/builds/3071

[test] Increase timeout to take print screenshot

---

docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
packages/grid/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx
packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx
packages/grid/x-data-grid/src/models/props/DataGridProps.ts

Docs said that the default value of DataGrid's logLevel prop is "debug", but its default value is false. 
Please refer to https://github.com/mui/mui-x/blob/a55478c44364734517f7517072cbba50a9360131/packages/grid/x-data-grid/src/models/props/DataGridProps.ts#:~:text=logLevel%3A%20keyof%20Logger%20%7C%20false%3B.
So, if logLevel is not set to debug, DataGrid logs are not visible. The docs need to be modified. @oliviertassinari

[docs] Fix default value of DataGrid's logLevel prop to false

---

packages/x-date-pickers/src/PickersActionBar/PickersActionBar.tsx

Fix #5779 
The component did not support accepting `className` and was unable to process usages of `styled(PickersActionBar)` correctly.
Enables using `styled(PickersActionBar)` to provide custom styles

[Pickers] Add `className` prop to `PickersActionBar`

---

packages/x-date-pickers/src/PickersDay/PickersDay.tsx

Fix #5570
It's a simpler alternative to PR #5598
This issue is a bit tricky because it has animations
The problem is the following:
When pressing mousse down, the focus moves to the day, which triggers the sliding of the month (that's logical)
When mouse up occurs, the element under the mouse might not be the same (due to the sliding of the calendar) so the click event is not triggered (click = down and up on the same element)
Proposed solution:
Prevent the default behavior on move down to avoid putting focus on the day, which triggers the scrolling
The focus is restored to the new button when finishing the `click`

[DatePicker] Support click on day outside of current month

---

docs/data/introduction/licensing/licensing.md

Aims at solving a pain point mentioned by a user when upgrading from community:
https://mui.zendesk.com/agent/tickets/4253
_"The document did not mention that I need to install the license package, and replace the current free packages with another set of packages."_
https://deploy-preview-5683--material-ui-x.netlify.app/x/introduction/licensing/#how-to-install-the-key

[docs] Improve "upgrading plans" documentation.

---

docs/data/date-pickers/localization/localization.md
packages/x-date-pickers/src/locales/index.ts
packages/x-date-pickers/src/locales/koKR.ts
scripts/x-date-pickers-pro.exports.json
scripts/x-date-pickers.exports.json

Following up on #3211, I'd like to provide Korean translations for the Date Picker component.

[pickers] Add Korean (ko-KR) locale

---

docs/data/date-pickers/localization/localization.md
docs/data/date-pickers/migration-lab/migration-lab.md

Fix #5599
We introduced breaking changes in alpha phase that should be introduced in the migration guide, otherwise someone doing the migration will get non working code because of them
[Page preview](https://deploy-preview-5805--material-ui-x.netlify.app/x/react-date-pickers/migration-lab/#3-handle-breaking-changes-introduced-in-alpha)

[pickers] Add a breaking change section in the migration guide

---

packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerViewDesktop.tsx
packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx
packages/x-date-pickers-pro/src/DesktopDateRangePicker/DesktopDateRangePicker.test.tsx
packages/x-date-pickers-pro/src/MobileDateRangePicker/MobileDateRangePicker.test.tsx
packages/x-date-pickers-pro/src/StaticDateRangePicker/StaticDateRangePicker.test.tsx
packages/x-date-pickers/src/CalendarPicker/CalendarPicker.test.tsx
packages/x-date-pickers/src/CalendarPicker/CalendarPicker.tsx
packages/x-date-pickers/src/CalendarPicker/DayPicker.tsx
packages/x-date-pickers/src/CalendarPicker/PickersCalendarHeader.tsx
packages/x-date-pickers/src/CalendarPicker/PickersSlideTransition.tsx
packages/x-date-pickers/src/ClockPicker/ClockPicker.tsx
packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.test.tsx
packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.test.tsx
packages/x-date-pickers/src/MobileDatePicker/MobileDatePicker.test.tsx
packages/x-date-pickers/src/MobileDateTimePicker/MobileDateTimePicker.test.tsx
packages/x-date-pickers/src/MonthPicker/MonthPicker.tsx
packages/x-date-pickers/src/PickersDay/PickersDay.test.tsx
packages/x-date-pickers/src/PickersDay/PickersDay.tsx
packages/x-date-pickers/src/StaticDatePicker/StaticDatePickerKeyboard.test.tsx
packages/x-date-pickers/src/StaticDateTimePicker/StaticDateTimePicker.test.tsx
packages/x-date-pickers/src/YearPicker/PickersYear.tsx
packages/x-date-pickers/src/YearPicker/YearPicker.tsx
packages/x-date-pickers/src/internals/components/PickersPopper.tsx

Fixes #4470
Superseedes #4472 
Closes #4472 
Adjust date pickers a11y implementation bringing it more in line with [w3 aria example](https://www.w3.org/WAI/ARIA/apg/example-index/dialog-modal/datepicker-dialog)
Tested changes on Windows with NVDA making sure that implementation works as similar to the example as possible.

[DatePicker] Improve `a11y` support

---

packages/grid/x-data-grid/src/models/colDef/gridColDef.ts

Closes #5885 by making deprecation note less confusing.
Before:
After:

[DataGrid] Update deprecation note for `GridColDef` `hide` property

---

docs/data/data-grid/editing/LinkedFieldsCellEditing.js
docs/data/data-grid/editing/LinkedFieldsCellEditing.tsx
docs/pages/x/api/data-grid/selectors.json
packages/grid/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx
packages/grid/x-data-grid/src/components/GridRow.tsx
packages/grid/x-data-grid/src/models/gridRows.ts

Fixes https://github.com/mui/mui-x/pull/5214#discussion_r939047535 
It makes much more sense to always treat grid row model as an object rather than `any`

[DataGrid] Improve `GridRowModel` typing

---

packages/grid/x-data-grid-generator/src/hooks/useDemoData.ts

Fixes https://github.com/mui/mui-x/issues/5418#issuecomment-1220583110
Before: https://codesandbox.io/s/restorestateapiref-demo-mui-x-forked-283wi9?file=/demo.js
After: https://codesandbox.io/s/restorestateapiref-demo-mui-x-forked-8kuncw?file=/demo.js
To reproduce:
1. Reorder a column
2. Click "Save state to localStorage"
3. Reload the demo

[core] Memoize `columns` in `useDemoData` hook

---

packages/x-date-pickers-pro/src/DateRangeField/DateRangeField.interfaces.ts
packages/x-date-pickers-pro/src/DateRangeField/useDateRangeField.ts
packages/x-date-pickers-pro/src/MultiInputDateRangeField/useMultiInputDateRangeField.ts
packages/x-date-pickers/src/DateField/DateField.interfaces.ts
packages/x-date-pickers/src/DateField/useDateField.ts

#5397 broke the typing of the fields
The fix is not trivial so I just added some type casting to avoid the error and unlock master.
Will automerge

[core] Fix Typescript error on field hooks

---

docs/data/date-pickers/migration-lab/migration-lab.md

Fix typo "should do not", and bold it so readers can more easily spot what this migration offers

[docs] Fix typo in `migration from lab`

---

packages/grid/x-data-grid-premium/src/DataGridPremium/useDataGridPremiumComponent.tsx

I forget a `useGridColumnGrouping(...)` in Premium hooks, leading to crashing the component because methods were called but not defined since the hook was not here

Fix column grouping in DataGridPremium

---

packages/grid/x-data-grid-pro/src/tests/rowPinning.DataGridPro.test.tsx
packages/grid/x-data-grid/src/components/GridRow.tsx

[DataGridPro] Fix crash when using `pinnedRows` + `getRowClassName` props and `rows=[]`

---

packages/x-date-pickers-pro/src/DateRangeField/DateRangeField.interfaces.ts
packages/x-date-pickers-pro/src/DateRangeField/useDateRangeField.ts
packages/x-date-pickers-pro/src/MultiInputDateRangeField/useMultiInputDateRangeField.ts
packages/x-date-pickers/src/internals-fields/index.ts
packages/x-date-pickers/src/internals/index.ts

[pickers] Do not require `date-fns` in `@mui/x-date-pickers-pro`

---

packages/grid/x-data-grid/src/components/panel/GridColumnsPanel.tsx

Fix #5830
Adds ability to specify a sort order for display of columns in column picker, without changing the order of the columns themselves.

[DataGrid] Add `sort` prop to columns panel slot

---

packages/x-date-pickers/src/CalendarPicker/CalendarPicker.tsx

The behavior described in the TODO has already been implemented (see lines below the removed comment)

[core] Remove outdated TODO

---

.circleci/config.yml
packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.test.tsx

Try fixing [test failing in Edge](https://app.circleci.com/pipelines/github/mui/mui-x/22866/workflows/37f63ea3-e1d3-4e26-827b-b907ea8a875a/jobs/131884) due to different timezone [mentioned here](https://github.com/mui/mui-x/pull/5801#discussion_r957389819).
Tested locally by [setting explicit process](https://blog.liprandi.net/2020/10/running-karma-in-specific-timezone.html) `TZ` of `America/Los_Angeles`.
Another change that could work and potentially reduce future issues - setting explicit time zone for karma tests.

[test] Fix time zone sensitive test

---

packages/x-date-pickers-pro/src/themeAugmentation/index.ts

Fixes #5965
In [docs we mention](https://mui.com/x/react-date-pickers/getting-started/#typescript) that it's enough to import `pro` package types to include augmentation for all pickers, but that's not the case at the moment.

[pickers] Include `community` package `themeAugmentation` in `pro` package types

---

packages/grid/x-data-grid-premium/src/hooks/features/rowGrouping/gridRowGroupingUtils.ts
packages/grid/x-data-grid-premium/src/hooks/features/rowGrouping/useGridRowGroupingPreProcessors.ts
packages/grid/x-data-grid-pro/src/hooks/features/treeData/gridTreeDataUtils.ts
packages/grid/x-data-grid-pro/src/hooks/features/treeData/useGridTreeDataPreProcessors.tsx
packages/grid/x-data-grid-pro/src/tests/filtering.DataGridPro.test.tsx
packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts
packages/grid/x-data-grid/src/hooks/features/filter/useGridFilter.tsx

[DataGridPro] Fix filtering with inactive items

---

packages/grid/x-data-grid-generator/package.json
packages/x-license-pro/package.json

Closes #4251, this was made possible by #5757. This change removes all the non-MIT licenses, ISC licenses:
which makes the evaluation process simpler, as well as solve https://groups.google.com/a/mui.com/g/x/c/5nCzjIIQeDE/m/sEcz_YYvBAAJ.

[core] Remove unused dependencies

---

packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts
packages/grid/x-data-grid/src/hooks/features/keyboardNavigation/useGridKeyboardNavigation.ts
packages/grid/x-data-grid/src/tests/columnSpanning.DataGrid.test.tsx

While fixing the tests for #5911 I noticed that, when using the new editing API, if a cell is committed with Enter and the cell below is spanned, the focus is not moved to the correct cell.
Before: https://codesandbox.io/s/keen-christian-ipv4v4?file=/demo.tsx
After: https://codesandbox.io/s/serverless-microservice-8hbnoe?file=/demo.tsx
- Press <kbd>Enter</kbd> in the Rating column in the 2nd row (Adidas)
- <kbd>Enter</kbd> again
It should move focus to the price column in the last row but it doesn't. In the legacy API it works as expected.

[DataGrid] Fix focused cell if column is spanned and new editing API is used

---

packages/x-date-pickers/src/CalendarPicker/CalendarPickerKeyboard.test.tsx
packages/x-date-pickers/src/CalendarPicker/DayPicker.tsx

Fix #6076
If the next date to focus is disabled, it looks in the current month, and the next one if there is an available date to focus.

[DatePicker] Allow keyboard navigation to ignore disabled date for left/right arrow

---

packages/x-date-pickers/src/MobileDatePicker/MobileDatePickerLocalization.test.tsx
packages/x-date-pickers/src/internals/components/PureDateInput.tsx

Fixes #6063 
Revert the change introduced in #5651 as it introduced a regression due to `onMouseUp` event registered on `Clock` component.
With this change we introduce an additional `onClick` listener on the root element to overcome the issue of `click` event not being registered when clicking on `label` element due to DOM structure and the fact, that `TextField` has a `label` with `pointer-events: none`

[pickers] Re-fix mobile picker not opening on label click

---

packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
packages/x-date-pickers/src/MobileDateTimePicker/MobileDateTimePicker.tsx
packages/x-date-pickers/src/StaticDateTimePicker/StaticDateTimePicker.tsx

I don't know why ESLint did not catch this one...
Fixes #6085

[DateTimePicker] Remove circular import

---

.github/ISSUE_TEMPLATE/5.rfc.yml

Update template as per https://github.com/mui/material-ui/pull/33871 discussion

Update rfc template

---

README.md

It reproduces https://github.com/mui/material-ui#security. My assumption is that there isn't any real reason for having a different tradeoff on how we structure the main Readme, so using the same strategy would be simpler.
I noticed the opportunity while working on https://github.com/mui/material-ui/pull/34219.

[README] Add link to the security page

---

docs/data/introduction/licensing/licensing.md

An attempt to improve #5683. Here is what I found as opportunities in https://mui.com/x/introduction/licensing/#upgrading-from-community
1. The TOCs, there are harder to scan, using "Upgrading" would be faster to search and scan. We use two different h2, for the same information, It feels more cluttered. 
Before
After
2. "Superset", this part seems super important, I'm giving it more emphasis and also make it clear that this is a rule we aim to always follow.
3. We break the superset rule in one case, this also feels important to document.
4. We are in the docs for the license, but the docs feels like it's about the data grid. I have turned the phrase so it takes the data grid as an example
5. "MUI X (Pro or Premium)" -> "MUI X Pro or Premium" to lean on the side of MUI X being an …

[docs] Improve Upgrade plan docs

---

test/regressions/TestViewer.js
test/regressions/index.js

When removing the Storybook, I migrated the regression test of the print to a doc example.
But it renders the date on the printed page, leading to Argos errors.
I can't just mock the time because the date is added by the browser outside of the page.
So I'm just removing the margin to hide it (similar to the solution described [on this page](https://www.geeksforgeeks.org/how-to-remove-url-from-printing-the-page/)).
I also removed an useless check on the test name.

[core] Hide the date on the print regression test

---

packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts

I have noticed this bug in #5292. Take the first demo of https://mui.com/x/react-data-grid/master-detail/ and use `autoHeight`. You will get https://codesandbox.io/s/peaceful-ishizaka-lc53sw?file=/demo.tsx:0-5223. Now, try to expand a row, and see how bad it feels with the scroll position that changes:
https://user-images.githubusercontent.com/3165635/188738223-3c1a9a0e-3ef5-49c3-b5c8-83c5a8cc95ca.mov
It drove me crazy, I couldn't help myself not to open this PR 😁. The fix is made after https://github.com/mui/material-ui/pull/22292.
**After**  😌
https://user-images.githubusercontent.com/3165635/188738402-ba2f4a15-38c3-4914-b108-fee45b6f9af6.mov
https://codesandbox.io/s/pensive-voice-1wif1j?file=/demo.tsx

[data grid] Fix scroll anchoring with master details

---

packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts

Select day, press ArrowDown down to reach a 31. The next ArrowDown leads to an error
https://user-images.githubusercontent.com/45398769/188917580-7025f1e8-0b03-4d4c-aa09-36bdc65271cf.mp4
[current demo](https://mui.com/x/react-date-pickers/date-field/)
[fixed demo](https://deploy-preview-6071--material-ui-x.netlify.app/x/react-date-pickers/date-field/)
The `utils.parse` set the other date parameters to today. So when modifying the day, we set:
|current day value | parsedValue (with dd/mm/yyyy format) | applied diff | newValue | 
|---|---|---|---|
| 1 | 01/09/2022 | -1 | 31/08/2022 |
| 31 | 31/09/2022 (InvalidDate) | crash | crash |
- Force the date to stick into today month (current fix)
- do not pass only the section value but a full date object
I chose the first solution because 
1. it …

[pickers] Fix invalid date error when decreasing `DateField` day 

---

packages/x-date-pickers/src/CalendarPicker/CalendarPicker.test.tsx
packages/x-date-pickers/src/CalendarPicker/CalendarPicker.tsx

Fixes #5393
Behavior described in the issue.

[CalendarPicker] Don't move to closest enabled date when `props.date` contains a disabled date

---

docs/data/pages.ts

Just notice that "Column ordering" is a pro feature but does not have the logo in the menu.

[docs] Add pro logo in "column ordering" link

---

packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json

https://www.npmjs.com/package/@mui/x-date-pickers

[docs] Fix npm repository link to date picker

---

packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerView.tsx
packages/x-date-pickers-pro/src/DesktopDateRangePicker/DesktopDateRangePicker.test.tsx
packages/x-date-pickers/src/CalendarPicker/CalendarPicker.tsx
packages/x-date-pickers/src/CalendarPicker/useCalendarState.tsx
test/utils/pickers-utils.tsx

Closing #5346
- Do not check if `open === true` (I don't understand this check, on pickers and it always `true` - otherwise this component is not rendered - and on static pickers it is always `false`, which caused #5346
- When `disableAutoMonthSwitching`, allow to switch month when it is caused by full value change (makez #5346 works even with this prop)
- Do not restrict the month change when the target date is disabled, `CalendarPicker` is not doing it.

[DateRangePicker] Switch to new month when changing the value from the outside

---

packages/x-date-pickers/src/internals/components/PickersPopper.tsx
packages/x-date-pickers/src/internals/components/wrappers/DesktopTooltipWrapper.tsx
packages/x-date-pickers/src/internals/components/wrappers/DesktopWrapper.tsx

Breaking change on an internal component so nothing special here.

[pickers] Rename the `onClose` prop of  `PickersPopper` `onDismiss` to simplify typing

---

docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
package.json
packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
packages/grid/x-data-grid-premium/src/components/GridExcelExportMenuItem.tsx
packages/grid/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx
packages/grid/x-data-grid-pro/src/components/GridDetailPanelToggleCell.tsx
packages/grid/x-data-grid-pro/src/components/GridTreeDataGroupingCell.tsx
packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx
packages/grid/x-data-grid/src/components/cell/GridActionsCell.tsx
packages/grid/x-data-grid/src/components/cell/GridBooleanCell.tsx
packages/grid/x-data-grid/src/components/cell/GridEditBooleanCell.tsx
packages/grid/x-data-grid/src/components/cell/GridEditDateCell.tsx
packages/grid/x-data-grid/src/components/cell/GridEditInputCell.tsx
packages/grid/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx
packages/grid/x-data-grid/src/components/columnSelection/GridCellCheckboxRenderer.tsx
yarn.lock

I need https://github.com/mui/material-ui/pull/34311 for https://github.com/mui/mui-x/pull/6070

[core] Update monorepo

---

README.md

This is part of improving our score in https://deps.dev/npm/%40mui%2Fx-date-pickers
See https://bestpractices.coreinfrastructure.org/en for why it matters, it also seems to be confirmed with https://mui.zendesk.com/agent/tickets/4926. An example of a project having this: https://github.com/tensorflow/tensorflow.

[docs] Link the OpenSSF Best Practices card

---

packages/x-date-pickers/src/internals/hooks/useField/useField.interfaces.ts
packages/x-date-pickers/src/internals/hooks/useField/useField.ts

We are always generating the date with the exact same function and only with stuff that is also on the state.
So we can just generate it a `useMemo` instead of in the state updaters.

[pickers] Remove `valueStr` from the field state

---

docs/data/data-grid/state/RestoreStateApiRef.js
docs/data/data-grid/state/RestoreStateApiRef.tsx

Closes #6190 
By fixing the Popper, I explicitly add `sx={{ zIndex: 'modal' }}` to Popper which will apply this z-index on to `MuiPopperUnstyled-root` class directly as `style` attribute does not work with Popper component.
Expected behavior you can see this screen record below. More information provided on [the issue](#6190)

[docs] Fix hidden popper in restore state example

---

docs/next.config.js
package.json
yarn.lock

https://deploy-preview-5938--material-ui-x.netlify.app/x/introduction/
- Fix the bug reported in https://github.com/mui/material-ui/pull/34037
- Remove duplication of Next.js configuration. We should be able to abstract most of the docs infrastructure in the mono-repo. We are one step closer to having our own MUI https://github.com/facebook/docusaurus.

[core] Fix scroll restoration in the docs

---

packages/x-date-pickers/src/CalendarPicker/CalendarPicker.test.tsx
packages/x-date-pickers/src/CalendarPicker/CalendarPicker.tsx
packages/x-date-pickers/src/YearPicker/PickersYear.tsx
packages/x-date-pickers/src/YearPicker/YearPicker.tsx

Fix #6187
Cherry picking from #6089

[YearPicker] Scroll to the current year even with `autoFocus=false`

---

docs/scripts/api/buildComponentsDocumentation.ts

The `generateUtilityClass` from @mui/base is going to have a Base-specific implementation (see https://github.com/mui/material-ui/pull/33411). The "bare" version of this function will remain in the @mui/utils package.

[docs] Import generateUtilityClass from @mui/utils

---

packages/x-date-pickers/src/internals/models/muiPickersAdapter.d.ts

[pickers] Fix usage with Typescript 4.8

---

packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx
packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts

Fixes #5742
Before: https://codesandbox.io/s/fullfeaturedcrudgrid-demo-mui-x-forked-9eis2n
After: https://codesandbox.io/s/fullfeaturedcrudgrid-demo-mui-x-forked-1uy5xu

[DataGrid] Do not publish `cellFocusOut` event if the row was removed

---

docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/grid-filter-form.json
docs/pages/x/api/data-grid/grid-filter-panel.json
docs/scripts/api/buildComponentsDocumentation.ts

I found this in the Algolia crawl results (I was looking a bit at how we can improve the Algolia UX)
https://crawler.algolia.com/admin/crawlers/739c29c8-99ea-4945-bd27-17a1df391902/inspector?search=&page=1&status=SKIPPED

[docs] Fix 301 link

---

package.json
scripts/README.md

Without this change, the alpha packages will be tagged as `latest`.

[core] Tag release as next in npm

---

packages/grid/x-data-grid/src/components/toolbar/GridToolbarFilterButton.tsx

Fixes https://github.com/mui/mui-x/issues/6246
Before:
After:
Preview: https://deploy-preview-6259--material-ui-x.netlify.app/x/react-data-grid/filtering/

[DataGrid] Fix `undefined` value being showed in filter button tooltip text

---

docs/data/date-pickers/getting-started/getting-started.md

Fixes #5171
In this issue there is also an issue about importing `TextField` but I think this is related to the clarity of our demo architecture, not to the pickers.
If some people struggle to understand how to display the full doc code, maybe we could improve the UX.

[docs] Improve pickers getting started examples

---

docs/next.config.js
docs/pages/_app.js
scripts/releaseChangelog.js

We missed the `#default-branch-switch` flags.
Before: https://next--material-ui-x.netlify.com/x/react-data-grid/
After: https://deploy-preview-6275--material-ui-x.netlify.app/x/react-data-grid/

[docs] Update the codesandbox to use next

---

packages/x-date-pickers/src/AdapterMoment/index.ts

Fix #6060
Did a migration from `dayjs` to `moment` in a dedicated commit to allow testing in the preview

[DateField] Extend moment adapter to support `expandFormat` and `formatTokenMap`

---

packages/grid/x-data-grid/src/components/GridPagination.tsx

Backport of https://github.com/mui/mui-x/pull/6238

[DataGrid] Fix `GridPagination` props typing

---

packages/grid/x-data-grid/src/components/GridRow.tsx
scripts/x-data-grid-premium.exports.json
scripts/x-data-grid-pro.exports.json
scripts/x-data-grid.exports.json

[DataGrid] Fix `GridRow` not forwarding `ref` to the root element

---

docs/data/data-grid/export/export.md
packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx
test/regressions/TestViewer.js
test/regressions/index.test.js
test/utils/createDOM.js

This seems to be an opportunity to:
1. Fix #6272
2. Show the print window faster, no need to wait for the page to load
3. Remove the HTTP header iframe limitation
4. Remove the dependency on https://github.com/mui/mui-x/pull/4149#issuecomment-1064109395
Before: https://mui.com/x/react-data-grid/export/#default-toolbar
After: https://deploy-preview-6273--material-ui-x.netlify.app/x/react-data-grid/export/#default-toolbar
Tested in Firefox, Safari, Chrome, latest versions
---
I have left a couple of TODO for a clean-up follow-up. I was also surprised with how we document the print export. If you:
1. open https://mui.com/.
2. search for print export: 
3. click on the first link, you will land on https://mui.com/x/react-data-grid/export/#print-export, without a demo. I was disoriented by …

[data grid] Improve print support

---

packages/x-date-pickers/src/internals/hooks/useField/useField.ts

I was still putting `valueParsed` in state instead of `value`, which totally broke the editing.
It is also fixed by #6141 (and tested to avoid future regressions), but I'm doing a standalone quick fix to be able to move forward on other topics.
It has never been released so I'm marking it as `core`.
Will auto-merge

[core] Fix typo in the state updater of useField

---

packages/x-date-pickers/src/CalendarPicker/CalendarPicker.tsx

In [DatePicker doc page](https://mui.com/x/react-date-pickers/date-picker/) the focus is caught by the year picker.
This PR should fix this bug

[CalendarPicker] Prevent getting focus when `autoFocus=false`

---

packages/grid/x-data-grid-premium/src/themeAugmentation/index.js
packages/grid/x-data-grid-premium/src/themeAugmentation/index.ts
packages/grid/x-data-grid-premium/src/themeAugmentation/overrides.ts
packages/grid/x-data-grid-premium/src/themeAugmentation/props.ts

Fixes https://github.com/mui/mui-x/pull/6269#issuecomment-1256512798
Before: https://codesandbox.io/s/muidatagrid-theme-override-forked-23ofno?file=/src/theme.ts
After: https://codesandbox.io/s/muidatagrid-theme-override-forked-exig8p?file=/src/theme.ts

[DataGridPremium] Add missing `themeAugmentation` module

---

docs/data/data-grid/style/StylingRowsGrid.js
docs/data/data-grid/style/StylingRowsGrid.tsx
docs/data/data-grid/style/StylingRowsGrid.tsx.preview
docs/data/data-grid/style/style.md

Preview: https://deploy-preview-6264--material-ui-x.netlify.app/x/react-data-grid/style/#styling-rows
Issue: #6065 
Tried to see if we can do some fix by changing the order of how the classes are being used inside DataGrid, it didn't work probably due to how emotion bundles css assets. Solution proposed by @m4theushw seemed most appropriate.
**Update:** The catch to fix specificity was to use sx on Grid itself rather than Box wrapping the Grid.

[docs] Fixes DataGrid/DataGridPro row styling issue

---

packages/x-date-pickers/src/CalendarPicker/CalendarPicker.tsx

Cherry picking from #6304
Fix #6343

[CalendarPicker] Prevent getting focus when `autoFocus=false` (#6304)

---

docs/data/data-grid/api-object/api-object.md
docs/data/data-grid/events/events.md
docs/data/data-grid/state/state.md

Continuing with #5764 
This PR applies the Style Guide to the 3 pages within the "Advanced" section of the Data Grid docs:
- API object
- Events
- State

[docs] Implement Style Guide on "Advanced" Data Grid doc pages

---

docs/data/date-pickers/localization/localization.md
packages/x-date-pickers/src/locales/index.ts
packages/x-date-pickers/src/locales/jaJP.ts
scripts/x-date-pickers-pro.exports.json
scripts/x-date-pickers.exports.json

Cherry picked from next (see https://github.com/mui/mui-x/pull/6365)

[l10n] Add Japanese (ja-JP) locale to pickers (#6365)

---

packages/x-license-pro/src/useLicenseVerifier/useLicenseVerifier.test.tsx

It seems to be possible since #6043.

[test] Remove redundant test clean-ups

---

packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerInput.tsx
packages/x-date-pickers-pro/src/DesktopDateRangePicker/DesktopDateRangePicker.test.tsx

Fix #6298
For now, the focus was getting lost somewhere on the Popper without keyboard navigation, and with the text fields that look like they are focused but are not truly.
I replaced the `ref` by `inputRef` such that the focus truly goes onto the input. This means the user can know either use the mouse to continue filling the form, or enter a date with a keyboard

[DateRangePicker] Force focus to stay on inputs

---

docs/data/date-pickers/date-range-picker/CustomDateRangePickerDay.js
docs/data/date-pickers/date-range-picker/CustomDateRangePickerDay.tsx

Fixing the demo issue described in the reported issue #6332 ,
DateRangePicker: Selecting days in week which span over month result in highlighting blank columns in other month

[docs] Fix customized day rendering demo style

---

packages/grid/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx
packages/grid/x-data-grid/src/tests/columnsGrouping.DataGrid.test.tsx

Fix #6255
Preview: https://deploy-preview-6405--material-ui-x.netlify.app/x/react-data-grid/column-groups/#define-column-groups

[DataGrid] Fix error when using columnGrouping with all columns hidden

---

CHANGELOG.md
docs/package.json
lerna.json
package.json
packages/grid/x-data-grid-generator/package.json
packages/grid/x-data-grid-premium/package.json
packages/grid/x-data-grid-pro/package.json
packages/grid/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-license-pro/package.json

v6.0.0 alpha.2

---

docs/package.json
yarn.lock

While looking at https://github.com/mui/mui-x/pull/6357 I discovered that:
- this package does not seem to be used
- this package is no longer maintained
- [material-ui replaced](https://github.com/mui/material-ui/pull/27071) it with a different package quite some time ago

[core] Remove unused `react-text-mask` package

---

packages/x-date-pickers/src/AdapterDayjs/index.ts

I was playing with #6337 codesanbox when I tried to use `fr` locale, if failed saying that `"L"` was not a valid token. It took me some time to realize `dayjs` needs to have `'fr'` and not `'frFR'`. And the I have to import `'dayjs/locale/fr'` to let it work.
This PR add a warning and a fallback on `en`

[core] Send explicit warning when dayjs locale is not found

---

packages/grid/x-data-grid-premium/src/hooks/utils/useGridApiContext.ts
packages/grid/x-data-grid-premium/src/hooks/utils/useGridApiRef.ts
packages/grid/x-data-grid-pro/src/components/GridDetailPanelToggleCell.tsx
packages/grid/x-data-grid-pro/src/hooks/utils/useGridApiContext.ts
packages/grid/x-data-grid-pro/src/hooks/utils/useGridApiRef.ts

Just an opportunity for simplification I've noticed while working on https://github.com/mui/mui-x/pull/6388

[DataGrid] Simplify `useGridApiContext` and `useGridApiRef` type overrides

---

CHANGELOG.md
docs/package.json
package.json
packages/grid/x-data-grid-generator/package.json
packages/grid/x-data-grid-premium/package.json
packages/grid/x-data-grid-pro/package.json
packages/grid/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-license-pro/package.json

v6.0.0 alpha.3

---

docs/data/date-pickers/date-picker/FormPropsDatePickers.js
docs/data/date-pickers/date-picker/FormPropsDatePickers.tsx
docs/data/date-pickers/date-picker/FormPropsDatePickers.tsx.preview

I was looking on how to integrate the date picker with a custom component inside Toolpad: https://master--toolpad.mui.com/_toolpad/app/cl4hla83p01949xoizo5uxf2a/pages/cl4hla87800029xoihl7tf4qz. I had to search how to disable the date picker, I found: https://mui.com/x/react-date-pickers/date-picker/#form-props. But I had to open the code sample to find the answer. It was a bit frustrating.
Preview: https://deploy-preview-6477--material-ui-x.netlify.app/x/react-date-pickers/date-picker/#form-props

[docs] Enable inlined preview for disbled date picker

---

packages/x-date-pickers-pro/src/internal/hooks/useMultiInputRangeField/useMultiInputDateRangeField.ts
packages/x-date-pickers-pro/src/internal/hooks/useMultiInputRangeField/useMultiInputDateTimeRangeField.ts
packages/x-date-pickers-pro/src/internal/hooks/useMultiInputRangeField/useMultiInputTimeRangeField.ts

When only one of the two date does not pass the validation, we should only mark its input as invalid.
That is the behavior on the current `DateRangePicker` component.
For the single input range fields, we have to set the whole input as invalid of course.
On both examples below, only the start date is invalid (it is before the `minDate` prop)
[Before](https://codesandbox.io/s/date-and-time-pickers-forked-9pqyfg?file=/src/App.tsx)
[After](https://codesandbox.io/s/date-and-time-pickers-forked-czkwue?file=/src/App.tsx)

[fields] Distinguish start and end input error on multi input fields

---

packages/x-date-pickers/src/internals/models/muiPickersAdapter.d.ts
packages/x-date-pickers/src/themeAugmentation/props.d.ts

Back-port relevant changes from https://github.com/mui/mui-x/pull/6322

[pickers] Fix TS type issues

---

benchmark/browser/webpack.config.js
docs/babel.config.js
docs/data/data-grid/events/CatalogOfEventsNoSnap.js
docs/package.json
package.json
test/e2e/webpack.config.js
test/performance/webpack.config.js
test/regressions/index.js
test/regressions/webpack.config.js
yarn.lock

In the future, we should look into how we can have the docs-infra control it's own npm dependencies so https://github.com/mui/material-ui/pull/34421 is enough.

[core] Remove outdated docsearch.js dependency

---

packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.test.tsx
packages/x-date-pickers-pro/src/DesktopDateRangePicker/DesktopDateRangePicker.test.tsx
packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.test.tsx
packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.test.tsx
packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.test.tsx
packages/x-date-pickers/src/LocalizationProvider/LocalizationProvider.test.tsx

On my previous PRs to migrate to slots, I did not follow a consistent nomenclature for the tests.
This PR is here to clean that a bit.
I propose to always apply the following pattern for component slots tests:
```ts
describe('Component slots: Popper', () => {});
```
It allows to easily look for all the tests related to one slot across components.
It would also probably be nice to create conformance tests like `describeValidation` for the various slots to test it more in depth.

[core] Organize tests for pickers slots

---

docs/data/date-pickers/fields/LifeCycleIgnoreInvalidValue.js
docs/data/date-pickers/fields/LifeCycleIgnoreInvalidValue.tsx
docs/data/date-pickers/fields/LifeCycleIgnoreInvalidValue.tsx.preview
docs/data/date-pickers/fields/fields.md
packages/x-date-pickers-pro/src/internal/hooks/useMultiInputRangeField/useMultiInputDateRangeField.ts
packages/x-date-pickers-pro/src/internal/hooks/useMultiInputRangeField/useMultiInputDateTimeRangeField.ts
packages/x-date-pickers-pro/src/internal/hooks/useMultiInputRangeField/useMultiInputTimeRangeField.ts
packages/x-date-pickers/src/internals-fields/index.ts
packages/x-date-pickers/src/internals/hooks/useField/index.ts
packages/x-date-pickers/src/internals/hooks/useField/useField.interfaces.ts
packages/x-date-pickers/src/internals/hooks/useField/useField.ts
packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts

Fixes #6421
I went for an object instead of just passing the validation error as the 2nd parameter to be future proof.
I think that the validation is light enough to compute it on every call but we could change for a lazy approach:
```tsx
interface FieldChangeHandlerContext<TError> {
validationError: TError;
}
onChange: (value: TValue,  getContext: () => FieldChangeHandlerContext<TError>) => void;
```
Or 
```tsx
interface FieldChangeHandlerContext<TError> {
getValidationError: () => TError;
}
onChange: (value: TValue,  context: FieldChangeHandlerContext<TError>) => void;
```

[fields] Add a `validationError` property to the `onChange` callback

---

packages/x-date-pickers/src/AdapterDateFns/localization.test.tsx
packages/x-date-pickers/src/AdapterDayjs/localization.test.tsx
packages/x-date-pickers/src/AdapterLuxon/index.ts
packages/x-date-pickers/src/AdapterLuxon/localization.test.tsx
packages/x-date-pickers/src/AdapterMoment/index.ts
packages/x-date-pickers/src/AdapterMoment/localization.test.tsx
test/utils/pickers-utils.tsx

Fix #6540
Luxon has specific behavior about localization. You should always specify the locale when calling a method from `DateTime`
Now the `adapterLocale` is applied to both the placeholder and the formatted for the 4 libraries

[adapters] Fix localisation of the placeholder

---

CHANGELOG.md
docs/data/data-grid/aggregation/aggregation.md
docs/data/data-grid/editing/editing.md
docs/data/date-pickers/getting-started/getting-started.md
docs/data/migration/migration-data-grid-v4/migration-data-grid-v4.md
docs/data/migration/migration-pickers-lab/migration-pickers-lab.md

With https://github.com/mui/material-ui/pull/34762 and https://github.com/mui/material-ui/pull/34765 merged, MUI X will need to make these changes, so I thought that I could do them ahead of time, to ease the upgrade of `@mui/monorepo`.

[core] Fix trailing spaces and git diff format

---

packages/grid/x-data-grid-pro/src/tests/rowReorder.DataGridPro.test.tsx
packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts

Fixes https://github.com/mui/mui-x/issues/6520
Before: https://codesandbox.io/s/focused-butterfly-mun6yt?file=/demo.tsx
After: https://codesandbox.io/s/white-firefly-u5tlib?file=/demo.tsx

[DataGridPro] Fix row order being reset after updating the row

---

packages/x-date-pickers-pro/src/internal/hooks/validation/useDateRangeValidation.ts
packages/x-date-pickers-pro/src/internal/hooks/validation/useDateTimeRangeValidation.ts
packages/x-date-pickers-pro/src/internal/hooks/validation/useTimeRangeValidation.ts
packages/x-date-pickers-pro/src/tests/describeValidation.tsx
packages/x-date-pickers-pro/src/tests/testValidation/testTextFieldValidation.tsx
packages/x-date-pickers/src/internals/hooks/validation/useDateValidation.ts

Fix #6404 
Before, we had an early return if one of the fields was incomplete.
Now if one of the fields has an error, it displays the error immediately (even if the second one is not set). 
I had in mind the following use case: If you set the start date to 2021 and `disablePast` is set to `true` you don't need to wait for the second field to be filled to warn the user that the start date is wrong.
If you're ok with the behavior Iw ill add tests

[pickers] Improve consistency between single and multiple range pickers

---

packages/x-date-pickers-pro/src/SingleInputDateRangeField/SingleInputDateRangeField.tsx
packages/x-date-pickers-pro/src/tests/testValidation/testTextFieldValidation.tsx
packages/x-date-pickers/src/DateField/DateField.tsx
packages/x-date-pickers/src/DateTimeField/DateTimeField.tsx
packages/x-date-pickers/src/TimeField/TimeField.tsx
packages/x-date-pickers/src/tests/testValidation/testDayViewValidation.tsx
packages/x-date-pickers/src/tests/testValidation/testTextFieldValidation.tsx

- `date` already equals `any` on the tests, the cast does nothing
- the cast was not needed on the slot, we can just define the type in a regular way

[core] Small typescript improvements

---

docs/pages/_app.js

To reproduce the issue:
1. Open https://618001407e06010008d74197--material-ui-x.netlify.app/components/data-grid/columns/#resizing (based on the `v4.x` branch
2. Click on the "Edit in CodeSandbox" button
3. It fails:
I worked on this because of https://mui.zendesk.com/agent/tickets/5398.
To prove that this fix works, I cherry-picked it to `docs-v4`: https://v4.mui.com/components/data-grid/columns/#resizing.

[docs] Fix codesandboxes with v4

---

docs/pages/_app.js

Same as #6599 for v5, it's meant to anticipate the issue, this time.

[docs] Fix code edit for when v6 will be stable

---

packages/grid/x-data-grid/src/hooks/core/useGridApiInitialization.ts
packages/grid/x-data-grid/src/utils/createSelector.ts

Port of https://github.com/mui/mui-x/pull/6579 to `next` branch

[DataGrid] Fix memory leak on grid unmount

---

packages/x-date-pickers/src/internals/hooks/useMaskedInput.tsx

Fix #6587
Maybe a better approach would be that date parsing ignore the milliseconds such that we can always use `isEqual` without having to worry about those miliseconds

[pickers] Ignore milliseconds in mask logic

---

packages/grid/x-data-grid/src/components/panel/GridColumnsPanel.tsx
packages/grid/x-data-grid/src/tests/columnsVisibility.DataGrid.test.tsx

Backport of https://github.com/mui/mui-x/pull/6444 to `master` branch

[DataGrid] Allow to disable autofocusing the search field in the columns panel

---

docs/public/_redirects

The https://next.mui.com/x/ page is broken, because of bad URL addresses for assets
Sounds like a duplicate of https://mui.com/x/ so better to do a redirect.
found it because it's [reported by ahrefs as orphan page](https://app.ahrefs.com/site-audit/3523498/36/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CcontentType%2Cdepth%2CincomingLinks%2CincomingRedirect%2CincomingCanonical%2CincomingHreflang%2CincomingCss%2CincomingImage%2CincomingJs&filterCollapsed=true&filterId=ec88e618f9ea51131562c23a677ee3f0&issueId=944b9296-00b2-11e8-aeb8-001e67ed4656)

[docs] Remove broken welcome page

---

packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx
packages/x-date-pickers/src/DateTimePicker/dateTimePickerToolbarClasses.ts

[DateTimePicker] Fix toolbar time order when `theme.rtl=true`

---

.github/ISSUE_TEMPLATE/1.bug.yml

We have tried the change https://github.com/mui/material-ui/pull/34279 in core and toolpad, it seems to be a step forward, a proposal to do the same here.

[core] Change reproduction position

---

docs/src/modules/components/ApiPage.js

Fix for the next update of the monorepo: https://github.com/mui/material-ui/pull/34850#issuecomment-1295804491 as raised by @Janpot.
The header of the file says:
```jsx
/**
* TODO replace file with:
* import ApiPage from 'docs/src/modules/components/ApiPage';
*/
```
which this change gets us one step closer to.

[core] Remove legacy migration function

---

.github/workflows/no-response.yml

Fixes a regression from https://github.com/mui/mui-x/pull/6396#discussion_r1008046273

[core] Fix permissions in `no-response` workflow

---

packages/grid/x-data-grid/src/components/columnSelection/GridCellCheckboxRenderer.tsx

Closes #6646
Tested with the demo provided on the ticket and confirmed that it resolves the issue.

[data grid] Remove `React.memo` from `GridCellCheckboxRenderer`

---

packages/grid/x-data-grid/src/components/columnSelection/GridCellCheckboxRenderer.tsx

Backport of https://github.com/mui/mui-x/pull/6655 to `master` branch

[DataGrid] Remove `React.memo` from `GridCellCheckboxRenderer`

---

packages/grid/x-data-grid/src/hooks/features/editing/useGridCellEditing.ts
packages/grid/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts

Based on https://github.com/mui/mui-x/pull/6257#discussion_r996500466. It feels a lot more likely that v19 behavior will be v18 rather than v17.

[DataGrid] Avoid future regression with React 19

---

packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts

Bug found while working on #6625
Without this line, changing the locale does not trigger a recomputation of the sections and thus the format in the input remains the old one.

[fields] Update sections when the locale changes

---

packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerInput.tsx
packages/x-date-pickers-pro/src/MobileDateRangePicker/MobileDateRangePicker.test.tsx
packages/x-date-pickers-pro/src/MobileDateRangePicker/MobileDateRangePicker.tsx
packages/x-date-pickers/src/internals/utils/utils.ts

Fixes #6627 
- fix `focused` prop declaration to allow for `focused` styles application both on tab-focus and when picker is open
- add `readonly` prop to `inputProps`  in mobile date range picker to align the behaviour with regular Date Picker and avoiding opening keyboard on mobile when value is selected

[DateRangePicker] Fix input focused style and mobile behaviour

---

docs/next.config.js

While I was working on this slide: https://docs.google.com/presentation/d/1wnNqlD5KBIOACRb-mutSiU8fLTqjBlff-2y8j4kDMMc/edit#slide=id.g1626cc333d1_0_16, I saw something very strange on Google Analytics:
https://analytics.google.com/analytics/web/#/report-home/a106598593w159022482p272132536
The hits are sent to the development property instead of the production one.
It turns out that we updated the mono repository #6570 to a version that requires `withDocsInfra()` to set the env variables requires by the docs. I have copied `docs/next.config.js`  that we have on the next branch and applied it to the master branch. I didn't think about this when I introduced the `withDocsInfra()` abstraction. I should probably have added some logic so it fails upfront with the env values missing, too late.

[docs] Fix Google Analytics going to the wrong property

---

docs/data/date-pickers/date-picker/date-picker.md

Fix #6758
@flaviendelangle For `next` branch I'm thinking about deleting the section, since all the other pages do not have any localization section:
https://next.mui.com/x/react-date-pickers/date-picker/#localization

[docs] Fix link to localization page

---

docs/data/introduction/licensing/licensing.md
packages/grid/x-data-grid-premium/src/tests/license.DataGridPremium.test.tsx
packages/x-license-pro/src/Watermark/Watermark.tsx
packages/x-license-pro/src/useLicenseVerifier/useLicenseVerifier.ts
packages/x-license-pro/src/utils/licenseErrorMessageUtils.ts
packages/x-license-pro/src/utils/licenseStatus.ts
packages/x-license-pro/src/verifyLicense/verifyLicense.test.ts
packages/x-license-pro/src/verifyLicense/verifyLicense.ts
scripts/x-license-pro.exports.json

A cherry-pick of #5260 in the master branch. It would help with https://mui.zendesk.com/agent/tickets/5620.
It seemed quick to cherry-pick, so I did it. Per https://github.com/mui/mui-x/projects/1 & https://www.notion.so/mui-org/v6-release-87136930824047a390c6c6479cd6c9e2 v6 stable isn't for tomorrow.

[license] Add new license status 'Out of scope'

---

docs/data/date-pickers/fields/fields.md

The demo imports from a `-pro` npm package. https://deploy-preview-6775--material-ui-x.netlify.app/x/react-date-pickers/fields/#fields-to-edit-a-range
I was looking at something unrelated, I was curious about how the range is implemented, I got confused about the docs.

[docs] Add missing Pro header suffix

---

packages/x-date-pickers/src/DatePicker/DatePickerToolbar.tsx
packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx
packages/x-date-pickers/src/internals/components/PickersToolbar.tsx

- Fix vertical alignment
- Remove redundant style overrides
- Add `position: relative` to fix `penIcon` placement in `DateTimePickerToolbar`
[Before](https://codesandbox.io/s/black-platform-26j6o2?file=/demo.tsx) | [After](https://codesandbox.io/s/festive-tharp-fiihkz?file=/demo.tsx:689-837)
Please also [have a look at argos](https://app.argos-ci.com/mui/mui-x/builds/5620) and decide if you agree on the changes visible there.

[pickers] Fix pickers toolbar styling

---

docs/public/static/styles/prism-okaidia.css

Fix https://next.mui.com/x/react-data-grid/row-grouping/
I have copied and pasted the code of `prism-okaidia.css` that we have in the docs-infra repo.
Preview: https://deploy-preview-6820--material-ui-x.netlify.app/x/react-data-grid/row-grouping/

[docs] Sync prism-okaidia.css with source

---

.circleci/config.yml
package.json

Try tackling the [same yarn error code 137 appearing](https://mui-org.slack.com/archives/G011VC970AW/p1668416304708469) when `typescript:ci` is being run.
This error is thrown when the system runs out of physical memory (RAM).
Done some testing using a few different configurations:
- [concurrency 4](https://app.circleci.com/pipelines/github/mui/mui-x/27811/workflows/7d2df8c8-9aba-4522-8c67-960ca7a54680/jobs/159852/resources) -> 72.68s
- [concurrency 5](https://app.circleci.com/pipelines/github/mui/mui-x/27820/workflows/4a246363-93d6-43da-a042-5feb62a37fa9/jobs/159891/resources) -> 69.43s
- [concurrency 7 + medium+*](https://app.circleci.com/pipelines/github/mui/mui-x/27822/workflows/a0a15bd1-4d31-40e0-9509-87dd6a005f36/jobs/159898/steps) -> 76.88s
- [concurrency 6 + …

[core] Fix `test-types` out of memory error

---

packages/grid/x-data-grid-pro/src/tests/detailPanel.DataGridPro.test.tsx
packages/grid/x-data-grid/src/components/GridRow.tsx

Fixes https://github.com/mui/mui-x/issues/6694
Before: https://codesandbox.io/s/hopeful-butterfly-8exv2f?file=/demo.tsx
After: https://codesandbox.io/s/vibrant-tree-vl0s4e?file=/demo.tsx

[DataGridPro] Fix detail panel not working with `getRowSpacing` prop

---

packages/grid/x-data-grid/src/locales/fiFI.ts

columnMenuSortAsc and columnMenuSortDesc were inverted.

[I10n] Improve Finnish (fi-FI) locale on the data grid

---

packages/x-date-pickers/src/DesktopNextDateTimePicker/DesktopNextDateTimePicker.tsx
packages/x-date-pickers/src/DesktopNextDateTimePicker/tests/field.DesktopNextDateTimePicker.test.tsx
packages/x-date-pickers/src/DesktopNextTimePicker/DesktopNextTimePicker.tsx
packages/x-date-pickers/src/DesktopNextTimePicker/tests/field.DesktopNextTimePicker.test.tsx
packages/x-date-pickers/src/MobileNextDateTimePicker/MobileNextDateTimePicker.tsx
packages/x-date-pickers/src/MobileNextDateTimePicker/tests/field.MobileNextDateTimePicker.test.tsx
packages/x-date-pickers/src/MobileNextTimePicker/MobileNextTimePicker.tsx
packages/x-date-pickers/src/MobileNextTimePicker/tests/field.MobileNextTimePicker.test.tsx

Currently, the format in the field does not react to the `ampm` props when used inside a picker.

[pickers] Pass the ampm prop from the new pickers to their field

---

packages/grid/x-data-grid/src/locales/fiFI.ts

[I10n] Improve Finnish (fi-FI) locale on the data grid (#6859)

---

docs/data/introduction/licensing/licensing.md
packages/grid/x-data-grid-premium/src/tests/license.DataGridPremium.test.tsx
packages/x-license-pro/src/Watermark/Watermark.tsx
packages/x-license-pro/src/utils/licenseErrorMessageUtils.ts

- We mention "scope" in the docs but I believe that we only used this terminology in the code to be more flexible in the future. As of now, I believe that it would be clearer to reference a "plan".
- I have used "license key" over "license" to reinforce "Please note that the license key does not cover every scenario, so possession of a valid license key does not by itself confer the right to use the Software." [source](https://mui.com/legal/mui-x-eula/#license-key).
It's a side fix while I was looking at how to fix the root problem of https://mail.google.com/mail/u/0/#inbox/FMfcgzGqRZhTNhvHTVzRCHKXcnSDlnfm. I think that #1364 could be it, point 5. and 7.

[license] Polish error messages
