docs/pages/x/api/date-pickers/pickers-shortcuts.json
packages/x-date-pickers/src/PickersShortcuts/PickersShortcuts.tsx

closes https://github.com/mui/mui-x/issues/12968

[pickers] Add optional `id` attribute on shortcut items

---

docs/data/introduction/licensing/licensing.md

That link didn't make sense, it was self-referring, oops 🙃

[docs] Fix legal link to EULA free trial

---

packages/x-data-grid/src/hooks/features/focus/useGridFocus.ts

Closes https://github.com/mui/mui-x/issues/12955
In HTML, className is a string. In SVG it is an `SVGAnimatedString` object. I think It is better to get the className of an element using `elem.getAttribute`.

[DataGrid] Fix throw error with onBlur at SVG element

---

docs/data/charts/styling/styling.md

[docs] Fix Charts styling typos

---

docs/src/modules/components/InterfaceApiPage.js

Fix broken headings (too big SVG icons) in custom API pages:
- https://mui.com/x/api/charts/axis-config/
- https://mui.com/x/api/data-grid/grid-col-def/
- https://deploy-preview-13074--material-ui-x.netlify.app/x/api/charts/axis-config/
- https://deploy-preview-13074--material-ui-x.netlify.app/x/api/data-grid/grid-col-def/

[docs-infra] Fix custom API page headings

---

packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
packages/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx
packages/x-data-grid/src/DataGrid/DataGrid.tsx
packages/x-data-grid/src/internals/utils/propValidation.ts

Open https://mui.com/x/react-data-grid/, see how we load unless code in the JS bundle:
It increases the bundle size reported in https://bundlephobia.com/package/@mui/x-data-grid 🙃. 
The most popular minifiers, esbuild seem to win https://npmtrends.com/esbuild-vs-terser-vs-uglify-js. A quick reproduction: https://esbuild.github.io/try/#YgAwLjIwLjIAeyBtaW5pZnk6IHRydWUsIGJ1bmRsZTogdHJ1ZSB9AABwcm9wVmFsaWRhdGlvbi5qcwBleHBvcnQgY29uc3QgcHJvcFZhbGlkYXRvcnMgPSBbKCkgPT4gJ2Vycm9yIG1lc3NhZ2UnXTsKCmV4cG9ydCBmdW5jdGlvbiB2YWxpZGF0ZVByb3BzKHByb3BzLCB2YWxpZGF0b3JzKSB7CiAgaWYgKHByb2Nlc3MuZW52Lk5PREVfRU5WID09PSAncHJvZHVjdGlvbicpIHsKICAgIHJldHVybjsKICB9CiAgdmFsaWRhdG9ycy5mb3JFYWNoKCh2YWxpZGF0b3IpID0+IHt9KTsKfQBlAERhdGFHcmlkLmpzAGltcG9ydCB7oHZhbGlkYXRlUHJvcHMsIHByb3BWYWxpZGF0b3JzIH0gZnJvbSAnLi9wcm9wVmFsaWRhdGl …

[DataGrid] Reduce bundle size with error messages

---

.circleci/config.yml

I saw this in https://github.com/mui/base-ui/pull/394
- It's strange to install Playwright for danger, it shouldn't need it.
- Why disable transpilation, it seems fine https://danger.systems/js/tutorials/transpilation

[core] Simplify Danger's config

---

packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.ts
packages/x-date-pickers/src/AdapterDateFnsBase/AdapterDateFnsBase.ts
packages/x-date-pickers/src/AdapterDateFnsJalali/AdapterDateFnsJalali.test.tsx
packages/x-date-pickers/src/AdapterDateFnsJalali/AdapterDateFnsJalali.ts
packages/x-date-pickers/src/AdapterDateFnsJalaliV3/AdapterDateFnsJalaliV3.ts
packages/x-date-pickers/src/AdapterDateFnsV3/AdapterDateFnsV3.ts

Follow-up on https://github.com/mui/mui-x/pull/12891
- Fix `AdapterDateFnsJalali.test.tsx` to test proper adapter
- Reuse `AdapterDateFnsBase` in Jalali adapters

[pickers] Reuse `AdapterDateFnsBase` in Jalali adapters

---

packages/x-charts/src/ChartsTooltip/utils.tsx
packages/x-charts/src/hooks/useAxisEvents.ts
packages/x-charts/src/internals/utils.ts

Resolves: https://github.com/mui/mui-x/issues/13041
Added tracking of touch events for correct operation on mobile devices. This works in case of an `axis` trigger.
This solution does not work for an `item` trigger. It is necessary to come up with a solution for this case.
**Preview:** https://deploy-preview-13043--material-ui-x.netlify.app/x/react-charts/tooltip/

[charts] Add support mobile tooltip

---

docs/pages/x/api/charts/bar-chart.json
docs/pages/x/api/charts/line-chart.json
docs/pages/x/api/charts/pie-chart.json
docs/pages/x/api/charts/scatter-chart.json
packages/x-charts/src/BarChart/BarChart.tsx
packages/x-charts/src/ChartsOverlay/ChartsLoadingOverlay.tsx
packages/x-charts/src/ChartsOverlay/ChartsNoDataOverlay.tsx
packages/x-charts/src/ChartsOverlay/ChartsOverlay.tsx
packages/x-charts/src/LineChart/LineChart.tsx
packages/x-charts/src/PieChart/PieChart.tsx
packages/x-charts/src/ScatterChart/ScatterChart.tsx

[charts] Fix the font used in the overlay

---

docs/data/date-pickers/custom-field/BrowserV7SingleInputRangeField.tsx
docs/data/date-pickers/date-time-range-picker/DateTimeRangePickerValue.tsx
docs/data/date-pickers/fields/ControlledSelectedSectionsMultiInputRangeField.tsx
docs/data/date-pickers/fields/ControlledSelectedSectionsSingleInputRangeField.tsx
packages/x-codemod/src/v6.0.0/pickers/migrate-to-components-componentsProps/actual.spec.js
packages/x-codemod/src/v6.0.0/pickers/migrate-to-components-componentsProps/expected.spec.js
packages/x-codemod/src/v6.0.0/pickers/rename-components-to-slots/actual-props.spec.js
packages/x-codemod/src/v6.0.0/pickers/rename-components-to-slots/expected-props.spec.js
packages/x-codemod/src/v6.0.0/pickers/replace-arrows-button-slot/actual.spec.js
packages/x-codemod/src/v6.0.0/pickers/replace-arrows-button-slot/expected.spec.js
packages/x-codemod/src/v7.0.0/pickers/preset-safe/actual.spec.tsx
packages/x-codemod/src/v7.0.0/pickers/preset-safe/expected.spec.tsx
packages/x-date-pickers-pro/src/DesktopDateRangePicker/tests/DesktopDateRangePicker.test.tsx
packages/x-date-pickers/src/AdapterDateFnsJalali/AdapterDateFnsJalali.test.tsx
packages/x-date-pickers/src/AdapterDateFnsJalaliV3/AdapterDateFnsJalaliV3.test.tsx
packages/x-date-pickers/src/AdapterDayjs/AdapterDayjs.test.tsx
packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.test.tsx
packages/x-date-pickers/src/AdapterMoment/AdapterMoment.test.tsx
packages/x-date-pickers/src/AdapterMomentHijri/AdapterMomentHijri.test.tsx
test/e2e/index.test.ts

Small cleanup—avoid importing from package root where possible.

[core] Avoid root level `@mui/x-date-pickers` imports

---

packages/x-data-grid-pro/src/tests/rowEditing.DataGridPro.test.tsx
packages/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts

Closes https://github.com/mui/mui-x/issues/11423
I need this to work for Toolpad. Instead of creating [workarounds](https://stackblitz.com/edit/react-m6fhje-31blaf?file=Demo.tsx), might as well just fix it at the root.
The problem seems to be that `updateStateToStopRowEditMode` in the loop doesn't run. `rowModesModel` is an empty object and thus the `.forEach` doesn't run. This PR adjusts the logic and runs the loop for each property of both previous and current `rowModesModel`. If the current one doesn't contain a model for a row, it assumes it's in view mode.

[DataGrid] Fix `rowModesModel` controlled prop

---

packages/x-charts/src/LineChart/AreaPlot.tsx

Fix #13067
I would still discourage the use of overlapping areas except for very specific edge case (such the one in the issue) 🙈
With no structure
With guarantee some series are always smaller than others
I introduced this `reverse` when creating the animation, otherwise you get a weird state with the line and the area not in sync, just because the area on top of you is overlapping  (the time it finishes its animation too)
This fix applies the reverse on staking groups instead of all series.
- For staked series, they do not overflow so we can reverse the series order
- For non-stacked series, we do not apply the reverse and so they overlap correctly

[charts] Fix area order when overlapping

---

docs/src/modules/components/InterfaceApiPage.js
package.json
pnpm-lock.yaml

Bring https://github.com/mui/material-ui/pull/42236 to have better sync between the docs in core and X, and avoid this regression: 
https://mui-org.slack.com/archives/C04U3R2V9UK/p1715099605724209
To test: https://deploy-preview-13139--material-ui-x.netlify.app/x/api/data-grid/grid-col-def/

[docs-infra] Reuse the `SectionTitle`

---

packages/x-charts/src/BarChart/BarElement.tsx

Fix #12921
The issue seems to come from the `useSlotProps` which try to guess props types from the component `Bar`
Wich can be a `styled(animated.rect)` or a `rect` component with some additional props.
To simplify all that:
- I updated `BarProps` such that it knows it needs to expect props `x`, `y`, `width`, and `height` to be animated ones
- Override the type of `BarElementPath` such that `styles only get access the the `BarProps`

[charts] Fix TS bottle neck

---

packages/x-date-pickers/src/DesktopDatePicker/tests/field.DesktopDatePicker.test.tsx
packages/x-date-pickers/src/internals/hooks/useField/useFieldV6TextField.ts

Fixes [#12573](https://github.com/mui/mui-x/issues/12573).
Add some tests to prevent it in the future.
It should now be possible to pass the `placeholder` prop as either an empty string or undefined in order to achieve an empty placeholder in textField component. Sending no placeholder prop must fall into the default placeholder, generated specifically for each kind of picker.

[fields] Allow empty `textField` slot placeholder value

---

docs/package.json
pnpm-lock.yaml
renovate.json
webpackBaseConfig.js

I started looking at how to solve https://github.com/mui/mui-x/security/dependabot/119.
This lead me to the super old `raw-loader` package.
Bumping to the latest version seemed to work.
Then I also tried removing the package—no issues after that as well. 🤔 
We are running our `md` files through `@mui/internal-markdown/loader` and that looks enough:
https://github.com/mui/mui-x/blob/fd544b72a3566c12eecf50e1bfbbc75c1b6fc114/docs/next.config.mjs#L135
MUI Core seems still have the `raw-loader` dependency, but it is not used anywhere as far as I can see...
https://github.com/mui/material-ui/blob/cadb0b1b937b86b3be214ab65b1cc7067080f85a/package.json#L178

[core] Remove `raw-loader` package

---

packages/x-charts/src/LineChart/MarkElement.tsx
packages/x-data-grid-premium/src/components/GridColumnMenuRowGroupItem.tsx
packages/x-data-grid-premium/src/components/GridColumnMenuRowUngroupItem.tsx
packages/x-data-grid-premium/src/components/GridPremiumColumnMenu.tsx
packages/x-data-grid-pro/src/components/GridProColumnMenu.tsx
packages/x-data-grid/src/components/GridScrollArea.tsx
packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx
packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx
packages/x-date-pickers/src/DayCalendarSkeleton/DayCalendarSkeleton.tsx
packages/x-date-pickers/src/PickersLayout/PickersLayout.tsx
packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx

Follow up on #13167
To be honest I did not dive deep to understand why those were outdated.
But the CI shows that generating the prop-types do not add those back, and I don't think we should keep prop-types that are not synchronized with the typing.

[core] Remove outdated prop-types

---

packages/x-tree-view/src/TreeItem/TreeItem.test.tsx
packages/x-tree-view/src/hooks/useTreeItem2Utils/useTreeItem2Utils.tsx
packages/x-tree-view/src/internals/plugins/useTreeViewIcons/useTreeViewIcons.test.tsx
packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.test.tsx
packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.test.tsx
test/utils/tree-view/describeTreeView/describeTreeView.tsx
test/utils/tree-view/describeTreeView/describeTreeView.types.ts

Part of #12433
I had to improve `describeTreeView` to handle these less traditional tests

[test] Use `describeTreeView` for items rendering edge-case tests

---

.codesandbox/ci.json
.eslintrc.js
.mocharc.js
babel.config.js
docs/pages/_app.js
docs/scripts/createXTypeScriptProjects.ts
packages/x-charts-pro/.mocharc.js
packages/x-charts-pro/LICENSE
packages/x-charts-pro/README.md
packages/x-charts-pro/package.json
packages/x-charts-pro/src/index.ts
packages/x-charts-pro/tsconfig.build.json
packages/x-charts-pro/tsconfig.json
packages/x-charts/src/ChartsText/ChartsText.tsx
packages/x-license/src/useLicenseVerifier/useLicenseVerifier.ts
pnpm-lock.yaml
scripts/buildApiDocs/chartsSettings/getComponentInfo.ts
scripts/buildApiDocs/chartsSettings/index.ts
tsconfig.json
webpackBaseConfig.js

This PR is just about the update of the config files. Mostly modifications taken from #12240 and #12610
Followup will be
- Add the watermark on the pro chart container
- Make a PoC of the heatmap

[charts] Setup the repository for charts-pro

---

docs/data/pages.ts
packages/x-tree-view/src/internals/useTreeView/useTreeViewModels.ts

[docs] Clean the pages in the navbar

---

packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePickerLayout.tsx
packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx
packages/x-date-pickers/src/internals/hooks/usePicker/usePickerViews.ts
test/utils/pickers/describePicker/describePicker.tsx

Fixes #11618.
- Avoid correlation between the `disableOpenPicker` prop intent and the fact that it forced the UI not to be rendered.
- Add a test asserting that:
- a button is hidden (if it even should be present) when `disableOpenPicker="true"`
- the `MuiPickersLayout-contentWrapper` element has children - is not empty

[pickers] Fix `disableOpenPicker` prop behavior

---

packages/x-tree-view/src/internals/plugins/useTreeViewExpansion/useTreeViewExpansion.ts
packages/x-tree-view/src/internals/plugins/useTreeViewExpansion/useTreeViewExpansion.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewFocus/useTreeViewFocus.ts
packages/x-tree-view/src/internals/plugins/useTreeViewFocus/useTreeViewFocus.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewId/useTreeViewId.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewJSXItems/useTreeViewJSXItems.tsx
packages/x-tree-view/src/internals/plugins/useTreeViewJSXItems/useTreeViewJSXItems.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.types.ts

I was supposed to do it for some time :angel:

[TreeView] Add JSDoc to every instance method

---

docs/data/charts/line-demo/LineWithPrediction.js
docs/data/charts/line-demo/LineWithPrediction.tsx
docs/data/charts/line-demo/LineWithPrediction.tsx.preview
docs/data/charts/line-demo/line-demo.md

[docs] Document how to customize a subsection of a line chart

---

.github/workflows/add-release-reviewers.yml

Prevent "Add reviewers" workflow from triggering since it doesn't work

---

docs/data/charts/tooltip/tooltip.md

[docs] Add conditional label formatting on tooltip page and link to label page

---

docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
packages/x-data-grid-premium/src/index.ts
packages/x-data-grid-pro/src/components/GridColumnHeaders.tsx
packages/x-data-grid-pro/src/index.ts
packages/x-data-grid/src/index.ts
packages/x-data-grid/src/models/gridSlotsComponent.ts
scripts/x-data-grid-premium.exports.json
scripts/x-data-grid-pro.exports.json
scripts/x-data-grid.exports.json

Fixes https://mui-org.slack.com/archives/C04U3R2V9UK/p1716299163315909

[DataGrid] Export `GridColumnHeadersProps`

---

packages/x-data-grid/src/locales/faIR.ts

fix some spaces and change some words

[l10n] Improve Persian (fa-IR) locale

---

packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx

Since MUI X v7 is supposed to have the same browser support as Material UI v6 https://github.com/mui/material-ui/issues/40958. So support Safari >=15.4. I'm removing code that is well supposed in that range: https://caniuse.com/css-touch-action.
Less code, faster parse time, faster rendering.
I saw this from working on #13248.

[data grid] Remove dead logic to support Safari < 13

---

packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx
packages/x-data-grid/src/utils/domUtils.ts

As part of my due diligence on https://app.ashbyhq.com/jobs/c86e52ce-0f3b-41cd-871b-5a7fd4044238/candidate-pipeline/active/right-side/candidates/9f3a6ab2-c71b-4b25-a92b-3996f1d04647/applications/ed537f84-6d1b-4efc-b788-a29fa6c7a081/emails. I looked at #12863. I wanted to better understand how the changes connect to the rest of the codebase.
I have added comments to explain why this much complexity.
It would be possible to cheat this, meaning working around https://codesandbox.io/p/sandbox/style-sync-np6fdh?file=%2Fsrc%2FApp.js%3A5%2C30, but it would mean adding some randomness to the width, hacky 😄

[core] Add comment on why logic to sync column header

---

docs/pages/_app.js

From @mui/monorepo we get `next` as the resolved version to be used in sandboxes, which is perfectly valid for them.
But `@mui/x` packages support only v5 releases of `@mui/material`.
This ensures consistency between docs demos and the opened sandbox examples (StackBlitz or CodeSandbox).

[docs-infra] Fix `@mui/material` version used in sandboxes

---

packages/x-date-pickers/src/models/adapters.ts
test/utils/pickers/describeGregorianAdapter/testCalculations.ts

[pickers] Fix `DateBuilderReturnType` when the date is `undefined`

---

docs/data/tree-view/rich-tree-view/customization/FileExplorer.js
docs/data/tree-view/rich-tree-view/customization/FileExplorer.tsx

Removes a line that has no effect for `TreeItem2`
Reported on #13259

[docs] Removes unused lines in TreeItem2 styling

---

docs/data/data-grid/faq/faq.md

[docs] Improve the Data Grid FAQ page

---

packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.test.tsx
packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx
packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.types.ts
packages/x-date-pickers-pro/src/DateRangeCalendar/useDragRange.ts

[typescript] Remove duplicate `DateRangePosition` type in favor of `RangePosition`

---

docs/data/data-grid/accessibility/accessibility.md
docs/data/tree-view/accessibility/accessibility.md

Adds information about key combinations that might be necessary on some devices.
The design and content are open to discussion

[docs] Add information about key combinations on a11y sections

---

docs/package.json
package.json

Fix https://github.com/mui/mui-x/actions/runs/9287240393
Follow up on https://github.com/mui/mui-x/pull/13251#discussion_r1618835800
Replace a few other easy instances of `babel-node` usages with `node` or `tsx`.

[core] Fix `l10n` script execution with arguments

---

packages/x-charts/src/BarChart/checkScaleErrors.ts

[charts] Refactor checkScaleErrors to improve readability and simplify axis message logic

---

packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx
packages/x-data-grid/src/utils/domUtils.ts

Closes: https://github.com/mui/mui-x/issues/12954
~~The support of the CSS API seems common enough: https://caniuse.com/mdn-api_css_escape_static.~~
Before: https://codesandbox.io/p/sandbox/wild-surf-ygtjk6
After: https://codesandbox.io/p/sandbox/upbeat-grass-9h7tfd

[data grid] Fix column resize not working with special character

---

package.json
packages/x-charts/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-license/package.json
packages/x-tree-view-pro/package.json
packages/x-tree-view/package.json
pnpm-lock.yaml

Fixes #13317.
- Move the `@mui/internal-test-utils` dependency from `dependencies` to `devDependencies` on the `@mui/x-data-grid` package.
- Change version to a stable released package `1.0.0`.
WDYT @mui/code-infra, wouldn't it be more correct if the internal package stable versions were released with the `latest` flag instead of `next`? 🤔

[core] Move `@mui/internal-test-utils` to dev dependency

---

docs/translations/api-docs/charts/axis-config.json
docs/translations/api-docs/charts/charts-x-axis/charts-x-axis.json
docs/translations/api-docs/charts/charts-y-axis/charts-y-axis.json
packages/x-charts/src/ChartsXAxis/ChartsXAxis.tsx
packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx
packages/x-charts/src/hooks/useTicks.ts

From docs feedback
> It is not clear when tickInterval is used and when is not. I placed breakpoint in useTicks.js to see how ticks are calculated for my BarChart, and useTicks returned result without using tickInterval value at all, doesn't matter if it is array or filtering function (code bellow comment //scale type = 'band').
BtW this feature is not applied on bar chart. The reason why is very opinionated. bar chart should be used on categorical plotting. So each tick should be present. But it's something open to dicussion

[docs] Fix the description of `tickInterval`

---

docs/data/date-pickers/timezone/timezone.md
packages/x-date-pickers/src/AdapterDayjs/AdapterDayjs.ts
test/e2e/fixtures/DatePicker/SingleDesktopDateRangePickerWithTZ.tsx
test/e2e/index.test.ts

Fixes #13290
The main problem was that in an environment, where `utc` and `timezone` plugins are enabled, but regular dayjs constructor is used, changing value could have resulted in timezone differences.
- Focus input
- Press <kbd>ArrowDown</kbd> twice
- Observe the thrown exception/error
https://codesandbox.io/p/sandbox/adapterdayjs-daterangepicker-timezone-error-lqdjgx?file=%2Fsrc%2FApp.tsx
https://codesandbox.io/p/sandbox/adapterdayjs-daterangepicker-timezone-error-fixed-hcz288?file=%2Fsrc%2FApp.tsx

[pickers] Fix `AdapterDayjs` timezone behavior

---

.gitignore

Adds `.env.local` to gitignore. @cherniavskii realised it was missing when testing a license key locally.

[core] add docs .env.local to gitignore

---

packages/x-charts/src/BarChart/BarPlot.tsx
packages/x-charts/src/ChartsLegend/ChartsLegend.tsx
packages/x-charts/src/ChartsOnAxisClickHandler/ChartsOnAxisClickHandler.tsx
packages/x-charts/src/ChartsTooltip/ChartsAxisTooltipContent.tsx
packages/x-charts/src/ChartsTooltip/ChartsItemTooltipContent.tsx
packages/x-charts/src/ChartsTooltip/utils.tsx
packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx
packages/x-charts/src/LineChart/AreaPlot.tsx
packages/x-charts/src/LineChart/LineHighlightPlot.tsx
packages/x-charts/src/LineChart/LinePlot.tsx
packages/x-charts/src/LineChart/MarkPlot.tsx
packages/x-charts/src/PieChart/PiePlot.tsx
packages/x-charts/src/ScatterChart/ScatterPlot.tsx
packages/x-charts/src/context/CartesianContextProvider.tsx
packages/x-charts/src/context/DrawingProvider.tsx
packages/x-charts/src/context/HighlightedProvider/HighlightedContext.ts
packages/x-charts/src/context/HighlightedProvider/HighlightedProvider.tsx
packages/x-charts/src/context/HighlightedProvider/useHighlighted.test.tsx
packages/x-charts/src/context/HighlightedProvider/useHighlighted.ts
packages/x-charts/src/context/HighlightedProvider/useItemHighlighted.ts
packages/x-charts/src/context/SeriesContextProvider.tsx
packages/x-charts/src/context/context.types.ts
packages/x-charts/src/hooks/useInteractionItemProps.ts
packages/x-charts/src/hooks/useSeries.test.tsx
packages/x-charts/src/hooks/useSeries.ts
packages/x-charts/src/hooks/useSvgRef.test.tsx
packages/x-charts/src/hooks/useSvgRef.ts

- Add `Initializable<T>` type
- Make sure complex user-facing contexts are initializable so we can more consistently check if they are actually present in the scope.
- Make sure simple user-facing contexts are initializable (`useSvgRef`)
- Add tests to ensure the checks
- Use hooks in place of `useContext`
Contexts are never `undefined`, they always have their default values, so the previous checks were doing nothing.
For contexts where the type is allow `null|undefined` but is required to be non-null at runtime, we can just check for thuthness

[charts] Add Initializable type and behaviour to allow checking if a complex context has been initialized. 

---

packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputMultipleSingleSelect.tsx
packages/x-date-pickers-pro/src/models/fields.ts
packages/x-date-pickers/src/PickersLayout/PickersLayout.types.ts
packages/x-date-pickers/src/internals/components/PickersToolbarButton.tsx

Cherry-pick changes that are necessary for React 18.3 (https://github.com/mui/mui-x/pull/12295), but can be applied before that.

[core] Fixes in preparation for React 18.3

---

docs/package.json
pnpm-lock.yaml

With the introduction of a direct dependency:
https://github.com/mui/mui-x/blob/671e68394d7ccde8badbbc1dbd923b971d004c32/package.json#L90
We are getting the `marked` dependency installed without us needing to specify it explicitly:
https://github.com/mui/mui-x/blob/671e68394d7ccde8badbbc1dbd923b971d004c32/pnpm-lock.yaml#L3718-L3725
Removing the explicit dependency to have easier control over it's versioning.

[core] Remove explicit `marked` dependency

---

package.json
pnpm-lock.yaml

Fixes:
Add missing root `rimraf` dep to make `clean:node_modules` work.

[core] Remove unused `@types/prettier` dependency

---

packages/x-charts/src/ChartContainer/ChartContainer.tsx
packages/x-charts/src/ChartContainer/defaultPlugins.ts
packages/x-charts/src/ChartContainer/usePluginsMerge.ts
packages/x-charts/src/models/plugin.ts
scripts/x-charts.exports.json

[charts] Simplify plugin types

---

.eslintrc.js
package.json
pnpm-lock.yaml

Added multiple ways to enable the eslint rule, globaly or by "package"
```
ENABLE_REACT_COMPILER_PLUGIN=true pnpm eslint
// Or use one of the package specific ones
```
Part of https://github.com/mui/material-ui/issues/42548

[core] Add `eslint-plugin-react-compiler` experimental version and rules

---

packages/x-charts/src/themeAugmentation/components.d.ts

Not sure if this interferes with anything, but noticed it when a [CI failed](https://app.circleci.com/pipelines/github/mui/material-ui/131175/workflows/93ed1d68-e4be-44d7-aeb2-d89749f15566/jobs/707475) on the dashboard.

[charts] Improve themeAugmentation typing

---

docs/data/data-grid/accessibility/accessibility.md
docs/data/date-pickers/accessibility/accessibility.md
docs/data/tree-view/accessibility/accessibility.md

We were talking about documenting accessibility testing guidelines in one of the Core meetings and eventually touched on how the Tree View component implemented keyboard navigation. Then, on each accessibility page, we realized we were saying "complete accessibility support" which is arguably one thing we can't ever say—we don't know if we're supporting every single accessibility-related feature or if we're being fully accessible, particularly given there's very little focus on, in any of these pages, screen readers; they're mostly focused on keyboard navigation.
So, this PR changes the descriptions of the accessibility-focused pages a bit to reflect that train of thought.

[docs] Update a11y pages description

---

.circleci/config.yml

- Use a regular docker container for the `danger` step as the playwright does not seem to need it... 🤷 🙈 
- Use the same `pnpm` version as in `package.json`
- using `latest-8` is no longer correct as we already use v9
- using `latest-9` is potentially incorrect depending on which version is specified in `package.json`.
~~Do you know if omitting the `@` portion would end up using the `package.json` specifier? @Janpot @michaldudak I see that both [base-ui](https://github.com/mui/base-ui/blob/master/.circleci/config.yml) and [toolpad](https://github.com/mui/mui-toolpad/blob/master/.circleci/config.yml) do not call `corepack prepare`. Have you seen any problems with it? Or maybe we could also remove it? 🤔~~
Removed the `corepack prepare` as agreed here: …

[infra] Adjust CI setup

---

docs/data/charts/scatter/scatter.md
docs/pages/x/api/charts/chart-container.json
docs/pages/x/api/charts/responsive-chart-container.json
docs/translations/api-docs/charts/chart-container/chart-container.json
docs/translations/api-docs/charts/responsive-chart-container/responsive-chart-container.json
packages/x-charts/src/BarChart/BarChart.tsx
packages/x-charts/src/ChartContainer/ChartContainer.tsx
packages/x-charts/src/ChartsOverlay/index.ts
packages/x-charts/src/ChartsTooltip/ChartsAxisTooltipContent.tsx
packages/x-charts/src/LineChart/LineChart.tsx
packages/x-charts/src/PieChart/PieChart.tsx
packages/x-charts/src/ResponsiveChartContainer/ResponsiveChartContainer.tsx
packages/x-charts/src/ScatterChart/ScatterChart.tsx
packages/x-charts/src/SparkLineChart/SparkLineChart.tsx

Currently, you have to add this context if needed (for example on scatter chart with composition).
The tradeoff feels bad. Might be better to have all context in the container. I removed the `zAxis` type propagation fot charts that do not use it (every charts except scatter for now).
Part of #13209

[charts] Move the `ZAxisContextProvider` by default in the `ChartContainer`

---

docs/scripts/api/buildApi.ts
docs/scripts/api/buildGridEventsDocumentation.ts
docs/scripts/api/buildInterfacesDocumentation.ts
docs/scripts/generateProptypes.ts
docs/scripts/tsconfig.json
package.json
pnpm-lock.yaml
prettier.config.js
scripts/build.mjs
scripts/buildApiDocs/index.ts
scripts/l10n.ts
scripts/prettier.mjs
scripts/releaseChangelog.mjs
scripts/releaseTag.mjs
scripts/treeDataFromFileTree.ts

- Fix TS issues and align approach of `yargs` usages
- Add missing `@babel/traverse` type
- Fix `l10n` TS issues
- Remove unused `scripts/prettier.mjs` file importing non-existent file
- Remove explicit prettier override as it is included in the monorepo already: https://github.com/mui/material-ui/pull/40668/files#diff-e42472dd65561fe56344281078077fb924cddca92821eadfbc2318cca3f89c9a
- Use `@mui/internal-markdown` import instead of `@mui/monorepo/packages/markdown`

[core] Minor setup cleanup

---

package.json
pnpm-lock.yaml

Based on https://github.com/mui/mui-x/pull/13463#issuecomment-2162775711
We are not using this dependency directly and it is even disallowed: https://github.com/mui/mui-x/blob/40b6038015646d41146614947fb53c52e7277687/.eslintrc.js#L187
This dependency is now coming from: https://github.com/mui/material-ui/blob/58831f0a1861337a7dddffe522cf3edbbeaf00d9/packages-internal/test-utils/package.json#L42
This will remove the need to separately control the dependency version and possibly introduce a discrepancy between expected package versions: https://github.com/mui/mui-x/pull/13429

[infra] Remove explicit `@testing-library/react` dependency

---

docs/data/date-pickers/base-concepts/base-concepts.md
docs/data/migration/migration-pickers-v6/migration-pickers-v6.md

[docs] Document the `PickerValidDate` type override

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/ptPT.ts

[l10n] Improve Portuguese (pt-PT) locale

---

packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.ts
packages/x-date-pickers/src/AdapterDateFnsJalali/AdapterDateFnsJalali.ts
packages/x-date-pickers/src/AdapterDateFnsJalaliV3/AdapterDateFnsJalaliV3.ts
packages/x-date-pickers/src/AdapterDateFnsV3/AdapterDateFnsV3.ts

Fixes #13226 as suggested in the comments.
Applied to both `AdapterDateFnsJalaliV3` & `AdapterDateFnsV3` who rely on date-fns-v3
UPD: Applied to Adapters based on **date-fns-v2** as well so the don't lose types when dependency is switched to date-fns-v3

[pickers] Fix `AdapterDateFnsV3` generated method types

---

packages/x-date-pickers/src/TimeField/tests/editing.TimeField.test.tsx
packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts

[fields] Do not apply digit editing when pressing `Space`

---

docs/data/data-grid/export/ExcelCustomExport.js
docs/data/data-grid/export/ExcelCustomExport.tsx
docs/data/data-grid/export/ExcelCustomExport.tsx.preview
docs/data/data-grid/tree-data/tree-data.md

Closes https://github.com/mui/mui-x/issues/13470

[docs][data grid] Warn about `getTreeDataPath` reference

---

packages/x-charts/src/BarChart/BarLabel/BarLabelPlot.tsx
packages/x-charts/src/BarChart/types.ts

[charts] Remove unnecessary proptypes from internal component

---

docs/data/tree-view/rich-tree-view/headless/LogExpandedItems.tsx
docs/data/tree-view/rich-tree-view/headless/headless.md
packages/x-tree-view/src/TreeItem/TreeItem.tsx
packages/x-tree-view/src/TreeItem/TreeItem.types.ts
packages/x-tree-view/src/TreeItem/useTreeItemState.ts
packages/x-tree-view/src/hooks/useTreeItem2Utils/useTreeItem2Utils.tsx
packages/x-tree-view/src/internals/TreeViewProvider/TreeViewProvider.types.ts
packages/x-tree-view/src/internals/TreeViewProvider/useTreeViewContext.ts
packages/x-tree-view/src/internals/models/plugin.ts
packages/x-tree-view/src/internals/models/treeView.ts
packages/x-tree-view/src/internals/plugins/useTreeViewExpansion/useTreeViewExpansion.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewFocus/useTreeViewFocus.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewIcons/useTreeViewIcons.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewJSXItems/useTreeViewJSXItems.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.types.ts
packages/x-tree-view/src/useTreeItem2/useTreeItem2.ts
packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts

Internal improvements for #13388
If a function needs to execute some logic from a plugin, it can usually be done in two ways:
1. The function calls some method exposed by the plugin (this is the role of the `apiRef` in both the Tree View and the Data Grid)
2. The function calls a generic method that do not depend on the plugin and on which the plugin might be hooked (this is the role of the pre-processors on the Data Grid and of the item wrapper and enhancers on the Tree View. For now the Tree View have no concept of pre-processors because it does not require it yet).
Solution 1. is usually simpler to implement and to read, but it does not respect the separation of concern, if our function is inside a plugin A and wants to call a method of the plugin B, then we have a dependency, A …

[TreeView] Improve typing to support optional dependencies in plugins and in the item

---

packages/x-tree-view/src/TreeItem/TreeItem.test.tsx
packages/x-tree-view/src/internals/TreeViewProvider/TreeViewChildrenItemProvider.tsx
packages/x-tree-view/src/internals/utils/utils.ts

Closes https://github.com/mui/mui-x/issues/13414

[TreeView] Support `itemId` with escaping characters when using `SimpleTreeView`

---

docs/pages/x/api/date-pickers/pickers-calendar-header.json
docs/pages/x/api/date-pickers/pickers-range-calendar-header.json
docs/translations/api-docs/date-pickers/pickers-calendar-header/pickers-calendar-header.json
docs/translations/api-docs/date-pickers/pickers-range-calendar-header/pickers-range-calendar-header.json
packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.test.tsx
packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx
packages/x-date-pickers-pro/src/DesktopDateRangePicker/tests/DesktopDateRangePicker.test.tsx
packages/x-date-pickers-pro/src/PickersRangeCalendarHeader/PickersRangeCalendarHeader.tsx
packages/x-date-pickers/src/PickersCalendarHeader/PickersCalendarHeader.tsx
packages/x-date-pickers/src/PickersCalendarHeader/PickersCalendarHeader.types.ts
packages/x-date-pickers/src/internals/components/PickersArrowSwitcher/PickersArrowSwitcher.tsx
packages/x-date-pickers/src/internals/components/PickersArrowSwitcher/PickersArrowSwitcher.types.tsx

Fixes #13534
- Add `id` and `aria-labelledby` relationship to `DateRangeCalendar` same as we have for `DateCalendar`.
- Update tests to benefit from this relationship instead of accessing parent elements and relying on consistent DOM.

[DateRangePicker] Add accessible name to calendar grid

---

packages/x-charts-pro/src/ChartContainerPro/ChartContainerPro.tsx
packages/x-charts-pro/src/ChartContainerPro/index.ts
packages/x-charts-pro/src/ResponsiveChartContainerPro/ResponsiveChartContainerPro.test.tsx
packages/x-charts-pro/src/ResponsiveChartContainerPro/ResponsiveChartContainerPro.tsx
packages/x-charts-pro/src/index.ts
packages/x-charts/src/ChartContainer/ChartContainer.tsx
packages/x-charts/src/ChartContainer/useChartContainerHooks.ts
packages/x-charts/src/context/ColorProvider.tsx
packages/x-charts/src/internals/index.ts
scripts/x-charts.exports.json

- This shouldn't change any of the current behaviours
- Add `ChartContainerPro` for Zoom changes
related https://github.com/mui/mui-x/pull/13405

[charts] Prepare `ChartContainerPro` for future Zoom changes

---

packages/x-date-pickers/src/DesktopDatePicker/tests/DesktopDatePicker.test.tsx
packages/x-date-pickers/src/internals/hooks/usePicker/usePickerViews.ts

[pickers] Fix controlled `view` behavior

---

packages/x-data-grid/src/hooks/features/export/serializers/csvSerializer.ts

Fixes mui/mui-x#12945
The actual fix is to apply escaping to values other than just strings, by first converting the value to a string.
Before: https://codesandbox.io/p/sandbox/boring-wildflower-rwjz6x?file=%2Fsrc%2FDemo.tsx%3A4%2C53
After: https://codesandbox.io/p/sandbox/optimistic-rain-d8zhk8

[DataGrid] Fix CSV export escaping for non-string values

---

packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClock.tsx

Closes [#11525](https://github.com/mui/mui-x/issues/11525)

[pickers] Adds RTL verification for the time pickers default views 

---

scripts/README.md

Releasing `v6.x` locally requires `pnpm`.
Depending on the setup that might not be available (if `pnpm` is used only with `corepack`).

[core] Update release readme with `pnpm` notice

---

packages/x-tree-view/src/internals/corePlugins/useTreeViewId/useTreeViewId.types.ts

No idea why it was here :laughing: 
It's also defined in `useTreeViewFocus` (and should only be defined there)

[TreeView] Remove unused state from `useTreeViewId`

---

docs/pages/_app.js

Same as https://github.com/mui/mui-toolpad/pull/3698
Also in this one: add viewport meta tag

[docs-infra] Sync _app file with monorepo

---

packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts

[DataGrid] Fix dimensions lag issue after autosize

---

docs/data/date-pickers/adapters-locale/adapters-locale.md

Add a callout for https://github.com/mui/mui-x/issues/11853.

[docs] Add callout for `Luxon` `throwOnInvalid` support

---

packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderSortIcon.tsx

Sets the multi-sort badge `overlap` prop to `circular` - this brings the number closer to the icon, and hopefully in most cases will prevent it getting cut off as seen in the issue below.
Tested on macOS Chrome, Safari and Firefox. 
https://deploy-preview-13625--material-ui-x.netlify.app/x/react-data-grid/sorting/#multi-sorting
Fixes #13406

[DataGridPro] Fix multi-sorting indicator being cut off

---

packages/x-tree-view/src/internals/models/plugin.ts
packages/x-tree-view/src/internals/models/treeView.ts
packages/x-tree-view/src/internals/useTreeView/extractPluginParamsFromProps.ts

While working on #13520, I noticed that if a plugin had an experimental feature and one of its dependencies also had an experimental feature, then the typing broke.
The reason is that calling `MergeSignaturesProperty` on a union did not work (we ended up with `'virtualization' & 'indentationPerLevel'` instead of `'virtualization' | 'indentationPerLevel'`.
I changed the logic to instead transform the experimental features into an object inside `TreeViewPluginSignature` to keep all the merging strategies consistent.

[TreeView] Support experimental features from plugin's dependencies

---

.eslintrc.js
packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx
packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePickerLayout.tsx

Following the discussion in https://github.com/mui/mui-x/pull/13562 where valid points were raised regarding folder structure and our own conventions, it made more sense to address the actual issue in the charts codebase, where the `../internals` root is sometimes automatically imported by the IDE, which has a high probability of causing cyclic imports.
This rule be updated to prevent this issue for all packages if needed.
Main issues when using on all our packages.
```bash
"/mui-x/packages/x-data-grid/src/components/cell/GridCell.tsx"
10:39  error  Unexpected path "../../internals" imported in restricted zone  import/no-restricted-paths
"/mui-x/packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx"
23:39  error  Unexpected path "../internals" imported in restricted zone …
```

[core] Add eslint rule to restrict import from `../internals` root

---

packages/x-charts/src/ChartsAxisHighlight/ChartsAxisHighlight.tsx
packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx
packages/x-charts/src/hooks/useAxisEvents.ts
packages/x-charts/src/hooks/useScale.ts
packages/x-charts/src/internals/getSVGPoint.ts
packages/x-charts/src/internals/index.ts
packages/x-charts/src/internals/utils.ts

Some cleanup related to https://github.com/mui/mui-x/pull/13405 but moved here to make that PR cleaner

[chart] Use default values instead of non-null assertion to prevent error being thrown

---

packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx
packages/x-date-pickers/src/internals/hooks/useField/useFieldV6TextField.ts

Fixes #13620 
Related to #10399.
The present behavior and test for section clearing on Android seemed incorrect.
It doesn't work like that on Desktop.
The change aligns the section clearing behavior between Desktop and Android.
~There is still an issue on Chrome on Android with syncing the focus on a section, which has a different length placeholder than the value (i.e. full length month).~
https://github.com/mui/mui-x/assets/4941090/72bcfc89-83d7-4c64-936d-f226e1ad65fd
~Maybe because it requires an extra repaint/resize cycle. 🤷 
If you have ideas on how to solve it—I'm all ears.
P.S. Wrapping the `syncSelectionToDOM` call in a `setTimeout` fixes the issue, but introduces a delay and causes the caret to be momentarily visible.
P.P.S. The situation with the MS Swiftkey keyboard is even …

[fields] Fix section clearing behavior on Android

---

packages/x-charts/src/ChartsSurface.tsx
packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx
packages/x-charts/src/ChartsTooltip/utils.tsx
packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx
packages/x-charts/src/hooks/useAxisEvents.ts
packages/x-charts/src/hooks/useInteractionItemProps.ts

- Disable `touchActions` on mobile inside the SVG
- Move events to use `pointer` events instead of high-level `touch/mouse` for better pointer capture control.
- This allows users to move the thumb around on mobile and the tooltip updates accordingly
- Move tooltip to the `top` when we detect user is not using a mouse
- Add some extra padding between pointer and tooltip
- `const yPosition = y - (pointerType === 'touch' ? 40 - height : 0);`
- `height` is the height of the pointer itself, eg: a mouse is usually `1px`, a thumb is around `2-5px`, a touch indicator on mobile emulation is a big circle, `~30px`, this formula allows us to display somewhat decently in most common situations.
Recoding on actual mobile
https://github.com/mui/mui-x/assets/9891233/8ef47858-35c7-4c20-b95d-de8aca67d119 …

[charts] Improve charts interaction for mobile users

---

docs/data/charts/gauge/gauge.md
docs/data/charts/overview/overview.md
docs/data/data-grid/overview/overview.md
docs/data/date-pickers/date-picker/CustomizationExamplesNoSnap.js
docs/data/date-pickers/overview/overview.md
docs/data/tree-view/overview/overview.md
docs/next.config.mjs
docs/package.json
docs/src/modules/components/ChartFeaturesGrid.js
docs/src/modules/components/ChartsUsageDemo.js
docs/src/modules/components/ComponentLinkHeader.js
docs/src/modules/components/CustomizationPlayground.tsx
docs/src/modules/components/InstallationGrid.js
docs/src/modules/components/InterfaceApiPage.js
pnpm-lock.yaml
scripts/buildApiDocs/tsconfig.json
tsconfig.json

- Cleanup remaining usages of imports that can be replaced with `@mui/docs`
- Use `@mui/docs` from npm (as a dep) instead of aliasing `monorepo`

[code-infra] Cleanup monorepo and `@mui/docs` usage

---

packages/x-data-grid/src/DataGrid/useDataGridProps.ts
packages/x-data-grid/src/tests/DataGrid.test.tsx
packages/x-data-grid/src/tests/pagination.DataGrid.test.tsx

closes: https://github.com/mui/mui-x/issues/13330
preview: https://deploy-preview-13349--material-ui-x.netlify.app/x/react-data-grid/pagination/
check this https://github.com/mui/mui-x/pull/13349#discussion_r1623490501 dicussion  for more context on implementaion of logic
after applying fix:

[DataGrid] Fix pagination when `pagination={undefined}`

---

packages/x-codemod/package.json
pnpm-lock.yaml

Drop the package as it does not look to be used and is potentially mistakenly introduced when creating the package. 🙈 
For reference usages in material-ui: https://github.com/mui/material-ui/blob/9f8e4f5d828bfe0e1692e1336eff57da7168b68b/packages/mui-codemod/src/v4.0.0/optimal-imports.js#L2

[core] Remove `jscodeshift-add-imports` package

---

docs/data/data-grid/recipes-row-grouping/RowGroupingChildRowCount.js
docs/data/data-grid/recipes-row-grouping/RowGroupingChildRowCount.tsx
docs/data/data-grid/recipes-row-grouping/RowGroupingChildRowCount.tsx.preview
docs/data/data-grid/recipes-row-grouping/recipes-row-grouping.md
docs/pages/x/api/data-grid/selectors.json
packages/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts
scripts/x-data-grid-premium.exports.json
scripts/x-data-grid-pro.exports.json
scripts/x-data-grid.exports.json

Users are looking to display the child row count when they have grouped rows.
Fixes #13638
- Adds two new selectors:
```json
{
"name": "gridFilteredDescendantRowCountSelector",
"returnType": "number",
"category": "Filtering",
"description": "Get the amount of descendant rows accessible after the filtering process.",
"supportsApiRef": true
},
{
"name": "gridFilteredRowCountSelector",
"returnType": "number",
"category": "Filtering",
"description": "Get the amount of rows accessible after the filtering process.\nIncludes top level and descendant rows.",
"supportsApiRef": true
},
```
- Adds example of showing child row count in footer to the row grouping recipes https://deploy-preview-13725--material-ui-x.netlify.app/x/react-data-grid/recipes-row-grouping/#dispaying-child-row-count-in-footer

[data grid] Add selectors to support showing child row count in footer

---

packages/x-date-pickers-pro/src/DesktopDateTimeRangePicker/DesktopDateTimeRangePicker.tsx
packages/x-date-pickers-pro/src/MobileDateTimeRangePicker/MobileDateTimeRangePicker.tsx
packages/x-date-pickers/src/internals/index.ts
packages/x-date-pickers/src/internals/utils/date-time-utils.ts

I noticed this problem while working on https://github.com/mui/mui-x/pull/13742.
The `DateTimeRangePicker` components were not resolving format from the given `views`, thus providing `['day', 'hours', 'minutes', 'seconds']` would trigger an error after minutes selection in the Picker view.

[DateTimeRangePicker] Resolve `format` from given `views`

---

docs/src/modules/components/PickersPlayground.tsx

Fixes #13736.
Also add `DateTimeRangePicker` into this playground.

[docs] Fix Pickers customization playground overflow

---

docs/pages/x/api/data-grid/grid-actions-col-def.json
docs/pages/x/api/data-grid/grid-api.json
docs/pages/x/api/data-grid/grid-col-def.json
docs/pages/x/api/data-grid/grid-row-selection-api.json
docs/pages/x/api/data-grid/grid-single-select-col-def.json
packages/x-data-grid/src/models/api/gridRowSelectionApi.ts
packages/x-data-grid/src/models/colDef/gridColDef.ts
packages/x-data-grid/src/models/gridRowSelectionModel.ts

[DataGrid] Use `readonly` on more array props

---

packages/x-date-pickers-pro/src/PickersRangeCalendarHeader/PickersRangeCalendarHeader.tsx

Fixes https://github.com/mui/mui-x/issues/13774.

[DateRangePicker] Fix `calendarHeader` slot props propagation

---

packages/x-charts/src/LineChart/AreaPlot.tsx
packages/x-charts/src/LineChart/extremums.ts

Fix #13759
The issue codesandbox with the fix https://codesandbox.io/s/quirky-meadow-glcdvy?file=/src/Demo.tsx
@JCQuintas The idea is to use the axis scale to replace the base value if out of range (the scale returns a NaN) I assume it will be impacted by zoom in a sens that we will need to refine the replacement value to be compatible

[charts] Fix area with log scale

---

packages/x-data-grid/src/components/containers/GridRoot.tsx
packages/x-data-grid/src/components/virtualization/GridMainContainer.tsx
packages/x-data-grid/src/components/virtualization/GridTopContainer.tsx

Closes: https://github.com/mui/mui-x/issues/13442
Preview: https://deploy-preview-13474--material-ui-x.netlify.app/x/react-data-grid/#premium-plan

[DataGrid] Fix incorrect panels position when using a toolbar

---

packages/x-date-pickers/src/internals/hooks/useField/useFieldV6TextField.ts

Follow-up on https://github.com/mui/mui-x/pull/13652.
This prevents the following case from triggering a recursion:
https://github.com/mui/mui-x/assets/4941090/ed57a064-adb3-41e9-bd8e-2c48237ca267

[fields] Prevent infinite recursion when ensuring selection

---

docs/data/tree-view/rich-tree-view/items/ApiMethodGetItemOrderedChildrenIds.js
docs/data/tree-view/rich-tree-view/items/ApiMethodGetItemOrderedChildrenIds.tsx
docs/data/tree-view/rich-tree-view/items/ApiMethodGetItemOrderedChildrenIds.tsx.preview
docs/data/tree-view/rich-tree-view/items/ApiMethodGetItemTree.js
docs/data/tree-view/rich-tree-view/items/ApiMethodGetItemTree.tsx
docs/data/tree-view/rich-tree-view/items/ApiMethodGetItemTree.tsx.preview
docs/data/tree-view/rich-tree-view/items/items.md
docs/pages/x/api/tree-view/rich-tree-view.json
docs/pages/x/api/tree-view/simple-tree-view.json
docs/pages/x/api/tree-view/tree-view.json
packages/x-tree-view/src/RichTreeView/RichTreeView.tsx
packages/x-tree-view/src/SimpleTreeView/SimpleTreeView.tsx
packages/x-tree-view/src/TreeView/TreeView.tsx
packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.test.tsx
packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.tsx
packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.types.ts
test/utils/tree-view/fakeContextValue.ts

Extracted from #12213
Used in #13388

[TreeView] Add `getItemTree` and `getItemOrderedChildrenIds` methods to the public API

---

packages/x-data-grid/src/components/panel/GridPanel.tsx

Closes https://github.com/mui/mui-x/issues/13473
Enable flip on the grid panel, as described in https://github.com/mui/mui-x/issues/13473#issuecomment-2168022198.
Before: https://codesandbox.io/p/sandbox/kind-roman-jqt8hy
After: https://codesandbox.io/p/sandbox/serene-cookies-p8ffrf

[DataGrid] Fix: enable flip on preferences panel

---

renovate.json

Implement https://github.com/mui/mui-x/pull/13760#discussion_r1668577151 suggestion as renovate still wants to bump to the incorrect version: https://github.com/mui/mui-x/pull/13746. 🙈

[code-infra] Follow `next` tag for `@mui/docs` package bumps

---

docs/src/modules/components/ChartsUsageDemo.js
docs/src/modules/components/DemoPropsForm.tsx

- Make `ChartDemoPropsForm` only work in controlled mode. Controller is now `ChartsUsageDemo`
- This allows us to pass the `onChange` handler to the render function, which allows children(examples) to change the knobs from their own logic 
- Useful on zoom to prevent throwing errors, we can check if prop.start > prop.end and update the knobs accordingly. 
- Cleaned up typing a and logic (removed undefined knob logic)
- Added `slider` component
For testing the slider locally.
```tsx
import Box from '@mui/material/Box';
import ChartsUsageDemo from 'docsx/src/modules/components/ChartsUsageDemo';
import { ScatterChart } from '@mui/x-charts/ScatterChart';
import { Chance } from 'chance';
const chance = new Chance(42);
const data = Array.from({ length: 200 }, () …
```

[charts] Allow controlling the demo form from the example

---

packages/x-charts-pro/src/ChartContainerPro/ChartContainerPro.tsx
packages/x-charts-pro/src/context/CartesianProviderPro/CartesianProviderPro.tsx
packages/x-charts-pro/src/context/ZoomProvider/Zoom.types.ts
packages/x-charts-pro/src/context/ZoomProvider/ZoomProvider.tsx
packages/x-charts-pro/src/context/ZoomProvider/defaultizeZoom.ts
packages/x-charts/src/ChartContainer/ChartContainer.tsx
packages/x-charts/src/ChartContainer/useChartContainerProps.ts
packages/x-charts/src/ChartContainer/useDefaultizeAxis.ts
packages/x-charts/src/context/CartesianProvider/CartesianProvider.tsx
packages/x-charts/src/context/CartesianProvider/computeValue.ts
packages/x-charts/src/context/CartesianProvider/index.ts
packages/x-charts/src/context/CartesianProvider/normalizeAxis.ts

Refer to: https://github.com/mui/mui-x/pull/13726#discussion_r1672564512

[charts] Defaultize axis on top level `useChartContainerProps` 

---

packages/x-charts-pro/src/LineChartPro/LineChartPro.tsx
packages/x-charts-pro/src/context/ZoomProvider/useSetupZoom.ts

Remove the animations while zooming the chart.

[charts] Disable animations while zooming

---

docs/data/date-pickers/date-picker/ClearableProp.js
docs/data/date-pickers/date-picker/ClearableProp.tsx
docs/data/date-pickers/date-picker/date-picker.md

The clearable behavior of date picker [was not tested and not implemented for mobile](https://github.com/mui/mui-x/issues/10842#issuecomment-1870298882). This PR updates the docs to clarify that only desktop, not mobile date picker variants are supported.

[docs] Clarify Pickers clearable behavior not working on mobile

---

packages/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx
packages/x-data-grid/src/tests/filterPanel.DataGrid.test.tsx

Closes: https://github.com/mui/mui-x/issues/13280

[DataGrid] Fix delete filter inconsistent behavior

---

packages/x-date-pickers-pro/src/DesktopDateRangePicker/tests/DesktopDateRangePicker.test.tsx
packages/x-date-pickers-pro/src/MobileDateRangePicker/tests/MobileDateRangePicker.test.tsx
packages/x-date-pickers-pro/src/internals/hooks/useDesktopRangePicker/useDesktopRangePicker.tsx
packages/x-date-pickers-pro/src/internals/hooks/useMobileRangePicker/useMobileRangePicker.tsx

Fixes #13818.
It applies to `DateTimeRangePicker` as well, but tagging only want to propagate the entry to a correct `changelog` entry.

[DateRangePicker] Fix `name` prop propagation regression

---

renovate.json

Fix a regression introduced by https://github.com/mui/mui-x/pull/13813.
It is missing the package matching:

[core] Fix `renovate` config

---

packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx

- Ensured the `columnResizeStop` event is emitted when the column resizer is clicked but not moved.
Closes: https://github.com/mui/mui-x/issues/13178

[DataGrid] Fix `columnResizeStop` event not emitted when column is not resized

---

packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputMultipleValue.tsx

When using `type = date` or `type = datetime-local` the prop types on `GridFilterInputMultipleValue` produce an error despite actually working perfectly fine given that this component (by default) just uses a native input.
This change is also consistent with how [GridFilterInputValue](https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputValue.tsx#L12) handles this property's typing (except there's no enum enforcement in the prop types over there, for some reason).
Please do let me know if I missed something, the change in the prop-types/types seemed trivial enough to do by hand, but if I must clone this and and run `pnpm prototype` to have the codegen do it for me I can, I had just chosen to take the easy way and directly edited …

[DataGrid] Support `date` and `datetime-local` input types in `GridFilterInputMultipleValue` type

---

packages/x-date-pickers/src/TimeClock/Clock.tsx
packages/x-date-pickers/src/TimeClock/clockClasses.ts

Fixes #12493.
Additional changes:
- ~Refactor active/selected styles to depend on the `Mui-selected` class rather than using a `variant`~. Can't do it now, because it's a possible BC: https://github.com/mui/mui-x/pull/13848#discussion_r1678801329
- Extract common meridiem button styles into a reusable function
P.S. I picked this up after I saw an old stash with partially complete work. 🙈

[TimePicker] Add `Mui-selected` class to `TimeClock` meridiem buttons

---

renovate.json

- Add `@mui/joy` back to the `MUI Core` group
- Removed in https://github.com/mui/mui-x/pull/13000
I forgot to add it back with https://github.com/mui/mui-x/pull/13741
- Add `@mui/types` to the `MUI Core` group as per: https://github.com/mui/mui-x/pull/13846#discussion_r1677770842
I've noticed that the internal packages are being released frequently and they trigger a lot of CI runtime even for these packages.
Grouping them together should reduce the CI effort.
Seeing the below case was the final "ding-ding" moment:
When we have separate bump PR: https://github.com/mui/mui-x/pull/13830.
WDYT @mui/code-infra, should we add `@mui/docs` to this group or `MUI Core`?
https://github.com/mui/mui-x/blob/29aeeb83613ea76b4b366ad3bbf18641da084412/renovate.json#L82-L91

[core] Add MUI Internal `renovate` group

---

docs/pages/x/api/charts/gauge.json
packages/x-charts/src/BarChart/BarChart.test.tsx
packages/x-charts/src/ChartContainer/ChartContainer.test.tsx
packages/x-charts/src/ChartContainer/useChartContainerProps.ts
packages/x-charts/src/Gauge/Gauge.test.tsx
packages/x-charts/src/LineChart/LineChart.test.tsx
packages/x-charts/src/LineChart/useLineChartProps.ts
packages/x-charts/src/PieChart/PieChart.test.tsx
packages/x-charts/src/PieChart/PieChart.tsx
packages/x-charts/src/ResponsiveChartContainer/ResponsiveChartContainer.test.tsx
packages/x-charts/src/ResponsiveChartContainer/useResponsiveChartContainerProps.ts
packages/x-charts/src/ScatterChart/ScatterChart.test.tsx
packages/x-charts/src/ScatterChart/useScatterChartProps.ts
packages/x-charts/src/SparkLineChart/SparkLineChart.test.tsx
packages/x-charts/src/SparkLineChart/SparkLineChart.tsx
packages/x-charts/src/context/HighlightedProvider/HighlightedProvider.tsx

[core] Normalize `...other` and test imports in charts

---

packages/x-tree-view/src/internals/useTreeView/useTreeView.ts
packages/x-tree-view/src/internals/useTreeView/useTreeViewBuildContext.ts

I tried to improve the readability of the `useTreeVIew` hook which is quite complex

[TreeView] Extract some logic outside of the `useTreeView` hook

---

docs/pages/x/api/data-grid/selectors.json
packages/x-data-grid/src/hooks/features/editing/gridEditingSelectors.ts
packages/x-data-grid/src/hooks/features/editing/index.ts
packages/x-data-grid/src/hooks/features/index.ts
scripts/x-data-grid-premium.exports.json
scripts/x-data-grid-pro.exports.json
scripts/x-data-grid.exports.json

Closes https://github.com/mui/mui-x/issues/11133
Make the selector public again.

[DataGrid] Expose `gridEditRowsStateSelector`

---

packages/x-charts-pro/src/BarChartPro/BarChartPro.tsx
packages/x-charts-pro/src/LineChartPro/LineChartPro.tsx
packages/x-charts-pro/src/context/ZoomProvider/useSetupPan.ts
packages/x-charts-pro/src/context/ZoomProvider/useSetupZoom.ts
packages/x-charts/src/BarChart/BarChart.tsx
packages/x-charts/src/ChartsLegend/DefaultChartsLegend.tsx
packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx
packages/x-charts/src/LineChart/LineChart.tsx
packages/x-charts/src/LineChart/LineHighlightPlot.tsx
packages/x-charts/src/LineChart/MarkPlot.tsx
packages/x-charts/src/ScatterChart/Scatter.tsx
packages/x-charts/src/context/DrawingProvider.tsx
packages/x-charts/src/hooks/useAxisEvents.ts
packages/x-charts/src/hooks/useDrawingArea.ts

- `BarChart`
- **highlight**: Move the highlight component inside the clip group
- **tooltip**: No change needed, as when the bars are fully outside the tooltip doesn't trigger.
- `LineChart` 
- **highlight**: Move the highlight component inside the clip group
- **tooltip**: Left as is. When you are zoomed in you might still want to see the value of what is outside
- `ScatterChart`
- **highlight**: none
- **tooltip**: Changed the voronoi/delauney to only consider the points inside render area

[charts] Improve zoomed highlight behaviour

---

packages/x-data-grid-premium/src/DataGridPremium/DataGrid.tsx
packages/x-data-grid-pro/src/DataGridPro/DataGrid.tsx

From https://discord.com/channels/1131323012554174485/1131329358062178324/1259822217475260447, it feels like the current error messages are confusing.
```jsx
import { DataGridPremium } from "@mui/x-data-grid-pro";
```
Before
After

[docs] Improve error message when moving between plans

---

packages/x-charts/src/PieChart/PieArc.tsx

Fix #13887
To test
```jsx
import * as React from "react";
import { PieChart } from "@mui/x-charts/PieChart";
const data = [
{ id: 0, value: 0, label: "series A" },
{ id: 1, value: 15, label: "series B" },
{ id: 2, value: 0, label: "series C" },
];
export default function PieActiveArc() {
return (
<PieChart
series={[
{
data,
highlightScope: { faded: "global", highlighted: "item" },
faded: { innerRadius: 30, additionalRadius: -30, color: "gray" },
},
]}
height={200}
/>
);
}
```

[charts] hide empty arcs in the PieChart

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/deDE.ts

This PR adds the missing translation for the German (de-DE) locale - https://github.com/mui/mui-x/issues/3211.

[l10n] Improve German (de-DE) locale

---

docs/data/tree-view/rich-tree-view/items/ApiMethodGetItemDOMElement.js
docs/data/tree-view/rich-tree-view/items/ApiMethodGetItemDOMElement.tsx
docs/data/tree-view/simple-tree-view/items/ApiMethodGetItemDOMElement.js
docs/data/tree-view/simple-tree-view/items/ApiMethodGetItemDOMElement.tsx

I got confused playing with the demo of https://mui.com/x/react-tree-view/simple-tree-view/items/#imperative-api. I clicked on the button and got lost, it took me to click 2 more times on the button to understand this demo.
Before
https://github.com/user-attachments/assets/e46403cf-5cec-404b-a3b2-61a084c250a8
After
https://github.com/user-attachments/assets/84db071e-cbba-4db8-8abb-04d2cc1002c7
---
**Off-topic**. @samuelsycamore I think this could be a small example of work / responsibility we could envision to structure to "Docs" team to grow around, meaning to be accountable for the end-to-end experience of the docs.

[tree view][docs] Fix scroll demos disorientation

---

packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx
packages/x-date-pickers/src/internals/hooks/useField/useField.ts
packages/x-date-pickers/src/internals/hooks/useField/useFieldV6TextField.ts
packages/x-date-pickers/src/internals/hooks/useField/useFieldV7TextField.ts
test/utils/pickers/fields.tsx

Closes [#13387](https://github.com/mui/mui-x/issues/13387)

[fields] Prevent keyboard editing when disabled

---

packages/x-data-grid/src/components/panel/GridPreferencesPanel.tsx

props and ref are not used anywhere, so its safe to remove them
A leftover from #11228.

[data grid] Remove dead code in internal GridPreferencesPanel

---

.github/ISSUE_TEMPLATE/1.bug.yml
.github/ISSUE_TEMPLATE/2.feature.yml
.github/ISSUE_TEMPLATE/3.pro-support.yml
.github/ISSUE_TEMPLATE/4.premium-support.yml
.github/ISSUE_TEMPLATE/5.priority-support.yml
.github/workflows/issue-cleanup.yml

---
This change adds 2 things:
1. a selection to the issue template to determine which products are affected
2. an addition to the cleanup action that labels the issue based on the selection
As a side effect I did add some labels based on the type of issue created
- Bug issue => labels 'bug 🐛'
- Feature request => labels 'new feature'
- etc

[infra] Issue template improvement

---

docs/data/charts/sparkline/sparkline.md

Fixing capitalization error
- [~x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

[docs] Update `SparkLineChart` reference not being correctly capitalised

---

packages/x-charts/src/BarChart/BarElement.tsx
packages/x-charts/src/BarChart/BarLabel/BarLabelItem.tsx
packages/x-charts/src/ChartsOverlay/ChartsOverlay.tsx
packages/x-charts/src/LineChart/AreaElement.tsx
packages/x-charts/src/LineChart/LineElement.tsx
packages/x-charts/src/LineChart/LineHighlightPlot.tsx
packages/x-charts/src/internals/SlotComponentPropsFromProps.ts

Part of #13907
I looked for components that uses `useSlotsProps` with a non-empty `ownerState` param
I picked the typing from the pickers. Might be a candidate for the `x-internal` package

[charts] Add `ownerState` function to `slotProps` typing when available

---

packages/x-data-grid-premium/src/DataGridPremium/useDataGridPremiumProps.ts
packages/x-data-grid/src/hooks/core/useGridApiInitialization.ts
packages/x-data-grid/src/hooks/utils/useGridApiEventHandler.ts

The code would only send it with Pro which would be a regression for clients switching from Pro to Premium.

[DataGrid] Also send the API with events in Premium

---

.github/workflows/vale-action.yml

Revert the `paths` filter, because it skips the action and [keeps that item in a pending state](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore). 🙈
> If a workflow is skipped due to path filtering, [branch filtering](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore), or a [commit message](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs), then checks associated with that workflow will remain in a "Pending" state. A pull request that requires those checks to be successful will be blocked from merging.
We already have a filter to run `vale` only on `docs/data`, it should be …

[infra] Revert `vale` action `paths` filtering

---

CHANGELOG.md
docs/data/data-grid/overlays/overlays.md
docs/data/data-grid/server-side-data/index.md
packages/x-internals/README.md

Those errors can be seen by running
`vale sync && git ls-files | grep -h ".md$" | xargs vale --filter='.Level=="error"'`
It's not in the CI yet because we share the config with the monorepo HEAD, which could mean breaking the CI in MUI X as soon as a PR is merged in the monorepo.
https://github.com/mui/mui-x/blob/c8845a254adff01c2799a3cc991345c7ea04cfe7/.vale.ini#L10
We will need to change this.

[docs] Fix Vale errors

---

packages/x-data-grid/src/internals/utils/useProps.ts

Noticed this while working on https://github.com/mui/mui-x/issues/10033 and https://github.com/mui/material-ui/pull/43120.
We are making a copy to pass to the function, but the callee never mutates its argument (like basically all functions in our codebase) so there is no need to copy.

[DataGrid] Refactor: remove useless copy

---

packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts
packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.types.ts

Based on @LukasTy review on #12213

[TreeView] Fix env check for drag and drop warning

---

docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md
packages/x-data-grid/src/components/GridHeaders.tsx
packages/x-data-grid/src/hooks/core/useGridRefs.ts
packages/x-data-grid/src/hooks/features/scroll/useGridScroll.ts
packages/x-data-grid/src/models/api/gridCoreApi.ts

Closes https://github.com/mui/mui-x/issues/13811
Tests Pass in Demo with PR preview package:
https://codesandbox.io/p/devbox/github/samwato/codesandbox/tree/main/mui-x-issue-13811?file=%2Fsrc%2FDemo.test.tsx%3A12%2C1

[DataGrid] Fix `columnHeadersContainerRef` being `undefined` before mount

---

packages/x-charts-vendor/.npmignore
packages/x-charts-vendor/package.json

Publish config is necessary for publishing, it is blocked otherwise.
The `.npmignore` changes doesn't seem necessary (current 7.12.0) was released without those but seem to work correctly. Added them for sake of completeness.

[charts] Fix charts vendor publish config

---

docs/pages/x/react-tree-view/rich-tree-view/ordering.js

I saw this from https://github.com/mui/mui-x/releases/tag/v7.12.0
https://mui.com/x/react-tree-view/rich-tree-view/ordering/

[docs] Disable ad in `Rich Tree View-Ordering` page

---

docs/data/data-grid/row-updates/row-updates.md

Doubling down on the usage of `updateRows` API method due to multiple inquiries in this regard.
The most recent one: https://github.com/mui/mui-x/issues/13962

[docs] Add a warning to promote the usage of `updateRows`

---

scripts/githubActions/issueBodyCleanup.js

Fixes the issue cleanup script. Fix regression from https://github.com/mui/mui-x/pull/14031#issuecomment-2271034876.

[infra] Re-added the removal of `Latest Version` section

---

packages/x-tree-view-pro/package.json
pnpm-lock.yaml

Fix #14147
Try to run `pnpm install @mui/x-tree-view-pro` you will see in your `node_modules` that it's not the correct folder that is added if you compare with the data grid ones :)

[tree-view] Fix the `@mui/x-tree-view-pro` published folder

---

docs/translations/api-docs/tree-view/rich-tree-view-pro/rich-tree-view-pro.json
packages/x-tree-view-pro/src/RichTreeViewPro/RichTreeViewPro.tsx
packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.test.tsx
packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts
packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.types.ts
packages/x-tree-view/src/internals/models/plugin.ts

[TreeView] Fix the parameters passed for the `canMoveItemToNewPosition` prop

---

packages/x-date-pickers/src/DateCalendar/tests/DateCalendar.test.tsx
packages/x-date-pickers/src/internals/utils/date-utils.test.ts
packages/x-date-pickers/src/internals/utils/date-utils.ts

Fixes tests for some reason only failing with `mui@material` v6 seen in https://github.com/mui/mui-x/pull/14142.
- The util had missing `milliseconds` retaining.
- A test was incorrect and not testing anything. 🤷 🙈

[pickers] Fix date and time merging to retain milliseconds

---

netlify.toml

Closes https://github.com/mui/mui-x/pull/14104
Netlify docs say the [`--shamefully-hoist ` flag is required for Next.js + pnpm setup](https://docs.netlify.com/frameworks/next-js/overview/#pnpm-support), but as pointed out by @Janpot this guide doesn't apply to us since we build+export and just host a static site.

[core] Fix Netlify build cache issue

---

packages/x-charts/src/ChartsTooltip/utils.tsx

Fix #14157
The other option would be to use the `touchend`

[charts] Do not remove mouse position for mouseUp event

---

packages/x-data-grid/src/hooks/features/export/serializers/csvSerializer.ts
packages/x-data-grid/src/tests/export.DataGrid.test.tsx

Fixes #14082
this issue comes from the changes done in #13560 , the motive of that PR is to  convert any non-string value into a string using template literals but it also converts `null` and `undefined` values into strings which then exported to CSV as a string.
I have added a check for these values.

[data grid] Fix CSV export for `null` and `undefined` values

---

packages/x-data-grid/src/hooks/core/useGridStateInitialization.ts

`publishEvent` is always available during grid state initialization (because we are adding it in API synchronously before state initialization) so there is no need to check that.

[DataGrid] remove needless check in `useGridStateInitialization`

---

docs/data/data-grid/filtering-recipes/FilteringLocalStorage.js
docs/data/data-grid/filtering-recipes/FilteringLocalStorage.tsx
docs/data/data-grid/filtering-recipes/FilteringLocalStorage.tsx.preview
docs/data/data-grid/filtering-recipes/filtering-recipes.md

Closes https://github.com/mui/mui-x/issues/14206
Preview: https://deploy-preview-14208--material-ui-x.netlify.app/x/react-data-grid/filtering-recipes/#persisting-filters-in-local-storage

[DataGrid] Add recipe for persisting filters in local storage

---

SECURITY.md
docs/data/introduction/support/support.md

I have noticed this from https://github.com/mui/mui-x/issues/new/choose, it leads to https://github.com/mui/mui-x/security/policy.
I was confused: What about v7?
---
On the policy itself we should use for LTS, I think that we can't keep the same policy as before. We used to support the last two majors, but this was from a time when we would release a major every year or two. We moved to a faster release frequency. I suspect that we want to cover 2 years, in between Node.js and Angular: https://www.notion.so/mui-org/sales-Paid-LTS-11b1534f8ed940d29d8b4464be6bf264?pvs=4#340d90259efd4e2abf0f4ea8e2f924d8.

[docs] Fix outdated SECURITY.md page

---

docs/data/data-grid/pagination/CursorPaginationGrid.js
docs/data/data-grid/pagination/CursorPaginationGrid.tsx
docs/data/data-grid/server-side-data/ServerSideErrorHandling.js
docs/data/data-grid/server-side-data/ServerSideErrorHandling.tsx
docs/data/data-grid/server-side-data/ServerSideTreeDataErrorHandling.js
docs/data/data-grid/server-side-data/ServerSideTreeDataErrorHandling.tsx
docs/src/modules/components/CustomizationPlayground.tsx

This is a general guideline we have in the codebase, we avoid variable abbreviations so noobies can better understand what variable they are manipulating. Now, there is also value in having this always the same it's more intuitive.
I have noticed this from this tweet: https://x.com/ericclemmons/status/1823108565285941266, which could suggest that we should have TanStack Query integration demos. Issue created: #14227.

[docs] Remove relience of abbreviations

---

packages/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx
packages/x-data-grid/src/components/menu/columnMenu/GridColumnMenuContainer.tsx
packages/x-data-grid/src/components/panel/GridPanel.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarDensitySelector.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarExportContainer.tsx
packages/x-data-grid/src/utils/keyboardUtils.ts

A little cleanup PR
we are already using `event.key` everywhere for different keys so why not for `Tab` and`Escape` keys ?

[data grid] use `event.key`  for `Tab` and `Escape` keys

---

docs/data/date-pickers/localization/data.json
packages/x-date-pickers/src/locales/viVN.ts

Preview: https://deploy-preview-14238--material-ui-x.netlify.app/

[l10n] Improve Vietnamese (vi-VN) locale

---

docs/data/date-pickers/localization/data.json
packages/x-date-pickers/src/locales/zhHK.ts

[l10n] Improve Chinese (zh-HK) locale

---

docs/src/modules/components/overview/CommunityOrPro.tsx
docs/src/modules/components/overview/InfoCard.tsx
docs/src/modules/components/overview/Internationalization.tsx
docs/src/modules/components/overview/Keyboard.tsx

I first saw this in https://app.ahrefs.com/site-audit/3992793/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CredirectChainUrls%2CisRedirectLoop%2CincomingAllLinks%2CincomingRedirect%2Corigin&current=16-08-2024T023256&filterId=808b08e88c934ee19e04fdec4ed87a5a&issueId=c64d12c1-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating
we link to "/pricing" but should be "/pricing/". Now, since this page gets versioned, e.g. https://v6.mui.com/x/react-date-pickers/ we can't use a relative URL, we have to use an absolute one, so https://mui.com/pricing/ in the end.
I opened a PR as it seemed equivalent to leaving the feedback.

[docs] Fix missing leading slashes in URLs

---

packages/x-charts/src/ChartsXAxis/ChartsXAxis.tsx
packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx
packages/x-charts/src/context/DrawingProvider.tsx
packages/x-charts/src/hooks/useAxisEvents.ts

- This normalises the code to use the same logic in both instances. 
- It also fixes an issue where the axis would show before the datapoint, even though the were displayed in the same line.
```tsx
import { ScatterChartPro, ZoomData } from '@mui/x-charts-pro';
export default function AreaBaseline() {
const [scatterZoom, setScatterZoom] = React.useState<ZoomData[]>([
{ axisId: 'b11', start: 11, end: 49 },
]);
return (
<ScatterChartPro
xAxis={[{ id: 'b11', zoom: true }]}
series={[
{
data: [
{ id: 0, x: 1, y: 100 },
{ id: 2, x: 5, y: 200 },
{ id: 3, x: 10, y: 300 },
{ id: 4, x: 15, y: 400 },
{ id: 5, x: 20, y: 500 },
],
},
]}
zoom={scatterZoom}
onZoomChange={setScatterZoom}
width={500}
height={300}
leftAxis={{}}
rightAxis={{}}
topAxis={{}}
bottomAxis={{}}
/> …
```

Use `isPointInside` function for both graphs and axis

---

changelogOld/CHANGELOG.v6.md
docs/data/date-pickers/timezone/timezone.md
docs/data/pages.ts

I was initially confused to not see the same thing between sidenav and h1
and went on to update the other instances.

[docs] Consistent use of UTC and timezones

---

packages/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts
packages/x-data-grid-premium/src/tests/clipboard.DataGridPremium.test.tsx

Fixes #14233 
- Before: https://codesandbox.io/p/sandbox/divine-wildflower-w6mqqg
- After: https://codesandbox.io/p/sandbox/competent-lalande-gmcp8j
Similar to https://github.com/mui/mui-x/pull/14083

[DataGridPremium] Clipboard paste not working for a single cell if the current page is not the first page

---

docs/data/date-pickers/adapters-locale/adapters-locale.md
docs/data/date-pickers/custom-components/custom-components.md
docs/data/date-pickers/getting-started/getting-started.md
docs/data/date-pickers/validation/validation.md

The usage of some dashes in the pickers docs seemed gramatically incorrect. This PR intends to improve it.

[docs][pickers] Dash usage revision

---

packages/x-charts/src/BarChart/BarPlot.tsx

Improve performances by removing the bar masks if the bar border-radius is not used
Plus it validate that codespeed is working correctly :)

[charts] Improve bar chart performances

---

packages/x-charts/src/ChartsGrid/ChartsGrid.tsx

Just found that while working on performances

[charts] Fix grid overflow with zooming

---

packages/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts
packages/x-data-grid-premium/src/tests/cellSelection.DataGridPremium.test.tsx

Fixes #14184 
Another reference is needed to detect the state change and trigger the event

[DataGridPremium] Fix `onCellSelectionModelChange` not triggered when additional cell range is selected

---

packages/x-data-grid-pro/src/models/dataGridProProps.ts
packages/x-data-grid-pro/src/tests/treeData.DataGridPro.test.tsx

We do not try to modify the array after receiving it, so let's accept an immutable array. This is still compatible with existing usage of getTreeDataPath.

[data grid] Use readonly array result for getTreeDataPath

---

packages/x-data-grid-pro/src/components/GridDataSourceTreeDataGroupingCell.tsx
packages/x-data-grid-pro/src/hooks/features/dataSource/gridDataSourceSelector.ts
packages/x-data-grid/src/hooks/utils/useGridSelector.ts
packages/x-data-grid/src/internals/index.ts
packages/x-data-grid/src/utils/createSelector.ts

Extracted from https://github.com/mui/mui-x/pull/13757/
Related discussion: https://github.com/mui/mui-x/pull/13757/files#r1686750062
- Add new v8 variants of `useGridSelector`, `createSelector`, and `createSelectorMemoized` named as `useGridSelectorV8`, `createSelectorV8`, and `createSelectorMemoizedV8`. Selectors created with `createSelectorV8` or `createSelectorMemoizedV8` must be used with `useGridSelectorV8` for them to work properly. These new variants will replace the existing props in v8.

[DataGrid] Introduce selectors with arguments

---

docs/pages/playground/tsconfig.json

I use `playground/components` for some reusable testing components, and they are full of red squiggly lines. NO MORE!

[code-infra] Typecheck nested folders in playground

---

docs/data/data-grid/row-height/ExpandableCells.js
docs/data/data-grid/row-height/ExpandableCells.tsx
docs/data/date-pickers/custom-field/BrowserV6Field.js
docs/data/date-pickers/custom-field/BrowserV6Field.tsx
docs/data/date-pickers/custom-field/BrowserV6SingleInputRangeField.js
docs/data/date-pickers/custom-field/BrowserV6SingleInputRangeField.tsx
docs/data/date-pickers/custom-field/BrowserV7Field.js
docs/data/date-pickers/custom-field/BrowserV7Field.tsx
docs/data/date-pickers/custom-field/BrowserV7SingleInputRangeField.js
docs/data/date-pickers/custom-field/BrowserV7SingleInputRangeField.tsx

Extracted from https://github.com/mui/mui-x/pull/14142
When running visual regression tests with `@mui/material@6` we had 5 demos with visual diffs: https://app.argos-ci.com/mui/mui-x/builds/23408
This PR applies styles to ensure that these 5 demos have no visual differences between `@mui/material@5` and `@mui/material@6`.
The goal is to avoid manually checking the screenshots for false negatives.

[core] Avoid visual regression when using `@mui/material@6`

---

renovate.json

Closes https://github.com/mui/mui-x/pull/14363.
While and if we stick to using `v5.x` to avoid the noise from renovate. 👍

[core] Allow only v5.x for `MUI Core` renovate group

---

packages/x-date-pickers-pro/src/DesktopDateTimeRangePicker/DesktopDateTimeRangePicker.tsx
packages/x-date-pickers-pro/src/MobileDateTimeRangePicker/MobileDateTimeRangePicker.tsx
packages/x-date-pickers/src/internals/utils/date-time-utils.ts
packages/x-date-pickers/src/internals/utils/date-utils.ts

Fixes #14334.
For `DateTimeRangePickers` the ["day"] case returns an incorrect format.

[DateTimeRangePicker] Fix date format resolving from views on 24hr locales

---

packages/x-date-pickers/src/TimeClock/Clock.tsx
packages/x-date-pickers/src/TimeClock/tests/TimeClock.test.tsx

[pickers] Add `onTouchStart` handler for `TimeClock`

---

packages/x-data-grid/src/components/GridScrollbarFillerCell.tsx
packages/x-data-grid/src/components/containers/GridRootStyles.ts
packages/x-data-grid/src/constants/gridClasses.ts
packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx

Spotted while working on #14373 
| --- | --- |
| ![image](https://github.com/user-attachments/assets/5df35892-c3ca-49d7-bf3d-9909e91e0638) | ![image](https://github.com/user-attachments/assets/dcf23510-2a41-478e-b5d9-dfda0d993f1b) |
Before Preview: https://deploy-preview-14366--material-ui-x.netlify.app/x/react-data-grid/filtering/header-filters/
After Preview: https://deploy-preview-14375--material-ui-x.netlify.app/x/react-data-grid/filtering/header-filters/
1. Double top border in header filters
2. Messed up scrollbar fillers' borders

[DataGridPro] Fix double top border in header filters

---

docs/data/data-grid/row-selection/CheckboxSelectionIndeterminateGrid.js
docs/data/data-grid/row-selection/CheckboxSelectionIndeterminateGrid.tsx
docs/data/data-grid/row-selection/CheckboxSelectionIndeterminateGrid.tsx.preview
docs/data/data-grid/row-selection/row-selection.md
docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
docs/translations/api-docs/data-grid/data-grid-premium/data-grid-premium.json
docs/translations/api-docs/data-grid/data-grid-pro/data-grid-pro.json
docs/translations/api-docs/data-grid/data-grid/data-grid.json
packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
packages/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx
packages/x-data-grid-pro/src/tests/rowSelection.DataGridPro.test.tsx
packages/x-data-grid/src/DataGrid/DataGrid.tsx
packages/x-data-grid/src/DataGrid/useDataGridProps.ts
packages/x-data-grid/src/components/columnSelection/GridHeaderCheckbox.tsx
packages/x-data-grid/src/models/props/DataGridProps.ts
packages/x-data-grid/src/tests/rowSelection.DataGrid.test.tsx

Extracted from [#13757](https://github.com/mui/mui-x/pull/13757#discussion_r1689400378) as suggested by @arminmeh
Part of #7753 
https://deploy-preview-14247--material-ui-x.netlify.app/x/react-data-grid/row-selection/#customize-indeterminate-checkbox-behavior
Todo:

[DataGrid] Allow to control the indeterminate checkbox behavior

---

packages/x-data-grid/src/utils/createSelector.ts

Follow-up of https://github.com/mui/mui-x/pull/11367#discussion_r1738415235

[DataGrid] Restore reselect behavior

---

docs/data/introduction/licensing/licensing.md

Scale to all the docs: https://github.com/mui/material-ui/pull/43438/files#r1730483431
We don't use it anywhere on https://mui.com/pricing/, https://mui.com/legal/mui-x-eula/

[docs] Remove notion of seats

---

packages/x-data-grid-pro/src/components/headerFiltering/GridHeaderFilterCell.tsx
packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx
packages/x-data-grid/src/components/containers/GridRootStyles.ts
packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx

I can't reproduce this issue https://github.com/mui/mui-x/pull/10059/files#r1417671356 using:
```jsx
import { DataGrid } from '@mui/x-data-grid';
const rows = [
{
id: 1,
username: '@MUI',
age: 20,
},
];
export default function ColumnSizingGrid() {
return (
<div style={{ height: 250, width: '100%' }}>
<DataGrid
columns={[
{ field: 'id' },
{ field: 'username', width: 125, minWidth: 150, maxWidth: 400 },
{ field: 'age', resizable: false },
]}
rows={rows}
/>
</div>
);
}
```
so I'm continuing https://github.com/mui/mui-x/pull/13293#discussion_r1695259684. I suspect that we can save bundle size here.
Edit: how fun, the CI is failing with the data picker, unrelated, it seems because we are the 1st of the month, but not 100% sure.
Preview: …

[DataGrid] Remove cell min-width / max-width styles

---

packages/x-data-grid/src/components/containers/GridRootStyles.ts

Fixes a couple of issues found on touch devices, introduced here #14293
**Snag 1:** Double border caused by separator not being hidden when a cell is focused
| --- | --- |
| <img width="386" alt="Screenshot 2024-09-03 at 21 13 36" src="https://github.com/user-attachments/assets/06397e0e-bb65-46e2-a78f-c2896e4b459d"> | <img width="387" alt="Screenshot 2024-09-03 at 21 13 27" src="https://github.com/user-attachments/assets/edc26bca-3013-4804-b8a5-0f2783cf4a1c"> |
**Snag 2:** Last separator always in "active" state
| --- | --- |
| <img width="389" alt="Screenshot 2024-09-03 at 21 12 51" src="https://github.com/user-attachments/assets/4dc9c5dd-5d53-43c9-85a8-15ba65f474bf"> | <img width="387" alt="Screenshot 2024-09-03 at 21 13 00" …

[DataGrid] Fix separator styles on touch devices

---

docs/translations/api-docs/charts/default-heatmap-tooltip/default-heatmap-tooltip.json
packages/x-charts-pro/src/Heatmap/DefaultHeatmapTooltip.tsx
packages/x-charts/src/ChartsTooltip/ChartsItemTooltipContent.tsx

Wrong copy pasted of the axis def into the item one

[charts] Fix JSDocs typo

---

.github/workflows/closed-issue-message.yaml

This is to align the workflow between repos.
Related PR https://github.com/mui/material-ui/pull/43450

[infra] Switch 'add closing message' to reusable workflow

---

packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.test.tsx
packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx
packages/x-date-pickers-pro/src/MobileDateRangePicker/tests/MobileDateRangePicker.test.tsx
packages/x-date-pickers/src/DateCalendar/tests/localization.DateCalendar.test.tsx

[DateRangePicker] Fix `currentMonthCalendarPosition` not scrolling to future sibling

---

packages/x-data-grid-pro/src/tests/detailPanel.DataGridPro.test.tsx

`setProps()` seems to call https://github.com/mui/material-ui/blob/dcc17031aa37b251678c39628b15637ec758d6b4/packages-internal/test-utils/src/createRenderer.tsx#L316 which seems to call https://github.com/testing-library/react-hooks-testing-library/blob/1e01273374af4e48a0feb1f2233bf6c76d742167/src/dom/pure.ts#L22 so this looks like dead code.
This was added in #8097.
I have noticed this in #14442 while I was quickly checking the CLA signed workflow, I looked at the PR diff and this seemed odd to me.

[test] Remove dead `act()` logic

---

docs/data/tree-view/rich-tree-view/customization/FileExplorer.js
docs/data/tree-view/rich-tree-view/customization/FileExplorer.tsx
docs/data/tree-view/rich-tree-view/customization/HeadlessAPI.js
docs/data/tree-view/rich-tree-view/customization/HeadlessAPI.tsx
docs/data/tree-view/rich-tree-view/editing/CustomLabelInput.js
docs/data/tree-view/rich-tree-view/editing/CustomLabelInput.tsx
docs/data/tree-view/rich-tree-view/ordering/FileExplorer.js
docs/data/tree-view/rich-tree-view/ordering/FileExplorer.tsx
docs/data/tree-view/rich-tree-view/ordering/OnlyReorderFromDragHandle.js
docs/data/tree-view/rich-tree-view/ordering/OnlyReorderFromDragHandle.tsx
docs/data/tree-view/simple-tree-view/customization/GmailTreeView.js
docs/data/tree-view/simple-tree-view/customization/GmailTreeView.tsx
docs/data/tree-view/simple-tree-view/customization/HeadlessAPI.js
docs/data/tree-view/simple-tree-view/customization/HeadlessAPI.tsx
packages/x-tree-view/src/TreeItem2/TreeItem2.tsx
packages/x-tree-view/src/useTreeItem2/index.ts
scripts/x-tree-view-pro.exports.json
scripts/x-tree-view.exports.json

As discussed on Slack, I kept the unstable version available to avoid a double migration (`unstable_useTreeItem2` => `useTreeItem2` => `useTreeItem`)

[TreeView] Make `useTreeItem2` stable

---

packages/x-data-grid/src/colDef/gridStringOperators.ts

Minor refactor to improve code reuse for the `contains`, `doesNotContain`, `equals`, `doesNotEqual`, `isEmpty` and `isNotEmpty` string operator functions.
Addresses this feedback: https://github.com/mui/mui-x/pull/14489#discussion_r1750124260

[DataGrid] Refactor string operator filter functions

---

renovate.json

We have numerous `eslint-plugin-*` dependencies that keep producing conflicts after merging one of the bump PRs.
https://github.com/mui/mui-x/blob/a198b26371fa8ed6185175426e983efffd2b1e3a/package.json#L144-L154
Having them grouped should ease such bumps. 🤞

[infra] Create `ESLint plugins` renovate group

---

renovate.json

Follow up on https://github.com/mui/mui-x/pull/14574 to fix a silly mistake. 🙈 
Source: https://docs.renovatebot.com/configuration-options/#matchpackagenames

[infra] Fix renovate ESLInt group config

---

packages/x-date-pickers/src/locales/beBY.ts
packages/x-date-pickers/src/locales/csCZ.ts
packages/x-date-pickers/src/locales/elGR.ts
packages/x-date-pickers/src/locales/enUS.ts
packages/x-date-pickers/src/locales/isIS.ts
packages/x-date-pickers/src/locales/kzKZ.ts
packages/x-date-pickers/src/locales/nbNO.ts
packages/x-date-pickers/src/locales/plPL.ts
packages/x-date-pickers/src/locales/ptBR.ts
packages/x-date-pickers/src/locales/skSK.ts
packages/x-date-pickers/src/locales/trTR.ts
packages/x-date-pickers/src/locales/urPK.ts
test/e2e/index.test.ts

See for why: https://github.com/mui/mui-x/pull/13289#discussion_r1720428730

[pickers][fields] Improve clear action label

---

docs/data/data-grid/recipes-row-grouping/recipes-row-grouping.md

Changed "Dispaying" to "Displaying"
The following docs section had a typo, which I proposed to fix.
https://mui.com/x/react-data-grid/recipes-row-grouping/#dispaying-child-row-count-in-footer

[docs] Fixed typo in Recipes Row Grouping

---

packages/x-data-grid-pro/src/hooks/features/detailPanel/gridDetailPanelToggleColDef.tsx
packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderTitle.tsx
packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx
packages/x-data-grid/src/tests/columnGrouping.DataGrid.test.tsx

Fixes #9954 
`aria-label` was only added if the default header component was used (`GridColumnHeaderTitle`).
That component adds label as its content which is read by the voice over, so the `aria-label` is not needed at all.

[DataGrid] Fix Voice Over reading the column name twice

---

packages/x-data-grid-pro/src/tests/infiniteLoader.DataGridPro.test.tsx
packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx

Fixes #12973 
Having a bottom pinned row would connect the last row observer which would report intersection.
Condition updated to target the content rows only

[DataGridPro] Fix `onRowsScrollEnd` being triggered instantly when using a bottom pinned row

---

docs/data/data-grid/column-definition/column-definition.md
packages/x-data-grid-pro/src/tests/infiniteLoader.DataGridPro.test.tsx

See https://mui-org.slack.com/archives/C0757R0KW67/p1726119696585269

[docs] Warn about the `valueGetter` and `valueFormatter` signature change

---

packages/x-data-grid-premium/src/tests/license.DataGridPremium.test.tsx
packages/x-license/src/generateLicense/generateLicense.ts
packages/x-license/src/utils/licenseModel.ts

Finish the renaming work: https://github.com/mui/mui-x/pull/14531#issuecomment-2344262574.

[license] Finish renaming of LicensingModel

---

packages/x-data-grid-pro/src/tests/infiniteLoader.DataGridPro.test.tsx

Based on https://github.com/mui/mui-x/pull/14602#discussion_r1761091495

[test] Spy on observe method to avoid flaky wait for a callback

---

docs/data/charts/composition/composition.md

Seems simpler to follow:
https://mui.com/x/react-charts/composition/#properties vs. https://deploy-preview-14603--material-ui-x.netlify.app/x/react-charts/composition/#properties
I struggled a bit to understand the code the first time I read it.

[charts][docs] Polish code formatting

---

packages/x-charts-pro/src/context/CartesianProviderPro/createAxisFilterMapper.ts
packages/x-charts/src/BarChart/extremums.test.ts
packages/x-charts/src/context/CartesianProvider/computeValue.ts
packages/x-charts/src/context/CartesianProvider/getAxisExtremum.ts
packages/x-charts/src/context/PluginProvider/ExtremumGetter.types.ts

Part of the Radar chart.
The radar will have one radial axis per radar direction, such that use can plot on different direction values with different scales. For example comparing the GDP/capit and the life expectancy of countries on the same radar implies different scales.
To map series value to the right axis, I need their index.
So for consistency I'm providing the same values to the cartesian axes

[charts] Pass the axis index to extremum getter

---

packages/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts
packages/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx
packages/x-data-grid/src/hooks/features/focus/useGridFocus.ts

Fixes #14591
- Before: https://codesandbox.io/p/sandbox/sharp-kepler-8l3fzr
- After: https://codesandbox.io/p/sandbox/gracious-flower-p7w9wl
Initially, the root element reference is `null`.
In `useEffect` that runs on init the `document` reference will point to the main window's document, since [this util](https://github.com/mui/material-ui/blob/v5.x/packages/mui-utils/src/ownerDocument/ownerDocument.ts#L2) is being used to get it.
Issue will not be visible unless the grid is actually rendered in another window (popup). In that case, some event listeners will end up being attached to the wrong document.
Callbacks and other event handlers that are triggered after user actions are fine, since the reference is there by that time.
I have updated all places where `ownerDocument` is being used …

[DataGrid] Fix document reference when the grid is rendered in a popup window

---

docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md
docs/data/migration/migration-pickers-v6/migration-pickers-v6.md
docs/data/migration/migration-tree-view-v6/migration-tree-view-v6.md

I noticed a few inconsistencies while working on #14651

[docs] Clean v6 => v7 migration guide

---

.browserslistrc
.github/workflows/vale-action.yml
packages/grid/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts
yarn.lock

Based on https://github.com/mui/mui-x/pull/14199
Related to https://github.com/mui/mui-x/issues/14184

[DataGridPremium] Fix onCellSelectionModelChange not triggered when additional cell range is selected

---

.vale.ini
docs/data/charts/bars/bars.md

The other projects do this: https://github.com/search?q=org%3Amui%20MinAlertLevel&type=code, so I don't see a need to be different in MUI X. I fixed some instances to illustrate the value.

[docs] Report Vale at warning level

---

test/regressions/data-grid/DataGridCssVars.js

I noticed we don't have a test that uses `CssVarsProvider`.
This PR adds one to ensure we don't break the DataGrid when used with `CssVarsProvider`

[DataGrid] Add `DataGridCssVars` regression demo

---

packages/x-data-grid-premium/src/hooks/features/aggregation/wrapColumnWithAggregation.tsx
packages/x-data-grid-premium/src/tests/rowSpanning.DataGridPremium.test.tsx

Fixes #14691
The row spanning tries to pre-compute some spanned rows during the initialization phase, but the aggregation wraps the `valueGetter` with a function that tries to access an API method `getRowId` which is not yet binded to the `apiRef`, the error occurs.

[DataGrid] Fix error when initializing aggregation with row spanning

---

packages/x-tree-view/src/hooks/useTreeItem2Utils/useTreeItem2Utils.tsx

From https://github.com/mui/mui-x/pull/14551#discussion_r1753192326

[TreeView] Export `publicAPI` form `useTreeItem2Utils`

---

packages/x-date-pickers/src/YearCalendar/YearCalendar.tsx
packages/x-date-pickers/src/YearCalendar/tests/keyboard.YearCalendar.test.tsx

Hi @LukasTy @MBilalShafi ,
A thousand apologies, I had tested this during development but when yearsOrder was changed from a boolean to `asc` | `desc` the RTL horizontal direction check got borken.
Still works fine with the default settings but if `yearsOrder='desc'` is used with rtl now the left/right navigation is backwards when the theme is right to left.
Finally found a good place to test these under the localization docs page and this small change should make everything right (/x/react-date-pickers/adapters-locale/).
I will work on an update to the automated tests too that would catch this, but this quick fix for now.

[pickers] Fix left-right keyboard nav with `yearsOrder="desc"` and `direction="rtl"`

---

packages/x-charts/src/LineChart/AnimatedArea.tsx
packages/x-charts/src/LineChart/AnimatedLine.tsx
packages/x-charts/src/LineChart/AppearingMask.tsx

Fixes https://github.com/mui/mui-x/issues/14664#issuecomment-2368581900
You can reproduce the bug with this codesandbox: https://codesandbox.io/embed/jp335h?module=/src/Demo.tsx
currently package fetching seems broken, So I've not been able to make one to prove it fixes the issue

[charts] Fix area appearing

---

packages/x-data-grid/src/components/cell/GridCell.tsx
packages/x-data-grid/src/components/columnHeaders/GridBaseColumnHeaders.tsx
packages/x-data-grid/src/components/containers/GridRoot.tsx
packages/x-data-grid/src/components/containers/GridToolbarContainer.tsx
packages/x-data-grid/src/components/menu/GridMenu.tsx
packages/x-data-grid/src/components/panel/GridPanel.tsx
packages/x-data-grid/src/components/panel/GridPanelContent.tsx
packages/x-data-grid/src/components/panel/GridPanelFooter.tsx
packages/x-data-grid/src/components/panel/GridPanelHeader.tsx
packages/x-data-grid/src/components/panel/GridPanelWrapper.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx
packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx
packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerToolbar.tsx
packages/x-date-pickers-pro/src/DateTimeRangePicker/DateTimeRangePickerToolbar.tsx
packages/x-date-pickers/src/DateTimePicker/DateTimePickerTabs.tsx
packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePickerLayout.tsx
packages/x-date-pickers/src/PickersCalendarHeader/PickersCalendarHeader.tsx
packages/x-date-pickers/src/PickersLayout/PickersLayout.tsx
packages/x-date-pickers/src/TimeClock/Clock.tsx
packages/x-date-pickers/src/TimeClock/ClockNumber.tsx
packages/x-date-pickers/src/TimeClock/ClockPointer.tsx
packages/x-date-pickers/src/internals/components/PickersToolbarButton.tsx
packages/x-date-pickers/src/internals/components/PickersToolbarText.tsx
packages/x-tree-view/src/TreeItem/TreeItemContent.tsx

A convention in the way the class names are visible when appended to the `class` attribute:
(I was in the airplane looking at something else and got confused by this. A quick-win)

[core] Fix class name composition order

---

docs/data/pages.ts

Per the playbook in #9727, I believe that the long-term goal is to have a blog infra that supports change for different product scopes: https://www.notion.so/mui-org/docs-infra-Improving-the-blog-infrastructure-bcae2b15493f4daba0758adf499f7793?pvs=4#d041fb05b6184dc68d7f9df7c9100b60. 
In any cases, when going to https://v6.mui.com/x/introduction/, we want the link to point to the most up to date content.

[docs] Fix what's new link to use absolute URL

---

packages/x-data-grid-pro/src/tests/filtering.DataGridPro.test.tsx
packages/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts

Closes https://github.com/mui/mui-x/issues/14446
Before: https://codesandbox.io/p/sandbox/wispy-paper-mfjzqs?file=%2Fsrc%2FDemo.tsx%3A1%2C1-23%2C1
After: https://codesandbox.io/p/sandbox/withered-surf-chyrgn?file=%2Fsrc%2FDemo.tsx

[data grid] Fix column definition undefined value

---

packages/x-data-grid/src/components/cell/GridCell.tsx

This is the result of a merge conflict. I refactored this in #14448 but #14124 wasn't merged yet. A quick-win.

[core] Replace minWidth, maxWidth with width

---

docs/data/date-pickers/timezone/timezone.md

This pull request corrects a typo in the usage of Moment guide within the Date and Time Pickers documentation. It replaces the reference to `datejs.utc` with the correct usage of `moment.utc` for creating UTC dates. This small change improves the accuracy of the documentation and helps users avoid confusion when working with UTC and timezones.

[docs] Fix typo in usage of Moment guide for UTC and timezones

---

docs/pages/x/api/charts/line-series-type.json
docs/translations/api-docs/charts/line-series-type.json
packages/x-charts/src/BarChart/formatter.ts
packages/x-charts/src/LineChart/formatter.ts
packages/x-charts/src/SparkLineChart/SparkLineChart.tsx
packages/x-charts/src/hooks/useSeries.ts
packages/x-charts/src/internals/geometry.ts
packages/x-charts/src/models/seriesType/line.ts

Just some improvements and consistency I've found when working on another PR
- Improve some types
- Add default curve used in line charts for clarity
- Use warnOnce in more places

[charts] Type improvements & `warnOnce` usage

---

docs/data/date-pickers/localization/data.json
packages/x-date-pickers/src/locales/hrHR.ts
packages/x-date-pickers/src/locales/index.ts

[l10n] Add Croatian (hr-HR) locale

---

packages/x-tree-view/src/internals/plugins/useTreeViewLabel/useTreeViewLabel.test.tsx

Same as https://github.com/mui/material-ui/pull/43961

[test] Fix `Escape` event firing event

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/hrHR.ts

Adds the missing translation for the Croatian (hr-HR) locale and fixes couple of current translations
Related to https://github.com/mui/mui-x/issues/3211

[l10n] Improve Croatian (hr-HR) locale

---

docs/data/data-grid/column-ordering/column-ordering.md

[docs] Added warning callout for Firefox reordering bug 

---

packages/x-data-grid-pro/src/tests/cellEditing.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/rowEditing.DataGridPro.test.tsx
packages/x-data-grid/src/hooks/features/editing/useGridCellEditing.ts
packages/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts

Previous PR: #14146 
This reverts commit 24c0442f1e3b33198df0b757d4dccc66be5e6526.

[datagrid] Revert "use `event.type`  for detecting IME key press"

---

scripts/releaseChangelog.mjs

This will add a section below the highlights giving the community contributors a special shoutout. We can still work on providing a social shoutout as well, but this is a first step towards recognition of community contributions. 💪🏼 
Running the changelog script will now add a section below the highlights that looks like this:
```markdown
Special thanks go out to our community contributors who have helped make this release possible:
@AWAIS97, @chucamphong, @GMchris, @JakubSveda, @k-rajat19, @k725, @lawvs, @lhilgert9, @Miodini, @ntamas, @ruiaraujo012, @Sanderand, @thomasmoon, @vallereaugabriel.
Following are all team members who have contributed to this release:
@alexfauquette, @arminmeh, @arthurbalduini, @cherniavskii, @flaviendelangle, @Janpot, @JCQuintas, @KenanYusuf, @LukasTy, …
```

[infra] Adds community contribution section to the changelog script

---

packages/x-data-grid/src/hooks/features/rows/useGridRows.ts

Fixes #14793
- Before: https://codesandbox.io/p/sandbox/hopeful-chandrasekhar-8xgvr4
- After: https://codesandbox.io/p/sandbox/modern-sound-zrlx8s
When a new data source is passed, the strategy processor gets updated and row preprocessing is re-triggered with the old data due to the binding with `activeStrategyProcessorChange` event.
The PR skips automatically re-running the pre-processing when the data source is updated.

[DataGridPro] Fix row pre-processing running with a stale data source

---

docs/data/data-grid/row-spanning/RowSpanningCustom.js
docs/data/data-grid/row-spanning/RowSpanningCustom.tsx

From #14124  - fixing name used in demo
- Before: https://deploy-preview-14821--material-ui-x.netlify.app/x/react-data-grid/row-spanning/#customizing-row-spanning-cells
- After: https://deploy-preview-14822--material-ui-x.netlify.app/x/react-data-grid/row-spanning/#customizing-row-spanning-cells

[data grid][docs] Change demo name example

---

docs/data/data-grid/master-detail/FullWidthDetailPanel.js
docs/data/data-grid/master-detail/FullWidthDetailPanel.tsx
docs/data/data-grid/master-detail/FullWidthDetailPanel.tsx.preview

This PR is created to address https://github.com/mui/mui-x/issues/14850
Unable to attach labels to the PR, can someone please help with attaching the `component: data grid` & `bug` & `docs` labels
Fixes #14850

[docs] Fix column pinning for "Disable detail panel content scroll" section

---

packages/x-charts-pro/package.json
packages/x-charts/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-internals/package.json
packages/x-license/package.json
packages/x-tree-view-pro/package.json
packages/x-tree-view/package.json
pnpm-lock.yaml

> Feel free to change the PR title, this fix applies to all mui-x products not just DataGrid
closes #14866
From https://codesandbox.io/p/sandbox/elegant-tree-xspyf2?file=%2Finitialize.ts%3A5%2C1,
It's the inconsistency of `@mui/utils` version.
- `@mui/material` => `@mui/utils` v6
- `@mui-x/data-grid` => `@mui/utils` v5
That's why configuring the classNameGenerator from `@mui/material` (using `@mui/utils` v6) does not affect DataGrid which is using `@mui/utils` v5.

[core] Support `@mui/utils` v6

---

packages/x-tree-view-pro/src/RichTreeViewPro/RichTreeViewPro.tsx
packages/x-tree-view/src/RichTreeView/RichTreeView.tsx
packages/x-tree-view/src/internals/components/RichTreeViewItems.tsx
packages/x-tree-view/src/internals/index.ts
packages/x-tree-view/src/internals/plugins/useTreeViewItems/index.ts
packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.types.ts

Extracted from #14210 and #13520
In #13520, the idea is to pass the virtualized items to this component instead of all items.

[TreeView] Rework how items are being rendered in Rich Tree View components

---

packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx

Fixes #14830 
`scrollToIndexes` eventually ends up here
https://github.com/mui/mui-x/blob/52601483fbc978b1f3d0f99562b20d807889e06b/packages/x-data-grid/src/hooks/features/scroll/useGridScroll.ts#L147-L152
`virtualScroller` gets the update and the scrollbar follows via an [event listener](https://github.com/mui/mui-x/blob/v7.19.0/packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx#L133)
In this scenario, only `scrollbar` should be updated, since this was already done for the `scroller`. it looks like that, in some cases, `scroller` event gets executed first and it locks `scrollbar` update with the `isLocked` flag set to `true`.
I have changed this to work with the last position (it was already used in one event listener). This means that the event listeners will run …

[DataGrid] Fix scrollbar position not being updated after `scrollToIndexes`

---

docs/data/data-grid/events/events.json
docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
docs/translations/api-docs/data-grid/data-grid-premium/data-grid-premium.json
docs/translations/api-docs/data-grid/data-grid-pro/data-grid-pro.json
docs/translations/api-docs/data-grid/data-grid/data-grid.json
packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
packages/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx
packages/x-data-grid/src/DataGrid/DataGrid.tsx
packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx
packages/x-data-grid/src/hooks/features/events/useGridEvents.ts
packages/x-data-grid/src/models/events/gridEventLookup.ts
packages/x-data-grid/src/models/props/DataGridProps.ts

[DataGrid] Add 'onColumnHeaderContextMenu' event

---

packages/x-data-grid-pro/src/tests/editComponents.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/pagination.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/rowEditing.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/rowPinning.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx
packages/x-data-grid/src/tests/rowSelection.DataGrid.test.tsx
packages/x-data-grid/src/tests/rowSpanning.DataGrid.test.tsx
packages/x-data-grid/src/tests/sorting.DataGrid.test.tsx

A follow-up on https://github.com/mui/mui-x/pull/14124#discussion_r1769261094. I believe the use of `waitFor()` should be avoided as much as possible. We want to be able to test changes with incremental steps, so using waitFor feels fundamentally a last resort option. 
I have removed a few to see how it would go.
A side note, there is maybe a need to move our act to be awaited https://github.com/mui/mui-public/issues/174.

[test] Replace waitFor() with act()

---

packages/x-date-pickers-pro/src/DateTimeRangePicker/DateTimeRangePickerToolbar.tsx
packages/x-date-pickers/src/models/pickers.ts

[pickers] Fix regression on `PickerValidDate`

---

packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts

Fixes #14826
- Before: https://codesandbox.io/p/sandbox/quirky-shirley-s3mzzz
- After: https://codesandbox.io/p/sandbox/white-resonance-vvd7vf

[DataGrid] Avoid row spanning computation of outdated rows

---

docs/data/data-grid/row-grouping/row-grouping.md
docs/translations/api-docs/data-grid/data-grid-premium/data-grid-premium.json
docs/translations/api-docs/data-grid/data-grid-pro/data-grid-pro.json
packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
packages/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx
packages/x-data-grid/src/hooks/features/rowSelection/utils.ts
packages/x-data-grid/src/models/props/DataGridProps.ts

Noticed those while working on #14899
I'm also not a fan of having that many flat params on `findRowsToSelect` and `findRowsToDeselect`.
I feel like it would be a lot more readable:
1. Passing `props.rowSelectionPropagation` to the function  (right now if you are searching the codebase, this concept can be named `rowSelectionPropagation.descendants` or `autoSelectDescendants` depending on where you are looking for)
2. Moving to an object (it's subjective, but for this method I think the perf overhead is negligible, feel free to ignore this one)
```tsx
findRowsToSelect({
apiRef,
tree,
id,
rowSelectionPropagation,
addRow,
});
```

[data grid] Fix typo on the `rowSelectionPropagation` feature

---

packages/x-data-grid-pro/src/tests/rowSelection.DataGridPro.test.tsx
packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts

Fixes #14859 
- Before: https://codesandbox.io/p/sandbox/festive-pasteur-55fj99
- After: https://codesandbox.io/p/sandbox/bold-meadow-68z2d5
_Context:_ https://github.com/mui/mui-x/issues/14859#issuecomment-2404613592

[DataGrid] Fix `onRowSelectionModelChange` firing unnecessarily on initial render

---

packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerToolbar.tsx

Fixes #14924
Same as #14896 but for `DateRangePickerToolbar`.
If someone could double check that he finds no `import("moment")` (or luxon or dayjs) in the bundle outside of the adapter file :cry:

[pickers] Fix `PickerValidDate` usage in `DateRangePickerToolbar`

---

packages/x-data-grid-pro/src/tests/cellEditing.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/columns.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/rowEditing.DataGridPro.test.tsx

Porting a change from https://github.com/mui/mui-x/pull/14508
Basically making the render independent from other test runs by not having a globally defined variable for the test.
Also removes `done()` from two tests 😅 
~~### Scrollbars~~
~~The changes on [columns.DataGridPro.test.tsx](https://github.com/mui/mui-x/pull/14926/files#diff-ed2f26687dbce52b79ed6f7fed0b2b2b20a4f3807c1c6537477ef24775c581ab) are due to playwright [not displaying scrollbars by default](https://github.com/microsoft/playwright/issues/5778).~~
~~If it is desirable to display the scrollbars, then I can revert this and force playwright to show them in headless mode instead.~~

[code-infra] Prepare some tests to work in `vitest/playwright`

---

docs/data/charts/scatter/ScatterDataset.js
docs/data/charts/scatter/ScatterDataset.tsx
docs/data/charts/scatter/ScatterDataset.tsx.preview
docs/data/charts/scatter/scatter.md
docs/next-env.d.ts
docs/pages/x/api/charts/scatter-series-type.json
docs/translations/api-docs/charts/scatter-series-type.json
packages/x-charts/src/ScatterChart/extremums.ts
packages/x-charts/src/ScatterChart/formatter.ts
packages/x-charts/src/models/seriesType/scatter.ts

Resolves #14333
Uses a single object signature. As it more accurately leverage typescript to force users to provide all keys when the object exists.
```tsx
type DatasetKeys = {
x: string,
y: string,
z?: string,
id: string
}
type ScatterChart = {
datasetKeys?: DatasetKeys
}
```

[charts] Allow `dataset` to be used with `ScatterChart`

---

packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts
packages/x-data-grid/src/tests/rowSelection.DataGrid.test.tsx

Fixes #14964 
- Before: https://codesandbox.io/p/sandbox/vigorous-oskar-rhgzlp
- After: https://codesandbox.io/p/sandbox/compassionate-black-forked-6sfvpm

[DataGrid] Fix `onRowSelectionModelChange` not being called after row is removed

---

packages/x-tree-view/src/TreeItem/TreeItem.tsx
packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.test.tsx
packages/x-tree-view/src/useTreeItem2/useTreeItem2.ts

Fixes #14982
The old behavior was linking to the ARIA doc which does not describes what was implemented...

[TreeView] Fix usage of the `aria-selected` attribute

---

packages/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts
packages/x-data-grid-premium/src/tests/clipboard.DataGridPremium.test.tsx
packages/x-data-grid-pro/src/tests/cellEditing.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/rowEditing.DataGridPro.test.tsx
packages/x-data-grid/src/hooks/features/clipboard/useGridClipboard.ts
packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts
packages/x-data-grid/src/internals/index.ts
packages/x-data-grid/src/utils/keyboardUtils.ts
packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx
packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx
packages/x-date-pickers/src/DateField/tests/selection.DateField.test.tsx
packages/x-date-pickers/src/TimeField/tests/editing.TimeField.test.tsx
packages/x-date-pickers/src/internals/hooks/useField/useField.ts
packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.test.tsx
packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts
packages/x-tree-view/src/useTreeItem2/useTreeItem2.test.tsx

Closes #14219 
We also fix the date picker and tree view shortcuts.

[data grid][pickers][tree-view] Fix shortcut with localization keyboard

---

packages/x-tree-view/src/TreeItem2DragAndDropOverlay/TreeItem2DragAndDropOverlay.tsx

[TreeView] Fix `alpha` usage with  CSS variables

---

packages/x-data-grid/src/hooks/features/rowSelection/utils.ts

Fixes #14954
- Before: https://codesandbox.io/p/sandbox/sweet-shirley-gt5xtc
- After: https://codesandbox.io/p/sandbox/white-shape-g3ly8s

[DataGridPro] Fix indeterminate checkbox state for server-side data

---

packages/x-tree-view/src/internals/corePlugins/useTreeViewId/useTreeViewId.ts
packages/x-tree-view/src/internals/corePlugins/useTreeViewId/useTreeViewId.types.ts

Fixes #14980
Extracted from #14210
Only sets the default id attribute after the hydration, like `useId` does

[TreeView] Fix hydration error

---

docs/pages/x/api/data-grid/grid-print-export-options.json
packages/x-data-grid/src/components/toolbar/GridToolbarExport.tsx
packages/x-data-grid/src/models/gridExport.ts

[DataGrid] Fix ugly prop-types for the `pageStyle` prop of the `GridPrintExportMenuItem` component

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/ptBR.ts

 [l10n] Add Portuguese (PT-BR)  translation 

---

docs/data/data-grid/pagination/PageSizeCustomOptions.js
docs/data/data-grid/pagination/PageSizeCustomOptions.tsx
docs/data/data-grid/pagination/PageSizeCustomOptions.tsx.preview
docs/data/data-grid/pagination/pagination.md
packages/x-data-grid/src/hooks/features/pagination/gridPaginationSelector.ts

This PR is created to address https://github.com/mui/mui-x/issues/14276
Unable to attach labels to the PR, can someone please help with attaching the labels

[Data grid] Fix number of rows to display for page size options with negative value

---

packages/x-charts/src/ChartsOnAxisClickHandler/ChartsOnAxisClickHandler.tsx
scripts/x-charts-pro.exports.json
scripts/x-charts.exports.json

In a scenario where we'd like to have a controlled state that holds the axis data and make other components react to that state as we update it by clicking on the axes of the chart it would be very useful if we could re-use the `AxisData` type. But it was not exported when I checked the source code.
This PR's purpose is to

[charts] Export data type in onAxisClick(_, data) callback

---

packages/x-data-grid/src/components/virtualization/GridMainContainer.tsx

Closes #15005
Before: https://codesandbox.io/p/sandbox/condescending-tereshkova-ytknq9 
After:  https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-sh3fw2?file=%2Fsrc%2Fdemo.tsx

[DataGrid] Fix `GridPanelAnchor` positioning

---

packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.itemPlugin.ts
packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.types.ts
packages/x-tree-view/src/TreeItem/TreeItem.types.ts
packages/x-tree-view/src/TreeItem/TreeItemContent.tsx
packages/x-tree-view/src/TreeItem/useTreeItemState.ts
packages/x-tree-view/src/TreeItem2/TreeItem2.types.ts
packages/x-tree-view/src/TreeItem2LabelInput/TreeItem2LabelInput.types.ts
packages/x-tree-view/src/hooks/useTreeItem2Utils/useTreeItem2Utils.tsx
packages/x-tree-view/src/internals/index.ts
packages/x-tree-view/src/internals/models/MuiCancellableEvent.ts
packages/x-tree-view/src/internals/models/index.ts
packages/x-tree-view/src/internals/plugins/useTreeViewFocus/useTreeViewFocus.ts
packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts
packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewLabel/useTreeViewLabel.itemPlugin.ts
packages/x-tree-view/src/models/events.ts
packages/x-tree-view/src/models/index.ts
packages/x-tree-view/src/useTreeItem2/useTreeItem2.ts
packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts
scripts/x-tree-view-pro.exports.json
scripts/x-tree-view.exports.json

Part of #14985
While writting the example for the issue, I noticed that I needed `MuiCancellableEventHandler` to have a correct typing but that this type was internal.
Given that we will have the same topic on other X packages (pickers need to work to better support this pattern), I moved the logic to the shared package before re-exporting it.

[TreeView] Make the cancellable event types public

---

docs/data/tree-view/simple-tree-view/items/items.md

I was going through docs and observed this typo. Raising a PR to fix it.
Link to docs - https://mui.com/x/react-tree-view/simple-tree-view/items/#disabled-items

[docs] Fix typo in Tree View docs

---

packages/x-tree-view/src/TreeItem2DragAndDropOverlay/TreeItem2DragAndDropOverlay.tsx

Fixes https://github.com/mui/mui-x/issues/15017.
This is a suggestion/simplification.
Feel free to suggest better colors/option that would work with CSS Variables as well. 👍

[TreeView] Fix drag and drop color usage

---

docs/package.json
docs/pages/_app.js
docs/src/modules/components/ChartsInstallationInstructions.js
docs/src/modules/components/DataGridInstallationInstructions.js
docs/src/modules/components/PickersInstallationInstructions.js
docs/src/modules/components/TreeViewInstallationInstructions.js
package.json
packages/x-codemod/README.md

This is to prepare for the next major release:
I did also introduce a little helper to get the docs paths for the components
Please call out anything that I might have missed.
Related notion page: https://www.notion.so/mui-org/MUI-X-Major-version-release-process-a27f296dfb9e4b33bdb767f3d6e8018c?pvs=4

[release] v8 preparation

---

docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
docs/translations/api-docs/data-grid/data-grid-premium/data-grid-premium.json
docs/translations/api-docs/data-grid/data-grid-pro/data-grid-pro.json
docs/translations/api-docs/data-grid/data-grid/data-grid.json
packages/x-data-grid-premium/src/components/GridColumnMenuAggregationItem.tsx
packages/x-data-grid-premium/src/components/GridColumnMenuRowGroupItem.tsx
packages/x-data-grid-premium/src/components/GridColumnMenuRowUngroupItem.tsx
packages/x-data-grid-premium/src/components/GridExcelExportMenuItem.tsx
packages/x-data-grid-pro/src/components/GridColumnMenuPinningItem.tsx
packages/x-data-grid-pro/src/components/headerFiltering/GridHeaderFilterMenu.tsx
packages/x-data-grid/src/components/cell/GridActionsCellItem.tsx
packages/x-data-grid/src/components/menu/columnMenu/menuItems/GridColumnMenuFilterItem.tsx
packages/x-data-grid/src/components/menu/columnMenu/menuItems/GridColumnMenuHideItem.tsx
packages/x-data-grid/src/components/menu/columnMenu/menuItems/GridColumnMenuManageItem.tsx
packages/x-data-grid/src/components/menu/columnMenu/menuItems/GridColumnMenuSortItem.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarDensitySelector.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarExport.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarExportContainer.tsx
packages/x-data-grid/src/material/index.ts
packages/x-data-grid/src/models/gridSlotsComponent.ts
packages/x-data-grid/src/models/gridSlotsComponentsProps.ts
scripts/x-data-grid-premium.exports.json
scripts/x-data-grid-pro.exports.json
scripts/x-data-grid.exports.json

Design-system agnostic related.
I've added `baseMenuList` & `baseMenuItem`. I did not introduce equivalents for `ListItemText` and `ListItemIcon` because I don't think I'll go with that API for the base slots, the API will probably look something like this instead:
```
<slots.baseMenuItem iconLeft={...} iconRight={...}>{text}</slots.baseMenuItem>
```
Because it's easier to adapt that API to the other design systems rather than the other way around.

[DataGrid] refactor: baseMenuList & baseMenuItem

---

docs/data/charts/getting-started/getting-started.md
docs/data/charts/overview/overview.md
docs/data/introduction/support/support.md
docs/next-env.d.ts
docs/src/modules/components/ChartFeaturesGrid.js

Part of https://www.notion.so/mui-org/Audit-and-edit-MUI-X-docs-10dcbfe7b6608028af52f73cae5b245a
This PR aims to bring consistency to the style and tone of the Charts Getting Started docs. 
The biggest change is the introduction of the terms "self-contained" and "composable" to refer to the difference between a "single" component and one assembled through custom composition. If folks are happy with this terminology then we could start to introduce it throughout the product docs.
I didn't put much effort into the Overview page, because I'm hoping it will get a major design makeover from @noraleonte soon like the Date Pickers did! 🙏

[docs] Copyedit the Charts Getting Started sequence

---

packages/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts
packages/x-data-grid/src/components/cell/GridActionsCell.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarColumnsButton.tsx

[DataGrid] refactor: remove more material imports

---

docs/data/data-grid/faq/faq.md
docs/data/pages.ts
docs/pages/x/react-data-grid/faq.js

Cherry-pick of #11686 and #13258 on `v6.x` branch
Partially solves #14855 (for v6)

[docs] Backport the Data Grid FAQ page to v6

---

.circleci/config.yml
docs/constants.js
docs/data/data-grid/localization/data.json
docs/data/date-pickers/localization/data.json
docs/data/introduction/support/support.md
scripts/releaseChangelog.mjs

Some instances of `default-branch-switch` replaced for `v7.x`

[core] Update some `default-branch-switch` instances for `v7.x`

---

.github/workflows/cherry-pick-master-to-v7.yml
.github/workflows/cherry-pick-v7-to-v6.yml

Adjust cherry-pick GH actions based on the changed branch strategy.
This is to fix cherry-picking until we start using https://github.com/mui/mui-public/pull/217.

[core] Adjust cherry-pick GH actions

---

packages/x-data-grid-pro/src/tests/detailPanel.DataGridPro.test.tsx
packages/x-data-grid/src/components/containers/GridRootStyles.ts
packages/x-data-grid/src/components/virtualization/GridBottomContainer.tsx
packages/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx
packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
packages/x-data-grid/src/tests/rows.DataGrid.test.tsx
test/regressions/data-grid/DataGridPinnedColumns.js

Cherry-pick of https://github.com/mui/mui-x/pull/14966

[DataGridPro] Fix column pinning layout

---

packages/x-data-grid-premium/src/hooks/features/rowGrouping/useGridRowGrouping.tsx
packages/x-data-grid-pro/src/hooks/features/dataSource/useGridDataSource.ts

Fixes codesandbox (`@mui/x-data-grid-pro`) build issue.
Seems a better solution than https://github.com/mui/mui-x/pull/15109#discussion_r1816182013

[DataGrid] Move `rowGroupingModelChange` handler to respective hook

---

packages/x-date-pickers-pro/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx
packages/x-date-pickers-pro/src/DesktopDateTimeRangePicker/DesktopDateTimeRangePicker.tsx
packages/x-date-pickers-pro/src/MobileDateRangePicker/MobileDateRangePicker.tsx
packages/x-date-pickers-pro/src/MobileDateTimeRangePicker/MobileDateTimeRangePicker.tsx
packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.tsx
packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.tsx
packages/x-date-pickers/src/MobileDatePicker/MobileDatePicker.tsx
packages/x-date-pickers/src/MobileDateTimePicker/MobileDateTimePicker.tsx
packages/x-date-pickers/src/MobileTimePicker/MobileTimePicker.tsx
packages/x-date-pickers/src/PickersLayout/index.ts
scripts/x-date-pickers-pro.exports.json
scripts/x-date-pickers.exports.json

Nice follow up on #14994, always nice to kill some `any` without tons of added complexity

[pickers] Correctly type the `ownerState` of the `field` and `actionBar` slots when resolved in a picker component

---

packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx
packages/x-data-grid/src/hooks/features/scroll/useGridScroll.ts

Fixes #15158 
Reverts https://github.com/mui/mui-x/pull/14888 (which _tried to_ fix another regression)
Scrollbar scroll positions are not set directly anymore as they are not the same number (heights of scroller and scrollbar do not match)
With smaller offsets from the top the difference is minimal, but it grows over time which is why the issue can be observed after a bit of scrolling.
The original code also impacts the performance as the values are recalculated a lot more than before the change. All this lead me to revert everything back to the state prior to https://github.com/mui/mui-x/pull/14877.
This brought back the very first [issue in the chain](https://github.com/mui/mui-x/issues/14830).
I found out that it is actually caused because of a stale value in `lastPosition`.
Following …

[DataGrid] Fix scroll jump when holding down arrow keys

---

packages/x-date-pickers/src/locales/plPL.ts

Follow-up on https://github.com/mui/mui-x/pull/15177
The cherry-pick unintentionally had a couple of changes that break this translation.
https://github.com/mui/mui-x/pull/15177/files#diff-47123d13580721e9d46a57634e5160492a9b30970bb1b01fbc2d06aec81e135fR62-R65

[core] Fix Pickers `pl-PL` translation after cherry-pick from master

---

packages/x-data-grid-premium/src/tests/rowSelection.DataGridPremium.test.tsx
packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts

Fixes #15206 
The issue occurs when `rowSelectionPropagation` is used on a grid with grouped columns and the data is updated.
After update, new selection lookup is being created, but the autogenerated rows are being added multiple times to the selection lookup array
Thing is, API to fetch the selection list uses selector that returns a `Map`, which removes duplicate values, so the issue is only visible on the count (which operates on the actual array).
Now, the selection lookup is rebuilt using the `Map` as well.
Duplicate values are coming from checking the parent for selection for each grouped row

[DataGridPremium] Fix incorrect rows selection count when selection propagation is enabled with row grouping

---

docs/data/date-pickers/localization/data.json
packages/x-date-pickers/src/locales/elGR.ts

Improve Greek (el-GR) locale.
Issue: #3211

[l10n] Improve Greek (el-GR) locale

---

docs/pages/x/api/charts/bar-series-type.json
docs/pages/x/api/charts/line-series-type.json
docs/pages/x/api/charts/scatter-series-type.json
docs/translations/api-docs/charts/bar-series-type.json
docs/translations/api-docs/charts/line-series-type.json
docs/translations/api-docs/charts/scatter-series-type.json
packages/x-charts/src/BarChart/BarPlot.tsx
packages/x-charts/src/BarChart/extremums.ts
packages/x-charts/src/ChartsOnAxisClickHandler/ChartsOnAxisClickHandler.tsx
packages/x-charts/src/ChartsTooltip/ChartsAxisTooltipContent.tsx
packages/x-charts/src/ChartsTooltip/ChartsItemTooltipContent.tsx
packages/x-charts/src/ChartsTooltip/useAxisTooltip.tsx
packages/x-charts/src/ChartsTooltip/useItemTooltip.tsx
packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx
packages/x-charts/src/LineChart/AreaPlot.tsx
packages/x-charts/src/LineChart/LineHighlightPlot.tsx
packages/x-charts/src/LineChart/LinePlot.tsx
packages/x-charts/src/LineChart/MarkPlot.tsx
packages/x-charts/src/LineChart/extremums.ts
packages/x-charts/src/ScatterChart/ScatterPlot.tsx
packages/x-charts/src/ScatterChart/extremums.ts
packages/x-charts/src/models/seriesType/common.ts
packages/x-charts/src/models/seriesType/scatter.ts

The  `xAxisKey`, `yAxisKey`, and `zAxisKey` properties got deprecated in favor of  `xAxisId`, `yAxisId`, and `zAxisId`.
Those deprecated properties are now removed.

[charts] Remove `xAxisKey`, `yAxisKey`, and `zAxisKey`

---

docs/data/data-grid/joy-ui/joy-ui.md
docs/data/date-pickers/custom-field/custom-field.md
docs/data/date-pickers/custom-layout/custom-layout.md
docs/data/date-pickers/experimentation/experimentation.md

Make the next docs-infra upgrade easier for https://github.com/mui/material-ui/pull/44292.

[docs] Fix missing punctuation on descriptions

---

packages/x-data-grid/src/colDef/gridBooleanOperators.ts
packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputBoolean.tsx
packages/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts
packages/x-data-grid/src/tests/filtering.DataGrid.test.tsx
scripts/x-data-grid-premium.exports.json
scripts/x-data-grid-pro.exports.json
scripts/x-data-grid.exports.json

Closes https://github.com/mui/mui-x/issues/15225
Related to #14327 
Before : https://mui.com/x/react-data-grid/filtering/
After : https://deploy-preview-15252--material-ui-x.netlify.app/x/react-data-grid/filtering/

[DataGrid] Fix filtering with `boolean` column type

---

docs/data/data-grid/list-view/ListViewAdvanced.js
docs/data/data-grid/list-view/ListViewAdvanced.tsx

The Argos test for the advanced list view demo is flaky https://app.argos-ci.com/mui/mui-x/builds/25941/116803997
I suspect this is due to there not being a height on the demo.

[test] Fix advanced list view regression test snapshot

---

packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts

Fixes #15068 (Pro plan)
- Before: https://codesandbox.io/p/sandbox/hopeful-maxwell-dxvvlw
- After: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-ssxqym
Fixes #15045 (Pro plan)
- Before: https://stackblitz.com/edit/react-ayw1zv-qxwdvx?file=Demo.js
- After: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-2hkqsq
Fixes #15079 (Community plan)
- Before: https://codesandbox.io/p/sandbox/headless-microservice-x38xc6
- After: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-zr6gzz
Fixes #15217 (Pro plan)
- Before: https://codesandbox.io/p/sandbox/dgpro-latest-row-selection-bug-forked-57mkp3
- After: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-3j6y7t

[DataGrid] Improve row selection propagation trigger

---

packages/x-charts/src/models/seriesType/common.ts

A. Omit irrelevant tooltip values by updating the SeriesValueFormatter type to allow retuning `null` values
B. Usage: update `valueFormatter` function to return null if the value is irrelevant
Use case: when displaying multiple series with the same label/color on a stacked bar chart it can be useful to omit the series that have no value for a given stack.
Note: I am interested in seeing 'axis' tooltip not 'item'
```
const series = [
{ ... , valueFormatter: (v: number | null) => v ? `${v} 分` : '-' }
]
```
The screenshot below shows the tooltip of a stack that has "MOVING", "STOPPED", and "MOVING"
In this example the order of these events matter both on the x axis and y axis so it was decided to split the multiple "MOVING" data into separate series
When hovering over the tooltip it becomes …

[charts] Allow `SeriesValueFormatter` to return `null` value

---

docs/data/charts/bars/BarAnimation.tsx
docs/data/charts/highlighting/ControlledHighlight.js
docs/data/charts/highlighting/ControlledHighlight.tsx
docs/data/charts/highlighting/ElementHighlights.js
docs/data/charts/highlighting/ElementHighlights.tsx
packages/x-charts/src/PieChart/PieArc.tsx
packages/x-charts/src/PieChart/PieArcPlot.tsx
packages/x-charts/src/context/HighlightedProvider/HighlightedContext.ts
packages/x-charts/src/context/HighlightedProvider/HighlightedProvider.tsx

The `highlighted` and `faded` properties of highlightScope were deprecated in favor of `highlight` and `fade`.
The deprecated ones are now removed.

[charts] Remove deprecated highlight properties

---

packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts

https://github.com/mui/mui-x/commit/431eccc938584ed52befd69590c592c2230b1f87 introduced a failing CI due to another [PR](https://github.com/mui/mui-x/pull/15216) addressing a similar area.

[DataGrid] Fix failing CI

---

docs/data/date-pickers/date-picker/examplesConfig.styling.tsx

Part of #15263.
Currently, we render Pickers in the demo with `enableAccessibleFieldDOMStructure` set to `true`.
This makes the customization to not apply in case of the `TextField` slot, because the theme entry is different (`MuiPickersTextField` instead of `MuiTextField`).
|--------|--------|
| ![Screenshot 2024-11-05 at 18 35 11](https://github.com/user-attachments/assets/a4a5c5ae-ae24-431a-9d85-dd32449d13a0) | ![Screenshot 2024-11-05 at 18 35 33](https://github.com/user-attachments/assets/33c8f8c0-cdbd-4826-950b-831c556ae4aa) |
WDYT about the link to the Material Text field customization page?
Does it still make sense? 🤔

[docs] Use `PickersTextField` in the customization playground

---

packages/x-charts-pro/README.md
packages/x-charts/README.md
packages/x-data-grid-premium/README.md
packages/x-data-grid-pro/README.md
packages/x-data-grid/README.md
packages/x-date-pickers-pro/README.md
packages/x-date-pickers/README.md
packages/x-tree-view-pro/README.md
packages/x-tree-view/README.md

I noticed this in https://www.npmjs.com/package/@mui/x-charts, it's a turn-off for adopting the lib. This was forgotten in #14142.
**Off-topic.** we might miss React 19 here in the peer dependency, needed to use Next.js 15.

[docs] Fix peer dependency range

---

docs/data/migration/migration-pickers-v7/migration-pickers-v7.md

[docs] Add migration guide for the removal of `LicenseInfo` from `@mui/x-date-pickers-pro`

---

docs/data/data-grid/editing/editing.md
docs/data/data-grid/filtering/header-filters.md
docs/data/data-grid/server-side-data/index.md
docs/data/data-grid/state/state.md
docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md

A side quick win I noticed while wanting to help with #15251.
The objective of this change is to make sure the URLs keep working even when using the docs on a different domain, e.g. localhost and for `pnpm docs:link-check` to catch broken links.
Today, it's even more relevant in the way that the docs is versioned: with subdomains. Now unclear if we will keep using subdomains for docs versioning, using folders is also quite common.
@vladmoroz We likely don't want to start thinking now on how we will version Base UI docs. A good chunk of docs use subfolders (Material UI used subdomains so far), maybe they do this for SEO to reinforce backlinks on a single domain, or maybe to make it impossible to have duplication of other pages, e.g. marketing homepage.
Anyway, creating this page as we have …

[docs] Fix hard coded URL domain

---

package.json
test/regressions/.mocharc.js
test/regressions/index.test.ts

- Move to use TS instead of JS
- Add `page.waitForLoadState()` before screenshot

[code-infra] Tentative fix for Argos flaky screenshot tests

---

docs/data/date-pickers/date-picker/examplesConfig.styling.tsx

[docs] Add `PickersPopper` component to customization playground

---

docs/data/introduction/overview/overview.md

Fixes #15393 
The `more details` link was targeted at a private notion page.

[docs] Fix link to private notion page

---

packages/x-charts-pro/src/ChartContainerPro/ChartContainerPro.tsx

Fix #15386
I'm adding the import into the definition, of the pro container since it's the common component to all pro charts

[charts-pro] Fix missing typeOverload

---

packages/x-data-grid/src/hooks/features/pagination/useGridPaginationModel.ts
packages/x-data-grid/src/models/props/DataGridProps.ts

Fixes #12897 
Update `stateRestorePreProcessing` and `setPaginationModel` to send the reason. Also fix TS declaration for `onPaginationModelChange` callback

[DataGrid] Pass reason to `onPaginationModelChange`

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/trTR.ts

Cherry-picked changes by @qerkules in #15377 because I got tangled in git and messed up the branch. 🤦

[l10n] Improve Turkish (tr-TR) locale

---

docs/pages/_app.js

Add links to v8/next in the app header.

[docs] Add `next` version links

---

packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx
packages/x-date-pickers-pro/src/DesktopDateTimeRangePicker/tests/DesktopDateTimeRangePicker.test.tsx
packages/x-date-pickers-pro/src/internals/utils/date-range-manager.test.ts
packages/x-date-pickers-pro/src/internals/utils/date-range-manager.ts

Fixes https://github.com/mui/mui-x/issues/15405.

[DateTimeRangePicker] Use time in `referenceDate` when selecting date

---

.eslintrc.js

This change should allow us to prevent issues like this: https://github.com/mui/mui-x/pull/15375/commits/0baadae71c09825e875753382b2516957d93e6bf
```tsx
import { SizeProvider } from '../../../../x-charts/src/context/SizeProvider';
```

[code-infra] Prevent relative imports across packages

---

docs/data/data-grid/column-spanning/column-spanning.md
docs/data/data-grid/list-view/list-view.md
docs/data/data-grid/row-spanning/row-spanning.md
docs/data/data-grid/server-side-data/ServerSideDataGrid.js
docs/data/data-grid/server-side-data/ServerSideDataGrid.tsx
docs/data/data-grid/server-side-data/ServerSideDataGrid.tsx.preview
docs/data/data-grid/server-side-data/ServerSideDataGridTTL.js
docs/data/data-grid/server-side-data/ServerSideDataGridTTL.tsx
docs/data/data-grid/server-side-data/ServerSideDataGridTTL.tsx.preview
docs/data/data-grid/server-side-data/index.md
docs/data/data-grid/server-side-data/row-grouping.md
docs/data/data-grid/server-side-data/tree-data.md
docs/data/pages.ts
docs/pages/x/react-data-grid/server-side-data/aggregation.js
docs/pages/x/react-data-grid/server-side-data/index.js
docs/pages/x/react-data-grid/server-side-data/infinite-loading.js
docs/pages/x/react-data-grid/server-side-data/lazy-loading.js
docs/pages/x/react-data-grid/server-side-data/row-grouping.js
docs/pages/x/react-data-grid/server-side-data/tree-data.js
packages/x-data-grid/src/models/gridDataSource.ts

Issues I saw in https://master--material-ui-x.netlify.app/x/react-data-grid/server-side-data/ during the last monthly meeting presentation. Faster to open a PR.
Preview: https://deploy-preview-15330--material-ui-x.netlify.app/x/react-data-grid/server-side-data/
**Off-topic**
- There are JS errors on that page http://0.0.0.0:3001/x/react-data-grid/server-side-data/
- The page transition speed between those docs pages is way too slow, >300ms on a high-end laptop. It seems to be a wide spread issue. It's incredibly annoying from a UX perspective, root cause is part of it is docs-infra, part of it is MUI System, part of it is data grid. Great would be 100ms or lower.

[docs][data grid] Polish Server-side data section

---

packages/x-date-pickers/src/DesktopDatePicker/tests/field.DesktopDatePicker.test.tsx
packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts
packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.types.ts

[pickers] Always use `props.value` when it changes

---

packages/x-date-pickers/src/internals/components/PickersToolbar.tsx

Noticed it while working on Time Range Picker.

[pickers] Fix unused code in `PickersToolbar` component

---

packages/x-charts/src/ChartsTooltip/contentDisplayed.test.tsx
packages/x-charts/src/ScatterChart/ScatterChart.test.tsx
packages/x-charts/src/ScatterChart/ScatterChart.tsx

Fix regression from #15154 where the default tooltip was changed to `axis` for `ScatterChart`

[charts] Fix `ScatterChart` tooltip wrong defaults

---

packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx
packages/x-date-pickers-pro/src/internals/hooks/useMultiInputRangeField/useMultiInputDateRangeField.ts
packages/x-date-pickers-pro/src/internals/hooks/useMultiInputRangeField/useMultiInputDateTimeRangeField.ts
packages/x-date-pickers-pro/src/internals/hooks/useMultiInputRangeField/useMultiInputTimeRangeField.ts
packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx
packages/x-date-pickers/src/DigitalClock/DigitalClock.tsx
packages/x-date-pickers/src/MonthCalendar/MonthCalendar.tsx
packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClock.tsx
packages/x-date-pickers/src/TimeClock/TimeClock.tsx
packages/x-date-pickers/src/YearCalendar/YearCalendar.tsx
packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts
packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts
packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.types.ts
packages/x-date-pickers/src/internals/hooks/useValueWithTimezone.test.tsx
packages/x-date-pickers/src/internals/hooks/useValueWithTimezone.ts

Part of #14809
I took the opportunity to test this hook
I will do a 2nd PR to add a warning when passing `timezone="UTC"`

[pickers] Use `props.referenceDate` timezone when `props.value` and `props.defaultValue` are not defined

---

packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx

Fixes #15529 
The `isLastColumn` value was not always correct, depending on the columns in view. This simplifies the check so that it only takes into account whether the column group is the last in the row.

[DataGrid] Fix last separator not being hidden when grid is scrollable

---

CHANGELOG.md
package.json
packages/x-charts-pro/package.json
packages/x-charts-vendor/package.json
packages/x-charts/package.json
packages/x-codemod/package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-internals/package.json
packages/x-license/package.json
packages/x-tree-view-pro/package.json
packages/x-tree-view/package.json
scripts/releaseChangelog.mjs

If you have any idea for the highlight, feel free to add them :)

v8.0.0-alpha.1

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/esES.ts

Related to https://github.com/mui/mui-x/issues/3211

[l10n] Improve Spanish(es-ES) locale

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/ptBR.ts

[l10n] Improve Portuguese (Brazil) (pt-BR) locale

---

packages/x-data-grid/src/components/toolbar/GridToolbarColumnsButton.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarDensitySelector.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarExportContainer.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarFilterButton.tsx

Fixed the order of props being spread to toolbar items. Applying props to the individual toolbar items should take precedence over slot props applied at the root level.
Also added the ability to override badge props for `GridToolbarFilterButton`.
Fixes #13416
Closes #15550

[DataGrid] Fix order of spread props on toolbar items

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/zhCN.ts

improve Chinese (zh-CN) locale about prompt control labels

[l10n] Improve Chinese (zh-CN) locale

---

CHANGELOG.md
docs/pages/x/api/data-grid/grid-api.json
docs/translations/api-docs/data-grid/grid-api.json
packages/x-data-grid/src/hooks/features/dimensions/gridDimensionsApi.ts
packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts

We stopped using it in https://github.com/mui/mui-x/pull/15549, and it's not needed anymore.
- The `apiRef.current.resize` method was removed.

[DataGrid] Remove unused `resize` method

---

packages/x-charts/src/hooks/useInteractionItemProps.ts

[charts] Prevent invalid `releasePointerCapture`

---

.eslintrc.js
packages/x-charts-pro/src/BarChartPro/BarChartPro.tsx
packages/x-charts-pro/src/ChartContainerPro/ChartContainerPro.tsx
packages/x-charts-pro/src/Heatmap/heatmapClasses.ts
packages/x-charts-pro/src/LineChartPro/LineChartPro.tsx
packages/x-charts-pro/src/context/CartesianProviderPro/createAxisFilterMapper.ts
packages/x-charts-pro/src/internals/utils/releaseInfo.ts
packages/x-charts/src/ChartsAxis/axisClasses.ts
packages/x-charts/src/ChartsLegend/chartsLegendClasses.ts
packages/x-charts/src/ChartsTooltip/ChartsTooltipTable.ts
packages/x-charts/src/models/axis.ts

[charts] Flatten imports from `@mui/utils` and `@mui/system`

---

packages/x-data-grid/src/components/cell/GridCell.tsx

Fixes the performance issue described in #15615 
We had about 150ms of scripting overhead when updating rows fast on typing via external filters (e.g. typing 5 letters, so 5 updates = 150ms in ~1s of user interaction). The larger the viewport, the larger the overhead. After this small change, all of it is gone, and it's mostly layout updates now.

[DataGrid] Remove try/catch from `GridCell` due to performance issues

---

packages/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx
packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts

Suggestion reported in https://github.com/mui/mui-x/issues/15459#issuecomment-2499270469

[DataGrid] Clear timers on unmount

---

docs/pages/x/api/charts/charts-tooltip-container.json
docs/pages/x/api/charts/charts-tooltip.json
docs/pages/x/api/charts/heatmap-tooltip.json
packages/x-charts-pro/src/Heatmap/HeatmapTooltip.tsx
packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx
packages/x-charts/src/ChartsTooltip/ChartsTooltipContainer.tsx

Fix https://github.com/mui/mui-x/pull/15575#discussion_r1856379685. It's a quick win, so why not. The solution is to copy https://mui.com/material-ui/api/popper/#popper-prop-anchorEl.
**Before**: https://master--material-ui-x.netlify.app/x/api/charts/charts-tooltip/#props
**After**. https://deploy-preview-15625--material-ui-x.netlify.app/x/api/charts/charts-tooltip/#props

[docs][charts] Fix anchorEl API page

---

docs/data/tree-view/tree-item-customization/tree-item-customization.md

Patch #15066. It's buggy, it creates a layout shift, so the anchor links don't work correct:
https://github.com/user-attachments/assets/b68bc57b-0fa0-485e-a87d-8ab35523482c
After: https://deploy-preview-15626--material-ui-x.netlify.app/x/react-tree-view/tree-item-customization/

[docs][tree view] Fix layout shift image

---

packages/x-data-grid-pro/src/components/headerFiltering/GridHeaderFilterCell.tsx
packages/x-data-grid-pro/src/tests/filtering.DataGridPro.test.tsx
packages/x-data-grid/src/tests/filtering.DataGrid.test.tsx

Closes https://github.com/mui/mui-x/issues/15524
Related to https://github.com/mui/mui-x/pull/15252
Preview - https://deploy-preview-15528--material-ui-x.netlify.app/x/react-data-grid/filtering/header-filters/

[DataGridPro] Fix header filtering with `boolean` column type

---

docs/data/data-grid/list-view/list-view.md

Accidentally left the selectors section in the list view docs despite there being no selectors to document.

[docs] Remove selectors section from list view docs

---

packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts
packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx

This change enables testing with Happy DOM without annoying warnings popping up. Fixes #10374.
Detect HappyDOM like jsdom through the user agent string to avoid width and height warnings during tests.

[x-data-grid][hooks] Change test dom check from /jsdom/ to /jsdom|HappyDOM/.

---

packages/x-data-grid-pro/src/hooks/features/dataSource/useGridDataSource.ts

This PR resolves an issue where the pagination displays an incorrect number of rows when fetching data from an API using the `unstable_dataSource` prop.
**Reproduction:**
1. Visit Server side data docs, [with data source](https://mui.com/x/react-data-grid/server-side-data/#:~:text=Copy-,With%20data%20source,-With%20the%20data) section
2. Apply a filter that matches no items (for instance, quantity = 9999)
**Actual behavior:**
1. The displayed rows counter shows 100 items
2. You can navigate between pages
This contrasts with client-side pagination, where the counter shows “0–0 of 0” when no results are found after applying a filter.
**Expected behavior:**
The rows counter should reflect the actual number of available rows, showing “0–0 of 0” when no data matches the applied filter, …

[DataGridPro] Fix pagination state not updating if the data source response has no rows

---

docs/data/migration/migration-data-grid-v7/migration-data-grid-v7.md

Added two items I see in the [breaking change section in the release PR](https://github.com/mui/mui-x/pull/15656/files) that were not in the migration guide

[docs] Improve migration guide

---

docs/data/date-pickers/base-concepts/base-concepts.md

Fix #15654.
The docs theme augmentation example is incorrect.
The provided code never did anything, and at some point, we removed the keys for `styleOverrides`, where they did not work, which makes this code example completely broken. 🙈

[docs] Fix Pickers theme augmentation example

---

packages/x-data-grid-pro/src/hooks/features/rowPinning/useGridRowPinningPreProcessors.ts

Fixes https://github.com/mui/mui-x/issues/15302
Before: https://codesandbox.io/p/sandbox/purple-grass-5dtr6k
After: https://codesandbox.io/p/sandbox/objective-cori-ss3hhh

[DataGridPro] Cleanup pinned rows on removal

---

packages/x-codemod/src/v8.0.0/preset-safe/preset-safe.test.ts

Fixes https://github.com/mui/mui-x/actions/runs/12124933846/job/33803737679

[code-infra] Check if `preset-safe` folder exists in codemod test

---

packages/x-data-grid-pro/src/tests/columns.DataGridPro.test.tsx
test/karma.conf.js

Fixes inconsistencies we had in a few tests, where tests were passing in CI, but failing locally or vice versa.
It turns out, that the headless Chrome in Circle CI had no hover capabilities, therefore it was applying `@media (hover: none)` styles, while locally it applied `@media (hover: hover)` styles.
Adding `primaryHoverType=2` enables hover capabilities for the headless Chrome in CI.

[test] Force hover in headless Chrome

---

packages/x-codemod/README.md
packages/x-codemod/src/v8.0.0/data-grid/preset-safe/actual.spec.tsx
packages/x-codemod/src/v8.0.0/data-grid/preset-safe/expected.spec.tsx
packages/x-codemod/src/v8.0.0/data-grid/preset-safe/index.ts
packages/x-codemod/src/v8.0.0/data-grid/preset-safe/preset-safe.test.ts
packages/x-codemod/src/v8.0.0/preset-safe/index.ts

Adds missing `preset-safe` for the data grid
https://github.com/mui/mui-x/pull/15659 helped detect that
I have added pickers section to the readme
Also, I have aligned formatting for the diffs in the readme (spacing for changed and unchanged lines)

[codemod] Add missing `preset-safe` for the data-grid

---

docs/data/migration/migration-data-grid-v7/migration-data-grid-v7.md
docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
docs/translations/api-docs/data-grid/data-grid-premium/data-grid-premium.json
docs/translations/api-docs/data-grid/data-grid-pro/data-grid-pro.json
docs/translations/api-docs/data-grid/data-grid/data-grid.json
packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
packages/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx
packages/x-data-grid/src/DataGrid/DataGrid.tsx
packages/x-data-grid/src/constants/dataGridPropsDefaultValues.ts
packages/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts
packages/x-data-grid/src/models/props/DataGridProps.ts

Closes https://github.com/mui/mui-x/issues/15480
- The `rowPositionsDebounceMs` prop was removed.

[DataGrid] Remove `rowPositionsDebounceMs` prop

---

docs/data/migration/migration-pickers-v7/migration-pickers-v7.md

Address suggestion raised in: https://github.com/mui/mui-x/pull/14651#discussion_r1855221788
Improve the description of the accessible DOM structure section with more information, clarifying the timeline and reasons for moving towards it.

[docs] Improve Pickers accessible DOM migration section description

---

docs/data/data-grid/localization/data.json
docs/data/date-pickers/localization/data.json
packages/x-data-grid/src/locales/roRO.ts
packages/x-date-pickers/src/locales/roRO.ts

Improve Romanian (ro-RO) locale: I have added the missing keys #3211

[l10n] Improve Romanian (ro-RO) locale

---

packages/x-data-grid-premium/src/hooks/features/rowGrouping/createGroupingColDef.tsx
packages/x-data-grid-premium/src/tests/rowGrouping.DataGridPremium.test.tsx

Fixes #15717 
Value formatters rely sometimes on the column definition.
Group column should use the original column's definition to format the value properly
Before: https://codesandbox.io/p/sandbox/valueoption-group-before-3zv4cv
After: https://codesandbox.io/p/sandbox/valueoption-group-after-cnf49r

[DataGridPremium] Fix group column ignoring `valueOptions` for `singleSelect` column type

---

packages/x-charts/src/ChartsAxis/ChartsAxis.tsx
packages/x-charts/src/ChartsLegend/useAxis.ts
packages/x-charts/src/ChartsTooltip/useAxisTooltip.tsx
packages/x-charts/src/ChartsTooltip/useItemTooltip.tsx
packages/x-charts/src/PieChart/PiePlot.tsx
packages/x-charts/src/ScatterChart/ScatterPlot.tsx
packages/x-charts/src/hooks/useColorScale.ts
packages/x-charts/src/hooks/useZAxis.ts

From working on store refactoring, I noticed it would be simpler if we hide the data getter logic behind a hook
`useZAxis` get me the data, I don't care if it's a provider, a selector, or just a random value :)

[charts] Only access store values by using hooks

---

docs/src/modules/utils/postProcessImport.test.ts
docs/src/modules/utils/postProcessImport.ts

Sync/update versions resolved for use in sandboxes.

[docs] Use date library version from package dev dependencies for sandboxes

---

packages/x-date-pickers/src/hooks/useClearableField.tsx
packages/x-date-pickers/src/internals/components/PickerProvider.tsx

Part of #14475
Extracted from #15671

[pickers] Use the new `ownerState` in `useClearableField`

---

packages/x-charts/src/ScatterChart/ScatterChart.test.tsx
packages/x-charts/src/ScatterChart/extremums.ts
packages/x-charts/src/ScatterChart/formatter.ts

Fix #15801
I hesitated to keep `undefined` values to be able to distinguish `undefined` and `null`.
But a scatter point where either x or y is not defined is impossible to represent
```js
Math.min(null, null) // returns 0
Math.min(undefined, null) // returns NaN
```
If you're ok with the fix I will add a test to prevent future regression

[charts] Fix scatter dataset with missing data

---

packages/x-charts/src/ChartsTooltip/ChartsAxisTooltipContent.tsx

Fixed a speling typos mistake in `ChartsAxisTooltipContent` component

[charts] Fix internal spelling typo

---

packages/x-date-pickers/src/PickersLayout/PickersLayout.tsx
packages/x-date-pickers/src/PickersLayout/PickersLayout.types.ts
packages/x-date-pickers/src/PickersLayout/usePickerLayout.tsx

Part of https://github.com/mui/mui-x/issues/14475
Improves consistency with #15777

[pickers] Rename layout `ownerState` property from `isRtl` to `layoutDirection`

---

packages/x-license/src/utils/licenseErrorMessageUtils.ts

Fixes https://github.com/mui/mui-x/issues/15765
It is a workaround until https://github.com/codesandbox/codesandbox-client/issues/8673 is resolved
FYI @flaviendelangle 
It should fix the Codesandbox of [this example](https://mui.com/x/react-tree-view/rich-tree-view/ordering/#enable-drag-amp-drop-re-ordering) as well

[license] Use `console.log` for the error message on Codesandbox to avoid rendering error

---

packages/x-charts/src/ChartsGrid/ChartsHorizontalGrid.tsx
packages/x-charts/src/ChartsGrid/ChartsVerticalGrid.tsx

[charts] Fix key generation for the ChartsGrid (@alexfauquette)

---

docs/data/data-grid/export/export.md
docs/data/data-grid/getting-started/getting-started.md
docs/data/introduction/overview/overview.md
packages/x-charts-pro/README.md
packages/x-charts/README.md
packages/x-data-grid-premium/README.md
packages/x-data-grid-pro/README.md
packages/x-data-grid/README.md
packages/x-date-pickers-pro/README.md
packages/x-date-pickers/README.md
packages/x-tree-view-pro/README.md
packages/x-tree-view/README.md
renovate.json
scripts/l10n.ts

The problem https://next.mui.com/x/introduction/#mui-x-vs-mui-core
https://mui-org.slack.com/archives/C04U3R2V9UK/p1733879862542189
At the same time, this is taking more steps to completely get ride of the notion of "MUI Core".

[docs] Fix outdated link to handbook

---

packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts
packages/x-data-grid/src/tests/rowSpanning.DataGrid.test.tsx

Fixes #15819 
- Before: https://grfpfs.csb.app/
- After: https://wglxzl.csb.app/
Addresses a corner case, whenever rows get updated and the (index based) `range` doesn't change, it results in skipping the necessary re-computation of row spanning state.

[DataGrid] Trigger row spanning computation on rows update

---

packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts
packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
packages/x-data-grid/src/tests/layout.DataGrid.test.tsx

Fixes #15721 
Before: https://codesandbox.io/p/sandbox/15850-after-forked-7yfwdz
After: https://codesandbox.io/p/sandbox/15850-after-pxr26t

[DataGrid] Round dimensions to avoid subpixel rendering error

---

docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
packages/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx
packages/x-data-grid/src/DataGrid/DataGrid.tsx
packages/x-data-grid/src/models/props/DataGridProps.ts

Fix #15614 
Context: https://github.com/mui/mui-x/pull/15522#discussion_r1851629848

[DataGrid] Deprecate `indeterminateCheckboxAction` prop

---

packages/x-tree-view/src/internals/models/plugin.ts
packages/x-tree-view/src/internals/plugins/useTreeViewExpansion/useTreeViewExpansion.selectors.ts
packages/x-tree-view/src/internals/plugins/useTreeViewExpansion/useTreeViewExpansion.ts
packages/x-tree-view/src/internals/plugins/useTreeViewExpansion/useTreeViewExpansion.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewExpansion/useTreeViewExpansion.utils.ts
packages/x-tree-view/src/useTreeItem/useTreeItem.ts
test/utils/tree-view/fakeContextValue.ts

There is no need for this variable in the render.

[TreeView] Move the `expansionTrigger` variable from the context value to the state

---

packages/x-data-grid-premium/src/components/GridColumnMenuAggregationItem.tsx
packages/x-data-grid-premium/src/components/GridColumnMenuRowGroupItem.tsx
packages/x-data-grid-premium/src/components/GridColumnMenuRowUngroupItem.tsx
packages/x-data-grid-pro/src/components/GridColumnMenuPinningItem.tsx
packages/x-data-grid/src/components/cell/GridActionsCellItem.tsx
packages/x-data-grid/src/components/menu/columnMenu/menuItems/GridColumnMenuFilterItem.tsx
packages/x-data-grid/src/components/menu/columnMenu/menuItems/GridColumnMenuHideItem.tsx
packages/x-data-grid/src/components/menu/columnMenu/menuItems/GridColumnMenuManageItem.tsx
packages/x-data-grid/src/components/menu/columnMenu/menuItems/GridColumnMenuSortItem.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarDensitySelector.tsx
packages/x-data-grid/src/material/index.tsx
packages/x-data-grid/src/models/gridSlotsComponentsProps.ts

`ListItemText` and `ListItemIcon` are now abstracted away in `baseMenuItem`. This interface (with icons as props) is easier to adapt to other design systems than the other way around.
This is a change to the public API, so it's a breaking change.

[DataGrid] Refactor: move ListItem(Text|Icon) to leaf import

---

docs/data/charts/scatter-demo/MultipleYAxesScatterChart.js
docs/data/charts/scatter-demo/MultipleYAxesScatterChart.tsx
docs/data/charts/scatter/ColorScale.js
docs/data/charts/scatter/ColorScale.tsx
docs/data/charts/styling/ColorTemplate.js
docs/data/charts/styling/ColorTemplate.tsx
docs/data/charts/styling/MuiColorTemplate.js
docs/data/charts/styling/MuiColorTemplate.tsx
packages/x-charts-pro/src/ScatterChartPro/ScatterChartPro.tsx
packages/x-charts/src/ScatterChart/formatter.ts
packages/x-charts/src/models/seriesType/scatter.ts

We recently introduced the possibility that some scatter chart item can be `null` if the x or y key is missing

[charts] Fix scatter the chart value type if `null`

---

packages/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts

[DataGrid] Consider `columnGroupHeaderHeight`  prop in `getTotalHeaderHeight` method (@k-rajat19)

---

packages/x-data-grid-premium/src/hooks/features/rowGrouping/useGridRowGroupingPreProcessors.ts
packages/x-data-grid-premium/src/tests/rowGrouping.DataGridPremium.test.tsx

Fixes https://github.com/mui/mui-x/issues/15808
Before: https://codesandbox.io/p/sandbox/runtime-night-typftk
After: https://codesandbox.io/p/sandbox/delicate-hill-qlv29f

[DataGridPremium] Fix column pinning with checkbox selection and row grouping

---

docs/package.json

Fixes #15957 – production profiler adds overhead to rendering, which hurts performance. For whatever reason the performance impact is higher in next15, impacting scroll performance visibly.

[docs] remove production profiler from docs build

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/nlNL.ts

Cherry-pick of #15920 as the `needs cherry-pick` label didn't trigger the action. 🙈

[l10n] Improve Dutch (nl-NL) locale (#15920) @JoepVerkoelen

---

docs/data/data-grid/custom-columns/EditingWithDatePickers.js
docs/data/data-grid/custom-columns/EditingWithDatePickers.tsx
packages/x-date-pickers/src/PickersTextField/PickersTextField.tsx

Created from an investigation on https://github.com/mui/mui-x/issues/15965 and https://github.com/mui/mui-x/pull/15967.

[docs] Refactor Data Grid with Date Pickers example

---

scripts/README.md

https://github.com/mui/mui-x/pull/16010#discussion_r1898538345

[core] Clarify the release strategy

---

docs/data/migration/migration-pickers-v7/migration-pickers-v7.md

Apply @michelengelen's proposal on every breaking change

[docs] Unify the wording of the pickers slots breaking changes

---

docs/data/migration/migration-pickers-v7/migration-pickers-v7.md
packages/x-date-pickers-pro/src/models/range.ts
packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts
scripts/x-date-pickers-pro.exports.json

I noticed the comment asking to remove it

[pickers] Remove `NonEmptyDateRange` type

---

scripts/README.md

Turns out, [`lerna version` only works with annotated tags](https://github.com/lerna/lerna/issues/3698), so we should avoid manually creating unannotated tags.
> In practice, the problem with unannotated tags is that Lerna will use the wrong tag as a last-release reference and will bump packages that had no changes since the actual last release. It's not an issue on its own, but when this happens the release engineer might decide to skip some packages manually which is error-prone.

[core] Update the `release:version` docs

---

docs/data/date-pickers/custom-field/BrowserV7MultiInputRangeField.js
docs/data/date-pickers/custom-field/BrowserV7MultiInputRangeField.tsx
docs/data/date-pickers/custom-field/JoyV6MultiInputRangeField.js
docs/data/date-pickers/custom-field/JoyV6MultiInputRangeField.tsx

I noticed in #15505 that those two demos are not using the same separator as the built-in one.
I'm extracting this change to avoid Argos diffs on the main PR.

[docs] Fix inconsistent multi input range field separators

---

packages/x-date-pickers/src/DesktopDatePicker/tests/DesktopDatePicker.test.tsx
packages/x-date-pickers/src/PickersActionBar/PickersActionBar.tsx
packages/x-date-pickers/src/PickersLayout/usePickerLayout.tsx
scripts/x-date-pickers-pro.exports.json
scripts/x-date-pickers.exports.json

Follow up on https://github.com/mui/mui-x/pull/15944#discussion_r1900791135.
- Memoize `PickersActionBar`
- Stop passing `ownerState` to the slot component to avoid breaking memoization
- Add tests to ensure the optimization does not get lost among changes

[pickers] Memoize `<PickersActionBar />`

---

packages/x-data-grid/src/models/gridBaseSlots.ts
packages/x-data-grid/src/models/gridSlotsComponentsProps.ts

Part of the design-agnostic work.
Create base tooltip props.

[DataGrid] Refactor: create tooltip props

---

packages/x-data-grid-premium/src/hooks/features/aggregation/createAggregationLookup.ts
packages/x-data-grid-premium/src/hooks/features/aggregation/gridAggregationUtils.ts
packages/x-data-grid-premium/src/hooks/features/aggregation/useGridAggregation.ts
packages/x-data-grid-premium/src/hooks/features/aggregation/useGridAggregationPreProcessors.tsx

Extracted from https://github.com/mui/mui-x/pull/9877
Aggregation is one of the core features for pivoting. It often involves aggregating dozens of columns.
This PR improves aggregation calculation performance with row grouping and multiple aggregation rules.
I've changed the way we calculate aggregation value for each row group.
**Before**
1. **Loop**: Iterate over aggregation rules (`getGroupAggregatedValue`). For each aggregation field:
2. Get the child `rowIds` for the row group (`getRowGroupChildren`). Requires traversing the group tree.
3. **Loop**: Iterate over child `rowIds` and calculate the aggregated value
Optimizations:
- Point 2 can be moved up to do `1 x row_group`, as opposed to `1 x row_group x aggregation_rule`.
- In the inner loop (point 3) we return early for some rows, …

[DataGridPremium] Improve aggregation performance for multiple columns

---

packages/x-charts/src/ChartsLabel/ChartsLabelGradient.test.tsx
packages/x-charts/src/ChartsLabel/ChartsLabelGradient.tsx

Resolves https://github.com/mui/mui-x/issues/16094

[charts] Support `rtl` for gradient legend

---

.github/workflows/create-cherry-pick-pr.yml

This is to improve the filtering for targets. For some reason the filtering with the wildcard character was not working for version branches.
I discovered while working on this that those workflows don't use the current master branch as reference for workflow files, so each workflow needs to be present on the branch it is used. For now this only applies to the cherry-pick PR action on version branches, so a cherry-pick is needed for this PR to apply the changes to them as well.

[infra] Improve cherry-pick action target list

---

docs/data/migration/migration-pickers-v7/migration-pickers-v7.md
packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx
packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerToolbar.tsx
packages/x-date-pickers-pro/src/DateTimeRangePicker/DateTimeRangePickerTabs.tsx
packages/x-date-pickers-pro/src/DateTimeRangePicker/DateTimeRangePickerTimeWrapper.tsx
packages/x-date-pickers-pro/src/DateTimeRangePicker/DateTimeRangePickerToolbar.tsx
packages/x-date-pickers-pro/src/internals/hooks/models/index.ts
packages/x-date-pickers-pro/src/internals/hooks/models/useRangePicker.ts
packages/x-date-pickers-pro/src/internals/hooks/useEnrichedRangePickerField.ts
packages/x-date-pickers-pro/src/internals/hooks/useRangePosition.ts

Similar to #16044
No breaking change compared to v7, no behavior change.
Just a small API consistency improvement.

[pickers] Rename `onRangePositionChange` into `setRangePosition` in `usePickerRangePositionContext`

---

packages/x-data-grid-pro/src/tests/columns.DataGridPro.test.tsx
packages/x-data-grid/src/components/GridRow.tsx
packages/x-data-grid/src/components/containers/GridRootStyles.ts
packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx
packages/x-data-grid/src/tests/rows.DataGrid.test.tsx
test/regressions/data-grid/DataGridBordered.js
test/regressions/data-grid/DataGridPinnedColumnsBordered.js
test/regressions/data-grid/DataGridPinnedColumnsScrollbars.js
test/regressions/data-grid/DataGridPinnedColumnsWithGap.js
test/regressions/index.test.ts

Cherry-pick of https://github.com/mui/mui-x/pull/15107
I just realized we forgot to cherry-pick it.

[DataGrid] Fix resizing right pinned column (@KenanYusuf)

---

packages/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx

Cherry-pick of https://github.com/mui/mui-x/pull/16202
It turned out that this test is flaky on v7 too: https://app.circleci.com/pipelines/github/mui/mui-x/78395/workflows/58f35812-b942-4f49-ae3a-f52af19d4e5b/jobs/446330?invite=true#step-106-8045_89

[test] Fix flaky column pinning unit test 

---

packages/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx

Similar to https://github.com/mui/mui-x/pull/16202, applied to other column pinning tests.
Other tests in that block sometimes fail too: https://app.circleci.com/pipelines/github/mui/mui-x/78454/workflows/6eaa6ae9-bcbc-4070-82cd-31a3bd9ca685/jobs/446701?invite=true#step-106-8044_90

[test] Fix flaky column pinning tests

---

packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx
packages/x-date-pickers/src/DateField/tests/selection.DateField.test.tsx
packages/x-date-pickers/src/internals/hooks/useField/useField.ts
packages/x-date-pickers/src/internals/hooks/useField/useFieldV6TextField.ts
packages/x-date-pickers/src/internals/hooks/useField/useFieldV7TextField.ts

Fixes https://github.com/mui/mui-x/issues/16201.
~The change resets the `selectedSections` to the `activeSectionIndex` when modification is done with navigation keys (Arrows, End, PageUp, etc.) just like with letters.~
Wrong initial assumption, the selected section was only being reset on letter/digit editing when a jump to the next section was requested.
I've updated the approach to always reset the `all` selection state when doing a manual modification.

[fields] Reset `all` selected state on section edit

---

packages/x-charts-pro/src/internals/plugins/useChartProZoom/creatZoomLookup.ts
packages/x-charts-pro/src/internals/plugins/useChartProZoom/useChartProZoom.selectors.ts
packages/x-charts-pro/src/internals/plugins/useChartProZoom/useChartProZoom.ts
packages/x-charts-pro/src/internals/plugins/useChartProZoom/useChartProZoom.types.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/index.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianAxis.selectors.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianAxis.types.ts

The next.mui.com/x/react-charts/zoom-and-pan/#zooming-options were broken because the zoomOptionLookup that maps axis id to its zoom options was computed on the initial render and never updated.
This PR removes it from the internal state and moves it to selectors as a derived state from and axis config.
It's still computed in the params defaultizer because it's required to initialize the zoom state

[charts] Fix zoom option reactivity

---

packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderFilterIconButton.tsx
packages/x-data-grid/src/hooks/features/preferencesPanel/gridPreferencePanelSelector.ts
packages/x-data-grid/src/hooks/features/preferencesPanel/index.ts

As a side-note to #16257, I saw that filter buttons are unnecessarily mounted to all columns, resulting in `n = # of rendered columns` state subscriptions and re-renders whenever `preferencePanel` state is changed. Added a simple wrapper for the default implementation as well as a state selector with params. A wrapper is necessary to still allow users to mount it to every column if they wish to do so.

[DataGrid] Only try to mount filter button if there are filters present

---

docs/data/charts/axis/axis.md

Found while answering a zendesk ticket.
We update the DevEx but not the docs

[docs] Fix `domainLimit` definition

---

docs/data/charts/lines/ExpandingStep.js
docs/data/charts/lines/ExpandingStep.tsx
docs/data/charts/lines/InterpolationDemoNoSnap.js
docs/data/charts/lines/lines.md
docs/pages/x/api/charts/line-series-type.json
docs/translations/api-docs/charts/line-series-type.json
packages/x-charts/src/LineChart/AreaPlot.tsx
packages/x-charts/src/LineChart/LinePlot.tsx
packages/x-charts/src/models/seriesType/line.ts

Fix #16183
For me that's not realy a breaking change. It's more of an improvement

[charts] Expand line with step interpolation

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/urPK.ts

[l10n] Improve Urdu (ur-PK) locale (#16081) (@AxharKhan)

---

docs/data/data-grid/column-groups/column-groups.md
docs/data/data-grid/pivoting/pivoting.md
docs/data/data-grid/row-grouping/row-grouping.md
docs/data/data-grid/row-ordering/row-ordering.md
docs/data/data-grid/server-side-data/lazy-loading.md
docs/data/date-pickers/date-range-picker/date-range-picker.md
docs/data/date-pickers/time-range-picker/time-range-picker.md
pnpm-lock.yaml

This PR cleans up the copy for planned feature callouts and standardizes the style and format for describing planned features: 
- callout comes first, then feature description
- "With this feature, users would be able to..."

[docs] Revise planned feature callouts and descriptions

---

packages/x-charts/src/internals/components/ChartsAxesGradients/ChartsPiecewiseGradient.tsx

Cherry-pick of https://github.com/mui/mui-x/pull/16131
Fixes https://github.com/mui/mui-x/issues/16294

[charts] Handle case where gradient stop `offset` could be `Infinite` (@JCQuintas)

---

packages/x-data-grid-premium/src/hooks/utils/useGridApiRef.ts
packages/x-data-grid-pro/src/hooks/utils/useGridApiRef.ts

Re-exported hook needs to be explicitly typed again to prevent type evaluation during build time to `React.RefObject`
Content of `useGridApiRef.d.ts` for the Pro package
before changes:
```typescript
import { GridApiPro } from '../../models/gridApiPro';
export declare const useGridApiRef: () => import("react").RefObject<GridApiPro>;
```
after changes:
```typescript
import { RefObject } from '@mui/x-internals/types';
import { GridApiCommon } from '@mui/x-data-grid';
import { GridApiPro } from '../../models/gridApiPro';
export declare const useGridApiRef: <Api extends GridApiCommon = GridApiPro>() => RefObject<Api>;
```

[DataGridPro] Fix the return type of `useGridApiRef` for Pro and Premium packages on React < 19

---

packages/x-data-grid/src/components/toolbar/GridToolbarColumnsButton.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarDensitySelector.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarExportContainer.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarFilterButton.tsx

Fixes #16355 
`onClick` needs to come after `{...buttonProps}` to ensure the button behavior works as expected when an `onClick` prop is passed to the toolbar button.

[DataGrid] Fix order of `onClick` prop on toolbar buttons

---

packages/x-data-grid/src/DataGrid/DataGrid.tsx

The resizing feature was made available to community users in https://github.com/mui/mui-x/pull/12420, however, this outdated warning remains.
Noticed in https://app.circleci.com/pipelines/github/mui/mui-x/79506/workflows/aefe7b46-c0ae-4730-8f29-426877e0a865/jobs/452817

[DataGrid] Remove outdated warning

---

test/performance-charts/tests/BarChart.bench.tsx
test/performance-charts/tests/BarChartPro.bench.tsx
test/performance-charts/tests/LineChart.bench.tsx
test/performance-charts/tests/LineChartPro.bench.tsx
test/performance-charts/tests/ScatterChart.bench.tsx
test/performance-charts/tests/ScatterChartPro.bench.tsx

This PR is here to reduce the size of the perf bechnmark to make sure #16211 is not degrading perfs

[core] Reduce chart perf benchmark weight

---

packages/x-data-grid-premium/src/tests/dataSourceAggregation.DataGridPremium.test.tsx
packages/x-data-grid-pro/src/components/headerFiltering/GridHeaderFilterCell.tsx
packages/x-data-grid-pro/src/components/headerFiltering/GridHeaderFilterMenu.tsx
packages/x-data-grid-pro/src/components/headerFiltering/GridHeaderFilterMenuContainer.tsx
packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputBoolean.tsx
packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputDate.tsx
packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputMultipleSingleSelect.tsx
packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputMultipleValue.tsx
packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputSingleSelect.tsx
packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputValue.tsx
packages/x-data-grid/src/models/gridFilterInputComponent.ts

This fixes the warning on React 18 that is breaking the tests
https://app.circleci.com/pipelines/github/mui/mui-x/79788/workflows/e0f5c399-0631-4b3e-a933-7581381b7d66
It does not need a cherry pick.
Before merge:

[test] Fix console warnings while executing tests with React 18

---

packages/x-data-grid/src/components/containers/GridRootStyles.ts

Before: https://deploy-preview-16066--material-ui-x.netlify.app/x/react-data-grid/row-pinning/#usage-with-other-features
After: https://deploy-preview-16396--material-ui-x.netlify.app/x/react-data-grid/row-pinning/#usage-with-other-features

[DataGridPro] Fix pinned rows missing background

---

docs/data/charts/scatter/scatter.md
docs/pages/x/api/charts/scatter-series-type.json
packages/x-charts/src/PieChart/PieArcLabelPlot.tsx
packages/x-charts/src/PieChart/PieArcPlot.tsx
packages/x-charts/src/PieChart/dataTransform/transition.ts
packages/x-charts/src/PieChart/dataTransform/useTransformData.ts
packages/x-charts/src/PieChart/legend.ts
packages/x-charts/src/ScatterChart/Scatter.tsx
packages/x-charts/src/ScatterChart/formatter.ts
packages/x-charts/src/models/seriesType/pie.ts
packages/x-charts/src/models/seriesType/scatter.ts
test/performance-charts/tests/ScatterChart.bench.tsx
test/performance-charts/tests/ScatterChartPro.bench.tsx

- The `id` property is now optional on the `Pie` and `Scatter` data types.

[charts] Make `id` optional on `PieValueType` and `ScatterValueType`

---

packages/x-charts-pro/src/internals/plugins/useChartProZoom/creatZoomLookup.ts
packages/x-charts-pro/src/internals/plugins/useChartProZoom/useChartProZoom.selectors.ts
packages/x-charts-pro/src/internals/plugins/useChartProZoom/useChartProZoom.ts

Panning along x/y was buggy because all zoom option was associated to the x direction 🙈

[charts] Fix zoom panning

---

packages/x-data-grid-generator/src/hooks/useMockServer.ts
packages/x-data-grid-pro/src/hooks/features/dataSource/useGridDataSource.ts
packages/x-data-grid-pro/src/tests/dataSource.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/dataSourceTreeData.DataGridPro.test.tsx

Cherry-pick of https://github.com/mui/mui-x/pull/16101 and https://github.com/mui/mui-x/pull/16395

[DataGridPro] Fetch new rows only once when multiple models are changed in one cycle (@arminmeh)

---

packages/x-date-pickers/src/internals/hooks/useField/useFieldInternalPropsWithDefaults.ts
packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts
packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.types.ts

Noticed this regression while working on #16175
In range picker, you can edit the field when the view is opened, and it would automatically close the view when doing it.

[pickers] Do not close the picker when doing keyboard editing

---

renovate.json

Closes https://github.com/mui/mui-x/pull/14438.
To avoid having stale PR and keep getting updates for newer releases until we update our docs API generation.

[code-infra] Ignore renovate updates for `react-docgen` package

---

.circleci/config.yml

Brings https://github.com/mui/base-ui/pull/1405 / https://github.com/mui/material-ui/pull/45185 to this repo

[core] Fix corepack and pnpm installation in CircleCI

---

packages/x-data-grid-premium/src/hooks/utils/useGridApiContext.ts
packages/x-data-grid-pro/src/hooks/utils/useGridApiContext.ts

Same fix that has been applied to `useGridApiRef()` in https://github.com/mui/mui-x/pull/16328

[DataGridPro] Fix the return type of `useGridApiContext()` for Pro and Premium packages on React < 19

---

packages/x-date-pickers-pro/src/MobileDateRangePicker/MobileDateRangePicker.tsx
packages/x-date-pickers-pro/src/MobileDateRangePicker/tests/MobileDateRangePicker.test.tsx
packages/x-date-pickers-pro/src/MobileDateTimeRangePicker/MobileDateTimeRangePicker.tsx

Fixes https://github.com/mui/mui-x/issues/15943.
Override the `currentMonthCalendarPosition` prop to `1` on Mobile Pickers since we override `calendars` to avoid inconsistent behavior.

[DateRangePicker] Fix `currentMonthCalendarPosition` prop behavior on mobile

---

packages/x-data-grid-premium/src/hooks/features/aggregation/gridAggregationUtils.ts
packages/x-data-grid-premium/src/tests/aggregation.DataGridPremium.test.tsx

Hides the pinned aggregation row if there aren't any values to aggregate.
**Before**
[CodeSandbox](https://codesandbox.io/p/devbox/16466-aggregation-no-rows-overaly-after-forked-7h5rgz)
**After**
[CodeSandbox](https://codesandbox.io/p/sandbox/16466-after-tnvcfy)
Fixes #16453

[data grid] Fix "no rows" overlay not showing with active aggregation

---

packages/x-data-grid/src/components/menu/columnMenu/GridColumnMenuContainer.tsx

[DataGrid] Refactor: remove material MenuList import

---

docs/pages/x/api/charts/bar-chart-pro.json
docs/pages/x/api/charts/bar-chart.json
docs/pages/x/api/charts/chart-container.json
docs/pages/x/api/charts/chart-data-provider-pro.json
docs/pages/x/api/charts/chart-data-provider.json
docs/pages/x/api/charts/heatmap.json
docs/pages/x/api/charts/line-chart-pro.json
docs/pages/x/api/charts/line-chart.json
docs/pages/x/api/charts/pie-chart.json
docs/pages/x/api/charts/scatter-chart-pro.json
docs/pages/x/api/charts/scatter-chart.json
docs/pages/x/api/charts/spark-line-chart.json
packages/x-charts-pro/src/BarChartPro/BarChartPro.tsx
packages/x-charts-pro/src/ChartDataProviderPro/ChartDataProviderPro.tsx
packages/x-charts-pro/src/Heatmap/Heatmap.tsx
packages/x-charts-pro/src/LineChartPro/LineChartPro.tsx
packages/x-charts-pro/src/ScatterChartPro/ScatterChartPro.tsx
packages/x-charts/src/BarChart/BarChart.tsx
packages/x-charts/src/ChartContainer/ChartContainer.tsx
packages/x-charts/src/ChartDataProvider/ChartDataProvider.tsx
packages/x-charts/src/LineChart/LineChart.tsx
packages/x-charts/src/PieChart/PieChart.tsx
packages/x-charts/src/ScatterChart/ScatterChart.tsx
packages/x-charts/src/SparkLineChart/SparkLineChart.tsx
packages/x-charts/src/internals/plugins/corePlugins/useChartSeries/useChartSeries.types.ts

Update default value for `colors` in docs since it was incorrectly set as `blueberryTwilightPalette`, while the correct value is `rainbowSurgePalette` ([1](https://github.com/mui/mui-x/blob/cff9176c4924100bc2d2bf36732c7926ed04608a/packages/x-charts/src/internals/plugins/corePlugins/useChartSeries/useChartSeries.ts#L51), [2](https://github.com/mui/mui-x/blob/b252b9a9562a69512b74d3cb89049be5591d908b/packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianAxis.ts#L234)).

[docs] Update colors default value

---

packages/x-data-grid-premium/src/tests/cellSelection.DataGridPremium.test.tsx

Avoid test failures due to a warning when running on React 18.
- https://app.circleci.com/pipelines/github/mui/mui-x/80660/workflows/2960b68a-efaa-44ad-bed2-2ac18642fbc8/jobs/459233
- https://app.circleci.com/pipelines/github/mui/mui-x/80660/workflows/2960b68a-efaa-44ad-bed2-2ac18642fbc8/jobs/459236

[test] Avoid test warning when running on React 18

---

package.json

I missed the root package when bumping 😢

[code-infra] Fix root package version

---

packages/x-data-grid/src/components/cell/GridActionsCell.tsx
packages/x-data-grid/src/material/index.tsx
packages/x-data-grid/src/models/gridBaseSlots.ts
packages/x-data-grid/src/models/gridSlotsComponentsProps.ts

Create base MenuList props. These are directly compatible with material props.

[DataGrid] Refactor: create base MenuList props

---

packages/x-charts-pro/src/internals/plugins/useChartProZoom/useChartProZoom.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createZoomLookup.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/index.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianAxis.selectors.ts

Fix https://github.com/mui/mui-x/pull/16507#discussion_r1949118858

[charts] Fix internal typo

---

packages/x-data-grid-premium/src/hooks/features/export/serializer/setupExcelExportWebWorker.ts
packages/x-data-grid-premium/src/hooks/features/export/serializer/utils.ts
packages/x-data-grid-premium/src/hooks/features/export/useGridExcelExport.tsx

The current logic looks wrong. Workers share the same pub-sub channel namespace. I believe it's why, e.g. https://revealjs.com/postmessage/ has a `namespace` property. You can reproduce a conflict by running
```bash
pnpm test:regressions:dev
```
and opening the page:
I don't know how to write a test for this effectively, so I skipped it. I initially noticed this improving slightly the visual regression flow in Material UI, saw an error in the console, which shouldn't be there.
Preview: https://deploy-preview-16020--material-ui-x.netlify.app/x/react-data-grid/export/#using-a-web-worker

[DataGridPremium] Namespace Excel export worker

---

docs/data/charts/sparkline/CustomYAxis.js
docs/data/charts/sparkline/CustomYAxis.tsx
docs/data/migration/migration-charts-v7/migration-charts-v7.md
docs/pages/x/api/charts/spark-line-chart.json
docs/translations/api-docs/charts/spark-line-chart/spark-line-chart.json
packages/x-charts/src/SparkLineChart/SparkLineChart.tsx
packages/x-codemod/README.md
packages/x-codemod/src/v8.0.0/charts/rename-sparkline-colors-to-color/actual.spec.tsx
packages/x-codemod/src/v8.0.0/charts/rename-sparkline-colors-to-color/expected.spec.tsx
packages/x-codemod/src/v8.0.0/charts/rename-sparkline-colors-to-color/index.ts
packages/x-codemod/src/v8.0.0/charts/rename-sparkline-colors-to-color/rename-sparkline-colors-to-color.test.ts

Remove `colors` prop from `SparkLineChart`. 
In https://github.com/mui/mui-x/pull/16477, I deprecated the `colors` prop, but we can still do breaking changes for v8. This will reduce the maintenance burden slightly. 
Also added codemod to migrate from the old `colors` prop to the new `color` prop.

[charts] Remove `colors` prop from `SparkLineChart`.

---

packages/x-charts/src/ChartsTooltip/ChartsTooltipContainer.tsx

Fixes https://github.com/mui/mui-x/issues/15736.
The tooltip offset on mobile now depends on its placement plus some offset to reduce the odds of it being displayed under the user's finger. 
Pardon my amateur video 😛:
https://github.com/user-attachments/assets/74905614-32c2-4cc8-913f-d79c513ea9ae
Tested on Safari iOS. It would be nice if someone could test it on an Android device as I don't have access to one.
I also don't have access to other touch formats (e.g., stylus/pen). It would be nice if we could test that.

[charts] Improve tooltip placement in mobile

---

packages/x-data-grid-premium/src/DataGridPremium/useDataGridPremiumComponent.tsx
packages/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts
packages/x-data-grid-pro/src/DataGridPro/useDataGridProComponent.tsx
packages/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.tsx
packages/x-data-grid/src/DataGrid/useDataGridComponent.tsx
packages/x-data-grid/src/hooks/features/clipboard/useGridClipboard.ts
packages/x-data-grid/src/hooks/utils/useGridNativeEventListener.ts

Cherry-pick of https://github.com/mui/mui-x/pull/16488

[DataGrid] Avoid `undefined` value for pagination `rowCount`

---

docs/data/migration/migration-data-grid-v7/migration-data-grid-v7.md
docs/pages/x/api/data-grid/grid-api.json
docs/translations/api-docs/data-grid/grid-api.json
packages/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts
packages/x-data-grid-premium/src/hooks/features/rowGrouping/useGridRowGrouping.tsx
packages/x-data-grid-pro/src/hooks/features/columnReorder/useGridColumnReorder.tsx
packages/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts
packages/x-data-grid/src/hooks/core/useGridStateInitialization.ts
packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx
packages/x-data-grid/src/hooks/features/columns/useGridColumns.tsx
packages/x-data-grid/src/hooks/features/editing/useGridCellEditing.ts
packages/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts
packages/x-data-grid/src/hooks/features/filter/useGridFilter.tsx
packages/x-data-grid/src/hooks/features/focus/useGridFocus.ts
packages/x-data-grid/src/hooks/features/headerFiltering/useGridHeaderFiltering.ts
packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts
packages/x-data-grid/src/hooks/features/rows/useGridRows.ts
packages/x-data-grid/src/hooks/features/sorting/useGridSorting.ts
packages/x-data-grid/src/hooks/features/statePersistence/useGridStatePersistence.ts
packages/x-data-grid/src/models/api/gridStateApi.ts

Resolves #16535
- The `apiRef.current.forceUpdate()` method was removed. Use selectors combined with `useGridSelector()` hook to react to changes in the state.

[DataGrid] Remove `apiRef.current.forceUpdate()` method

---

packages/x-charts/src/ChartsTooltip/ChartsTooltipContainer.tsx
pnpm-lock.yaml

Should fix #13450
My assumption is that the `anchorEl` and `modifiers`  was always triggering the creation of a new popper.js instance.
After those memorization I do not manage to reproduce the error message

[charts] Memoize some tooltip internals

---

docs/data/charts/axis/FormatterD3.js
docs/data/charts/axis/FormatterD3.tsx
docs/data/charts/axis/axis.md
docs/pages/x/api/charts/axis-config.json
packages/x-charts-pro/src/Heatmap/HeatmapTooltip.tsx
packages/x-charts/src/ChartsLegend/ContinuousColorLegend.tsx
packages/x-charts/src/ChartsLegend/PiecewiseColorLegend.tsx
packages/x-charts/src/ChartsTooltip/useAxisTooltip.tsx
packages/x-charts/src/hooks/useTicks.ts
packages/x-charts/src/models/axis.ts

Fix #16350
I did not propagate the scale to the legend formatter, because in such case, it's not clear is it's the axis scale, or the color-scale to pass. And not that much usefull.

[charts] Propagate the axis scale to the `valueFormatter`

---

docs/data/data-grid/filtering/FilteringWithPageReset.js
docs/data/data-grid/filtering/FilteringWithPageReset.tsx
docs/data/data-grid/filtering/FilteringWithPageReset.tsx.preview
docs/data/data-grid/filtering/index.md
docs/data/data-grid/filtering/server-side.md
docs/data/data-grid/pagination/ServerPaginationFilterSortGrid.js
docs/data/data-grid/pagination/ServerPaginationFilterSortGrid.tsx
docs/data/data-grid/pagination/ServerPaginationFilterSortGrid.tsx.preview
docs/data/data-grid/pagination/pagination.md
docs/data/data-grid/sorting/SortingWithPageReset.js
docs/data/data-grid/sorting/SortingWithPageReset.tsx
docs/data/data-grid/sorting/SortingWithPageReset.tsx.preview
docs/data/data-grid/sorting/sorting.md
docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
docs/translations/api-docs/data-grid/data-grid-premium/data-grid-premium.json
docs/translations/api-docs/data-grid/data-grid-pro/data-grid-pro.json
docs/translations/api-docs/data-grid/data-grid/data-grid.json
packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
packages/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx
packages/x-data-grid/src/DataGrid/DataGrid.tsx
packages/x-data-grid/src/constants/dataGridPropsDefaultValues.ts
packages/x-data-grid/src/hooks/features/pagination/useGridPaginationModel.ts
packages/x-data-grid/src/models/props/DataGridProps.ts
packages/x-data-grid/src/tests/pagination.DataGrid.test.tsx

Realted to https://github.com/mui/mui-x/issues/15378
It is a first PR that will be cherry-picked to v7
https://github.com/mui/mui-x/pull/16447 will remove the prop for v8 and include migration notes
Preview
https://deploy-preview-16450--material-ui-x.netlify.app/x/react-data-grid/sorting/#reset-page-on-sorting
https://deploy-preview-16450--material-ui-x.netlify.app/x/react-data-grid/filtering/#reset-page-on-filtering

[DataGrid] Add `resetPageOnSortFilter` prop that resets the page after sorting/filtering

---

docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
docs/translations/api-docs/data-grid/data-grid-premium/data-grid-premium.json
docs/translations/api-docs/data-grid/data-grid-pro/data-grid-pro.json
docs/translations/api-docs/data-grid/data-grid/data-grid.json
packages/x-data-grid/src/material/index.tsx
packages/x-data-grid/src/models/gridBaseSlots.ts
packages/x-data-grid/src/models/gridSlotsComponent.ts
packages/x-data-grid/src/models/gridSlotsComponentsProps.ts

Create base Switch component. This is not used at the moment but will be by #9877.

[DataGrid] Refactor: create base Switch

---

packages/x-date-pickers/src/TimeClock/Clock.tsx
packages/x-date-pickers/src/managers/useTimeManager.ts

Follow up on https://github.com/mui/mui-x/pull/16522#discussion_r1954094585.
Do you think it warrants an entry in the migration guide? 🤔 
- The `aria-label` on the `<Clock />` component and Time Picker opening button has been fixed to rely on the set `ampm` property instead of defaulting to the user's locale.

[pickers] Fix time related aria labels to depend on `ampm` flag value

---

test/performance-charts/package.json
test/performance-charts/vitest.config.ts

Add `test:performance:browser` script to `performance-charts`. I'd like to benchmark locally using a real browser because some of the changes I'm doing rely on `getBBox`, which JSDOM doesn't implement. 
Ideally we'd run the benchmarks in CI using a real browser as well, but it seems Codspeed doesn't allow running vitest in browser mode. I'll keep investigating.

[charts] Add test:performance:browser script

---

docs/data/charts/axis/CustomDomainYAxis.tsx
docs/pages/x/api/charts/pie-series-type.json
packages/x-charts-pro/src/Heatmap/Heatmap.tsx
packages/x-charts-pro/src/models/seriesType/heatmap.ts
packages/x-charts-pro/src/typeOverloads/readonly.spec.tsx
packages/x-charts/src/BarChart/BarChart.tsx
packages/x-charts/src/LineChart/LineChart.tsx
packages/x-charts/src/PieChart/PieChart.tsx
packages/x-charts/src/ScatterChart/ScatterChart.tsx
packages/x-charts/src/internals/calculateMargins.ts
packages/x-charts/src/internals/plugins/corePlugins/useChartSeries/processSeries.ts
packages/x-charts/src/internals/plugins/corePlugins/useChartSeries/useChartSeries.types.ts
packages/x-charts/src/models/seriesType/pie.ts
packages/x-charts/src/tests/readonly.spec.tsx

I've missed most of the `non-primitive` `series.data` types from being readonly...
Related https://github.com/mui/mui-x/pull/16632

[charts] Make `series.data` readonly

---

test/utils/pickers/describeValue/testPickerOpenCloseLifeCycle.tsx

Revert this fix https://github.com/mui/mui-x/pull/12786, which has been removed in https://github.com/mui/mui-x/pull/16049/files#diff-d6bd7719fe1f538431daaaf15aba967817c1126a9e42387a75a190a9d5ce0c3fL187 to avoid flaky test failures in CI.

[test] Revert timeout increase for possibly slow tests

---

packages/x-data-grid/src/material/index.tsx

Fixes Select components not closing on click-away.
Having `onClose: undefined` in `MenuProps` removes the default close handler.

[DataGrid] Fix: base Select menuprops onClose

---

packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts
packages/x-data-grid/src/tests/rows.DataGrid.test.tsx

See reproduction steps in #16628 to try the fix locally.
Fixes #16628

[DataGrid] Fix scrollbars overlapping cells on mount

---

packages/x-charts/src/PieChart/PieChart.test.tsx
packages/x-charts/src/PieChart/PieChart.tsx

Fixes https://github.com/mui/mui-x/issues/16655.
This issue does not happen in v8, so I'm only fixing it for v7.
Before:
https://github.com/user-attachments/assets/6d09b4d4-77e0-4ce1-8659-82a2efabb12a
After:
https://github.com/user-attachments/assets/a6e6617e-f31b-4b14-949e-bd5bb09981f5

[charts] Fix empty series pie chart v7

---

packages/x-charts/src/PieChart/PieChart.test.tsx

Add unit test for pie chart with empty series.
Cherry-picked from https://github.com/mui/mui-x/pull/16657.

[charts] Add unit test for pie chart with empty series

---

packages/x-charts/src/ChartsXAxis/ChartsXAxis.tsx
packages/x-charts/src/internals/domUtils.ts

Depends on https://github.com/mui/mui-x/pull/16548.
Part of https://github.com/mui/mui-x/issues/10928.
Measuring the size of text using `getBoundingClientRect` is expensive, especially when appending elements one by one to the DOM, which is what we're doing at the moment. 
Knowing that, this PR focuses on reducing the number of times we actually measure text. In the case of tick labels in the x-axis, this is done by:
1. Checking whether the center of label would overlap with a previous label (or the minimum gap between labels);
2. Checking whether the center of the label would be outside the visible area.
Only if these two checks are true do we actually measure the text. This helps us reduce the number of measurements, improving performance for when rendering many labels. 
Bear in mind …

[charts] Improve performance of rendering ticks in x-axis

---

packages/x-date-pickers/src/TimeClock/Clock.tsx
packages/x-date-pickers/src/TimeClock/ClockPointer.tsx

It's broken only on v8/master.
|--------|------|
|![Screenshot 2025-02-21 at 12 31 39](https://github.com/user-attachments/assets/5b4d5703-1bb5-4424-886a-76239e492d35)|![Screenshot 2025-02-21 at 12 48 03](https://github.com/user-attachments/assets/e672e565-44c4-4fb0-9146-f38559a1eae9)|

[pickers] Fix `TimeClock` meridiem button selected styles

---

docs/data/migration/migration-pickers-v7/migration-pickers-v7.md

Improve the Pickers migration guide docs:
- Move the `date-fns` adapters rename section to the top of the page
- Mark low impacts BCs with ⏩ and add a callout explaining this marking

[docs] Improve Pickers migration page

---

docs/src/modules/components/DemoPropsForm.tsx

difference without/with this change.
https://github.com/user-attachments/assets/220a1c9f-001e-416f-990c-26c307e514f4

[charts] Display slider tooltip on demos

---

packages/x-data-grid-pro/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx
packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx
test/regressions/data-grid/DataGridBorderedCells.js
test/regressions/data-grid/DataGridBorderedColumns.js

The column headers were using `showCellVerticalBorder` to determine whether the border should be enabled between items instead of `showColumnVerticalBorder`.

[DataGrid] Fix `showColumnVerticalBorder` prop

---

packages/x-data-grid/src/hooks/features/sorting/useGridSorting.ts
packages/x-data-grid/src/models/gridSortModel.ts
packages/x-data-grid/src/tests/DataGrid.spec.tsx

Fix the type of the GridSortModel to allow readonly arrays.

[DataGrid] Use readonly array for GridSortModel

---

packages/x-data-grid/src/hooks/features/sorting/useGridSorting.ts
packages/x-data-grid/src/models/gridSortModel.ts
packages/x-data-grid/src/tests/DataGrid.spec.tsx

Manual cherry-pick of https://github.com/mui/mui-x/pull/16627

[DataGrid] Use readonly array for GridSortModel (@pcorpet)

---

packages/x-data-grid/src/components/panel/GridPanel.tsx
packages/x-data-grid/src/material/index.tsx
packages/x-data-grid/src/models/gridBaseSlots.ts

Fixes https://mui-org.slack.com/archives/C05SBSU8NPR/p1740497242687319
Focus trap was not working.
Both `MUIClickAwayListener` and `MUIFocusTrap` require a ref'able child, but none of them forward the ref, so they can't be used on top of another.

[DataGrid] fix: popper focus trap

---

docs/data/charts/legend/LegendCustomLabelMark.js
docs/data/charts/legend/LegendCustomLabelMark.tsx
docs/data/charts/legend/LegendCustomLabelMark.tsx.preview
docs/data/charts/legend/legend.md
docs/data/charts/pie-demo/PieChartWithCustomLegendAndTooltip.js
docs/data/charts/pie-demo/PieChartWithCustomLegendAndTooltip.tsx
docs/data/charts/pie-demo/pie-demo.md
packages/x-charts/src/ChartsLabel/ChartsLabelMark.tsx
packages/x-charts/src/ChartsLabel/index.ts
packages/x-charts/src/ChartsLabel/labelMarkClasses.ts
packages/x-charts/src/PieChart/PieArcLabelPlot.tsx
packages/x-charts/src/PieChart/PieArcPlot.tsx
scripts/x-charts-pro.exports.json
scripts/x-charts.exports.json

Related to https://github.com/mui/mui-x/pull/16640. Implementation of option B as defined [here](https://github.com/mui/mui-x/pull/16654#issuecomment-2677967216). 
Accept component in `labelMarkType` to customize the mark in legends and tooltips. 
A consequence of this API is that when customizing the shape of a scatter chart, a user will need to define the `labelMarkType` and scatter shape in different places. 
https://github.com/user-attachments/assets/e5769e3b-bf20-40b1-b0c3-6d6a45cabce2

[charts] Accept component in `labelMarkType`

---

packages/x-charts-pro/src/Heatmap/Heatmap.test.tsx
packages/x-charts-pro/src/Heatmap/Heatmap.tsx
packages/x-charts/src/BarChart/BarChart.test.tsx
packages/x-charts/src/ChartsXAxis/ChartsXAxis.tsx
packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx
packages/x-charts/src/LineChart/LineChart.test.tsx
packages/x-charts/src/ScatterChart/ScatterChart.test.tsx
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/defaultizeAxis.ts

Remove redundant default axis when processing user-provided axes. 
Also fixes a crash with the Heatmap when the `xAxis` prop was an empty array. 
Added unit tests for every chart that accepts an array for either the `xAxis` or the `yAxis` prop.
Before:
https://github.com/user-attachments/assets/af4e3546-fa2a-48b5-b929-10c109468b31
After:
https://github.com/user-attachments/assets/22938fba-0d8b-4120-93b2-c555958f38cc

[charts] Remove redundant default axis

---

packages/x-charts/src/internals/plugins/featurePlugins/useChartHighlight/useChartHighlight.selectors.ts

Found while testing #16575
Instead of using the selector that returns a function. SHould probably continue the search for non memorized stuff

[charts] Fix is highlighted memoization

---

.github/ISSUE_TEMPLATE/5.priority-support.yml

Replaced 'support: unknown' with 'support: priority' to better reflect the intended categorization of issues for MUI X Premium users with the Priority Support add-on. This ensures more accurate labeling for streamlined issue management.

[infra] Update label in priority-support issue template

---

docs/data/data-grid/filtering/QuickFilteringCustomLogic.js
docs/data/data-grid/filtering/QuickFilteringCustomLogic.tsx
docs/data/data-grid/filtering/quick-filter.md
packages/x-data-grid/src/colDef/gridActionsColDef.tsx
packages/x-data-grid/src/colDef/gridBooleanColDef.tsx
packages/x-data-grid/src/colDef/gridCheckboxSelectionColDef.tsx

Fixes https://github.com/mui/mui-x/issues/16733
from https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/models/colDef/gridColDef.ts#L264-L265
* The callback that generates a filtering function for a given quick filter value.
* This function can return `null` to skip filtering for this value and column.

[DataGrid] remove the quick filtering on a given column

---

packages/x-date-pickers/src/PickersTextField/PickersTextField.tsx

Fixes #16637.
We missed adding the relationship of `helperText` with some specific element.
This PR adds `aria-describedby` to the root `spinbutton` `group` element and also adds `aria-live="polite"` to signal that this element changes need to be read by the screen reader.
On the "v6" (input) approach, it is not needed because the `aria-describedby` is added on the `input` element, which is focused and receiving changes.
P.S. This is technically a small regression due to it working fine on the old "INPUT" approach. 🙈

[fields] Fix Fields aria relationship with `helperText`

---

packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx
packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx

Fixes https://github.com/mui/mui-x/issues/16706
`aria-hidden` cannot be removed because of https://github.com/mui/mui-x/issues/16706#issuecomment-2698060646
`tabIndex` cannot be removed because we don't want focus on the scrollbar

[DataGrid] Fix `aria-hidden` console error when scrollbar is dragged

---

docs/data/charts/radar/radar.md
docs/translations/api-docs/charts/axis-config.json
docs/translations/api-docs/charts/radar-series-area/radar-series-area.json
docs/translations/api-docs/charts/radar-series-marks/radar-series-marks.json
docs/translations/api-docs/charts/radar-series-plot/radar-series-plot.json
packages/x-charts/src/RadarChart/RadarDataProvider/radar.types.ts
packages/x-charts/src/RadarChart/RadarSeriesPlot/RadarSeriesArea.tsx
packages/x-charts/src/RadarChart/RadarSeriesPlot/RadarSeriesMarks.tsx
packages/x-charts/src/RadarChart/RadarSeriesPlot/RadarSeriesPlot.tsx
packages/x-charts/src/RadarChart/RadarSeriesPlot/RadarSeriesPlot.types.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartPolarAxis/useChartPolarAxis.types.ts
packages/x-charts/src/models/axis.ts

[docs] Typo fixes

---

docs/src/modules/components/InstallationInstructions.tsx

Preview: https://deploy-preview-16794--material-ui-x.netlify.app/x/react-date-pickers/quickstart/
Noticed this with #16554

[docs] Fix padding package install on mobile

---

packages/x-charts/src/ChartsXAxis/ChartsXAxis.tsx
packages/x-charts/src/internals/invertTextAnchor.ts

Fix x-axis text anchor default when language is RTL.
<details>
<summary>Comparison code</summary>
```tsx
import { BarChart } from '@mui/x-charts/BarChart';
import { BarChartProps } from '@mui/x-charts';
import RtlProvider from '@mui/system/RtlProvider';
const rtl = true;
const defaultXAxis = {
scaleType: 'band',
dataKey: 'code',
height: 80,
valueFormatter: (value: any) => {
const item = usAirportPassengers.find((item) => item.code === value)!;
return (rtl ? item.fullNameAr.slice(0, 5) : item.fullName.slice(0, 5)) + '…';
},
} as const;
const degrees = [-180, -135, -90, -45, 0, 45, 90, 135, 180];
const xAxes: BarChartProps['xAxis'] = degrees
.map((angle) => ({
...defaultXAxis,
position: 'bottom',
id: `angle${angle}`,
tickLabelStyle: { angle },
}))
.concat( …
```

[charts] Fix x-axis text anchor default when language is RTL

---

packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/defaultizeAxis.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/index.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianAxis.ts

Split the `defaultizeAxis` function into `defaultizeXAxis` and `defaultizeYAxis` with the goal of simplifying types.

[charts] Split `defaultizeAxis` function into two

---

packages/x-charts/src/BarChart/BarPlot.tsx
packages/x-charts/src/BarChart/checkScaleErrors.test.ts
packages/x-charts/src/BarChart/checkScaleErrors.ts
packages/x-charts/src/LineChart/LinePlot.tsx

Fix #16740
If we agree on the idea, this could be extended to the line charts

[charts] Warn if axis data don't have enough elements

---

packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/defaultizeAxis.ts

Fix `undefined` behaving differently from missing value for axis size. Also fixed the same issue for the `position` property.
Example:
```tsx
<BarChart xAxis={[{ height: undefined }]} />
```
had a different behavior than:
```tsx
<BarChart xAxis={[{}]} />
```
`height`:
https://github.com/user-attachments/assets/7a041ac6-6e2a-4d92-939d-d03c634f2f2f
`position`:
https://github.com/user-attachments/assets/86163be5-e3e6-4c17-a17b-dcae9deb2ed4
`height`:
https://github.com/user-attachments/assets/1f751111-cb77-4925-b0da-c4cf44eb4219
`position`:
https://github.com/user-attachments/assets/6c081c2e-6024-4bb1-9049-497ff00b6814

[charts] Fix undefined behaving differently from missing value for axis size

---

packages/x-date-pickers-pro/src/managers/useDateRangeManager.ts
packages/x-date-pickers-pro/src/managers/useDateTimeRangeManager.ts
packages/x-date-pickers-pro/src/managers/useTimeRangeManager.ts
packages/x-date-pickers/src/internals/models/manager.ts
packages/x-date-pickers/src/managers/useDateManager.ts
packages/x-date-pickers/src/managers/useDateTimeManager.ts
packages/x-date-pickers/src/managers/useTimeManager.ts
packages/x-date-pickers/src/models/manager.ts

Allow to pass only the props relevant for validation to `useValidation` without having TS complain in #16069
It also simplifies some of the typing

[pickers] Add `TValidationProps` generic to the `PickerManager` interface

---

packages/x-date-pickers/src/internals/components/PickerFieldUI.tsx

Fixes https://github.com/mui/mui-x/issues/12825.
Looks like the main problem is with us setting `edge` when `variant` is `standard`, which is not ok according to https://v5.mui.com/material-ui/react-text-field/#input-adornments.
In regards to the vertical scrollbar, it seems to be coming from the `DemoContainer` component usage. 🙈

[pickers] Fix `edge` property setting in different button position cases

---

docs/data/date-pickers/custom-field/behavior-autocomplete/MaterialDatePicker.js
docs/data/date-pickers/custom-field/behavior-autocomplete/MaterialDatePicker.tsx

Fixes the broken autocomplete behavior (options are not opening).
Incorrect ref (`rootRef` instead of `triggerRef`) definition was the problem. 🙈 
Cleanup and improve the demo.

[docs] Fix Pickers custom field with Autocomplete demo

---

packages/x-date-pickers/src/timeViewRenderers/timeViewRenderers.tsx

Fix consistently failing tests on React 18:
- https://app.circleci.com/pipelines/github/mui/mui-x/83939/workflows/ccd79a7c-a82f-4230-a01d-bf5269f15187/jobs/479137
- https://app.circleci.com/pipelines/github/mui/mui-x/83939/workflows/ccd79a7c-a82f-4230-a01d-bf5269f15187/jobs/479136
The `renderTimeViewClock` already has this safeguard to prevent wrapper components from passing unexpected `focusedView`.

[pickers] Avoid passing unexpected `focusedView` to time renderers

---

packages/x-charts-pro/src/FunnelChart/FunnelSection.tsx
packages/x-charts/src/ChartsLegend/ChartsLegend.tsx
packages/x-charts/src/internals/consumeSlots.test.tsx

Fix [React 18 tests failing](https://app.circleci.com/pipelines/github/mui/mui-x/84116/workflows/4f11b85a-b719-4dee-988c-d545bbc849d3/jobs/480151) due to missing `forwardRef`.
Issue introduced in [this PR](https://github.com/mui/mui-x/pull/16640). [I had identified](https://github.com/mui/mui-x/pull/16640#discussion_r1973955807) that we needed to add `forwardRef`, but forgot to add it in the PR. It wasn't caught in CI because it isn't needed in React 19, but it is in React 18.

[charts] Fix React 18 tests failing due to missing `forwardRef`

---

docs/data/date-pickers/lifecycle/lifecycle.md

Clarify the field lifecycle section explaining when `onChange` is called and with what values.
The current explanation is no longer valid after https://github.com/mui/mui-x/pull/15875.

[docs] Adjust Picker field lifecycle explanation

---

packages/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx

Fixes #14861 
Currently, we are enforcing `hideFooter` in `printOptions` to false by default but it should also consider the `hideFooter` root prop value to avoid issues like this.
Before: https://stackblitz.com/edit/github-kbnsbh?file=src%2Fdemo.tsx
After: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-9wx4pw

[DataGrid] `printOptions` should respect `hideFooter` root prop

---

packages/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts

Hi there,
**Problem:**
When adding or removing columns in a grid with an active edit state, the column change fires, causing the field to no longer appear. This happens because the editing state fetched via const editingState = gridEditRowsStateSelector(apiRef.current.state) still holds the old list of columns and their editing states, which includes the old field.
As a result, the call to const column = apiRef.current.getColumn(field) returns undefined because the current column state doesn’t reflect the most up-to-date column state, leading to an outdated state. This causes the following check to fail:
`if (column.valueSetter)`
**Solution:**
To address this issue, I’ve added a check to ensure that the column is defined before accessing column.valueSetter. This prevents errors caused by …

[DataGrid] Fix bug with adding and removing columns in active edit state

---

packages/x-charts-pro/src/ChartContainerPro/useChartContainerProProps.ts
packages/x-charts-pro/src/internals/plugins/allPlugins.ts
packages/x-charts/src/ChartContainer/useChartContainerProps.ts
packages/x-charts/src/internals/plugins/allPlugins.ts

The polar event handler was triggered even if no polar axis are provided. So I removed the plugin.
Latter we could remove this `ChartContainer` by `CartesianChartContainer` and let all the other chart get `RadarChartContainer`, `PieChartContainer`, ...

[charts] Remove the polar axis plugin from the default plugins of the ChartContainer

---

packages/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.tsx

Fixes https://github.com/mui/mui-x/issues/16906
~~Reverts the change made to the infinite loading in https://github.com/mui/mui-x/pull/16488~~
Had to take a different approach. In tests, virtual scroll reference is never updated so the observer is not attached.
Waiting until dimensions are ready does the trick.
@cherniavskii since you did the changes in https://github.com/mui/mui-x/pull/16488 do you see any issues with the update?
Before: https://mui.com/x/react-data-grid/row-updates/#infinite-loading
After: https://deploy-preview-16926--material-ui-x.netlify.app/x/react-data-grid/row-updates/#infinite-loading

[DataGridPro] Fix infinite loading not reacting on scrolling to the end

---

packages/x-charts/src/RadarChart/RadarAxisHighlight/RadarAxisSliceHighlight.tsx
packages/x-charts/src/RadarChart/RadarAxisHighlight/useRadarAxisHighlight.ts

I noticed that the point I disiliked in the radar slice highlight is due to a computation imprecision.
Initially, I've set the notion of slice to the middle path between two value points. In this PR I replace the definition by the intersection of the line between two points, and the middle angle.

[charts] Improve radar slice

---

packages/x-charts/src/ChartsText/ChartsText.tsx
packages/x-charts/src/ChartsXAxis/ChartsXAxis.tsx
packages/x-charts/src/hooks/useIsHydrated.ts
packages/x-charts/src/hooks/useIsHydrationDone.ts

Related to https://github.com/mui/mui-x/pull/16709#discussion_r1990942020

[charts] Rename useIsClient

---

packages/x-charts-pro/README.md
packages/x-charts-pro/package.json
packages/x-charts/README.md
packages/x-charts/package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/README.md
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/README.md
packages/x-data-grid-pro/package.json
packages/x-data-grid/README.md
packages/x-data-grid/package.json
packages/x-date-pickers-pro/README.md
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/README.md
packages/x-date-pickers/package.json
packages/x-internals/package.json
packages/x-license/package.json
packages/x-tree-view-pro/README.md
packages/x-tree-view-pro/package.json
packages/x-tree-view/README.md
packages/x-tree-view/package.json
pnpm-lock.yaml

Add support for MUI Core libraries v7 versions to peer dependencies to support migration from v5 to v7 of Core packages before upgrading MUI X to v8.
> [!NOTE]
> Tested on a minimal project locally all X v7 with Core v7 libraries, and they seem to work fine. 👌

[core] Allow MUI Core v7 in dependencies

---

.circleci/config.yml

Revert https://github.com/mui/mui-x/pull/16434, as the root issue has been fixed in Node v20.19.

[code-infra] Bump `cimg/node` image version

---

packages/x-data-grid/src/hooks/features/overlays/useGridOverlays.tsx

The Apple M3 is unable to execute unit test cases. On the other hand, the Apple Intel processor has no problem running them.
The `selector` is undefined.
```bash
➜  mui-x git:(master) npx cross-env NODE_OPTIONS=--max-old-space-size=4096 NODE_ENV=test TZ=UTC mocha  packages/x-data-grid/src/tests/columnGrouping.DataGrid.test.tsx
including inaccessible elements by default
[
'3gp',  'aac',  'doc',
'docx', 'm4a',  'ppt',
'pptx', 'txt',  'webp',
'xls',  'xlsx'
]
!!!!!!!!!!!,,,,
0 passing (83ms)
4 pending
11 failing
1) <DataGrid /> - Column grouping
Header grouping columns
should add one header row when columns have a group:
TypeError: selector is not a function
at useGridSelector (packages/x-data-grid/src/hooks/utils/useGridSelector.ts:72:23)
at useGridOverlays …
```

[test] Fix Apple M3 failing to execute unit test cases

---

packages/x-data-grid/src/material/index.tsx

Adds the `disableAutoFocus` prop to the MUI `FocusTrap`, removing the automatic scrolling when the columns and filter panels open — it is not necessary since we handle focus manually.
Fixes #16867
**Before**
https://github.com/user-attachments/assets/78bfcea4-c955-41f0-a666-50b56f955e35
**After**
https://github.com/user-attachments/assets/4eab4a02-0b90-4e37-adb8-5016b7ad9291

[DataGrid] Fix page scrolling when preference panel is opened

---

packages/x-data-grid/src/components/columnSelection/GridHeaderCheckbox.tsx

Fixes https://github.com/mui/mui-x/issues/17005
Maybe an example with a bit more context would help (https://github.com/mui/mui-x/issues/17005#issuecomment-2733744567)
I don't see a benefit of using `checkboxSelectionVisibleOnly` and `paginationMode="server"` because you are seeing all rows anyway.
But, we can fix the issue regardless.

[DataGridPro] Fix header select checkbox state with `checkboxSelectionVisibleOnly` and `paginationMode="server"`

---

packages/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts

Fixes https://github.com/mui/mui-x/issues/17030
Regression from https://github.com/mui/mui-x/pull/16741
Custom id needs to be passed (if it is there), not the `id` field
Thanks @michelengelen for spotting it

[DataGrid] Fix error while editing rows with custom id

---

packages/x-data-grid/src/material/index.tsx

Docs state that the component cannot hold a ref
https://mui.com/material-ui/api/click-away-listener/
Because of our own `forwardRef` implementation, warning is visible only in React <= 18
To reproduce:
Load the grid and check the console
Also visible in our CI
https://app.circleci.com/pipelines/github/mui/mui-x/85474/workflows/b784d8d7-e3ef-4421-b122-f783f9f33ede/jobs/489491
```
Chrome Headless 134.0.0.0 (Linux x86_64) ERROR: 'Warning: forwardRef render functions accept exactly two parameters: props and ref. %s', 'Did you forget to use the ref parameter?'
Chrome Headless 134.0.0.0 (Linux x86_64) ERROR: 'Warning: forwardRef render functions do not support propTypes or defaultProps. Did you accidentally pass a React component?'
```

[DataGrid] Fix error caused by `forwardRef` to `ClickAwayListener`

---

packages/x-charts/src/BarChart/extremums.test.ts
packages/x-charts/src/BarChart/seriesConfig/extremums.ts

While working on the tooltip generalization, I noticed that bar chart does not render if horizontal with multiple axes.
Here is a fix and an extension of tests

[charts] Fix horizontal bar with multiple axes

---

packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.itemPlugin.ts
packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.selectors.ts
packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts
packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.types.ts
packages/x-tree-view/src/hooks/useTreeItemUtils/useTreeItemUtils.tsx
packages/x-tree-view/src/internals/models/itemPlugin.ts
packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.selectors.ts
packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.tsx
packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts
packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewLabel/useTreeViewLabel.itemPlugin.ts
packages/x-tree-view/src/internals/plugins/useTreeViewLabel/useTreeViewLabel.selectors.ts
packages/x-tree-view/src/internals/plugins/useTreeViewLabel/useTreeViewLabel.ts
packages/x-tree-view/src/internals/plugins/useTreeViewLabel/useTreeViewLabel.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewLazyLoading/useTreeViewLazyLoading.selectors.ts
packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.itemPlugin.ts
packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.selectors.ts
packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.test.tsx
packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.ts
packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.types.ts
packages/x-tree-view/src/internals/utils/selectors.ts
packages/x-tree-view/src/useTreeItem/useTreeItem.ts
packages/x-tree-view/src/useTreeItem/useTreeItem.types.ts
test/utils/tree-view/fakeContextValue.ts

On my way to entirely remove the context value :sunglasses: 
- Remove `useTreeViewIcons` in favor of a change similar to #16990 (that way we remove something MUI specific from the plugin system that will be used in the Base UI implementation).
- Drop the ability for the plugins to add stuff to the context (this will unlock #16357)

[TreeView] Use state and instance instead of context in all plugins except `useTreeViewIcons`

---

docs/pages/x/api/charts/heatmap-tooltip.json
docs/translations/api-docs/charts/heatmap-tooltip/heatmap-tooltip.json
packages/x-charts-pro/src/Heatmap/Heatmap.test.tsx
packages/x-charts-pro/src/Heatmap/HeatmapTooltip.tsx
packages/x-charts-pro/src/hooks/useFunnelSeries.test.tsx
packages/x-charts-pro/src/hooks/useHeatmapSeries.test.tsx
packages/x-charts-vendor/tsconfig.json
packages/x-charts/src/hooks/useBarSeries.test.tsx
packages/x-charts/src/hooks/useInteractionItemProps.ts
packages/x-charts/src/hooks/useLineSeries.test.tsx
packages/x-charts/src/hooks/usePieSeries.test.tsx
packages/x-charts/src/hooks/useRadarSeries.test.tsx
packages/x-charts/src/hooks/useScatterSeries.test.tsx
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianAxis.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartPolarAxis/useChartPolarAxis.ts
test/utils/setupJSDOM.js

I've noticed we couldn't remove the tooltip of the Heatmap while testing. Added it on this PR. 
Also bundled a few test changes to prevent `act` warnings

[charts-pro] Allow disabling Heatmap tooltip

---

docs/data/data-grid/list-view/ListViewAdvanced.js
docs/data/data-grid/list-view/ListViewAdvanced.tsx
docs/data/data-grid/list-view/components/Drawer.js
docs/data/data-grid/list-view/components/Drawer.tsx
docs/data/data-grid/list-view/components/RenameDialog.tsx

Use the `window` prop that gets passed to iframe demos instead of a ref on the container element.
Fixes #17056 
**Before**
https://next.mui.com/x/react-data-grid/list-view/#advanced-usage
https://github.com/user-attachments/assets/3eb9a113-15a7-4633-9e22-92dd1197e4fc
**After**
https://deploy-preview-17064--material-ui-x.netlify.app/x/react-data-grid/list-view/#advanced-usage
https://github.com/user-attachments/assets/69951e66-84bf-4ff3-bdea-a8a7dec3887d

[docs] Fix Data Grid advanced list view demo

---

packages/x-data-grid-premium/src/hooks/features/rowGrouping/useGridRowGroupingPreProcessors.ts
packages/x-data-grid-premium/src/tests/rowGrouping.DataGridPremium.test.tsx

Fixes https://github.com/mui/mui-x/issues/17046
Had to revert changes done in https://github.com/mui/mui-x/pull/15908
Root cause was the length check because changing the mode with one grouping column changes its autogenerated field name

[DataGridPremium] Update column state correctly when grouping mode is updated with one grouping column

---

packages/x-charts/src/ChartsOverlay/ChartsLoadingOverlay.tsx
packages/x-charts/src/ChartsOverlay/ChartsNoDataOverlay.tsx

Extracted from #17062
The idea is to have `theme.palette` containing all the colors, and `theme.vars.palette` containing the same structure but with CSS variables.
The advantage of `theme.vars.palette` is that toggle the dark/light does not modify the JS object. only the CSS vars value are impacted. So you can switch without having to re-render the all page

[charts] Fix CSS vars support for dark theme

---

packages/x-date-pickers-pro/src/DateRangePicker/DateRangePicker.test.tsx
packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/selection.SingleInputDateRangeField.test.tsx
packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.test.tsx
packages/x-date-pickers/src/AdapterDateFnsJalali/AdapterDateFnsJalali.test.tsx
packages/x-date-pickers/src/AdapterDateFnsJalaliV2/AdapterDateFnsJalaliV2.test.tsx
packages/x-date-pickers/src/AdapterDayjs/AdapterDayjs.test.tsx
packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.test.tsx
packages/x-date-pickers/src/AdapterMoment/AdapterMoment.test.tsx
packages/x-date-pickers/src/AdapterMomentHijri/AdapterMomentHijri.test.tsx
packages/x-date-pickers/src/AdapterMomentJalaali/AdapterMomentJalaali.test.tsx
packages/x-date-pickers/src/DateField/tests/selection.DateField.test.tsx
packages/x-date-pickers/src/DateTimeField/tests/editing.DateTimeField.test.tsx
packages/x-date-pickers/src/DateTimeField/tests/timezone.DateTimeField.test.tsx
packages/x-date-pickers/src/DesktopDatePicker/tests/field.DesktopDatePicker.test.tsx
packages/x-date-pickers/src/DesktopDateTimePicker/tests/field.DesktopDateTimePicker.test.tsx
packages/x-date-pickers/src/DesktopTimePicker/tests/field.DesktopTimePicker.test.tsx
packages/x-date-pickers/src/MobileDatePicker/tests/MobileDatePicker.test.tsx
packages/x-date-pickers/src/MobileDateTimePicker/tests/field.MobileDateTimePicker.test.tsx
packages/x-date-pickers/src/MobileTimePicker/tests/field.MobileTimePicker.test.tsx
packages/x-date-pickers/src/tests/fieldKeyboardInteraction.test.tsx
test/utils/pickers/createPickerRenderer.tsx
test/utils/pickers/describeAdapters/describeAdapters.ts
test/utils/pickers/describeJalaliAdapter/testCalculations.ts
test/utils/pickers/describeValue/describeValue.tsx
test/utils/pickers/fields.tsx

These are improvements made during the [`vitest` PR ](https://github.com/mui/mui-x/pull/14508)
I'm moving the changes out so that PR is leaner. The changes mostly revolve around removing `clock='fake'` usage.
Hopefully these are reasonable enough changes to be merged without issues.

[code-infra] Update some date-pickers tests for vitest

---

packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts

Manual cherry-pick of #17051 (the action failed)

[fields] Improve the check for year in `doesSectionFormatHaveLeadingZeros`

---

docs/data/data-grid/components/export/export.md

The example import for `ExportExcel` was referencing the wrong package.
https://deploy-preview-17110--material-ui-x.netlify.app/x/react-data-grid/components/export/

[docs] Fix example import for `ExportExcel` component

---

packages/x-data-grid-premium/src/tests/aggregation.DataGridPremium.test.tsx
packages/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/columnsVisibility.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/dataSourceTreeData.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/infiniteLoader.DataGridPro.test.tsx
packages/x-data-grid/src/tests/cells.DataGrid.test.tsx
packages/x-data-grid/src/tests/columnHeaders.DataGrid.test.tsx
packages/x-data-grid/src/tests/columnSpanning.DataGrid.test.tsx
packages/x-data-grid/src/tests/columns.DataGrid.test.tsx
packages/x-data-grid/src/tests/quickFiltering.DataGrid.test.tsx
packages/x-data-grid/src/tests/rows.DataGrid.test.tsx
packages/x-data-grid/src/tests/toolbar.DataGrid.test.tsx

These are improvements made during the [`vitest` PR ](https://github.com/mui/mui-x/pull/14508)
I'm moving the changes out so that PR is leaner. 
The changes mostly revolve around:
- removing `clock='fake'` usage.
- using `user` events rather than `fireEvent` where applicable.

[code-infra] Update some data-grid tests for vitest

---

packages/x-data-grid/src/components/GridRow.tsx
packages/x-data-grid/src/hooks/features/columns/useGridColumns.tsx
packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx

Fixes https://github.com/mui/mui-x/issues/16638 (still have to verify since there is no reproduction code)
Fixes https://github.com/mui/mui-x/issues/17022
Removes the need for https://github.com/mui/mui-x/pull/16672
The root cause for this is dealing with state from different update cycles.
Rows are rendered from `getRows` which uses [rows data](https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx#L429) obtained through `useGridSelector` [here](https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/hooks/utils/useGridVisibleRows.ts#L30).
Once those rows are rendered, they use `getRowParam` API which [throws](https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/hooks/features/rows/useGridParamsApi. …

[DataGrid] Fix error caused by trying to render rows that are not in the state anymore

---

docs/data/migration/migration-data-grid-v7/migration-data-grid-v7.md
packages/x-codemod/README.md
packages/x-codemod/src/v8.0.0/data-grid/add-showToolbar-prop/actual.spec.js
packages/x-codemod/src/v8.0.0/data-grid/add-showToolbar-prop/add-showToolbar-prop.test.ts
packages/x-codemod/src/v8.0.0/data-grid/add-showToolbar-prop/expected.spec.js
packages/x-codemod/src/v8.0.0/data-grid/add-showToolbar-prop/index.ts
packages/x-codemod/src/v8.0.0/data-grid/add-showToolbar-prop/ts-actual.spec.tsx
packages/x-codemod/src/v8.0.0/data-grid/add-showToolbar-prop/ts-expected.spec.tsx
packages/x-codemod/src/v8.0.0/data-grid/preset-safe/actual.spec.tsx
packages/x-codemod/src/v8.0.0/data-grid/preset-safe/expected.spec.tsx
packages/x-codemod/src/v8.0.0/data-grid/preset-safe/index.ts

- Adds `showToolbar` prop to show toolbar properly.
```diff
<DataGrid
slots={{
toolbar: GridToolbar,
}}
+  showToolbar
/>
```

[codemod] Add `showToolbar` prop when using toolbar component

---

packages/x-data-grid/src/components/quickFilter/QuickFilter.tsx

Removes `aria-controls` `role` and `aria-orientation` attributes that were accidentally copied over from the toolbar component when working on the quick filter changes here: #16862

[DataGrid] Remove unwanted attributes from `QuickFilter` component

---

docs/pages/x/api/charts/radar-chart.json
packages/x-charts/src/RadarChart/RadarAxisHighlight/useRadarAxisHighlight.ts
packages/x-charts/src/RadarChart/RadarChart.test.tsx
packages/x-charts/src/RadarChart/RadarGrid/RadarGrid.tsx
packages/x-charts/src/RadarChart/RadarGrid/useRadarGridData.ts
packages/x-charts/src/RadarChart/RadarSeriesPlot/useRadarSeriesData.ts
packages/x-charts/src/hooks/useAxis.ts
packages/x-charts/src/hooks/useScale.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianInteraction.selectors.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartPolarAxis/coordinateTransformation.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartPolarAxis/getAxisValue.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartPolarAxis/useChartPolarAxis.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartPolarAxis/useChartPolarInteraction.selectors.ts

1. Prevent charts from breaking if no cartesian axis found
2. Add interaction solector for polar charts
3. Use it for radar chart
Remaining:
Add test on radar chart for the axis highlight

[charts] Fix radar hover

---

.github/workflows/issue-status-label-handler.yml

This pull request includes a small change to the `.github/workflows/issue-status-label-handler.yml` file. The change grants write permissions to the `actions` scope.
This is needed for the status label handler workflow to delete the cache and create a new one.
Related PR: https://github.com/mui/mui-public/pull/297
* [`.github/workflows/issue-status-label-handler.yml`](diffhunk://#diff-39f7419b803abac83bb454886d44600de03f9138be0137c41055b5c4dbf51a56R19): Added `actions: write` permission in the `permissions` section.

[infra] Add write permission for actions in issue status label handler

---

packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx

This one feels like a quick win, so going after it. 
You can compare the scrollbar width with:
Help with #9311
On the solution space, Ant Design uses a similar solution, but it's different:
they also use `scrollbar-width: thin` but also:
1. leave more width. It feels great because when we look at https://github.com/mui/mui-x/issues/9311#issuecomment-1709169359, it looks like someone who added a large zoom. So It feels like fixing #9311 should also involve a change in this direction. One could argue that to full fix this, we need to have a custom scrollbar handling logic, like one we have on Base UI scroll area component or Material UI tabs component, but I don't know, this feel overkill, the pragmatic approach feels like to try those quick wins, and see if it's good enough. Adding more JS …

[pickers] Fix time picker scrollbar width

---

docs/data/introduction/support/support.md

Reflect https://www.notion.so/mui-org/devex-Fix-Stack-Overflow-tags-structure-1b9cbfe7b66080828083e7eccddf6d62
I noticed this because in https://app.ahrefs.com/site-audit/3523498/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CcontentType%2Cdepth%2CincomingAllLinks&current=26-03-2025T032224P0100&filterId=9b88587038fc9bb2e08e0ff143d5f328&issueId=c64d89a6-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating we have 
cc @mapache-salvaje for awareness.

[docs] Sync Stack Overflow docs with reality

---

docs/pages/_app.js

Since `@mui/material@latest` now resolves to v7, our demos at https://mui.com/x/react-data-grid/ do not work in codesandbox.
Here's an example: https://codesandbox.io/p/sandbox/infallible-dust-2zh9wf?file=%2Fpackage.json
We need to use v6 core packages to keep it working.

[docs] Use v6 core packages in MUI X v7 docs

---

packages/x-date-pickers/src/DigitalClock/DigitalClock.tsx

Follow up on https://github.com/mui/mui-x/pull/16774 to align the width of scrollbars between digital clocks.
|--------|------|
| ![Screenshot 2025-03-31 at 13 27 40](https://github.com/user-attachments/assets/ceab30a9-bb79-4dc2-ac59-dde72c334d29) | ![Screenshot 2025-03-31 at 13 27 53](https://github.com/user-attachments/assets/9b5ed3a5-40c7-49fa-960f-6a96e699ebcc) |

[TimePicker] Align DigitalClock scrollbar thickness

---

docs/pages/x/api/date-pickers/localization-provider.json
packages/x-date-pickers/src/LocalizationProvider/LocalizationProvider.tsx

Follow up on https://github.com/mui/mui-x/pull/17200.
The updated link does not exist on v8, hence updating to use `next.` and the appropriate section hash.

[docs] Update Localization Provider JSDoc link

---

packages/x-charts/src/colorPalettes/colorPalettes.ts

In this PR:
- Slightly adjusted the shades to work better for dark mode.
- We discussed with @joserodolfofreitas today that the order of the colors might work better like this, since in our docs, many demos showcase 3 different values, so the blue, yellow, red are more contrasting and complement each other better
|---|---|
| ![image](https://github.com/user-attachments/assets/98bcda12-041c-4df6-be29-235bb6edc393) | ![image](https://github.com/user-attachments/assets/ff303e81-e786-4509-99ab-21351a341684) |
| ![image](https://github.com/user-attachments/assets/2d84aa3f-b57d-4576-a117-88878dfc9b6c) | ![image](https://github.com/user-attachments/assets/b8dd4d10-83d6-4807-b12c-600f894158b9) |

[charts] Adjust color palettes

---

.mocharc.js
packages/x-codemod/package.json

Fix warning when running `pnpm test:unit`
```
(node:35926) [MODULE_TYPELESS_PACKAGE_JSON] Warning: 
Module type of file is not specified and it doesn't parse as CommonJS.
file:///mui-x/packages/x-codemod/src/v6.0.0/pickers/text-props-to-localeText/text-props-to-localeText.test.js 
```

[code-infra] Fix `test:unit` warning

---

docs/data/migration/migration-pickers-v7/migration-pickers-v7.md

This one is hard to document :grimacing: 
I made the choice of nos listing every single change and instead present the principles of the change, because they are hundreds of changes and the list would be horrible to read (and to write) imo.

[docs] Add migration guide for the picker's `ownerState` changes

---

docs/public/_redirects

Fix #17143
I'm also fixing the other broken ones that are visible in https://app.ahrefs.com/site-audit/3992793/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cdepth%2Ccompliant%2CincomingAllLinks%2Corigin&current=02-04-2025T045209P0200&filterId=91013c8aafad4fe1f7a0ad504eccad42&issueId=c64da643-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating.
Well, it's not really a fix, as after those changes, we have 301 instead of 404, but we should truly have 200. Now, since we plan to do a MUI X release very soon, we will get those 200 soon enough, so let's be lazy.
**Off-topic**. I would really want to delegate the ahrefs crawls to the team. It takes too much time on my plate. So far, our best guess is that the docs-infra role would be accountable for them, and each team responsible and …

[docs] Fix 404 link on the marketing page

---

docs/data/charts/bars/LabelsAboveBars.js
docs/data/charts/bars/LabelsAboveBars.tsx
docs/data/charts/bars/LabelsAboveBars.tsx.preview
docs/data/charts/bars/bars.md

Add labels above bars example. Related to https://github.com/mui/mui-x/issues/12975.

[charts] Add labels above bars example

---

docs/pages/x/api/charts/bar-element.json
docs/translations/api-docs/charts/bar-element/bar-element.json
packages/x-charts/src/BarChart/barElementClasses.ts

- Added `series` key to `barElementClasses` so users can write:
```ts
`${barElementClasses.series}-${seriesId}`

[charts] Export 'series' class as part of barElementClasses

---

babel.config.js
packages/x-charts-vendor/.babelrc.js
scripts/build.mjs

Based on https://github.com/mui/mui-x/pull/17058#pullrequestreview-2738900330
I was wondering if we should move this logic to the main babel config. Because for now the babel runtime version is managed by the `build.mjs`. I reverted the modification because I struggled with relative path. But I could try again if you think it's an improvement to force the correct version for all scripts

[core] Always use the correct babel runtime

---

packages/x-charts/src/BarChart/BarChart.test.tsx
packages/x-charts/src/BarChart/BarPlot.tsx

Test and Fix #17201 bug
Imported in bar chart the logic from the line chart. If a data item is `== null` it's either that the user set `null` or we overflow that data array. IN both case we can just ignore the data

[charts] Fix bar chart with partial data

---

packages/x-date-pickers/src/internals/hooks/useField/useFieldV7TextField.ts
test/utils/pickers/describePicker/describePicker.tsx

The click or keyboard event was propagating up top and this handler was processing it and focusing the input.
Aligning approach with the v6 hook:
https://github.com/mui/mui-x/blob/15f6ad2bd497646b6976aae79a3a2af795884785/packages/x-date-pickers/src/internals/hooks/useField/useFieldV6TextField.ts#L204-L209
Add a "describe" test to assert the expected behavior.
https://github.com/user-attachments/assets/e03bed88-4611-495c-ac5d-12b387a20863
https://github.com/user-attachments/assets/9843c54b-28d5-46d8-ab2d-572a9a18a461

[pickers] Fix to not process default prevented propagated events

---

packages/x-date-pickers-pro/src/DesktopDateTimeRangePicker/DesktopDateTimeRangePicker.tsx
packages/x-date-pickers-pro/src/DesktopDateTimeRangePicker/tests/DesktopDateTimeRangePicker.test.tsx
packages/x-date-pickers-pro/src/MobileDateTimeRangePicker/MobileDateTimeRangePicker.tsx
packages/x-date-pickers-pro/src/MobileDateTimeRangePicker/tests/MobileDateTimeRangePicker.test.tsx

- Remove override of `focusedView` to `null` which stopped defined value from taking effect
- Add tests asserting expected behavior
https://github.com/user-attachments/assets/5245eec9-1073-4c98-a7bf-45b3e5ac5028
https://github.com/user-attachments/assets/df3445eb-121c-4940-a09b-4052fd862007
https://github.com/user-attachments/assets/08bda9c0-188b-44a4-83e8-e8d700c20b0b
https://github.com/user-attachments/assets/aa746214-575a-4c4a-ac06-56b03bda8533

[DateTimeRangePicker] Fix focused view behavior

---

packages/x-data-grid-generator/src/columns/commodities.columns.tsx
packages/x-data-grid-generator/src/columns/employees.columns.tsx
packages/x-data-grid-generator/src/renderer/renderCountry.tsx

Fixes grouping by country reported in https://github.com/mui/mui-x/pull/16992/files#r2037611001
It affects both "Employee" and "Commodity" datasets.
Before:
After:

[docs] Fix country columns throwing on grouping

---

packages/x-data-grid-premium/src/hooks/features/pivoting/utils.ts

[DataGridPremium] Fix cell display with custom renderers in pivot mode

---

packages/x-data-grid-premium/src/hooks/features/aggregation/wrapColumnWithAggregation.tsx
packages/x-data-grid-premium/src/tests/aggregation.DataGridPremium.test.tsx

Fixes regression introduced by https://github.com/mui/mui-x/pull/17296
Preview: https://deploy-preview-17326--material-ui-x.netlify.app/x/react-data-grid/aggregation/#usage-with-row-grouping

[DataGridPremium] Fix aggregated values sorting

---

docs/data/migration/migration-charts-v7/migration-charts-v7.md

The current version stills tells to import from `ResponsiveChartContainer`, but component is now in a different file too.

[docs] Fix paths in `ResponsiveChartContainer` migration guide

---

packages/x-license/package.json
scripts/build.mjs

Also remove some of the values from the side effects array as after copying, the relative path would keep working, and the top-level package.json wouldn't be considered anyway for `./esm/utils/licenseInfo.js` by webpack as it finds a closer by package.json.
Solves https://github.com/mui/mui-x/pull/17359#discussion_r2042890008
> Ideally we just import the core script.
> ```tsx
> import '@mui/monorepo/scripts/build.mjs'
> ```
> To be investigated first how much the scripts have diverged.

[code-infra] Align build script with core to handle sideEffects

---

docs/pages/x/api/charts/area-element.json
docs/pages/x/api/charts/bar-label.json
docs/pages/x/api/charts/heatmap.json
docs/pages/x/api/charts/line-element.json
docs/pages/x/api/charts/mark-element.json
docs/pages/x/api/charts/pie-arc-label.json
docs/pages/x/api/charts/pie-arc.json
docs/translations/api-docs/charts/area-element/area-element.json
docs/translations/api-docs/charts/bar-label/bar-label.json
docs/translations/api-docs/charts/heatmap/heatmap.json
docs/translations/api-docs/charts/line-element/line-element.json
docs/translations/api-docs/charts/mark-element/mark-element.json
docs/translations/api-docs/charts/pie-arc-label/pie-arc-label.json
docs/translations/api-docs/charts/pie-arc/pie-arc.json
packages/x-charts-pro/src/FunnelChart/funnelSectionClasses.ts
packages/x-charts-pro/src/Heatmap/heatmapClasses.ts
packages/x-charts/src/BarChart/BarLabel/barLabelClasses.tsx
packages/x-charts/src/BarChart/barElementClasses.ts
packages/x-charts/src/LineChart/AreaElement.tsx
packages/x-charts/src/LineChart/LineElement.tsx
packages/x-charts/src/LineChart/markElementClasses.ts
packages/x-charts/src/PieChart/PieArc.tsx
packages/x-charts/src/PieChart/PieArcLabel.tsx

Document series class name, e.g., `lineElementClasses.series` since there was some confusion in [this issue](https://github.com/mui/mui-x/issues/15982#issuecomment-2802743632) that it was possible customize elements differently per series.

[charts] document series class name

---

docs/data/charts/line-demo/LineWithUncertaintyArea.js
docs/data/charts/line-demo/LineWithUncertaintyArea.tsx
docs/data/charts/line-demo/line-demo.md

Fixes https://github.com/mui/mui-x/issues/17254.
Happy to update colors if needed.

[charts] Add uncertainty area to line with forecast demo

---

packages/x-charts-pro/package.json
packages/x-charts/package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-internals/package.json
packages/x-license/package.json
packages/x-tree-view-pro/package.json
packages/x-tree-view/package.json
pnpm-lock.yaml

Replicate https://github.com/mui/mui-x/pull/17160 in v7.x since Material v7 is now stable.

[core] Cleanup `@mui` dependency versions

---

packages/x-data-grid/src/components/containers/GridRootStyles.ts

Closes https://github.com/mui/mui-x/issues/17029
Create a stacking context to prevent the scrollbars from showing over other elements.
Before: https://stackblitz.com/edit/react-yjbgmx5t?file=Demo.tsx

[DataGrid] Prevent scrollbars from showing on top

---

packages/x-charts-pro/src/ChartDataProviderPro/ChartDataProviderPro.tsx
packages/x-charts-pro/src/Heatmap/Heatmap.tsx
packages/x-charts/src/ChartDataProvider/useChartDataProviderProps.ts
packages/x-charts/src/RadarChart/RadarDataProvider/RadarDataProvider.tsx
packages/x-charts/src/context/ChartProvider/ChartProvider.types.ts
packages/x-charts/src/internals/plugins/allPlugins.ts

Add default plugins in `ChartDataProvider` and `ChartDataProviderPro` if the `plugins` prop is `undefined` or `null`. 
I don't think we need to consider this a breaking change since plugins only add extra functionality.
Unblocks https://github.com/mui/mui-x/pull/17285.

[charts] Add default plugins in `ChartDataProvider`

---

docs/data/charts/composition/composition.md

`ChartsLegend`'s `direction` prop is `vertical` or `horizontal`, not `row` or `column`.
https://github.com/mui/mui-x/blob/937bbc31ace347902dbe78f3ce3a2bc8e62d3ffa/packages/x-charts/src/ChartsLegend/ChartsLegend.tsx#L31
https://github.com/mui/mui-x/blob/3fe74a95d53dc96214fa7584e37f724da7785e13/packages/x-charts/src/ChartsLegend/direction.ts#L1

[charts] Fix chart direction in docs

---

docs/data/data-grid/components/ai-assistant-panel/GridAiAssistantPanelTrigger.js
docs/data/data-grid/components/ai-assistant-panel/GridAiAssistantPanelTrigger.tsx
docs/data/data-grid/components/ai-assistant-panel/GridAiAssistantPanelTrigger.tsx.preview

Fixes the demo on the AI Assistant Panel component docs. Currently, the trigger isn't opening the panel because we are not passing the component to the slot.

[docs] Fix AI Assistant Panel Trigger demo

---

test/regressions/TestViewer.tsx
test/regressions/index.tsx

This is necessary to run animation frames before taking a screenshot. This will also unblock changes in https://github.com/mui/mui-x/pull/17285 because the test in that PR requires an animation frame to run before the print dialog is shown.

[charts] advance time in charts regression tests

---

package.json
pnpm-lock.yaml
renovate.json

Fix `@types/node` management.
We have `v23.11.0` listed in dependencies; however, such a version does not exist.
Installation probably didn't complain, because we kept the `v20` resolution.
Since our CI is running on bleeding edge v23, I think it's safe to say that we can run the codebase at least on v22. 🙈 
At the same time, I've removed the `resolutions` altogether as only `exceljs -> fast-csv -> @fast-csv/parse & @fast-csv/format` deps pick up `v14` of the dependency.
I couldn't target `resolutions` to override types only for that particular package, probably because `pnpm why @types/node` doesn't find it as well. 🙈 
We could override `exceljs>fast-csv` to v5 if we wanted, since it looks like it involved only dep changes, but I don't think the current state is bad anyway. 🤔 
I've also …

[core] Bump `@types/node`

---

docs/package.json
package.json
packages/x-charts/package.json
pnpm-lock.yaml
renovate.json

Follow-up on https://github.com/mui/mui-x/pull/17444#issuecomment-2816551216.
The `react-is` dependency is not used anywhere in this repository explicitly.
Dependencies using it have it listed in the dependencies list (`@mui/utils` & `@mui/material`).
Removing from `@mui/x-charts` package as it seems that it's usage has been removed from the package.

[core] Remove `react-is` dependency

---

test/regressions/TestViewer.tsx
test/regressions/index.test.ts
test/regressions/index.tsx

Second attempt at fixing charts visuals flakiness.
First attempt: https://github.com/mui/mui-x/pull/17469
PR that introduced the flakiness: https://github.com/mui/mui-x/pull/17420
Basically, this PR is reverting the changes in https://github.com/mui/mui-x/pull/17420. We'll only advance time in the print export test. All other chart tests should be unchanged.

[charts] fix charts visuals flakiness

---

packages/x-charts/src/ChartsTooltip/ChartsTooltipContainer.tsx
packages/x-charts/src/ChartsTooltip/utils.tsx

The tooltip was not visible on my phone. The reason is the `(event as PointerEvent).height` which returns a value between 10 and 2000 (yes, a x200 range) which of course put the tooltip outside to the screen
I tested on another phone, and it returns 0.
Since this `height` property does not seem reliable, I remove its usage, and replace it with a fixed padding.
I also updatedthe  fallback to avoid as much as possible getting the tooltip below the thumb for right-handed people

[charts] Fix tooltip position

---

docs/src/modules/components/overview/CommunityOrPro.tsx

https://mui.com/x/react-tree-view/ feels a bit strange:
(annotation through https://chromewebstore.google.com/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh)

[tree view][docs] Fix heading structure

---

docs/data/charts/composition/composition.md
docs/data/migration/migration-charts-v7/migration-charts-v7.md

Fix the following docs feedback
> The only time ChartsLegend component is to create a custom HTML component with ChatsSurface and ChartsDataProvider, and thus a customized legend. Before, in v7, it was possible to use ChatsLegend inside ChartContainer with together with multiple Line/BarPlots, unfortunately this page as no indication/help/example for that scenario. All graphs rendered here have no legend.
sent from https://mui.com/x/react-charts/composition/

[docs][chart] Add docs information for Legend HTML

---

packages/x-data-grid-premium/src/components/aiAssistantPanel/GridAiAssistantPanelConversationsMenu.tsx

The `material` prop should not be used internally, only on docs examples and in user-land.
For now we can live without the dense version of menu items.

[DataGrid] Remove internal usage of `material` prop

---

packages/x-date-pickers/src/PickersTextField/PickersFilledInput/PickersFilledInput.tsx
packages/x-date-pickers/src/PickersTextField/PickersInput/PickersInput.tsx
packages/x-date-pickers/src/PickersTextField/PickersInputBase/PickersInputBase.tsx
packages/x-date-pickers/src/PickersTextField/PickersInputBase/PickersInputBase.types.ts
packages/x-date-pickers/src/PickersTextField/PickersOutlinedInput/Outline.tsx
packages/x-date-pickers/src/PickersTextField/PickersOutlinedInput/PickersOutlinedInput.tsx
packages/x-date-pickers/src/PickersTextField/PickersTextField.tsx
packages/x-date-pickers/src/PickersTextField/PickersTextField.types.ts
packages/x-date-pickers/src/PickersTextField/index.ts
packages/x-date-pickers/src/PickersTextField/usePickerTextFieldOwnerState.ts
packages/x-date-pickers/src/models/fields.ts
packages/x-date-pickers/src/themeAugmentation/themeAugmentation.spec.ts
scripts/x-date-pickers-pro.exports.json
scripts/x-date-pickers.exports.json

Related to https://github.com/mui/mui-x/issues/17297.
Partially solve some slight inconsistencies.
___
However, the actual type should be only `PickerTextFieldOwnerState`.

[pickers] Improve `PickersInputBase` owner state typing

---

packages/x-data-grid/src/locales/index.ts

New locale was not exported in https://github.com/mui/mui-x/pull/17422

[l10n] Fix l10n export

---

packages/x-data-grid-premium/src/DataGridPremium/useDataGridPremiumProps.ts
packages/x-data-grid-pro/src/DataGridPro/useDataGridProProps.ts
packages/x-data-grid/src/DataGrid/useDataGridProps.ts

This PR is fixes #17128 using an alternate approach to https://github.com/mui/material-ui/pull/45943
All cells change value when entering edit mode.
https://codesandbox.io/p/sandbox/17490-before-76t4mt
https://github.com/user-attachments/assets/0004b2dd-efbd-4afb-b843-be8d93425d3e
Only the selected cell changes value when entering edit mode.
https://codesandbox.io/p/sandbox/17490-after-ftlktq
https://github.com/user-attachments/assets/ce6c8472-97c0-4b7c-9440-cf1846ef5ad5

[DataGrid] Fix theme `defaultProps` causing unwanted re-renders

---

packages/x-data-grid-premium/src/DataGridPremium/useDataGridPremiumComponent.tsx
packages/x-data-grid-pro/src/DataGridPro/useDataGridProComponent.tsx
packages/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.tsx
packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts
packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridInfiniteLoadingIntersection.tsx
packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridIntersectionObserver.tsx
packages/x-data-grid-pro/src/internals/index.ts
packages/x-data-grid-pro/src/tests/dataSourceLazyLoader.DataGridPro.test.tsx
packages/x-data-grid/src/models/events/gridEventLookup.ts

I have extracted IntersectionObserver logic into a separate hook and moved it to the server side feature folder, since the client side feature is deprecated.
Both client and server side infinite loading are now listening to the new internal event from this hook to handle the data update
There are two main reasons for doing this:
1. With the intersection observer we are covering more cases where the new data fetch should occur. One of them is if the page size is not big enough to fill the whole viewport. With the observer additional data is fetched until the viewport is filled.
2. IntersectionObserver events are far less frequent than scroll events, so handling those reduces the impact on the grid performance

[DataGridPro] Use intersection observer to trigger server-side infinite loading

---

docs/package.json
pnpm-lock.yaml
test/e2e/package.json
test/package.json
test/regressions/package.json

Closes https://github.com/mui/mui-x/pull/17541 (and supercedes).

Bump `react-router` to ^7.5.2 [SECURITY]

---

docs/data/data-grid/accessibility/accessibility.md
docs/data/data-grid/cell-selection/cell-selection.md
docs/data/data-grid/clipboard/clipboard.md
docs/data/data-grid/components/toolbar/toolbar.md
docs/data/tree-view/accessibility/accessibility.md

Fixing regressions from #3297
Preview: https://deploy-preview-17536--material-ui-x.netlify.app/x/react-data-grid/accessibility/#navigation

[core][docs] Fix <kbd> a11y

---

packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianAxis.test.tsx
packages/x-charts/src/internals/plugins/featurePlugins/useChartPolarAxis/useChartPolarAxis.test.tsx
packages/x-data-grid-premium/src/tests/cellSelection.DataGridPremium.test.tsx
packages/x-data-grid-premium/src/tests/pivoting.DataGridPremium.test.tsx
packages/x-data-grid-pro/src/tests/columnHeaders.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/columns.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/rowEditing.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/rowSelection.DataGridPro.test.tsx
packages/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx
packages/x-data-grid/src/tests/slots.DataGrid.test.tsx

Same as with previous PRs, goal is to trim down changes in the [main PR](https://github.com/mui/mui-x/pull/14508), though there were adjustments I had to make for mocha/karma 🫠 
Most notable changes are commented

[code-infra] Further remove `clock=fake` and add `async act` for datagrid

---

docs/data/charts/highlighting/highlighting.md

https://mui.com/x/react-charts/highlighting/ looked really strange. I assumed the content was in a page, moved to another page, and we forgot to flatten the headers.
Noticed this in #17580
Preview: https://deploy-preview-17581--material-ui-x.netlify.app/x/react-charts/highlighting/

[charts][docs] Fix highlighting heading structure

---

docs/pages/_app.js
package.json

The link in https://v6.mui.com/x/introduction/ to v7 is outdated now.
I have noticed this from https://mui-org.slack.com/archives/C041SDSF32L/p1745416149123639. I thought we might fix this, quick-win. It could help people migrate https://tools-public.mui.com/prod/pages/npmVersion?package=@mui/x-data-grid
I also used the opportunity to fix the CI on this branch. v6.x is on LTS in case we need to release hot fixes: https://mui.com/x/introduction/support/#supported-versions.
---
For the future, steps added in https://www.notion.so/mui-org/Name-vX-0-0-1e2cbfe7b66080ce89fef5ac5eaeb4e7?pvs=4#1e2cbfe7b66080498d6ecfc8c5969d2d and marked it as done https://www.notion.so/mui-org/MUI-X-v8-0-0-1e2cbfe7b6608092934afbe7e2b5df22?pvs=4#1e2cbfe7b6608025b9b5ffee59f2e2e4. We could also have a "View all …

[docs] Add link to version

---

packages/x-charts-pro/src/internals/plugins/useChartProExport/common.ts
packages/x-charts-pro/src/internals/plugins/useChartProExport/exportImage.ts
packages/x-charts-pro/src/internals/plugins/useChartProExport/print.ts
packages/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx
packages/x-internals/src/export/index.ts
packages/x-internals/src/export/loadStyleSheets.tsx

Move `loadStyleSheets` to `@mui/x-internals` and use it in data grid and charts.

[core] Move loadStyleSheets to internals and use it in data grid and charts

---

packages/x-date-pickers-pro/src/MobileDateTimeRangePicker/tests/MobileDateTimeRangePicker.test.tsx
test/utils/pickers/describeRangeValidation/testDayViewRangeValidation.tsx

Same as with previous PRs, goal is to trim down changes in the [main PR](https://github.com/mui/mui-x/pull/14508)

[code-infra] Latest vitest picker changes

---

packages/x-data-grid/src/material/variables.ts
packages/x-internals/src/hash/index.ts
packages/x-internals/src/hash/stringify.ts

The theme may contains circular references, so it needs special handling for stringification & hashing.
Closes https://github.com/mui/mui-x/issues/17442
Closes https://github.com/mui/mui-x/issues/17521
Before: https://codesandbox.io/p/devbox/x-react-data-grid-getting-started-forked-nl9s3p?from-embed=&workspaceId=ws_3SJ17h6UtA66t5QH97aCiT

[DataGrid] Fix: circular reference error

---

test/e2e/package.json
test/regressions/package.json

As I understand it, for private npm packages, the version is optional, so we might as well delete it to keep things simple.

[core] Remove empty version

---

.circleci/config.yml
docs/constants.ts
docs/data/introduction/support/support.md
docs/data/migration/migration-charts-v7/migration-charts-v7.md
docs/data/migration/migration-data-grid-v7/migration-data-grid-v7.md
docs/data/migration/migration-pickers-v7/migration-pickers-v7.md
docs/data/migration/migration-tree-view-v7/migration-tree-view-v7.md
docs/pages/_app.js
docs/src/modules/components/ChartsInstallationInstructions.js
docs/src/modules/components/DataGridInstallationInstructions.js
docs/src/modules/components/PickersInstallationInstructions.js
docs/src/modules/components/TreeViewInstallationInstructions.js
packages/x-codemod/README.md
scripts/README.md
scripts/releaseChangelog.mjs

This replaces the `#default-branch-switch` comments with one of the following 3:
- `#target-branch-reference`: the git branch corresponding to where the code is worked on.
- `#npm-tag-reference`: the npm tag corresponding to where the code is published.
- `#host-reference`: the URL corresponding to where the docs are deployed.
According to [this notion document](https://www.notion.so/mui-org/React-Major-release-process-0178410ef26941e6a4f333f80ded127a?pvs=4)

[infra] Updates to `branch switch comments`

---

docs/data/charts/tooltip/TooltipStyle.js
docs/data/charts/tooltip/TooltipStyle.tsx
docs/data/charts/tooltip/TooltipStyle.tsx.preview
docs/data/charts/tooltip/tooltip.md

Fixes https://github.com/mui/mui-x/issues/17594.
The tooltip has the particularity that it cannot be styled directly with `sx`. This PR adds a docs section to explain how to style it.

[charts] Add docs on tooltip style

---

package.json

[code-infra] Allow postinstall scripts for packages requesting it

---

packages/x-data-grid/src/components/panel/GridPanel.tsx
packages/x-data-grid/src/material/index.tsx

The panels should be aligned to the side of the trigger
| --- | --- |
| <img width="311" alt="Screenshot 2025-04-30 at 09 32 00" src="https://github.com/user-attachments/assets/4a0c74a8-a2f4-4cee-acfc-293ad0fe11a2" /> | <img width="307" alt="Screenshot 2025-04-30 at 09 31 21" src="https://github.com/user-attachments/assets/44868064-b788-45b0-97a0-257c7a957184" /> |

[DataGrid] Fix panel alignment

---

test/utils/pickers/describeValidation/testDayViewValidation.tsx
test/utils/pickers/describeValidation/testMonthViewValidation.tsx
test/utils/pickers/describeValidation/testYearViewValidation.tsx

- Added fake timers to `should apply disablePast` and `should apply disableFuture` to prevent issues on date boundaries
- Should prevent https://app.circleci.com/pipelines/github/mui/mui-x/90474/workflows/c15dd0bf-da32-4fd5-9b5b-4a3de0c38671/jobs/525643

[test] Fix date-time sensitive tests

---

docs/data/charts/bar-demo/PopulationPyramidBarChart.js
docs/data/charts/bar-demo/PopulationPyramidBarChart.tsx
docs/data/charts/bar-demo/bar-demo.md

Add a population pyramid demo with data for South Korea in 2022.
Data source: [KOSIS](https://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1BPA001&conn_path=I2&language=en).

[charts] Add population pyramid demo

---

docs/data/charts/zoom-and-pan/ZoomSliderComposition.js
docs/data/charts/zoom-and-pan/ZoomSliderComposition.tsx

[docs][charts] Fix randomised argos test

---

docs/data/charts/sparkline/SparklineLineWidth.js
docs/data/charts/sparkline/SparklineLineWidth.tsx
docs/data/charts/sparkline/sparkline.md
docs/pages/x/api/charts/charts-clip-path.json
docs/pages/x/api/charts/spark-line-chart.json
docs/translations/api-docs/charts/charts-clip-path/charts-clip-path.json
docs/translations/api-docs/charts/spark-line-chart/spark-line-chart.json
packages/x-charts/src/ChartsClipPath/ChartsClipPath.tsx
packages/x-charts/src/SparkLineChart/SparkLineChart.tsx

Fixes https://github.com/mui/mui-x/issues/15221.
Before we weren't respecting the margin because the drawing area wasn't being clipped, but it is now. The examples below have a margin of 5px, which wasn't respected before.
Before:
After:
Fix sparkline not clipping elements outside the drawing area. Clipping can be disabled by setting `disableClipping` to true.

[charts] Fix spark line not having clip path

---

packages/x-date-pickers-pro/src/internals/hooks/useDesktopRangePicker/useDesktopRangePicker.tsx
packages/x-date-pickers-pro/src/internals/hooks/useMobileRangePicker/useMobileRangePicker.tsx
packages/x-date-pickers/src/internals/components/PickersModalDialog.tsx
pnpm-lock.yaml
test/package.json
test/utils/pickers/describeValue/testPickerOpenCloseLifeCycle.tsx

For now, the range position is reset to `start` only when the Desktop range Picker is closed.
This PR fixes to do the same for Mobile Picker and adds to ensure this behavior is stable.

[DateRangePicker] Fix to reset range position after closing mobile Picker

---

.circleci/config.yml

Remove `requires: - checkout` for circleci steps. 
It doesn't speed up the tests, and only blocks running the cases we forget to dedupe the installs.
This should trim ~2 minutes from the overall wait time for the tests to run, since all tests wait for this to finish.

[code-infra] Remove required checkout step

---

packages/x-data-grid-pro/src/tests/rowEditing.DataGridPro.test.tsx
packages/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts

Fixes https://github.com/mui/mui-x/issues/17298

[DataGrid] Ignore `preProcessEditCellProps` for non-editable columns when starting a row update

---

docs/data/charts/export/export.md
docs/data/charts/zoom-and-pan/zoom-and-pan.md

I was almost going to delete the whole sentence, but this is a bit of a larger scope, so stick to fixing the layout and experience:
- Make sure the whole block line break with an unbreakable space (the initial opportunity I saw)
- Remove the logo, it makes the sentence hard to read, breaks the flow, and draws too much visual attention.
Before
After
Preview: https://deploy-preview-17715--material-ui-x.netlify.app/x/react-charts/export/.

[charts][docs] Fix weird line wrap export

---

packages/x-data-grid-premium/src/components/pivotPanel/GridPivotPanelField.tsx

Fixes label issue I noticed in https://github.com/mui/mui-x/issues/17616#issuecomment-2864379145

[DataGridPremium] Fix aggregation label not being used in pivot panel

---

test/performance-charts/tests/ScatterChartPro.bench.tsx

Add benchmark for zoomed in scatter chart.
Used to compare with [this performance improvement](https://github.com/mui/mui-x/pull/17755).

[charts-pro] add benchmark for zoomed in scatter chart

---

packages/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts

Fixes https://github.com/mui/mui-x/issues/14130
Before: https://stackblitz.com/edit/vaghyrmw
After: https://stackblitz.com/edit/vaghyrmw-a2jg1urg

[DataGrid] Fix column spanning jump on scroll

---

docs/scripts/tsconfig.json
docs/tsconfig.json
packages/x-tree-view-pro/src/internals/index.ts
tsconfig.dev.json
tsconfig.json
tsconfig.prod.json

Prevents missing required `export type` in some instances.
Eg: https://github.com/mui/mui-x/issues/17772

[code-infra] Set `isolatedModules=true` in tsconfig

---

packages/x-data-grid-pro/src/tests/rowSelection.DataGridPro.test.tsx
packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts

Extracted from https://github.com/mui/mui-x/pull/17743
Makes the grid use `exclude` selection type if quick filter has values, but they are all empty strings
like
```ts
initialState={{
filter: {
filterModel: {
items: [],
quickFilterValues: [''],
},
},
}}
```

[DataGrid] Use `exclude` selection model type if quick filter does not have actual values

---

packages/x-charts-pro/src/internals/plugins/useChartProExport/exportImage.ts

Fixes https://github.com/mui/mui-x/issues/17893.
I've discussed this change with @Janpot and this seems to be the safest way to work in most bundlers for the time being. Although, as a long-term solution we should try to contribute to rasterizehtml and update it to support ESM, fork it, or choose another library. A library that doesn't support ESM might come and bite us in the future.

[charts-pro] fix error when importing rasterizehtml

---

packages/x-charts-pro/src/internals/plugins/useChartProZoom/useChartProZoom.ts
packages/x-charts/src/ChartsXAxis/ChartsXAxis.tsx
packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx
packages/x-charts/src/LineChart/LineHighlightPlot.tsx
packages/x-charts/src/LineChart/MarkPlot.tsx
packages/x-charts/src/ScatterChart/Scatter.tsx
packages/x-charts/src/hooks/useTicks.ts
packages/x-charts/src/internals/plugins/corePlugins/useChartDimensions/useChartDimensions.ts
packages/x-charts/src/internals/plugins/corePlugins/useChartDimensions/useChartDimensions.types.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianAxis.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartPolarAxis/useChartPolarAxis.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartVoronoi/useChartVoronoi.ts

Improve performance in scatter chart by reducing the amount of allocations made. `isPointInside` is called many times when calculating which points to show, so by moving from object arguments to positional arguments the performance improved slightly.

[charts] Improve performance in scatter chart 

---

packages/x-charts/src/ChartsXAxis/ChartsXAxis.tsx
packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx
packages/x-charts/src/hooks/useTicks.ts
packages/x-charts/src/internals/plugins/corePlugins/useChartDimensions/useChartDimensions.ts
packages/x-charts/src/internals/plugins/corePlugins/useChartDimensions/useChartDimensions.types.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianAxis.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartPolarAxis/useChartPolarAxis.ts

Follow-up to [this comment](https://github.com/mui/mui-x/pull/17849#pullrequestreview-2852983848). 
Should improve performance slightly by reducing the number of allocations in the hot path. `isPointInside` is called many times, especially when zoomed in.

[charts] add `isXInside` and `isYInside`

---

packages/x-data-grid-pro/src/components/GridRowReorderCell.tsx
packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx
packages/x-data-grid/src/components/containers/GridRootStyles.ts

Closes https://github.com/mui/mui-x/issues/16303
[Debug Info on the same](https://github.com/mui/mui-x/issues/16303#issuecomment-2639944018)

[DataGridPro] Prevent text selection when reordering rows

---

docs/data/charts/axis/GroupedAxes.js
docs/data/charts/axis/GroupedAxes.tsx
docs/data/charts/axis/axis.md
docs/pages/x/api/charts/charts-axis.json
docs/pages/x/api/charts/charts-x-axis.json
docs/pages/x/api/charts/charts-y-axis.json
docs/translations/api-docs/charts/charts-axis/charts-axis.json
docs/translations/api-docs/charts/charts-x-axis/charts-x-axis.json
docs/translations/api-docs/charts/charts-y-axis/charts-y-axis.json
packages/x-charts/src/ChartsAxis/axisClasses.ts
packages/x-charts/src/ChartsXAxis/ChartsXAxis.tsx
packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx

Fixes https://github.com/mui/mui-x/issues/17839.
Add grouped axes demo. To achieve this, I added the axis ID to the class names so it's easier to target the given axis. 
I'm not very fond of the hack to make every third tick bigger than normal, but `line` elements' `x` and `y` properties cannot be styled using CSS.

[charts] Add grouped axes demo

---

docs/data/data-grid/quickstart/quickstart.md

DataGrid- Quickstart: Remove the double border on the demo to keep consistency
Before:
After:

[docs] Remove double border on DataGrid- Quickstart 

---

packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx
packages/x-date-pickers/src/DateField/tests/selection.DateField.test.tsx
packages/x-date-pickers/src/internals/hooks/useField/useFieldSectionContainerProps.ts
packages/x-date-pickers/src/internals/hooks/useField/useFieldSectionContentProps.ts

Closes #17895
Fixes old disable value when reenabling pickers
- [x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

[fields] Ensure fresh `disabled` value is used when focusing or clicking

---

docs/data/charts/heatmap/heatmap.md
docs/data/chartsApiPages.ts
docs/pages/x/api/charts/heatmap-tooltip-content.js
docs/pages/x/api/charts/heatmap-tooltip-content.json
docs/translations/api-docs/charts/heatmap-tooltip-content/heatmap-tooltip-content.json
packages/x-charts-pro/src/Heatmap/Heatmap.tsx
packages/x-charts-pro/src/Heatmap/HeatmapTooltip/HeatmapTooltip.classes.ts
packages/x-charts-pro/src/Heatmap/HeatmapTooltip/HeatmapTooltip.tsx
packages/x-charts-pro/src/Heatmap/HeatmapTooltip/HeatmapTooltip.types.ts
packages/x-charts-pro/src/Heatmap/HeatmapTooltip/HeatmapTooltipContent.tsx
packages/x-charts-pro/src/Heatmap/HeatmapTooltip/index.ts
scripts/x-charts-pro.exports.json

The Heatmap got kind forgotten in the tooltip refactoring.
While updating the docs, I also made the content of the tooltip available to have a 1-1 correspondence with the DX of common tooltip

[charts] Clean and document Heatmap Tooltip

---

docs/data/data-grid/pivoting/GridGetPivotDerivedColumns.js
docs/data/data-grid/pivoting/GridGetPivotDerivedColumns.tsx
docs/data/data-grid/pivoting/GridPivotingFinancial.js
docs/data/data-grid/pivoting/GridPivotingFinancial.tsx

Closes https://github.com/mui/mui-x/issues/17924
`groupingValueGetter` must be used since grouped column does not support `date`

[docs] Fix derived column pivoting demo crash 

---

packages/x-charts/src/internals/plugins/featurePlugins/useChartHighlight/useChartHighlight.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartInteraction/useChartInteraction.ts

Use `fastObjectShallowCompare` to compare the previous and next highlighted items to decide whether to update the store and call `onHighlightChange`. 
At the moment, `onHighlightChange` is called even if the `newItem` hasn't changed, so this change fixes that behavior as well.

[charts] Only update store if interaction item is different

---

docs/data/charts/zoom-and-pan/ZoomSlider.js
docs/data/charts/zoom-and-pan/ZoomSlider.tsx
packages/x-charts-pro/src/BarChartPro/BarChartPro.tsx
packages/x-charts-pro/src/ChartZoomSlider/internals/ChartAxisZoomSlider.tsx
packages/x-charts-pro/src/FunnelChart/FunnelChart.tsx
packages/x-charts-pro/src/LineChartPro/LineChartPro.tsx
packages/x-charts-pro/src/ScatterChartPro/ScatterChartPro.tsx
packages/x-charts-pro/src/internals/plugins/useChartProZoom/useChartProZoom.ts
packages/x-charts-pro/src/internals/plugins/useChartProZoom/useChartProZoom.types.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianAxisRendering.selectors.ts

Part of https://github.com/mui/mui-x/issues/15383.
Adds a range selection to zoom slider. It respects all zoom options (e.g., `minSpan`, `minStart`). 
https://github.com/user-attachments/assets/821146a8-2827-40ac-8a5d-c08519bae817
Selection starts too close to the end and the cursor goes to the right, so the `minSpan` of 10 wouldn't be respected. In this case, we need to move the start to the left.
https://github.com/user-attachments/assets/3ca28e61-8cd0-450c-8d24-7bcc52a91f4f
Selection starts outside `minStart`. In this case, we move the start to `minStart` and adjust the end accordingly.
https://github.com/user-attachments/assets/40571f5d-e262-42e6-9edf-9ebd9be6f564

[charts-pro] Add range selection to zoom slider

---

packages/x-date-pickers-pro/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx
packages/x-date-pickers-pro/src/MobileDateRangePicker/MobileDateRangePicker.tsx

[DateRangePicker] Allow to override the format in the field

---

packages/x-charts/src/internals/domUtils.ts
packages/x-charts/src/internals/index.ts
test/setupVitest.ts
test/utils/mochaHooks.js

Use Map for string cache instead of object. We get entry counting for free. 
Also removed `unstable_cleanupDOM` since it wasn't doing anything.

[charts] Use Map for string cache instead of object

---

docs/data/charts/bar-demo/PopulationPyramidBarChart.js
docs/data/charts/bar-demo/PopulationPyramidBarChart.tsx

A continuation of #17652 and #17980. https://mui.com/x/react-charts/bar-demo/#population-pyramid has a number of problems:
1. I have never seen an age pyramid rendered in this order. This is the "right" way IMHO: https://en.wikipedia.org/wiki/Population_pyramid.
2. It's hard to read on mobile: 
3. We render a h6 in the page, orphan from the other headers.
Preview: https://deploy-preview-17987--material-ui-x.netlify.app/x/react-charts/bar-demo/#population-pyramid
---
**Off-topics**:  I don't understand this: https://github.com/mui/mui-x/blob/ecc9177a6a522ab5f699fe1affbfc3387f289ed5/packages/x-charts/src/constants/index.ts#L5-L10
I thought we would get 0 for all those values. I had to set `margin={{ right: 0, left: 0 }}` and then use CSS to set the margin that I wanted, with responsive …

[charts][docs] Fix Population pyramid demo

---

packages/x-charts-pro/src/ChartContainerPro/ChartProApi.ts
packages/x-charts-pro/src/context/useChartApiContext.ts
packages/x-charts/src/ChartContainer/ChartContainer.tsx
packages/x-charts/src/context/index.ts
packages/x-charts/src/context/useChartApiContext.ts
packages/x-charts/src/internals/plugins/allPlugins.ts
scripts/x-charts-pro.exports.json
scripts/x-charts.exports.json

Expose `ChartApi` through context so that descendants of `ChartDataProvider` can access it without having to pass `apiRef` as props. 
I tried to make the API similar to the [Data Grid's](https://mui.com/x/react-data-grid/api-object/#inside-the-data-grid):
Data Grid:
```tsx
function CustomFooter() {
const apiRef = useGridApiContext();
return <Button onClick={() => apiRef.current.setPage(1)}>Go to page 1</Button>;
}
```
Charts:
```tsx
function ResetZoomButton(props) {
const apiRef = useChartApiContext();
return (
<ToolbarButton
{...props}
onClick={() => {
apiRef.current.setZoomData((prev) =>
prev.map((zoom) => ({ ...zoom, start: 0, end: 100 })),
);
}}
render={<Button />}
/>
);
}
```
This PR doesn't have an example usage. That will be added in this [PR …

[charts] Expose ChartApi through context

---

packages/x-data-grid-pro/src/hooks/features/columnPinning/useGridColumnPinningPreProcessors.ts
packages/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx
packages/x-data-grid/src/hooks/features/columns/gridColumnsSelector.ts

Fixes #17889
The column management section was not respecting order of pinned columns when users were changing visibility of columns. As a result this user interaction led to change in the order of the columns in column panel.
This fix ensures column management section keeps the same order as the pinned columns in the grid.

[DataGridPro] Fix pinned columns order in column management

---

docs/data/charts/zoom-and-pan/ZoomSlider.js
docs/data/charts/zoom-and-pan/ZoomSlider.tsx
packages/x-charts-pro/src/ChartZoomSlider/internals/ChartAxisZoomSliderActiveTrack.tsx
packages/x-charts/src/internals/index.ts
packages/x-charts/src/internals/invertScale.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianAxisRendering.selectors.ts
packages/x-charts/src/models/axis.ts

Show axis value in zoom slider tooltip instead of a value 0-100. 
I had misunderstood the designs and we were never meant to show a range 0-100, so this PR is fixing that issue. 
https://github.com/user-attachments/assets/53acddf3-0ac4-404b-958c-019b259bb155

[charts-pro] Show axis value in zoom slider tooltip

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/arSD.ts

- [x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
I have translated the column selector for the latest version of mui-x.  These translations are missing in 7 and 8

[l10n] Improve Arabic (ar-SD) locale

---

docs/data/scheduler/event-calendar/StandaloneWeekView.js
docs/data/scheduler/event-calendar/StandaloneWeekView.module.css
docs/data/scheduler/event-calendar/StandaloneWeekView.tsx
docs/data/scheduler/event-calendar/StandaloneWeekView.tsx.preview
docs/data/scheduler/event-calendar/event-calendar.md
packages/x-scheduler/src/joy/header-toolbar/HeaderToolbar.css
packages/x-scheduler/src/joy/header-toolbar/view-switcher/ViewSwitcher.css
packages/x-scheduler/src/joy/week-view/WeekView.tsx

- Added temporary dark mode styles for the View Switcher to prevent it from looking broken until the final design is ready.
- Added missing Standalone Week View to the docs.

[scheduler] Add temporary dark mode styles (view switcher) and standalone week view demo

---

docs/pages/x/api/charts/heatmap.json
docs/translations/api-docs/charts/heatmap/heatmap.json
packages/x-charts-pro/src/Heatmap/Heatmap.tsx

Render the toolbar in the heatmap chart.
At the moment, there isn't anything to show in the toolbar, but https://github.com/mui/mui-x/pull/18210 will introduce the export button in the toolbar.

[charts-pro] Render the toolbar in the heatmap chart

---

CHANGELOG.md
package.json
packages/x-charts-pro/package.json
packages/x-charts-vendor/package.json
packages/x-charts/package.json
packages/x-codemod/package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-internals/package.json
packages/x-license/package.json
packages/x-telemetry/package.json
packages/x-tree-view-pro/package.json
packages/x-tree-view/package.json

[release] v8.5.1

---

packages/x-internals/src/useComponentRenderer/useComponentRenderer.test.tsx
packages/x-internals/src/useComponentRenderer/useComponentRenderer.tsx

First part of https://github.com/mui/mui-x/issues/18205.
Remove `sx` prop merging from `useComponentRenderer` as it isn't being used in the Data Grid nor Charts. If everything works well, then I'll go ahead and replace `useComponentRenderer` with Base UI's version in a follow-up PR.

[DataGrid][charts] Remove sx prop merging from `useComponentRenderer`

---

packages/x-charts-pro/src/ChartZoomSlider/internals/ChartAxisZoomSliderActiveTrack.tsx
packages/x-charts/src/internals/defaultValueFormatters.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts
packages/x-charts/src/models/axis.ts

Follow-up to https://github.com/mui/mui-x/pull/18054. 
Fixes https://github.com/mui/mui-x/issues/18022.
Add a default value formatter for continuous scales.

[charts] Add a default value formatter for continuous scales

---

docs/data/guides/telemetry/telemetry.md
packages/x-telemetry/src/runtime/events.ts

A quick win while I was looking at #18257:
1. I don't feel like https://github.com/mui/mui-x/pull/17244#discussion_r2030289530 was correctly handled.
2. When looking at the overhead of the package in production, with https://bundlejs.com/?q=%40mui%2Fx-telemetry%408.5.1, we get this, before running Prettier:
```jsx
var r = {
licenseVerification: (t, i) => ({
eventName: "licenseVerification",
payload: i,
context: t,
}),
},
n = r;
var e = () => {},
l = e,
s = { enableDebug: e, enableTelemetry: e, disableTelemetry: e };
export {
n as muiXTelemetryEvents,
s as muiXTelemetrySettings,
l as sendMuiXTelemetryEvent,
};
```
456 B / 291 B (gzip)
which we can reduce down to:
```jsx
var r={licenseVerification:()=>{}},n=r;var e=()=>{},l=e,s={enableDebug:e,enableTelemetry:e,disableTelemetry:e};export{n …
```

[x-telemetry][docs] Reduce Telemetry overhead

---

packages/x-data-grid-pro/src/tests/columns.DataGridPro.test.tsx
packages/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts

Closes #17969
When updating flex column widths, we were mutating the `columnsLookup` obj directly which could cause missing the state update. This change creates a new object
for the column lookup to ensure the component properly detects and applies the width changes.
This fixes issues where flex column width changes weren't being reflected in the UI,
particularly when using pinned columns.

[DataGridPro] Fix flex column width if it is a pinned column

---

docs/data/charts/zoom-and-pan/ZoomSliderTooltip.js
docs/data/charts/zoom-and-pan/ZoomSliderTooltip.tsx
docs/data/charts/zoom-and-pan/zoom-and-pan.md
packages/x-charts/src/models/index.ts
scripts/x-charts-pro.exports.json
scripts/x-charts.exports.json

Follow-up to https://github.com/mui/mui-x/pull/18178.
Document zoom slider tooltip value formatting.

[charts-pro] Document zoom slider tooltip value formatting

---

.github/workflows/ci.yml
.github/workflows/codspeed.yml
.github/workflows/l10n.yml
netlify.toml

- Align Node to v22 on CI where specified.
- Explicitly increase the allowed heap memory on Netlify environment to hopefully avoid flaky OOM issues when deploying docs.

[code-infra] Align Node version used in CI to v22

---

packages/x-scheduler/src/joy/internals/components/time-grid/TimeGrid.css

Issue #18335 
There is a small visual misalignment in the "All day" cell of the calendar when viewed on Windows.
The misalignment seems to be specific to Windows, everything looks fine on macOS (Chrome, Safari, Firefox checked).
_Expected behavior:_
The "All day" cell should be perfectly aligned with the rest of the grid and headers.
**Demo on VM**

[scheduler][joy] Small misalignment in "All day" cell on Windows

---

docs/data/scheduler/primitives/DayGridPrimitives.js
docs/data/scheduler/primitives/DayGridPrimitives.tsx
packages/x-scheduler/src/primitives/time-grid/event/TimeGridEvent.tsx

The Time Grid Event had `data-state={[Object object}] data-props={[Object object}]` because I forgot to decompose the returned object :angel:

[scheduler] Fix data attributes in `<TimeGrid.Event />`

---

packages/x-data-grid/src/components/toolbarV8/GridToolbar.tsx
packages/x-data-grid/src/models/gridBaseSlots.ts

Fixes https://github.com/mui/mui-x/issues/18321. Related to https://github.com/mui/mui-x/pull/18210#discussion_r2135301517.
Fix export menu button tooltip being interactive when menu is open.
The solution was to `disableInteractive` when the tooltip is open. Please read the accessibility concerns [here](https://github.com/mui/mui-x/pull/18327#discussion_r2139518811).
Before:
https://github.com/user-attachments/assets/0b412576-813c-4c70-ac3a-d88f4052c147
After:
https://github.com/user-attachments/assets/55086c62-8a1f-47d7-898e-4a99f63627bb

[data grid] Fix export menu button tooltip being interactive when menu is open

---

docs/pages/x/api/charts/charts-legend.json
docs/translations/api-docs/charts/charts-legend/charts-legend.json
packages/x-charts/src/ChartsLegend/ChartsLegend.tsx
packages/x-charts/src/ChartsLegend/chartsLegendClasses.ts
pnpm-lock.yaml

Add item class to list item around each series in legend. 
This is particularly useful when hiding a list item. Since the parent has the `gap` property set, if we hide the child of the list item, the list item will have a width of zero causing a double gap.

[charts] Add item class to list item around each series in legend

---

CHANGELOG.md
docs/data/date-pickers/overview/overview.md
docs/data/scheduler/event-calendar/event-calendar.md
docs/data/scheduler/overview/overview.md
docs/data/scheduler/primitives/primitives.md

While I was at it, noticed a regression: https://github.com/renovatebot/renovate/discussions/36568.

[core] Fix pnpm valelint error

---

docs/package.json
docs/src/modules/utils/adapter-dependencies.json
docs/src/modules/utils/postProcessImport.test.ts
docs/src/modules/utils/postProcessImport.ts
scripts/buildPickerAdapterDeps.ts

Fixes an issue where, after migration to [pnpm catalogs](https://github.com/mui/mui-x/pull/18302), our [`postProcessImport`](https://github.com/mui/mui-x/blob/master/docs/src/modules/utils/postProcessImport.ts) script resolves adapter dependencies to the `catalog:` version and results in the following failures when code examples are opened. 🙈

[docs][pickers] Fix adapter version resolving when opening demo to edit

---

docs/data/charts/localization/localization.md
docs/data/charts/radar/radar.md
docs/pages/x/api/charts/chart-container.json
docs/pages/x/api/charts/chart-data-provider.json

The radar data provider API page got removed when adding the pro component
The ChartsDataContainer never existed

[docs] Fix 404 in charts docs

---

CHANGELOG.md
package.json
packages/x-charts-pro/package.json
packages/x-charts-vendor/package.json
packages/x-charts/package.json
packages/x-codemod/package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-internal-gestures/package.json
packages/x-internals/package.json
packages/x-license/package.json
packages/x-telemetry/package.json
packages/x-tree-view-pro/package.json
packages/x-tree-view/package.json

[release] v8.5.3

---

docs/data/date-pickers/custom-components/UsePickerAdapter.js
docs/data/date-pickers/custom-components/UsePickerAdapter.tsx
docs/data/date-pickers/custom-components/UsePickerAdapter.tsx.preview
docs/data/date-pickers/custom-components/custom-components.md
packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx
packages/x-date-pickers/src/LocalizationProvider/LocalizationProvider.tsx
packages/x-date-pickers/src/hooks/index.tsx
packages/x-date-pickers/src/hooks/usePickerAdapter.ts
packages/x-date-pickers/src/internals/demo/DemoContainer.tsx
packages/x-date-pickers/src/internals/hooks/useUtils.ts
packages/x-date-pickers/src/validation/useValidation.ts
scripts/x-date-pickers-pro.exports.json
scripts/x-date-pickers.exports.json

Fixes https://github.com/mui/mui-x/issues/18402.
- Add a publicly exported `usePickerAdapter` hook.
- Deprecate `MuiPickersAdapterContext`
- Add demo using `usePickerAdapter`
Leaving the refactor to use `usePickerAdapter` instead of `useUtils` internally for a follow-up.

[pickers] Add `usePickerAdapter` hook

---

scripts/createReleasePR.mjs

this is fixing a bug that snuck in for the release preparation script in #18345

[infra] Use `String.raw` for creating the remote regex

---

babel.config.js
docs/pages/_app.js
packages/x-internal-gestures/src/core/gestures/PanGesture.ts
scripts/printPkgPrNewPublishDirs.mts
tsconfig.json
tsconfig.prod.json
webpackBaseConfig.js

Differentiate `totalDelta` from `activeDelta` and `delta`.
- `delta` is the difference since last event
- `activeDelta` is the difference since pointer down
- `totalDelta` is the total difference across all gestures
This is useful in the charts as the zoom pan calculates the amount of the svg area to pan in percentages, the `totalDelta` is not useful as we need to perform the action relative to the pointer, and the `delta` is too fine-grained, which introduces issues. The `activeDelta` mimics the current behaviour, and is also an useful prop in itself.

[charts] Improve `PanGesture` delta tracking and setup gesture infra

---

docs/data/date-pickers/custom-components/ActionBarComponent.js
docs/data/date-pickers/custom-components/ActionBarComponent.tsx
docs/data/date-pickers/custom-components/custom-components.md
docs/pages/x/api/date-pickers/pickers-action-bar.json
packages/x-date-pickers/src/PickersActionBar/PickersActionBar.tsx

Fixes https://github.com/mui/mui-x/issues/18458.
- Update action bar demo to use the `nextOrAccept` and `next` actions.
- Update text to mention the new actions.
- Update the JSDoc prop to better reflect current behavior.

[docs][pickers] Update action bar demo to use the `nextOrAccept` action

---

packages/x-internals/src/hash/stringify.ts

fix https://github.com/mui/mui-x/issues/17855
Issue - stringifying to json whole window object which in case of MFE can't be really accessed to stringify
Fix - just return simple string to stringify in such case ("[object Window]")

[core] avoid json stringify whole window object

---

packages/x-scheduler/src/joy/styles/tokens.css

Minor adjustment to resolve a dark mode issue caused by CSS specificity.

[scheduler] Fix Scheduler dark mode

---

docs/data/charts/funnel/FunnelCurves.js
docs/data/charts/funnel/FunnelCurves.tsx
packages/x-charts-pro/src/FunnelChart/FunnelPlot.tsx
packages/x-charts-pro/src/FunnelChart/funnel.types.ts
packages/x-charts-pro/src/FunnelChart/seriesConfig/seriesProcessor.ts

Fixes https://github.com/mui/mui-x/issues/18559
- Add `funnelDirection` to control pyramid direction
- Not sure if we should use `increasing/decreasing` or `ascending/descending`
- We could go for `direction` too instead of `dataDirection`
- I didn't document it as it can be done in the pyramid PR, since it works for pyramid only.

[charts-pro] Add `funnelDirection` to control pyramid direction

---

packages/x-data-grid-premium/src/hooks/features/rowGrouping/useGridDataSourceRowGroupingPreProcessors.ts
packages/x-data-grid-pro/src/hooks/features/serverSideTreeData/useGridDataSourceTreeDataPreProcessors.tsx
packages/x-data-grid-pro/src/hooks/features/serverSideTreeData/utils.ts
packages/x-data-grid-pro/src/internals/index.ts

After fix: https://deploy-preview-18715--material-ui-x.netlify.app/x/react-data-grid/server-side-data/row-grouping/
Fixes the root cause of https://github.com/mui/mui-x/issues/18645
Closes https://github.com/mui/mui-x/pull/18647 as it only handles the symptom.
Root cause of the error is a (by the grid's tree builder) perceived duplicate group/tree key on a full tree refresh.
It is only visible if the whole tree is regenerated and some of the subgroups have the same value under different parents.
This is the case in our [demo](https://mui.com/x/react-data-grid/server-side-data/row-grouping/), where the status is being repeated for each parent. Also, this is why the error will not happen if less than 2 subgroups are expanded, because there are no duplicates in that scenario.
Note:
I will …

[DataGridPro] Set correct parent paths when tree is refreshed with data source tree data and row grouping

---

test/performance-charts/tests/BarChart.bench.tsx
test/performance-charts/tests/BarChartPro.bench.tsx
test/performance-charts/tests/LineChart.bench.tsx
test/performance-charts/tests/LineChartPro.bench.tsx
test/performance-charts/tests/ScatterChart.bench.tsx
test/performance-charts/tests/ScatterChartPro.bench.tsx

Related to https://github.com/mui/mui-x/issues/12960.
Increase data points in bar, line and scatter chart benchmarks, so we can better see how performance scales with greater number of data points. 
Also added area chart benchmark to ensure we benchmark that use case as well.

[charts] Increase data points in chart benchmarks

---

packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.test.tsx
packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.tsx

Issue: #18689 
**Problem**
When using checkboxSelection with lazy loading, expanding a node triggered unnecessary `removeItem` event for items that were not actually removed (for all the items). This event is responsible for resetting the focus to the default focus (1) when it matches, resulting in the scroll position jumping to the top and a poor user experience.
**Solution**
The solution was to use **newItems**.itemMetaLookup for the comparison that decides when to trigger the event, this ensures that the diff checks against the merged lookup (which includes both previous and new nodes), so "removeItem" is only triggered for items that are truly removed from the tree, not for those that are still present after lazy loading.
**Demo** …

[tree view] Fix scrolling bug when lazy loading and checkboxSelection are enabled

---

packages/x-charts/src/RadarChart/RadarAxisHighlight/RadarAxisHighlight.tsx
packages/x-charts/src/RadarChart/RadarAxisHighlight/useRadarAxisHighlight.ts

While working on the radar, I noticed
1. A typo (my bad)
2. The radar axis highlight is returning an array of objects with coordinates of the highlighted points, **and** the previous/next points. I remove this option
The previouse/next point was initially computed to enable the following shape: A slice of the radar (the green area).
The design solution got abandoned so this is just dead code

[charts] Simplify radar internal hooks

---

packages/x-charts-vendor/tsconfig.json
pnpm-lock.yaml
test/performance-charts/package.json

Remove dependency on `@testing-library/jest-dom` since we don't use jest. 
Also removed `jest.config.ts` from `x-charts-vendor/tsconfig.json` as that file does not exist.

[code-infra] Remove charts benchmarks dependency on `@testing-library/jest-dom`

---

packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx
packages/x-date-pickers/src/PickersLayout/PickersLayout.tsx

Closes https://github.com/mui/mui-x/issues/18818
Before:
After:

[pickers] Fix digital clock column width CSS

---

packages/x-charts/src/BarChart/seriesConfig/extremums.ts
packages/x-charts/src/LineChart/seriesConfig/extremums.ts
packages/x-charts/src/ScatterChart/seriesConfig/extremums.ts
packages/x-charts/src/internals/findMinMax.test.ts
packages/x-charts/src/internals/findMinMax.ts
packages/x-charts/src/internals/index.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/getAxisExtremum.ts

Part of https://github.com/mui/mui-x/issues/12960.
Fix an issue where scatter charts with 1 million data points would crash with "Maximum call stack size exceeded".

[charts] Fix crash when rendering large scatter dataset

---

docs/pages/x/react-scheduler/full-screen-event-calendar.js
packages/x-scheduler/src/joy/event-calendar/EventCalendar.tsx
packages/x-scheduler/src/joy/event-calendar/EventCalendar.types.ts
packages/x-scheduler/src/joy/event-calendar/store.ts
packages/x-scheduler/src/joy/event-calendar/useEventCalendar.ts
packages/x-scheduler/src/joy/internals/components/event/time-grid-event/TimeGridEvent.css
packages/x-scheduler/src/joy/internals/components/event/time-grid-event/TimeGridEvent.tsx
packages/x-scheduler/src/primitives/time-grid/column/TimeGridColumn.tsx
packages/x-scheduler/src/primitives/time-grid/event-resize-handler/TimeGridEventResizeHandler.tsx
packages/x-scheduler/src/primitives/time-grid/event-resize-handler/index.ts
packages/x-scheduler/src/primitives/time-grid/event/TimeGridEvent.tsx
packages/x-scheduler/src/primitives/time-grid/event/TimeGridEventContext.ts
packages/x-scheduler/src/primitives/time-grid/event/TimeGridEventDataAttributes.ts
packages/x-scheduler/src/primitives/time-grid/index.parts.ts
packages/x-scheduler/src/primitives/utils/drag-utils.ts

Closes #17692
Follow up
- Clean multi days resizing (right now it's broken, but the rendering of multi days event is broken anyway)

[scheduler][primitives] Allow to expand / shrink an event duration using drag & drop in the Time Grid

---

packages/x-scheduler/src/joy/internals/components/resource-legend/ResourceLegend.css
packages/x-scheduler/src/joy/internals/components/resource-legend/ResourceLegend.tsx

Issue #18937 
We need to add a hover effect for the entire item instead of just the icon
Current hover effect:
https://github.com/user-attachments/assets/ae0843bf-8d62-4e1b-979a-2f429e68a3bd
Fixed hover effect:
https://github.com/user-attachments/assets/e3020262-ca25-4e3b-8857-b6f50383143a

[scheduler] Fix resource item hover

---

docs/translations/api-docs/charts/charts-tooltip-container/charts-tooltip-container.json
docs/translations/api-docs/charts/charts-tooltip/charts-tooltip.json
packages/x-charts-pro/src/FunnelChart/FunnelChart.tsx
packages/x-charts-pro/src/FunnelChart/funnelSlots.types.ts
packages/x-charts-pro/src/ScatterChartPro/ScatterChartPro.tsx
packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx
packages/x-charts/src/ChartsTooltip/ChartsTooltipContainer.tsx
packages/x-charts/src/ScatterChart/ScatterChart.tsx

Fixes https://github.com/mui/mui-x/issues/18900.
See videos in https://github.com/mui/mui-x/issues/18900.
https://github.com/user-attachments/assets/a2ef8426-df1c-4209-909e-c4245b98dfc4
https://github.com/user-attachments/assets/dbb520a4-70d0-4e59-a028-502826ea2490

[charts-pro] Fix `slotProps.tooltip.trigger` not respected in `ScatterChartPro` and `FunnelChart`

---

packages/x-charts/src/ChartsAxisHighlight/ChartsXAxisHighlight.tsx
packages/x-charts/src/ChartsAxisHighlight/ChartsYAxisHighlight.tsx

This PR removes unnecessary `@ts-expect-error` checks

[charts] Fix type assertion in axis highlight components

---

scripts/dangerfileContent.ts

Accidentally added in https://github.com/mui/mui-x/pull/18884. These created some duplication in the bundle size output

[bundles] Remove tracking from some modules

---

docs/src/modules/components/demos/data-grid/Inventory/InventoryDashboard.tsx
docs/src/modules/components/demos/data-grid/Inventory/data/products.ts

Reduces total download for all images in the demo from ~5MB to ~90kB.
I have resized the images down to 120x120 - double than the image size from styles - because of retina displays
I have also made master/detail props static, as it is suggested in https://mui.com/x/react-data-grid/master-detail
Preview
https://deploy-preview-19004--material-ui-x.netlify.app/x/react-data-grid/demos/inventory/

[docs] Reduce image size in the inventory grid demo

---

docs/scripts/formattedTSDemos.js

Fixes a bug I introduced in https://github.com/mui/mui-x/pull/19127.
`fs.exists` is valid, but `fs.promises.exists` doesn't exist since `fs.exists` is deprecated.
Reverting to `fs-extra`'s version for now. I'll look into removing it later.

[infra] Fix `fs-extra` removal from `formattedTSDemos` script

---

eslint.config.mjs
packages/x-license/src/utils/licenseInfo.ts
packages/x-telemetry/src/runtime/config.ts
test/utils/addChaiAssertions.ts

Lint rule to disallow usage of typescript namespaces. We've seen at least two problems with them:
* Creates [non-portable types](https://github.com/mui/base-ui/pull/2324) in base ui.
* [This pattern](https://github.com/mui/mui-x/blob/1cf853ed45cf301211ece1c0ca21981ea208edfb/packages/x-virtualizer/src/models/core.ts#L4-L10) leads to broken bundling in [codesandbox](https://codesandbox.io/embed/kgylpd?module=/src/Demo.tsx&fontsize=12).
Gauging the ecosystem it also looks like support for namespaces in tooling is poor and tends to be treated as a deprecated feature. Propose to shy away from it to avoid other future problems.
* Leaving to the authors to refactor other usage
* The usage in chai is allowed, no other way to achieve this on legacy code.
* Will move this rule to code infra …

[code-infra] Remove namespaces

---

.github/ISSUE_TEMPLATE/1.bug.yml
.github/ISSUE_TEMPLATE/2.feature.yml

Context, I have spent some time to dive into the product backlog labeling health:
1. I create filters that allows us to find all the issues without a product scope label: https://www.notion.so/mui-org/product-GitHub-community-issues-PRs-Tier-1-12a84fdf50e44595afc55343dac00fca?source=copy_link#24bcbfe7b66080f19ad0d207c9e5ce1a. Then fixed them to get to zero.
But I gave up on covering material-ui repo, it would have taken a whole day 😀.
2. I fixed all the issues with more than one label type. From which, it seems clear that `expected behavior` and `duplicate` label should be ["type" labels](https://www.notion.so/mui-org/GitHub-issues-Product-backlog-c1d7072e0c2545b0beb43b115f6030f6?source=copy_link#1e3cbfe7b660801e8af6eed5b0d0ce68) because they are mutually exclusive with the other type …

[support-infra] Remove default issue label

---

docs/data/charts/gantt/gantt.md
docs/data/charts/treemap/treemap.md
docs/data/pages.ts

Preview: https://deploy-preview-19140--material-ui-x.netlify.app/x/react-charts/#planned-charts

[charts] Add Future components link in the sidebar 

---

packages/x-data-grid-premium/src/tests/license.DataGridPremium.test.tsx
packages/x-license/src/generateLicense/generateLicense.test.ts
packages/x-license/src/useLicenseVerifier/useLicenseVerifier.test.tsx
packages/x-license/src/verifyLicense/verifyLicense.test.ts
packages/x-license/src/verifyLicense/verifyLicense.ts
test/performance-charts/setup.ts
test/utils/testLicense.js

The initial goal was to finish the renaming of "licensing model" to "license model", where it got missed. At the same time I did:
- Align the license decode method with the source, to prepare for https://github.com/mui/mui-x/issues/19024.

[core] Fix licensing model name

---

packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts
packages/x-virtualizer/src/features/dimensions.ts

Closes #19017 
The effect was running too often because the container wasn't stable. Adding/removing the `ResizeObserver` seems to cause scroll jumps on firefox (and maybe chrome).

[datagrid] Fix scroll jumping

---

docs/data/data-grid/ai-assistant/ai-assistant.md

The key is used directly for billing; if it's public, people can grab a random one and use it on their own server. Until we fix https://github.com/mui/mui-private/issues/1057. I believe we can't, in the docs, tell people to "avoid", it should be "don't. I have been wanting to fix this for a long time, #19142 gave more importance to it.

[ai-assistant] Make it clear that the API key must be private

---

packages/x-data-grid/src/components/containers/GridRootStyles.ts

Fixes https://github.com/mui/mui-x/issues/19238
(try resizing `email` column)
Before: https://stackblitz.com/edit/kqpvdt5d-nvpznub8?file=src%2FDemo.tsx
After: https://stackblitz.com/edit/avd95mh8?file=src%2FDemo.tsx
In the situation where a pinned, non-resizable column is coming after a flex column, the column separators overlap each other. Since the pinned column is not resizable, the interactions on the separator are disabled, which also prevents interactions with the separator of the flex column.
The update hides the separator of the first pinned column (since it already has a border) and allows easier access to the separators of the flex column.

[DataGrid] Hide column separator of non-resizable pinned column

---

.github/workflows/codspeed.yml

~By default, the pull_request type has `opened`, `synchronize`, `reopened` https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#pull_request_target. It seems to be all we need. I was surprised to see this action trigger when a label was applied. It was added in #13952. https://codspeed.io/docs/integrations/ci/github-actions says nothing about it either.~
Add comments to clarify why.

[internal] Add comment for Codspeed triggers

---

.github/workflows/check-if-pr-has-type-label.yml

A few enhancements:
- Restrict the permissions; we only need read access
- Run the action from the PR, not from the target, so we can more easily iterate on this logic. As long as it has no write permissions, we are good.
- Sort keys to match the other actions
Context: I was cleaning up a bit the issue description of https://github.com/mui/mui-public/issues/206, I read this file, and it seemed strange.

[support-infra] Improve GitHub Action that check PRs labels

---

packages/x-date-pickers/src/internals/components/PickerFieldUI.tsx

closes https://github.com/mui/mui-x/issues/19391
Working preview: https://deploy-preview-19399--material-ui-x.netlify.app/x/react-date-pickers/custom-opening-button/#add-an-icon-next-to-the-opening-button
Argos failing is expected

[pickers] Merge slotProps for input adornment in PickerFieldUI component

---

package.json
packages/x-charts-premium/package.json
packages/x-charts-pro/package.json
packages/x-charts/package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-license/package.json
packages/x-scheduler/package.json
packages/x-telemetry/package.json
packages/x-tree-view-pro/package.json
packages/x-tree-view/package.json
pnpm-lock.yaml

Since it is automatically added by the build cli. The equivalent is adding the same path to `exports["."]` which'll then get added as `main`/`module` to the built package.json

[infra] Remove "main" fields from publishable packages

---

packages/x-data-grid/src/components/columnsManagement/GridColumnsManagement.tsx

Fixes #19456 
The PR #19097 added this slot, it seems, styled API requires to pass an empty object even if there are no actual styles.

[DataGrid] Fix styled API arguments error

---

packages/x-data-grid/src/components/columnSelection/GridHeaderCheckbox.tsx

Fixes #19434 
`filteredSelection.ids` contains the ids in the model irrespective of `exclude` or `include` selection type, which causes issues when in `exclude` mode.

[DataGrid] Fix indeterminate select all state with exclude model

---

packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.tsx

[TreeView] Do not mutate `props.items` in the `getItemTree` method

---

docs/next.config.ts

This log doesn't seem to be adding much. The default case is considering various locales and we're already logging when we aren't following the default case. 
On the other hand, it occupies some space in the terminal for no benefit, so I'd like to know your thoughts on removing it.

[code-infra] Remove log when restarting dev server

---

.circleci/config.yml
.github/workflows/ci.yml
netlify.toml
package.json
pnpm-workspace.yaml

Also make the engine requirement strict (node >=22.18) for local dev

[infra] Set nodejs versions of various CIs to 22.18

---

packages/x-date-pickers/src/internals/hooks/useField/useFieldSectionContentProps.ts

Fixes https://github.com/mui/mui-x/issues/19274.
The IDs did not serve any purpose.
- The SO behavior with `NVDA` on `Firefox` remains the same.
- This fixes the SO behavior with VoiceOver on MacOS, as it used to skip/miss the section `aria-label` given the existence of `aria-labelledby`, which pointed "nowhere". 🙈

[fields] Remove redundant `id` and `aria-labelledby` attributes from spinbuttons

---

CHANGELOG.md
package.json
packages/x-charts-pro/package.json
packages/x-charts-vendor/package.json
packages/x-charts/package.json
packages/x-codemod/package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-internal-gestures/package.json
packages/x-internals/package.json
packages/x-license/package.json
packages/x-telemetry/package.json
packages/x-tree-view-pro/package.json
packages/x-tree-view/package.json
packages/x-virtualizer/package.json

[release] v8.11.3

---

docs/data/visual-regression-tests/ZoomSliderPreview.js
docs/data/visual-regression-tests/ZoomSliderPreview.tsx
docs/data/visual-regression-tests/ZoomSliderPreview.tsx.preview
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.test.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/getAxisDomainLimit.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/getAxisScale.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianAxisPreview.selectors.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianAxisRendering.selectors.ts
packages/x-charts/src/internals/scaleGuards.ts

Fixes #17561. 
Alternative to #19332.

[charts] Fix zoom discard inconsistency

---

packages/x-scheduler/src/primitives/use-event-occurrences-with-timeline-position/useEventOccurrencesWithTimelinePosition.ts

The idea is simple, if the occurrences can be splitted in two blocks of occurrences that don't overlap at all, then I can build the conflicts of each group independently. So if one group has a high `longestDurationMs`, the other groups don't pay this higher computation cost.
This doesn't add significant benefits for the Time Grid.
But for the Timeline, it will allow to avoid high computation costs for all the events when only some portion of the timeline contain long events.
Other improvement:  since we are already computing the timestamp of every event, I'm using it to do all the comparison instead of using `isAfter` and `isBefore`.

[scheduler] Improve performances of `buildOccurrenceConflicts`

---

docs/data/visual-regression-tests/PiecewiseRestrictedAxis.js
docs/data/visual-regression-tests/PiecewiseRestrictedAxis.tsx
packages/x-charts/src/ScatterChart/Scatter.tsx

Fixes #19594.
The issue was that `i` from `scatterPlotData` doesn't match the original `dataIndex`, which caused the markers to get the color from another data point. To fix it, we need to use `dataPoint.dataIndex`. This issue only happened in the individual scatter; the batch scatter is unaffected.
Added visual regression test. 
Before:
After:

[charts] Fix piecewise scale causing wrong colors in axis with min/max

---

test/performance-charts/tests/ScatterChartPro.bench.tsx

CodSpeed doesn't read the titles from `describe` blocks, so it was hard to see if the affected benchmarks were referring to the single or batch renderer.

[charts] Add renderer suffix to performance benchmarks

---

packages/x-date-pickers-pro/src/DesktopTimeRangePicker/DesktopTimeRangePicker.tsx
packages/x-date-pickers-pro/src/MobileTimeRangePicker/MobileTimeRangePicker.tsx
packages/x-date-pickers-pro/src/TimeRangePicker/shared.tsx

Same issue (https://github.com/mui/mui-x/issues/19405) which was happening in DateTimePicker and DateTimeRangePicker, is happening in TimeRangePicker as well.  
Preview: https://deploy-preview-19626--material-ui-x.netlify.app/x/react-date-pickers/time-range-picker/#basic-usage
I have checked `TimePicker`, I can't see issue there

[pickers] Preserve time format when using single column layout on TimeRangePicker

---

packages/x-charts-pro/src/FunnelChart/funnelAxisPlugin/computeAxisValue.ts
packages/x-charts/src/internals/index.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/getAxisExtrema.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/getAxisScale.ts

Refactor `getAxisExtremum`. Applied several small changes:
- Rename to `getAxisExtrema`
- Move the logic for deciding the min/max to `getAxisExtrema` instead of `axisExtremumCallback`
- Change it to a named function so that it shows up in performance traces

[charts] Refactor `getAxisExtremum`

---

packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts

Fixes #18640 
Thanks to @flaviendelangle for the solution.
I tested this manually as well and it seems to fix the problem

[pickers] Ensure reference value is not updated for invalid values

---

scripts/changelogUtils.mjs
scripts/createReleasePR.mjs

fixes a problem with the changelog generation script

[infra] Update `findLatestTaggedVersion` to filter tags based on major version

---

packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/getAxisScale.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianAxisPreview.selectors.ts
packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/useChartCartesianAxisRendering.selectors.ts

`getAxisScale` was never being called with `getFilters`, and `zoomOption` was unnecessary.
Also moved `getAxisExtrema` below the checks for ordinal scales because it isn't necessary before and it should save some unnecessary computation.

[charts] Remove unused code path from `getAxisScale`

---

docs/pages/x/api/charts/charts-wrapper.json
packages/x-charts/src/ChartsWrapper/ChartsWrapper.tsx

I am using composition for some of our more complicated charts and #19257 introduced a new required prop on `ChartWrapper ` which broke our build. I have made this optional with a false default, which seems reasonable to me?

[charts] Make new hideLegend prop on ChartWrapper optional

---

packages/x-data-grid-premium/src/hooks/features/rowGrouping/createGroupingColDef.tsx

Team decision after https://github.com/mui/mui-x/issues/19018 has been reported.
The actual problem is fixed in https://github.com/mui/mui-x/pull/19690
Preview: https://deploy-preview-19692--material-ui-x.netlify.app/x/react-data-grid/row-grouping/

[DataGridPremium] Disable aggregation on the grouping column by default

---

packages/x-date-pickers/src/DateField/tests/DateField.test.tsx
packages/x-date-pickers/src/DesktopDatePicker/tests/DesktopDatePicker.test.tsx
packages/x-date-pickers/src/internals/components/PickerFieldUI.tsx

Fix: https://github.com/mui/mui-x/issues/14684#issuecomment-3325498780
Confirmed locally that it fixes the issue showcased in the example.
After the change, `slotProps.textField.slotProps.htmlInput` was not being resolved, causing a slight regression in some usage configurations.

[pickers] Fix `slotProps.textField.slotProps.htmlInput` resolution

---

packages/x-scheduler/src/primitives/utils/SchedulerStore/SchedulerStore.ts

Naming convention proposal:
- Use **`original`** when updating an entity (the source of truth before applying changes).
- Use **`previous`** when comparing state values (UI flags, placeholders, etc.).
- Use **`existing`** when validating duplicates during creation.
This way the naming stays consistent and makes the intent clear in each context.

[scheduler] Refactor - use `original` when checking the source of truth before applying changes 

---

packages/x-data-grid-premium/src/hooks/features/chartsIntegration/useGridChartsIntegration.tsx

Reproduction steps
1 .Go to https://mui.com/x/react-data-grid/charts-integration/#row-grouping
2. Click on "Reset demo" button
On re-render, active chart id is not in the state in the cycle where the targeted row depth is being calculated, making the hook skip collecting the data for one level of the rows.
Preview https://deploy-preview-19720--material-ui-x.netlify.app/x/react-data-grid/charts-integration/#row-grouping

[DataGridPremium] Get correct active chart id while rebuilding data

---

packages/x-charts/src/ChartsSurface/ChartsSurface.tsx

On bar chart, the outline was taking the color of the bar.
Here we fix the color to:
- black in light mode
- white in dark mode

[charts] Fix outline color

---

.github/workflows/publish.yml
docs/package.json
package.json
pnpm-lock.yaml
scripts/README.md

* Allow publishing to different dist tag than "latest"
* Tweak docs deploy to fetch latest master first, like https://github.com/mui/material-ui/pull/47018/

[code-infra] Support custom npm dist tags during release
