mui/mui-x

CHANGELOG.md, docs/package.json, package.json, packages/grid/x-data-grid-generator/package.json, packages/grid/x-data-grid-premium/package.json, packages/grid/x-data-grid-pro/package.json, packages/grid/x-data-grid/package.json, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json, packages/x-license-pro/package.json
=> v6.0.0-alpha.8

docs/data/date-pickers/getting-started/InstructionsNoSnap.js
* Enforce a value for package manager and license type options
* It makes sense that at least one of the options is selected at all times
* This will avoid the bug where 'null' ends up getting displayed
Before: 
After:
=> [docs] Enforce values for installation options in Date / Time pickers Getting Started page

packages/x-date-pickers/src/DateCalendar/PickersCalendarHeader.tsx
Fixed picker selection circle
With removing `maxHeight`:
=> [pickers] Fix calendar header switch view button hover circle

docs/data/date-pickers/custom-components/ArrowSwitcherComponent.js, docs/data/date-pickers/custom-components/ArrowSwitcherComponent.tsx, docs/data/date-pickers/custom-components/ArrowSwitcherComponentProps.js, docs/data/date-pickers/custom-components/ArrowSwitcherComponentProps.tsx
Related #6896 
* Clicking on the toggle button twice makes the content disappear
* This PR fixes that in two demos in the page
* This PR makes sure to make relevant changes for both the `.js` and `.tsx` files
The demos in question: https://next.mui.com/x/react-date-pickers/custom-components/#component-3
=> [docs] Fix toggle button bug in demos in Custom Components page

packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.types.ts, packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerViewMobile.tsx, packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx, packages/x-date-pickers/src/DateCalendar/PickersCalendarHeader.tsx
=> [pickers] Clean `PickersCalendarHeader` slots

packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts, packages/grid/x-data-grid-pro/src/tests/detailPanel.DataGridPro.test.tsx
Closes #5613 
- `Ctrl/Cmd + Enter` will no longer toggle the master detail panel
=> [DataGrid] Prevents master detail panel toggle with Ctrl+Enter

docs/pages/x/api/data-grid/data-grid-premium.json, docs/pages/x/api/data-grid/data-grid-pro.json, docs/pages/x/api/data-grid/data-grid.json, packages/grid/x-data-grid/src/components/GridErrorOverlay.tsx, packages/grid/x-data-grid/src/components/containers/GridOverlay.tsx, packages/grid/x-data-grid/src/constants/defaultGridSlotsComponents.ts, packages/grid/x-data-grid/src/models/gridSlotsComponent.ts
=> [DataGrid] Rename `ErrorOverlay` to `GridErrorOverlay`

.browserslistrc, docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md, packages/grid/x-data-grid-generator/package.json, packages/grid/x-data-grid-premium/package.json, packages/grid/x-data-grid-pro/package.json, packages/grid/x-data-grid/package.json, packages/x-codemod/package.json, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json, packages/x-license-pro/package.json
Closes https://github.com/mui/mui-x/issues/5605
We've upgraded Node.js version used in CircleCI, Netlify and Codesandbox CI earlier in https://github.com/mui/mui-x/pull/4999
=> [core] Update minimum supported version of Node.js to 14.0.0

packages/grid/x-data-grid-pro/src/tests/lazyLoader.DataGridPro.test.tsx, packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts
Fixes https://github.com/mui/mui-x/issues/6857
TODO:
Before: https://codesandbox.io/s/funny-lovelace-4igujv?file=/demo.tsx
https://user-images.githubusercontent.com/13808724/202181987-8aaf7362-03e4-434b-8120-a46f52118d07.mov
After: https://codesandbox.io/s/fragrant-rgb-yivj2n?file=/demo.tsx
https://user-images.githubusercontent.com/13808724/202182581-b0f041e6-c217-4db7-88c3-423dbe59acea.mov
=> [DataGridPro] Fix lazy-loaded rows not working with `updateRows` API method

docs/package.json, yarn.lock
Revert #6681. Same bug as in https://github.com/mui/material-ui/pull/35118#issuecomment-1324911398.
HEAD, broken: https://next--material-ui-x.netlify.app/x/react-data-grid/#mit-version
PR, works: https://deploy-preview-6975--material-ui-x.netlify.app/x/react-data-grid/#mit-version
I have no idea what's wrong but it would be great to see if the problem is on our side or Next.js's side
Same bug on the master branch: https://mui.com/x/react-data-grid/.
=> [docs] Fix live edit

docs/data/date-pickers/time-picker/time-picker.md, docs/public/_redirects
ahrefs notified a 404 links in https://next.mui.com/x/react-date-pickers/time-picker/ in the API section
=> [docs] Update API links from clock-picker to time-clock

docs/data/date-pickers/localization/localization.md, packages/x-date-pickers/src/locales/index.ts, packages/x-date-pickers/src/locales/ukUA.ts, packages/x-date-pickers/src/locales/urPK.ts, scripts/x-date-pickers-pro.exports.json, scripts/x-date-pickers.exports.json
Counterpart of #6866 for pickers
=> [pickers] Add Urdu (ur-PK) locale

packages/grid/x-data-grid-premium/src/hooks/features/export/serializer/excelSerializer.ts
Fix #7008
The codesandbox with the fix https://codesandbox.io/s/snowy-bash-etv2u5?file=/demo.tsx
=> [DataGridPremium] Fix empty column group in Excel export

docs/data/migration/migration-pickers-v5/migration-pickers-v5.md
Add missing breaking changes from #6543 and #6445.
[Docs preview](https://deploy-preview-7000--material-ui-x.netlify.app/x/migration/migration-pickers-v5/#replace-toolbar-props-by-slot)
P.S. I've already updated the GH pre-release with missing info (about tabs)
=> [docs] Add missing pickers migration docs

docs/pages/x/api/date-pickers/index.md, docs/scripts/reportBrokenLinks.js
The api pages have anchor autogenerated, so we only check if the url exist (don't care about the hash)
=> [docs] test links with API page ignoring url hash

.github/ISSUE_TEMPLATE/6.docs-feedback.yml, docs/next.config.js
Follow up of https://github.com/mui/material-ui/pull/34641
Configure docs and create the template for the link "open an issue" in the new documentation feedbacks
=> [docs] Setup GitHub issue template for feedbacks about docs

package.json
A different take on #5564, this time only copy & pasting what's done in the main repo.
`global.gc` is still available and I removed options of the CLI that override
https://github.com/mui/mui-x/blob/4e5023840793242198772743bc7d968a507db1d6/.mocharc.js#L2-L24
https://github.com/mui/mui-x/pull/5458#issuecomment-1180517434 @mnajdova does it work now on Windows?
=> [test] Sync test:unit with monorepo

packages/grid/x-data-grid/src/components/GridRow.tsx, packages/grid/x-data-grid/src/components/cell/GridCell.tsx, packages/grid/x-data-grid/src/tests/cells.DataGrid.test.tsx
Closes #5612
- Passing children as `null` to `<GridCell />` will not render `valueToRender` anymore
=> [DataGrid] Removes <GridCell /> fallback to `valueToRender` on `null` children

docs/src/modules/components/ApiPage.js, yarn.lock
Apply https://github.com/mui/material-ui/pull/35201 in MUI X.
Before: https://next.mui.com/x/api/data-grid/data-grid/
After: https://deploy-preview-7051--material-ui-x.netlify.app/x/api/data-grid/data-grid/
---
We should be able to remove this duplication of the `ApiPage` component as we move forward. It feels like we introduced debt when we decided to fork the file. The current diff now between the mono repo and MUI X seems to be about:
- Slots, Material UI should have https://mui.com/x/api/data-grid/data-grid/#slots too but doesn't yet
- A different way to display the import path. So this should be outside of the file.
- MUI X has a better way to show the global class name
https://github.com/mui/material-ui/pull/35202 will also need to be applied twice.
=> [docs] Fix API page ad space regression

docs/src/modules/components/ApiPage.js
I apply https://github.com/mui/material-ui/pull/35202
---
Same comment as with #7051 ("We should be able to remove this duplication of the ApiPage component as we move forward."). The git diff between `ApiPage.js` in the two repositories looks like this:
```diff
diff --git a/docs/src/modules/components/ApiPage.js b/docs/src/modules/components/ApiPage.js
index 112aab9478..77d2978167 100644
--- a/docs/src/modules/components/ApiPage.js
+++ b/docs/src/modules/components/ApiPage.js
@@ -171,6 +175,7 @@ function getTranslatedHeader(t, header) {
import: t('api-docs.import'),
'component-name': t('api-docs.componentName'),
props: t('api-docs.props'),
+    slots: t('api-docs.slots'),
inheritance: t('api-docs.inheritance'),
css: 'CSS',
};
@@ -222,7 +227,9 @@ export default function ApiPage(props) { …
```
=> [core] Sync ApiPage.js with monorepo

docs/data/date-pickers/localization/localization.md
Part of #7096 
Update documentation to use a locale, which exists among all the products (data grid, material ui, pickers).
I've chosen `deDE` as we have already used it in other demos.
Feel free to suggest a better alternative. 🙈 
[Preview](https://deploy-preview-7102--material-ui-x.netlify.app/x/react-date-pickers/localization/)
=> [docs] Update localization doc to use existing locale

packages/x-date-pickers/src/MonthCalendar/MonthCalendar.tsx, packages/x-date-pickers/src/MonthCalendar/tests/MonthCalendar.test.tsx, packages/x-date-pickers/src/YearCalendar/YearCalendar.tsx, packages/x-date-pickers/src/YearCalendar/tests/YearCalendar.test.tsx
Fixes #7114 
Instead of current approach, when `now` is used and has a side-effect of initialising date with current time, change to:
- Fix to init date to `startOfYear` when selecting a year
- Fix to init date to `startOfMonth` when selecting a month
=> [pickers] Initialize date without time when selecting year or month

CHANGELOG.md, docs/package.json, package.json, packages/grid/x-data-grid-generator/package.json, packages/grid/x-data-grid-premium/package.json, packages/grid/x-data-grid-pro/package.json, packages/grid/x-data-grid/package.json, packages/x-codemod/package.json, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json, packages/x-license-pro/package.json
=> v6.0.0-alpha.11

packages/x-date-pickers/src/DateTimePicker/DateTimePicker.tsx
DateTimePickers export pattern doesn't match that of all the other x-date-picker components. 
This change fixes an issue with [react-docgen-typescript](https://www.npmjs.com/package/react-docgen-typescript) being able to locate the component. I am already in the process of looking for a fix in react-docgen-typescript but its not as simple. This change over here seems small enough and has no impact and would improve consistency, so maybe we could get this in in the meantime?
Examples of other component exports:
[ClockPicker](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/ClockPicker/ClockPicker.tsx#L206)
[CalendarPicker](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/CalendarPicker/CalendarPicker.tsx#L216) …
=> [DateTimePicker] Update export pattern

packages/grid/x-data-grid/src/components/cell/GridSkeletonCell.tsx
Fixes small visual bug introduced in https://github.com/mui/mui-x/pull/4197
Before: 
After:
=> [DataGridPro] Fix wrong border color on skeleton cells

packages/grid/x-data-grid/src/components/columnHeaders/GridColumnGroupHeader.tsx, packages/grid/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx, packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts
Fixes #1623
Removed column separator, it will only be shown when there's resize support available.
- [Figma Process](https://www.figma.com/file/W6TItYkiGJZjL5zLnfeSjy/Data-grid?node-id=1227%3A62449&t=MAO4kO2qvUssZFTG-0) 
- Figma Final
=> [DataGrid] Remove column separator to match table styles

docs/data/date-pickers/localization/data.json, packages/x-date-pickers/src/locales/koKR.ts
Resolves part of #3211 
Translated Korean locale text for `Date and Time Pickers`
=> [pickers] Improve Korean (ko-KR) locale

docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md, packages/grid/x-data-grid/src/DataGrid/useDataGridProps.ts, packages/grid/x-data-grid/src/components/toolbar/GridToolbarDensitySelector.tsx, packages/grid/x-data-grid/src/hooks/features/density/useGridDensity.tsx, packages/grid/x-data-grid/src/models/api/gridDensityApi.ts, packages/grid/x-data-grid/src/models/gridDensity.ts, scripts/x-data-grid-premium.exports.json, scripts/x-data-grid-pro.exports.json, scripts/x-data-grid.exports.json
Context: https://github.com/mui/mui-x/pull/7199#discussion_r1048802214
- The `GridDensityTypes` enum was removed. Use `GridDensity` type instead.
=> [DataGrid] Remove `GridDensityType` enum

docs/public/_redirects
Fixes https://github.com/mui/material-ui/pull/34820#issuecomment-1334198189
Example:
https://deploy-preview-7341--material-ui-x.netlify.app/pt/x/api/data-grid/data-grid/
redirects to:
https://deploy-preview-7341--material-ui-x.netlify.app/x/api/data-grid/data-grid/
TODO:
=> [docs] Redirect translated pages

scripts/copyFiles.mjs
To change https://unpkg.com/@mui/x-date-pickers-pro@5.0.12/node/index.js. It matches with https://unpkg.com/browse/react-dom@18.2.0/cjs/react-dom-server.node.production.min.js.
And no, it's not MIT.
Related to https://github.com/mui/material-ui/pull/35703
=> [core] Fix the product license reference name

packages/x-date-pickers-pro/src/themeAugmentation/components.d.ts, packages/x-date-pickers/src/themeAugmentation/components.d.ts
`variants` are not supported by any component in `mui-x` repository.
Most of mui-core components do have variants and so they have additional typing and logic to support additional variants extension.
In pickers case we did not even support it anywhere.
This is technically a breaking change, but it would not impact anyone as those fields served no purpose. It was just a mistake on our side.
If you think that we should include it in the migration docs—we could do it, but I see little to no purpose in it... 🙈
=> [pickers] Remove redundant `variants` in theme augmentation

packages/x-date-pickers-pro/src/SingleInputDateRangeField/useSingleInputDateRangeField.ts, packages/x-date-pickers-pro/src/SingleInputDateTimeRangeField/useSingleInputDateTimeRangeField.ts, packages/x-date-pickers-pro/src/SingleInputTimeRangeField/useSingleInputTimeRangeField.ts, packages/x-date-pickers/src/DateField/useDateField.ts, packages/x-date-pickers/src/DateTimeField/useDateTimeField.ts, packages/x-date-pickers/src/TimeField/useTimeField.ts, packages/x-date-pickers/src/internals/hooks/useField/useField.ts, packages/x-date-pickers/src/internals/hooks/useField/useField.types.ts, packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts, packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts
[Behavior before](https://codesandbox.io/s/date-and-time-pickers-forked-fepeji)
[Behavior after](https://codesandbox.io/s/date-and-time-pickers-forked-onxvj9)
Press `ArrowUp`, the old one should go to the 8th of April, not the new one.
Maybe some people want the old behavior and if so we could introduce a prop to support it.
But the new behavior feels more coherent to me, especially with time range pickers were the behavior is very weird when we have `12:00 - 15:00` rendered but the field is in error because the `15:00` is actually in the day before.
=> [field] Prevent date change on `TimeField` arrow edition

CHANGELOG.md, docs/package.json, package.json, packages/grid/x-data-grid-generator/package.json, packages/grid/x-data-grid-premium/package.json, packages/grid/x-data-grid-pro/package.json, packages/grid/x-data-grid/package.json, packages/x-codemod/package.json, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json, packages/x-license-pro/package.json, scripts/README.md, scripts/releaseChangelog.mjs
=> v6.0.0-alpha.14

docs/data/data-grid/export/export.md, packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx, test/regressions/TestViewer.js, test/regressions/index.test.js, test/utils/createDOM.js
Backport of https://github.com/mui/mui-x/pull/6273 to the `master` branch.
The scroll jump is annoying and the print preview doesn't work on localhost, which makes it harder to look into print export issues reported lately (https://github.com/mui/mui-x/issues/7400)
=> [DataGrid] Improve print support

docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md, docs/pages/x/api/data-grid/data-grid-premium.json, docs/pages/x/api/data-grid/data-grid-pro.json, docs/pages/x/api/data-grid/data-grid.json, docs/translations/api-docs/data-grid/data-grid-premium-pt.json, docs/translations/api-docs/data-grid/data-grid-premium-zh.json, docs/translations/api-docs/data-grid/data-grid-premium.json, docs/translations/api-docs/data-grid/data-grid-pro-pt.json, docs/translations/api-docs/data-grid/data-grid-pro-zh.json, docs/translations/api-docs/data-grid/data-grid-pro.json, docs/translations/api-docs/data-grid/data-grid-pt.json, docs/translations/api-docs/data-grid/data-grid-zh.json, docs/translations/api-docs/data-grid/data-grid.json, packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx, packages/grid/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx, packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx, packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts, packages/grid/x-data-grid/src/hooks/features/columns/useGridColumns.tsx, packages/grid/x-data-grid/src/models/props/DataGridProps.ts, packages/grid/x-data-grid/src/tests/filtering.DataGrid.test.tsx, packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx
Closes https://github.com/mui/mui-x/issues/242
- The `columnTypes` prop was removed. For custom column types see [Custom column types](/x/react-data-grid/column-definition/#custom-column-types) docs.
=> [DataGrid] Remove the `columnTypes` prop

docs/data/introduction/licensing/licensing.md, docs/pages/_app.js, packages/grid/x-data-grid-premium/src/tests/license.DataGridPremium.test.tsx, packages/x-license-pro/src/useLicenseVerifier/useLicenseVerifier.test.tsx, test/regressions/index.js
Per https://github.com/mui/mui-x/issues/3969#issuecomment-1373914604.
We still need each package to export LicenseInfo as when we do a breaking change with the license package, we will need developers to be able to upgrade their component incrementally.
=> [core] Update package used to import LicenseInfo

docs/data/date-pickers/validation/validation.md
```diff
-shouldDisableTime={(timeValue, view) => currentView === 'hours' && timeValue > 12 && timeValue < 15}
+shouldDisableTime={(timeValue, view) => view === 'hours' && timeValue > 12 && timeValue < 15}
```
I also fix the scrollbar in:
for 13" screens
https://next.mui.com/x/react-date-pickers/validation/#disable-specific-times
=> [docs] Fix wrong reference to currentView

packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx, packages/x-date-pickers/src/internals/hooks/useField/useField.ts
Part of #7440
In Android, we have 2 `onChange`, for the 1st one we need to just store the result as is in the input.
Since the RTL PR, we were storing the clean value (without the RTL characters), which was causing shift in the edited layout on the 2nd `onChange`.
=> [fields] Fix Android editing

packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/describes.SingleInputDateRangeField.test.tsx, packages/x-date-pickers/src/DateField/tests/describes.DateField.test.tsx, packages/x-date-pickers/src/PickersDay/PickersDay.test.tsx
Extract the finer grain test of inheritComponent from #7294.
An example of failure message when the `inheritComponent` value is wrong:
=> [test] Add a few inheritComponent

packages/x-date-pickers/src/TimeClock/TimeClock.tsx, packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx
While working on #7339, I noticed that a time picker with just the `minutes` and `seconds` view was renderting `MM:SS AM` in the toolbar, which is confusing.
=> [pickers] Hide am/pm controls when their is no hour view

packages/grid/x-data-grid/src/hooks/features/clipboard/useGridClipboard.ts
Per https://github.com/mui/material-ui/pull/35670/files#r1059417694, this might be better
=> [core] Handle selection edge case

docs/data/data-grid/accessibility/accessibility.md, packages/grid/x-data-grid-pro/src/tests/clipboard.DataGridPro.test.tsx, packages/grid/x-data-grid/src/hooks/features/clipboard/useGridClipboard.ts, packages/grid/x-data-grid/src/models/api/gridClipboardApi.ts
Relates to #3287 
Closes #5618 
- <kbd>Alt</kbd>(or <kbd>⌥ Option</kbd>) + <kbd>C</kbd> keyboard shortcut is no longer supported
=> [DataGrid] Remove Alt+C keyboard shortcut

packages/x-date-pickers-pro/src/MobileNextDateRangePicker/MobileNextDateRangePicker.tsx
Fixes an inconsistency between the doc and the actual behavior
https://github.com/mui/mui-x/blob/e472a0e6848d68a115e278408e973acddbfdc4de/docs/data/date-pickers/date-range-picker/date-range-picker.md?plain=1#L79
=> [DateRangeCalendar] Ignore `calendars` prop on mobile

packages/x-date-pickers/src/CalendarPicker/DayPicker.tsx
=> [pickers] Ensure `key` is passed without object spreading

packages/x-date-pickers-pro/src/internal/hooks/useStaticRangePicker/useStaticRangePicker.tsx
Fix to propagate `rangePosition` to view—same as we do for desktop and mobile picker versions.
It fixes the issue of view not being aware of the currently selecting range position and thus:
- not changing selected toolbar range position after start or end date is selected
- always showing preview highlighting range styling for start position
=> [DateRangePicker] Propagate `rangePosition` to view

scripts/README.md
Add optional release documentation step detailing codemod package tag change.
Created [from discussion](https://mui-org.slack.com/archives/G011VC970AW/p1672962585159909?thread_ts=1672930784.808279&cid=G011VC970AW).
=> [core] Add release documentation step detailing `x-codemod` package tag change

packages/x-date-pickers/src/DateCalendar/tests/keyboard.DateCalendar.test.tsx, packages/x-date-pickers/src/internals/hooks/usePicker/usePickerViews.ts, packages/x-date-pickers/src/internals/hooks/useViews.tsx
Fix #7177
I did not find any effect taking care of setting the focus on open.
Why did it work the first time you open the popper and not after?
Because in `useDesktopPicker` we can see that `usePicker` is called with `autoFocusView: true` but `autoFocus` is only here for the first render (it set the default focused vie to `'day'` instead of `'null'`)
=> [pickers] Update focus when opening a UI view

packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx
Fixes https://github.com/mui/mui-x/issues/7630
Starting from Chromium 109, [the `afterprint` event is not being emitted](https://stackoverflow.com/questions/75129430/window-onafterprint-not-working-if-window-print-is-called-via-js#comment132603442_75129430).
So I used [`matchMedia`](https://caniuse.com/matchmedia) and [`MediaQueryList`](https://caniuse.com/?search=MediaQueryList) instead.
Before: https://codesandbox.io/s/hopeful-dijkstra-1ciqso (only reproducible with Chromium 109)
After: https://codesandbox.io/s/clever-lamarr-vb5tbr
TODO:
=> [DataGrid] Fix grid state not being updated after print preview is closed

CHANGELOG.md, docs/data/migration/migration-pickers-v5/migration-pickers-v5.md, docs/scripts/addDemoItemsAttributes.js, packages/x-codemod/README.md, packages/x-codemod/src/v6.0.0/pickers/preset-safe/actual.spec.js, packages/x-codemod/src/v6.0.0/pickers/preset-safe/expected.spec.js, packages/x-codemod/src/v6.0.0/pickers/preset-safe/index.ts, packages/x-codemod/src/v6.0.0/pickers/rename-components-to-slots/index.ts, packages/x-codemod/src/v6.0.0/pickers/rename-should-disable-time/actual-props.spec.js, packages/x-codemod/src/v6.0.0/pickers/rename-should-disable-time/expected-props.spec.js, packages/x-codemod/src/v6.0.0/pickers/rename-should-disable-time/index.ts, packages/x-codemod/src/v6.0.0/pickers/rename-should-disable-time/rename-should-disable-time.test.ts, packages/x-codemod/src/v6.0.0/pickers/replace-arrows-button-slot/index.ts
=> [codemod] Rename `shouldDisableTime` prop

packages/grid/x-data-grid/src/components/GridAutoSizer.tsx, packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx
Fixes the regression introduced in https://github.com/mui/mui-x/pull/7001 (see "Before" preview below)
Before: https://deploy-preview-7001--material-ui-x.netlify.app/x/react-data-grid/events/#catalog-of-events
After: https://deploy-preview-7701--material-ui-x.netlify.app/x/react-data-grid/events/#catalog-of-events
=> [DataGrid] Fix `autoHeight` not working properly inside of a flex container

docs/data/date-pickers/custom-components/custom-components.md
Fix #7683
information about the customizable components is added
=> [docs] Add info callout about available component `slots`

packages/x-date-pickers/src/themeAugmentation/components.d.ts, packages/x-date-pickers/src/themeAugmentation/themeAugmentation.spec.ts
=> [TimePicker] Add missing `themeAugmentation` entry

docs/next.config.js
The fix replicates the docs https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix
=> [core] Fix Next.js warning

yarn.lock
Fix [Dependabot](https://github.com/mui/mui-x/security/dependabot/71)
=> [core] Bump `loader-utils`

docs/data/migration/migration-pickers-v5/migration-pickers-v5.md, packages/x-codemod/src/codemod.ts, packages/x-codemod/src/util/addComponentsSlots.js, packages/x-codemod/src/v6.0.0/pickers/rename-components-to-slots/actual-props.spec.js, packages/x-codemod/src/v6.0.0/pickers/rename-components-to-slots/expected-props.spec.js
- Add "Rename `components` to `slots`" section
- Fix typos
- Fix `codemod` script examples message to contain a valid example
=> [docs] Polish pickers migration docs

docs/data/date-pickers/localization/data.json, packages/x-date-pickers/src/locales/itIT.ts
- Fixed grammatical error (`un ora` -> `un'ora`)
- Added missing translations
=> [l10n] Improve Italian (it-IT) locale

packages/grid/x-data-grid-pro/src/hooks/features/rowPinning/useGridRowPinningPreProcessors.ts
Fixes https://github.com/mui/mui-x/issues/7580
The issue is not reproducible on the `next` branch.
Before: https://codesandbox.io/s/affectionate-leakey-vpmrzi?file=/demo.js
After: https://codesandbox.io/s/gallant-rhodes-wqzu6n?file=/demo.js
=> [DataGrid] Fix an error when deleting pinned row using actions column button

packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json, yarn.lock
Since we remove the mask utils, we do not need to keep RIFM - React Input Format & Mask in the dependencies
=> [core] Remove `rifm` dependency

packages/x-date-pickers/src/internals/components/PickerViewRoot/PickerViewRoot.tsx
Preview: https://deploy-preview-7766--material-ui-x.netlify.app/x/react-date-pickers/date-picker/#available-components
Jittery behaviour of calendar component fixed #7756
=> [pickers] Hide scrollbars in the date calendar container

docs/data/data-grid/getting-started/getting-started.md, docs/data/date-pickers/getting-started/getting-started.md, docs/src/modules/components/DataGridInstallationInstructions.js, docs/src/modules/components/InstallationInstructions.tsx, docs/src/modules/components/PickersInstallationInstructions.js, docs/tsconfig.json
- Use the `@next` tag in installation instructions (for both data grid and pickers) so that the latest prerelease version is installed (currently beta.2)
- Make data grid installation instructions interactive (pickers docs already had this):
Preview: https://deploy-preview-7814--material-ui-x.netlify.app/x/react-data-grid/getting-started/#installation
=> [docs] Use `@next` tag in grid and pickers installation instructions

docs/data/date-pickers/date-range-picker/date-range-picker.md
The issue is already solved and solution is delivered and [documented](https://next.mui.com/x/react-date-pickers/date-range-picker/#add-shortcuts).
=> [docs] Remove no longer relevant range shortcuts section

docs/data/date-pickers/date-picker/date-picker.md, docs/data/date-pickers/date-range-picker/date-range-picker.md, docs/data/date-pickers/date-time-picker/date-time-picker.md, docs/data/date-pickers/time-picker/time-picker.md
I used the same wordings as @joserodolfofreitas in #7820 
If you have other information to add that might interest people.
I think those 4 pages are the most crucial if we want people to know that the beta exists and that it is exciting.
=> [docs] Add messages in v5 doc to inform people about v6

docs/data/whats-new.md
Followup on #7820.
Users landing from Material-UI might lose context and may need support to reorient.
Add "MUI X" to the page title to make it clearer (on the spot) that it is an X page.
=> [docs] Add product name to "What's New" page title.

packages/grid/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx, packages/grid/x-data-grid/src/utils/domUtils.ts
Cherry-pick of https://github.com/mui/mui-x/pull/7354
=> [DataGrid] Fix getCellElement method not working with pinned columns

packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx, packages/x-date-pickers/src/internals/hooks/useField/useField.ts, packages/x-date-pickers/src/internals/hooks/useField/useFieldCharacterEditing.ts
Part of https://github.com/mui/mui-x/pull/7834#pullrequestreview-1285351956
Needs to also by applied on #7842
=> [fields] Reset query when pressing `Backspace` or `Delete`

docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md, packages/x-codemod/README.md, packages/x-codemod/src/util/renameIdentifiers.ts, packages/x-codemod/src/v6.0.0/data-grid/rename-selectors-and-events/actual.spec.js, packages/x-codemod/src/v6.0.0/data-grid/rename-selectors-and-events/expected.spec.js, packages/x-codemod/src/v6.0.0/data-grid/rename-selectors-and-events/index.ts
Related to #7086 
- Add pre-reqs and more cases to the `rename-selectors-and-events` codemod
- Reorganize list of selector BCs to have handled with codemod on top
=> [codemod] Add more cases to `rename-selectors-and-events` codemod

packages/x-date-pickers/src/internals/hooks/useMaskedInput.tsx
=> [pickers] Update pickers when new value has a distinct timezone

packages/x-date-pickers-pro/tsconfig.json, packages/x-date-pickers/tsconfig.json, patches/@date-io+date-fns+2.16.0.patch, patches/@date-io+date-fns-jalali+2.16.0.patch, patches/@date-io+dayjs+2.16.0.patch, patches/@date-io+hijri+2.16.1.patch, patches/@date-io+luxon+2.16.1.patch, patches/@date-io+moment+2.16.1.patch, patches/date-fns-jalali+2.13.0-0.patch
Related to https://github.com/dmtrKovalenko/date-io/issues/52
If we were able to remove `skipLibCheck: "true"`, we would avoid most issues like https://github.com/mui/mui-x/issues/7779
Currently, our authored `.d.ts` files are ignored by `tsc` and thus, any issues in them can slip unnoticed by both human eye as well as CI steps.
It's not the most robust solution as package bumps might need changes, but IMHO it's worth the added type safety in our authored `d.ts` files. 🙈 🤞 
- Fix `@date-io` adapters type declaration module names to be uniquely scoped (seems like it should originally be something like that)
- Rename `date-fns-jalali` duplicated typing type names to avoid tsc issues
=> [pickers] Ditch pickers `skipLibCheck`

packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
Fixes https://github.com/mui/mui-x/issues/3894
Supersedes https://github.com/mui/mui-x/pull/5978
In v6, listening to `debouncedResize` is enough to reduce the amount of rerenders drastically.
I didn't dive deep into the reason behind it, but I suspect it has something to do with https://github.com/mui/mui-x/pull/7001 which [removed the children function from auto sizer](https://github.com/mui/mui-x/pull/7001/files/35807f9d338d59da1321fe3ea0b68e0d05fa6e46#diff-9e93b57cf45d5ec1fa25b84787828b6db8753bee011ce39e557fca891075ab7dR78)
Side note: merging https://github.com/mui/mui-x/pull/7857 will reduce the number of rerenders even more.
Before: https://codesandbox.io/s/datagriddemo-rendercell-call-count-v5-forked-gbk73
After: https://codesandbox.io/s/datagriddemo-rendercell-call-count-v5-forked-b …
=> [DataGrid] Improve grid resize performance

packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx
Fixes a regression of slide transition not being present.
Current v5:
https://user-images.githubusercontent.com/4941090/217871906-667cb2ae-b69e-4491-beb6-7edf0f03ca16.mov
Current v6:
https://user-images.githubusercontent.com/4941090/217871966-479d4595-da1a-4ee3-931f-97bf14ea3fcc.mov
Updated [v6 calendar](https://deploy-preview-7874--material-ui-x.netlify.app/x/react-date-pickers/date-range-calendar/#basic-usage)
=> [DateRangePicker] Fix slide transition by avoiding useless component re-rendering

.circleci/config.yml, docs/data/date-pickers/date-time-picker/date-time-picker.md, docs/data/date-pickers/time-picker/time-picker.md, package.json
Closes #7919 
Implement a suggestion mentioned in https://github.com/mui/mui-x/issues/7919#issuecomment-1427570586
=> [docs] Add an info callout specifying the current state of desktop time view

docs/scripts/api/buildComponentsDocumentation.ts, docs/translations/api-docs/date-pickers/localization-provider.json, packages/x-date-pickers/src/LocalizationProvider/LocalizationProvider.tsx
Created [from](https://mui-org.slack.com/archives/C041SDSF32L/p1675893700633939):
> What does DateAdapter mean, where do I find it, what are the options?
> sent from https://mui.com/x/api/date-pickers/localization-provider/
- Support parsing `@see` with `{@link}` JSDoc into an anchor
- Update `LocalizationProvider` `dateAdapter` JSDoc to no longer refer to `DateIO` and link to a doc
JSDoc example in IDE:
Rendered [doc example](https://deploy-preview-7872--material-ui-x.netlify.app/x/api/date-pickers/localization-provider/#:~:text=you%20are%20using-,dateAdapter,-func).
=> [docs] Update `LocalizationProvider` `dateAdapter` with a link to doc

docs/data/date-pickers/localization/data.json, packages/x-date-pickers/src/locales/huHU.ts, packages/x-date-pickers/src/locales/index.ts, scripts/x-date-pickers-pro.exports.json, scripts/x-date-pickers.exports.json
=> [l10n] Add Hungarian (hu-HU) locale from @noherczeg

packages/grid/x-data-grid-premium/src/hooks/features/rowGrouping/createGroupingColDef.tsx, packages/grid/x-data-grid-premium/src/tests/rowGrouping.DataGridPremium.test.tsx
Fixes #7949 
The `leafField` was borrowing `hasFocus` from the actual cell (not the grouping one where it's rendered) and passing it in `leafField.renderCell` due to which the user can not keep track of the true focused cell.
Before: https://codesandbox.io/s/hasfocus-for-row-grouping-leaves-tuw57o?file=/demo.tsx
After: https://codesandbox.io/s/hasfocus-for-row-grouping-leaves-forked-359w8j?file=/demo.tsx
=> [DataGridPremium] Fix `leafField` to have correct focus value

CHANGELOG.md, docs/package.json, package.json, packages/grid/x-data-grid-generator/package.json, packages/grid/x-data-grid-premium/package.json, packages/grid/x-data-grid-pro/package.json, packages/grid/x-data-grid/package.json, packages/x-codemod/package.json, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json, packages/x-license-pro/package.json
```sh
```
Once deployed, it will be accessible at https://material-ui-x.netlify.app/ for the `docs-v5` deployment.
=> v6.0.0-beta.4

packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx, packages/x-date-pickers/src/DateTimePicker/shared.ts, packages/x-date-pickers/src/internals/components/PickersToolbar.tsx, packages/x-date-pickers/src/internals/models/props/baseToolbarProps.ts, packages/x-date-pickers/src/internals/models/views.ts, packages/x-date-pickers/src/locales/csCZ.ts, packages/x-date-pickers/src/locales/deDE.ts, packages/x-date-pickers/src/locales/enUS.ts, packages/x-date-pickers/src/locales/esES.ts, packages/x-date-pickers/src/locales/faIR.ts, packages/x-date-pickers/src/locales/fiFI.ts, packages/x-date-pickers/src/locales/frFR.ts, packages/x-date-pickers/src/locales/isIS.ts, packages/x-date-pickers/src/locales/itIT.ts, packages/x-date-pickers/src/locales/jaJP.ts, packages/x-date-pickers/src/locales/nbNO.ts, packages/x-date-pickers/src/locales/nlNL.ts, packages/x-date-pickers/src/locales/plPL.ts, packages/x-date-pickers/src/locales/ptBR.ts, packages/x-date-pickers/src/locales/ruRU.ts, packages/x-date-pickers/src/locales/svSE.ts, packages/x-date-pickers/src/locales/trTR.ts, packages/x-date-pickers/src/locales/ukUA.ts, packages/x-date-pickers/src/locales/utils/pickersLocaleTextApi.ts, packages/x-date-pickers/src/locales/zhCN.ts
Noticed that the `aria-label` on the editing mode button doesn't change when switching tabs or changing view by clicking toolbar sections.
- ensure the `viewType` is dynamically updated from `DateTimePickerToolbar`;
- create a type for `'calendar' | 'clock'`
- remove redundant types in localization files
=> [DateTimePicker] Ensure toolbar `viewType` is correctly updated

docs/pages/x/api/date-pickers/single-input-date-time-range-field.json, docs/pages/x/api/date-pickers/single-input-time-range-field.json, docs/translations/api-docs/date-pickers/single-input-date-time-range-field.json, docs/translations/api-docs/date-pickers/single-input-time-range-field.json, packages/x-date-pickers-pro/src/SingleInputDateTimeRangeField/SingleInputDateTimeRangeField.tsx, packages/x-date-pickers-pro/src/SingleInputDateTimeRangeField/SingleInputDateTimeRangeField.types.ts, packages/x-date-pickers-pro/src/SingleInputTimeRangeField/SingleInputTimeRangeField.tsx, packages/x-date-pickers-pro/src/SingleInputTimeRangeField/SingleInputTimeRangeField.types.ts
Noticed this misalignment when working on #7987 
- fix slot name issue;
- fix missing `slotProps?.textField ??` on `SingleInputDateTimeRangeField`;
=> [fields] Fix single input time range fields slot props

docs/data/data-grid/localization/DataGridLocalisationTableNoSnap.js, docs/data/date-pickers/base-concepts/ComponentExplorerNoSnap.js, docs/data/date-pickers/base-concepts/ComponentExplorerNoSnap.tsx, docs/data/date-pickers/custom-layout/AddComponent.js, docs/data/date-pickers/custom-layout/AddComponent.tsx, docs/data/date-pickers/date-calendar/date-calendar.md, docs/data/date-pickers/date-field/date-field.md, docs/data/date-pickers/date-picker/date-picker.md, docs/data/date-pickers/date-range-calendar/CustomDateRangePickerDay.js, docs/data/date-pickers/date-range-calendar/CustomDateRangePickerDay.tsx, docs/data/date-pickers/date-range-field/date-range-field.md, docs/data/date-pickers/date-range-picker/date-range-picker.md, docs/data/date-pickers/date-time-field/date-time-field.md, docs/data/date-pickers/date-time-picker/date-time-picker.md, docs/data/date-pickers/date-time-range-field/date-time-range-field.md, docs/data/date-pickers/fields/LifeCycleDateRangeField.js, docs/data/date-pickers/fields/LifeCycleDateRangeField.tsx, docs/data/date-pickers/fields/LifeCycleDateRangeField.tsx.preview, docs/data/date-pickers/localization/PickersLocalisationTableNoSnap.js, docs/data/date-pickers/time-clock/time-clock.md, docs/data/date-pickers/time-field/time-field.md, docs/data/date-pickers/time-picker/TimePickerViews.js, docs/data/date-pickers/time-picker/TimePickerViews.tsx, docs/data/date-pickers/time-picker/time-picker.md, docs/data/date-pickers/time-range-field/time-range-field.md, docs/src/modules/components/LocalizationTable.js, packages/x-date-pickers/src/internals/demo/DemoContainer.tsx
Fix for SEO https://search.google.com/search-console/mobile-usability?resource_id=sc-domain:mui.com&utm_source=wnc_10030322&utm_medium=gamma&utm_campaign=wnc_10030322&utm_content=msg_100058679&hl=en
Fix part of #5652
=> [docs] Fix a few scroll issues on mobile

packages/x-date-pickers/src/DateField/tests/format.DateField.test.tsx
Follow up #7888 and #7868
I don't think we should do it for all the tests (the selection for example is not very adapter-bound).
But for the format, the test could fail on some adapters (and was failing on Luxon) so I think that's worth adding those.
=> [test] Support all adapters on the field tests about the formats

packages/x-date-pickers/src/tests/describeAdapters/describeAdapters.ts
We need a cleaner fix but it's broken on `next` so I'm doing a quick fix first
=> [core] Fix moment locale on adapter tests

dangerfile.js, dangerfile.ts, docs/data/data-grid/editing/editing.md, docs/data/date-pickers/custom-components/custom-components.md
Taken from https://github.com/mui/material-ui/pull/35995
=> [core] Add modified docs page links in the PR

docs/data/data-grid/filtering/DisableMultiFiltersDataGridPro.js, docs/data/data-grid/filtering/DisableMultiFiltersDataGridPro.tsx, packages/grid/x-data-grid-pro/src/tests/filtering.DataGridPro.test.tsx, packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterPanel.tsx
Related to #4872, #6333
Emerged during working on #7968 
**Problem:**
The return type (`GridColDef['field']`) of `getColumnForNewFilter` was not correct, in some cases (when the intention is to not add a filter) the expected return value was `undefined` but the type definition didn't allow it.
**Solution:**
Added `| null` to the return type to handle the use case of not adding a new filter. Why not `| undefined`? As `null` is more explicit than `undefined` and depicts the action taken is intended.
=> [DataGridPro] Improve typing for `getColumnForNewFilter` method

docs/data/data-grid/row-pinning/RowPinning.js, docs/data/data-grid/row-pinning/RowPinning.tsx, docs/data/data-grid/row-pinning/RowPinning.tsx.preview, docs/data/data-grid/row-pinning/RowPinningWithActions.js, docs/data/data-grid/row-pinning/RowPinningWithActions.tsx, docs/data/data-grid/row-pinning/RowPinningWithActions.tsx.preview, docs/data/data-grid/row-pinning/RowPinningWithPagination.js, docs/data/data-grid/row-pinning/RowPinningWithPagination.tsx, docs/data/data-grid/row-pinning/RowPinningWithPagination.tsx.preview, docs/data/data-grid/row-pinning/row-pinning.md, docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md, docs/pages/x/api/data-grid/data-grid-premium.json, docs/pages/x/api/data-grid/data-grid-pro.json, packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx, packages/grid/x-data-grid-premium/src/tests/rowPinning.DataGridPremium.test.tsx, packages/grid/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx, packages/grid/x-data-grid-pro/src/hooks/features/rowPinning/useGridRowPinning.ts, packages/grid/x-data-grid-pro/src/models/dataGridProProps.ts, packages/grid/x-data-grid-pro/src/tests/rowPinning.DataGridPro.test.tsx, packages/x-codemod/src/v6.0.0/data-grid/remove-stabilized-experimentalFeatures/actual.spec.js, packages/x-codemod/src/v6.0.0/data-grid/remove-stabilized-experimentalFeatures/expected.spec.js, packages/x-codemod/src/v6.0.0/data-grid/remove-stabilized-experimentalFeatures/index.ts
Closes #8038 
- 🎁 The row pinning is no longer experimental.
You can now use the row pinning without the `experimentalFeatures.rowPinning` flag enabled.
```diff
<DataGridPro
-  experimentalFeatures={{ rowPinning: true }}
/>
```
=> [DataGridPro] Remove row pinning from experimental features

docs/data/date-pickers/adapters-locale/UTCMoment.js, docs/data/date-pickers/adapters-locale/UTCMoment.tsx, docs/data/date-pickers/adapters-locale/UTCMoment.tsx.preview, docs/data/date-pickers/adapters-locale/adapters-locale.md, packages/x-date-pickers/src/AdapterMoment/index.ts
[Doc preview](https://deploy-preview-8031--material-ui-x.netlify.app/x/react-date-pickers/adapters-locale/#with-moment-2)
`moment.utc` does not have the static properties (same issue we had for `dayjs`).
I think we could update the JSDoc of `dateLibInstance` to say that it's the instance we use to parse dates, not the instance we use for the rest.
=> [pickers] Add support for UTC on moment adapter

docs/pages/x/api/date-pickers/date-time-picker.json, docs/pages/x/api/date-pickers/desktop-date-time-picker.json, docs/pages/x/api/date-pickers/desktop-time-picker.json, docs/pages/x/api/date-pickers/mobile-date-time-picker.json, docs/pages/x/api/date-pickers/mobile-time-picker.json, docs/pages/x/api/date-pickers/static-date-time-picker.json, docs/pages/x/api/date-pickers/static-time-picker.json, docs/pages/x/api/date-pickers/time-picker.json, packages/x-date-pickers/src/DateTimePicker/DateTimePicker.tsx, packages/x-date-pickers/src/DateTimePicker/shared.tsx, packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx, packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.tsx, packages/x-date-pickers/src/MobileDateTimePicker/MobileDateTimePicker.tsx, packages/x-date-pickers/src/MobileTimePicker/MobileTimePicker.tsx, packages/x-date-pickers/src/StaticDateTimePicker/StaticDateTimePicker.tsx, packages/x-date-pickers/src/StaticTimePicker/StaticTimePicker.tsx, packages/x-date-pickers/src/TimeClock/Clock.tsx, packages/x-date-pickers/src/TimeClock/TimeClock.types.ts, packages/x-date-pickers/src/TimePicker/TimePicker.tsx, packages/x-date-pickers/src/TimePicker/shared.tsx
Part of #7372
- Remove usage of `WrapperVariantContext` in `Clock`
- Replicate behavior by providing `ampmInClock` prop defaultized to `true` on `desktop`
- refactor specific `Time` and `DateTime` picker types by removing duplicated (redundant) `ampm` prop and replacing it with `ampmInClock` with more specific (correct) default documentation
=> [pickers] Stop using `WrapperVariantContext` in `Clock`

docs/data/data-grid/demo/PopularFeaturesDemo.js, docs/data/data-grid/demo/PopularFeaturesDemo.tsx
- Fix typo on Aggregation.
- Add Column Menu and Cell Selection to the demo list. 
https://deploy-preview-7863--material-ui-x.netlify.app/x/react-data-grid/demo/
=> [docs] Update Data Grid demo to v6-beta

.github/ISSUE_TEMPLATE/1.bug.yml, .github/ISSUE_TEMPLATE/3.pro-support.yml, .github/ISSUE_TEMPLATE/4.premium-support.yml, docs/data/introduction/support/support.md
Closes https://github.com/mui/mui-x/issues/6899
Users purchasing a license through a procurement service sometimes don't get access to the original order ID. We'll ship the order ID as a Support key together with the license key, to make sure the number reaches the developers that will be using the license and technical support.
This PR goes together with https://github.com/mui/mui-store/pull/230, which adds the order Id as a support key to the order note, as we do with the license key.
=> Mention the use of Support key as an alternative to the OrderID

packages/grid/x-data-grid/src/models/gridSlotsComponentsProps.ts
Relates to #7968 
As shown in this [codesandbox](https://codesandbox.io/s/data-grid-community-forked-sv2j2g?file=/src/Test.tsx), with current typing, if user tries to augment the same interface twice in a same project, typescript makes them both mandatory which is not always the expectation.
=> [DataGrid] Allow multiple modules' augmentation

packages/grid/x-data-grid-pro/src/tests/detailPanel.DataGridPro.test.tsx, packages/grid/x-data-grid-pro/src/tests/rowPinning.DataGridPro.test.tsx, packages/grid/x-data-grid/src/tests/pagination.DataGrid.test.tsx, packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx
Fixes https://github.com/mui/mui-x/pull/7986#discussion_r1121837811
If it works well, I'll submit a PR that would remove `fake` clock in other tests as well.
=> [test] Fix flaky tests

docs/data/data-grid/cell-selection/cell-selection.md, docs/data/data-grid/column-pinning/column-pinning.md, docs/data/data-grid/editing/editing.md, docs/data/data-grid/export/export.md, docs/data/data-grid/filtering/filtering.md, docs/data/data-grid/master-detail/master-detail.md, docs/data/data-grid/pagination/pagination.md, docs/data/data-grid/row-grouping/row-grouping.md, docs/data/data-grid/row-selection/row-selection.md, docs/data/data-grid/scrolling/scrolling.md
=> [docs] Link `API object` in the `apiRef` sections

packages/x-date-pickers/src/AdapterDateFns/index.ts, packages/x-date-pickers/src/AdapterDateFnsJalali/index.ts, packages/x-date-pickers/src/AdapterDayjs/index.ts, packages/x-date-pickers/src/AdapterLuxon/index.ts, packages/x-date-pickers/src/AdapterMoment/index.ts, packages/x-date-pickers/src/AdapterMomentHijri/index.ts, packages/x-date-pickers/src/AdapterMomentJalaali/index.ts
No behavior change, will automerge
=> [fields] Clean the order of the tokens in the `formatTokenMap` of each adapter

docs/data/data-grid/localization/data.json, packages/grid/x-data-grid/src/locales/csCZ.ts
I just fill remaining translations and fix typos.
=> [l10n] Import Czech (cs-CZ) locale

docs/data/pages.ts
We're in a very early phase with the charts, and although I agree we can employ the opportunity to add links to the issues for upvoting, I think we need at least a good overview page to make them public.
=> [docs] Remove charts path structure from side navigation menu.

docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md
=> [docs] Add expansion state behavioral change to v6 migration guide

packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json, packages/x-license-pro/package.json
The goal is to link the page of the docs that is covering as much ground as possible for the related npm package but without being too broad.
=> [docs] Improve link from npm to docs

docs/data/migration/migration-pickers-v5/migration-pickers-v5.md, packages/x-codemod/src/v6.0.0/pickers/migrate-to-components-componentsProps/actual.spec.js
=> [docs] Fix a typo in the migration guide

packages/x-date-pickers/src/internals/hooks/usePicker/usePicker.ts
=> [pickers] Add a runtime warning when a `renderInput` prop is passed to a picker

packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx
=> [pickers] Don't pass `ownerState` to the `inputAdornment` slot

packages/grid/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx
Fixes #8166
Before: https://codesandbox.io/s/bug-reproduction-h06vvj?file=/src/App.tsx
After: https://codesandbox.io/s/bug-reproduction-forked-z0f82v?file=/src/App.tsx
=> [DataGrid] Fix `MenuProps.onClose` being overriden for single select edit component

docs/src/modules/components/ApiPage.js
Fix https://app.ahrefs.com/site-audit/3992793/28/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cdepth%2Ccompliant%2CincomingAllLinks%2Corigin&filterId=91013c8aafad4fe1f7a0ad504eccad42&issueId=c64da643-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating
See the bug on https://mui.com/x/api/date-pickers/date-picker/#component-name
---
The issue was introduced with https://github.com/mui/material-ui/pull/36008. MUI X uses the translations of the docs-infra. This reinforces that we should remove the duplication of the `ApiPage` component from MUI X to use the docs-infra.
After: https://deploy-preview-8200--material-ui-x.netlify.app/x/api/date-pickers/date-picker/#component-name
=> [docs] Fix 404 links to customization Material UI APIs

packages/x-date-pickers-pro/src/internal/hooks/useDesktopRangePicker/useDesktopRangePicker.tsx, packages/x-date-pickers-pro/src/internal/hooks/useDesktopRangePicker/useDesktopRangePicker.types.ts, packages/x-date-pickers-pro/src/internal/hooks/useMobileRangePicker/useMobileRangePicker.tsx, packages/x-date-pickers-pro/src/internal/hooks/useMobileRangePicker/useMobileRangePicker.types.ts
=> [DateRangePicker] Allow to override `slotProps.textField`

packages/x-date-pickers/src/internals/hooks/useField/useField.ts
We now have a warning in `LocalizationProvider` checking that the adapter comes from our packages.
And all adapter from our packages have a token map.
So this warning is never usefull.
=> [fields] Remove the warning about invalid adapter

docs/data/migration/migration-pickers-v5/migration-pickers-v5.md
Should solve #8161 (keeping it open until I have a feedback)
=> [docs] Add a warning in the migration guide for people re-enabling the clock on desktop

docs/data/data-grid/scrolling/scrolling.md
https://mui.com/x/react-data-grid/scrolling/#scrolling-to-specific-cells feels pretty bad with this grey background, there isn't enough contrast. I saw this in https://mui-org.slack.com/archives/C041SDSF32L/p1678786680764649?thread_ts=1678783975.763379&cid=C041SDSF32L.
Preview: https://deploy-preview-8239--material-ui-x.netlify.app/x/react-data-grid/scrolling/#scrolling-to-specific-cells.
=> [docs] Improve contrast on data grid navigation

docs/data/date-pickers/shortcuts/shortcuts.md
In the documentation, the code example is behind the latest changes (use `slotProps`, not `componentProps`)
=> [docs] Update shortcuts page to use slotProps

docs/data/date-pickers/date-range-field/date-range-field.md, docs/data/date-pickers/date-time-range-field/date-time-range-field.md, docs/data/date-pickers/time-range-field/time-range-field.md
We've discussed that a few pro plan links are pointing to the store, while most other cases point to the licensing page.
The former were updated.
=> [docs] Fix pro license links to point to the same page

packages/x-date-pickers/src/internals/hooks/useField/useField.ts, packages/x-date-pickers/src/tests/describeValue/testPickerOpenCloseLifeCycle.tsx
Fixes #8283 
The previous (initial) implementation was causing a regression due to the fact that in Safari calling `setSelectionRange` causes the input to receive focus.
Source: https://bugs.webkit.org/show_bug.cgi?id=224425
P.S. The state of pickers in Safari is not ideal, there are other, less severe issues that I observed, but they would need a separate investigation on how to solve them.
=> [fields] Fix Safari input selection resetting regression

packages/x-date-pickers-pro/src/internal/utils/valueManagers.ts, packages/x-date-pickers/src/internals/hooks/useField/index.ts, packages/x-date-pickers/src/internals/hooks/useField/useField.ts, packages/x-date-pickers/src/internals/hooks/useField/useField.types.ts, packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts, packages/x-date-pickers/src/internals/index.ts, packages/x-date-pickers/src/internals/utils/valueManagers.ts
@alexfauquette is there something preventing us from using the sections from the state instead of calling `splitFormatIntoSections` just for the section order ?
It simplifies the whole data flow.
=> [fields] Cleanup section order generation

packages/x-date-pickers-pro/src/internal/utils/valueManagers.ts, packages/x-date-pickers/src/DesktopDatePicker/tests/field.DesktopDatePicker.test.tsx, packages/x-date-pickers/src/internals/hooks/useField/useField.ts, packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts, packages/x-date-pickers/src/internals/index.ts, packages/x-date-pickers/src/internals/utils/date-utils.ts, packages/x-date-pickers/src/internals/utils/valueManagers.ts
Fixes #8296 
Fixes a bug caused by #8287 (not released yet) and #8082
If you clean a section in the field, it now cleans the entire field when used inside a picker ?
Why ? Because the picker replaces `Invalid Date` by `null` in its internal state, to when you clean a section, the field fires `onChange` with the invalid date (#8082), the picker replaces it with `null` and the field updates the sections based on this new value (the fix from #8287 uncovered this broken behavior).
____
The views don't like invalid dates.
That's something we should probably improve at some point.
For now, I just allows to store `Invalid Date` in the picker state and instead replace it with `null` before passing it to the views.
That way the field does receive the `Invalid Date` it asked for.
I also changed the …
=> [pickers] Support invalid dates from the field

packages/x-date-pickers/src/internals/hooks/useField/useField.ts
Fixes #8321 
I'm honestly not sure, why it help stop the scroll jumping, even though the `scrollTop` is always 0 as far as I've tested. 🤷 
After all native Apple software is the "new IE" of the world. 😆
=> [fields] Fix iOS browser scroll jumping when entering data

docs/data/migration/migration-pickers-v5/migration-pickers-v5.md
Fixes #8346 
Extended the `shouldDisableTime` migration documentation to increase the clarity on what has happened, what the codemod will handle, and what should the user do.
=> [docs] Explain the `shouldDisableTime` migration more in-depth

packages/grid/x-data-grid/src/components/menu/columnMenu/GridColumnHeaderMenu.tsx, packages/grid/x-data-grid/src/tests/columnHeaders.DataGrid.test.tsx
Closes https://github.com/mui/mui-x/issues/8251
Before: https://codesandbox.io/s/zud9od?file=/demo.tsx
After: https://codesandbox.io/s/pensive-bhabha-ov3y19
The fix added prevents calling `hideColumnMenu` if the button clicked is `kebab` icon that opens up column menu.
=> [DataGrid] Prevent reopening column menu when clicking in the button while it is open

docs/data/data-grid/localization/data.json, packages/grid/x-data-grid/src/locales/daDK.ts
Translate the last missing data grid keys for the Danish locale
=> [l10n] Improve Danish (da-DK) locale

docs/data/date-pickers/adapters-locale/FieldPlaceholder.js, docs/data/date-pickers/adapters-locale/FieldPlaceholder.tsx, docs/data/date-pickers/adapters-locale/FieldPlaceholder.tsx.preview, docs/data/date-pickers/overview/CommonlyUsedComponents.js, docs/data/date-pickers/overview/CommonlyUsedComponents.tsx
Refactor demos where having `label` reduces the clarity of the idea that is trying to be portrayed.
___
=> [docs] Remove `label` from demos where it reduces clarity

docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md
This was pointed out by our user through docs feedback.
=> [docs] Fix `GridCellParams` signature in migration guide

packages/grid/x-data-grid-premium/src/hooks/features/aggregation/wrapColumnWithAggregation.tsx
Fixes #8419 
For some weird reason, when using both `rowGrouping` and `quickFilter` initial states along with the `aggregation`, the `aggregation.aggregationLookup` becomes `undefined` on the initial render.
The fix resolves the issue apparently, but we may need to dig a bit deeper into why the issue is occurring in the first place.
Before: https://codesandbox.io/s/aggregation-grouping-quick-filter-broken-09nu8h
After: https://codesandbox.io/s/aggregation-grouping-quick-filter-broken-forked-vb6gto?file=/demo.js
=> [DataGridPremium] Fix aggregation initial state causing issue with quick filter

packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaderTitle.tsx
Fixes #8406
Before - https://codesandbox.io/s/datagrid-column-header-tooltip-not-rendering-4n99kg?file=/src/App.tsx
After - https://codesandbox.io/s/third-approach-for-title-overflow-tooltip-64lc9h
=> [DataGrid] Fix column header tooltip not showing when the title is truncated

docs/data/data-grid/components/components.md, docs/data/data-grid/localization/data.json, docs/data/data-grid/localization/localization.md, docs/data/date-pickers/localization/data.json, packages/x-codemod/package.json, scripts/l10n.ts
This surfaces in https://app.ahrefs.com/site-audit/3523498/61/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CcontentType%2Cdepth%2Credirect%2CincomingAllLinks&filterId=b3b75b6257a370fcf9f1f73befb5deb5&issueId=c64d8847-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating. 
It's a good opportunity to use a link to the base branch so that once we change the default branch, the links on the stable version of the docs stay correct.
=> [core] Avoid 301 links

docs/data/data-grid/column-visibility/ColumnSelectorGridCustomizeColumns.js, docs/data/data-grid/column-visibility/ColumnSelectorGridCustomizeColumns.tsx, docs/data/data-grid/column-visibility/ColumnSelectorGridCustomizeColumns.tsx.preview, docs/data/data-grid/column-visibility/column-visibility.md, packages/grid/x-data-grid/src/components/panel/GridColumnsPanel.tsx, packages/grid/x-data-grid/src/tests/columnsVisibility.DataGrid.test.tsx
Fixes #7534 
Preview: https://deploy-preview-8401--material-ui-x.netlify.app/x/react-data-grid/column-visibility/#customize-the-list-of-columns-in-panel
=> [DataGrid] Allow to control visibility of columns shown in `ColumnsPanel`

docs/data/data-grid/localization/data.json, docs/data/date-pickers/localization/data.json, packages/x-date-pickers/src/locales/caES.ts, packages/x-date-pickers/src/locales/esES.ts
Spanish (es-ES) locale improved
=> [l10n] Add Catalan (Spain) (ca-ES) and improve Spanish (es-ES) locales

docs/public/_redirects
Fix https://app.ahrefs.com/site-audit/3992793/31/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CcontentType%2Cdepth%2CincomingAllLinks&filterId=624c70b6a74a7ac140893dd4714b6d3f&issueId=c64d3b5a-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating
It's used in locations like: https://stackoverflow.com/questions/74389125/mui-datepicker-how-can-i-change-yearpicker-styling
=> [docs] Fix broken API reference link

packages/grid/x-data-grid/src/components/columnHeaders/ColumnHeaderMenuIcon.tsx
Closes https://github.com/mui/mui-x/issues/7877
=> [DataGrid] Wrap column menu button with a tooltip

packages/grid/x-data-grid/src/hooks/core/useGridApiInitialization.ts, packages/grid/x-data-grid/src/models/api/gridCoreApi.ts, packages/grid/x-data-grid/src/utils/createSelector.test.ts, packages/grid/x-data-grid/src/utils/createSelector.ts
Fixes https://github.com/mui/mui-x/issues/6566#issuecomment-1476813266
=> [DataGrid] Fix memory leaks in development

packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx, packages/x-date-pickers/src/DateCalendar/PickersCalendarHeader.tsx, packages/x-date-pickers/src/TimeClock/TimeClock.tsx, packages/x-date-pickers/src/internals/components/PickersArrowSwitcher/PickersArrowSwitcher.tsx, packages/x-date-pickers/src/internals/components/PickersArrowSwitcher/PickersArrowSwitcher.types.tsx, packages/x-date-pickers/src/internals/components/PickersModalDialog.tsx, packages/x-date-pickers/src/internals/components/PickersPopper.tsx
Fixes #8506 
Fix to correctly apply:
```tsx
componentsProps={{
dialog: {
sx: {
backgroundColor: 'red',
},
},
}}
```
Also removed `components` and `componentsProps` from all internal components:
- PickersCalendarHeader
- PickersArrowSwitcher
- PickersModalDialog
- PickersPopper
=> [pickers] Fix `componentsProps.dialog` propagation

packages/x-date-pickers-pro/src/internal/utils/valueManagers.ts, packages/x-date-pickers/src/internals/hooks/useField/useField.ts, packages/x-date-pickers/src/internals/hooks/useField/useField.types.ts, packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts, packages/x-date-pickers/src/internals/utils/valueManagers.ts
Slightly improve the abstraction in `usePickerValue` by using the `hasError` method
`fieldValueManager` has now only methods really related to the field.
=> [pickers] Move `hasError` from `fieldValueManager` to `valueManager`

packages/x-date-pickers-pro/README.md, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/README.md, packages/x-date-pickers/package.json
Fix #8530 
Also tested and updated the minimum viable `@mui/system` version.
`5.8.6` is the minimum version exposing `useSlotProps`.
=> [pickers] Update peer dependency versions

packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts
Fix an issue mentioned here: https://github.com/mui/mui-x/pull/8533#pullrequestreview-1376114851
Allows for correct shortcuts behavior.
https://deploy-preview-8533--material-ui-x.netlify.app/x/react-date-pickers/shortcuts/
https://deploy-preview-8543--material-ui-x.netlify.app/x/react-date-pickers/shortcuts/
=> [pickers] Fix `isValid` regression

packages/grid/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts, packages/grid/x-data-grid/src/tests/rowSelection.DataGrid.test.tsx
Fixes #8455 
Before: https://codesandbox.io/s/checkbox-selection-bug-iflfz4?file=/src/App.tsx
After: https://codesandbox.io/s/checkbox-selection-bug-forked-9juhyv?file=/src/App.tsx
=> [DataGrid] Reset selection state on `checkboxSelection` toggle

packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputBoolean.tsx, packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputSingleSelect.tsx
I've noticed this problem in https://github.com/mui/mui-x/pull/8067 where I added a custom `baseTextfield` component and it turned out that the boolean select in the filter panel is now a regular text field:
If it was using `baseSelect` rather than `baseTextField`, the default Material UI select component would have been used (I didn't override the `baseSelect` with a Joy UI one yet)
=> [DataGrid] Use `baseSelect` slot instead of `baseTextField` with `select={true}`

docs/data/data-grid/localization/data.json, packages/grid/x-data-grid/src/locales/frFR.ts
Hi, I'm trying to translate aggregation literals. If it appears where I think it does, it's better to use abbreviation but not sure of the ones I chose. One could even argue that the English ones could be better understand by French speakers (except for `avg` maybe). Open to discussion.
=> [l10n] Improve French (fr-FR) locale

renovate.json
- Add `@mui/styles` to the `MUI Core` bump group (should avoid a separate `@mui/styles` bump PR and pointless CI runs)
- Create a `React router` group bumping both `react-router` and `react-router-dom` as they are always released in tandem and result in double PR/CI. 🙈
=> [core] Optimize `renovate` rules

packages/x-date-pickers/src/DateCalendar/DayCalendar.tsx, packages/x-date-pickers/src/DateTimePicker/shared.tsx, packages/x-date-pickers/src/DesktopDatePicker/tests/describes.DesktopDatePicker.test.tsx, packages/x-date-pickers/src/DesktopDateTimePicker/tests/describes.DesktopDateTimePicker.test.tsx, packages/x-date-pickers/src/DesktopTimePicker/tests/describes.DesktopTimePicker.test.tsx, packages/x-date-pickers/src/MobileDateTimePicker/MobileDateTimePicker.test.tsx, packages/x-date-pickers/src/MobileDateTimePicker/tests/describes.MobileDateTimePicker.test.tsx, packages/x-date-pickers/src/MobileTimePicker/tests/describes.MobileTimePicker.test.tsx, packages/x-date-pickers/src/StaticDateTimePicker/StaticDateTimePicker.test.tsx, packages/x-date-pickers/src/StaticTimePicker/StaticTimePicker.test.tsx, packages/x-date-pickers/src/tests/describeValidation/describeValidation.tsx, packages/x-date-pickers/src/tests/describeValidation/describeValidation.types.ts, packages/x-date-pickers/src/tests/describeValidation/testMinutesViewValidation.tsx
Fix #8520 
Change the default to include the date when validating `disablePast` and `disableFuture` in the `TimeClock`.
Fixes issue of TimeClock validation disabling all future or past time choices on any given day.
=> [DateTimePicker] Fix `TimeClock` validation ignoring date by default

packages/x-date-pickers-pro/README.md, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/README.md, packages/x-date-pickers/package.json
Avoids an issue discovered https://github.com/mui/mui-x/issues/8530#issuecomment-1503915419
Also synced all `peerDependencies` between community and pro packages.
=> [pickers] Add `@mui/base` to `peerDependencies`

docs/src/sw.js
This should solve https://github.com/mui/material-ui/issues/36808, but only for MUI X.
I can apply this to MUI Core docs after it's solved in MUI X.
I followed this guide: https://developer.chrome.com/docs/workbox/remove-buggy-service-workers/
=> [docs] Add no-op service worker to fix stale cache issue

packages/grid/x-data-grid/src/components/panel/GridColumnsPanel.tsx, packages/grid/x-data-grid/src/tests/columnsVisibility.DataGrid.test.tsx
Relates to #8401 
Previously I didn't add this callback to the `toggleAllColumns` method, but after playing around with the demo a bit, I feel the user's expectation could be to also have this callback honored when pressing Hide all and Show all buttons. I am open to feedback/suggestions on this though.
It may be useful in cases like avoiding blank grid state (when user accidentally hides all the columns and the state is not reversible)
Preview: https://deploy-preview-8496--material-ui-x.netlify.app/x/react-data-grid/column-visibility/#customize-the-list-of-columns-in-panel
=> [DataGrid] Add `getTogglableColumns` to `Hide all` and `Show all` actions

packages/x-date-pickers/src/MobileDatePicker/MobileDatePicker.test.tsx, packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts
Fix #8663
Fix #8684
If we update the controlled value with a side effect, the new value should be committed and published. Otherwise dismiss and cancel action will be incoherent with what the dev implemented
=> [pickers] Sync internal state with controlled value

packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts
`instanceof` was causing issues in #8261
See https://github.com/dmtrKovalenko/date-io/pull/639 for context
=> [pickers] Do not use `instanceOf DateTime` in `AdapterLuxon`

packages/x-date-pickers-pro/src/MultiInputDateRangeField/MultiInputDateRangeField.tsx, packages/x-date-pickers-pro/src/MultiInputDateTimeRangeField/MultiInputDateTimeRangeField.tsx, packages/x-date-pickers-pro/src/MultiInputTimeRangeField/MultiInputTimeRangeField.tsx
Part of @gerdadesign design review on the pickers
=> [pickers] Use en dash instead of em dash in multi input range fields

packages/grid/x-data-grid-premium/src/components/GridAggregationHeader.tsx, packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts
https://deploy-preview-8694--material-ui-x.netlify.app/x/react-data-grid/aggregation/
- Column titles with aggregation labels are not correctly aligned with other column titles. They are rendered slightly lower as shown with the red line below.
- The blue aggregation label is too close to the bottom.
=> [data grid] Fix aggregation label alignment

packages/x-charts/src/Highlight/Highlight.tsx, packages/x-charts/src/LineChart/LinePlot.tsx, packages/x-charts/src/ScatterChart/Scatter.tsx, packages/x-charts/src/hooks/useScale.ts, packages/x-charts/src/internals/getCurve.ts, packages/x-charts/src/models/seriesType/line.ts
To simplify the PR review, commits titles have a meaning
---
If you run `scale(value)` for most of the scaling, the answer is unique.
Except for band scale which returns the start of the band whereas w would like the middle to have nice looking between bar and lines plots
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://user-images.githubusercontent.com/45398769/233652745-46ca7ecc-3657-4c20-9bac-131c7508971c.png"/>
<td><img src="https://user-images.githubusercontent.com/45398769/233652590-64ecdde0-1c3a-4f39-a6e6-bd09f319f547.png" />
</table>
Add a parameter `curve` to series with `type: 'line'` such that user con chose the line interpolation
=> [charts] Adapt line and scatter the band scale

packages/x-date-pickers/src/PickersDay/PickersDay.tsx
Fix #8763 
Things changed:
- Do not apply the disabled (black with opacity -> gray) color to a selected & disabled day;
- Apply `opacity` to a disabled & selected day to achieve more consistent styling with the other disabled days and make it more visually clear that it's selected, but disabled;
Before issues can be seen in the issue.
=> [pickers] Fix date calendar `selected` & `disabled` day style

packages/grid/x-data-grid/src/hooks/features/columnGrouping/useGridColumnGrouping.ts, packages/grid/x-data-grid/src/tests/columnsGrouping.DataGrid.test.tsx
Fixes https://github.com/mui/mui-x/issues/8602
Before: https://codesandbox.io/s/data-grid-pro-version-6-1-0-bp39li?file=/demo.js
After: https://codesandbox.io/s/data-grid-pro-version-6-1-0-d8mm7r?file=/demo.js
The problem comes from this effect where column grouping is recalculated:
https://github.com/mui/mui-x/blob/970124e990bb677cd867fcc49842fb7454fa9cb2/packages/grid/x-data-grid/src/hooks/features/columnGrouping/useGridColumnGrouping.ts#L147-L181
The main dependencies of this effect are:
- `columnFields` coming from columns state
- `visibleColumnFields` coming from columns state
- `props.columnGroupingModel` coming from props
The problem is that after updating both `columns` and `columnGroupingModel` props, the effect is triggered by `columnGroupingModel` prop change, while …
=> [DataGridPro] Fix error after updating `columns` and `columnGroupingModel` at once

packages/x-date-pickers-pro/src/internal/models/dateTimeRange.ts, packages/x-date-pickers/src/DateTimeField/DateTimeField.types.ts, packages/x-date-pickers/src/DateTimePicker/shared.tsx, packages/x-date-pickers/src/internals/index.ts, packages/x-date-pickers/src/internals/models/validation.ts, packages/x-date-pickers/src/internals/utils/validation/extractValidationProps.ts, packages/x-date-pickers/src/tests/describeValidation/testTextFieldValidation.tsx
Fixes #8774 
The prop name had a typo and thus was not correctly extracted where needed.
The only relevant functional change is this line: https://github.com/mui/mui-x/compare/master...LukasTy:fix-minutes-step-validation?expand=1#diff-bd535b311395403beb06c0752755b96f8ffc56ede0aa626b670e6d8b6d8f48b6R33
- Added tests covering the behavior;
- Strict typed the validation prop names;
- Created a co-located type for `DateTimeValidationProps`;
=> [pickers] Fix `minutesStep` validation prop behavior

packages/grid/x-data-grid/src/components/toolbar/GridToolbarFilterButton.tsx, packages/grid/x-data-grid/src/tests/filtering.DataGrid.test.tsx
Displaying before fix:
https://codesandbox.io/s/muddy-star-18il32?file=/demo.tsx
After:
https://codesandbox.io/s/determined-ellis-hidp5r?file=/demo.tsx
=> [DataGrid] Fix falsy filter values not showing in filter button tooltip

.gitignore, docs/pages/playground/tsconfig.json
We used to include playground pages in `docs/tsconfig.json` to get proper types in these files https://github.com/mui/mui-x/pull/5367
This has one downside - if you have outdated playground pages that do not compile, `yarn typescript` will also fail locally.
Playground pages were excluded in https://github.com/mui/mui-x/pull/8792/files#r1182249749, but broke TS compilation of these pages in IDE, as reported by @LukasTy :
---
This PR fixes TS compilation of playground pages in IDE while excluding them from `yarn typescript`.
=> [core] Do not include playground pages in `yarn typescript` script

packages/x-date-pickers/src/DateTimePicker/shared.tsx, packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.tsx, packages/x-date-pickers/src/TimeClock/TimeClock.types.ts, packages/x-date-pickers/src/internals/hooks/usePicker/usePickerViews.ts, packages/x-date-pickers/src/internals/models/props/clock.ts, packages/x-date-pickers/src/timeViewRenderers/timeViewRenderers.tsx
Fixes #8821
- Adjust `viewRenderers` typing to allow for both `TimeClock` as well as `DigitalClock` overriding.
- Avoid appending the `meridiem` view when some other renderer than `renderMultiSectionDigitalClockTimeView` is provided to the `hours` renderer. (i.e. providing `renderTimeViewClock`).
- Fix viewRenderers individual view entry typing to contain only the relevant `views` key. This allows passing `hours: renderDigitalClockTimeView` without errors complaining that the views have all possible views instead of only the one that is being overridden.
- Small typing fixes/improvements
=> [pickers] Fix time picker `viewRenderers` overriding

packages/x-date-pickers-pro/src/MobileDateRangePicker/tests/MobileDateRangePicker.test.tsx
Try fixing sometimes unexpectedly failing 2 `MobileDateRangePicker` [tests](https://app.circleci.com/pipelines/github/mui/mui-x/37668/workflows/d6e325f4-bc0f-404c-9ce3-4770d66cfb1f/jobs/216366/parallel-runs/0/steps/0-107).
=> [test] Use `fake` clock on `MobileDateRangePicker`

packages/grid/x-data-grid-premium/src/tests/rowGrouping.DataGridPremium.test.tsx, packages/grid/x-data-grid-pro/src/utils/tree/utils.ts
Fixes https://github.com/mui/mui-x/issues/8580
Before: https://codesandbox.io/s/kind-lamarr-ofjvim
After: https://codesandbox.io/s/wild-http-h2gfjq
Fixes https://github.com/mui/mui-x/issues/8853
Before: https://codesandbox.io/s/cocky-sunset-f7qkjg
After: https://codesandbox.io/s/frosty-bassi-1hwexf
---
The issue comes down to this part where we update the row tree:
https://github.com/mui/mui-x/blob/1099111eb455dc8ab744388517fc2fe4a12bab2b/packages/grid/x-data-grid-pro/src/utils/tree/updateRowTree.ts#L61-L63
Here we compare `path` and `pathInPreviousTree`. But `isInSameGroup` always equals `false`, even if the groups have not been changed. Here are example values that are being compared:
```tsx
[{ field: undefined, key: "1" }, { field: 14, key: 14 }] // pathInPreviousTree
[{ key: 14, …
```
=> [DataGridPremium] Fix expanded groups being collapsed after calling `updateRows`

docs/data/date-pickers/localization/data.json, packages/x-date-pickers/src/locales/index.ts, packages/x-date-pickers/src/locales/skSK.ts, scripts/x-date-pickers-pro.exports.json, scripts/x-date-pickers.exports.json
Add Slovak (sk-SK) locale for date-pickers, improve (cz-CZ) locale
=> [l10n][pickers] Add Slovak (sk-SK) locale

packages/grid/x-data-grid/src/joy/icons.tsx, packages/grid/x-data-grid/src/joy/joySlots.tsx
Most of the icons are from [Lucide](https://lucide.dev/). I think we don't have to spend a lot of time deciding which library we want to use at this point. At least the new one is differ from Material design.
Preview: https://deploy-preview-8940--material-ui-x.netlify.app/x/react-data-grid/experiments/joy-ui/
Here is the comparison:
=> [DataGrid] Add Joy UI icon slots

docs/data/date-pickers/localization/localization.md
It should be "@mui/x-date-pickers", not "@mui/x-date-pikers"
=> [docs] Fix date pickers typo in the docs 

packages/grid/x-data-grid-premium/src/tests/rowGrouping.DataGridPremium.test.tsx
Covers https://github.com/mui/mui-x/issues/8853 that was fixed in https://github.com/mui/mui-x/pull/8823
=> [test] Cover row grouping regression with a unit test 

packages/grid/x-data-grid-premium/src/DataGridPremium/useDataGridPremiumProps.ts, packages/grid/x-data-grid-pro/src/DataGridPro/useDataGridProProps.ts, packages/grid/x-data-grid/src/DataGrid/useDataGridProps.ts, packages/grid/x-data-grid/src/internals/utils/computeProps.ts, packages/grid/x-data-grid/src/internals/utils/index.ts, packages/grid/x-data-grid/src/internals/utils/useProps.ts
Closes #8932
This PR partially fixes the performance issues in the issue linked above by memoizing the grid root props. Previously, even if the props values were not changing, the destructuring of props into `...themedProps` was creating a new props object at every rerender of `DataGrid`, which triggered a re-render of all `GridRow` components.
The reason why I say that this PR partially fixes the issue is that if the user does something like below, then the props are going to be recomputed at every render because the `slots` object changes at every render, which will trigger all rows to be re-rendered.
```tsx
<DataGrid
{...someProps}
slots={{ row: MemoizedRow }}
/>
```
I think that a more thorough and general solution that expands beyond just `GridRow` would be to replace …
=> [Datagrid] Memoize root props

packages/grid/x-data-grid/src/locales/csCZ.ts
Better localization for czech.
=> [l10n][data grid] Improve Czech (cs-CZ) locale

docs/data/data-grid/localization/data.json, packages/grid/x-data-grid/src/locales/heIL.ts
Adding a translation to:
1. columnMenuManageColumns
2. filterPanelRemoveAll
=> [l10n] Add missing keys in Hebrew (he-IL) locale

docs/data/date-pickers/date-calendar/date-calendar.md, docs/data/date-pickers/date-field/date-field.md, docs/data/date-pickers/date-picker/date-picker.md, docs/data/date-pickers/date-range-calendar/date-range-calendar.md, docs/data/date-pickers/date-range-field/date-range-field.md, docs/data/date-pickers/date-range-picker/date-range-picker.md, docs/data/date-pickers/date-time-field/date-time-field.md, docs/data/date-pickers/date-time-picker/date-time-picker.md, docs/data/date-pickers/date-time-range-field/date-time-range-field.md, docs/data/date-pickers/digital-clock/digital-clock.md, docs/data/date-pickers/time-clock/time-clock.md, docs/data/date-pickers/time-field/time-field.md, docs/data/date-pickers/time-picker/time-picker.md, docs/data/date-pickers/time-range-field/time-range-field.md
I'm trying to improve the understanding of this section for people doing the following feedback:
- https://mui-org.slack.com/archives/C04U3R2V9UK/p1680715599729219
- https://mui-org.slack.com/archives/C04U3R2V9UK/p1681986257614069
I will apply the same change on all the other pages once we'll have decided on a wording
https://deploy-preview-8926--material-ui-x.netlify.app/x/react-date-pickers/date-picker/#uncontrolled-vs-controlled-value
=> [docs] Clarify what Controlled / Uncontrolled means

packages/x-date-pickers/src/internals/hooks/useViews.tsx
=> [pickers] Fix view management when `openTo` or `views` is modified

docs/data/data-grid/row-pinning/RowPinningWithPagination.js, docs/data/data-grid/row-pinning/RowPinningWithPagination.tsx, docs/data/data-grid/row-pinning/row-pinning.md, packages/grid/x-data-grid-pro/src/tests/rowPinning.DataGridPro.test.tsx, packages/grid/x-data-grid/src/hooks/features/editing/useGridEditing.ts, packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts, packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts
Closes https://github.com/mui/mui-x/issues/5591
Preview: https://deploy-preview-8921--material-ui-x.netlify.app/x/react-data-grid/row-pinning/#usage-with-other-features
=> [DataGridPro] Support pinned rows editing

packages/x-date-pickers/src/TimeField/tests/editing.TimeField.test.tsx, packages/x-date-pickers/src/internals/hooks/useField/useField.ts
=> [fields] Select the first section instead of last when clicking right of content

packages/grid/x-data-grid/src/tests/rowSelection.DataGrid.test.tsx
=> [core] Add assertion about checkbox rerenders

docs/pages/_app.js, docs/scripts/buildServiceWorker.js
See https://github.com/mui/material-ui/issues/36808#issuecomment-1533210335
=> [docs] Fix docs using wrong service worker

packages/grid/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts, packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx
Fixes https://github.com/mui/mui-x/issues/8737
Scenario 1:
Before: https://codesandbox.io/s/data-grid-community-forked-3ctumy
After: https://codesandbox.io/s/data-grid-community-forked-4glro7
Scenario 2:
Before: https://codesandbox.io/s/sparkling-waterfall-3sdhkk?file=/demo.tsx
After: https://codesandbox.io/s/vigilant-curran-xgf9pt
=> [DataGrid] Fix grid size calculation when `.MuiDataGrid-main` has border

docs/data/data-grid/performance/GridWithReactMemo.js, docs/data/data-grid/performance/GridWithReactMemo.tsx
Since #7846, we have a great performance demo, however, I noticed that we could improve the design of the animation, so I did for fun (overkill PR):
https://github.com/mui/mui-x/assets/3165635/0e65996c-acb4-41e8-b112-4ae7786a6dcd
https://mui.com/x/react-data-grid/performance/#memoize-inner-components-with-react-memo. It smoothly appears (feels a bit laggy) and then instantly disappears (feels a bit brutal). I think that it should be reversed like Chrome whose repaints feel great:
https://github.com/mui/mui-x/assets/3165635/7f044954-0b81-41fa-a252-a10d8b88d9a9
For the colors, we could consider picking the ones of React Dev Tools' UX, but it feels a bit cheap:
https://github.com/mui/mui-x/assets/3165635/fa775e24-4a58-4f05-b7e6-8604c4c03edf
Here is how it looks now: …
=> [docs] Smooth performance animation

packages/grid/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx
Fixes #8658 
Before: https://codesandbox.io/s/datagridpro-oncolumnwidthchange-issue-on-mobile-touchend-vvoion?file=/src/App.tsx
After: https://codesandbox.io/s/datagridpro-oncolumnwidthchange-issue-on-mobile-touchend-forked-lhph3v?file=/package.json
(To visualize the problem, open https://vvoion.csb.app/ on a mobile device and try to resize a column, no log will be shown on screen, now check https://lhph3v.csb.app/ it should print a log produced by `columnWidthChange` event)
=> [DataGridPro] Emit `columnWidthChange` event on `touchEnd` of column resize

packages/x-date-pickers/src/internals/hooks/useField/useField.ts
Fix #9003
`setSelectionRange` implementation on Safari/WebKit is strictly based on spec, where calling this method is only allowed on the focused element, hence, WebKit focuses the element before executing the `setSelectionRange` logic: https://bugs.webkit.org/show_bug.cgi?id=224425
In the case of pickers using MultiInput range fields, the `setSelectionRange` is being called on both inputs and that is causing the focus to jump between the two.
Ensuring that the `setSelectionRange` is being set only on the active element seems to fix the issue. 🤔
=> [pickers] Fix focus jumping on Safari

docs/data/data-grid/getting-started/getting-started.md, docs/data/date-pickers/getting-started/getting-started.md, packages/grid/x-data-grid-generator/package.json, packages/grid/x-data-grid-premium/README.md, packages/grid/x-data-grid-premium/package.json, packages/grid/x-data-grid-pro/README.md, packages/grid/x-data-grid-pro/package.json, packages/grid/x-data-grid/README.md, packages/grid/x-data-grid/package.json, packages/x-charts/package.json, packages/x-date-pickers-pro/README.md, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/README.md, packages/x-date-pickers/package.json, packages/x-license-pro/package.json
The problem with:
https://mui.com/x/react-data-grid/getting-started/#installation
is two folds:
1. It won't age well, https://jubianchi.github.io/semver-check/#/%3E%3D17.0.2/25.0.0
2. It's not clear what version is supported, it's actually the same issue as with 1. It makes developers confused https://mui-org.slack.com/archives/C041SDSF32L/p1683384455188729
=> [docs] Clarify the peer dependency with react

docs/package.json, yarn.lock
Closes https://github.com/mui/mui-x/pull/9055
The bump [would introduce](https://github.com/mui/mui-x/pull/9055/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR10335) a secondary `node-fetch` package, although, the `cross-fetch` itself does not seem to be used at all... 🤷
=> [core] Remove `cross-fetch` dependency

docs/src/modules/components/LocalizationTable.js
Before: https://deploy-preview-9030--material-ui-x.netlify.app/x/react-data-grid/localization/#supported-locales
After: https://deploy-preview-9033--material-ui-x.netlify.app/x/react-data-grid/localization/#supported-locales
Closes #7101 
Improvements to the progress bar:
- gave all bars more horizontal space (100%) for more readability & to avoid the inconsistency currently happening when we have fewer digits displaying. 
- Changed the background to a neutral color for more contrast 
- using the lighter version of the colors gives an overall softer look
- since the difference between 35/36 and 36/36 is still not very distinguishable, I changed the text displayed when the translation is complete to 'done' (another option would have been to use an emoji for this - which would look nice - …
=> [docs] Improve localization table progress bars

package.json, renovate.json, yarn.lock
Closes #9060
Address https://github.com/mui/mui-x/pull/9060#pullrequestreview-1441631866
Locking it on v18 as we plan to stick with v18 (current LTS) for CI as discussed here https://github.com/mui/material-ui/pull/37173
=> [core] Lock `@types/node` on v18

packages/x-date-pickers/src/internals/hooks/useField/useField.ts
Fix #9035
I thought it was a problem about the token parser, but no. It's the `onChange` which has a specific behavior when all tokens are selected.
This behavior has been added in #8330, such that when selecting the entire field by doing <kbd>Ctrl</kbd>+<kbd>A</kbd> pressing a key edit the first section.
This assumes that there is no `startSeparator` on the first/last `endSeparator` elements. shuch that when pressing 1 onchange get the pressed key (I'm using `||` to show selection range):
- `|hh:mm|` becomes `1` which is then transformed to `|01|:mm` by field code
- `it is |hh:mm|:00` becomes `it is 1:00` which not a valid value for `hh` so the field keep the previous state
The quick fix is to test if `onChange` has only one character
=> [pickers] Fix bug when fields have a unique section

packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts, packages/grid/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts
This PR avoids object allocations in `hydrateRowsMeta`. For large datasets, the costs are quite high. This is compounded by the fact that we create our objects with `{ ...spread }`, and `_objectSpread2` is very expensive.
The results below are obtained by clearing the filters in the same example as in #9120 
| --- | --- |
| ![Screenshot from 2023-05-25 22-45-53](https://github.com/mui/mui-x/assets/1423607/94bd2d23-3bfd-415d-9224-26504aac00e9) | ![Screenshot from 2023-05-25 22-42-43](https://github.com/mui/mui-x/assets/1423607/d31e23b8-23f8-4519-ac79-981d59c1d40b) |
=> [DataGrid] Avoid allocations in `hydrateRowsMeta`

docs/data/date-pickers/date-calendar/DateCalendarViews.js, docs/data/date-pickers/date-calendar/DateCalendarViews.tsx, docs/data/date-pickers/date-calendar/DateCalendarViews.tsx.preview
Noticed that https://mui.com/x/react-date-pickers/date-calendar/#views demo lists demos with different views, but only one demo uses the correct views in line with the used label.
Changed the used views to align with the ones listed in the labels. The same views are used in the `DatePicker` demo page as well.
=> [docs] Align `DateCalendar` demo views with labels

docs/data/data-grid/localization/data.json, docs/data/date-pickers/localization/data.json, scripts/localeNames.js
Address https://mui-org.slack.com/archives/C04U3R2V9UK/p1685503030459259
Or do you think that the report author suggested removing the parenthesis `()` as well? 🤔
=> [docs] Fix Norwegian locale typo

packages/grid/x-data-grid-premium/src/hooks/features/export/gridExcelExportInterface.ts, packages/grid/x-data-grid-premium/src/hooks/features/export/serializer/excelSerializer.ts
When specifying `excelOptions` -> `columnStyles` of the data grid's toolbar, I get the following error:
I believe not all properties are required so in my change I used `Partial` to improve this.
=> [DataGrid] refactor(DataGridPremium): improve grid excel export interface

packages/x-date-pickers/src/AdapterDayjs/AdapterDayjs.ts, packages/x-date-pickers/src/AdapterMoment/AdapterMoment.ts
Fixes #9174
`AdapterDateFns` and `AdapterDateFnsJalali` already passes the locale to the `startOfWeek` method
`AdapterLuxon` does not handle localized start of week
=> [pickers] Use the locale start of the week in `getWeekArray`

packages/x-date-pickers/src/MonthCalendar/MonthCalendar.tsx, packages/x-date-pickers/src/MonthCalendar/tests/MonthCalendar.test.tsx, packages/x-date-pickers/src/YearCalendar/YearCalendar.tsx, packages/x-date-pickers/src/YearCalendar/tests/YearCalendar.test.tsx
Fixes #9133 
Revert change made in https://github.com/mui/mui-x/pull/6034/files#diff-3d04258c1d5878605735157d4ee3e38af1a738cc4fc66d42727f04b7414f544cR168
These particular functions are never passed down to downstream components.
Using `useEventCallback` caused a function resolved before the current render to be called after the first render.
The regression has been introduced in `v6.0.0-alpha.0`.
=> [pickers] Fix `MonthCalendar` and `YearCalendar` disabled validation

docs/data/data-grid/demo/PopularFeaturesDemo.js, docs/data/data-grid/demo/PopularFeaturesDemo.tsx
Found in https://app.ahrefs.com/site-audit/3523498/70/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cpsi_request_status%2Cpsi_crux_cls_percentile%2Cpsi_crux_cls_category%2Cpsi_crux_fid_percentile%2Cpsi_crux_fid_category%2Cpsi_crux_lcp_percentile%2Cpsi_crux_lcp_category%2Cpsi_lighthouse_score%2Cpsi_lighthouse_cls_value%2Cpsi_lighthouse_tbt_value%2Cpsi_lighthouse_lcp_value%2Cdepth%2Ccompliant%2CincomingLinks%2Corigin&filterId=3bc4bee7603e9aee6c8c313b286e2a72&issueId=09a46610-1538-11ec-a251-0aa06bfc17da
It can also be seen in https://pagespeed.web.dev/analysis/https-mui-com-x-react-data-grid-demo/ugrve9dtg8?form_factor=desktop
I have added a min height of 1000px. This avoids the layout shift from the scrollbar and avoid seeing the footer.
Before: …
=> [docs] Reduce layout shift in grid demo

packages/grid/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx, packages/grid/x-data-grid-pro/src/tests/columns.DataGridPro.test.tsx, test/e2e/fixtures/DataGridPro/NotResize.tsx, test/e2e/index.test.ts
Closes #4777
Prevents click event that happen right after a column resize. They currently trigger a click on the column header (which changes the sorting) if the mouseup happens over the header.
=> [DataGridPro] Prevent click event on sorting after a resize

packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts, packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx
Fixes https://github.com/mui/mui-x/issues/8547#issuecomment-1570304743
I have no idea why the visual regressions were not reported in https://github.com/mui/mui-x/pull/8577
=> [DataGrid] Allow overflowing grid root element

docs/data/charts/axis/AxisWithComposition.js, docs/data/charts/axis/AxisWithComposition.tsx, docs/data/charts/stacking/StackOrderDemo.js, docs/data/charts/stacking/StackOrderDemo.tsx, packages/x-charts/src/XAxis/XAxis.tsx, packages/x-charts/src/YAxis/YAxis.tsx, packages/x-charts/src/internals/components/AxisSharedComponents.tsx
The code taken from hackathon was relying on the font size to place labels.
Instead I use:
- [`alignmentBaseline`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline) and [`textAnchor`](https://developer.mozilla.org/fr/docs/Web/SVG/Attribute/text-anchor) to place labels at the extremity of ticks
- use the `x` and `y` properties to place tet, to let devs use the `transform` property if they need it
For this kind of PR, Argos is super useful 😁
=> [charts] Improve axis label and ticks label alignements

docs/data/charts/axis/ScaleExample.js, docs/data/charts/axis/ScaleExample.tsx, docs/data/charts/axis/ScaleExample.tsx.preview, packages/x-charts/src/context/CartesianContextProvider.tsx, packages/x-charts/src/hooks/useTicks.ts
In previous PR, I introduced the D3 `nice()` function to round the default extremums values. For example, having the axis going from 0 to 200 when data varies between 2 and 185.
But this axis cleaning is don at the end of the process. So if user specify a `min` or `max` values, it will be override by this `nice()` function.
This PR has 2 commits:
1. first is a renaming to follow D3 naming convention:
- `domain` is in the values space
- `range` is in the drawing pace (the value in px used in the rendering)
2. the fix of the bug
The bug is especially visible in the following [demo](https://mui.com/x/react-charts/axis/#axis-sub-domain) since you can modify axis min/max values 1 by 1, but the axis will update 5 by 5 on a large screen.
=> [charts] Enforce axis `min`/`max` over the `nice()` method

packages/grid/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts, packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx, packages/grid/x-data-grid/src/tests/DataGrid.test.tsx
Closes #9264 
Avoid failing if the rows have ids like `constructor`.
=> [DataGrid] Fix row with ids matching Object prototype

docs/pages/_app.js
Fix the link in the docs header
Need to be added to v5 docs
=> [docs] Fix version redirect

docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md
Fixes #9271 
It might be obvious for some users that if `selectionModel` -> `rowSelectionModel` change is done, their corresponding types should also be updated `GridSelectionModel` -> `GridRowSelectionModel`, but some users may get confused with this. Also, since both these types old and renamed one are exported in v5 and v6, someone may be searching directly for it in the migration guide.
=> [DataGrid] Update data grid migration guide to include updated type

docs/data/introduction/licensing/licensing.md
Now that the [Next.js app folder is stable](https://nextjs.org/blog/next-13-4#nextjs-app-router), it makes more sense to document it.
~The 'use client' feels a bit like crap at this location, but I couldn't find any other API. I'm surprised Next.js doesn't have a global JavaScript injection point, typically for polyfills.~
Before: https://mui.com/x/introduction/licensing/#where-to-install-the-key
After: https://deploy-preview-8975--material-ui-x.netlify.app/x/introduction/licensing/#where-to-install-the-key
=> [docs] Improve Next.js license installation guide

docs/pages/_app.js
I landed here from:
when opening http://0.0.0.0:3001/x/introduction/.
=> [docs] Fix missing docs version warning

CHANGELOG.md, docs/data/data-grid/filtering/header-filters.md, docs/data/data-grid/filtering/multi-filters.md
The link to the header filter is broken, also add the missing plan icon in the header.
Side fix, the previews on the release page have design issues https://github.com/mui/mui-x/releases/tag/v6.6.0: sometimes no cursor, pixelization, hosted under a personal GitHub account not under the MUI org. I have also tried the big gif road rather than the video, seems to work.
Before: https://github.com/mui/mui-x/blob/master/CHANGELOG.md#660
After: https://github.com/oliviertassinari/mui-x/blob/19ee4a013f410559bfafc6bc6dc32e515bf999fe/CHANGELOG.md#660
Before: https://github.com/mui/mui-x/blob/master/CHANGELOG.md#v650
After: https://github.com/oliviertassinari/mui-x/blob/19ee4a013f410559bfafc6bc6dc32e515bf999fe/CHANGELOG.md#650
=> [docs] Fix grid header filter link

docs/data/date-pickers/date-calendar/DateCalendarServerRequest.js, docs/data/date-pickers/date-calendar/DateCalendarServerRequest.tsx
Closes #7331
There was an error in the [Dynamic Data Example](https://mui.com/x/react-date-pickers/date-calendar/#DateCalendarServerRequest.tsx ) which did not allow to highlight the first day in the month.
I implemented a simple fix so that the index 0 is now also allowed.
=> [docs] Fix `Date Calendar` dynamic data demo

docs/data/data-grid/events/events.json, packages/grid/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts, packages/grid/x-data-grid/src/hooks/features/clipboard/useGridClipboard.ts, packages/grid/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts, packages/grid/x-data-grid/src/models/events/gridEventLookup.ts, packages/grid/x-data-grid/src/utils/keyboardUtils.ts
This is an iteration on a couple of other PRs. These changes fixes two bugs:
1. <kbd>Option</kbd>+<kbd>V</kbd> doesn't work on https://mui.com/x/react-data-grid/clipboard/#clipboard-paste while it does now on https://deploy-preview-9220--material-ui-x.netlify.app/x/react-data-grid/clipboard/#clipboard-paste.
2. The paste shortcut on a Dvorak keyboard
=> [DataGrid] Polish shortcut logic

packages/grid/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts
This PR will enable the Actions columns on the DataGrid for tabbing, which is necessary for accessibility / keyboard-only users to make edits to a row.
Please see related issue for more context: https://github.com/mui/mui-x/issues/9250
=> [DataGrid] Fix tabbing between `actions` cells in edit mode

.circleci/config.yml, .codesandbox/ci.json, netlify.toml, packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx
Similar to https://github.com/mui/material-ui/pull/37173.
=> [core] Upgrade Node.js to v18 on CircleCI, CodeSandbox and Netlify

.github/workflows/l10n.yml
Came from https://github.com/mui/material-ui/pull/37604 to ensure consistency. This job runs only on `master` and `next` branches.
=> [core] Update to Node v18 for `l10n` GitHub CI

docs/data/data-grid/editing/BasicEditingGrid.js, docs/data/data-grid/editing/BasicEditingGrid.tsx, docs/data/data-grid/editing/BasicRowEditingGrid.js, docs/data/data-grid/editing/BasicRowEditingGrid.tsx, docs/data/data-grid/editing/DisableStopEditModeOnFocusOut.js, docs/data/data-grid/editing/DisableStopEditModeOnFocusOut.tsx, docs/data/data-grid/editing/FullFeaturedCrudGrid.js, docs/data/data-grid/editing/FullFeaturedCrudGrid.tsx, docs/data/data-grid/editing/FullFeaturedCrudGrid.tsx.preview, docs/data/data-grid/editing/IsCellEditableGrid.js, docs/data/data-grid/editing/IsCellEditableGrid.tsx, docs/data/data-grid/editing/ServerSidePersistence.js, docs/data/data-grid/editing/ServerSidePersistence.tsx, docs/data/data-grid/editing/StartEditButtonGrid.js, docs/data/data-grid/editing/StartEditButtonGrid.tsx, docs/data/data-grid/editing/editing.md
Based on user feedback* and [analytics](https://analytics.google.com/analytics/web/#/report/content-event-events/a106598593w159022482p160376982/_u.date00=20230313&_u.date01=20230327&_r.drilldown=analytics.eventCategory:demo,analytics.eventAction:expand&explorer-table.plotKeys=%5B%5D&explorer-table.filter=data-grid~2Fediting&explorer-table.rowStart=0&explorer-table.rowCount=25/).
> After a couple years of using the datagrid, this is my first need to edit.  I have to think 99 out of 100 developers just come here to find the best practice to simply edit a row and have it saved to a state variable.... or do something to commit the change.  If that's here, it's very hard to find as much of it is far more complicated that it needs to be.  I'm guessing someone else wrote this versus all your …
=> [docs] Improve and reorganize sections on editing page

README.md, docs/data/introduction/support/support.md
Since we are moving toward treating more each part of MUI as its own open-source project/product, to help them compete with community alternatives. We are making the developer feel like each project is more lazer focused on one problem and less "bloated".
=> [docs] Use the mui-x Stack Overflow tag

packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx
This 2px has been here since the very first version, e.g. https://material-ui-pickers-git-next-mui-org.vercel.app/demo/daterangepicker:
However, it feels horrendous. Instead, we can use 1px, it should be enough. This is what MD2 documents:
https://m2.material.io/components/date-pickers#desktop-pickers
Note that the majority of the date range pickers we benchmark again have no borders at all: https://mui-org.notion.site/Date-Range-Picker-component-271834fb7d274531a9c44286c1d23d9c?pvs=4
Preview: https://deploy-preview-9368--material-ui-x.netlify.app/x/react-date-pickers/date-range-picker/
This was very obvious on https://flights.teamout.com/, the date range picker UX on this page doesn't feel great.
=> [pickers] Reduce date range calendar vertical border width

docs/data/data-grid/components/components.md, docs/data/date-pickers/adapters-locale/adapters-locale.md, docs/data/date-pickers/calendar-systems/calendar-systems.md, docs/data/date-pickers/custom-components/custom-components.md, docs/data/date-pickers/fields/fields.md, docs/data/date-pickers/localization/localization.md, docs/data/date-pickers/validation/validation.md, docs/data/pages.ts, docs/pages/x/api/date-pickers/date-field.json, docs/pages/x/api/date-pickers/date-time-field.json, docs/pages/x/api/date-pickers/date-time-picker-tabs.json, docs/pages/x/api/date-pickers/localization-provider.json, docs/pages/x/api/date-pickers/multi-input-date-range-field.json, docs/pages/x/api/date-pickers/multi-input-date-time-range-field.json, docs/pages/x/api/date-pickers/multi-input-time-range-field.json, docs/pages/x/api/date-pickers/single-input-date-range-field.json, docs/pages/x/api/date-pickers/single-input-date-time-range-field.json, docs/pages/x/api/date-pickers/single-input-time-range-field.json, docs/pages/x/api/date-pickers/time-field.json
When browsing the docs, I believe that making the H1 of the page match with the side nav link that was clicked leads to a better UX. It becomes clear that the page that is now displayed is actually the page you clicked on. Otherwise, you might think you are on the wrong tab.
=> [docs] Sync h1 with sidenav link

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
We didn't have a PR template so I added one. In addition, I added a line in the contribution guide related to CLA. Hopefully, this will streamline the PR contributions a bit.
=> [core] Add PR template and update the contributions guide

packages/x-date-pickers/src/internals/hooks/useField/useField.ts, packages/x-date-pickers/src/internals/hooks/usePicker/usePickerViews.ts
Fixes #9326 
Calling the field selection before the field is focused and in different even loop cycles results in inconsistencies and Chrome not marking the selected section correctly, but it would work fine on Safari.
Calling them both in the same timeout results in consistent visual behavior, albeit with a slight flickering (visible input focusing and instant selected range selection).
=> [pickers] Fix field section selection on `DateTimePicker`

packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx, packages/x-date-pickers/src/internals/hooks/useField/useField.ts
Guys, just saw your [PR](https://github.com/mui/mui-x/pull/9385) for solving https://github.com/mui/mui-x/issues/9357, thought I might contribute my findings, since I think the underlying issue is still not solved. For example, let's say I have a managed datepicker with a value passed from the outside. If the value passed in changes, the internal query state is not cleared and the same problem can be observed that I've described in https://github.com/mui/mui-x/issues/9357.
In the issue @alexfauquette noted that the internal state could be cleared whenever...
> the value is updated for another reason than typing digits
This got me thinking a bit and I saw that you guys also keep track of a `referenceValue`, which, according to the docs, only changes, if...
> [...] It is updated whenever we …
=> [fields] Reset internal state when referenceValue changes

docs/data/data-grid/pagination/PageSizeAutoPremium.js, docs/data/data-grid/pagination/PageSizeAutoPremium.tsx, docs/data/data-grid/pagination/PageSizeAutoPremium.tsx.preview, docs/data/data-grid/pagination/pagination.md
There was no mention of Premium on the note about the default behavior of the `pagination` prop.
I changed the initial note into a section so it's available on the right-side navbar, added a demo using the prop and an explicit mention of the DataGridPremium so it's searchable on the page. 
https://deploy-preview-8759--material-ui-x.netlify.app/x/react-data-grid/pagination/
=> [DataGrid] Add section about enabling pagination on Pro and Premium

packages/grid/x-data-grid-pro/src/tests/treeData.DataGridPro.test.tsx, packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationSelector.ts
Closes #9402
The selector tries to index a rowTree that refers to new values with an old value.
=> [DataGridPro] checkboxSelection & treeData/grouping bug

docs/pages/_app.js
Fix the "productId" logic. Here are reproduction of the bugs:
1. See the source of https://mui.com/x/api/data-grid/grid-toolbar-quick-filter/
This prevents Algolia's crawler from correctly updating its index. After the fix https://deploy-preview-9451--material-ui-x.netlify.app/x/api/data-grid/grid-toolbar-quick-filter/
2. https://dashboard.algolia.com/apps/TZGZ85B9TB/analytics/no-results/material-ui?from=2023-06-17&to=2023-06-23&tags=product%3Aundefined
The date picker custom `<DemoContainer>` component is the most searched query with no results, but it's not labeled as being part of the date picker. It's currently `undefined`.
=> [docs] Fix productId logic

packages/x-date-pickers-pro/src/SingleInputDateRangeField/SingleInputDateRangeField.tsx, packages/x-date-pickers-pro/src/SingleInputDateTimeRangeField/SingleInputDateTimeRangeField.tsx, packages/x-date-pickers-pro/src/SingleInputTimeRangeField/SingleInputTimeRangeField.tsx, packages/x-date-pickers/src/DateField/DateField.tsx, packages/x-date-pickers/src/DateTimeField/DateTimeField.tsx, packages/x-date-pickers/src/TimeField/TimeField.tsx
Fixes #9467
Aligning the `onKeyDown` management with the multi-input range fields approach, where `onKeyDown` is passed to the `inputProps` instead of `InputProps` to avoid handling it when clicking while the focus is on an adornment.
=> [pickers] Handle `keyDown` only when input is focused

packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx
Fixes #9389 
This change results in a new compromise: we no longer scroll when selecting an already selected item.
Ant design also has the same compromise: https://ant.design/components/date-picker
=> [DateTimePicker] Scroll to Digital Clock section only when selection changes

packages/grid/x-data-grid-pro/src/hooks/features/columnPinning/useGridColumnPinning.tsx
Closes #9440 
Prevent an error from being thrown if a callback is called after the row container is unmounted.
Before: https://codesandbox.io/s/muidgridpro-pinnedcolumn-lazyloadroute-error-forked-73t2c6
After: https://codesandbox.io/s/muidgridpro-pinnedcolumn-lazyloadroute-error-forked-ng3cv4
=> [DataGridPro] Don't throw error in column pinning

docs/data/charts/funnel/funnel.md, docs/data/charts/gantt/gantt.md, docs/data/charts/heat-map/heat-map.md, docs/data/charts/pie/pie.md, docs/data/charts/radar/radar.md, docs/data/charts/sankey/sankey.md, docs/data/charts/tree-map/tree-map.md, docs/data/data-grid/column-groups/column-groups.md, docs/data/data-grid/pivoting/pivoting.md, docs/data/data-grid/row-grouping/row-grouping.md, docs/data/data-grid/row-ordering/row-ordering.md, docs/data/data-grid/row-spanning/row-spanning.md, docs/data/data-grid/tree-data/tree-data.md, docs/data/date-pickers/date-range-picker/date-range-picker.md, docs/data/date-pickers/date-time-range-picker/date-time-range-picker.md, docs/data/date-pickers/time-range-picker/time-range-picker.md
We have two waiting for upvotes warnings in the docs without corresponding GitHub issue: https://mui.com/x/react-data-grid/column-groups/#manage-group-visibility. This leads to developers asking questions like https://mui.zendesk.com/agent/tickets/9359. We now link #6651 and #9448.
Instead, let's link them all, I have used the opportunity to normalize the message.
=> [docs] Add missing upcoming flag without issue

docs/data/data-grid/master-detail/master-detail.md, docs/data/data-grid/row-recipes/DetailPanelOneExpandedRow.js, docs/data/data-grid/row-recipes/DetailPanelOneExpandedRow.tsx, docs/data/data-grid/row-recipes/DetailPanelOneExpandedRow.tsx.preview, docs/data/data-grid/row-recipes/row-recipes.md, docs/data/pages.ts, docs/pages/x/react-data-grid/row-recipes.js
Closes https://github.com/mui/mui-x/issues/7782
Adds a recipe based on https://github.com/mui/mui-x/issues/7782#issuecomment-1413545379
Preview: https://deploy-preview-9488--material-ui-x.netlify.app/x/react-data-grid/row-recipes/#one-expanded-detail-panel-at-a-time
=> [docs] Add a recipe limiting to one expanded detail panel at a time

docs/data/charts/styling/MuiColorTemplate.js, docs/data/charts/styling/MuiColorTemplate.tsx, packages/grid/x-data-grid-pro/src/tests/rowPinning.DataGridPro.test.tsx
I don't know why these tests often fail in JSDOM, and I don't want to waste more time investigating it.
Running these tests in the browser should be enough.
=> [test] Skip flaky row pinning tests in JSDOM

docs/data/data-grid/localization/data.json, packages/grid/x-data-grid/src/locales/esES.ts
Added Spanish strings that were either without stress marks or missing
=> [l10n] Improve Spanish (es-ES) locale

packages/grid/x-data-grid/src/components/cell/GridEditDateCell.tsx, packages/grid/x-data-grid/src/components/cell/GridEditInputCell.tsx, packages/grid/x-data-grid/src/hooks/features/editing/useGridEditing.ts, packages/grid/x-data-grid/src/models/api/gridEditingApi.ts
Closes #9475 
Before: https://codesandbox.io/s/blissful-scooby-t38hvj
After: https://codesandbox.io/s/reverent-microservice-wr4264
=> [DataGrid] Fix react 17 editing bug

packages/x-date-pickers/src/DigitalClock/DigitalClock.tsx, packages/x-date-pickers/src/DigitalClock/tests/DigitalClock.test.tsx
forward `classes` prop in `DigitalClock` component
=> [pickers] Forward digital clock classes

packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts, packages/grid/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts, packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx
Fixes https://github.com/mui/mui-x/issues/9550
Before: https://codesandbox.io/s/quiet-frost-3yn7ss
After: https://codesandbox.io/s/stoic-cherry-6nfdz7
Fixes https://github.com/mui/mui-x/pull/9516#issuecomment-1619996793
Before: https://codesandbox.io/s/maximum-call-stack-size-exceeded-zhz6dw
After: https://codesandbox.io/s/maximum-call-stack-size-exceeded-forked-wwvd53
=> [DataGrid] Fix `RangeError` when flex columns have duplicated `field` property

CHANGELOG.md, docs/public/_redirects
Today, we were talking about the Figma variable features and the struggle to know if the plans in this feature were available. This sparked this idea: What if we were to flatten the changelog to make it clear where the improvement is? Effectively, I'm continuing the discussion we started in https://www.notion.so/mui-org/How-to-display-the-changelogs-c8f46c2f2f9943d793b181aa53133785, going with Option A.
Here is a preview of what it could look like. The main objective for me is to help grow MUI X as a standalone open-source project, a step toward supporting Mantine, Chakra UI, Tailwind CSS, etc. as possible rendered layers. Without this change, developers might feel like MUI X is mostly paid features, but when you actually segment the changes, it becomes clear that the reality is.
--- …
=> [CHANGELOG] Clarify each plan

packages/grid/x-data-grid-premium/src/tests/license.DataGridPremium.test.tsx, packages/x-license-pro/src/generateLicense/generateLicense.test.ts, packages/x-license-pro/src/generateLicense/generateLicense.ts, packages/x-license-pro/src/utils/licensingModel.ts, packages/x-license-pro/src/verifyLicense/verifyLicense.test.ts, packages/x-license-pro/src/verifyLicense/verifyLicense.ts
`throw new Error('MUI: Invalid sales model');` doesn't make sense.
I have also used the opportunity to:
- remove dead code
- prepare the renaming from `subscription` to `annual`. We could use `subscription` in the future, but this would IMHO, also imply the need to have an active license in production
=> [license] Fix error terminology

packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerToolbar.tsx, packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx, packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx, packages/x-date-pickers/src/PickersDay/PickersDay.tsx, packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx, packages/x-date-pickers/src/internals/components/pickersToolbarClasses.ts, packages/x-date-pickers/src/themeAugmentation/themeAugmentation.spec.ts
Extract fixes done in #8851.
- Remove redundant "pen icon" styles as this feature has been removed in v6.
- Fix date range calendar selected day styling when a selected day is being dragged
- Remove unwanted `opacity` on selected day range days
=> [pickers] Fix date calendar issues

docs/data/data-grid/events/events.json, docs/data/data-grid/row-grouping/RowGroupingSetChildrenExpansion.js, docs/data/data-grid/row-grouping/RowGroupingSetChildrenExpansion.tsx, docs/data/data-grid/row-grouping/row-grouping.md, packages/grid/x-data-grid/src/models/events/gridEventLookup.ts
Closes #6335 
I wanted to add more things like `isExpanded` and `row` to the params of event as they could be useful in certain customizations, but this might be a breaking change for some users as the event is being used by some users and also used in [one](https://mui.com/x/react-data-grid/tree-data/#children-lazy-loading) of the demos. Recommendations are welcome.
=> [DataGrid] Make `rowExpansionChange` event public

docs/src/modules/components/InstallationInstructions.tsx, docs/src/modules/components/PickersRenderingInstructions.js, docs/src/modules/components/ToggleOptions.tsx, yarn.lock
This PR uses the remaining codes from https://github.com/mui/material-ui/pull/36766 to improve the installation instruction
When the screen get too small the toggle button groups transform into a select to have best of desktop and mobile experience
=> [docs] Improve the UI for pickers introduction

packages/x-date-pickers/src/AdapterDayjs/AdapterDayjs.ts
Fixes #9642 
Update the comment to avoid using `require` and thus avoid an issue on the "Vite land".
=> [pickers] Remove `require` usage in comment

docs/data/date-pickers/adapters-locale/adapters-locale.md, docs/data/date-pickers/base-concepts/base-concepts.md, docs/data/date-pickers/calendar-systems/calendar-systems.md, docs/data/date-pickers/custom-components/custom-components.md, docs/data/date-pickers/custom-field/custom-field.md, docs/data/date-pickers/custom-layout/custom-layout.md, docs/data/date-pickers/getting-started/getting-started.md, docs/data/date-pickers/overview/overview.md, docs/data/date-pickers/shortcuts/shortcuts.md, docs/data/date-pickers/timezone/timezone.md, docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md, docs/pages/x/api/date-pickers/index.md
Updating Date Picker usage to Title Case. 
For example, `Date picker` => `Date Picker`
Work on #9318
=> [docs] Fix Date Pickers usage to Title Case

packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts
This PR applies point 5 of #9120.
=> [DataGrid] Filtering performance: compile filter applier with eval

packages/grid/x-data-grid-pro/src/tests/export.DataGridPro.test.tsx, packages/grid/x-data-grid/src/hooks/features/export/serializers/csvSerializer.ts
Fixes https://github.com/mui/mui-x/issues/9322
=> [DataGrid] Fix CSV export for values containing double quotes

packages/grid/x-data-grid-pro/src/utils/tree/utils.ts
Fixes https://github.com/mui/mui-x/issues/8581
It's >3x faster for 10k top-level rows:
| ------ | ----- |
| <img width="879" src="https://github.com/mui/mui-x/assets/13808724/97f2adc4-545d-4cf1-a784-9264cd260985"> | <img width="894" src="https://github.com/mui/mui-x/assets/13808724/fa8fd72b-4e6c-493b-a6b9-56d5f21e6668"> |
v5: https://codesandbox.io/s/intelligent-lewin-j4yv2y?file=/demo.tsx
HEAD: https://codesandbox.io/s/funny-rui-nl4rs4??file=/demo.tsx
=> [DataGridPro] Improve tree data performance

docs/data/introduction/licensing/licensing.md
Add instruction to add the `NEXT_PUBLIC` prefix to environment variables.
The pain point was previously seen at:
https://mui.zendesk.com/agent/tickets/6989
https://deploy-preview-9575--material-ui-x.netlify.app/x/introduction/licensing/
=> [docs] Add additional note for license key installation on Next.js

docs/data/charts/overview/overview.md, docs/data/data-grid/getting-started/getting-started.md, docs/data/date-pickers/getting-started/getting-started.md, docs/src/modules/components/InstallationInstructions.tsx
Adding the support of pnpm in MUI X 
Fix #9699 
https://deploy-preview-9707--material-ui-x.netlify.app/x/react-data-grid/getting-started/
=> [docs] Add pnpm installation instructions for MUI X

.circleci/config.yml
Same as https://github.com/mui/material-ui/pull/38039. In most cases, it's not needed, but it sounds simpler to blindly apply the same code, in case of a strange behavior.
=> [test] Fail the CI when new unexpected files are created

docs/data/data-grid/components/components.md
We got this feedback recently:
>The code example isn't correct. You should add
>> import '@mui/x-data-grid-pro'
>
> to the augmentation file. It won't work otherwise.
While I couldn't reproduce the issue, it makes sense to augment the package that you actually use.
Preview: https://deploy-preview-9668--material-ui-x.netlify.app/x/react-data-grid/components/#custom-slot-props-with-typescript
=> [docs] Differentiate between packages in `slotProps` docs

packages/grid/x-data-grid/src/components/GridRow.tsx, packages/grid/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts, packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx
Fixes https://github.com/mui/mui-x/issues/8042
Closes https://github.com/mui/mui-x/pull/8060
Before: https://codesandbox.io/s/relaxed-galileo-sl75wd?file=/demo.js
After: https://codesandbox.io/s/happy-khayyam-s57wm2?file=/demo.js
=> [DataGrid] Fix row click propagation causing error in nested grid

packages/x-license-pro/src/Watermark/Watermark.tsx, packages/x-license-pro/src/useLicenseVerifier/useLicenseVerifier.test.tsx, packages/x-license-pro/src/useLicenseVerifier/useLicenseVerifier.ts, packages/x-license-pro/src/utils/licenseErrorMessageUtils.ts, packages/x-license-pro/src/utils/licenseStatus.ts, packages/x-license-pro/src/verifyLicense/verifyLicense.test.ts, packages/x-license-pro/src/verifyLicense/verifyLicense.ts, scripts/x-license-pro.exports.json
A continutation of #9135.
- During the first 30 days, you only get a console.error, as before.
- After 30 days, you get this:
Effectively, if you are doing SSR, you can't build anymore, you would need to remove the license key. I think that the timing for this makes sense now. Developers can opt into the perpetual plan if they prefer this license model.
I worked a bit on #1364 at the same time.
=> [license] Throw in dev mode after 30 days

docs/data/date-pickers/date-calendar/date-calendar.md, docs/data/date-pickers/date-field/date-field.md, docs/data/date-pickers/date-range-calendar/date-range-calendar.md, docs/data/date-pickers/date-range-field/date-range-field.md, docs/data/date-pickers/date-range-picker/date-range-picker.md, docs/data/date-pickers/date-time-field/date-time-field.md, docs/data/date-pickers/date-time-picker/date-time-picker.md, docs/data/date-pickers/date-time-range-field/date-time-range-field.md, docs/data/date-pickers/digital-clock/digital-clock.md, docs/data/date-pickers/time-clock/time-clock.md, docs/data/date-pickers/time-field/time-field.md, docs/data/date-pickers/time-picker/time-picker.md, docs/data/date-pickers/time-range-field/time-range-field.md
Only the [Date Picker](https://mui.com/x/react-date-pickers/date-picker/#uncontrolled-vs-controlled-value) page seems to currently have a separate `uncontrolled vs controlled` section (heading).
Applied the same section (heading) approach to all the picker component pages.
=> [docs] Align pickers `uncontrolled vs controlled` sections

docs/pages/_app.js
The codesandbox generated by preview were not using the code from the PR but the latest release
From https://github.com/mui/mui-x/pull/9744#pullrequestreview-1544784552
https://codesandbox.io/s/lyqllr?file=/demo.tsx
=> [core] Use PR charts version in preview

docs/data/data-grid/localization/data.json, packages/grid/x-data-grid/src/locales/fiFI.ts
Added Finnish translation for columnMenuManageColumns
=> [DataGrid][l10n] Improve Finnish (fi-FI) locale

packages/x-date-pickers/src/DigitalClock/DigitalClock.tsx
closes #9794 
Removing the `endOfDate` from the `timeOptions` array, as it introduces invalid values for different `timeSteps`. 
- if `timeStep={60}`: https://mui.com/x/react-date-pickers/digital-clock/#skip-rendering-disabled-options
- if `timeStep={1}`:
=> [pickers] Remove the `endOfDate` from `DigitalClock` timeOptions

packages/x-license-pro/src/useLicenseVerifier/useLicenseVerifier.ts, packages/x-license-pro/src/verifyLicense/verifyLicense.test.ts, packages/x-license-pro/src/verifyLicense/verifyLicense.ts
#9701 was a bit too ambitious. There will be cases where developers run their CI and the data grid tests alongside them for completely unrelated parts of their product. It wouldn't be fair to break the build for e.g. vitest uses `process.env.NODE_ENV = test`. This was surfaced during my weekly call with @mbrookes.
=> [license] Only throw in dev mode

packages/x-date-pickers-pro/src/internals/utils/valueManagers.ts, packages/x-date-pickers/src/DesktopDatePicker/tests/field.DesktopDatePicker.test.tsx, packages/x-date-pickers/src/internals/utils/valueManagers.ts
Fixes #9818
When clearing a section, the value passed to `onChange` is an invalid date.
For these date, we can't reliably set the timezone, so I'd suggest treating them as `null` and ignore there timezone.
=> [fields] Fix section clearing with timezone

packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx, packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx, packages/x-date-pickers/src/internals/hooks/useDefaultReduceAnimations.ts, packages/x-date-pickers/src/internals/index.ts, packages/x-date-pickers/src/internals/utils/defaultReduceAnimations.ts
Fixes #9740
- Add media query detection for reduced motion when resolving the default `reduceAnimations` prop value
- Fix `DateCalendar` props defaulting order
=> [pickers] Use device motion reduction preference

packages/x-date-pickers-pro/src/MobileDateRangePicker/MobileDateRangePicker.tsx
Fixes #9851
I probably forgot to remove this spreading when the `sx` and `className` management was moved inside the shared files.
=> [pickers] Fix `sx` and `className` props on `MobileDateRangePicker`

packages/x-charts/package.json
I created a basic nextjs with charts to reproduce [this issue comment](https://github.com/mui/mui-x/issues/9556#issuecomment-1657232487). It failed to build because of missing TS definition.
https://github.com/alexfauquette/charts-next-test
The modification in this PR made directly in the `node_module` allowed to build
=> [charts] Add TS definition to the exported elements

docs/data/data-grid/editing/FullFeaturedCrudGrid.js, docs/data/data-grid/editing/FullFeaturedCrudGrid.tsx, docs/data/data-grid/editing/FullFeaturedCrudGrid.tsx.preview, docs/data/data-grid/editing/ValidateServerNameGrid.js, docs/data/data-grid/editing/ValidateServerNameGrid.tsx, docs/data/data-grid/editing/ValidateServerNameGrid.tsx.preview, docs/data/data-grid/recipes-editing/MultilineEditing.js, docs/data/data-grid/recipes-editing/MultilineEditing.tsx, docs/data/data-grid/recipes-editing/MultilineEditing.tsx.preview, docs/data/data-grid/recipes-row-grouping/recipes-row-grouping.md, docs/data/pages.ts
https://mui-org.slack.com/archives/C04U3R2V9UK/p1690394764752449
These demos seem to still work correctly. Ok, there are warnings in the console to fix but it seems unrelated, only that we don't always use Material UI correctly.
I have found a few more instances where we are confusing users when it comes to MIT vs. Pro.
=> [docs] Fix demo using Pro while it's MIT

packages/x-date-pickers/src/internals/hooks/useField/useField.ts, test/e2e/index.test.ts
This fix resolves the issue mentioned here: https://github.com/mui/mui-x/issues/9165#issuecomment-1655702729
Calling `fill('04/11/2022')` (in playwright and possibly other e2e frameworks) on the pickers field does nothing because we explicitly check only the `event.target.value`.
In such case `event.target.value` will equal `04/11/2022/MM/YYYY`, which is not valid as per our code and nothing happens.
With the change done here, we'd use the `event.nativeEvent.data`, which would contain the whole `04/11/2022` and update the value using it, instead of the regular section updating process.
When using regular editing by typing characters with the keyboard results in `event.nativeEvent.data` having only the changed character.
=> [fields] Correctly handle events with a complete value insertion

packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts
Fixes #9900
Using `endOfYear` in the field lead to bugs due to the following inconsistency in dayjs:
```tsx
const today = dayjs.tz(undefined, 'Europe/Lisbon')!;
const endOfYear = today.endOf('year');
console.log(endOfYear.hour())
```
Weirdly, I could not reproduce the dayjs strange behavior on the testing environment :thinking:
=> [fields] Fix hours editing on dayjs with timezone and DST

packages/grid/x-data-grid-premium/src/hooks/features/aggregation/wrapColumnWithAggregation.tsx
Closes #9876
Remove a `!` and handle the null case.
I find that `!` often ends up causing bugs down the line. I wonder if there is a set of rules we could enfore for its usage that would protect us more from bugs.
Before: https://codesandbox.io/s/frosty-burnell-smdsgs?file=/Demo.tsx
After: https://codesandbox.io/s/vibrant-wu-c9gjj7?file=/Demo.tsx
=> [DataGrid] `getCellAggregationResult`: handle null rowNode case

docs/data/migration/migration-pickers-v5/migration-pickers-v5.md
This migration is a bit ambiguous.
Hopefully clarifying the code examples with comments will make it a bit more clear for whoever doesn't bother reading the paragraph.
=> [docs] Clarify the `shouldDisableClock` migration code options

docs/data/charts/axis/AxisWithComposition.js, docs/data/charts/axis/AxisWithComposition.tsx, docs/data/charts/components/BasicScaleDemo.js, docs/data/charts/components/BasicScaleDemo.tsx, docs/data/charts/components/ScaleDemo.js, docs/data/charts/components/ScaleDemo.tsx, docs/data/charts/stacking/StackOrderDemo.js, docs/data/charts/stacking/StackOrderDemo.tsx, packages/x-charts/src/ChartsLegend/ChartsLegend.tsx, packages/x-charts/src/PieChart/PieArcLabel.tsx, packages/x-charts/src/internals/components/AxisSharedComponents.tsx
Fixes #9929 
- Use `dominantBaseline` instead of `alignmentBaseline`. The `alignmentBaseline` shouldn't work on `text` elements as per the spec.
- Remove explicit `PieArcLabel` alignment as it didn't seem to do anything
- Fix typo
=> [charts] Fix label and tick alignment

.github/workflows/ensure-triage-label.yml
For context: https://www.notion.so/mui-org/GitHub-Action-to-add-need-triage-label-if-none-is-present-e6357dacba7947a1879d684c7bb63939?d=4912f8bad6af466783a3ef21ac71bad2
=> [core] Port GitHub workflow for ensuring triage label is present

packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx, packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClock.tsx, packages/x-date-pickers/src/MultiSectionDigitalClock/tests/describes.MultiSectionDigitalClock.test.tsx, packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx, packages/x-date-pickers/src/internals/utils/date-utils.ts, packages/x-date-pickers/src/models/adapters.ts, test/utils/pickers/viewHandlers.ts
Fixes #9977
The `getMeridiemText` did not have the same behavior across adapters.
It can be replaced by an adapter-agnostic method.
=> [pickers] Always respect locale when formatting meridiem

packages/x-charts/src/themeAugmentation/components.d.ts, packages/x-charts/src/themeAugmentation/overrides.d.ts, packages/x-charts/src/themeAugmentation/themeAugmentation.spec.ts
Created from: https://github.com/mui/mui-x/pull/9994#discussion_r1290246220
- Remove `ChartsXAxis` and `ChartsYAxis` `styleOverrides` as they are not used. Only the `ChartsAxis` is used globally.
- Remove `never` entries (same change as in https://github.com/mui/mui-x/pull/9978/files#diff-099ff841d1bc7939194814f7348976c6c1eb34f250eb792e93ef4bd2781851f8)
=> [charts] Remove not functional component `styleOverrides`

docs/data/charts/stacking/StackOffsetDemo.js, docs/data/charts/stacking/StackOffsetDemo.tsx, docs/data/charts/stacking/StackOrderDemo.js, docs/data/charts/stacking/StackOrderDemo.tsx, docs/data/charts/styling/MuiColorTemplate.js, docs/data/charts/styling/MuiColorTemplate.tsx, docs/data/charts/tooltip/ElementHighlights.js, docs/data/charts/tooltip/ElementHighlights.tsx, docs/data/charts/tooltip/Interaction.js, docs/data/charts/tooltip/Interaction.tsx, docs/data/data-grid/accessibility/accessibility.md, docs/data/data-grid/master-detail/DetailPanelAutoHeight.js, docs/data/data-grid/master-detail/DetailPanelAutoHeight.tsx, docs/data/data-grid/row-height/ExpandableCells.js, docs/data/data-grid/row-height/ExpandableCells.tsx, docs/src/modules/components/ToggleOptions.tsx
On the surface level, it's wasteful to render a Box to not use it (a small perf hit) 
Now, in longer terms, we have a few opportunities, from the most short-term win to the most long-term:
0. The change done here.
1. We could have a warning that tells us when we use a Box without any prop, so we can't regress on 0.
2. We could have a plugin that automatically transforms the Box into a div at built-time, so we get the performance win, while also not having to add/remove the Box import
3. We could fix https://github.com/mui/material-ui/issues/23220, the Box abstraction is annoying, all these `</Box>` closing tags tells you nothing. It would be much clearer if we could use the native element directly or the class name directly like in https://panda-css.com/docs/utilities/spacing#all-sides. …
=> [core] Remove unnecessary Box

packages/grid/x-data-grid-pro/src/components/GridDetailPanel.tsx
To illustrate one use case where `!` is optimal, related to https://github.com/mui/mui-x/pull/9915#issuecomment-1667943314
=> [DataGrid] Unhide potential ref binding issue

packages/x-date-pickers/src/internals/components/PickersToolbar.tsx
Fixes #9990 
The content wrapping `Grid` container parent seems useless and error-prone, because it requires the children to be `Grid` items for correct layout.
Styling needs seem to be easily achievable with just some extra CSS.
=> [pickers] Replace `Grid` toolbar component with a styled `div`

packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx, packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts
Fixes #3154 
- Before: https://codesandbox.io/s/unruffled-bird-hn429h?file=/Demo.tsx
- After: https://codesandbox.io/s/confident-kalam-52944q?file=/Demo.tsx
**Options that were available:**
1. Limit print export to 100 rows and add an explicit warning (would not work great with "Free Forever" MIT licensing, or would it? 🤔 CC @joserodolfofreitas)
2. ✅ Make Grid think during the export that it doesn't have 100 rows per page restriction (by modifying the signature prop manually, isn't very clean, but works)
Let me know if you have other ideas in mind.
=> [DataGrid] Allow print export for more than 100 rows

packages/x-date-pickers/src/internals/components/PickersPopper.tsx
Fixes #10006 
The placement is `top-start` when the popper opens to the top, because of that the conditional style did not work.
Preview: https://deploy-preview-10069--material-ui-x.netlify.app/x/react-date-pickers/
=> [pickers] Fix to `transform-origin` when popper opens to `top`

packages/x-charts/package.json
Fix https://github.com/mui/mui-toolpad/pull/2500
=> [charts] Fix import issue

docs/src/modules/components/DemoPropsForm.tsx, yarn.lock
Benefits from the merged https://github.com/mui/material-ui/pull/38579 and https://github.com/mui/mui-x/pull/10026 to properly generate plan icon link titles
=> [core] Bump monorepo

docs/data/pages.ts
To simplify the distinction between docs pages that are common to most of the components and the components themself, I propose to reorganize the menu. Part of #10075
A first group "common feature" with most used features: validation, lifecycle, and shortcuts
Identify all components in a group
Replace the two accordion by a subsection
=> [docs] Reorganize the page menu

packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts, packages/grid/x-data-grid/src/tests/columns.DataGrid.test.tsx
Fixes https://github.com/mui/mui-x/issues/5970#issuecomment-1679498700
=> [DataGrid] Fix `valueFormatter` being persisted on column type change

docs/data/charts/overview/overview.md, docs/data/charts/tooltip/BandHighlight.js, docs/data/charts/tooltip/BandHighlight.tsx, docs/data/charts/tooltip/tooltip.md
I have tried `import { Tooltip } from '@mui/x-charts/Tooltip';` but it didn't work. ChartTooltip is what works, and also what feels "right" in a global namespace.
Change tested with:
```diff
diff --git a/docs/data/charts/overview/Combining.tsx b/docs/data/charts/overview/Combining.tsx
index 5f2a25250..060bbfd15 100644
--- a/docs/data/charts/overview/Combining.tsx
+++ b/docs/data/charts/overview/Combining.tsx
@@ -1,6 +1,8 @@
import { BarPlot } from '@mui/x-charts/BarChart';
import { LinePlot } from '@mui/x-charts/LineChart';
+import { ChartsTooltip } from "@mui/x-charts/ChartsTooltip";
+import { ChartsAxisHighlight } from "@mui/x-charts/ChartsAxisHighlight";
import { ChartContainer } from '@mui/x-charts/ChartContainer';
import { AllSeriesType } from …
```
=> [docs] Fix wrong chart tooltip reference

docs/data/charts/bars/bars.md, docs/data/charts/funnel/funnel.md, docs/data/charts/gantt/gantt.md, docs/data/charts/heat-map/heat-map.md, docs/data/charts/lines/lines.md, docs/data/charts/pie/pie.md, docs/data/charts/radar/radar.md, docs/data/charts/sankey/sankey.md, docs/data/charts/scatter/scatter.md, docs/data/charts/sparkline/sparkline.md, docs/data/charts/tree-map/tree-map.md
Per the following search volume data, I think we should change the SEO title.
https://app.ahrefs.com/keywords-explorer/list/new/db2c322fa1f3891b3d2c32da458fe4a5/google/us/overview
on this pages, and the other chart pages.
Preview: https://deploy-preview-10170--material-ui-x.netlify.app/x/react-charts/gantt/
=> [docs] Improve chart SEO

docs/next.config.js, docs/pages/_app.js
Fixes https://github.com/mui/mui-x/issues/9951#issuecomment-1699626297
=> [docs] Add tree view nav item

docs/data/date-pickers/custom-components/custom-components.md, docs/data/date-pickers/date-picker/date-picker.md, docs/data/date-pickers/date-range-picker/date-range-picker.md, docs/data/date-pickers/date-time-picker/date-time-picker.md, docs/data/date-pickers/time-picker/time-picker.md
Address idea discussed in https://mui-org.slack.com/archives/C04U3R2V9UK/p1693305205544659?thread_ts=1693304702.501099&cid=C04U3R2V9UK
Add some missing ending dots (`.`) that I noticed.
=> [docs] Add link to `custom layout` page

packages/x-date-pickers/src/internals/demo/DemoContainer.tsx
Fixes #10106 
Apply the least intrusive improvement of adding a JSDoc explaining the intent of these components.
I'm not sure we should start renaming the components and possibly causing even more confusion at this stage. 🤔 🤷
=> [docs] Add `DemoContainer` and `DemoItem` JSDoc

docs/data/data-grid/filtering/customization.md, packages/grid/x-data-grid/src/models/colDef/gridColDef.ts
As I understand it, this property has no effect since #7309. I have noticed the issue looking at a date formatting issue with Toolpad: https://github.com/mui/mui-toolpad/blob/32d14b33cd296b204a1ce9b3199035524bd751db/packages/toolpad-components/src/DataGrid.tsx#L285
But the docs look wrong too: https://mui.com/x/react-data-grid/filtering/customization/#custom-column-types.
=> [DataGrid] Fix custom column docs, remove legacy `extendType`

docs/data/charts/overview/overview.md, docs/data/date-pickers/date-calendar/date-calendar.md, docs/data/date-pickers/date-field/date-field.md, docs/data/date-pickers/date-picker/date-picker.md, docs/data/date-pickers/date-time-field/date-time-field.md, docs/data/date-pickers/date-time-picker/date-time-picker.md, docs/data/date-pickers/overview/overview.md
According to ahrefs, it seems that "react chart" is the main query developers uses to find a charting library. See https://app.ahrefs.com/keywords-explorer/google/us/overview?keyword=react%20charts vs. https://app.ahrefs.com/keywords-explorer/google/us/overview?keyword=react%20chart. I see more clicks for "react chart" than "react charts", we also see a blog post that compare chart libraries to rank first for "react chart". So it feels like the query to optimize for.
According to Moz, we have a couple of opportunities to make the page rank higher: https://analytics.moz.com/pro/research/page-grader?keyword=react%20chart&url=https%3A%2F%2Fmui.com%2Fx%2Freact-charts%2F. 
This PR acts on these opportunities.
I believe we have the wrong page ranking for the "react date picker" query. We want …
=> [docs] Polish page for SEO

packages/x-charts/package.json, packages/x-charts/src/BarChart/BarElement.tsx, packages/x-charts/src/LineChart/AreaElement.tsx, packages/x-charts/src/LineChart/LineElement.tsx, packages/x-date-pickers-pro/README.md, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/README.md, packages/x-date-pickers/package.json, packages/x-tree-view/README.md, packages/x-tree-view/package.json, yarn.lock
There is no singleton in @mui/base, no need to have it as a peer dependency. Along the way, I added a missing dependency for the charts.
I have noticed the issue installing Toolpad:
See https://github.com/mui/mui-x/pull/8590#issuecomment-1511226153 for a previous discussion on this. I have seen the change listed in #7902 but I don't see how it could be a breaking change.
---
Side note:
- `import X from '@mui/base'` should be banned, it pulls in everything. It should be imported from the lower level.
- `import X from '@mui/utils'` should be banned in MUI X (unless there is a really good reason). It's a private npm repository for Base UI and MUI System. Developers who would look at how to add their own components should be able to do such with public packages. They might check MUI X to see …
=> [core] Move @mui/base from peer dependency to dependency

package.json, yarn.lock
I discovered it while checking https://github.com/mui/mui-x/pull/9622 and seeing that after a major bump, we'd be left with a couple of `prettier` major versions.
I've checked that `mui-x` does not seem to use this package, hence, it seems safe to remove it.
=> [core] Remove unused `babel-plugin-tester` package

README.md, docs/data/introduction/installation/installation.md, docs/data/introduction/overview/overview.md, docs/data/pages.ts, docs/data/tree-view/getting-started/FirstComponent.js, docs/data/tree-view/getting-started/FirstComponent.tsx, docs/data/tree-view/getting-started/FirstComponent.tsx.preview, docs/data/tree-view/getting-started/getting-started.md, docs/pages/x/react-tree-view/getting-started.js
I am moving "Getting Started" above "Overview" in the nav bar because for now "Overview contains all the doc of the Tree View and should be read after "Getting Started".
But once we move this doc to new pages and we build an actual "Overview" page that only introduces the component, I will move it back in 1st position.
I think it's worth creating the "Getting Started" page now to have a clear installation guide just like we have on other components
=> [docs] Add a Getting Started page for the Tree View

docs/data/charts/pie-demo/PieChartWithCenterLabel.js, docs/data/charts/pie-demo/PieChartWithCenterLabel.tsx, packages/x-charts/package.json
Part of #10195
Adding @Janpot as a preferred reviewer as he approved https://github.com/mui/mui-x/pull/10111, which might be related.
Ended up only fixing the demo imports.
The root cause is covered with https://github.com/mui/mui-x/pull/10272
=> [docs] Fix charts demo using too deep import

packages/x-charts/package.json
At the moment we don't have a working commonjs export for `@mui/x-charts`. We're using this alpha package to test the waters in the community about support for ESM modules. As such it makes sense to remove the non-working `require` condition, and supply a `default` condition as a fallback. Alternatively we could opt for removing the `import` condition altogether and just keeping `default`.
Closes https://github.com/mui/mui-x/issues/10257
Closes #10195
* https://deploy-preview-10272--material-ui-x.netlify.app/x/react-charts/bars/
* https://codesandbox.io/s/jsttrw?file=/Demo.tsx
=> [charts] Remove require condition from package.json exports

docs/data/tree-view/overview/BarTreeView.js, docs/data/tree-view/overview/BarTreeView.tsx, docs/data/tree-view/overview/BarTreeView.tsx.preview, docs/data/tree-view/overview/ControlledTreeView.js, docs/data/tree-view/overview/ControlledTreeView.tsx, docs/data/tree-view/overview/CustomizedTreeView.js, docs/data/tree-view/overview/CustomizedTreeView.tsx, docs/data/tree-view/overview/DisabledTreeItems.js, docs/data/tree-view/overview/DisabledTreeItems.tsx, docs/data/tree-view/overview/FileSystemNavigator.js, docs/data/tree-view/overview/FileSystemNavigator.tsx, docs/data/tree-view/overview/FileSystemNavigator.tsx.preview, docs/data/tree-view/overview/IconExpansionTreeView.js, docs/data/tree-view/overview/IconExpansionTreeView.tsx, docs/data/tree-view/overview/IconExpansionTreeView.tsx.preview, docs/data/tree-view/overview/MultiSelectTreeView.js, docs/data/tree-view/overview/MultiSelectTreeView.tsx, docs/data/tree-view/overview/RichObjectTreeView.js, docs/data/tree-view/overview/RichObjectTreeView.tsx, docs/data/tree-view/overview/RichObjectTreeView.tsx.preview, docs/data/tree-view/overview/overview.md
I notice on #10255 that https://mui.com/x/react-tree-view/#custom-icons-border-and-animation demos is broken:
https://github.com/mui/mui-x/assets/3165635/36c97bcc-e8be-4a58-98ca-78d032942d51
1. It animates on load while it shouldn't. It can be solved like this https://github.com/pmndrs/react-spring/issues/485#issuecomment-460409296.
2. It creates an overflow scrollbar. It can be solved with `overflowX: hidden`, see how even with an overflow y, it continues to work:
https://github.com/mui/mui-x/assets/3165635/680cde4e-6de8-44b9-b3cb-8598129951fb
---
Along the way, I improved a bit in the other demos:
- Use less vertical space when possible
- Use minHeight over height in the case we add more items in the demos and forgot about this property (same for developer who copy the demos)
- Use …
=> [docs] Improve Tree View demos

packages/x-tree-view/src/TreeItem/TreeItem.tsx
1. Open https://mui.com/x/react-tree-view/
2. Open the first demo in codesandbox https://codesandbox.io/s/confident-sammet-2m3vhd
Only `CssBaseline` changes the box-sizing globally https://mui.com/material-ui/react-css-baseline/#layout (I imagine only used by evergreen projects). So depending on how your app is configured the component will break.
https://tailwindcss.com/docs/box-sizing talks a bit about the concept as well.
We use the same trick in all the other Material UI components where it's needed.
I found this by pure luck, I wanted to test the playground http://0.0.0.0:3000/playground/.
=> [TreeView] Fix box-sizing dependency

docs/data/charts/bar-demo/PositiveAndNegativeBarChart.js, docs/data/charts/bar-demo/PositiveAndNegativeBarChart.tsx, packages/x-charts/src/context/CartesianContextProvider.tsx, packages/x-charts/src/models/axis.ts
Fixes #10196 
Also, increase the `categoryGapRatio` to `0.2` from `0.1` as the current default seems somewhat cramped. 🤷
Preview: https://deploy-preview-10317--material-ui-x.netlify.app/x/react-charts/bars/#basics
=> [charts] Add default `barGapRatio` and increase `categoryGapRatio`

docs/data/introduction/licensing/licensing.md
Fix https://mui.com/x/introduction/licensing/#1-missing-license-key layout shift when loading.
---
**Off-topic** for @mui/docs-infra and @Janpot who worked a bit on the problem in the past.
We could likely solve this at the route by adding the width and height property right from the `parseMarkdown` file. It runs in a webpack loader. I mean, I guess we could use https://www.npmjs.com/package/image-size like Next.js does https://www.notion.so/mui-org/Docs-infra-Images-solution-30e78dbf24744ed5b570027656139092?pvs=4#ce8c7d593c9746e1aed59a5409f2a81b. I think this could also apply to `DocsImage.tsx` if we make it built-in. 
I would want to benchmark this though, I hope reading images in the filesystem isn't too slow. Because otherwise, we could do this in a script, so it gets cashed. But …
=> [docs] Fix image layout shift

packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx, packages/x-date-pickers/src/DesktopDatePicker/tests/DesktopDatePicker.test.tsx, packages/x-date-pickers/src/DesktopDateTimePicker/tests/DesktopDateTimePicker.test.tsx, packages/x-date-pickers/src/MonthCalendar/MonthCalendar.tsx, packages/x-date-pickers/src/MonthCalendar/MonthCalendar.types.ts, packages/x-date-pickers/src/MonthCalendar/PickersMonth.tsx, packages/x-date-pickers/src/MonthCalendar/tests/MonthCalendar.test.tsx, packages/x-date-pickers/src/MonthCalendar/tests/describes.MonthCalendar.test.tsx, packages/x-date-pickers/src/YearCalendar/PickersYear.tsx, packages/x-date-pickers/src/YearCalendar/YearCalendar.tsx, packages/x-date-pickers/src/YearCalendar/YearCalendar.types.ts, packages/x-date-pickers/src/YearCalendar/tests/YearCalendar.test.tsx, packages/x-date-pickers/src/YearCalendar/tests/describes.YearCalendar.test.tsx
Fixes #9916 
Fixes #10141
I've looked into replicating the role structure that the DayCalendar has and it seems that it's not really possible without a breaking change.
The structure needs to include a `grid -> row -> cell` structure to work properly.
We can't introduce such a structure without a breaking change, because that would change the DOM structure and possibly impact someone depending on the current structure.
The simplest and still logical solution seemed to use `radiogroup` role as the behavior of the `YearCalendar` and `MonthCalendar` components is essentially just that - a group of radio buttons from which only one can be selected at a time.
I've looked into all possible solutions I could think of that would avoid a **breaking change** (not changing the role) but to no avail. …
=> [pickers] Fix `YearCalendar` and `MonthCalendar` a11y

packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts
Fixes #10056 
Hide `eval` calls so bundlers can minify.
| --- | --- |
| ![Screenshot from 2023-09-13 07-20-32](https://github.com/mui/mui-x/assets/1423607/4ffa4e2e-2f42-44e0-94dc-330f06537eae) | ![Screenshot from 2023-09-13 07-19-44](https://github.com/mui/mui-x/assets/1423607/2696a019-e0b4-47bc-8dc8-4d3521c4832f) |
=> [datagrid] Hide `eval` from bundlers

packages/grid/x-data-grid-pro/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx
Fixes #10325 
- Before: https://codesandbox.io/s/musing-lake-9ltjdm?file=/Demo.tsx
- After: https://codesandbox.io/s/trusting-ellis-rlqrm3
The bug surfaced after https://github.com/mui/mui-x/pull/9712, the reason is the same as in https://github.com/mui/mui-x/issues/8119, i.e. till a valid filter item is defined for a column, a new default filter item is being generated on every render which is causing the [useEffect](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputValue.tsx#L58) in the GridFilterItemValue to be called unnecessarily hence removing the first typed character from the header filter.
**Test:** I didn't manage to reproduce the issue, probably it's not re-rendering that often in test env 🤔
=> [DataGridPro] Make default filter items have stable references in header filters

.github/workflows/issue-cleanup.yaml
Closes #10340
Remove the checkboxes from new issues' body. I have hardcoded the strings, seems good enough.
Result: https://github.com/romgrk/mui-test-issue-cleanup/issues/3
=> [core] Cleanup issues body

packages/grid/x-data-grid/src/components/cell/GridActionsCellItem.tsx
Fixes #4654
Fix typing, add `component`.
https://github.com/mui/mui-x/issues/4654#issuecomment-1119956263
=> [datagrid] Fix typing of GridActionsCellItem

docs/data/data-grid/accessibility/GridAriaV7.js, docs/data/data-grid/accessibility/GridAriaV7.tsx, docs/data/data-grid/accessibility/GridAriaV7.tsx.preview
I noticed this during the monthly meeting, this feels simpler, and I think compatible with "The value of ariaV7 should be constant and not change during the lifetime of the Data Grid.".
=> [docs] Easier to understand demo

docs/data/charts/tooltip/tooltip.md
Solve this slack message
New comment :-1:
> "you don't use highlights, and the tooltip is triggered by an item" what does that even means? what's the difference between highlights and tooltips, here?
sent from https://mui.com/x/react-charts/tooltip/
=> [docs] Slack feedback on wording

dangerfile.js, packages/grid/x-data-grid-pro/src/components/headerFiltering/GridHeaderFilterMenu.tsx, packages/grid/x-data-grid/src/components/cell/GridActionsCell.tsx, packages/grid/x-data-grid/src/components/menu/GridMenu.tsx, packages/grid/x-data-grid/src/components/menu/columnMenu/GridColumnHeaderMenu.tsx, packages/grid/x-data-grid/src/components/toolbar/GridToolbarDensitySelector.tsx, packages/grid/x-data-grid/src/components/toolbar/GridToolbarExportContainer.tsx
I noticed all our usages of `GridMenu` use the same logic, so it's easier to centralize.
Following an exploration done for #10241 but unrelated.
=> [DataGrid] Refactor `GridMenu` prop `onClickAway` to `onClose`

packages/grid/x-data-grid/src/components/menu/GridMenu.tsx
Closes #10241
Restore focus after the grid menu closes. Not sure about this implementation, read the comment below & the issue above.
=> [DataGrid] Restore focus after `GridMenu` closes

packages/grid/x-data-grid-premium/src/tests/DataGridPremium.test.tsx, packages/grid/x-data-grid-premium/src/tests/aggregation.DataGridPremium.test.tsx, packages/grid/x-data-grid-premium/src/tests/exportExcel.DataGridPremium.test.tsx, packages/grid/x-data-grid-premium/src/tests/rowGrouping.DataGridPremium.test.tsx, packages/grid/x-data-grid-premium/src/tests/statePersistence.DataGridPremium.test.tsx, packages/grid/x-data-grid-pro/src/tests/cellEditing.DataGridPro.test.tsx, packages/grid/x-data-grid-pro/src/tests/columnHeaders.DataGridPro.test.tsx, packages/grid/x-data-grid-pro/src/tests/columnSpanning.DataGridPro.test.tsx, packages/grid/x-data-grid-pro/src/tests/columnsVisibility.DataGridPro.test.tsx, packages/grid/x-data-grid-pro/src/tests/editComponents.DataGridPro.test.tsx, packages/grid/x-data-grid-pro/src/tests/events.DataGridPro.test.tsx, packages/grid/x-data-grid-pro/src/tests/rowEditing.DataGridPro.test.tsx, packages/grid/x-data-grid-pro/src/tests/rowSelection.DataGridPro.test.tsx, packages/grid/x-data-grid-pro/src/tests/statePersistence.DataGridPro.test.tsx, packages/grid/x-data-grid-pro/src/tests/treeData.DataGridPro.test.tsx, packages/grid/x-data-grid/src/tests/columnHeaders.DataGrid.test.tsx, packages/grid/x-data-grid/src/tests/columnSpanning.DataGrid.test.tsx, packages/grid/x-data-grid/src/tests/columnsVisibility.DataGrid.test.tsx, packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx, packages/grid/x-data-grid/src/tests/quickFiltering.DataGrid.test.tsx, packages/grid/x-data-grid/src/tests/rowSelection.DataGrid.test.tsx
Fix #7201
Searched for `describe(` in the codebase and fixed the results. Most of the descriptions are just names of props tested, so it was fast 😁
=> [test] Name test suites according to sentence case

docs/data/data-grid/column-dimensions/ColumnAutosizing.js, docs/data/data-grid/column-dimensions/ColumnAutosizing.tsx
A quick follow-up on #10180. Fix a scrollbar on the page on mobile.
before https://deploy-preview-10180--material-ui-x.netlify.app/x/react-data-grid/column-dimensions/#autosizing
after https://deploy-preview-10455--material-ui-x.netlify.app/x/react-data-grid/column-dimensions/#autosizing
=> [docs] Fix mobile scrollbar column resize

packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts
Fixes https://github.com/mui/mui-x/issues/10056#issuecomment-1734121108
Jest already has a variable named `global` in scope in their build process and it prevents code from reusing that name.
NOTE: AUTO-MERGE ENABLED
=> [DataGrid] Rename `global` to `globalScope` due to Jest issue

packages/x-date-pickers/src/internals/hooks/useField/useField.ts, packages/x-date-pickers/src/internals/hooks/useField/useField.types.ts
=> [pickers] Fix clearable behavior when disabled

docs/pages/x/api/data-grid/data-grid-premium.json, docs/pages/x/api/data-grid/data-grid-pro.json, docs/pages/x/api/data-grid/data-grid.json, docs/translations/api-docs/data-grid/data-grid-premium.json, docs/translations/api-docs/data-grid/data-grid-pro.json, docs/translations/api-docs/data-grid/data-grid.json, packages/grid/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx, packages/grid/x-data-grid-pro/src/tests/columns.DataGridPro.test.tsx, packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts, packages/grid/x-data-grid/src/constants/gridClasses.ts
Closes_ sidenote in https://github.com/mui/mui-x/issues/10456
Use `.getBoundingClientRect` to calculate widths.
=> [DataGrid] Fix autosize missing a few pixels

docs/src/modules/components/CustomizationPlayground.tsx, docs/src/modules/utils/useCustomizationPlayground.tsx, packages/x-date-pickers/src/DateCalendar/DayCalendar.tsx
closes #10514 
- Fix `weekNumber` and `weekNumberLabel` bug:
https://github.com/mui/mui-x/assets/72460825/49115c87-b008-422a-9ba3-d9b335802854
- Improve custom theme examples to init new theme outside of the `ThemeProvider`
=> [pickers] Improve customization playground examples

packages/x-date-pickers/src/AdapterDayjs/AdapterDayjs.ts, packages/x-date-pickers/src/AdapterMoment/AdapterMoment.ts, test/utils/pickers/describeGregorianAdapter/testCalculations.ts
Fix #10579
The issue seems to be that `Europe/London` is `+01:00` in summer and `+00:00` during the winter. And for the latter, the `isUTC()` returns true which moves the internal timeZone from `Europe/London` to `UTC`
Here is a codesandbox to reproduce the bug: https://codesandbox.io/s/vibrant-zhukovsky-rcz9f4?file=/Demo.tsx (click on 30th or 31th of October)
Here is the same with a fix https://codesandbox.io/s/mystifying-lewin-v2tzj2?file=/Demo.tsx
The duplicate day for dayjs example is another issue #10584
=> [pickers] Fix timezone `UTC` false positive

test/regressions/index.js, test/regressions/webpack.config.js
A small issue I noticed in #10609, cleaning things up so the next person has a better experience.
To reproduce, you can run `yarn test:regressions:dev`
The rest of the codebase already does it correctly, the only instance that I could find that is wrong.
---
Same goes for, fixed using Material UI solution
=> [test] Fix dev mode warning

packages/grid/x-data-grid-pro/src/hooks/features/lazyLoader/useGridLazyLoader.ts
Fixes #10047 
A nasty one reported [twice](https://github.com/mui/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20LazyLoadingGrid%20crashes) in material-ui repo and [eight times](https://github.com/mui/mui-x/issues?q=is%3Aissue%20[docs]%20Demo%20LazyLoadingGrid%20crashes) in mui-x repo.
=> [DataGrid] Fix `LazyLoading` demo crash

packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts
Closes #10598 
- Before: https://codesandbox.io/s/eager-minsky-wt7xxv?file=/src/demo.tsx
- After: https://codesandbox.io/s/cranky-sanne-c9fhnp?file=/package.json
Pass `getRowId` as a param rather than accessing it directly in `eval` code.
=> [DataGrid] Fix: getRowId not defined

packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx, packages/grid/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx, packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx, packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx, packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterPanel.tsx, packages/grid/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx
--- 
This adds Demo and API links to the export for `DataGrid`, `DataGridPro` and `DataGridPremium`
=> [docs] Fix DataGrid[Pro/Premium] reference links

packages/x-date-pickers/src/internals/components/FakeTextField/FakeTextField.tsx, packages/x-date-pickers/src/internals/components/FakeTextField/index.ts
Code to play with a concrete example:
```tsx
import dayjs from 'dayjs';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { FakeTextField } from '@mui/x-date-pickers/internals/components/FakeTextField';
import {
addPositionPropertiesToSections,
splitFormatIntoSections,
} from '@mui/x-date-pickers/internals/hooks/useField';
import { useLocaleText, useUtils } from '@mui/x-date-pickers/internals';
const date = dayjs('2022-04-17');
const timezone = 'default';
const format = 'MM-DD-YYYY';
const formatDensity = 'spacious';
const shouldRespectLeadingZeros = false;
const isRTL = false;
const AppContent = () => {
const utils = useUtils();
const localeText = …
```
=> [fields] Bootstrap the multi-HTML input component

packages/x-charts/src/ChartsXAxis/ChartsXAxis.tsx, packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx, packages/x-charts/src/context/CartesianContextProvider.tsx, packages/x-charts/src/hooks/useTicks.ts, packages/x-charts/src/models/axis.ts
`tickNumber` was singular for the exposed interface and plural (`ticksNumber`) when computed internally
=> [charts] Fix typo between internal/external variable 

docs/pages/x/api/data-grid/data-grid-premium.json, docs/pages/x/api/data-grid/data-grid-pro.json, docs/pages/x/api/data-grid/data-grid.json, packages/grid/x-data-grid-generator/src/services/tree-data-generator.ts, packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx, packages/grid/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx, packages/grid/x-data-grid-pro/src/models/gridGroupingColDefOverride.ts, packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx, packages/grid/x-data-grid/src/models/props/DataGridProps.ts
=> [DataGrid] Remove unnecessary syntax in JSDoc

docs/src/modules/components/PickersPlayground.tsx
Fixes #10642
- Do not allow unselecting all views by disabling the last available view checkbox
- Show tooltip on the disabled checkbox with a reason
=> [docs] Avoid Pickers playground error due to empty views

packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerToolbar.tsx, packages/x-date-pickers/src/DatePicker/DatePickerToolbar.tsx, packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx, packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx
---
- `DatePickerToolbar`
- `DateRangePickerToolbar`
- `DateTimePickerToolbar`
- `TimePickerToolbar`
... components
=> [pickers] Add reference links to toolbar components

packages/x-charts/src/PieChart/PieChart.tsx, packages/x-charts/src/PieChart/PiePlot.tsx, packages/x-charts/src/ScatterChart/Scatter.tsx, packages/x-charts/src/ScatterChart/ScatterChart.tsx, packages/x-charts/src/ScatterChart/ScatterPlot.tsx
---
- `PieChart`
- `PiePlot`
- `Scatter`
- `ScatterChart`
- `ScatterPlot`
... components
=> [charts] Add reference links to pie + scatter chart components 

packages/x-charts/src/LineChart/LineChart.tsx, packages/x-charts/src/LineChart/LineElement.tsx, packages/x-charts/src/LineChart/LineHighlightElement.tsx, packages/x-charts/src/LineChart/LineHighlightPlot.tsx, packages/x-charts/src/LineChart/LinePlot.tsx, packages/x-charts/src/LineChart/MarkElement.tsx, packages/x-charts/src/LineChart/MarkPlot.tsx, packages/x-charts/src/SparkLineChart/SparkLineChart.tsx
---
- `LineChart`
- `LineElement`
- `LineHighlightElement`
- `LineHighlightPlot`
- `LinePlot`
- `MarkElement`
- `MarkPlot`
- `SparkLineChart` (although technically not 100%in the linechart group)
... components
=> [charts] Add reference links to line chart + sparkline components

packages/x-charts/src/BarChart/BarChart.tsx, packages/x-charts/src/BarChart/BarPlot.tsx, packages/x-charts/src/LineChart/AreaElement.tsx, packages/x-charts/src/LineChart/AreaPlot.tsx
---
- `AreaPlot`
- `AreaElement`
- `BarChart`
- `BarPlot`
... components
=> [charts] Add reference links to area + bar chart components

packages/x-date-pickers-pro/src/DateRangeCalendar/useDragRange.ts, test/e2e/index.test.ts
~~⚠️ This PR is a replacement for #10403 since the commit history got corrupted and included changes not related to this change.~~ (did not notice that those changes came from @LukasTy .. Sry 🙇🏼 )
Touch based range dragging was preventing the selection of a date, when a range was set already. With this change it is possible to select a single date from the range, even if it is the start-date.
Fixes #10332 
https://github.com/mui/mui-x/assets/32863416/05fca116-18eb-40c4-93bf-27158544bc48
=> [DateRangePicker] Fix touch based range dragging

docs/data/date-pickers/date-time-picker/date-time-picker.md, docs/data/date-pickers/time-picker/time-picker.md, docs/pages/x/api/date-pickers/digital-clock.json, docs/pages/x/api/date-pickers/multi-section-digital-clock.json, docs/pages/x/api/date-pickers/time-clock.json, packages/x-date-pickers/src/DigitalClock/DigitalClock.tsx, packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClock.tsx, packages/x-date-pickers/src/TimeClock/TimeClock.tsx
---
- `TimeClock`
- `DigitalClock`
- `MultiSectionDigitalClock`
... components
=> [pickers] Add reference links to clock components

packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx, packages/x-date-pickers/src/DateTimePicker/DateTimePickerTabs.tsx, packages/x-date-pickers/src/DayCalendarSkeleton/DayCalendarSkeleton.tsx, packages/x-date-pickers/src/LocalizationProvider/LocalizationProvider.tsx, packages/x-date-pickers/src/PickersActionBar/PickersActionBar.tsx, packages/x-date-pickers/src/PickersCalendarHeader/PickersCalendarHeader.tsx, packages/x-date-pickers/src/PickersDay/PickersDay.tsx, packages/x-date-pickers/src/PickersLayout/PickersLayout.tsx, packages/x-date-pickers/src/PickersShortcuts/PickersShortcuts.tsx
---
- `DateTimePickerTabs`
- `DateRangePickerDay`
- `DayCalendarSkeleton`
- `LocalizationProvider`
- `PickersCalendarHeader`
- `PickersDay`
- `PickersActionBar`
- `PickersLayout`
- `PickersShortcuts`
... components
=> [pickers] Add reference links to misc picker components

docs/data/date-pickers/date-picker/examplesConfig.ts, docs/src/modules/components/CustomizationPlayground.tsx, docs/src/modules/utils/useCustomizationPlayground.tsx
related to https://github.com/mui/mui-x/issues/10657 
When styling the elements within the popper of `DesktopDatePicker` with the `sx` prop, this needs to be passed to one of the parents of the styled element in order for it to be targeted. I updated the code examples for this. However, it is a workaround-ish solution, so I flagged it with 'warning' and left a comment in the code.
=> [docs] Customization Playground - fix DesktopDatePicker sx props examples

renovate.json
Noticed that the `@types/react` and `@types/react-dom` dependency bumping happens via separate PRs and almost always causes conflicts after merging one or the other. 🙈 
Bumping all relevant React dependencies in a single Renovate PR should avoid such cases.
=> [core] Update React renovate group with `@types`

packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx, packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaderSortIcon.tsx, packages/grid/x-data-grid/src/components/menu/columnMenu/menuItems/GridColumnMenuSortItem.tsx, packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts, packages/grid/x-data-grid/src/hooks/features/sorting/gridSortingUtils.ts, packages/grid/x-data-grid/src/models/props/DataGridProps.ts, packages/grid/x-data-grid/src/tests/columns.spec.tsx
=> [DataGrid] Allow passing readonly arrays to `columns` and `sortingOrder` props

docs/data/data-grid/state/SaveAndRestoreStateInitialState.js, docs/data/data-grid/state/SaveAndRestoreStateInitialState.tsx, docs/data/data-grid/state/SaveAndRestoreStateInitialState.tsx.preview, docs/data/data-grid/state/state.md, docs/scripts/pages/playground/index.tsx
---
Adds a new recipe to the `DataGrid` docs pages showing how to save and restore `state` externally using `LocalStorage`.
Fixes #10508 
Preview: https://deploy-preview-10722--material-ui-x.netlify.app/x/react-data-grid/state/#save-and-restore-the-state-from-external-storage
=> [docs] Add a recipe for saving and restoring `state` externally

docs/package.json, yarn.lock
Closes #9544
- Remove explicit `stylis` dependency as `emotion` and `styled-components` already have direct dependencies of it and we are not importing it directly anywhere.
- Remove `stylis-plugin-rtl-sc` dependency as it's not used on our end (docs) and it's version was already the same as for the original `stylis-plugin-rtl`.
- Bump `styled-components` package as MUI Core has already done it (https://github.com/mui/material-ui/pull/39042) as well.
=> [core] Update `styled-components`

docs/data/data-grid/localization/DataGridRTL.js, docs/data/data-grid/localization/DataGridRTL.tsx, docs/data/data-grid/localization/DataGridRTL.tsx.preview, docs/package.json, yarn.lock
Related to #8665 and a continuation of #10561. I landed here by chance, I was looking at https://github.com/mui/material-ui/pull/31847 (I'm in Morroco right now, an Arabic / RTL country, so why not empathize with them 😄) and noticed that the style of the demo was broken.
Before https://deploy-preview-10721--material-ui-x.netlify.app/x/react-data-grid/localization/#rtl-support
After https://deploy-preview-10728--material-ui-x.netlify.app/x/react-data-grid/localization/#rtl-support
=> [docs] Fix RTL data grid demo

packages/grid/x-data-grid-pro/src/hooks/features/treeData/gridTreeDataGroupColDef.ts, packages/grid/x-data-grid-pro/src/tests/treeData.DataGridPro.test.tsx
Fixes https://github.com/mui/mui-x/issues/9344
Fixes https://github.com/mui/mui-x/issues/8571
=> [DataGridPro] Fix `undefined` values passed to `valueFormatter` for tree leaf nodes

packages/grid/x-data-grid-premium/src/hooks/features/aggregation/gridAggregationFunctions.ts, packages/grid/x-data-grid-premium/src/tests/aggregation.DataGridPremium.test.tsx, packages/grid/x-data-grid/src/utils/utils.ts
Fixes https://github.com/mui/mui-x/issues/10717
- Before: https://codesandbox.io/s/datagridpremium-basic-forked-4pcq56?file=/src/App.tsx
- After: https://codesandbox.io/s/datagridpremium-basic-forked-hg9v2c?file=/src/App.tsx
=> [DataGridPremium] Fix `sum` aggregation to ignore non-numeric values

packages/grid/x-data-grid-premium/src/hooks/features/aggregation/gridAggregationFunctions.ts, packages/grid/x-data-grid-premium/src/tests/aggregation.DataGridPremium.test.tsx
Fixes https://github.com/mui/mui-x/issues/10743
=> [DataGridPremium] Fix `avg` aggregation to ignore non-numeric values

docs/data/data-grid/state/SaveAndRestoreStateInitialState.js, docs/data/data-grid/state/SaveAndRestoreStateInitialState.tsx, docs/data/data-grid/state/SaveAndRestoreStateInitialState.tsx.preview, docs/data/data-grid/state/state.md
---
This implements the suggested changes from @lauri865 (many thanks for pointing that out 🙇🏼).
Now we do save the state on either one of 2 routes:
1. when unmounting with the `useLayoutEffect` cleanup function
2. on navigating away or refreshing (when client session gets reset) by listening on the `beforeunload` event
Fixes #10770
=> [docs] Improve recipe with `useLayoutEffect` and `beforeunload` event-listener

packages/x-charts/src/internals/components/ChartsText.tsx
Fixes #10808.
Thanks to @alexfauquette.
This fix can be reverted when Apple release a new Safari version with the fix mentioned at
[https://webkit.org/blog/14390/release-notes-for-safari-technology-preview-174/](https://webkit.org/blog/14390/release-notes-for-safari-technology-preview-174/).
> Fixed dominant-baseline CSS property to be inherited ([265525@main](https://commits.webkit.org/265525@main))
=> [charts] Fix text position in Safari

packages/x-charts/src/ChartsAxis/ChartsAxis.tsx, packages/x-charts/src/ChartsAxisHighlight/ChartsAxisHighlight.tsx, packages/x-charts/src/ChartsClipPath/ChartsClipPath.tsx, packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx, packages/x-charts/src/ChartsXAxis/ChartsXAxis.tsx, packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx, packages/x-charts/src/context/CartesianContextProvider.tsx, packages/x-charts/src/context/DrawingProvider.tsx
---
- `CartesianContextProvider`
- `ChartsAxis`
- `ChartsXAxis`
- `ChartsYAxis`
- `DrawingProvider`
- `ChartsTooltip`
- `ChartsClipPath`
- `ChartsAxisHighlight`
... components
=> [charts] Add reference links to shared/misc chart components 

docs/data/data-grid/column-dimensions/ColumnAutosizingAsync.js, docs/data/data-grid/column-dimensions/ColumnAutosizingAsync.tsx, docs/data/data-grid/column-dimensions/column-dimensions.md
---
This adds a recipe for the autosizing functionality of the DataGrid using the `apiRef.current.autosizeColumns()` and `apiRef.current.updateRows()` methods.
I did take the example provided by @cherniavskii (option 3 described in #10578) and refactored the `useData` function a bit to fake an API call.
Fixes #10578
=> [docs] Add a recipe for autosizing columns after fetching row-data

packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts, packages/grid/x-data-grid/src/hooks/features/filter/useGridFilter.tsx
Closes #10256 
Use `apiRef.current.getRowId`.
Before: https://codesandbox.io/s/mui-filter-issue-vx5jd8?file=/Demo.tsx
=> [DataGrid] Fix undefined row id

docs/data/date-pickers/custom-field/PickerWithBrowserField.js, docs/data/date-pickers/custom-field/PickerWithBrowserField.tsx, docs/data/date-pickers/custom-field/PickerWithJoyField.js, docs/data/date-pickers/custom-field/PickerWithJoyField.tsx, docs/data/date-pickers/custom-field/PickerWithJoyField.tsx.preview, docs/data/date-pickers/custom-field/RangePickerWithBrowserField.js, docs/data/date-pickers/custom-field/RangePickerWithBrowserField.tsx, docs/data/date-pickers/custom-field/RangePickerWithBrowserField.tsx.preview, docs/data/date-pickers/custom-field/RangePickerWithJoyField.js, docs/data/date-pickers/custom-field/RangePickerWithJoyField.tsx, docs/data/date-pickers/custom-field/RangePickerWithJoyField.tsx.preview, docs/data/date-pickers/custom-field/RangePickerWithSingleInputBrowserField.js, docs/data/date-pickers/custom-field/RangePickerWithSingleInputBrowserField.tsx, docs/data/date-pickers/custom-field/RangePickerWithSingleInputBrowserField.tsx.preview, docs/data/date-pickers/custom-field/RangePickerWithSingleInputJoyField.js, docs/data/date-pickers/custom-field/RangePickerWithSingleInputJoyField.tsx, docs/data/date-pickers/custom-field/RangePickerWithSingleInputJoyField.tsx.preview, docs/data/date-pickers/custom-field/custom-field.md
Created from discussions on https://github.com/mui/mui-x/pull/10485
We agreed that if we split more complex demos on the linked PR, these complex ones should also be split.
I've removed the `DemoContainer` from the individual demos as it was causing more problems with layout. 🙈
=> [docs] Improve custom field input demos readability

docs/data/charts/styling/MarginNoSnap.js, docs/data/charts/styling/styling.md
> New comment :-1:
> I find MUI X docs to be very confusing compared to Material-UI docs.
> 
> I'm trying to apply margin right now (as mentioned above). It won't take 'inherit' as a value, seems to only accept a number.
> 
> So I want to look at the definition of the margin prop: what are its default values?
> Well I can't find the margin prop. It's not in the API reference under BarChart (which is what I'm using).
> sent from https://mui.com/x/react-charts/styling/
https://mui-org.slack.com/archives/C04U3R2V9UK/p1698962389920629
=> [docs] Add demo about how to use charts margin

packages/x-date-pickers/src/DesktopDatePicker/tests/DesktopDatePicker.test.tsx, packages/x-date-pickers/src/internals/hooks/useViews.tsx
Fixes #10878
This snippet was correctly updating the `view`:
https://github.com/mui/mui-x/blob/6c749a8b73435b387d2f5d7c92563271e0f07745/packages/x-date-pickers/src/internals/hooks/useViews.tsx#L140
and after that, this snippet was reverting the `view` back to the original `defaultView` 🙈 
https://github.com/mui/mui-x/blob/6c749a8b73435b387d2f5d7c92563271e0f07745/packages/x-date-pickers/src/internals/hooks/usePicker/usePickerViews.ts#L259
After this change, having the up-to-date `defaultView` avoids the problem of incorrectly reverting the `view`.
=> [pickers] Always use up-to-date `defaultView`

packages/x-date-pickers-pro/src/internals/hooks/useMultiInputRangeField/useMultiInputDateTimeRangeField.ts
=> [fields] fix multi input date time field section selection

packages/x-license-pro/src/useLicenseVerifier/useLicenseVerifier.test.tsx, packages/x-license-pro/src/useLicenseVerifier/useLicenseVerifier.ts
This is a continuation of #9701. The cache for the output of `useLicenseVerifier()` wasn't set at the right location. It would lead to a strange behavior where the exception would log, but not break the rendering flow, at least, not always. It would only break when using server-side rendering.
Now, the behavior is consistent, it breaks server-side and client-side (new).
=> [license] Correctly throw errors

packages/x-date-pickers-pro/src/internals/hooks/useMultiInputRangeField/useMultiInputDateTimeRangeField.ts, packages/x-date-pickers-pro/src/internals/hooks/useMultiInputRangeField/useMultiInputTimeRangeField.ts
follow-up on https://github.com/mui/mui-x/pull/10915
=> [fields] Fix `MultiInputTimeRangeField` section selection

docs/data/data-grid/filtering-recipes/UseNonNativeSelect.js, docs/data/data-grid/filtering-recipes/UseNonNativeSelect.tsx, docs/data/data-grid/filtering-recipes/UseNonNativeSelect.tsx.preview, docs/data/data-grid/filtering-recipes/filtering-recipes.md
---
Title says it all.
Just a small recipe showing that replacing the select is an easy feat.
Recipe in addition to #4127
=> [data grid] Adds a recipe for using non-native select in filter panel

packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts
This fixes an issue that arises when sorting is applied to a filtered, lazy loaded DataGrid instance. An error is thrown when the sort method is changed. 
The stack trace thrown on my app is as follows:
Which leads you into the line of code that I changed:
This fixes the issue, where a child row doesn't appear in the tree.
=> [DataGrid] Fix for error thrown when removing skeleton rows, after sorting is applied

packages/grid/x-data-grid/src/internals/utils/computeSlots.ts
Closes #10933
Allow passing `undefined` as a slot value.
=> [DataGrid] Fix undefined slot values

packages/grid/x-data-grid/src/components/cell/GridActionsCell.tsx, packages/grid/x-data-grid/src/components/cell/GridCell.tsx, packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx
---
This fixes the keyboard navigation for the actions cell when the first (or all) button is disabled.
It does also introduce a new check for the `managesOwnFocus` and renames it to `canManageOwnFocus`
https://github.com/mui/mui-x/assets/32863416/0eab6c81-5dfd-43e6-b367-225df359352a
Fixes #10696
=> [data grid] Fix keyboard navigation for actions cell with disabled buttons

docs/pages/_app.js
---
In preparation for the coming alpha release this adds the alpha version into the version selector on the docs.
Therefor this is intentionally targeted at the master branch
Should be merged together with or after the first alpha release.
=> [core] Adds new alpha version to version select on the docs

packages/grid/x-data-grid/src/components/cell/GridActionsCell.tsx, packages/grid/x-data-grid/src/components/cell/GridCell.tsx, packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx
Cherry picking changes from #10882
=> [DataGrid] Fix keyboard navigation for actions cell with disabled buttons

packages/grid/x-data-grid/src/locales/csCZ.ts
Proposing better translation for column pinning text. Current translation sounds more slovak than czech.
=> [l10n] Improve Czech (cs-CZ) locale

docs/data/charts/legend/HiddenLegend.js, docs/data/charts/legend/HiddenLegend.tsx, docs/data/charts/legend/HiddenLegend.tsx.preview, docs/data/charts/legend/legend.md, packages/x-charts/src/ChartsLegend/ChartsLegend.tsx
From discord message
https://discord.com/channels/1131323012554174485/1131329761952682114/1171478571051663430
=> [docs] Document how to hide the legend

docs/data/migration/migration-charts-v6/migration-charts-v6.md, docs/data/migration/migration-tree-view-v6/migration-tree-view-v6.md
---
I did put in some wrong package names in the migration docs for charts and tree view.
This replaces them with the correct names
=> [core] Fixed wrong package names in migration docs

packages/grid/x-data-grid/src/internals/utils/computeSlots.ts
=> [DataGrid] Fix: undefined slot value

packages/grid/x-data-grid-premium/src/components/GridAggregationHeader.tsx, packages/grid/x-data-grid-premium/src/hooks/features/aggregation/wrapColumnWithAggregation.tsx, test/regressions/index.test.js
Fixes https://github.com/mui/mui-x/issues/10817
Before: https://codesandbox.io/s/renderheader-mui-bug-forked-lv9xhc
After: https://codesandbox.io/s/renderheader-mui-bug-forked-pqkdfk
=> [DataGridPremium] Render aggregation label when `renderHeader` is used

CHANGELOG.md, package.json, packages/grid/x-data-grid-generator/package.json, packages/grid/x-data-grid-premium/package.json, packages/grid/x-data-grid-pro/package.json, packages/grid/x-data-grid/package.json, packages/x-charts/package.json, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json
---
The following steps must be proposed as a pull request.
=> [release] v6.18.1

packages/x-date-pickers/src/DateCalendar/tests/DateCalendar.test.tsx, packages/x-date-pickers/src/DateCalendar/useCalendarState.tsx, packages/x-date-pickers/src/DesktopTimePicker/tests/describes.DesktopTimePicker.test.tsx, packages/x-date-pickers/src/DigitalClock/DigitalClock.tsx, packages/x-date-pickers/src/DigitalClock/tests/DigitalClock.test.tsx, packages/x-date-pickers/src/DigitalClock/tests/describes.DigitalClock.test.tsx, packages/x-date-pickers/src/MobileTimePicker/tests/describes.MobileTimePicker.test.tsx, packages/x-date-pickers/src/MonthCalendar/MonthCalendar.tsx, packages/x-date-pickers/src/MonthCalendar/tests/MonthCalendar.test.tsx, packages/x-date-pickers/src/MonthCalendar/tests/describes.MonthCalendar.test.tsx, packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClock.tsx, packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClock.types.ts, packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClock.utils.ts, packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx, packages/x-date-pickers/src/MultiSectionDigitalClock/tests/MultiSectionDigitalClock.test.tsx, packages/x-date-pickers/src/TimeField/tests/describes.TimeField.test.tsx, packages/x-date-pickers/src/YearCalendar/YearCalendar.tsx, packages/x-date-pickers/src/YearCalendar/tests/YearCalendar.test.tsx, packages/x-date-pickers/src/YearCalendar/tests/describes.YearCalendar.test.tsx, test/utils/pickers/misc.ts, test/utils/pickers/viewHandlers.ts
Part of #10747 
Align the behavior of `referenceDate` on the views (`DateCalendar`, `DigitalClock`, and `MultiSectionDigitalClock`).
The behavior on `TimeClock` already makes sense.
- Make the `referenceDate` day focusable (tabindex="0") if no value is present in `DateCalendar` instead of today's day
- Make the `referenceDate` time focusable (tabindex="0") and scroll the options list to it if no value is present and the date maps to an available option in `DigitalClock`
- Make the `referenceDate` time sections focusable (tabindex="0") and scroll the options lists to them if no value is present and the date maps to an available option in `MultiSectionDigitalClock`
~~WDYT about `MonthCalendar` and `YearCalendar`, should we align it to also not mark the `reference` month and day as selected, …
=> [pickers] Refine `referenceDate` behavior in views

docs/data/date-pickers/localization/data.json, packages/x-date-pickers/src/locales/esES.ts, packages/x-date-pickers/src/locales/eu.ts, packages/x-date-pickers/src/locales/euES.ts, packages/x-date-pickers/src/locales/index.ts, scripts/l10n.ts, scripts/localeNames.js, scripts/x-date-pickers-pro.exports.json, scripts/x-date-pickers.exports.json
Add Basque l10n for date pickers.
=> [l10n] Add Basque (eu) locale and improve Spanish (es-ES) locale

packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.test.tsx, packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts, packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts
Fix #10177
This branch is on top of #10185
=> [pickers] Escape non tokens words

packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts, test/utils/pickers/describeGregorianAdapter/testLocalization.ts
=> [pickers] Add short weekdays token

CHANGELOG.md, package.json, packages/grid/x-data-grid-generator/package.json, packages/grid/x-data-grid-premium/package.json, packages/grid/x-data-grid-pro/package.json, packages/grid/x-data-grid/package.json, packages/x-charts/package.json, packages/x-codemod/package.json, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json, packages/x-license-pro/package.json
---
The following steps must be proposed as a pull request.
=> [release] v7.0.0-alpha.0

docs/data/migration/migration-pickers-v6/migration-pickers-v6.md, packages/x-date-pickers/src/internals/hooks/useField/useField.test.tsx, packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts, packages/x-date-pickers/src/models/fields.ts
Closes #10987 
- The property `hasLeadingZeros` has been removed from the sections in favor of the more precise `hasLeadingZerosInFormat` and `hasLeadingZerosInInput` properties.
To keep the same behavior, you can replace it by `hasLeadingZerosInFormat`:
```diff
const fieldRef = React.useRef<FieldRef<FieldSection>>(null);
React.useEffect(() => {
const firstSection = fieldRef.current!.getSections()[0]
-    console.log(firstSection.hasLeadingZeros)
+    console.log(firstSection.hasLeadingZerosInFormat)
}, [])
return (
<DateField unstableFieldRef={fieldRef} />
);
```
=> [pickers] Remove the `hasLeadingZeros` property from `FieldSection`

docs/data/migration/migration-pickers-v6/migration-pickers-v6.md, packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx, packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.ts, packages/x-date-pickers/src/AdapterDateFnsJalali/AdapterDateFnsJalali.ts, packages/x-date-pickers/src/AdapterDayjs/AdapterDayjs.ts, packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts, packages/x-date-pickers/src/AdapterMoment/AdapterMoment.ts, packages/x-date-pickers/src/AdapterMomentHijri/AdapterMomentHijri.ts, packages/x-date-pickers/src/AdapterMomentJalaali/AdapterMomentJalaali.ts, packages/x-date-pickers/src/models/adapters.ts
=> [pickers] Modify `adapter.isEqual` method to accept `TDate | null` instead of any

test/regressions/index.test.js
Fixes false-positives like https://app.argos-ci.com/mui/mui-x/builds/15042/64442787
=> [test] Wait for images to load

docs/data/migration/migration-pickers-v6/migration-pickers-v6.md, packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.ts, packages/x-date-pickers/src/AdapterDateFnsJalali/AdapterDateFnsJalali.ts, packages/x-date-pickers/src/AdapterDayjs/AdapterDayjs.ts, packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts, packages/x-date-pickers/src/AdapterMoment/AdapterMoment.ts, packages/x-date-pickers/src/AdapterMomentHijri/AdapterMomentHijri.ts, packages/x-date-pickers/src/AdapterMomentJalaali/AdapterMomentJalaali.ts, packages/x-date-pickers/src/YearCalendar/YearCalendar.tsx, packages/x-date-pickers/src/models/adapters.ts, test/utils/pickers/describeGregorianAdapter/testCalculations.ts, test/utils/pickers/describeHijriAdapter/testCalculations.ts, test/utils/pickers/describeJalaliAdapter/testCalculations.ts
Closes #10977
- The `adapter.getYearRange` method used to accept two params and now accepts a tuple to be consistent with the `adapter.isWithinRange` method:
```diff
- adapter.getYearRange(start, end);
+ adapter.getYearRange([start, end])
```
=> [pickers] Change the input format of `adapter.getYearRange` to be consistent with `adapter.isWithinRange`

docs/data/date-pickers/custom-components/custom-components.md
=> [docs] Fix Pickers CustomComponents Incorrect naming of a component in example

docs/data/date-pickers/adapters-locale/CustomCalendarHeaderFormat.js, docs/data/date-pickers/adapters-locale/CustomCalendarHeaderFormat.tsx, docs/data/date-pickers/adapters-locale/CustomCalendarHeaderFormat.tsx.preview, docs/data/date-pickers/adapters-locale/adapters-locale.md, docs/pages/x/api/date-pickers/date-range-calendar.json, docs/pages/x/api/date-pickers/date-range-picker.json, docs/pages/x/api/date-pickers/desktop-date-range-picker.json, docs/pages/x/api/date-pickers/mobile-date-range-picker.json, docs/pages/x/api/date-pickers/pickers-calendar-header.json, docs/pages/x/api/date-pickers/static-date-range-picker.json, docs/translations/api-docs/date-pickers/date-range-calendar.json, docs/translations/api-docs/date-pickers/date-range-picker.json, docs/translations/api-docs/date-pickers/desktop-date-range-picker.json, docs/translations/api-docs/date-pickers/mobile-date-range-picker.json, docs/translations/api-docs/date-pickers/pickers-calendar-header.json, docs/translations/api-docs/date-pickers/static-date-range-picker.json, packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx, packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.types.ts, packages/x-date-pickers/src/DateCalendar/tests/DateCalendar.test.tsx, packages/x-date-pickers/src/PickersCalendarHeader/PickersCalendarHeader.tsx, packages/x-date-pickers/src/internals/components/PickersArrowSwitcher/PickersArrowSwitcher.types.tsx
Part of #10776
I can mark this as breaking and add it to the migration guide if you want.
=> [DateCalendar] Allow to override the format of the header with a prop

docs/data/date-pickers/custom-components/custom-components.md
=> [docs] Fix incorrect component name in the "Custom slots and subcomponents" page

docs/data/migration/migration-pickers-v6/migration-pickers-v6.md, packages/x-date-pickers/src/DateCalendar/index.ts, packages/x-date-pickers/src/index.ts, packages/x-date-pickers/src/themeAugmentation/overrides.d.ts, packages/x-date-pickers/src/themeAugmentation/themeAugmentation.spec.ts
- The imports related to the `calendarHeader` slot have been moved from `@mui/x-date-pickers/DateCalendar` to `@mui/x-date-pickers/PIckersCalendarHeader`:
```diff
export {
pickersCalendarHeaderClasses,
PickersCalendarHeaderClassKey,
PickersCalendarHeaderClasses,
PickersCalendarHeader,
PickersCalendarHeaderProps,
PickersCalendarHeaderSlotsComponent,
PickersCalendarHeaderSlotsComponentsProps,
ExportedPickersCalendarHeaderProps,
- } from '@mui/x-date-pickers/DateCalendar';
+ } from '@mui/x-date-pickers/PickersCalendarHeader';
```
Closes #11019
=> [pickers] v7: Move the exports of the `calendarHeader` slot to `@mui/x-date-pickers/PickersCalendarHeader`

docs/package.json, package.json, yarn.lock
To be coherent with https://github.com/mui/material-ui/pull/36347
It's also needed for https://github.com/mui/mui-x/security/dependabot/86
=> [core] Upgrade babel-plugin-module-resolver to 5.0.0

docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md, docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md, docs/data/migration/migration-pickers-v5/migration-pickers-v5.md, docs/data/migration/migration-pickers-v6/migration-pickers-v6.md, packages/x-codemod/README.md
Update the README of the `@mui/x-codemod` package to be ready to have both v6 and v7 codemods
=> [docs] Clean the codemod README

docs/pages/_app.js
- Fix a bug of redirecting to a non-existent charts v6 page
- Use direct Data Grid documentation links instead of aliases
- Use same (Overview) page for Pickers v6 link (align with Data Grid)
=> [docs] Fix version links

renovate.json
This rule is enabled on MUI core and Toolpad repositories. I'm proposing to bring X in line. This adds a monthly [renovatebot PR with recreated lockfile](https://docs.renovatebot.com/configuration-options/#lockfilemaintenance). The goal is to regularly bring all transitive dependencies up to date. It will be especially intersting around the docs to keep transitive dependencies relatively up to date as many of them are implicitly shared between the repositories.
Note for reviewers: The maintenance burden of closing the resulting PRs will stay with the X team, not the code infra team.
=> [renovate] Monthly schedule for lockfile maintenance

docs/data/date-pickers/localization/data.json, packages/x-date-pickers/src/locales/deDE.ts
https://github.com/mui/mui-x/issues/11102
=>  [l10n] Improve German (de-DE) locale

packages/x-date-pickers/src/DateCalendar/useCalendarState.tsx
Fixes #11062
Does not occur in v7 because `focusedDay` is initialized to equal `referenceDate` which does a similar test.
Once `focusedDay` contains an invalid date, it is passed to `findClosestEnabledDate` in `DayCalendar` and the method does not like it.
=> [pickers] Fix `DateCalendar` crashing when given an invalid value

test/e2e/index.test.ts
Fixes flaky test that sometimes fails in CircleCI on Webkit:
=> [test] Skip flaky e2e test in webkit

docs/pages/x/api/date-pickers/date-calendar.json, docs/pages/x/api/date-pickers/date-picker.json, docs/pages/x/api/date-pickers/date-range-calendar.json, docs/pages/x/api/date-pickers/date-range-picker.json, docs/pages/x/api/date-pickers/date-time-picker.json, docs/pages/x/api/date-pickers/desktop-date-picker.json, docs/pages/x/api/date-pickers/desktop-date-range-picker.json, docs/pages/x/api/date-pickers/desktop-date-time-picker.json, docs/pages/x/api/date-pickers/mobile-date-picker.json, docs/pages/x/api/date-pickers/mobile-date-range-picker.json, docs/pages/x/api/date-pickers/mobile-date-time-picker.json, docs/pages/x/api/date-pickers/static-date-picker.json, docs/pages/x/api/date-pickers/static-date-range-picker.json, docs/pages/x/api/date-pickers/static-date-time-picker.json, packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx, packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.types.ts, packages/x-date-pickers-pro/src/DateRangePicker/DateRangePicker.tsx, packages/x-date-pickers-pro/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx, packages/x-date-pickers-pro/src/MobileDateRangePicker/MobileDateRangePicker.tsx, packages/x-date-pickers-pro/src/StaticDateRangePicker/StaticDateRangePicker.tsx, packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx, packages/x-date-pickers/src/DateCalendar/DateCalendar.types.ts, packages/x-date-pickers/src/DatePicker/DatePicker.tsx, packages/x-date-pickers/src/DateTimePicker/DateTimePicker.tsx, packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.tsx, packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx, packages/x-date-pickers/src/MobileDatePicker/MobileDatePicker.tsx, packages/x-date-pickers/src/MobileDateTimePicker/MobileDateTimePicker.tsx, packages/x-date-pickers/src/StaticDatePicker/StaticDatePicker.tsx, packages/x-date-pickers/src/StaticDateTimePicker/StaticDateTimePicker.tsx
=> [pickers] Deprecate `defaultCalendarMonth` prop

packages/grid/x-data-grid-generator/README.md, packages/grid/x-data-grid-generator/package.json, packages/grid/x-data-grid-premium/package.json, packages/grid/x-data-grid-pro/package.json, packages/grid/x-data-grid/package.json, packages/x-charts/package.json, packages/x-codemod/package.json, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json, packages/x-tree-view/package.json
Make it clearer from https://www.npmjs.com/package/@mui/x-data-grid-generator where the source of the package is located at.
I have noticed this from https://mui.zendesk.com/agent/tickets/14319, the link we have right now is not really relevant.
=> [docs] Point to the source of @mui/x-data-grid-generator

packages/x-codemod/README.md, packages/x-codemod/src/v7.0.0/data-grid/rename-components-to-slots/index.ts, packages/x-codemod/src/v7.0.0/pickers/preset-safe/actual.spec.js, packages/x-codemod/src/v7.0.0/pickers/preset-safe/expected.spec.js, packages/x-codemod/src/v7.0.0/pickers/preset-safe/index.ts, packages/x-codemod/src/v7.0.0/pickers/rename-components-to-slots/index.ts
=> [codemod] Clean the components to slots codemod usage

docs/data/pages.ts
@LukasTy the most recent feature is *Digital Clock*, I think we can still remove the flag and only use it for v7 features, what do you think?
=> [docs] Remove the `newFeature` flag on v6 features

packages/grid/x-data-grid-premium/src/hooks/features/aggregation/wrapColumnWithAggregation.tsx, packages/grid/x-data-grid-premium/src/tests/aggregation.DataGridPremium.test.tsx
Fixes https://github.com/mui/mui-x/issues/10864
=> [DataGridPremium] Fix aggregated column ignoring column definition changes

docs/next.config.js
I'm not sure what went wrong on this one, but it's likely when we refactored the logic to move the value to `ENABLE_AD_IN_DEV_MODE` abstracted under the docs infra that we lost track of this value.
Related to #10795
=> [core] Remove outdated ENABLE_AD env variable

docs/data/charts/axis/MinMaxExample.js, docs/data/charts/axis/MinMaxExample.tsx, docs/data/charts/axis/axis.md
Before: https://mui.com/x/react-charts/axis/#axis-sub-domain
After: https://deploy-preview-11173--material-ui-x.netlify.app/x/react-charts/axis/#axis-sub-domain
=> [docs] Simplify a bit chart demo

packages/x-charts/src/LineChart/extremums.ts
Fix #11032
The issue was due to the initialisation of the reducer. It was looking for the first array item which does not exist when the data set is empty.
=> [charts] Fix error with empty dataset

docs/next.config.js, docs/package.json, netlify.toml, package.json
A regression introduced from #10795, see #10539 for the context of what's the regression.
I didn't expect it would be easy to fix. At first, I was going to encourage a revert, using #10539 as why. But while I was refining the reproduction to raise the issue to the Next.js team in https://github.com/oliviertassinari/next-55817, I found by chance that following the proposed upgrade path solved the issue.
=> [docs] Fix <title> generation

packages/x-charts/src/internals/defaultizeValueFormatter.ts
=> [charts] Adjusted `defaultizeValueFormatter` util to accept an optional `series.valueFormatter` value 

docs/.link-check-errors.txt, docs/data/introduction/licensing/licensing.md
While working on https://github.com/mui/material-ui/pull/39832, I noticed a few relatively quick improvement opportunities for the MUI X docs! This one adds in just some minor copywriting and formatting tweaks to make the page more consistent: 
- Remove unnecessary backticks from headings
- Capitalize the components' names
- Remove callouts when possible
👉 https://deploy-preview-11178--material-ui-x.netlify.app/x/introduction/licensing/
=> [docs] Add small formatting improvements to the licensing page

docs/data/introduction/installation/installation.md, docs/src/modules/components/InstallationGrid.js
While working on https://github.com/mui/material-ui/pull/39832, I noticed a few relatively quick improvement opportunities for the MUI X docs! This one adds a card grid to the installation page to make it a bit more interesting to look at as well as less repetitive (there were four repeating "The installation instructions" text elements).
👉  https://deploy-preview-11177--material-ui-x.netlify.app/x/introduction/installation/
=> [docs] Add a card grid to the installation page

packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx, packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputValue.tsx, packages/grid/x-data-grid/src/tests/filterPanel.DataGrid.test.tsx
Upon investigation, we discovered that this issue occurs when a user wants to filter a value in a String column and then tries to change the String Column to a Number column. When this happens, the program tries to parse the string value the user initially inputted in the Value Text field to a number value, because it's unable to do that, it clears out the value from the Text Field but the value still remains in the items object in the program.
The solution to this would be to reset the item value property when the user switches from one column to another.
[Loom Video](https://www.loom.com/share/d3f38557fcd54acabc4241c178d95606?sid=29b3f889-ed0f-40a9-9a82-728dddc05a85)
Fixes https://github.com/mui/mui-x/issues/10489
Closes https://github.com/mui/mui-x/pull/10711
---
This code was written …
=> [DataGrid] Fix `onFilterModelChange` being fired with stale field value

yarn.lock
I want to pull in a change to simplify the Algolia crawler configuration. This should allow:
```diff
defaultValue: $(".algolia-lvl0")
.map((index, element) => $(element).text())
.get()
.join(" > "),
},
lvl1: [".algolia-lvl1", ".markdown-body h1"],
lvl2: [".algolia-lvl2", ".markdown-body h2"],
-           lvl3: [".algolia-lvl3", ".markdown-body h3, .MuiApi-item-title"],
+           lvl3: [".algolia-lvl3", ".markdown-body h3"],
lvl4: [".algolia-lvl4", ".markdown-body h4"],
content:
-             ".algolia-content, .markdown-body p, .markdown-body li, .markdown-body td:first-of-type, .prop-list-description",
+             ".algolia-content, .markdown-body p, .markdown-body li, .markdown-body td:first-of-type",
},
```
https://crawler.algolia.com/admin/crawlers/739c29c8-99ea-4945-bd27-17a1df391 …
=> [core] Update @mui/monorepo

packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx, packages/x-date-pickers/src/MultiSectionDigitalClock/multiSectionDigitalClockSectionClasses.ts
Cherry-pick fixes introduced in #9528 
- Fix scrolling on mobile https://github.com/mui/mui-x/pull/9528/commits/0fd69b33e9dae7119060641ec0ad3f5a5297c3fd
- Apply class name to an item https://github.com/mui/mui-x/pull/9528/commits/787ed6ce96ae8b3bd5f4945e421abe205c128a58
- Fix component name: https://github.com/mui/mui-x/pull/9528/commits/a38e5b99b00f7964d6ecc59b268bbe6cae3b0933
You could say that it is a breaking change, but I'd say that this is just a bugfix, because we had duplicate items with the same name and no way to correctly target them.
=> [pickers] Fix `MultiSectionDigitalClock` issues

docs/data/charts/bars/bars.md, packages/x-charts/src/SparkLineChart/SparkLineChart.tsx
I was reading the latest blog post about MUI X and landed on this strange demo experience: https://next.mui.com/x/react-data-grid/custom-columns/#sparkline.
https://github.com/mui/mui-x/assets/3165635/d540aaff-03c3-4632-923b-710fa251865c
None of the Sparklines in https://www.notion.so/mui-org/Sparkline-component-fc42c8576f7a4a46858fbcd713146072 have animations. I think animation is nice if you have a few charts, and you don't need to quickly scan the values, but if that's not the case, e.g. sparkling, it degrades the UX.
This is a polish on top of #9926.
After: https://deploy-preview-11311--material-ui-x.netlify.app/x/react-data-grid/custom-columns/#sparkline
---
**Off-topic**. We have no label per component type, is this missing? e.g. LineChart, BarChart, Sparkline, etc.
=> [charts] Remove animation on sparkline

docs/data/date-pickers/base-concepts/ReferenceDateDefaultBehavior.js, docs/data/date-pickers/base-concepts/ReferenceDateDefaultBehavior.tsx, packages/x-date-pickers/src/internals/demo/DemoContainer.tsx
This PR was inspired by https://github.com/mui/mui-x/pull/9528/commits/f67c50b231a526a7fc47ec0f3272ec10ca901255, but the solution was incorrect and needed much improvement. 🙈 
The problems that were solved:
- The `sx` styles were lost whenever the component in question was wrapped in an intermediate `DemoItem`;
It was fixed by injecting the relevant styles to such an intermediate component, based on its name.
- MultiInputDateTimeRangeField had no explicit styling and thus its value was cut off.
=> [docs] Improve `DemoContainer` styling coverage

packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx, packages/x-date-pickers/src/PickersCalendarHeader/PickersCalendarHeader.tsx, packages/x-date-pickers/src/internals/constants/dimensions.ts
Extract https://github.com/mui/mui-x/pull/9528/commits/19b9cbde59591a6001393e583582f3d3c514f7db and https://github.com/mui/mui-x/pull/9528/commits/95c320ae7078686fe015e3a2c9c9e8cc37e28379.
While working on integrating DateRangeCalendar and time clock in a two column layout for the Date Time Range picker I've noticed that there is an inconsistency in the calendar height, particularly the `PickersCalendarHeader`, which was 2px too short on regular DateCalendar.
The [MD2 spec](https://m2.material.io/components/date-pickers#specs:~:text=Mobile%20calendar%20picker-,Calendar%20header,-The%20mobile%20calendar) calls for a header height of 56px instead of the 54px, which we currently have.
Extracting the change into a separate PR to separate the Argos diff.
=> [pickers] Fix views height consistency

docs/data/charts/getting-started/getting-started.md, packages/x-charts/package.json
---
This adds `@mui/utils` as a dependency for the charts package.
I included the section about the `peerDependencies` from the pickers page as well.
Fixes #11338
=> [charts] Added `@mui/utils` as a dependency

CHANGELOG.md, package.json, packages/grid/x-data-grid-generator/package.json, packages/grid/x-data-grid-premium/package.json, packages/grid/x-data-grid-pro/package.json, packages/grid/x-data-grid/package.json, packages/x-charts/package.json, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json, packages/x-tree-view/package.json
=> v7.0.0-alpha.4

packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx
Fixes autoFocus for `DateRangePicker`.
- Fixed mistake in logic for `DayCalendarForRange`'s`autoFocus` prop.
=> [DateRangePicker] Fix `autoFocus` behavior 

.github/workflows/no-response.yml
Context: https://github.com/mui/mui-x/issues/10810#issuecomment-1844849589
Added an enhancement to auto-remove the label `status: waiting for maintainer` on the issue close or auto-remove the label `status: waiting for author` on the issue comment and close, if the issue was closed by the author.
Here's a test of the updated action carried out on a test repo: https://github.com/MBilalShafi/test-github-action/issues/6
The action is configured on that repo, feel free to play around with it.
=> [github] Update `no-response` workflow

packages/x-date-pickers/src/internals/hooks/useField/useField.types.ts
The fix is a cherry-pick of this commit: https://github.com/mui/mui-x/pull/11280/commits/1f0b1049be4b0102730358c3b4e794a2525045a7
We can't merge the https://github.com/mui/mui-x/pull/11280 yet.
In the meantime, shipping only this fix should help users avoid problems like this: https://github.com/mui/mui-x/pull/11280#issuecomment-1851045582.
=> [pickers] Fix field types to avoid error on latest `@types/react` version

docs/data/charts/styling/MarginNoSnap.js
Fixes #10885
I realized this bug is not the fault of the dynamic size feature.
The parent has a display flex which leads to ignoring the element sizing. Wrapping the charts in a div solves the issue
=> [charts] Fix size overflow

.github/workflows/cherry-pick-next-to-master.yml
This might be useful for the PRs that need to be cherry-picked to master during the alpha and beta phases of development.
Tested the workflow on a test repo, and it seems to work as expected!
=> [core] Automate cherry-pick of PRs from `next` -> `master`

docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md, packages/grid/x-data-grid/src/models/controlStateItem.ts, packages/grid/x-data-grid/src/utils/createSelector.spec.ts, packages/grid/x-data-grid/src/utils/createSelector.test.ts, packages/grid/x-data-grid/src/utils/createSelector.ts
I'm using an opportunity to remove some `TODO v6` comments 😅
=> [DataGrid] Make `instanceId` required for state selectors

docs/data/data-grid/column-dimensions/ColumnAutosizingGroupedRows.js, docs/data/data-grid/column-dimensions/ColumnAutosizingGroupedRows.tsx, docs/data/data-grid/column-dimensions/ColumnAutosizingGroupedRows.tsx.preview, docs/data/data-grid/column-dimensions/column-dimensions.md
---
Added a new recipe to show how column autosizing can be used when row grouping is in place as well
Closes #11262
=> [DataGrid] Recipe for grouped rows autosizing

CHANGELOG.md, package.json, packages/grid/x-data-grid-generator/package.json, packages/grid/x-data-grid-premium/package.json, packages/grid/x-data-grid-pro/package.json, packages/grid/x-data-grid/package.json, packages/x-codemod/package.json, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json
=> v7.0.0-alpha.5

docs/data/date-pickers/localization/data.json, packages/x-date-pickers/src/locales/ruRU.ts
Added a clear value locale filed.
=> [l10n] Improve Russian (ru-RU) locale

packages/x-charts/src/BarChart/formatter.ts, packages/x-charts/src/LineChart/formatter.ts, packages/x-charts/src/context/SeriesContextProvider.tsx, packages/x-charts/src/models/seriesType/config.ts
When working on https://github.com/mui/material-ui/pull/40107 I noticed `null` was not accepted as a data set value. This PR fixes this issue by allowing `null` and `undefined`.
On a larger topic, I think devs tend to put various things in the dataset. The result of their data fetching without preprocessing to enable rich tooltip for example. I'm wondering if the default type should be `unknown` such that they can put whatever they want in the dataset, and do stricter type-checking into formatters
=> [charts] Improve dataset typing

docs/data/date-pickers/date-picker/FormPropsDatePickers.js, docs/data/date-pickers/date-picker/FormPropsDatePickers.tsx, docs/data/date-pickers/date-picker/FormPropsDatePickers.tsx.preview, docs/data/date-pickers/date-range-picker/SingleInputDateRangePicker.js, docs/data/date-pickers/date-range-picker/SingleInputDateRangePicker.tsx, docs/data/date-pickers/date-range-picker/SingleInputDateRangePicker.tsx.preview, docs/data/date-pickers/date-range-picker/date-range-picker.md, docs/data/date-pickers/date-time-picker/FormPropsDateTimePickers.js, docs/data/date-pickers/date-time-picker/FormPropsDateTimePickers.tsx, docs/data/date-pickers/date-time-picker/FormPropsDateTimePickers.tsx.preview, docs/data/date-pickers/time-picker/FormPropsTimePickers.js, docs/data/date-pickers/time-picker/FormPropsTimePickers.tsx, docs/data/date-pickers/time-picker/FormPropsTimePickers.tsx.preview
Follow-up on #11025 
- Use more form related `name` prop values;
- Add `name` prop usage example on `DateRangePicker` example with single input field;
- Add relevant `components` item to avoid layout issues;
=> [docs] Improve Pickers `name` prop examples

packages/x-date-pickers/src/PickersSectionList/PickersSectionList.tsx
Small improvement to avoid the duplication of the warning in each method of the ref.
=> [pickers] Cleanup error messages in `PickersSectionList`

packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx, packages/x-date-pickers/src/internals/hooks/useField/useField.ts, test/e2e/index.test.ts
Fixes #10880 
Currently, when we detect a section paste, we just `return` from the paste handler, thus handing the execution to a regular input change handler, which fails on non-chromium browsers, because on them the `event.data` contains the pasted value.
Changed the logic to update a section value with the pasted value and call `preventDefault` to avoid triggering the input change handler.
I tried hard to make the e2e test work, but sadly, headless and CI don't play along with Clipboard API nicely. Left only the `firefox` test functional. 🙈 
- Add e2e test asserting correct section copy and paste behavior
- include an assertion of reset query resetting 
- Add unit test asserting correct section paste behavior
=> [fields] Fix section pasting

.github/workflows/cherry-pick-next-to-master.yml
Follow up on #11382
- Add a job name to fix:
- Re-use the PR author as the author of the cherry-pick PR. This should help reduce the headache of updating the author of the cherry-pick PR on the generated release changelog.
=> [core] Cherry pick follow up

docs/data/data-grid/custom-columns/EditingWithDatePickers.js, docs/data/data-grid/custom-columns/EditingWithDatePickers.tsx, docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md, packages/grid/x-data-grid/src/colDef/gridDateOperators.ts, packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputDate.tsx, packages/grid/x-data-grid/src/tests/filtering.DataGrid.test.tsx
Closes https://github.com/mui/mui-x/issues/6564
TODO:
- The `filterModel` now supports `Date` objects as values for `date` and `dateTime` column types.
The `filterModel` still accepts strings as values for `date` and `dateTime` column types,
but all updates to the `filterModel` coming from the UI (e.g. filter panel) will set the value as a `Date` object.
=> [DataGrid] Support `Date` objects in filter model

.github/workflows/cherry-pick-next-to-master.yml
Fixes #11468 
- Added a root level no permissions declaration which should solve `Token-Permissions` in https://github.com/mui/mui-x/security/code-scanning
- Pinned the dependencies to their corresponding SHAs
- Moved the `env` to the scope where it's needed, no need to define it globally.
=> [core] Fix security regressions in cherry-pick-next-to-master.yml

packages/x-charts/src/BarChart/BarPlot.tsx, packages/x-charts/src/BarChart/formatter.ts, packages/x-charts/src/ChartsAxis/ChartsAxis.tsx, packages/x-charts/src/ChartsReferenceLine/ChartsReferenceLine.tsx, packages/x-charts/src/LineChart/AreaPlot.tsx, packages/x-charts/src/LineChart/LineHighlightPlot.tsx, packages/x-charts/src/LineChart/LinePlot.tsx, packages/x-charts/src/LineChart/MarkPlot.tsx, packages/x-charts/src/LineChart/formatter.ts, packages/x-charts/src/ResponsiveChartContainer/index.tsx, packages/x-charts/src/context/CartesianContextProvider.tsx, packages/x-charts/src/context/SeriesContextProvider.tsx
This improvement the charts error message in 3 ways (one per commit):
- Use the prefix `MUI-Charts: ` to distinguish error messages that are charts from those coming from other MUI dependencies.
- Provide the array of available axes ids when the provided id is not found, to quickly know if it's a typo or a more serious error.
- Adapt the error message when the axis id is not specified by the user. It's frequent with composition to get an error `Axis of id "DEFAULT_X_AXIS_KEY" should be ...` which makes no sense for a new user.
=> [charts] Make error message more explicit

docs/pages/x/api/charts/pie-arc-label-plot.json, docs/pages/x/api/charts/pie-arc-plot.json, packages/x-charts/src/PieChart/PieArcLabelPlot.tsx, packages/x-charts/src/PieChart/PieArcPlot.tsx, packages/x-charts/src/PieChart/PieChart.tsx, packages/x-charts/src/PieChart/PiePlot.tsx, packages/x-charts/src/PieChart/dataTransform/useTransformData.ts, packages/x-charts/src/internals/utils.ts, packages/x-charts/src/models/seriesType/pie.ts, scripts/x-charts.exports.json
Fix #11309
The inner radius value for 100% is the maximal radius.
My initial idea was to take:
- outer radius at 100% = the maximal radius that fits in the drawing area
- inner radius at 100% = the outer radius
This would ensure that the inner radius is always smaller than the outer radius.
But if you want to put multiple pie charts inside each other, you will need to do some computation to get the outer radius of one pie to match the inner radius of the other one.
The percentage is supported only at the `PiePlot` level. To place sub-components you already need to manipulate the drawing area, so the diff between having to compute `width/2` vs providing `'50%'` is small enough to remove percent support
=> [charts] Allow percentage values for pie chart center and radius

.github/ISSUE_TEMPLATE/6.docs-feedback.yml
We forgot to replace "MUI Core". I saw this on this page https://github.com/mui/mui-x/issues/new/choose, it felt strange.
=> [core] Localize the issue template to MUI X

packages/grid/x-data-grid/src/locales/csCZ.ts
Correctly is "Seskupit" in Czech.
=> [l10n] Update Czech (cs-CZ) locale

docs/data/data-grid/getting-started/getting-started.md, docs/data/data-grid/localization/data.json, docs/data/data-grid/localization/localization.md, docs/data/data-grid/overview/overview.md, docs/data/date-pickers/getting-started/getting-started.md, docs/data/date-pickers/localization/data.json, docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md, docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md, docs/data/migration/migration-pickers-v5/migration-pickers-v5.md, docs/data/tree-view/getting-started/getting-started.md, docs/next.config.js, docs/pages/_app.js, docs/src/modules/components/DataGridInstallationInstructions.js, docs/src/modules/components/PickersInstallationInstructions.js, packages/x-codemod/README.md, scripts/releaseChangelog.mjs
I iterated on https://www.notion.so/mui-org/MUI-X-Major-version-release-process-a27f296dfb9e4b33bdb767f3d6e8018c?d=f7462ff3fce140f68d7a67a2605270f2 to improve the swap experience.
Initially, I was only going to document this step missing https://www.notion.so/mui-org/MUI-X-Major-version-release-process-a27f296dfb9e4b33bdb767f3d6e8018c?pvs=4#d397efa2780a4cc1b7d9495277d8b05f (and did it to fix the strange demo live edit line text misalignment), but saw more stuff that are wrong, I couldn't help myself.
Preview: https://deploy-preview-11521--material-ui-x.netlify.app/x/introduction/
=> [docs] Complete transition to next branch

docs/next.config.js, docs/tsconfig.json
Same as https://github.com/mui/mui-toolpad/pull/3027
=> [docs] Lint next.config.js

docs/data/migration/migration-tree-view-v6/migration-tree-view-v6.md, docs/data/tree-view/rich-tree-view/expansion/TrackNodeExpansionToggle.js, docs/data/tree-view/rich-tree-view/expansion/TrackNodeExpansionToggle.tsx, docs/data/tree-view/rich-tree-view/expansion/TrackNodeExpansionToggle.tsx.preview, docs/data/tree-view/rich-tree-view/expansion/expansion.md, docs/data/tree-view/simple-tree-view/expansion/TrackNodeExpansionToggle.js, docs/data/tree-view/simple-tree-view/expansion/TrackNodeExpansionToggle.tsx, docs/data/tree-view/simple-tree-view/expansion/expansion.md
Bring back migration guide from #11476 (was lost in a merge) + add a doc example for the new prop.
=> [docs] Add example for TreeView `onNodeExpansionToggle` prop

docs/pages/x/api/data-grid/data-grid-premium.json, docs/pages/x/api/data-grid/data-grid-pro.json, docs/pages/x/api/data-grid/data-grid.json, docs/translations/api-docs/data-grid/data-grid-premium-pt.json, docs/translations/api-docs/data-grid/data-grid-premium-zh.json, docs/translations/api-docs/data-grid/data-grid-premium.json, docs/translations/api-docs/data-grid/data-grid-pro-pt.json, docs/translations/api-docs/data-grid/data-grid-pro-zh.json, docs/translations/api-docs/data-grid/data-grid-pro.json, docs/translations/api-docs/data-grid/data-grid-pt.json, docs/translations/api-docs/data-grid/data-grid-zh.json, docs/translations/api-docs/data-grid/data-grid.json, packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx, packages/grid/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx, packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx, packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts, packages/grid/x-data-grid/src/models/props/DataGridProps.ts
Merry christmas!
Fixes #11465 
I had the same issue as #11465 and changed the evaluation of hasEval so that it no longer writes a warning/error in the console in case eval is blocked by the csp. 
I also made disableEval appeir in the DataGrid API as per @flaviendelangle but I'm of course open to reverting this in case it's not wanted.
This change also makes it so that the eval check won't be executed if `filterMode='server'` regardless of the disableEval prop.
=> [DataGrid] Don't evaluate hasEval when disableEval is set

packages/x-charts/src/LineChart/formatter.ts
When using null or undefined in the data set, it was replaced by `0` whereas `null` now has the meaning of 'no data'
Discovered when doing https://github.com/mui/material-ui/pull/40107
=> [charts] Fix `null` in line chart using dataset

docs/data/charts/pie/pie.md, docs/pages/x/api/charts/pie-arc-label-plot.json, docs/pages/x/api/charts/pie-arc-plot.json, docs/translations/api-docs/charts/pie-arc-label-plot.json, docs/translations/api-docs/charts/pie-arc-plot.json, packages/x-charts/src/PieChart/PieArcLabel.tsx, packages/x-charts/src/PieChart/PieArcLabelPlot.tsx, packages/x-charts/src/PieChart/PieArcPlot.tsx, packages/x-charts/src/PieChart/PieChart.tsx, packages/x-charts/src/PieChart/PiePlot.tsx, packages/x-charts/src/PieChart/dataTransform/transition.ts, packages/x-charts/src/PieChart/dataTransform/useTransformData.ts, packages/x-charts/src/models/seriesType/pie.ts
Fix #11127
I kept the strategy of 100% is the maximal radius for same reason as before: having a single baseline for all radius dimensions
=> [charts] Add `arcLabelRadius` property

docs/data/date-pickers/timezone/LuxonTimezone.tsx, docs/data/date-pickers/timezone/LuxonUTC.tsx
Address https://github.com/mui/mui-x/issues/4751#issuecomment-1873898846
Be more explicit in the Luxon examples about the fact that the value can be in three states:
- Valid `DateTime`
- Invalid `DateTime`
- null
=> [docs] Clarify Pickers usage with Luxon

packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts
I was curious if we could improve this logic:
- `getRowId` was removed in #10897, no need to provide it as an argument anymore.
- Avoid the need for `atob('ZXZhbA==')`, it feels like obfuscation and fix #11046
- ~eval and new Function are by default sloopy https://2ality.com/2014/01/eval.html, made it strict.~
=> [DataGrid] Replace eval with new Function

packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx, packages/grid/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx, packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx, packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx
the warning doesn't follow the [guideline](https://www.notion.so/mui-org/Technical-writing-guidance-7e55b517ac2e489a9ddb6d0f6dd765de?pvs=4#85219822c3194b6f8a49ee08ea82b90a), so I updated it. More context in https://github.com/mui/mui-x/pull/11554#discussion_r1441871710.
=> [DataGrid] follow warning message guideline for `autoPageSize` and `autoHeight`

.circleci/config.yml, .github/workflows/l10n.yml, netlify.toml, package.json
Since Playwright v1.38.0, it does not download browsers automatically: https://github.com/microsoft/playwright/releases/tag/v1.38.0, so PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD is noise.
I found this by chance, I wanted to run the Karma tests for https://github.com/mui/material-ui/pull/39981 and went down a deep rabbit hole as I was trying to make sense of a few strange things in the codebase.
=> [core] Remove PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD

packages/x-charts/src/internals/domUtils.ts
This is the logic we use in Material UI. It doesn't seem to fall short in practice.
Sure React uses something more advanced https://github.com/facebook/react/blob/1d5667a1273386f84e416059af7b6aba069e068e/packages/shared/ExecutionEnvironment.js but it seems dead code. Preact which focuses on bundle size, seems to use a simpler version: https://github.com/preactjs/preact/blob/f7ccb9010077ecb46fc271224bbc5e015e00efe6/compat/src/render.js#L18.
Same idea as https://github.com/mui/material-ui/pull/40471
=> [core] Simplify isSsr logic

docs/src/modules/utils/postProcessImport.test.ts, docs/src/modules/utils/postProcessImport.ts
Noticed that after https://github.com/mui/mui-x/pull/11463 and specifically https://github.com/mui/mui-x/pull/11463/files#diff-41c21e2dc42b8c223fc2fa17580e58041afa590fe34d9fbe9a1ffbe5e17d318bL46 our demos using `@mui/x-date-pickers-pro/<adapterName>` import no longer work, because the regex doesn't account for the possibility of the adapter being imported from the pro package.
=> [docs] Fix parsing of `x-date-pickers-pro` demo adapter imports

packages/x-date-pickers/src/locales/index.ts, scripts/x-date-pickers-pro.exports.json, scripts/x-date-pickers.exports.json
This PR adds a missing export for the daDK locale in `packages/x-date-pickers/src/locales/index.ts`
=> [l10n] Add missing Danish (da-DK) locale export

package.json, renovate.json, yarn.lock
After merging https://github.com/mui/mui-x/pull/11303 I noticed that our CI pipeline became slower:
The difference is coming from the `test:unit` step:
| -- | -- |
| <img width="937" alt="Screenshot 2024-01-11 at 01 04 17" src="https://github.com/mui/mui-x/assets/13808724/c9345cda-8c6e-4fea-9d1f-85c0f1dbb99c"> | <img width="934" src="https://github.com/mui/mui-x/assets/13808724/26b5d5aa-0b6e-402b-a3cb-0211028e4e02"> |
Turns out, there was a CSS selector engine change in `jsdom` that causes a performance regression - see https://github.com/jsdom/jsdom/releases/tag/23.2.0
I've locked the `jsdom` version for now.
=> [core] Lock `jsdom` version

docs/data/data-grid/row-grouping/RowGroupingReadOnly.js, docs/data/data-grid/row-grouping/RowGroupingReadOnly.tsx, docs/data/data-grid/row-grouping/RowGroupingReadOnly.tsx.preview, docs/data/data-grid/row-grouping/row-grouping.md, packages/grid/x-data-grid-premium/src/components/GridColumnMenuRowGroupItem.tsx, packages/grid/x-data-grid-premium/src/components/GridPremiumColumnMenu.tsx, packages/grid/x-data-grid-premium/src/hooks/features/rowGrouping/gridRowGroupingSelector.ts, packages/grid/x-data-grid-premium/src/tests/rowGrouping.DataGridPremium.test.tsx
Handles `colDef.groupable` part of #10552
https://deploy-preview-11539--material-ui-x.netlify.app/x/react-data-grid/row-grouping/#read-only-row-groups
**ToDos:**
- Non-groupable columns could now be grouped programmatically to create read-only row groups by controlling or initializing `rowGroupingModel`, or by updating the `rowGroupingModel` by API method `apiRef.current.setRowGroupingModel`.
=> [DataGridPremium] Allow programmatically grouping non-groupable columns

docs/data/data-grid/pagination/pagination.md
This is a continuation of #9438. I saw this from https://github.com/mui/material-ui/issues/40589
Preview https://deploy-preview-11682--material-ui-x.netlify.app/x/react-data-grid/pagination/#page-size-options
=> [docs] Improve data grid `pageSizeOptions` prop documentation

docs/data/migration/migration-charts-v6/migration-charts-v6.md, docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md, docs/data/migration/migration-pickers-v6/migration-pickers-v6.md, docs/data/migration/migration-tree-view-v6/migration-tree-view-v6.md, packages/grid/x-data-grid-generator/package.json, packages/grid/x-data-grid-premium/README.md, packages/grid/x-data-grid-premium/package.json, packages/grid/x-data-grid-pro/README.md, packages/grid/x-data-grid-pro/package.json, packages/grid/x-data-grid/README.md, packages/grid/x-data-grid/package.json, packages/x-charts/README.md, packages/x-charts/package.json, packages/x-date-pickers-pro/README.md, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/README.md, packages/x-date-pickers/package.json, packages/x-tree-view/README.md, packages/x-tree-view/package.json
Needed to unblock https://github.com/mui/mui-x/pull/11480
We've discussed this question on eXplore weekly meeting and concluded that it shouldn't hurt to sync the required peer dep version to a more recent one when shipping a new major.
Currently, only the `TreeView` package has `variants`, but if we wanted to introduce (bring them back) to other packages, that would not be properly possible without requiring at least `5.15.0` of `@mui/material` due to https://github.com/mui/material-ui/pull/39623.
We also don't know what API we might end up needing during v7 that is only available in a more recent `@mui/material` release and at that point we'd be forced to either delay the change or release a slight BC during a minor release.
=> [core] Bump `@mui/material` peer dependency for all packages

docs/data/date-pickers/playground/playground.md, docs/data/pages.ts, docs/src/modules/components/PickersPlayground.tsx
This PR adds in some low-hanging design improvements to the Date and Time Pickers playground component. I've mostly standardized the styles here to other playground-like components we have throughout the Material UI docs. Additionally, I changed the place the "Playground" page was sitting relative to all other pickers pages — having it on the very first section makes more sense as it is a general tool (and also put the API reference close to the components pages).
One thing I'd appreciate help with is turning all the "true/false" radio button groups into switches. We can cut the unnecessary "false" and "true" labels there as well as simplify the interaction (switch is exactly for binary values! 😬). I left a start of this work on line 106 of the playground component! …
=> [docs] Uplift the Date Pickers playground

docs/data/data-grid/faq/faq.md, docs/data/pages.ts, docs/pages/x/react-data-grid/faq.js
=> [DataGrid] Start the FAQ page

docs/src/modules/components/PickersPlayground.tsx
Follow-up on https://github.com/mui/mui-x/pull/11555
I let some things slip through. 🙈 
P.S. Don't mind the slight difference in background colors, that's `deployed` vs `local` diff.
|--------|--------|
| ![Screenshot 2024-01-16 at 16 19 17](https://github.com/mui/mui-x/assets/4941090/fe82cc42-9fe6-4513-8dd4-69880e9de81f) | ![Screenshot 2024-01-16 at 16 19 27](https://github.com/mui/mui-x/assets/4941090/3bf43138-914b-4e83-8b83-8afb06493e08) | 
|--------|--------|
| ![Screenshot 2024-01-16 at 16 20 18](https://github.com/mui/mui-x/assets/4941090/16910385-13ff-4ac1-a69f-b0882da600fc) | ![Screenshot 2024-01-16 at 16 20 42](https://github.com/mui/mui-x/assets/4941090/74afe217-de40-4472-961b-e6559e1cfd6f) |
|--------|--------|
| …
=> [docs] Cleanup and fix Pickers Playground styling

docs/data/charts/bars/BarsDataset.tsx, docs/data/charts/bars/HorizontalBars.tsx, docs/pages/x/api/charts/spark-line-chart.json, packages/x-charts/src/BarChart/formatter.ts, packages/x-charts/src/ChartsTooltip/DefaultChartsItemTooltipContent.tsx, packages/x-charts/src/LineChart/formatter.ts, packages/x-charts/src/SparkLineChart/SparkLineChart.tsx, packages/x-charts/src/hooks/useAxisEvents.ts, packages/x-charts/src/models/seriesType/bar.ts, packages/x-charts/src/models/seriesType/common.ts, packages/x-charts/src/models/seriesType/line.ts
Using `valueFormatter: (value: TValue) => string` leads to `valueFormatter: (value: BarValueType & LineValueType & PieValueType) => string` when doing the union
Neest to use generic when defining function type
```ts
valueFormatter: <V extends TValue>(value: V) => string
```
Let me realised the bar charts did not have the typing for `null` which is weird
=> [charts] Remove a TS ignore

package.json, test/karma.conf.js
The DX of `karma-parallel` is bad when debugging a single test, this PR restores the behavior of `test:karma` and makes the parallel version available under a new command.
=> [core] make karma-parallel run under a new command

packages/x-charts/src/PieChart/PieArcLabel.tsx
Remove an error when plotting pie charts. Probably introduced when adding the support of `labelRadius`
=> [charts] Do not propagate `innerRadius` and `outerRadius` to the DOM

packages/grid/x-data-grid-pro/src/tests/columnHeaders.DataGridPro.test.tsx
Fixes https://app.circleci.com/pipelines/github/mui/mui-x/51160/workflows/1e35111b-7fee-4625-a11f-aa99294b099c/jobs/293100
I finally found the reason why this test fails sometimes.
The test itself is fine, it's the test that runs before it that doesn't have proper cleanup.
It starts resizing a column but never finishes the resizing. Somehow this impacted the test that was run next.
After adding the cleanup, I couldn't reproduce the issue locally anymore.
=> [test] Fix flaky Data Grid test

docs/data/migration/migration-tree-view-v6/migration-tree-view-v6.md, docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.js, docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.tsx, docs/data/tree-view/simple-tree-view/customization/IconExpansionTreeView.js, docs/data/tree-view/simple-tree-view/customization/IconExpansionTreeView.tsx, docs/data/tree-view/simple-tree-view/customization/customization.md, packages/x-codemod/README.md, packages/x-codemod/src/v7.0.0/tree-view/preset-safe/actual.spec.tsx, packages/x-codemod/src/v7.0.0/tree-view/preset-safe/expected.spec.tsx, packages/x-codemod/src/v7.0.0/tree-view/preset-safe/index.ts, packages/x-codemod/src/v7.0.0/tree-view/rename-use-tree-item/actual-nested-imports.spec.tsx, packages/x-codemod/src/v7.0.0/tree-view/rename-use-tree-item/actual-root-imports.spec.tsx, packages/x-codemod/src/v7.0.0/tree-view/rename-use-tree-item/expected-nested-imports.spec.tsx, packages/x-codemod/src/v7.0.0/tree-view/rename-use-tree-item/expected-root-imports.spec.tsx, packages/x-codemod/src/v7.0.0/tree-view/rename-use-tree-item/index.ts, packages/x-codemod/src/v7.0.0/tree-view/rename-use-tree-item/rename-use-tree-item.ts, packages/x-tree-view/src/TreeItem/TreeItemContent.tsx, packages/x-tree-view/src/TreeItem/index.ts, packages/x-tree-view/src/TreeItem/useTreeItemState.ts, scripts/x-tree-view.exports.json
We discussed it briefly during a meeting.
If we want a clean headless version of the `TreeItem`, we need to create a `useTreeItem` hook but the name is already taken by a utility hook.
=> [TreeView] Rename `useTreeItem` to `useTreeItemState`

docs/pages/x/api/date-pickers/date-range-calendar.json, docs/pages/x/api/date-pickers/date-range-picker-day.json, docs/pages/x/api/date-pickers/date-range-picker.json, docs/pages/x/api/date-pickers/desktop-date-range-picker.json, docs/pages/x/api/date-pickers/mobile-date-range-picker.json, docs/pages/x/api/date-pickers/multi-input-date-range-field.json, docs/pages/x/api/date-pickers/multi-input-date-time-range-field.json, docs/pages/x/api/date-pickers/multi-input-time-range-field.json, docs/pages/x/api/date-pickers/single-input-date-range-field.json, docs/pages/x/api/date-pickers/single-input-date-time-range-field.json, docs/pages/x/api/date-pickers/single-input-time-range-field.json, docs/pages/x/api/date-pickers/static-date-range-picker.json, scripts/buildApiDocs/chartsSettings/getComponentInfo.ts, scripts/buildApiDocs/pickersSettings/getComponentInfo.ts, scripts/buildApiDocs/treeViewSettings/getComponentInfo.ts
Parse the markdown in the `Component demos` list of titles.
https://next.mui.com/x/api/date-pickers/date-range-calendar/
=> [docs] Parse markdown on Pickers API docs demo titles

docs/babel.config.js, package.json, yarn.lock
~~Updated the path of the MuiError Babel macro.~~
Removed the rename-imports Babel macro as per https://github.com/mui/material-ui/pull/40262#issuecomment-1866107076
This should be merged after the monorepo sources containing https://github.com/mui/material-ui/pull/40262 are pulled in.
=> [code-infra] Update the Babel macro path

docs/scripts/api/buildApi.ts, docs/scripts/api/buildGridEventsDocumentation.ts, docs/scripts/api/buildGridSelectorsDocumentation.ts, docs/scripts/api/buildInterfacesDocumentation.ts, docs/scripts/api/utils.ts, docs/scripts/formattedTSDemos.js, docs/scripts/generateProptypes.ts, scripts/l10n.ts
Upcoming prettier deprecates those APIs. Rewriting these calls in advance to avoid cluttering the PR with new formatting changes
=> [code-infra] Migrate all prettier APIs to the async version

babel.config.js, docs/scripts/generateProptypes.ts, tsconfig.json
Extracted a few core fixes from https://github.com/mui/mui-x/pull/9528
Avoid the `Could not resolve` errors when running `proptypes` or `docs:api` scripts.
=> [core] Cleanup script and alias setup

docs/pages/x/api/date-pickers/mobile-date-range-picker.json, docs/pages/x/api/date-pickers/static-date-range-picker.json, docs/translations/api-docs/date-pickers/mobile-date-range-picker/mobile-date-range-picker.json, packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.types.ts, packages/x-date-pickers-pro/src/MobileDateRangePicker/MobileDateRangePicker.tsx, packages/x-date-pickers-pro/src/MobileDateRangePicker/MobileDateRangePicker.types.ts, packages/x-date-pickers-pro/src/StaticDateRangePicker/StaticDateRangePicker.tsx, packages/x-date-pickers-pro/src/StaticDateRangePicker/StaticDateRangePicker.types.ts
Extracted from https://github.com/mui/mui-x/pull/9528
Relevant commits with discussions from that PR: https://github.com/mui/mui-x/pull/9528/commits/6b772d9fe3d30018bccaa9f1d369874a23e1cee4, https://github.com/mui/mui-x/pull/9528/commits/4875a16e520fab0e3fcdd586a659b5b93500a1bb.
WDYT, should we ship it in v6 as well?
You could say that it is a BC, but at the same time - it never worked anyways and I'd say it's more of a (bug/TS)fix. 🤷
=> [DateRangePicker] Remove `calendars` prop on `Mobile`

packages/x-date-pickers/src/DateTimePicker/DateTimePickerTabs.tsx, packages/x-date-pickers/src/PickersLayout/pickersLayoutClasses.ts, packages/x-date-pickers/src/PickersLayout/usePickerLayout.tsx, packages/x-date-pickers/src/internals/models/props/tabs.ts
Extract bug-fix from https://github.com/mui/mui-x/pull/9528/commits/bb7d90bbc073ddc77baea8a9cd3a74a9444bab9f
=> [pickers] Apply the `layout.tabs` class to `Tabs` slot

docs/pages/x/api/tree-view/simple-tree-view.json, docs/pages/x/api/tree-view/tree-view.json, docs/translations/api-docs/tree-view/simple-tree-view/simple-tree-view.json, docs/translations/api-docs/tree-view/tree-view/tree-view.json, packages/x-tree-view/src/SimpleTreeView/SimpleTreeView.plugins.ts, packages/x-tree-view/src/SimpleTreeView/SimpleTreeView.tsx, packages/x-tree-view/src/TreeView/TreeView.tsx
Those props are specific to the `RichTreeView`
=> [TreeView] Remove unused props from prop-types and typing

packages/grid/x-data-grid/src/hooks/core/useGridApiInitialization.ts, packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx
I need this for https://github.com/mui/mui-x/pull/11164, where I use `apiRef` in the `sortComparator` for the grouping column + `sortingModel` in the `initialState`.
The demo throws an error, because when initial sorting happens the `apiRef` is not initialized yet (this is also the reason why [Netlify deployment fails](https://app.netlify.com/sites/material-ui-x/deploys/65afb15407d3a90008444ea9))
A simpler example to illustrate the issue:
Before: https://codesandbox.io/p/sandbox/gallant-wu-gh2svt
After: https://codesandbox.io/p/sandbox/heuristic-spence-nmkx2w
=> [DataGrid] Initialize `apiRef` early

packages/x-tree-view/src/internals/plugins/useTreeViewJSXNodes/useTreeViewJSXNodes.tsx, packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.test.tsx, packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.ts
Closes #10230
Not required before beta, nothing breaking here :+1:
=> [TreeView] Throw an error when two items have the same id

docs/translations/api-docs/date-pickers/date-time-picker-tabs/date-time-picker-tabs.json, docs/translations/api-docs/date-pickers/date-time-range-picker-tabs/date-time-range-picker-tabs.json, packages/x-date-pickers-pro/src/DateTimeRangePicker/DateTimeRangePickerTabs.tsx, packages/x-date-pickers-pro/src/DateTimeRangePicker/DateTimeRangePickerToolbar.tsx, packages/x-date-pickers-pro/src/DesktopDateTimeRangePicker/DesktopDateTimeRangePicker.types.ts, packages/x-date-pickers-pro/src/MobileDateTimeRangePicker/MobileDateTimeRangePicker.types.ts, packages/x-date-pickers-pro/src/internals/hooks/useDesktopRangePicker/useDesktopRangePicker.tsx, packages/x-date-pickers-pro/src/internals/hooks/useMobileRangePicker/useMobileRangePicker.tsx, packages/x-date-pickers-pro/src/themeAugmentation/components.d.ts, packages/x-date-pickers-pro/src/themeAugmentation/overrides.d.ts, packages/x-date-pickers-pro/src/themeAugmentation/props.d.ts, packages/x-date-pickers-pro/src/themeAugmentation/themeAugmentation.spec.ts, packages/x-date-pickers/src/DateTimePicker/DateTimePickerTabs.tsx, packages/x-date-pickers/src/internals/models/props/tabs.ts
Continuation of https://github.com/mui/mui-x/pull/9528
- Add new theme augmentation entries.
- Fix some inconsistently exported props.
=> [pickers] Add `DateTimeRangePicker` theme augmentation

docs/next.config.js, docs/package.json, netlify.toml, package.json
Cherry pick https://github.com/mui/mui-x/pull/11182
@oliviertassinari I've seen it because of ahrefs, but then realised it's only running on `mui.com/x` and not `next.mui.com/x`
So I added a crawler on the second one to be sure we are not blind on SEO during version migration
=> [docs] Fix <title> generation (#11182)

README.md, docs/data/introduction/support/support.md
My idea is to create a standard for the Support page, starting with MUI X.
To then go to the core and update Material UI support, create Base UI, MUI System support pages, etc. I'm not a fan of https://mui.com/material-ui/getting-started/support/.
Preview: https://deploy-preview-11556--material-ui-x.netlify.app/x/introduction/support/
=> [docs] Improve Support page

docs/data/charts/areas-demo/areas-demo.md, docs/data/charts/axis/axis.md, docs/data/charts/bar-demo/bar-demo.md, docs/data/charts/bars/bars.md, docs/data/charts/components/components.md, docs/data/charts/composition/composition.md, docs/data/charts/funnel/funnel.md, docs/data/charts/gantt/gantt.md, docs/data/charts/gauge/gauge.md, docs/data/charts/getting-started/getting-started.md, docs/data/charts/heat-map/heat-map.md, docs/data/charts/legend/legend.md, docs/data/charts/line-demo/line-demo.md, docs/data/charts/lines/lines.md, docs/data/charts/overview/overview.md, docs/data/charts/pie-demo/pie-demo.md, docs/data/charts/pie/pie.md, docs/data/charts/radar/radar.md, docs/data/charts/sankey/sankey.md, docs/data/charts/scatter-demo/scatter-demo.md, docs/data/charts/scatter/scatter.md, docs/data/charts/sparkline/sparkline.md, docs/data/charts/stacking/stacking.md, docs/data/charts/styling/styling.md, docs/data/charts/tooltip/tooltip.md, docs/data/charts/tree-map/tree-map.md, docs/data/date-pickers/custom-field/custom-field.md
Two updates:
- Remove reference to `PickersSectionList` which does not exist in v6
- Cherry pick https://github.com/mui/mui-x/pull/11832 to fix internal links to the charts API pages
=> [docs] Fix 404

docs/data/charts/areas-demo/areas-demo.md, docs/data/charts/axis/axis.md, docs/data/charts/bar-demo/bar-demo.md, docs/data/charts/bars/bars.md, docs/data/charts/components/components.md, docs/data/charts/composition/composition.md, docs/data/charts/funnel/funnel.md, docs/data/charts/gantt/gantt.md, docs/data/charts/gauge/gauge.md, docs/data/charts/getting-started/getting-started.md, docs/data/charts/heat-map/heat-map.md, docs/data/charts/legend/legend.md, docs/data/charts/line-demo/line-demo.md, docs/data/charts/lines/lines.md, docs/data/charts/overview/overview.md, docs/data/charts/pie-demo/pie-demo.md, docs/data/charts/pie/pie.md, docs/data/charts/radar/radar.md, docs/data/charts/sankey/sankey.md, docs/data/charts/scatter-demo/scatter-demo.md, docs/data/charts/scatter/scatter.md, docs/data/charts/sparkline/sparkline.md, docs/data/charts/stacking/stacking.md, docs/data/charts/styling/styling.md, docs/data/charts/tooltip/tooltip.md, docs/data/charts/tree-map/tree-map.md
> None of the links for the API work for the Chart components :/
>
> It is generally really difficult to understand how to get all the same feature set when using compositions because all the examples use the non-composition syntax. With the broken API links it is especially difficult.
>
> Thank you for this package, I'm looking forward to using it more. I <3 MUI
I removed the cherry pick because I integrated it in https://github.com/mui/mui-x/pull/11852
=> [docs] Fix charts API links

docs/data/data-grid/editing/CustomEditComponent.js, docs/data/data-grid/editing/CustomEditComponent.tsx, docs/data/data-grid/performance/GridVisualization.js, docs/data/data-grid/performance/GridVisualization.tsx, packages/grid/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx
Relates to https://github.com/mui/material-ui/pull/38762
=> [core] Rely on immutable ref when possible

docs/pages/x/api/date-pickers/time-picker-toolbar.json, docs/translations/api-docs/date-pickers/time-picker-toolbar/time-picker-toolbar.json, packages/x-date-pickers/src/TimePicker/timePickerToolbarClasses.ts
Fixes:
> New comment :-1:
>> CSS classes don't have description
> sent from https://mui.com/x/api/date-pickers/time-picker-toolbar/
https://mui-org.slack.com/archives/C04U3R2V9UK/p1706548112786409
=> [TimePicker] Add missing toolbar classes descriptions

packages/grid/x-data-grid/src/components/columnsManagement/GridColumnsManagement.tsx
Followup to #11770 as discussed in team meeting
Updates:
- Make Show/Hide All checkbox text normal case
- Have consistent spacing for Show/Hide All checkbox
For preview: https://deploy-preview-11858--material-ui-x.netlify.app/x/react-data-grid/#pro-plan
Todo after merge:
=> [DataGrid] Make columns management' casing consistent

packages/x-charts/src/BarChart/formatter.ts, packages/x-charts/src/ChartsTooltip/ChartsAxisTooltipContent.tsx, packages/x-charts/src/ChartsTooltip/DefaultChartsAxisTooltipContent.tsx, packages/x-charts/src/ChartsTooltip/utils.tsx, packages/x-charts/src/LineChart/formatter.ts
Fix #11893
If some series stop earlier, the default tooltip called the formatter with `undefined` which was no handled by the default formatter.
I tried to improve the typing, but not that much a success
=> [charts] Fix Tooltip crash with out of range lines

CHANGELOG.md, package.json, packages/grid/x-data-grid-generator/package.json, packages/grid/x-data-grid-premium/package.json, packages/grid/x-data-grid-pro/package.json, packages/grid/x-data-grid/package.json, packages/x-charts/package.json, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json
1. Checkout the last version of the working branch
2. `yarn && yarn release:build` (make sure you have the latest dependencies installed, and build the packages)
3. `yarn release:publish` (release the versions on npm, you need your 2FA device)
4. `yarn release:tag` (push the newly created tag)
Push the working branch on the documentation release branch to deploy the documentation with the latest changes.
```bash
git push -f upstream next:docs-next
```
Once deployed, it will be accessible at https://material-ui-x.netlify.app/ for the …
=> v7.0.0-beta.1

.eslintrc.js, docs/constants.js, docs/next.config.mjs, docs/package.json, docs/src/modules/utils/find.mjs, docs/src/modules/utils/findPages.js, docs/tsconfig.json, scripts/l10n.ts, tsconfig.json, yarn.lock
See https://github.com/mui/material-ui/pull/40869
I extracted a few constants into a separate cjs file, they are used in one of the scritps. ATM the scripts have poor ESM support. We'll improve that separately by ditching babel-node. We'll also think deeper about docs config once we start extracting more things into the next.js plugin.
=> [code-infra] Move next config to ESM

docs/data/charts/components/components.md, docs/data/charts/scatter-demo/scatter-demo.md, docs/data/charts/scatter/scatter.md, docs/data/tree-view/overview/overview.md, docs/pages/x/api/tree-view/tree-item.json, docs/pages/x/api/tree-view/tree-view.json
Fix 404 reported by ahrefs
Fix #11927
=> [docs] Fix API links

packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.test.tsx, packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts, test/utils/pickers/describeGregorianAdapter/testCalculations.ts
Fixes #11622
We used Luxon API for comparing equality, but it also includes some metadata in comparison (like locale the date was created it).
With this change, we are only going to compare the difference in time.
=> [pickers] Avoid relying on locale in Luxon `isWithinRange` method

docs/package.json, package.json
We no longer use `next export` - it was replaced by the `output: 'export'` flag in `next.config` in https://github.com/mui/mui-x/pull/11182.
Because of this change, we can no longer use `next start` to serve the production build locally.
This PR adds a replacement `docs:serve` script that serves the `export` folder locally.
=> [core] Add `docs:serve` script

docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md
Thought about opening this quick one as I saw [the table on the CSS classes section](https://next.mui.com/x/migration/migration-data-grid-v6/#css-classes) was broken. Also took the opportunity to do some very minor updates here and there — this is definitely _not_ a full revision. :)
https://deploy-preview-11806--material-ui-x.netlify.app/x/migration/migration-data-grid-v6/
=> [docs][Data Grid] Add quick fixes to the migration guide

packages/grid/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts
=> [data grid] Fix Unable to Paste Row Data in Data Grid with CAPS Lock Key Enabled

packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterPanel.tsx, packages/grid/x-data-grid/src/models/events/gridEventLookup.ts
=> [DataGrid] Add 'removeAllFilterItems' as a reason of `onFilterModelChange` callback

docs/data/charts/tooltip/tooltip.md
=> [docs] Fix `ChartsTooltip` typo

packages/x-tree-view/src/TreeItem/TreeItem.test.tsx, packages/x-tree-view/src/TreeItem/TreeItem.tsx, packages/x-tree-view/src/internals/plugins/useTreeViewJSXNodes/useTreeViewJSXNodes.tsx
Expandable state was not being detected correctly when multiple conditional arrays would return null. The resulting children prop in react created: `children: [Array(0), Array(0)]` which would set expandable to true. Changed logic to check for multiple different scenarios where children could would have content but be empty in the dom. 
Closes #11948
=> [TreeView] Correctly detect if an item is expandable

docs/data/date-pickers/adapters-locale/adapters-locale.md, docs/src/modules/components/PickersRenderingInstructions.js
Not the prettiest code :grimacing: 
But I think it will reduce the amount of people trying to use `AdapterDateFns` with the latest date-fns releases
=> [docs] Add a note about `AdapterDateFnsV3` on the Getting Started page

packages/x-data-grid/src/components/GridPagination.tsx, packages/x-data-grid/src/models/props/DataGridProps.ts
=> [DataGrid] Allow passing readonly arrays to `pageSizeOptions` prop

.github/styles/Blog/ComposedWords.yml, changelogOld/CHANGELOG.v5.md, docs/data/data-grid/column-pinning/column-pinning.md, docs/data/data-grid/editing/AskConfirmationBeforeSave.js, docs/data/data-grid/editing/AskConfirmationBeforeSave.tsx, docs/data/data-grid/editing/ServerSidePersistence.js, docs/data/data-grid/editing/ServerSidePersistence.tsx, docs/data/data-grid/filtering/QuickFilteringCustomLogic.js, docs/data/data-grid/filtering/QuickFilteringCustomLogic.tsx, docs/data/data-grid/filtering/index.md, docs/data/data-grid/filtering/quick-filter.md, docs/data/data-grid/pagination/pagination.md, docs/data/data-grid/row-grouping/row-grouping.md, docs/data/date-pickers/adapters-locale/adapters-locale.md, docs/data/date-pickers/validation/validation.md, docs/data/introduction/support/support.md, docs/data/migration/migration-pickers-v5/migration-pickers-v5.md, docs/data/tree-view/rich-tree-view/items/items.md, docs/scripts/reportBrokenLinks.js, packages/x-charts/src/ChartsReferenceLine/ChartsReferenceLine.tsx, packages/x-data-grid-pro/src/hooks/features/columnReorder/useGridColumnReorder.tsx, packages/x-data-grid/src/hooks/features/rows/useGridRows.ts, packages/x-data-grid/src/internals/utils/propValidation.ts, packages/x-data-grid/src/tests/rows.DataGrid.test.tsx
https://www.merriam-webster.com/grammar/cannot-vs-can-not-is-there-a-difference#:~:text=Both%20cannot%20and%20can%20not,general%2C%20it%20is%20somewhat%20informal.
=> [docs] Use "cannot" instead of "can't" or "can not"

docs/data/date-pickers/date-calendar/date-calendar.md, docs/data/date-pickers/date-field/CustomDateFormat.js, docs/data/date-pickers/date-field/CustomDateFormat.tsx, docs/data/date-pickers/date-field/CustomDateFormat.tsx.preview, docs/data/date-pickers/date-field/date-field.md, docs/data/date-pickers/date-picker/date-picker.md, docs/data/date-pickers/date-range-calendar/date-range-calendar.md, docs/data/date-pickers/date-range-field/date-range-field.md, docs/data/date-pickers/date-range-picker/date-range-picker.md, docs/data/date-pickers/date-time-field/CustomDateTimeFormat.js, docs/data/date-pickers/date-time-field/CustomDateTimeFormat.tsx, docs/data/date-pickers/date-time-field/CustomDateTimeFormat.tsx.preview, docs/data/date-pickers/date-time-field/date-time-field.md, docs/data/date-pickers/date-time-picker/date-time-picker.md, docs/data/date-pickers/date-time-range-field/date-time-range-field.md, docs/data/date-pickers/date-time-range-picker/date-time-range-picker.md, docs/data/date-pickers/digital-clock/digital-clock.md, docs/data/date-pickers/time-clock/time-clock.md, docs/data/date-pickers/time-field/CustomTimeFormat.js, docs/data/date-pickers/time-field/CustomTimeFormat.tsx, docs/data/date-pickers/time-field/CustomTimeFormat.tsx.preview, docs/data/date-pickers/time-field/time-field.md, docs/data/date-pickers/time-picker/time-picker.md, docs/data/date-pickers/time-range-field/time-range-field.md
Resolve topics discussed in https://mui-org.slack.com/archives/C04U3R2V9UK/p1707325208275059
- Consistently have `Localization` & `Validation` section in all Picker component pages
- Add callouts in `Customize the <x> format` sections to the `Custom format` documentation section
- Simplify demos by using `defaultValue` instead of `controlled value`
- Make `Validation` section copyright consistent
- Simplify `Localization` section copyright
=> [docs] Refactor `Localization` documentation sections

docs/pages/x/api/data-grid/data-grid-premium.json, docs/pages/x/api/data-grid/data-grid-pro.json, docs/pages/x/api/data-grid/data-grid.json, docs/translations/api-docs/data-grid/data-grid-premium/data-grid-premium.json, docs/translations/api-docs/data-grid/data-grid-pro/data-grid-pro.json, docs/translations/api-docs/data-grid/data-grid/data-grid.json, packages/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx, packages/x-data-grid/src/components/GridRow.tsx, packages/x-data-grid/src/components/GridScrollbarFillerCell.tsx, packages/x-data-grid/src/components/containers/GridRootStyles.ts, packages/x-data-grid/src/constants/gridClasses.ts, packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
Follow-up of https://github.com/mui/mui-x/pull/10059#issuecomment-1904425888
Restore the vertical scrolling performance.
Changes:
- Remove the `transform: translate(...)` style on cells and use an offset filler cell instead
- ~Remove the virtual scroller render zone DOM node, keep only the virtual scroller content and rename it to "centerContainer" to match the "topContainer" and "bottomContainer"~
=> [DataGrid] Vertical scrolling performance

docs/data/charts/lines/LineDataset.js, docs/data/charts/lines/LineDataset.tsx, docs/data/charts/tooltip/Formatting.js, docs/data/charts/tooltip/Formatting.tsx, docs/data/charts/tooltip/Formatting.tsx.preview, docs/pages/x/api/charts/spark-line-chart.json, packages/x-charts/src/SparkLineChart/SparkLineChart.tsx
I think we should avoid shorthands for the docs. It made me work harder to figure out how to do https://github.com/mui/mui-public/pull/147:
Before: https://next.mui.com/x/api/charts/spark-line-chart/#spark-line-chart-prop-valueFormatter
After: https://deploy-preview-12000--material-ui-x.netlify.app/x/api/charts/spark-line-chart/#spark-line-chart-prop-valueFormatter
=> [charts][docs] Avoid use of shorthand

packages/x-charts/src/PieChart/PieArc.tsx, packages/x-charts/src/PieChart/PieArcLabelPlot.tsx
Convention, helps with PRs conflicts.
Side note, it's kind of weird for `arcLabelMinAngle` to still render a `<text>` element but have it empty, maybe we could skip the text in the first place.
=> [core] Sort prop asc

docs/data/migration/migration-pickers-v6/migration-pickers-v6.md
Fix small typo in dayOfWeekFormatter modified props code sample.
Based on the example above it, there's a missing '}' that should be there.
=> [docs] Fix `dayOfWeekFormatter` typo in the pickers v6 to v7 migration document

yarn.lock
=> bump monorepo

docs/data/data-grid/events/events.json, docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md, docs/pages/x/api/data-grid/data-grid-premium.json, docs/pages/x/api/data-grid/data-grid-pro.json, docs/pages/x/api/data-grid/data-grid.json, docs/translations/api-docs/data-grid/data-grid-premium/data-grid-premium.json, docs/translations/api-docs/data-grid/data-grid-pro/data-grid-pro.json, docs/translations/api-docs/data-grid/data-grid/data-grid.json, packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx, packages/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx, packages/x-data-grid/src/DataGrid/DataGrid.tsx, packages/x-data-grid/src/models/events/gridEventLookup.ts, packages/x-data-grid/src/models/props/DataGridProps.ts
Closes #12071
- The `rowEditCommit` event and the related prop `onRowEditCommit` was removed. The [`processRowUpdate`](https://next.mui.com/x/react-data-grid/editing/#the-processrowupdate-callback) prop can be used in place.
=> [DataGrid] Remove legacy editing API event: `rowEditCommit`

docs/data/data-grid/custom-columns/EditingWithDatePickers.js, docs/data/data-grid/custom-columns/EditingWithDatePickers.tsx
=> [docs] Removed `focused` prop from demo

CHANGELOG.md, package.json, packages/x-charts/package.json, packages/x-data-grid-generator/package.json, packages/x-data-grid-premium/package.json, packages/x-data-grid-pro/package.json, packages/x-data-grid/package.json, packages/x-tree-view/package.json
```bash
git push -f upstream next:docs-next
```
=> v7.0.0-beta.3

docs/data/charts/gauge/ArcPlaygroundNoSnap.js, docs/data/charts/gauge/TextPlaygroundNoSnap.js, docs/data/charts/gauge/gauge.md, docs/data/pages.ts, docs/src/modules/components/ChartComponentsGrid.js
Just minor stuff I noticed while quickly browsing through the page — the commits should serve to tell what's in it! :)
https://deploy-preview-12076--material-ui-x.netlify.app/x/react-charts/gauge/
=> [charts][docs] Add small improvements to the Gauge page

packages/x-tree-view/src/internals/TreeViewProvider/DescendantProvider.tsx
=> [TreeView] Stop using custom `findIndex` to support IE11

packages/x-date-pickers/src/DateCalendar/tests/DateCalendar.test.tsx, packages/x-date-pickers/src/DateCalendar/useCalendarState.tsx
Fixes #12058
Backport main relevant fix from #10863.
=> [pickers] Fix `referenceDate` day calendar focus

docs/data/data-grid/column-definition/RenderExpandCellGrid.js, docs/data/data-grid/column-definition/RenderExpandCellGrid.tsx, packages/x-date-pickers/src/internals/components/PickersPopper.tsx
Per https://github.com/mui/material-ui/issues/40958#issuecomment-1951351873, It's safe to say that IE 11 will be entirely gone from Material UI v6, so it makes sense for MUI X v7 too. This is simpler to reason with and a bit smaller in bundle size.
I saw this in https://github.com/mui/mui-x/pull/11965
=> [core] Remove IE 11 compat logic

packages/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts, packages/x-data-grid/src/hooks/features/clipboard/useGridClipboard.ts, packages/x-data-grid/src/hooks/features/editing/useGridCellEditing.ts, packages/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts, packages/x-data-grid/src/internals/index.ts, packages/x-data-grid/src/utils/keyboardUtils.ts, packages/x-date-pickers/src/internals/hooks/useField/useField.ts
IMHO, if we close #11790, I think it should be after we fully fixed the issue. #11965 is a step, but there is more. Here is a quick PR to go more in depth:
- `toLowerCase` is missing in a good chunk of other cases
- We don't need a double if
- We can apply the same alternative keys check in all the other places
- Left a note about a bug in macOS but I suspect it's overkill to fix (not worth the extra bundle size)
=> [core] Fix shortcuts when Caps Lock enabled

packages/x-data-grid/src/components/columnSelection/GridCellCheckboxRenderer.tsx, packages/x-data-grid/src/hooks/features/editing/useGridCellEditing.ts, packages/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts, packages/x-data-grid/src/hooks/features/sorting/useGridSorting.ts, packages/x-data-grid/src/utils/keyboardUtils.ts
These helpers look like noise. I didn't remove them all to save time, but at least wanted to help make a step toward removing them.
I saw this in https://github.com/mui/mui-x/pull/11965.
=> [core] Simplify key utils

docs/data/charts/bars/bars.md, docs/pages/x/api/charts/spark-line-chart.json, docs/translations/api-docs/charts/spark-line-chart/spark-line-chart.json, packages/x-charts/src/SparkLineChart/SparkLineChart.tsx
Fix #12152
The bar animation has been added by error in sparkline with #9926 in the v6.0.0-alpha.16.
For v7 it has been removed by #11311
Since the behavior is here since the beginning of v6.0.0 I propose to add the `skipAnimation` props to sparkline to keep the same default as before, and keep v7 as it is
=> [charts] Allow to skip animation on sparkline bar

docs/package.json, docs/scripts/generateProptypes.ts, yarn.lock
This PR integrates changes from Core's https://github.com/mui/material-ui/pull/41079.
[It was decided](https://www.notion.so/mui-org/Publishing-internal-packages-87b7e5ec5a6b44ec8a2787e94ec34d8b?pvs=4#80eac69a4ad44503a962966873be5aca) that (almost) all the shared code-infra modules will be a part of a single @mui/internal-scripts package. This PR introduces this package in place of @mui-internal/typescript-to-proptypes.
=> [core] Use the @mui/internal-scripts package

docs/data/introduction/licensing/licensing.md
Address docs feedback:
> The "the relevant clause in the EULA." link doesn't jump to the intended section; it should now link to https://mui.com/legal/mui-x-eula/#2-5-required-quantity-of-licenses
sent from https://mui.com/x/introduction/licensing/#how-many-developer-seats-do-i-need (from section [How many developer seats do I need?)](https://mui.com/x/introduction/licensing/#how-many-developer-seats-do-i-need)
=> [docs] Fix "Licensing" page link

docs/data/data-grid/style-recipes/ColumnHeaderHideSeparator.js, docs/data/data-grid/style-recipes/ColumnHeaderHideSeparator.tsx, docs/data/data-grid/style-recipes/ColumnHeaderHideSeparator.tsx.preview, docs/data/data-grid/style-recipes/style-recipes.md
---
Adds a recipe that shows how to hide the separator (and with that the drag handle) on non-resizable columns.
Fixes #12017
=> [docs] Add recipe for hiding separator on non-resizable columns

docs/data/charts/axis/axis.md
Realised when answering #12161
That  `scaleType='point'`  is not documented.
It's a bit complex because normally it does not make sens to plot a line chart on categories. With categories you're supposed to use bar chart because their is not an obvious order relation between categories.
But i's usefull if for example you want to display yearly result without bothering with `Date` objects.
=> [docs] Add the 'point' scaleType to the axis documentation

docs/data/date-pickers/localization/data.json, packages/x-date-pickers/src/locales/koKR.ts
Cherry-pick https://github.com/mui/mui-x/pull/12186
=> [l10n] Improve Korean (ko-KR) locale (#12186) @Luzi

packages/x-data-grid-pro/src/tests/filtering.DataGridPro.test.tsx, packages/x-data-grid/src/hooks/features/filter/useGridFilter.tsx
Closes [11793](https://github.com/mui/mui-x/issues/11793)
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
=> [DataDrid] Fix `upsertFilterItems` removing filters that are not part of the update

packages/x-charts/src/ChartsGrid/ChartsGrid.tsx
=> [charts] Fix grid duplicated key

packages/x-data-grid-pro/src/tests/lazyLoader.DataGridPro.test.tsx, packages/x-data-grid/src/hooks/features/rows/useGridRows.ts
It seems there a sorting issue in combination with the lazy loader. When `unstable_replaceRows` is called having existing rows in a different order, `useGridRows` gives an error because it can't find rows because they have been deleted before. 
This behavior can be seen in the following demo. This is a fork of the lazy loading example from the documentation with rowLength adjusted to 10. To trigger the error simply change the order of the Name column.
https://codesandbox.io/s/nifty-pike-slzjmd?file=/src/Demo.tsx
This PR includes a suggested fix and test. Let me know if any change is needed and we're happy to update it.
=> [DataGridPro] Fix useGridRows not giving error on reversed data

docs/pages/x/api/date-pickers/date-picker-toolbar.json, docs/pages/x/api/date-pickers/date-range-picker-toolbar.json, docs/pages/x/api/date-pickers/date-time-picker-toolbar.json, docs/pages/x/api/date-pickers/date-time-range-picker-toolbar.json, docs/pages/x/api/date-pickers/time-picker-toolbar.json, docs/translations/api-docs/date-pickers/date-picker-toolbar/date-picker-toolbar.json, docs/translations/api-docs/date-pickers/date-range-picker-toolbar/date-range-picker-toolbar.json, docs/translations/api-docs/date-pickers/date-time-picker-toolbar/date-time-picker-toolbar.json, docs/translations/api-docs/date-pickers/date-time-range-picker-toolbar/date-time-range-picker-toolbar.json, docs/translations/api-docs/date-pickers/time-picker-toolbar/time-picker-toolbar.json, packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerToolbar.tsx, packages/x-date-pickers-pro/src/DateTimeRangePicker/DateTimeRangePickerToolbar.tsx, packages/x-date-pickers-pro/src/DesktopDateRangePicker/DesktopDateRangePicker.types.ts, packages/x-date-pickers-pro/src/MobileDateRangePicker/MobileDateRangePicker.types.ts, packages/x-date-pickers-pro/src/StaticDateRangePicker/StaticDateRangePicker.types.ts, packages/x-date-pickers-pro/src/themeAugmentation/props.d.ts, packages/x-date-pickers-pro/src/themeAugmentation/themeAugmentation.spec.ts, packages/x-date-pickers/src/DatePicker/DatePickerToolbar.tsx, packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx, packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx, packages/x-date-pickers/src/internals/components/PickersToolbar.tsx, packages/x-date-pickers/src/internals/models/props/toolbar.ts, packages/x-date-pickers/src/themeAugmentation/props.d.ts, packages/x-date-pickers/src/themeAugmentation/themeAugmentation.spec.ts
Noticed this problem when I started working on https://github.com/mui/mui-x/issues/12048 and discovered that I can't pass `data-testid` to the toolbar slot and hope that it ends up on the root element.
Checking the toolbar props more thoroughly I noticed that they are too loose, the current solution allows providing internal props, that ought to be passed only internally and can't be overridden via `defaultProps` in the theme.
This is technically a breaking change, but one that I'd say isn't very impactful to the user and technically is more of a bug fix.
WDYT about backporting it to v6? 🤔
=> [pickers] Fix toolbar components props handling

docs/.gitignore, docs/next.config.mjs
Allows for local next.js settings.
I use it to disable react strict mode.
=> [core] Allow local docs next.js settings

packages/x-data-grid/src/components/cell/GridCell.tsx
Closes #11891 
Cell range classnames weren't being updated because the cells aren't re-rendering as much as before.
=> [DataGrid] Fix cell range classnames

packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx, packages/x-data-grid-pro/src/tests/columns.DataGridPro.test.tsx, packages/x-data-grid-pro/src/tests/columnsVisibility.DataGridPro.test.tsx
=> [data grid]  fix onColumnWidthChange called before autosize affects column width

packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx
Preview: https://deploy-preview-12233--material-ui-x.netlify.app/x/react-data-grid/column-pinning/#initializing-the-pinned-columns
Fixes:
https://github.com/mui/mui-x/assets/13808724/ae9e18f9-0f36-4508-967e-2e4ae98c052f
=> [DataGrid] Fix wrong offset for right-pinned columns when toggling dark/light modes

packages/x-data-grid/src/components/columnSelection/GridCellCheckboxRenderer.tsx
The cell checkbox renderer is calling `.querySelector` via an API function on each render.
=> [DataGrid] perf: remove querySelector call

scripts/buildApiDocs/chartsSettings/getComponentInfo.ts, scripts/buildApiDocs/gridSettings/getComponentInfo.ts, scripts/buildApiDocs/pickersSettings/getComponentInfo.ts, scripts/buildApiDocs/treeViewSettings/getComponentInfo.ts
Follow up on #11946
This folder no longer exists
=> [core] Remove grid folder from `getComponentInfo` RegExp

packages/x-data-grid/src/components/columnsManagement/GridColumnsManagement.tsx
It was not possible to render either reset or show/hide - redundant logical check allowed only both on or off. disableShowHideToggle and disableResetButton are still checked at next lines.
=> [DataGrid] Fix `disableResetButton` and `disableShowHideToggle` flags to not exclude each other

packages/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts, packages/x-data-grid-premium/src/tests/clipboard.DataGridPremium.test.tsx
=> [DataGridPremium] Make clipboard copy respect the sorting during cell selection

packages/grid/x-data-grid-pro/src/tests/lazyLoader.DataGridPro.test.tsx, packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts
Cherry-pick of https://github.com/mui/mui-x/pull/10821
=> [DataGridPro] Fix lazy loading error when existing rows are passed to replaceRows (@martijn-basesoft)

CHANGELOG.md, package.json, packages/x-charts/package.json, packages/x-data-grid-generator/package.json, packages/x-data-grid-premium/package.json, packages/x-data-grid-pro/package.json, packages/x-data-grid/package.json, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json, packages/x-tree-view/package.json
```bash
```
You can follow the deployment process [on the Netlify Dashboard](https://app.netlify.com/sites/material-ui-x/deploys?filter=docs-v6)
Once deployed, it will be accessible at https://material-ui-x.netlify.app/ for the `docs-v6` deployment.
=> v7.0.0-beta.5

docs/pages/x/api/tree-view/rich-tree-view.json, docs/pages/x/api/tree-view/simple-tree-view.json, docs/pages/x/api/tree-view/tree-view.json, packages/x-tree-view/src/RichTreeView/RichTreeView.tsx, packages/x-tree-view/src/SimpleTreeView/SimpleTreeView.tsx, packages/x-tree-view/src/TreeView/TreeView.tsx, packages/x-tree-view/src/hooks/useTreeViewApiRef.tsx, packages/x-tree-view/src/internals/plugins/useTreeViewFocus/useTreeViewFocus.types.ts, packages/x-tree-view/src/internals/plugins/useTreeViewJSXNodes/useTreeViewJSXNodes.tsx, packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.ts, packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.types.ts
Closes #10957
Not sure why but I can't use the PR package on Codesandbox :thinking: 
Here is a basic usage of the method if you want to test it:
```tsx
import Box from '@mui/material/Box';
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import { TreeViewBaseItem } from '@mui/x-tree-view/models';
import { RichTreeView } from '@mui/x-tree-view/RichTreeView';
import {useTreeViewApiRef} from "@mui/x-tree-view";
const MUI_X_PRODUCTS: TreeViewBaseItem[] = [
{
id: 'grid',
label: 'Data Grid',
children: [
{ id: 'grid-community', label: '@mui/x-data-grid' },
{ id: 'grid-pro', label: '@mui/x-data-grid-pro' },
{ id: 'grid-premium', label: '@mui/x-data-grid-premium' },
],
},
{
id: 'pickers',
label: 'Date and Time Pickers', …
```
=> [TreeView] New instance and publicAPI method: `getItem`

packages/x-data-grid-generator/src/renderer/renderEditRating.tsx
fixes 2nd bug mentioned in this comment https://github.com/mui/mui-x/issues/12199#issuecomment-1966227917
PR for 1st point --> https://github.com/mui/mui-x/pull/12335
preview: https://deploy-preview-12315--material-ui-x.netlify.app/x/react-data-grid/filtering/quick-filter/
=> [data-grid] Fix crashing of demos on rating change

packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.ts
When using the following code:
```tsx
const ITEMS = [{ id: '1', label: 'Item 1' }]
<RichTreeView id="my-tree" items={ITEMS} />
```
Will produce the following HTML:
```html
<ul id="my-tree">
<li class="MuiTreeItem-root" id="1" />
</ul>
```
With this behavior, it is very very easy to unintentionally set an id attribute to your item that is not unique in the whole document.$
No setting the id attribute in state allows us to use the fallback which is `${treeId}-${nodeId}`:
```html
<ul id="my-tree">
<li class="MuiTreeItem-root" id="my-tree-1" />
</ul>
```
We could add a new prop `getItemIdAttribute` to help people customize the id attribute.
Otherwise, they risk to do ugly things such as:
```tsx
<RichTreeView
items={ITEMS}
slotProps={{
item: ({ someProp }) => ({ id: someProp }),
}}
/>
```
And …
=> [TreeView] In the `RichTreeView`, do not use the item id as the HTML id attribute

packages/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx, packages/x-data-grid/src/components/virtualization/GridVirtualScrollerFiller.tsx
=> [DataGrid] Fix double border under header

packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.ts
Regression introduced in #12251, never released
=> [TreeView] Fix invalid nodes state when updating `props.items`

packages/x-charts/src/ChartsLegend/DefaultChartsLegend.tsx, packages/x-charts/src/PieChart/PieChart.tsx, packages/x-charts/src/internals/useIsRTL.ts
Fix #12118
Maybe I should invert the order of square/text : put the square on the right of the text @samueltrevor do you have some insight on this aspect?
=> [charts] Fix RTL legend

docs/src/modules/components/WhatsNewLayout.js
This change brings two main things:
- Use a full brand name to help position each component as a standalone.
- Use an exact version number to help anchor the change to a specific version to install.
Before: https://deploy-preview-12307--material-ui-x.netlify.app/x/whats-new/
After: https://deploy-preview-12309--material-ui-x.netlify.app/x/whats-new/
---
I saw these opportunities from #11396 while I was reviewing the AG Grid's design teamwork on https://ag-grid.com/whats-new/. As far as I could audit it, it wasn't done by them but one of the engineers on the team https://github.com/ag-grid/ag-grid/blame/v31.0.1/grid-packages/ag-grid-docs/documentation/src/pages/whats-new.module.scss. So nothing much to learn from this other than: there is a clear gap in design execution that wasn't/isn't …
=> [docs] Polish What's new in MUI X blog titles

packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx
A quick win, I noticed this by chance, providing an example in #12401. It's a small regression from #10059.
Before:
https://github.com/mui/mui-x/assets/3165635/1d0e3081-2be4-4d57-b828-c587e0a8dbb0
After:
https://github.com/mui/mui-x/assets/3165635/71e461e4-b774-4032-a064-f9873dcabd26
Similar to https://github.com/mui/material-ui/pull/9147 but also different. There are no focus rings for scroll containers, it's not what end-users expect.
BTW, great to see that the keyboard actually works, it doesn't on AG Grid 🙈, a positive differentiator 👍
=> [data grid] Fix focus visible style on scrollbar

packages/x-date-pickers/src/DateCalendar/tests/DateCalendar.test.tsx, packages/x-date-pickers/src/internals/utils/date-utils.test.ts, packages/x-date-pickers/src/internals/utils/date-utils.ts
Fixes #12373 
We currently reset the selected date to `startOfDay` when doing `findClosestEnabledDate`.
It seems incorrect - using (merging) the existing/requested time part seems to make more sense... 🤷
=> [pickers] Keep the existing time when looking for closest enabled date

CHANGELOG.md, docs/data/date-pickers/adapters-locale/adapters-locale.md, docs/data/migration/migration-pickers-v6/migration-pickers-v6.md
Noticed while testing week starts on behavior on various adapters.
=> [docs] Add missing luxon `Info` import

docs/pages/x/api/data-grid/data-grid-premium.json, docs/pages/x/api/data-grid/data-grid-pro.json, docs/pages/x/api/data-grid/data-grid.json, docs/translations/api-docs/data-grid/data-grid-premium/data-grid-premium.json, docs/translations/api-docs/data-grid/data-grid-pro/data-grid-pro.json, docs/translations/api-docs/data-grid/data-grid/data-grid.json, packages/x-data-grid/src/joy/joySlots.tsx, packages/x-data-grid/src/material/index.ts, packages/x-data-grid/src/models/gridSlotsComponent.ts
Following the column management panels refactor, we don't use the switch anymore.
=> [DataGrid] Remove baseSwitch

packages/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx, packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts
Fixes https://github.com/mui/mui-x/issues/12431
Before: https://codesandbox.io/p/sandbox/nervous-dijkstra-9x2hv6
After: https://codesandbox.io/p/sandbox/vibrant-drake-5ngz8x
TODO:
=> [DataGridPro] Fix filler rendered for no reason when there are pinned columns

packages/x-data-grid/src/hooks/features/editing/useGridCellEditing.ts, packages/x-data-grid/src/tests/keyboard.DataGrid.test.tsx
Fix #12125  [michelengelen](https://github.com/michelengelen)
This PR refines the value reset logic to align with column data types on Backspace/Delete key press.
UnitTesting
Implemented tests to check cell value reset upon Backspace and Delete key presses.
The video shows the correct default boolean value when the delete/backspace key is pressed.
=> [data grid] Fixed issue where pressing Delete key resets various cell values to empty string.

docs/data/charts/tooltip/tooltip.md, docs/pages/x/api/charts/bar-chart.json, docs/pages/x/api/charts/charts-legend.json, docs/pages/x/api/charts/charts-tooltip.json, docs/pages/x/api/charts/default-charts-legend.json, docs/pages/x/api/charts/line-chart.json, docs/pages/x/api/charts/pie-chart.json, docs/pages/x/api/charts/scatter-chart.json, docs/pages/x/api/charts/spark-line-chart.json, docs/translations/api-docs/charts/bar-chart/bar-chart.json, docs/translations/api-docs/charts/charts-legend/charts-legend.json, docs/translations/api-docs/charts/charts-tooltip/charts-tooltip.json, docs/translations/api-docs/charts/default-charts-legend/default-charts-legend.json, docs/translations/api-docs/charts/line-chart/line-chart.json, docs/translations/api-docs/charts/pie-chart/pie-chart.json, docs/translations/api-docs/charts/scatter-chart/scatter-chart.json, docs/translations/api-docs/charts/spark-line-chart/spark-line-chart.json, packages/x-charts/src/ChartsLegend/ChartsLegend.tsx, packages/x-charts/src/ChartsLegend/DefaultChartsLegend.tsx, packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx, packages/x-charts/src/models/axis.ts
Fix #12268
Fix #10352
- First commit ass some slots definition for the tooltip and axis
- Second commit is the result of `yarn proptypes & yarn docs:api`
- Third commit is adding a section in tooltip to show how to use those slots
=> [docs] Improve slots definitions for charts

CHANGELOG.md, package.json, packages/x-charts/package.json, packages/x-codemod/package.json, packages/x-data-grid-generator/package.json, packages/x-data-grid-premium/package.json, packages/x-data-grid-pro/package.json, packages/x-data-grid/package.json, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json, packages/x-tree-view/package.json
1. Checkout the last version of the working branch
2. `yarn && yarn release:build` (make sure you have the latest dependencies installed, and build the packages)
3. `yarn release:publish` (release the versions on npm, you need your 2FA device)
4. `yarn release:tag` (push the newly created tag)
Push the working branch on the documentation release branch to deploy the documentation with the latest changes.
```bash
git push -f upstream next:docs-next
```
Once deployed, it will be accessible at https://material-ui-x.netlify.app/ for the …
=> v7.0.0-beta.7

packages/x-charts/src/context/CartesianContextProvider.tsx
Just noticed this in a callstack
=> [charts] Fix small typo in `CartesianContextProvider`

packages/x-license/src/utils/licenseErrorMessageUtils.ts
=> [license] Fix grammar on expired license error message

packages/x-data-grid/src/components/GridPagination.tsx, packages/x-data-grid/src/components/cell/GridActionsCellItem.tsx
Fixes https://github.com/mui/material-ui/issues/40427 for the data grid
| ------  | ----- |
| <img width="522" src="https://github.com/mui/mui-x/assets/13808724/0cc9b060-8bad-475d-8a7c-17b965b984d4"> | <img width="519" src="https://github.com/mui/mui-x/assets/13808724/7302f2f5-9cc6-4c82-9bdc-e408866b92dd"> |
In `GridPanel`, you can still see generics being passed to `React.ElementType`, but this was solved on the Core side in https://github.com/mui/material-ui/pull/41500
It's hard to test because it requires a different version of `@types/react` than we use in our monorepo.
I've created a branch in https://github.com/cherniavskii/cra-data-grid-test/tree/react17
Before:
```sh
npx tsc --skipLibCheck false
node_modules/@mui/base/Unstable_Popup/Popup.d.ts:13:70 - error …
```
=> [DataGrid] Fix `ElementType` usage

packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts, packages/x-date-pickers/src/DateField/tests/format.DateField.test.tsx, packages/x-date-pickers/src/internals/hooks/useField/buildSectionsFromFormat.ts
=> [fields] Support format without separator

docs/data/charts/getting-started/getting-started.md, docs/data/migration/migration-tree-view-v6/migration-tree-view-v6.md
=> [docs] Remove mentions of pre release

docs/data/date-pickers/validation/validation.md, docs/pages/x/api/date-pickers/date-time-range-picker.json, docs/pages/x/api/date-pickers/desktop-date-time-range-picker.json, docs/pages/x/api/date-pickers/mobile-date-time-range-picker.json, packages/x-date-pickers-pro/src/DateTimeRangePicker/DateTimeRangePicker.tsx, packages/x-date-pickers-pro/src/DesktopDateTimeRangePicker/DesktopDateTimeRangePicker.tsx, packages/x-date-pickers-pro/src/MobileDateTimeRangePicker/MobileDateTimeRangePicker.tsx
- Add missing `DateTimeRangePicker` components JSDoc with `Demos` and `API` links
- Add `DateTimeRangePicker` family components to the `validation` page list so that they are included in the API page link
=> [DateTimeRangePicker] Add component `JSDoc`

.browserslistrc
Follow-up on https://github.com/mui/mui-x/pull/12151.
=> [core] Remove leftover `legacy` `browserlistrc` entry

.browserslistrc, yarn.lock
Follow up on https://github.com/mui/mui-x/pull/12415#discussion_r1520254716.
The [coverage seems](https://browsersl.ist/#q=%3E0.5%25%2C+last+2+versions%2C+Firefox+ESR%2C+not+dead%2C+safari+%3E%3D+15.4%2C+iOS+%3E%3D+15.4) pretty good.
Respective Core PR: https://github.com/mui/material-ui/pull/41568
I omitted the `node` major bump (it could also be a separate PR as it's a bit different topic) until we have a green light from Core and we agree that this makes sense for us, where MUI-X v7 will be released quite a bit sooner than `@mui/material`.
WDYT @mui/x @mui/code-infra?
- Update `caniuse-lite` to benefit from latest data
- Run the command and update entries (including `safari >=15.4`)
=> [core] Update supported browsers (browserlistrc)

packages/x-date-pickers-pro/src/MobileDateTimeRangePicker/MobileDateTimeRangePicker.tsx
Fixes a regression where on mobile after selecting start time the view switches to end time instead of end date.
Caused by https://github.com/mui/mui-x/pull/12441/files#diff-3486b9e595ab1f393c7d593c337d48b0dfcde196e3d1f2b0fc641bba34f895abR108
Unblocking the release for now.
Will investigate why the test was not failing locally and reliably and how to make the view switching less fragile.
=> [DateTimeRangePicker] Fix views behavior regression

docs/data/data-grid/localization/data.json, docs/data/date-pickers/localization/data.json, docs/next.config.js
Links to github translation are wrong, because the grid flatten it's folder path from `/grid/x-data-grid` to `/x-data-grid`
But I assume other links will probably break if we don't update the nextjs config
=> [docs] These API don't exist in MUI X v6

scripts/l10n.ts
Avoids incorrect path building on Windows.
Example: https://github.com/mui/mui-x/pull/12547/commits/da87e358d0c37462c1e53ca7659deff15b6e9aba
P.S. Tested on a local Windows machine.
=> [core] Fix `l10n` script on Windows

packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx, packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx
Close #12459
Avoid using a ref that may be undefined.
Before: https://codesandbox.io/p/sandbox/mui-x-datagrid-issue-12459-tl2vy4
After: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-q5lln4
=> [DataGrid] Fix bug in suspense

packages/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx
When creating a custom toolbar in DataGrid with GridToolbarQuickFilter, GridToolbarQuickFilter would not have MuiDataGrid-toolbarQuickFilter rendered as expected.
Fixes [https://github.com/mui/mui-x/issues/12400](https://github.com/mui/mui-x/issues/12400)
=> [DataGrid] Fix missing class name rendered to GridToolbarQuickFilter

packages/x-date-pickers/src/DateField/tests/selection.DateField.test.tsx, packages/x-date-pickers/src/internals/hooks/useField/useField.ts, test/e2e/fixtures/DatePicker/BasicDesktopDatePickerV6.tsx, test/e2e/index.test.ts
Fixes #12574 
- Add e2e tests asserting that current focusing behavior after clearing value is broken
- Call `isFieldFocused` function instead of only checking it's existence
=> [fields] Fix input refocusing after clearing a value

packages/x-date-pickers/src/DesktopDatePicker/tests/field.DesktopDatePicker.test.tsx, packages/x-date-pickers/src/internals/hooks/useField/useField.types.ts, packages/x-date-pickers/src/internals/hooks/useField/useFieldV6TextField.ts
=> [fields] Fix placeholder override

packages/x-date-pickers-pro/src/DesktopDateRangePicker/tests/DesktopDateRangePicker.test.tsx, packages/x-date-pickers-pro/src/internals/hooks/useEnrichedRangePickerFieldProps.ts, packages/x-date-pickers/src/internals/hooks/useField/useFieldV6TextField.ts, test/e2e/fixtures/DatePicker/ReadonlyDesktopDateRangePickerSingleV6.tsx, test/e2e/fixtures/DatePicker/ReadonlyDesktopDateRangePickerSingleV7.tsx, test/e2e/index.test.ts
Fixes #12576 
- Avoid calling `setSelectedSection` which forces the range position to be changed after the picker is opened
This seems to function more similarly to how v7 behavior works.
- Fix `focused` styling behavior on range Pickers using a single input field.
The input received a `focused` state only when the Picker was opened.
Now the behavior is better aligned with all other Pickers (including the Range Pickers using multiple fields).
- Add tests for both cases.
=> [DateRangePicker] Fix selection behavior with single input field when readonly

packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx
Discovered when doing demos for #12490 that the y axis was not reacting when providing the `ticInterval`
=> [charts] Fix `ticInterval` usage for y-axis

docs/package.json, yarn.lock
Checked https://github.com/mui/mui-x/pull/12598 and noticed that this package is not used anywhere explicitly.
I think that we can keep it as a transitive dependency of `@slack/bolt` unless I'm missing something.
=> [core] Remove explicit `express` package

packages/x-date-pickers-pro/src/DesktopDateTimeRangePicker/tests/DesktopDateTimeRangePicker.test.tsx, packages/x-date-pickers-pro/src/internals/utils/date-range-manager.test.ts, packages/x-date-pickers-pro/src/internals/utils/date-range-manager.ts
Fixes #12586
The problem was that we were using `isBefore` to compare the dates when calculating the new range.
This works for `DateRangePicker`, but in the case of `DateTimeRangePicker` its a problem, because it includes time in comparison.
Changed the comparison function to `isBeforeDay` instead.
=> [DateTimeRangePicker] Fix selection on same day

package.json, packages/x-date-pickers-pro/src/DesktopDateRangePicker/tests/DesktopDateRangePicker.test.tsx, packages/x-date-pickers-pro/src/internals/hooks/useEnrichedRangePickerFieldProps.ts, packages/x-date-pickers/src/internals/hooks/useField/useField.ts, test/e2e/fixtures/DatePicker/ReadonlyDesktopDateRangePickerSingle.tsx, test/e2e/index.test.ts, yarn.lock
Cherry-pick of https://github.com/mui/mui-x/pull/12593
Keep changes only relevant for v6.
=> [DateRangePicker] Fix selection behavior with single input field when `readOnly`

packages/x-date-pickers/src/internals/hooks/useField/useFieldV6TextField.ts
Apply the same, more proper and isolated fix for https://github.com/mui/mui-x/issues/12576 as in https://github.com/mui/mui-x/pull/12605/files#diff-dc059fc96319bb9a9af78bcdf3a3fe9fb3249209a369e7be34ef104d22afad25R519.
=> [fields] Fix `readOnly` behavior

scripts/releaseChangelog.mjs
Fix the problem with incorrectly placed `l10n` and `i18n` PRs.
They are now being always assumed to belong to the `DataGrid` package, whereas `pickers` probably receives even more `l10n` contributions.
We are already fetching information about every PR.
I've added extra logic to use the labels added to a certain PR to put the PR message in the correct package.
> [!IMPORTANT]
> This relies on us assigning a correct package label on any `l10n` or `i18n` PR.
=> [core] Use PR labels to identify the package a `l10n` PR belongs to

docs/data/charts/pie/PieShapeNoSnap.js
just to quicken the copy paste process when trying to play with this demo in local
=> [docs] Fix missing closing props in `PieShapeNoSnap` demo

docs/data/data-grid/localization/data.json, packages/x-data-grid/src/locales/ptBR.ts
=> [l10n] Improve Portuguese (pt-BR) locale

docs/data/tree-view/rich-tree-view/customization/IconExpansionTreeView.js, docs/data/tree-view/rich-tree-view/customization/IconExpansionTreeView.tsx, docs/data/tree-view/rich-tree-view/customization/IconExpansionTreeView.tsx.preview
I missed this one when creating `TreeItem2`
=> [docs] Use `TreeItem2` for icon expansion example on `RichTreeView`

packages/x-tree-view/src/SimpleTreeView/SimpleTreeView.test.tsx, packages/x-tree-view/src/TreeItem/TreeItem.test.tsx, packages/x-tree-view/src/internals/plugins/useTreeViewExpansion/useTreeViewExpansion.test.tsx, packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.test.tsx, test/utils/tree-view/describeTreeView/describeTreeView.tsx, test/utils/tree-view/describeTreeView/describeTreeView.types.ts
Part of #12433
Most tests are just migration with unified API from existing tests.
I did not remove any test.
I have doubt about some of the current behaviors, which IMHO are not what the ARIA spec describes (clicking on a selected item in single selection does not un-select it, but the specs say that it should "toggle" the selection). But for now I migrated all the tests without touching the behaviors to avoid mixing the two.
=> [core] Use `describeTreeView` for selection tests

.github/workflows/closed-issue-message.yaml
I did a quick dive into the comment experience with this PR:
1. Output tested in https://github.com/mui/mui-x/issues/12594#issuecomment-2025413729. This feels easier to parse and understand.
2. Also made it so that we can use https://tally.so/forms/w4r5Mk/edit with other products.
3. And did a quick-win when the rating left is equal to 5:
https://tally.so/forms/w4r5Mk. This executes https://www.notion.so/mui-org/mui-x-Gather-reviews-on-a-third-party-website-8be4fc85bcb34974a7d62cd74750e383?pvs=4#65c912f218a041c8958e7f84947ac8c2.
4. I have also documented the thing in https://www.notion.so/mui-org/Technical-Support-80c9c7e0af614af68c1abb7120f634c8?pvs=4#d0e2a3e120fe415b869506fa3ed88748. 
---
Going forward, I think that it would be great to invest in metrics. I have added these ideas to …
=> [infra] Polish support survey experience

.circleci/config.yml
This is a continuation of https://github.com/mui/mui-x/pull/8796.
We again started occasionally seeing 137 errors: https://app.circleci.com/pipelines/github/mui/mui-x/55996/workflows/3785ca42-1a35-41fb-945a-6672ab60ff50/jobs/320388/steps
I assume that the memory limit applies to a single node instance.
Given that Lerna runs 3 concurrent instances at a single point in time, it would mean that theoretically we currently allow a maximum of 9GB of RAM to be used. 🙈 
It doesn't seem to impact the step runtime in a significant way that couldn't be attributed to a difference between runs:
| ------- | ----- |
| ![Screenshot 2024-04-03 at 17 52 28](https://github.com/mui/mui-x/assets/4941090/368dbf7d-79a0-4345-9573-fb5f31c36280) | ![Screenshot 2024-04-03 at 17 52 …
=> [core] Limit `test-types` CI step allowed memory

.github/workflows/cherry-pick-master-to-v6.yml
Add an action, which would cherry-pick a PR merged to master into a `v6.x` branch if it would have a `needs cherry-pick` label.
Could be useful for bug fixes during the v7 development / v6 maintenance mode.
=> [core] Add cherry-pick `master` to `v6` action

docs/data/data-grid/row-selection/CheckboxSelectionVisibleOnlyGrid.js, docs/data/data-grid/row-selection/CheckboxSelectionVisibleOnlyGrid.tsx, docs/data/data-grid/row-selection/row-selection.md
---
This adds a new demo to the selection page in the docs to show the behaviour of the `checkboxSelectionVisibleOnly` prop.
This came up in #12625
=> [docs] Adds a recipe for the `checkboxSelectionVisibleOnly` prop

.github/workflows/closed-issue-message.yaml
---
the default username that gets checked is the one that triggered the state change (closed the issue), but for this we need to check if the user that opened the issue has the required permissions.
It also fixes the result check to use booleans
=> [support-infra] fixes user permission check

docs/data/migration/migration-data-grid-v6/ColDefChangesGridNoSnap.js
Fixes #12628
No need to allow column menu operations on this demo, since this is mostly meant for informational purposes
=> [DataGrid] Fix `ColDefChangesGridNoSnap` demo crash

packages/x-data-grid-generator/src/hooks/useQuery.ts
Fixes #12661
We updated the signature of ApplyFilterFunction in [this PR](https://github.com/mui/mui-x/pull/9254/files#diff-a5d39315fa266575b09805ca877789bd276c55b17ddb8ea3d271803bcd9eec29R12-R17) but didn't update it in `useQuery`. In v7, when we [removed](https://github.com/mui/mui-x/pull/10897) the legacy filter, the demo started to break.
I first spotted and fixed it in #12317, but a separate fix would be better.
=> [DataGrid] Fix server-side filter demo not working

docs/data/date-pickers/custom-field/custom-field.md
---
In v7, the `UseDateFieldProps` and `BaseSingleInputFieldProps` require an additional `TEnableAccessibleFieldDOMStructure extends boolean` type argument.
https://github.com/mui/mui-x/blob/ef40e06213d4721c51d498328f4fadf8e545b3e7/packages/x-date-pickers/src/DateField/DateField.types.ts#L24-L27
https://github.com/mui/mui-x/blob/ef40e06213d4721c51d498328f4fadf8e545b3e7/packages/x-date-pickers/src/models/fields.ts#L168-L174
The latest ["Custom field" documentation page](https://mui.com/x/react-date-pickers/custom-field/#how-to-build-a-custom-field) is still using the old v6 version.  TypeScript reports the following errors:
```
TS2314: Generic type 'UseDateFieldProps<TDate, TEnableAccessibleFieldDOMStructure>' requires 2 type argument(s).
TS2314: Generic type BaseSingleInputFieldProps …
```
=> [docs] Fix type arguments in Custom Field page

docs/data/data-grid/aggregation/AggregationValueFormatter.js, docs/data/data-grid/aggregation/AggregationValueFormatter.tsx, docs/pages/x/api/data-grid/grid-aggregation-function.json, packages/x-data-grid-premium/src/hooks/features/aggregation/gridAggregationFunctions.ts, packages/x-data-grid-premium/src/hooks/features/aggregation/gridAggregationInterfaces.ts, packages/x-data-grid-premium/src/hooks/features/aggregation/wrapColumnWithAggregation.tsx, packages/x-data-grid-premium/src/tests/aggregation.DataGridPremium.test.tsx, packages/x-data-grid/src/models/params/gridCellParams.ts, scripts/x-data-grid-premium.exports.json, scripts/x-data-grid-pro.exports.json, scripts/x-data-grid.exports.json
Closes #12658 
We didn't complete this breaking change. This is now a bug at runtime for users, so we need to remove it even if we didn't do it at v7 release.
=> [DataGrid] Remove GridFormatterParams completely

docs/data/charts/axis/MarginAndLabelPosition.js, docs/data/charts/axis/MarginAndLabelPosition.tsx, docs/data/charts/axis/axis.md, docs/data/charts/getting-started/getting-started.md
=> [docs] Make the Charts `margin` usage more visible

packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx, scripts/x-charts.exports.json
The cause for this is that `@mui/base/Popper` doesn't seen to have the sx property.
I've re-exported a `PopperProps` property with the added `sx` prop. I decided on having the property be exported from the lib in order for users to be able to use it somewhere else.
=> [charts] Fix typescript error when using `sx` property on ChartsTooltip

docs/translations/api-docs/charts/charts-voronoi-handler/charts-voronoi-handler.json, packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx
Issue was due to `Object.keys()` returning an array of strings even if the keys are numbers.
This fix stores the `seriesId` as a property inside the series object to avoid the issue mentioned above.
Fixes #12603
=> [charts] Fix Scatter series highlight when id is a `number`

docs/data/charts/composition/LimitOverflow.js, docs/data/charts/composition/LimitOverflow.tsx, docs/data/charts/composition/composition.md
=> [docs] Explain how to clip plots with composition

docs/data/charts/tooltip/AxisFormatter.js, docs/data/charts/tooltip/AxisFormatter.tsx, docs/data/charts/tooltip/AxisFormatter.tsx.preview, docs/data/charts/tooltip/tooltip.md
- Added example on how to format `xAxis` on tick vs tooltip.
closes #12442
=> [docs] Add AxisFormatter documentation for customizing tick/tooltip value formatting

packages/x-charts/src/BarChart/extremums.test.ts, packages/x-charts/src/BarChart/extremums.ts
We just use optional chain and nullchecks as fallbacks.
@alexfauquette Should we add tests for these functions?
Fixes #12462
=> [charts] Fix Barchart with empty dataset throwing an error

docs/data/data-grid/localization/data.json, docs/data/date-pickers/localization/data.json, packages/x-data-grid/src/locales/svSE.ts, packages/x-date-pickers/src/locales/svSE.ts
This PR adds the missing translation for the Swedish (sv-SE) locale - https://github.com/mui/mui-x/issues/3211.
=> [l10n] Improve Swedish (sv-SE) locale

packages/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts, packages/x-data-grid-premium/src/tests/clipboard.DataGridPremium.test.tsx, packages/x-data-grid-pro/src/tests/clipboard.DataGridPro.test.tsx, packages/x-data-grid/src/hooks/features/export/serializers/csvSerializer.ts
Fixes https://github.com/mui/mui-x/issues/12456
[Escaping double quotes is specific to CSV format](https://techterms.com/definition/csv) and shouldn't be done when copying to clipboard.
=> [DataGrid] Do not escape double quotes when copying to clipboard

scripts/releaseChangelog.mjs
This is a follow-up on https://github.com/mui/mui-x/pull/12639.
Support resolving changelog for `l10n` packages targeting both Pickers and Data Grid packages (i.e. https://github.com/mui/mui-x/pull/12731).
=> [core] Support multiple resolved `l10n` PR packages

docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md, packages/x-data-grid/src/components/containers/GridRootStyles.ts
Closes #12682 
Fix overflow behavior with dynamic row height. I'm not sure why the `overflow: initial` was added (probably by me) but I think this would be the correct behavior.
Before: https://codesandbox.io/p/sandbox/aged-field-hjnfyv
After: https://codesandbox.io/p/sandbox/upbeat-liskov-c2j655
=> [DataGrid] Fix overflow with dynamic row height

packages/x-date-pickers-pro/src/internals/hooks/useEnrichedRangePickerFieldProps.ts, packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts, packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.types.ts, test/e2e/fixtures/DatePicker/BasicClearableDesktopDatePicker.tsx, test/e2e/index.test.ts
Fixes #12652.
Clicking the open button causes the following event to be triggered and if default is not prevented, it executes the input DOM selection logic.
https://github.com/mui/mui-x/blob/f617d7032d26305445b83307f46df777979f82bf/packages/x-date-pickers/src/internals/hooks/useField/useFieldV6TextField.ts#L248-L257
Changed the `onOpen` and `onClose` actions to call `event.preventDefault()` to avoid such problems.
=> [fields] Fix field editing after closing the picker

packages/x-charts/src/ChartsXAxis/ChartsXAxis.tsx, packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx, packages/x-charts/src/hooks/useTicks.ts
- Start using `tickLabelInterval` to determine which labels should be skipped
- Fix small typos
You can test it here: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-lhvxqm?file=%2Fsrc%2Fdemo.tsx%3A161%2C1
fixes #12725
=> [charts] Fix `tickLabelInterval` not working on YAxis

docs/data/charts/axis/AxisCustomizationNoSnap.js, docs/data/charts/axis/ModifyAxisPosition.js, docs/data/charts/axis/ModifyAxisPosition.tsx, docs/data/charts/axis/ModifyAxisPosition.tsx.preview, docs/data/charts/axis/axis.md, docs/data/charts/styling/MarginNoSnap.js, docs/translations/api-docs/charts/bar-chart/bar-chart.json, docs/translations/api-docs/charts/chart-container/chart-container.json, docs/translations/api-docs/charts/line-chart/line-chart.json, docs/translations/api-docs/charts/pie-chart/pie-chart.json, docs/translations/api-docs/charts/responsive-chart-container/responsive-chart-container.json, docs/translations/api-docs/charts/scatter-chart/scatter-chart.json, packages/x-charts/src/BarChart/BarChart.tsx, packages/x-charts/src/ChartContainer/ChartContainer.tsx, packages/x-charts/src/ChartsAxis/ChartsAxis.tsx, packages/x-charts/src/LineChart/LineChart.tsx, packages/x-charts/src/PieChart/PieChart.tsx, packages/x-charts/src/ResponsiveChartContainer/ResponsiveChartContainer.tsx, packages/x-charts/src/ScatterChart/ScatterChart.tsx, packages/x-charts/src/context/CartesianContextProvider.tsx
Fix #12531
The root cause of the issue was that:
- if `yAxis` is not defined, we internally create a default axis configuration with id `DEFAULT_Y_AXIS_KEY`.
- if `yAxis` is defined without an id, the auto-generated ids are `deaultized-y-axis-0`, `deaultized-y-axis-1`, `deaultized-y-axis-2`, ... 
To fix this, I propose to allow providing props such as `rightAxis` with empty config which will render the first axis. Which match how series work:
https://github.com/mui/mui-x/blob/8efee23e8ba67ea1e3c31ab54ac71561b3cd9223/packages/x-charts/src/BarChart/BarPlot.tsx#L89-L100
This allow me to remove all references to `DEFAULT_X_AXIS_KEY` and `DEFAULT_Y_AXIS_KEY` in the docs
=> [charts] Do not document the usage of `DEFAULT_X_AXIS_KEY` and `DEFAULT_Y_AXIS_KEY`

docs/data/charts/areas-demo/AreaChartFillByValue.js, docs/data/charts/areas-demo/AreaChartFillByValue.tsx, docs/data/charts/areas-demo/SimpleAreaChart.js, docs/data/charts/areas-demo/SimpleAreaChart.tsx, docs/data/charts/areas-demo/SimpleAreaChart.tsx.preview, docs/data/charts/areas-demo/StackedAreaChart.js, docs/data/charts/areas-demo/StackedAreaChart.tsx, docs/data/charts/line-demo/DashedLineChart.js, docs/data/charts/line-demo/DashedLineChart.tsx, docs/data/charts/line-demo/TinyLineChart.js, docs/data/charts/line-demo/TinyLineChart.tsx, docs/data/charts/lines/CSSCustomization.js, docs/data/charts/lines/CSSCustomization.tsx
Some docs example was using string to target some of our classes. The PR replaces them with classes objects.
The only limitation is the classes including some ids which are not supported yet.
=> [docs] Use charts classes objects

docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md
Follow-up of https://github.com/mui/mui-x/pull/12683#discussion_r1560772877
=> [docs] Add grid cell display example to the migration guide

packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx
Closes #12585
Fix column resize when around the end of the row by updating the `rowWidth` CSS variable while resizing.
=> [DataGrid] Fix column resize

packages/x-data-grid/src/components/panel/GridPanel.tsx
Closes https://github.com/mui/mui-x/issues/5183
| ------ | ------ |
| <img width="284" src="https://github.com/mui/mui-x/assets/13808724/ddfe2072-4e41-4e81-89d0-55b1b1f61660"> | <img width="283" src="https://github.com/mui/mui-x/assets/13808724/c7cf67b0-5316-4d90-900a-275f0c1521bb"> |
=> [DataGrid] Limit panel width to not exceed screen width

docs/pages/x/api/data-grid/data-grid-premium.json, docs/pages/x/api/data-grid/data-grid-pro.json, docs/pages/x/api/data-grid/data-grid.json, docs/translations/api-docs/data-grid/data-grid-premium/data-grid-premium.json, docs/translations/api-docs/data-grid/data-grid-pro/data-grid-pro.json, docs/translations/api-docs/data-grid/data-grid/data-grid.json, packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx, packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderSeparator.tsx, packages/x-data-grid/src/components/containers/GridRootStyles.ts, packages/x-data-grid/src/constants/gridClasses.ts, packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx
Closes #12788
Closes #12783 
Fix column separators, make the separators from their full width. The last column is `overflow: hidden` because otherwise the flex layout is messed up due to the separator sticking out of the row width.
Preview: https://deploy-preview-12808--material-ui-x.netlify.app/x/react-data-grid/column-dimensions/
=> [DataGrid] Fix column separators

test/utils/pickers/describeValue/testPickerOpenCloseLifeCycle.tsx
This test sometimes fails locally with a `1s` timeout.
Given how much CI VMs are slower, it could simply be an actual flaky timeout. 🙈 
Increase timeout of the test that occasionally fails on CI with `DesktopDateTimeRangePicker` or `MobileDateTimeRangePicker`.
- https://app.circleci.com/pipelines/github/mui/mui-x/56644/workflows/3fad6689-5a66-4c52-b9ad-129f0aa7c708/jobs/324060
- https://app.circleci.com/pipelines/github/mui/mui-x/55241/workflows/48a5768d-15c0-44fc-affb-0ffebdbe3a71/jobs/315947
- https://app.circleci.com/pipelines/github/mui/mui-x/56639/workflows/8293160a-8444-48a3-b61e-053e5a040908/jobs/324035
- https://app.circleci.com/pipelines/github/mui/mui-x/55868/workflows/d44dc6ca-55af-404b-a73d-4d364dfe9582/jobs/320203
=> [test] Increase timeout for test that sometimes fail on DateTimeRangePicker

docs/scripts/api/buildApi.ts, docs/scripts/api/buildGridEventsDocumentation.ts, docs/scripts/api/buildInterfacesDocumentation.ts, docs/scripts/api/utils.ts, docs/scripts/createXTypeScriptProjects.ts
1.Isolate the interfaces docs pages from the API JSON generation
2. Allow to get interfaces from some specific packages
3. Remove most of the hard coded values specific to the data grid 
This PR is used to add interfaces for x-charts in https://github.com/mui/mui-x/pull/12656
Could be used the same way to add interfaces pages for tree view
=> [docs-infra] Prepare infra to document charts interfaces

packages/x-data-grid-premium/src/hooks/features/aggregation/gridAggregationInterfaces.ts, scripts/x-data-grid-premium.exports.json
Closes #12805 
This is simply exporting a type to make creating custom aggregators easier from a typing perspective.
=> export GridAggregationParams for use with custom aggregators

packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
Closes #12006
Don't know what the root cause is but the devtools point at that function for the leak, applied a transformation similar to what is already in v7 where the leak doesn't exist. Not reproducible in a codesandbox, see the issue above for reproduction case.
=> [DataGrid] Fix virtualization memory leak

packages/x-tree-view/src/internals/plugins/useTreeViewFocus/useTreeViewFocus.ts, packages/x-tree-view/src/internals/plugins/useTreeViewJSXItems/useTreeViewJSXItems.tsx, packages/x-tree-view/src/useTreeItem2/useTreeItem2.ts
This is clearly a nitpick but let's be consistent :ok_hand: 
Unless I'm missing some prop, we now support `defaultMuiPrevented` on all the props of the Tree View components and `TreeItem2` (not the legacy `TreeItem`).
=> [TreeView] Support `defaultMuiPrevented` on the `onFocus` prop of the root slot

docs/data/charts/bars/ColorScaleNoSnap.js, docs/data/charts/bars/ColorScaleNoSnap.tsx, docs/data/charts/lines/ColorScaleNoSnap.js, docs/data/charts/lines/ColorScaleNoSnap.tsx, docs/data/charts/scatter/ColorScaleNoSnap.js, docs/data/charts/scatter/ColorScaleNoSnap.tsx, docs/data/charts/scatter/scatter.md, docs/pages/x/api/charts/scatter-chart.json, docs/translations/api-docs/charts/scatter-chart/scatter-chart.json, packages/x-charts/src/ChartsTooltip/ChartsAxisTooltipContent.tsx, packages/x-charts/src/ChartsTooltip/ChartsItemTooltipContent.tsx, packages/x-charts/src/ScatterChart/ScatterChart.tsx, packages/x-charts/src/ScatterChart/ScatterPlot.tsx, packages/x-charts/src/ScatterChart/getColor.ts, packages/x-charts/src/context/ZAxisContextProvider.tsx, packages/x-charts/src/context/index.ts, packages/x-charts/src/internals/colorGetter.ts, packages/x-charts/src/models/colorMapping.ts, packages/x-charts/src/models/seriesType/scatter.ts, packages/x-charts/src/models/z-axis.ts, scripts/x-charts.exports.json
A followup of #12490
TODO:
- The current state make sens for me. It's a mix between having a `z` value the same way `x` and `y` are currently handled by the scatter series. And a `zAxis.data` that will simplify the work with other charts such as the bar chart
I'm not a big fan of exporting the `ZAxisProvider` but it's the only way I see to le it available for composition
- 🎁 Scatter Charts get a z-axis to allow coloring data points independently from their coordinate.
=> [charts] Add z-axis to colorize scatter charts

docs/pages/_app.js
Use v6 versions of MUI X packages in Codesandbox and Stackblitz demos opened from https://v6.mui.com/x/react-data-grid.
=> [docs] Use MUI X v6 in Codesandbox and Stackblitz demos

.github/workflows/discord-release-announcement.yaml, scripts/README.md, scripts/releaseChangelog.mjs
---
cherry picking the release announcement workflow since the original PR was targeted at next 🤦🏼
=> [support-infra] Add release announcement to GitHub workflows (#11867)

packages/x-data-grid/src/colDef/gridDateOperators.ts, packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputDate.tsx
Fixes https://github.com/mui/mui-x/issues/12785
Preview: https://deploy-preview-12836--material-ui-x.netlify.app/x/react-data-grid/column-definition/#column-types
=> [DataGrid] Fix date filtering for negative timezone offsets

packages/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts, packages/x-data-grid/src/hooks/features/columns/useGridColumns.tsx
Closes https://github.com/mui/mui-x/issues/12584
Make flex column width work again.
Before: https://codesandbox.io/p/sandbox/mui-x-datagrid-issue-12459-forked-cksdhh
After: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-99ccdf
=> [DataGrid] Fix flex column width when used with pinned columns

packages/x-data-grid/src/components/GridHeaders.tsx
Fixes https://github.com/mui/mui-x/issues/12749
=> [DataGrid] Pass slot props to `columnHeaders` slot

docs/data/date-pickers/localization/data.json, packages/x-date-pickers/src/locales/caES.ts
In response to issue https://github.com/mui/mui-x/issues/3211, this PR add (or fix) the missing translation for Catalan.
=> [l10n] Improve Catalan (ca-ES) locale

CHANGELOG.md, docs/data/data-grid/pagination/pagination.md, scripts/README.md
Illustrate why we need Vale in the CI
=> [docs] Fix Vale regression

docs/data/data-grid/getting-started/getting-started.md
It seems that we forgot to update this availability matrix that shows which features are available in which tear after we made the Column resizing and autosizing features available in the community plan
=> [docs] Update Column features availability

docs/data/migration/migration-charts-v6/migration-charts-v6.md, docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md, docs/data/migration/migration-pickers-v6/migration-pickers-v6.md, docs/data/migration/migration-tree-view-v6/migration-tree-view-v6.md
Closes https://github.com/mui/mui-x/issues/12612
Preview: https://deploy-preview-12710--material-ui-x.netlify.app/x/migration/migration-data-grid-v6/#drop-webpack-4-support
=> [docs] Cover webpack 4 support in migration guide

packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts
Fixes #12826 
Not sure if this is a bug fix or just a behavior change.
The current type-ahead was alphabetical, if you have the items `["A3", "A2", "A1"]`, you focus `"A3"` and press `"a"`, the focus goes to `"A1"` because it's the 1st matching item alphabetically. 
This PR switches for a search based on the displayed order (you focus `"A2"` because it is the 1st matching item below the currently focused one.
IMHO this is a lot more consistent, it's the approach taken by [this TreeView](https://clarity.design/documentation/tree-view) for instance.
Nice side-effect, we no longer generate the list of the 1st letter of **every item** on each keystroke 
Now that `getNextNavigableItem` is cheap it's a lot more efficient that way
Add test in #12811
=> [TreeView] Use the order in which the items are displayed for type-ahead

docs/data/migration/migration-tree-view-v6/migration-tree-view-v6.md, packages/x-tree-view/src/TreeItem/TreeItem.test.tsx, packages/x-tree-view/src/internals/plugins/useTreeViewFocus/useTreeViewFocus.ts, packages/x-tree-view/src/internals/useTreeView/useTreeView.types.ts
Closes #12494
Unless we consider this to be a BC @LukasTy? :thinking:
=> [TreeView] Remove un-needed `aria-activedescendant` attribute

packages/x-charts/src/ChartsTooltip/ChartsTooltipTable.ts, packages/x-charts/src/ChartsTooltip/DefaultChartsAxisTooltipContent.tsx, packages/x-charts/src/ChartsTooltip/DefaultChartsItemTooltipContent.tsx
A few opportunities I saw looking randomly at the code.
=> [charts] Improve default tooltip content 

packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx, packages/x-data-grid/src/utils/domUtils.ts, test/e2e/fixtures/DataGrid/ResizeWithFlex.tsx, test/e2e/index.test.ts
Fix #12290 
Recalculate group header widths after column widths were adjusted based on the flex values
Before: https://stackblitz.com/edit/react-cecf1r-nfqkhk
After: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-td62tk
=> [DataGrid] Fix group header resize

docs/data/charts/bars/BorderRadius.js, docs/data/charts/bars/BorderRadius.tsx, docs/data/charts/bars/BorderRadius.tsx.preview, docs/data/charts/bars/bars.md
As @alexfauquette suggested on the [previous PR](https://github.com/mui/mui-x/pull/12834) in order to provide a quick alternative to borderRadius on bar charts, we can simply use css' `clipPath` property, which should be enough for most regular cases. 
@alexfauquette not sure this "resolves" the issue at #12220, what do you think? 
https://deploy-preview-12859--material-ui-x.netlify.app/x/react-charts/bars/#border-radius
=> [charts] Add documentation on border radius alternative for `BarCharts`

docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md
https://mui-org.slack.com/archives/C04U3R2V9UK/p1713726371441179
=> [docs] Improve Data Grid migration guide

.github/workflows/l10n.yml
Fix workflow broken after switching to `pnpm`: https://github.com/mui/mui-x/actions/runs/8818836993/job/24208602684.
=> [core] Fix `l10n` GH workflow

package.json, packages/x-charts/package.json, packages/x-data-grid-generator/package.json, packages/x-data-grid-premium/package.json, packages/x-data-grid-pro/package.json, packages/x-data-grid/package.json, packages/x-date-pickers-pro/package.json, packages/x-date-pickers/package.json, packages/x-license/package.json, packages/x-tree-view-pro/package.json, packages/x-tree-view/package.json
I noticed it while working on the `pnpm` migration.
These files do not seem to exist anymore and the config is located in respective test framework setup files.
=> [core] Remove redundant `setupFiles` entries in `package.json`

packages/x-charts/src/BarChart/BarElement.tsx, packages/x-charts/src/BarChart/BarPlot.tsx
Seems that rounding the px coordinate of the stack bars is better to avoid weird overlapping
=> [charts] Round y values for bar chart

docs/data/date-pickers/localization/data.json, packages/x-date-pickers/src/locales/heIL.ts
Added missing translations, now missing only meridiem.
=> [l10n] Improve Hebrew (he-IL) locale

packages/x-date-pickers/src/PickersDay/PickersDay.tsx
=> [pickers] Improve TypeScript performance in `PickersDay`

docs/data/date-pickers/localization/data.json, packages/x-date-pickers/src/locales/huHU.ts
Add missing translations for date-pickers.
=> [l10n] Improve Hungarian (hu-HU) locale

packages/x-charts/src/PieChart/PieChart.tsx
Fixes #12926 
[working example](https://codesandbox.io/p/sandbox/heuristic-hawking-w98gzj?file=%2Fsrc%2FDemo.tsx%3A9%2C12)
=> [charts][PieChart] Fix `prop.slots` and `prop.slotProps` not passed to `<ChartsTooltip />`

.circleci/config.yml
Bumping to use latest LTS (v18.x) version to benefit from updates and security fixes.
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md
=> [code-infra] Bump node image used by CI in docker

packages/x-data-grid/src/hooks/features/rows/useGridRows.ts
Fixes #12769
- Before: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-dt6nxy
- After: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-v4x3jd
Also tested in this repo: https://github.com/MBilalShafi/test-mui-x-12833
Seems to work as expected.
=> [DataGrid] Fix rows not being recomputed on `props.rowCount` change

scripts/README.md, scripts/releaseTag.mjs
=> [core] Improve release process docs

.github/workflows/add-release-reviewers.yml
---
adds an action to automatically request reviews from the x maintainers on a release PR
cc @JCQuintas :P
=> [infra] Automation: Add release PR reviewers
