packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
packages/grid/x-data-grid-premium/src/DataGridPremium/useDataGridPremiumProps.ts
packages/grid/x-data-grid-premium/src/models/dataGridPremiumProps.ts
packages/grid/x-data-grid-premium/src/tests/clipboard.DataGridPremium.test.tsx

Fixes https://github.com/mui/mui-x/issues/9103

[DataGridPremium] Remove last line break on clipboard paste

---

packages/grid/x-data-grid-premium/src/themeAugmentation/overrides.ts
packages/grid/x-data-grid-pro/src/themeAugmentation/overrides.ts
packages/grid/x-data-grid/src/themeAugmentation/overrides.ts

Fixes https://github.com/mui/mui-x/issues/9234

[DataGrid] Fix module augmentation error when using ﻿`@mui/lab`

---

docs/data/data-grid/localization/data.json
packages/grid/x-data-grid/src/locales/elGR.ts

Add translation for missing X-Data-Grid locale strings.

[l10n] Improve Greek (el-GR) locale for data grid

---

docs/data/date-pickers/localization/data.json
packages/x-date-pickers/src/locales/elGR.ts
packages/x-date-pickers/src/locales/index.ts
scripts/x-date-pickers-pro.exports.json
scripts/x-date-pickers.exports.json

Add translation for date pickers locale strings.

[l10n] Add Greek (el-GR) locale

---

docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md

https://mui-org.slack.com/archives/C04U3R2V9UK/p1686353219568269

[docs] Link pagination documentation to the migration guide

---

packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx

[pickers] Fix disabling for digital clock

---

packages/grid/x-data-grid/src/hooks/features/editing/useGridCellEditing.ts
packages/grid/x-data-grid/src/models/params/gridEditCellParams.ts

Fix #9281
Context: https://github.com/mui/mui-x/issues/9281#issuecomment-1584309343
Before: https://codesandbox.io/s/currying-night-xpfv64?file=/demo.tsx
After: https://codesandbox.io/s/youthful-resonance-n2ypdt?file=/demo.tsx

[DataGrid] Correct the type for single digit edited number value

---

docs/data/data-grid/demo/PopularFeaturesDemo.js
docs/data/data-grid/demo/PopularFeaturesDemo.tsx

https://deploy-preview-9069--material-ui-x.netlify.app/x/react-data-grid/demo/

[docs] Add header filters to the popular features demo

---

docs/data/charts/overview/overview.md

Minor changes I thought could make things clearer

[docs] Improve Chart overview

---

packages/grid/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts

[DataGrid] Correct the type for single digit edited number for row edit

---

CHANGELOG.md
docs/data/introduction/overview/overview.md
docs/data/migration/migration-pickers-v5/migration-pickers-v5.md

These are outdated references.

[docs] Fix Base UI references

---

docs/data/data-grid/editing/FullFeaturedCrudGrid.js
docs/data/data-grid/editing/FullFeaturedCrudGrid.tsx

Fixes https://github.com/mui/mui-x/pull/8431/files#r1171841451
Reported in https://github.com/mui/mui-x/pull/9287#issuecomment-1594971193

[docs] Fix random screenshot generation

---

packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx
packages/x-date-pickers/src/internals/hooks/useField/useField.ts

[pickers] Reset fields internal state when pasting value

---

docs/data/date-pickers/date-time-picker/DateTimePickerViewRenderers.js
docs/data/date-pickers/date-time-picker/DateTimePickerViewRenderers.tsx
docs/data/date-pickers/date-time-picker/DateTimePickerViewRenderers.tsx.preview
docs/data/date-pickers/date-time-picker/date-time-picker.md
docs/data/date-pickers/time-picker/TimePickerViewRenderers.js
docs/data/date-pickers/time-picker/TimePickerViewRenderers.tsx
docs/data/date-pickers/time-picker/TimePickerViewRenderers.tsx.preview
docs/data/date-pickers/time-picker/time-picker.md

[docs] Add examples of using different time view renderers

---

packages/grid/x-data-grid/src/components/GridRow.tsx
packages/grid/x-data-grid/src/components/cell/GridCell.tsx
packages/grid/x-data-grid/src/components/cell/GridEditInputCell.tsx

Fix https://app.circleci.com/pipelines/github/mui/mui-x/40434/workflows/971a77cb-641d-45c8-9932-44390cf8e7d0/jobs/232010

[core] Fix proptypes

---

docs/data/pages.ts
packages/x-charts/package.json
scripts/releaseChangelog.mjs

Make scripts ready for the release of alpha 0
- Add a changelog text (I was not super inspired might redo it)
- make package public
- update changelog generator script
- make the docs visible
We release a new package `@mui/x-charts`.
This package aims at simplifying the integration of charts into your dashboards. 📊
It already contains [lines](https://mui.com/x/react-charts/lines/), [bars](https://mui.com/x/react-charts/bars/), and [scatter](https://mui.com/x/react-charts/scatter/) charts with basic customization features.
Please, visit the new [documentation](https://mui.com/x/react-charts/) to know what it does, and open issues to get the feature you need to be implemented 🚀

[charts] Prepare the charts release

---

docs/data/charts/overview/overview.md

Fix spelling error in package name.

[docs] Update charts overview.md

---

README.md
packages/x-charts/README.md
packages/x-charts/package.json
yarn.lock

- Update the readme
- Remove the `d3-array` package

[charts] Update README.md

---

docs/next.config.js
scripts/l10n.ts
yarn.lock

Modification from https://github.com/mui/material-ui/pull/37695

Bumb update monorepo

---

.github/workflows/priority-support-validation-prompt.yml

[core] Update `uses` for priority support action

---

.github/workflows/priority-support-validation-prompt.yml

[core] Add `edit-mode` to priority support action

---

CHANGELOG.md
packages/grid/x-data-grid-premium/src/hooks/features/export/serializer/excelSerializer.ts

A polish on #9422, these media look very strange on my screen, enough for me to want to fix it 😁
Before: https://github.com/LukasTy/mui-x/blob/25c67a67f2b30fb6a79324eb0d3be30cf3a21563/CHANGELOG.md#690
After: https://github.com/mui/mui-x/blob/21493776c80dc8ebd87ca6756d6ab4105d665217/CHANGELOG.md#690
(I can't figure out how to remove the bottom border line)
It's more or less the same fix as in https://github.com/mui/mui-x/pull/9225

[CHANGELOG] Fix media quality

---

packages/x-charts/package.json
packages/x-charts/src/ChartsTooltip/ChartsTooltipTable.tsx
packages/x-charts/src/ResponsiveChartContainer/index.tsx
yarn.lock

[charts] Take responsive container from data grid

---

yarn.lock

Closes https://github.com/mui/mui-x/issues/9194
Preview: https://deploy-preview-9490--material-ui-x.netlify.app/x/react-data-grid/row-updates/

[docs] Display plan icon in ToC

---

docs/data/date-pickers/localization/data.json
packages/x-date-pickers/src/locales/nbNO.ts

[I10n] Improve Norwegian (nb-NO) locale

---

docs/data/data-grid/localization/data.json
packages/grid/x-data-grid/src/locales/plPL.ts

[l10n][data grid] Improve Polish (pl-PL) locale

---

.github/ISSUE_TEMPLATE/5.priority-support.yml
.github/workflows/priority-support-validation-prompt.yml

Based on https://github.com/mui/material-ui/issues/37810#issuecomment-1620592599

[core] Update priority support issue template and prompt

---

docs/data/date-pickers/custom-components/custom-components.md

Add a callout clarifying correct slot components usage.
This is in an effort to hopefully alleviate some of the duplicate issues (#8850) avalanche regarding the same problem. 🙈

[docs] Add slot components usage alert

---

packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts
packages/grid/x-data-grid/src/tests/columns.DataGrid.test.tsx

Before: https://codesandbox.io/s/wizardly-jennings-zt5dz5?file=/demo.tsx
After: https://codesandbox.io/s/kind-mccarthy-n44p45?file=/demo.tsx
Fixes https://github.com/mui/mui-x/issues/5970

[DataGrid] Fix column type change not working correctly

---

docs/src/modules/components/LocalizationTable.js

A take on this, first time experiencing the badges.
Preview: https://deploy-preview-9672--material-ui-x.netlify.app/x/react-data-grid/localization/
Before
After
Before
After

[docs] Localization progress, polish

---

docs/data/data-grid/components/CustomSortIcons.js
docs/data/data-grid/components/CustomSortIcons.tsx
docs/data/data-grid/components/CustomSortIcons.tsx.preview

https://mui-org.slack.com/archives/C04U3R2V9UK/p1689180204329509

[DataGrid] Fix sorting in `CustomSortIcons` demo

---

packages/grid/x-data-grid/src/hooks/features/filter/useGridFilter.tsx
packages/grid/x-data-grid/src/tests/quickFiltering.DataGrid.test.tsx

Closes #9666 
Before (9666): https://codesandbox.io/s/fervent-rain-whg9tt
After: https://codesandbox.io/s/silly-christian-47jv5r

[DataGrid] Fix quickfilter undefined row error

---

packages/x-charts/src/LineChart/extremums.ts
packages/x-charts/src/ResponsiveChartContainer/index.tsx

[charts] Fix blinking in responsive charts and extremums computation for line charts

---

packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx

Fixes https://github.com/mui/mui-x/issues/9398
Before: https://codesandbox.io/s/quizzical-varahamihira-ssjwcd
After: https://codesandbox.io/s/awesome-brook-4nzt9s

[DataGrid] Wait for remote stylesheets to load before print

---

packages/x-charts/src/ScatterChart/Scatter.tsx

I think a first level of optimization would be to limit the amount of looping on the series data.
This array can quickly grow to several hundred / thousand of items.
On `master` we are looping 3 time on the data points (map => filter => map).
This PR combines the first map and filter and add some memoization.
We could map a single time if we generate the React nodes inside the `useMemo`.

[charts] Improve performances of Scatter component

---

docs/data/charts/axis/AxisCustomizationNoSnap.js
docs/data/charts/axis/AxisWithComposition.js
docs/data/charts/axis/AxisWithComposition.tsx
docs/data/charts/axis/MinMaxExample.js
docs/data/charts/axis/MinMaxExample.tsx
docs/data/charts/axis/ModifyAxisPosition.js
docs/data/charts/axis/ModifyAxisPosition.tsx
docs/data/charts/axis/ScaleExample.js
docs/data/charts/axis/ScaleExample.tsx
docs/data/charts/axis/ScaleExample.tsx.preview
docs/src/modules/components/ChartsUsageDemo.js

https://deploy-preview-9801--material-ui-x.netlify.app/x/react-charts/axis/

[docs] Fix charts width in axis pages

---

test/e2e/fixtures/DataGrid/KeyboardNavigationFocus.tsx
test/e2e/index.test.ts

This is a follow-up to https://github.com/mui/mui-x/pull/9747#discussion_r1277175440
Better review with whitespace changes hidden

[test] Data grid e2e tests follow-up

---

docs/pages/x/api/tree-view/tree-item-content.js
docs/pages/x/api/tree-view/tree-item.js
docs/pages/x/api/tree-view/tree-item.json
docs/pages/x/api/tree-view/tree-view.js
docs/pages/x/api/tree-view/tree-view.json
docs/translations/api-docs/tree-view/tree-item.json
docs/translations/api-docs/tree-view/tree-view.json

[core] Update tree data API docs

---

docs/next.config.js
docs/pages/_app.js

Fix https://mui-org.slack.com/archives/C040YT7KB6H/p1690535230799779
There was charts product identifier and version number in the navigation panel.

[docs] Add charts nav item

---

README.md
docs/data/introduction/installation/installation.md
docs/data/introduction/overview/overview.md

- Mention charts on the overview
- Add chart installation instructions
https://deploy-preview-9704--material-ui-x.netlify.app/x/introduction/

[docs] Add charts to MUI X introduction pages

---

packages/x-date-pickers-pro/src/SingleInputDateRangeField/SingleInputDateRangeField.tsx
packages/x-date-pickers-pro/src/SingleInputDateTimeRangeField/SingleInputDateTimeRangeField.tsx
packages/x-date-pickers-pro/src/SingleInputTimeRangeField/SingleInputTimeRangeField.tsx
packages/x-date-pickers/src/DateField/DateField.tsx
packages/x-date-pickers/src/DateTimeField/DateTimeField.tsx
packages/x-date-pickers/src/TimeField/TimeField.tsx

[pickers] Allow to override the `InputProps` of the `TextField` using the `slotProps`

---

packages/x-tree-view/src/TreeView/index.ts
scripts/x-tree-view.exports.json

Makes sure all the exports from the lab are also exported from X

[TreeView] Add missing exported types

---

packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.tsx
packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.tsx
packages/x-date-pickers/src/MobileDatePicker/MobileDatePicker.tsx
packages/x-date-pickers/src/MobileDateTimePicker/MobileDateTimePicker.tsx
packages/x-date-pickers/src/MobileTimePicker/MobileTimePicker.tsx

[pickers] Allow to override the opening aria text using the `localeText` prop on the pickers

---

docs/scripts/utils.ts

Back port https://github.com/mui/material-ui/pull/38276

[core] Fix the link-check script on Windows

---

docs/pages/x/api/date-pickers/date-picker.json
docs/pages/x/api/date-pickers/date-range-picker.json
docs/pages/x/api/date-pickers/date-time-picker.json
docs/pages/x/api/date-pickers/desktop-date-picker.json
docs/pages/x/api/date-pickers/desktop-date-range-picker.json
docs/pages/x/api/date-pickers/desktop-date-time-picker.json
docs/pages/x/api/date-pickers/desktop-time-picker.json
docs/pages/x/api/date-pickers/mobile-date-picker.json
docs/pages/x/api/date-pickers/mobile-date-range-picker.json
docs/pages/x/api/date-pickers/mobile-date-time-picker.json
docs/pages/x/api/date-pickers/mobile-time-picker.json
docs/pages/x/api/date-pickers/time-picker.json
packages/x-date-pickers/src/internals/components/PickersModalDialog.tsx
packages/x-date-pickers/src/internals/components/PickersPopper.tsx

Update slot default description to avoid improper formatting in IDE.

[pickers] Fix default descriptions

---

docs/pages/x/api/charts/spark-line-chart.js
docs/pages/x/api/charts/spark-line-chart.json
docs/translations/api-docs/charts/spark-line-chart.json
packages/x-charts/src/SparkLineChart/SparkLineChart.tsx

[core] Fix pipeline

---

docs/pages/x/api/date-pickers/pickers-calendar-header.json

[core] Regen doc

---

scripts/releaseChangelog.mjs

[TreeView] Add tree view to changelog generator script

---

packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts
packages/x-date-pickers/src/tests/describeValue/describeValue.tsx
packages/x-date-pickers/src/tests/describeValue/testPickerActionBar.tsx
packages/x-date-pickers/src/tests/describeValue/testShortcuts.tsx
test/utils/pickers/assertions.ts

Fixes #9931
It was just a dumb mistake on my side :/

[pickers] Call `onChange` when selecting a picker with `changeImportance="set"`

---

docs/data/date-pickers/localization/data.json
packages/x-date-pickers/src/locales/isIS.ts

[l10n][pickers] Improve Icelandic (is-IS) locale

---

docs/data/tree-view/overview/overview.md
packages/x-tree-view/src/themeAugmentation/components.d.ts
packages/x-tree-view/src/themeAugmentation/index.js
packages/x-tree-view/src/themeAugmentation/index.ts
packages/x-tree-view/src/themeAugmentation/overrides.d.ts
packages/x-tree-view/src/themeAugmentation/props.d.ts
packages/x-tree-view/src/themeAugmentation/themeAugmentation.spec.ts

[TreeView] Add theme augmentation

---

packages/x-charts/src/colorPalettes/colorPalettes.ts

[charts] extend cheerful fiesta palette

---

docs/pages/x/api/charts/charts-axis.json
docs/translations/api-docs/charts/charts-axis.json
yarn.lock

Bump `@mui/monorepo`

---

docs/data/data-grid/column-definition/column-definition.md

Closes #10038
Clarify requirements for each column type.

[DataGrid] Docs: update column types

---

packages/x-charts/src/LineChart/MarkPlot.tsx

[charts] Fix slotProps propagation

---

packages/x-date-pickers/src/internals/components/PickersPopper.tsx

Discovered this issue while working on https://github.com/mui/mui-x/pull/10069
The issue is that currently, we do not expose any `ownerState` to the `desktopPaper` slot even though the typing includes it.
```tsx
slotProps={{
desktopPaper(ownerState) {
// `ownerState` is empty here
console.info(ownerState);
return {};
}
}}
```
https://codesandbox.io/s/rough-sound-ztx5zt?file=/Demo.tsx check console
Extracted `Paper` into a separate component to have access to the `placement` value in the `useSlotProps` hook, which then correctly exposes `ownerState`.
https://codesandbox.io/s/thirsty-maria-4xq53y?file=/Demo.tsx check console

[pickers] Fix `ownerState` on `desktopPaper` slot props

---

packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx

[pickers] Make `openPickerButton` toggle picker

---

packages/x-date-pickers/src/internals/hooks/useValidation.ts

I removed the export as this is never imported internally nor can be imported from the npm package.

[core] Remove oudated link

---

test/e2e/index.test.ts

Try increasing the timeout in CI and do it globally in hopes that it would help avoid the occasional false positives: https://app.circleci.com/pipelines/github/mui/mui-x/43005/workflows/1d6f2ee4-7ac8-4070-b91a-15612bd58e95/jobs/246939

[core] Increase global e2e timeout

---

docs/data/introduction/licensing/licensing.md

It's not super clear if the version means MUI X or the version of the developers's application.
Surfaced in https://mui-org.slack.com/archives/C04U3R2V9UK/p1693216972335579 and #10162.

[docs] Precise Expired license key condition

---

test/e2e/index.test.ts

This test is still occasionally failing on Webkit 🙈 
https://app.circleci.com/pipelines/github/mui/mui-x/43471/workflows/3b1a90df-b2b1-4929-9e68-9201ae46c0b1/jobs/249545

[test] Disable false positive e2e test on webkit

---

packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts

[DataGrid] Fix an error when hovering on a row, the background changed to white

---

docs/data/charts/pie-demo/PieChartWithCenterLabel.js
docs/data/charts/pie-demo/PieChartWithCenterLabel.tsx
docs/data/charts/pie-demo/PieChartWithCenterLabel.tsx.preview
docs/data/charts/pie-demo/pie-demo.md

- [ ✅ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
Added a pieCenter slot and docs to show how to use it

[docs] Add pie chart demo with a center label

---

packages/grid/x-data-grid-generator/src/services/tree-data-generator.ts

See https://github.com/mui/mui-x/issues/8624#issuecomment-1685419336

[docs] Enable `ariaV7` flag for demos using `useDemoData` hook

---

packages/grid/x-data-grid-premium/README.md
packages/grid/x-data-grid-pro/README.md
packages/grid/x-data-grid/README.md

The narrative in https://www.npmjs.com/package/@mui/x-charts feels backward.

[docs] Improve npm package README

---

packages/x-tree-view/src/TreeItem/TreeItem.tsx
packages/x-tree-view/src/TreeView/TreeView.tsx

See https://github.com/mui/mui-x/issues/9226 for the root issue

[docs] Fix Tree View link to API references

---

packages/x-date-pickers/src/TimeClock/Clock.tsx
packages/x-date-pickers/src/TimeClock/clockClasses.ts

Resolves issue noticed in https://github.com/mui/mui-x/issues/10302#issuecomment-1716439968
Before: https://codesandbox.io/s/sleepy-shtern-ljwzmh?file=/Demo.tsx
After: https://codesandbox.io/s/competent-leftpad-gvphzn?file=/Demo.tsx

[pickers] Localize `TimeClock` meridiem text

---

docs/data/data-grid/column-visibility/column-visibility.md

https://mui-org.slack.com/archives/C04U3R2V9UK/p1688641274584799

[docs] Improve the column visibility section

---

packages/grid/x-data-grid/src/components/cell/GridCell.tsx

Fixes #10278
Before: https://codesandbox.io/s/distracted-cartwright-7dxf55?file=/demo.tsx
After: https://codesandbox.io/s/shy-water-p8qff4?file=/demo.tsx

[Datagrid] add border:0 to unmounted focused cell to avoid layout shifts in that row

---

docs/data/data-grid/column-definition/RenderCellGrid.js
docs/data/data-grid/column-definition/RenderCellGrid.tsx

Preview: https://deploy-preview-10359--material-ui-x.netlify.app/x/react-data-grid/column-definition/#rendering-cells

[docs] Polish typescript ref use

---

docs/data/date-pickers/localization/data.json
packages/x-date-pickers/src/locales/fiFI.ts

[l10n] Improve Finnish (fi-FI) locale

---

packages/grid/x-data-grid-pro/src/components/headerFiltering/GridHeaderFilterCell.tsx
packages/grid/x-data-grid-pro/src/tests/filtering.DataGridPro.test.tsx
packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts

Fixes #10357
- Before: https://codesandbox.io/s/2szq7t?file=/Demo.tsx
- After: https://deploy-preview-10358--material-ui-x.netlify.app/x/react-data-grid/filtering/header-filters/

[DataGridPro] Fix keyboard navigation issue in header filters

---

.circleci/config.yml
package.json

Fix OOM by allowing a bigger nodejs heap.

[core] Fix Circle CI OOM

---

docs/data/data-grid/row-definition/row-definition.md

https://mui-org.slack.com/archives/C04U3R2V9UK/p1693581767504329

[docs] Improve the documentation section `rowIdentifier`

---

packages/x-charts/src/SparkLineChart/SparkLineChart.tsx

Fix #10349 and fix the https://github.com/mui/mui-x/pull/9228#issuecomment-1724994536
[before](https://codesandbox.io/s/cranky-grass-h3w4hp?file=/Demo.tsx)
[after](https://codesandbox.io/s/admiring-bogdan-vh66m2?file=/package.json)

[charts] Fix sparkline scale and rendering

---

packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputBoolean.tsx
packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputSingleSelect.tsx

[DataGrid] Fix dev warning about `InputLabelProps`

---

docs/data/data-grid/column-definition/column-definition.md

Closes https://github.com/mui/mui-x/issues/10431

[docs] Fix usage of `GridRenderCellParams` interface

---

docs/data/data-grid/row-updates/UpdateRowsProp.js
docs/data/data-grid/row-updates/UpdateRowsProp.tsx

Fixes https://github.com/mui/mui-x/issues/10434

[docs] Fix demo crashing when all rows are deleted

---

docs/data/tree-view/overview/overview.md

https://mui.com/x/react-tree-view/#api

[docs] Fix Tree View product ID

---

packages/grid/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx

Fixes https://github.com/mui/mui-x/issues/10430

[DataGrid] Fix column headers scroll when theme scoping is used

---

packages/x-tree-view/src/TreeView/TreeView.test.tsx
packages/x-tree-view/src/internals/plugins/useTreeViewFocus/useTreeViewFocus.ts
packages/x-tree-view/src/internals/plugins/useTreeViewFocus/useTreeViewFocus.types.ts

[TreeView] Do not try to focus a collapsed node when re-focusing the TreeView

---

docs/pages/x/api/data-grid/index.md

https://mui-org.slack.com/archives/C04U3R2V9UK/p1695673736579859

[docs] Correct the typo in data grid api docs

---

packages/x-tree-view/src/TreeView/TreeView.test.tsx
packages/x-tree-view/src/TreeView/TreeView.tsx

Fixes https://github.com/mui/mui-toolpad/pull/2716#discussion_r1335215258
Fixes #10478

[TreeView] Fix typing of the Multiple generic

---

docs/data/data-grid/localization/data.json
packages/grid/x-data-grid/src/locales/ruRU.ts

Updated remaining keys in the localization file for Russian (ru-RU) language https://github.com/mui/mui-x/issues/3211

[l10n] Improve Russian (ru-RU) locale

---

docs/data/data-grid/column-visibility/ColumnSelectorDisabledGrid.js
docs/data/data-grid/column-visibility/ColumnSelectorDisabledGrid.tsx
docs/data/data-grid/column-visibility/column-visibility.md
packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsInterfaces.ts

https://mui-org.slack.com/archives/C04U3R2V9UK/p1691095016645389

[docs] Add section about disabling columns panel

---

docs/data/data-grid/column-visibility/ColumnSelectorDisabledGrid.js
docs/data/data-grid/column-visibility/ColumnSelectorDisabledGrid.tsx

To fix Argos' inconsistencies like: https://app.argos-ci.com/mui/mui-x/builds/14056/60181948
Thanks @LukasTy for reporting 🙏

[DataGrid] Make `disableColumnSelector` demo idempotent

---

docs/data/date-pickers/custom-field/DateRangePickerWithButtonField.js
docs/data/date-pickers/custom-field/DateRangePickerWithButtonField.tsx
docs/data/date-pickers/custom-field/DateRangePickerWithButtonField.tsx.preview
docs/data/date-pickers/custom-field/PickerWithButtonField.js
docs/data/date-pickers/custom-field/PickerWithButtonField.tsx
docs/data/date-pickers/custom-field/PickerWithButtonField.tsx.preview
docs/data/date-pickers/custom-field/custom-field.md

Improve based on https://github.com/mui/mui-x/issues/10469

[docs] Add `DateRangePicker` example with a `Button` trigger

---

docs/pages/x/api/charts/charts-tooltip.json
docs/translations/api-docs/charts/charts-tooltip.json
packages/x-charts/src/BarChart/BarChart.tsx
packages/x-charts/src/ChartsTooltip/ChartsAxisTooltipContent.tsx
packages/x-charts/src/ChartsTooltip/ChartsItemTooltipContent.tsx
packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx
packages/x-charts/src/LineChart/LineChart.tsx
packages/x-charts/src/PieChart/PieChart.tsx
packages/x-charts/src/ScatterChart/ScatterChart.tsx
packages/x-charts/src/SparkLineChart/SparkLineChart.tsx
scripts/x-charts.exports.json

[charts] Support `slots`/`slotProps` for the tooltip

---

packages/grid/x-data-grid/src/tests/filtering.DataGrid.test.tsx

Fixes https://github.com/mui/mui-x/pull/9863#discussion_r1296001604

[test] Fix `testEval` not invoking test assertions

---

packages/grid/x-data-grid-generator/src/services/random-generator.ts

I'm hopeful that this will avoid the need to change tests as in #10548 in the future.
https://github.com/mui/mui-x/assets/3165635/2756f11e-9acb-46f0-a5c2-c639e7c1b129

[test] Set UUID chance seed in visual tests

---

packages/grid/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx
packages/grid/x-data-grid/src/hooks/features/columnGrouping/gridColumnGroupsUtils.ts
packages/grid/x-data-grid/src/hooks/features/columnGrouping/useGridColumnGrouping.ts

Fixes #7041 
- Before: https://codesandbox.io/s/serene-feather-rrdrg7?file=/Demo.tsx
- After: https://codesandbox.io/s/tender-mccarthy-znsr3c?file=/Demo.tsx
Fixes #9286 
- Before: https://codesandbox.io/s/loving-borg-zqh3rc?file=/demo.tsx
- After: https://codesandbox.io/s/dark-moon-ffqz28?file=/package.json

[DataGridPro] Improve column grouping and column pinning friendship

---

packages/grid/x-data-grid/src/colDef/gridDateColDef.ts

Check https://github.com/mui/mui-x/issues/10496#issuecomment-1757070187
Fixes #10496
- Before: https://codesandbox.io/s/amazing-lederberg-xgrxhw?file=/Demo.tsx:0-1610
- After: https://codesandbox.io/s/withered-smoke-zjx2kl?file=/Demo.tsx

[DataGrid] Get quick filter to work OOTB with `date` and `datetime` fields

---

packages/grid/x-data-grid/src/components/GridRow.tsx
packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
packages/grid/x-data-grid/src/models/events/gridEventLookup.ts

Fixes https://github.com/mui/mui-x/pull/10252#issuecomment-1737639096
Before: https://codesandbox.io/s/jolly-forest-crqxcd?file=/Demo.tsx
After: https://codesandbox.io/s/charming-jerry-kgsfwj?file=/Demo.tsx
https://github.com/mui/mui-x/assets/13808724/06ecac24-5b06-4914-9874-3579bcd258b4
TODO:

[DataGrid] Update row hover behavior to match native hover

---

.github/ISSUE_TEMPLATE/1.bug.yml
.github/ISSUE_TEMPLATE/2.feature.yml
.github/ISSUE_TEMPLATE/3.pro-support.yml
.github/ISSUE_TEMPLATE/4.premium-support.yml
.github/ISSUE_TEMPLATE/5.priority-support.yml
.github/ISSUE_TEMPLATE/6.docs-feedback.yml
.github/ISSUE_TEMPLATE/7.rfc.yml
.github/workflows/ensure-triage-label.yml
.github/workflows/mark-duplicate.yml

[core] Update the issue templates to reflect the new support workflow

---

packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx

Fixes https://github.com/mui/mui-x/issues/10547
Before: https://codesandbox.io/s/exciting-leaf-md7m2f
After: https://codesandbox.io/s/elegant-dust-5pftwy

[DataGrid] Fix cells overlapping the scrollbar in iOS Safari

---

docs/data/charts/axis/HidingAxis.js
docs/data/charts/axis/HidingAxis.tsx
docs/data/charts/axis/HidingAxis.tsx.preview
docs/data/charts/axis/axis.md

Fix https://github.com/mui/mui-x/pull/9228#discussion_r1230910044

[docs] Add example about how to add an axis

---

packages/grid/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts
packages/grid/x-data-grid-premium/src/tests/cellSelection.DataGridPremium.test.tsx

Fix #10777
- Before: https://codesandbox.io/embed/cocky-jones-l7mnvn?fontsize=14&hidenavigation=1&theme=dark
- After: https://codesandbox.io/s/reverent-aj-6r83vw
Fix #10260

[DataGridPremium] Fix cell selection throwing index error on second page and beyond

---

docs/data/date-pickers/adapters-locale/adapters-locale.md

Found it while answering #10790

[docs] Fix non-closed warning

---

docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
docs/translations/api-docs/data-grid/data-grid-premium.json
docs/translations/api-docs/data-grid/data-grid-pro.json
docs/translations/api-docs/data-grid/data-grid.json
packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
packages/grid/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx
packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx
packages/grid/x-data-grid/src/DataGrid/useDataGridProps.ts
packages/grid/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts
packages/grid/x-data-grid/src/models/props/DataGridProps.ts

Closes https://github.com/mui/mui-x/issues/10704
Before: https://codesandbox.io/s/nostalgic-payne-dls9rd
After: https://codesandbox.io/s/charming-wind-m43lfq

[DataGrid] Allow changing debounce time for row positions calculation

---

packages/grid/x-data-grid/src/components/menu/columnMenu/menuItems/GridColumnMenuSortItem.tsx
packages/grid/x-data-grid/src/models/api/gridLocaleTextApi.ts

Fix #9568 
Preview: https://codesandbox.io/s/ecstatic-poitras-m6272m

[DataGrid][l10n] Allow to customize sorting label per column

---

docs/data/charts/overview/overview.md
docs/data/pages.ts

[docs] Fix charts docs as stable

---

docs/data/data-grid/style-recipes/StylingAllCellsButAggregation.js
docs/data/data-grid/style-recipes/StylingAllCellsButAggregation.tsx
docs/data/data-grid/style-recipes/style-recipes.md
docs/data/data-grid/style/StylingAllCells.js
docs/data/data-grid/style/StylingAllCells.tsx

---
It's all in the title
Fixes #10912

[data grid] Adds a recipe to style cells without impacting the aggregation cells

---

docs/data/charts/legend/HiddenLegend.js
docs/data/charts/legend/HiddenLegend.tsx
docs/data/charts/legend/HiddenLegend.tsx.preview
docs/data/charts/legend/legend.md
packages/x-charts/src/ChartsLegend/ChartsLegend.tsx

[docs] Document how to hide the legend (#10951)

---

scripts/README.md

Point no. 4 of https://www.notion.so/mui-org/MUI-X-Major-version-release-process-a27f296dfb9e4b33bdb767f3d6e8018c?pvs=4#e5e593391d9a4419ad4bbbe15e21f14b

[core] Update release instructions as per v7 configuration

---

docs/data/charts/overview/overview.md
docs/data/data-grid/getting-started/getting-started.md
docs/data/date-pickers/getting-started/getting-started.md
docs/data/tree-view/getting-started/getting-started.md
docs/src/modules/components/DataGridInstallationInstructions.js
docs/src/modules/components/PickersInstallationInstructions.js

Point no. 7 of https://www.notion.so/mui-org/MUI-X-Major-version-release-process-a27f296dfb9e4b33bdb767f3d6e8018c?pvs=4#e5e593391d9a4419ad4bbbe15e21f14b

[docs] Add `@next` tag to the installation instructions

---

packages/x-codemod/src/v7.0.0/data-grid/preset-safe/actual.spec.js
packages/x-codemod/src/v7.0.0/data-grid/preset-safe/expected.spec.js
packages/x-codemod/src/v7.0.0/data-grid/preset-safe/index.ts
packages/x-codemod/src/v7.0.0/data-grid/preset-safe/preset-safe.test.ts
packages/x-codemod/src/v7.0.0/pickers/preset-safe/actual.spec.js
packages/x-codemod/src/v7.0.0/pickers/preset-safe/expected.spec.js
packages/x-codemod/src/v7.0.0/pickers/preset-safe/preset-safe.test.ts
packages/x-codemod/src/v7.0.0/preset-safe/actual.spec.js
packages/x-codemod/src/v7.0.0/preset-safe/expected.spec.js
packages/x-codemod/src/v7.0.0/preset-safe/index.ts
packages/x-codemod/src/v7.0.0/preset-safe/preset-safe.test.ts

- Add the initial root level `v7.0.0/preset-safe`
- Add the data grid `preset-safe` including the `components` -> `slots` transformation

[codemod] Add `v7.0.0/preset-safe`

---

test/regressions/index.test.js

Backport of https://github.com/mui/mui-x/pull/11004 to `master`

[test] Wait for images to load

---

docs/data/introduction/support/support.md

Adds LTS section (with supported versions) to the support page.
https://deploy-preview-10927--material-ui-x.netlify.app/x/introduction/support/#long-term-support-lts

Add LTS section to support docs

---

docs/data/data-grid/localization/data.json
packages/grid/x-data-grid/src/locales/heIL.ts

[l10n] Improve Hebrew (he-IL) locale

---

docs/data/data-grid/localization/data.json
packages/grid/x-data-grid/src/locales/arSD.ts

Cherry-pick #11096 from master

[l10n] Improve Arabic (ar-SD) locale 

---

docs/data/date-pickers/localization/data.json
packages/grid/x-data-grid-generator/src/services/static-data.ts
packages/x-date-pickers/src/locales/index.ts
packages/x-date-pickers/src/locales/mk.ts
scripts/localeNames.js
scripts/x-date-pickers-pro.exports.json
scripts/x-date-pickers.exports.json

[l10n] Add Macedonian (mk) locale

---

packages/grid/x-data-grid/src/utils/domUtils.ts

Just found those very old functions that are not used anywhere while closing old issues

[grid] Remove unused utilities

---

CHANGELOG.md
package.json
packages/grid/x-data-grid-generator/package.json
packages/grid/x-data-grid-premium/package.json
packages/grid/x-data-grid-pro/package.json
packages/grid/x-data-grid/package.json
packages/x-charts/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json

Don't mind the incorrect branch name. 🙈 😭 
```bash
git push upstream master:docs-v6 -f
```
You can follow the deployment process [on the Netlify Dashboard](https://app.netlify.com/sites/material-ui-x/deploys?filter=docs-v6)
Once deployed, it will be accessible at https://material-ui-x.netlify.app/ for the `docs-v6` deployment.

Release 6.18.2

---

CHANGELOG.md
package.json
packages/grid/x-data-grid-generator/package.json
packages/grid/x-data-grid-premium/package.json
packages/grid/x-data-grid-pro/package.json
packages/grid/x-data-grid/package.json
packages/x-charts/package.json
packages/x-codemod/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json

Release v7.0.0-alpha.2

---

docs/pages/_app.js

[docs] Fix version links

---

.circleci/config.yml
package.json
packages/grid/x-data-grid-pro/src/tests/cellEditing.DataGridPro.test.tsx
packages/grid/x-data-grid-pro/src/tests/editComponents.DataGridPro.test.tsx
packages/grid/x-data-grid-pro/src/tests/rowEditing.DataGridPro.test.tsx
packages/grid/x-data-grid/src/components/cell/GridEditDateCell.tsx
packages/grid/x-data-grid/src/hooks/features/editing/useGridCellEditing.ts
packages/grid/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts
packages/grid/x-data-grid/src/models/api/gridEditingApi.ts
packages/grid/x-data-grid/src/models/params/gridEditCellParams.ts
packages/grid/x-data-grid/src/models/params/gridRowParams.ts
test/e2e/fixtures/DataGrid/KeyboardEditNumber.tsx
test/e2e/index.test.ts
yarn.lock

Cherry-pick of https://github.com/mui/mui-x/pull/9205 from `next`
Cherry-pick of https://github.com/mui/mui-x/pull/11086 from `next`

[DataGrid] Fix cell editing adding a leading "v" on paste

---

packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx

Fixes https://app.circleci.com/pipelines/github/mui/mui-x/47890/workflows/8209f60b-d916-42e9-ae4e-b724c73a27dc/jobs/274795

[core] yarn proptypes

---

packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.ts
packages/x-date-pickers/src/AdapterDateFnsJalali/AdapterDateFnsJalali.ts
packages/x-date-pickers/src/AdapterDayjs/AdapterDayjs.ts
packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts
packages/x-date-pickers/src/AdapterMoment/AdapterMoment.ts
packages/x-date-pickers/src/AdapterMomentHijri/AdapterMomentHijri.ts
packages/x-date-pickers/src/AdapterMomentJalaali/AdapterMomentJalaali.ts

[pickers] Use adapter methods instead of date library ones whenever possible

---

packages/grid/x-data-grid-premium/src/hooks/features/aggregation/wrapColumnWithAggregation.tsx

Fixes https://github.com/mui/mui-x/issues/11037
It's easier to [review without whitespace changes](https://github.com/mui/mui-x/pull/11201/files?w=1)
Before: https://codesandbox.io/p/sandbox/data-grid-community-forked-yj97y5
After: https://codesandbox.io/p/sandbox/data-grid-community-forked-wqq4sr

[DataGridPremium] Fix custom filter operators not working on aggregated column

---

docs/data/migration/migration-pickers-v6/migration-pickers-v6.md

Fixes https://app.circleci.com/pipelines/github/mui/mui-x/48188/workflows/bcae2c78-36f9-4f0e-80a6-7b7caa0c13bb/jobs/276524

[chore] Fix linter error

---

docs/data/data-grid/column-visibility/ColumnSelectorGridCustomizeColumns.js
docs/data/data-grid/column-visibility/ColumnSelectorGridCustomizeColumns.tsx
docs/data/data-grid/column-visibility/column-visibility.md

Cherry-pick https://github.com/mui/mui-x/pull/11238

[docs] Improve Data Grid togglable columns example

---

packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx
packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputValue.tsx

Cherry-pick of https://github.com/mui/mui-x/pull/11000 from `next`

[DataGrid] Fix onFilterModelChange being fired with stale field value

---

docs/data/date-pickers/adapters-locale/adapters-locale.md
packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts
packages/x-date-pickers/src/locales/utils/pickersLocaleTextApi.ts

[pickers] Expand field placeholder methods flexibility by providing `format` parameter

---

docs/data/whats-new/WhatsNewLayout.js
docs/data/whats-new/WhatsNewLayout.tsx

[docs] Add end v6 blogpost to whats new page (@joserodolfofreitas)

---

CHANGELOG.md
package.json
packages/grid/x-data-grid-generator/package.json
packages/grid/x-data-grid-premium/package.json
packages/grid/x-data-grid-pro/package.json
packages/grid/x-data-grid/package.json
packages/x-charts/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json

v7.0.0-alpha.3

---

packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx
packages/x-date-pickers/src/MultiSectionDigitalClock/multiSectionDigitalClockSectionClasses.ts

[pickers] Fix `MultiSectionDigitalClock` issues

---

docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md

Updated the documentation to include better understanding of how params are passed into the onPaginationModelChange prop.

[docs] Added params to onPaginationModelChange docs

---

packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx

[DateRangePicker] Fix `autoFocus` behavior  (@kealjones-wk)

---

docs/data/data-grid/column-groups/BasicGroupingDemo.js
docs/data/data-grid/column-groups/BasicGroupingDemo.tsx
docs/data/data-grid/column-groups/BreakingGroupDemo.js
docs/data/data-grid/column-groups/BreakingGroupDemo.tsx
docs/data/data-grid/column-groups/CustomizationDemo.js
docs/data/data-grid/column-groups/CustomizationDemo.tsx
docs/data/data-grid/overview/DataGridDemo.js
docs/data/data-grid/overview/DataGridDemo.tsx
packages/grid/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx

OCD request. Jamie and Cersei are twins, they should be the same age.

[docs] Respect GoT books

---

docs/data/data-grid/column-groups/BasicGroupingDemo.js
docs/data/data-grid/column-groups/BasicGroupingDemo.tsx
docs/data/data-grid/column-groups/BreakingGroupDemo.js
docs/data/data-grid/column-groups/BreakingGroupDemo.tsx
docs/data/data-grid/column-groups/CustomizationDemo.js
docs/data/data-grid/column-groups/CustomizationDemo.tsx
docs/data/data-grid/overview/DataGridDemo.js
docs/data/data-grid/overview/DataGridDemo.tsx

Just realized the PR was pointing to the master branch
Cherry-pick #11294

[docs] Respect GoT books (@janoma)

---

docs/data/data-grid/row-selection/ControlledSelectionServerPaginationGrid.js
docs/data/data-grid/row-selection/ControlledSelectionServerPaginationGrid.tsx
docs/data/data-grid/row-updates/InfiniteLoadingGrid.js
docs/data/data-grid/row-updates/InfiniteLoadingGrid.tsx
packages/grid/x-data-grid-generator/src/hooks/useQuery.ts

Fixes https://app.argos-ci.com/mui/mui-x/builds/15959/67670174 (Hopefully 🤞🏻)

[test] Fix flaky screenshots

---

CHANGELOG.md

[pickers] Add missing breaking changes to changelog

---

docs/data/date-pickers/localization/data.json
packages/x-date-pickers/src/locales/ruRU.ts

[l10n] Improve Russian (ru-RU) locale (@wensiet)

---

docs/data/date-pickers/date-picker/FormPropsDatePickers.js
docs/data/date-pickers/date-picker/FormPropsDatePickers.tsx
docs/data/date-pickers/date-picker/FormPropsDatePickers.tsx.preview
docs/data/date-pickers/date-range-picker/SingleInputDateRangePicker.js
docs/data/date-pickers/date-range-picker/SingleInputDateRangePicker.tsx
docs/data/date-pickers/date-range-picker/SingleInputDateRangePicker.tsx.preview
docs/data/date-pickers/date-range-picker/date-range-picker.md
docs/data/date-pickers/date-time-picker/FormPropsDateTimePickers.js
docs/data/date-pickers/date-time-picker/FormPropsDateTimePickers.tsx
docs/data/date-pickers/date-time-picker/FormPropsDateTimePickers.tsx.preview
docs/data/date-pickers/time-picker/FormPropsTimePickers.js
docs/data/date-pickers/time-picker/FormPropsTimePickers.tsx
docs/data/date-pickers/time-picker/FormPropsTimePickers.tsx.preview

[docs] Improve Pickers `name` prop examples

---

test/regressions/index.test.js

Fixes https://app.circleci.com/pipelines/github/mui/mui-x/49371/workflows/4bd02d71-8663-4111-9b04-55f29f5e57be/jobs/283177
When one test demo crashes, the remaining ones will time out because the page is empty and there are no links to the remaining tests
This gives the wrong impression that half of the test suite is broken, while it could be only one demo that has thrown an error on mount 🙃

[test] Reload the page if its blank and there are no links to the remaining tests

---

CHANGELOG.md
docs/pages/x/api/charts/charts-text.json
package.json
packages/grid/x-data-grid-generator/package.json
packages/grid/x-data-grid-premium/package.json
packages/grid/x-data-grid-pro/package.json
packages/grid/x-data-grid/package.json
packages/x-charts/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json

[release] V6.18.6

---

CHANGELOG.md
package.json
packages/grid/x-data-grid-generator/package.json
packages/grid/x-data-grid-premium/package.json
packages/grid/x-data-grid-pro/package.json
packages/grid/x-data-grid/package.json
packages/x-charts/package.json
packages/x-codemod/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json

[release] v7.0.0-alpha.6

---

CHANGELOG.md

Fix the version in the changelog to be aligned with the latest released package version.
If you think that it makes more sense to re-release the package, feel free to do that, but IMHO, that's not strictly necessary. 🤔

[changelog] Fix charts version

---

CHANGELOG.md
packages/x-charts/package.json

Follow-up of https://github.com/mui/mui-x/pull/11492#discussion_r1435385971

[core] Fix release changelog

---

packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx
packages/x-date-pickers/src/internals/components/PickersInput/PickersFilledInput.tsx
packages/x-date-pickers/src/internals/components/PickersInput/PickersStandardInput.tsx

See https://stackoverflow.com/questions/7327326/what-is-the-difference-between-before-and-before for why, for the sake of correctness and gaining trust with our most exigent users.

[core] Fix use of ::before & ::after

---

docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
packages/grid/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx
packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx
packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx

[DataGrid] warn devs when `autoPageSize` used with `autoheight`

---

docs/data/charts/overview/ChartsOverviewDemo.js
docs/data/charts/overview/ChartsOverviewDemo.tsx
docs/data/charts/overview/ChartsOverviewDemo.tsx.preview
docs/data/charts/overview/overview.md

This PR adds a simple demo to the Charts Overview page as suggested here https://github.com/mui/mui-x/pull/11533#issuecomment-1875980853. It's nice as it gets consistent with the other respective Overview pages!
https://deploy-preview-11569--material-ui-x.netlify.app/x/react-charts/

[charts][docs] Add demo to the Overview page

---

CHANGELOG.md
package.json
packages/grid/x-data-grid-generator/package.json
packages/grid/x-data-grid-premium/package.json
packages/grid/x-data-grid-pro/package.json
packages/grid/x-data-grid/package.json
packages/x-charts/package.json
packages/x-codemod/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-tree-view/package.json
yarn.lock

v7.0.0-alpha.7

---

docs/data/charts/overview/overview.md
docs/src/modules/components/ChartComponentsGrid.js

A continuation of https://github.com/mui/mui-x/pull/11533
Preview: https://deploy-preview-11570--material-ui-x.netlify.app/x/react-charts/

[charts][docs] Improve landing page

---

packages/x-date-pickers/src/hooks/useClearableField.tsx

[pickers] Fix clearable behavior blocking focus return to `OpenPickerButton`

---

.circleci/config.yml

The problem was solved differently between:
- https://github.com/mui/material-ui/pull/39131/files
- https://github.com/mui/mui-x/pull/9413/files
This PR matches the solution. 
Same as https://github.com/mui/material-ui/pull/40475

[core] Sync playwright cache between MUI X and Material UI

---

yarn.lock

Needed for https://github.com/mui/mui-x/pull/11280

[core] Bump monorepo

---

.github/styles/Blog/BrandName.yml
.github/styles/Blog/ComponentNaming.yml
.github/styles/Blog/ComposedWords.yml
.github/styles/Blog/NamingConventions.yml
.github/styles/Blog/NoCompanyName.yml
.vale.ini

Same as https://github.com/mui/material-ui/pull/40525

[docs-infra] Enforce brand name rules

---

docs/data/migration/migration-pickers-v6/migration-pickers-v6.md

Follow-up on https://github.com/mui/mui-x/pull/11612#discussion_r1452833972

[docs] Fix Pickers migration syntax and diffs

---

packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts

Follow-up on https://github.com/mui/mui-x/pull/11594

[pickers] Fix AdapterLuxon `getWeekNumber` behavior

---

docs/pages/x/api/tree-view/rich-tree-view.json
docs/pages/x/api/tree-view/simple-tree-view.json
docs/pages/x/api/tree-view/tree-item.json
docs/pages/x/api/tree-view/tree-view.json
docs/translations/api-docs/tree-view/rich-tree-view/rich-tree-view.json
docs/translations/api-docs/tree-view/simple-tree-view/simple-tree-view.json
docs/translations/api-docs/tree-view/tree-item/tree-item.json
docs/translations/api-docs/tree-view/tree-view/tree-view.json

The CI is red ❌ 😱 
https://github.com/mui/mui-x/commits/next/

[docs] Fix generated tree view API docs

---

docs/data/data-grid/components/components.md

Spotted this issue while reviewing #11759

[docs] Fix typo in Data Grid components page

---

packages/x-date-pickers-pro/src/MultiInputDateRangeField/MultiInputDateRangeField.types.ts
packages/x-date-pickers-pro/src/MultiInputDateTimeRangeField/MultiInputDateTimeRangeField.types.ts
packages/x-date-pickers-pro/src/MultiInputTimeRangeField/MultiInputTimeRangeField.types.ts
packages/x-date-pickers-pro/src/SingleInputDateRangeField/SingleInputDateRangeField.tsx
packages/x-date-pickers-pro/src/SingleInputDateTimeRangeField/SingleInputDateTimeRangeField.tsx
packages/x-date-pickers-pro/src/SingleInputTimeRangeField/SingleInputTimeRangeField.tsx
packages/x-date-pickers-pro/src/internals/hooks/useEnrichedRangePickerFieldProps.ts
packages/x-date-pickers-pro/src/internals/hooks/useMultiInputRangeField/useMultiInputRangeField.types.ts
packages/x-date-pickers-pro/src/internals/models/fields.ts

Extracted from https://github.com/mui/mui-x/pull/9528

[pickers] Fields typing optimization

---

docs/data/tree-view/rich-tree-view/expansion/expansion.md
docs/data/tree-view/rich-tree-view/selection/DisableSelection.js
docs/data/tree-view/rich-tree-view/selection/DisableSelection.tsx
docs/data/tree-view/rich-tree-view/selection/DisableSelection.tsx.preview
docs/data/tree-view/rich-tree-view/selection/selection.md
docs/data/tree-view/simple-tree-view/expansion/expansion.md
docs/data/tree-view/simple-tree-view/selection/DisableSelection.js
docs/data/tree-view/simple-tree-view/selection/DisableSelection.tsx
docs/data/tree-view/simple-tree-view/selection/selection.md

We are documenting it on the data grid so I guess we also need a section for the tree view

[docs] Add section for the `disableSelection` prop

---

docs/data/charts/areas-demo/AreaChartFillByValue.js
docs/data/charts/areas-demo/AreaChartFillByValue.tsx
docs/data/charts/areas-demo/areas-demo.md
packages/x-charts/src/hooks/useDrawingArea.ts

Fix #11818
Adding this demo: https://deploy-preview-11824--material-ui-x.netlify.app/x/react-charts/areas-demo/#areachartfillbyvalue

[chart] Document how to modify color according to values

---

docs/data/data-grid/column-visibility/column-visibility.md

Followup to #10794
Changes:
- Corrects slot name `columnsPanel` -> `columnsManagement`
- Add a snippet to reduce some friction in using the prop

[docs] Improve column visibility documentation

---

docs/pages/x/api/date-pickers/time-picker-toolbar.json
docs/translations/api-docs/date-pickers/time-picker-toolbar/time-picker-toolbar.json
packages/x-date-pickers/src/TimePicker/timePickerToolbarClasses.ts

[TimePicker] Add missing toolbar classes descriptions (#11856)

---

docs/pages/x/api/date-pickers/date-picker.json
docs/pages/x/api/date-pickers/date-range-picker.json
docs/pages/x/api/date-pickers/date-time-picker.json
docs/pages/x/api/date-pickers/time-picker.json
docs/translations/api-docs/date-pickers/date-picker/date-picker.json
docs/translations/api-docs/date-pickers/date-range-picker/date-range-picker.json
docs/translations/api-docs/date-pickers/date-time-picker/date-time-picker.json
docs/translations/api-docs/date-pickers/time-picker/time-picker.json
scripts/buildApiDocs/pickersSettings/getComponentInfo.ts

[docs] Fix docs:api when typo in slots typing

---

packages/grid/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts

[DataGrid] Fix row reorder with cell selection

---

docs/src/modules/components/WhatsNewLayout.js

Update with content from the latest blog post
https://mui.com/blog/mui-x-v7-beta/
https://deploy-preview-11879--material-ui-x.netlify.app/x/whats-new/

[docs] Update whats new page with "v7 Beta blogpost" content

---

docs/data/data-grid/column-definition/ActionsWithModalGrid.js
docs/data/data-grid/column-definition/ActionsWithModalGrid.tsx
docs/data/data-grid/column-definition/ActionsWithModalGrid.tsx.preview
docs/data/data-grid/column-definition/column-definition.md
packages/grid/x-data-grid/src/components/cell/GridActionsCell.tsx
packages/grid/x-data-grid/src/components/cell/GridActionsCellItem.tsx

Closes https://github.com/mui/mui-x/issues/11579
Preview: https://deploy-preview-11909--material-ui-x.netlify.app/x/react-data-grid/column-definition/#system-ActionsWithModalGrid.tsx

[DataGrid] Add support for dialogs in menu actions

---

packages/grid/x-data-grid/src/components/cell/GridActionsCellItem.tsx

Fixes https://app.circleci.com/pipelines/github/mui/mui-x/52341/workflows/9ab2a8f1-d438-4bb5-a647-e0e3ce46d9da/jobs/299661
Regression after merging https://github.com/mui/mui-x/pull/11909 and https://github.com/mui/mui-x/pull/11795

[core] Fix `test_types` failing on the `next` branch

---

docs/pages/x/api/charts/default-charts-axis-tooltip-content.json
packages/x-charts/src/ChartsTooltip/ChartsAxisTooltipContent.tsx
packages/x-charts/src/ChartsTooltip/DefaultChartsAxisTooltipContent.tsx
packages/x-charts/src/context/InteractionProvider.tsx

[charts] Fix Proptypes by support string values for axes

---

packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts

Cherry-pick of https://github.com/mui/mui-x/pull/11557

[DataGrid] Replace `eval` with `new Function`

---

docs/data/introduction/support/support.md

Fixes https://app.circleci.com/pipelines/github/mui/mui-x/52473/workflows/b36fc8b3-b753-4ebf-b6d4-194ec095f430/jobs/300467

[core] Fix failing `test_static` on the next branch

---

packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts

Cherry-pick of https://github.com/mui/mui-x/pull/11870

[DataGridPremium] Fix autosize grouping cell (@romgrk)

---

docs/pages/x/api/charts/bar-chart.json
docs/pages/x/api/charts/line-chart.json
docs/pages/x/api/charts/pie-chart.json
docs/pages/x/api/charts/scatter-chart.json
docs/translations/api-docs/charts/bar-chart/bar-chart.json
docs/translations/api-docs/charts/line-chart/line-chart.json
docs/translations/api-docs/charts/pie-chart/pie-chart.json
docs/translations/api-docs/charts/scatter-chart/scatter-chart.json
packages/x-charts/src/BarChart/BarChart.tsx
packages/x-charts/src/LineChart/LineChart.tsx
packages/x-charts/src/PieChart/PieChart.tsx
packages/x-charts/src/PieChart/PiePlot.tsx
packages/x-charts/src/ScatterChart/ScatterChart.tsx

[docs] Complete charts API pages

---

packages/x-tree-view/src/TreeItem/useTreeItemState.ts
packages/x-tree-view/src/internals/plugins/useTreeViewJSXNodes/useTreeViewJSXNodes.tsx

The instance is always defined

[TreeView] Remove instance existence checks

---

docs/.link-check-errors.txt
docs/data/data-grid/getting-started/getting-started.md
docs/data/date-pickers/getting-started/getting-started.md
docs/data/tree-view/getting-started/getting-started.md
docs/scripts/reportBrokenLinks.js

Cherry-pick of https://github.com/mui/mui-x/pull/12135.

[core] Fix docs link check

---

packages/x-charts/src/ChartsXAxis/ChartsXAxis.tsx
packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx
packages/x-charts/src/hooks/useTicks.ts

[charts] Fix typo in JSDoc

---

docs/data/date-pickers/localization/data.json
packages/x-date-pickers/src/locales/koKR.ts

[l10n] Improve Korean (ko-KR) locale

---

CHANGELOG.md
package.json
packages/x-charts/package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-tree-view/package.json

```bash
```
You can follow the deployment process [on the Netlify Dashboard](https://app.netlify.com/sites/material-ui-x/deploys?filter=docs-v6)
Once deployed, it will be accessible at https://material-ui-x.netlify.app/ for the `docs-v6` deployment.

v7.0.0-beta.4

---

packages/x-data-grid/src/colDef/gridBooleanOperators.ts

[data grid] boolean filter "is" uses string version of true for determining truthiness

---

packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx

Closes https://github.com/mui/mui-x/issues/12209

[DataGridPro] Fix column resize errors on MacOS with automatic scrollbars enabled

---

docs/data/data-grid/row-updates/LazyLoadingGrid.js
docs/data/data-grid/row-updates/LazyLoadingGrid.tsx
docs/data/data-grid/row-updates/row-updates.md

Preview: https://deploy-preview-12062--material-ui-x.netlify.app/x/react-data-grid/row-updates/#lazy-loading

[docs] Update lazy loading demo to show skeleton rows during initial rows fetch

---

packages/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx

Closes https://github.com/mui/mui-x/issues/12264

[DataGrid] Render scrollbars only if there is scroll

---

packages/x-data-grid/src/hooks/features/sorting/useGridSorting.ts
packages/x-data-grid/src/tests/sorting.DataGrid.test.tsx

[DataGrid] Fix empty sort being saved in the `sortModel`

---

docs/data/date-pickers/adapters-locale/adapters-locale.md

Closes https://github.com/mui/mui-x/issues/12323.

[docs] Update `date-fns` `weekStarsOn` overriding example

---

docs/data/migration/migration-tree-view-v6/migration-tree-view-v6.md
docs/pages/x/api/tree-view/rich-tree-view.json
docs/pages/x/api/tree-view/simple-tree-view.json
docs/pages/x/api/tree-view/tree-view.json
docs/translations/api-docs/tree-view/rich-tree-view/rich-tree-view.json
docs/translations/api-docs/tree-view/simple-tree-view/simple-tree-view.json
docs/translations/api-docs/tree-view/tree-item-2/tree-item-2.json
docs/translations/api-docs/tree-view/tree-item/tree-item.json
docs/translations/api-docs/tree-view/tree-view/tree-view.json
packages/x-codemod/README.md
packages/x-codemod/src/v7.0.0/tree-view/preset-safe/index.ts
packages/x-codemod/src/v7.0.0/tree-view/rename-focus-callback/actual.spec.js
packages/x-codemod/src/v7.0.0/tree-view/rename-focus-callback/expected.spec.js
packages/x-codemod/src/v7.0.0/tree-view/rename-focus-callback/index.ts
packages/x-codemod/src/v7.0.0/tree-view/rename-focus-callback/rename-focus-callback.test.ts
packages/x-tree-view/src/RichTreeView/RichTreeView.tsx
packages/x-tree-view/src/SimpleTreeView/SimpleTreeView.test.tsx
packages/x-tree-view/src/SimpleTreeView/SimpleTreeView.tsx
packages/x-tree-view/src/TreeItem/TreeItem.test.tsx
packages/x-tree-view/src/TreeItem/TreeItem.tsx
packages/x-tree-view/src/TreeItem/TreeItem.types.ts
packages/x-tree-view/src/TreeItem2/TreeItem2.tsx
packages/x-tree-view/src/TreeItem2/TreeItem2.types.ts
packages/x-tree-view/src/TreeView/TreeView.tsx
packages/x-tree-view/src/internals/plugins/useTreeViewFocus/useTreeViewFocus.ts
packages/x-tree-view/src/internals/plugins/useTreeViewFocus/useTreeViewFocus.types.ts

part of https://github.com/mui/mui-x/issues/12262

[TreeView] Rename `onNodeFocus` to `onItemFocus`

---

docs/pages/x/api/data-grid/selectors.json
packages/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts
packages/x-data-grid-premium/src/tests/cellSelection.DataGridPremium.test.tsx
packages/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts
packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts
packages/x-data-grid/src/hooks/features/headerFiltering/gridHeaderFilteringSelectors.ts
packages/x-data-grid/src/hooks/features/headerFiltering/useGridHeaderFiltering.ts
packages/x-data-grid/src/models/gridHeaderFilteringModel.ts
scripts/x-data-grid-premium.exports.json
scripts/x-data-grid-pro.exports.json
scripts/x-data-grid.exports.json

Fixes https://github.com/mui/mui-x/issues/12266

[DataGridPremium] Fix auto-scroll not working when selecting cell range

---

docs/pages/_app.js

Preparation for the v7 release.
Covers https://www.notion.so/mui-org/v7-stable-release-9f3fded55b9c425c80c03e9813dc8171?pvs=4#cecea937ca5c4acdb783a753378f739a

[docs] Update links to v6

---

docs/pages/_app.js

Preparation for the v7 release.
Covers https://www.notion.so/mui-org/v7-stable-release-9f3fded55b9c425c80c03e9813dc8171?pvs=4#09786a998ce34c06a918946de3295c59

[docs] Update links to v7

---

docs/translations/api-docs/tree-view/tree-view/tree-view.json
packages/x-date-pickers/src/internals/hooks/useField/useFieldV7TextField.ts
packages/x-tree-view/src/RichTreeView/RichTreeView.tsx
packages/x-tree-view/src/SimpleTreeView/SimpleTreeView.tsx
packages/x-tree-view/src/TreeView/TreeView.tsx

[docs] Update links to v7 docs

---

package.json

Covers https://www.notion.so/mui-org/v7-stable-release-9f3fded55b9c425c80c03e9813dc8171?pvs=4#64971896345c456e92320d00f811b284

[core] Update NPM tag

---

docs/data/introduction/support/support.md

Updated supported versions to:
- v7 as current stable
- v6 as long term support
- Discontinued support for v5
https://deploy-preview-12508--material-ui-x.netlify.app/x/introduction/support/

[docs] Update supported versions

---

package.json

[core] Update prettier script to use `master` branch 

---

docs/data/pages.ts

To highlight the v7 migration.
| ------- | ----- |
| <img width="283" src="https://github.com/mui/mui-x/assets/13808724/cd94e79d-44ca-4d9c-8c06-cebaafa6225b"> | <img width="298" alt="Screenshot 2024-03-25 at 13 17 55" src="https://github.com/mui/mui-x/assets/13808724/f761567f-158e-4e9c-9988-e3b26f7c343b"> |

[docs] Reduce noize in migration docs side navigation

---

docs/data/pages.ts

[docs] Fix small typo

---

docs/data/data-grid/localization/data.json
docs/data/date-pickers/localization/data.json
packages/x-date-pickers/src/locales/zhHK.ts

[l10n] Improve Chinese (Hong Kong) (zh-HK) locale

---

docs/data/charts/getting-started/getting-started.md
docs/data/charts/overview/overview.md

This is more aligned to what developers search on Google.

[docs] Chart title for SEO

---

packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.ts
packages/x-tree-view/src/internals/plugins/useTreeViewJSXItems/useTreeViewJSXItems.tsx

[TreeView] Fix typo in errors

---

docs/data/migration/migration-tree-view-v6/migration-tree-view-v6.md

[docs] Fix grammar in TreeView migration doc

---

packages/x-tree-view/src/internals/plugins/useTreeViewFocus/useTreeViewFocus.types.ts
packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.types.ts

Based on https://github.com/mui/mui-x/pull/12595#discussion_r1543092884

[TreeView] Add JSDoc to all `publicAPI` methods

---

packages/x-tree-view/src/internals/plugins/useTreeViewExpansion/useTreeViewExpansion.test.tsx

Fixes https://app.circleci.com/pipelines/github/mui/mui-x/56079/workflows/4ad6822b-1e21-41cf-a779-6330ba7c360b/jobs/320837
https://mui-org.slack.com/archives/C011VC970AW/p1712171855235309

[test] Fix TreeView test import

---

docs/data/data-grid/events/events.json
docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md
docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
docs/translations/api-docs/data-grid/data-grid-premium/data-grid-premium.json
docs/translations/api-docs/data-grid/data-grid-pro/data-grid-pro.json
docs/translations/api-docs/data-grid/data-grid/data-grid.json
packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
packages/grid/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx
packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx
packages/grid/x-data-grid/src/models/events/gridEventLookup.ts
packages/grid/x-data-grid/src/models/props/DataGridProps.ts

[DataGrid] Remove legacy editing API event: `rowEditCommit`

---

docs/data/migration/migration-pickers-v6/migration-pickers-v6.md

[docs] Fix typo in Pickers v7 migration page

---

docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md

[docs] Fix typo in Data Grid v7 migration page

---

packages/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts

Fixes https://github.com/mui/mui-x/issues/12723
Preview: https://deploy-preview-12724--material-ui-x.netlify.app/x/react-data-grid/clipboard/#events

[DataGridPremium] Fix clipboard paste not working when cell loses focus

---

packages/grid/x-data-grid-pro/src/components/headerFiltering/GridHeaderFilterCell.tsx
packages/grid/x-data-grid-pro/src/utils/domUtils.ts
packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx
packages/grid/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx

Cherry-pick of https://github.com/mui/mui-x/pull/12553
As per https://github.com/mui/mui-x/pull/12553#issuecomment-2049392687

[DataGrid] Fix bug in suspense

---

docs/data/data-grid/localization/data.json
docs/data/date-pickers/localization/data.json
packages/x-data-grid/src/locales/deDE.ts
packages/x-date-pickers/src/locales/deDE.ts

Adds missing translations for the German (de-DE) locale.

[l10n] Improve German (de-DE) locale

---

packages/x-date-pickers-pro/src/DateTimeRangePicker/DateTimeRangePickerToolbar.tsx

Fix a regression introduced by https://github.com/mui/mui-x/pull/12003/files#diff-98ff2e054c9262171192808f81a42fb64c0bef346b1e905d86e7719949c28ef6

[DateTimeRangePicker] Fix desktop toolbar style

---

packages/x-data-grid/src/components/cell/GridCell.tsx

Closes https://github.com/mui/mui-x/issues/12860
Demo: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-sc7cdn

[DataGrid] Derive `formattedValue` from the edit value when passing to `renderEditCell`

---

packages/x-charts/src/BarChart/BarChart.tsx
packages/x-data-grid-generator/src/services/gridColDefGenerator.ts
packages/x-data-grid-generator/src/services/tree-data-generator.ts
packages/x-data-grid-premium/src/hooks/features/rowGrouping/createGroupingColDef.tsx
packages/x-data-grid-pro/src/models/gridGroupingColDefOverride.ts
packages/x-data-grid/src/components/panel/filterPanel/GridFilterPanel.tsx
packages/x-data-grid/src/hooks/features/filter/gridFilterState.ts
packages/x-data-grid/src/models/api/gridCoreApi.ts
packages/x-date-pickers/src/PickersDay/PickersDay.tsx

A random cleanup while I was looking at something else.

[core] Remove inconsistent blank lines

---

docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md

[docs] Improve Data Grid migration guide

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/skSK.ts

Supplemented Slovak translation

[l10n] Improve Slovak (sk-SK) locale

---

.github/workflows/add-release-reviewers.yml

---
Hopefully the last fix now ... simplified the usage of env vars

[infra] Fix automated reviewers assignment workflow - part 2

---

.github/workflows/add-release-reviewers.yml

---
sry @JCQuintas ... one last time (I hope) :P

[infra] Fix automated reviewers assignment workflow - part 3

---

.github/workflows/add-release-reviewers.yml

---
@JCQuintas lets hope for the best this time! :D

[infra] changed to usage of reusable workflow

---

packages/x-data-grid-pro/src/tests/rowEditing.DataGridPro.test.tsx

It's no longer possible: https://react.dev/blog/2024/04/25/react-19-upgrade-guide#ref-cleanup-required

[core] Prepare React 19

---

.github/workflows/add-release-reviewers.yml

[infra] changed version to use master branch for now

---

.github/workflows/add-release-reviewers.yml

[infra] changed permission for nested workflow

---

.github/workflows/add-release-reviewers.yml

[infra] Changed action target branch

---

test/regressions/index.js
test/utils/mochaHooks.js

Follow-up on https://github.com/mui/mui-x/pull/8917.
Once again update the license key for tests.
Or would you suggest having **a public** perpetual key for tests to avoid the need for updating? 🤔

[core] Update license key used for tests

---

docs/data/data-grid/column-pinning/column-pinning.md

Fixes https://app.slack.com/client/TS83SPSTV/C04U3R2V9UK

[docs] Update interface name in pinned columns docs

---

pnpm-lock.yaml
test/package.json
test/regressions/index.js
test/utils/mochaHooks.js
test/utils/testLicense.js

Try the suggested idea: https://github.com/mui/mui-x/pull/13052#issuecomment-2100388668.

[core] Refactor tests license setting

---

packages/x-charts/package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-tree-view/package.json

Forgot to increase the package versions on the release PR.

v7.4.0 fix

---

package.json

v7.4.0 fix 2

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/nbNO.ts

Added data grid columns management Norwegian translations
Did it after this PR: https://github.com/mui/mui-x/pull/12844

[l10n] Improve Norwegian (nb-NO) locale

---

packages/x-data-grid/src/locales/esES.ts

finishing the spanish translation in this document

[l10n] Improve Spanish (es-SE) locale

---

docs/data/date-pickers/calendar-systems/AdapterJalali.tsx
docs/data/date-pickers/calendar-systems/AdapterJalali.tsx.preview
docs/data/date-pickers/calendar-systems/AdapterMomentJalali.js
docs/data/date-pickers/calendar-systems/AdapterMomentJalali.tsx
docs/data/date-pickers/calendar-systems/AdapterMomentJalali.tsx.preview
docs/data/date-pickers/calendar-systems/calendar-systems.md
docs/data/date-pickers/timezone/MomentTimezone.js
docs/data/date-pickers/timezone/MomentTimezone.tsx
docs/data/date-pickers/timezone/MomentUTC.js
docs/data/date-pickers/timezone/MomentUTC.tsx
docs/package.json
package.json
packages/x-date-pickers/src/AdapterMomentJalaali/AdapterMomentJalaali.ts
test/e2e/fixtures/DatePicker/MomentJalaliDateCalendar.tsx
test/e2e/index.test.ts
test/regressions/index.js
test/utils/mochaHooks.js
test/utils/testLicense.js

Cherry-pick https://github.com/mui/mui-x/pull/13144.
Add a `clean:node_modules` script.
Cherry-pick #13076 to fix test failures.

[pickers] Fix `AdapterMomentJalaali` regression

---

package.json

[core] Fix version in root package.json

---

lerna.json

Enable `nx` for lerna task orchestration.
Aligns the setup with other repositories.
There do not seem to be any clear performance issues with `nx` orchestration enabled.
https://app.circleci.com/pipelines/github/mui/mui-x/58373/workflows/bbbc2903-3673-4ddd-80a6-2fdcd2b1e417
https://app.circleci.com/pipelines/github/mui/mui-x/58366/workflows/e11633f2-759c-4f1b-b459-748cdc73fa14

[code-infra] Use `nx` for lerna tasks

---

packages/x-charts/src/BarChart/BarLabel/BarLabel.tsx
packages/x-charts/src/BarChart/BarLabel/BarLabelItem.tsx
packages/x-charts/src/BarChart/BarLabel/BarLabelPlot.tsx

Fix yarn proptypes vs pnpm proptypes

---

docs/data/date-pickers/faq/faq.md

[docs] Fix Pickers FAQ callout

---

.github/workflows/l10n.yml

Fix https://github.com/mui/mui-x/actions/runs/9385072077/job/25842318591 after merging https://github.com/mui/mui-x/pull/13344.

[core] Fix `l10n` action setup

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/ptBR.ts

Translated the columnsManagementReset key introduced in 7.3.2

[l10n] Improve Portuguese (pt-PT) locale

---

docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
docs/translations/api-docs/data-grid/data-grid-premium/data-grid-premium.json
docs/translations/api-docs/data-grid/data-grid-pro/data-grid-pro.json
docs/translations/api-docs/data-grid/data-grid/data-grid.json
packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx
packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderSortIcon.tsx
packages/x-data-grid/src/constants/defaultGridSlotsComponents.ts
packages/x-data-grid/src/models/gridSlotsComponent.ts
packages/x-data-grid/src/models/gridSlotsComponentsProps.ts
scripts/x-data-grid-premium.exports.json
scripts/x-data-grid-pro.exports.json
scripts/x-data-grid.exports.json

[DataGrid] Add `columnHeaderSortIcon` slot

---

packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx

[charts] Support RTL for y-axis

---

docs/package.json
packages/eslint-plugin-material-ui/package.json
packages/x-internals/package.json
pnpm-lock.yaml
test/package.json

https://github.com/mui/mui-x/pull/13662 has been merged without syncing with master and caused out of sync lock file due to the `@mui/x-internals` package recent merge and an action failure: https://github.com/mui/mui-x/actions/runs/9744053494/job/26888856146
Going to auto-merge.

[core] Fix dependency setup

---

packages/x-charts/src/ChartsAxisHighlight/ChartsAxisHighlight.tsx

[charts] Fix Axis Highlight on horizontal bar charts regression

---

docs/data/charts/tooltip/tooltip.md

[charts] Instruct how to disable the tooltip to docs

---

docs/data/charts/pie-demo/OnSeriesItemClick.js
docs/data/charts/pie-demo/OnSeriesItemClick.tsx

[charts] Use correct click handler prop on pie chart `OnSeriesItemClick` documentation

---

docs/data/charts/getting-started/getting-started.md
docs/data/data-grid/getting-started/getting-started.md
docs/data/date-pickers/getting-started/getting-started.md
docs/data/migration/migration-pickers-lab/migration-pickers-lab.md
docs/data/migration/migration-tree-view-lab/migration-tree-view-lab.md
docs/data/tree-view/getting-started/getting-started.md
docs/src/modules/components/InstallationInstructions.tsx

Part of https://github.com/mui/material-ui/issues/42699
https://deploy-preview-13894--material-ui-x.netlify.app/x/react-data-grid/getting-started/#installation
There will be more to migrate, but at least, it's going in the right direction.

[docs] Bump pnpm priority as a package manager

---

docs/data/date-pickers/localization/data.json
packages/x-date-pickers/src/locales/index.ts
packages/x-date-pickers/src/locales/nnNO.ts

- Adds norwegian nynorsk (nnNO) locale to x-date-pickers

[l10n] Add Norwegian Nynorsk (nn-NO) locale

---

renovate.json

To group these:
Will force auto-merge.

[core] Add `@mui/material-nextjs` to `MUI Core` renovate group

---

scripts/orderIdValidation.js

fixes the regex test (stupid me did it the wrong wayaround)
Also adds a notice and early return instead of a `setFailed`

[infra] Fix regex in order id validation

---

scripts/orderIdValidation.js

--- 
Another stupid mistake with regex corrected 🤷🏼 🙇🏼

[infra] Fix regex match in order id validation

---

.github/workflows/issue-cleanup.yml
.github/workflows/order-id-validator.yml
scripts/orderIdValidation.js

[infra] Fixes permissions on order id job

---

scripts/orderIdValidation.js

[infra] Fix label name for order ID validation

---

.github/workflows/issue-cleanup.yml
.github/workflows/order-id-validator.yml

[infra] Fixes the workflow_run parameter on the order id workflow

---

.github/workflows/codspeed.yml

[core] Fix GHA syntax for Codspeed action

---

.github/workflows/issue-cleanup.yml
scripts/githubActions/issueBodyCleanup.js

[infra] Fixes output to empty string on `'_No response_'` as order id

---

docs/data/date-pickers/localization/data.json
packages/x-date-pickers/src/locales/nlNL.ts

[l10n] Improve Dutch (nlNL) locale (pickers)

---

docs/data/tree-view/rich-tree-view/editing/CustomLabelInput.js
docs/data/tree-view/rich-tree-view/editing/CustomLabelInput.tsx

Fix https://app.circleci.com/pipelines/github/mui/mui-x/64040/workflows/3ef3e23c-7150-4e42-a788-5e70dbc76a01/jobs/365547

[core] Fix ESLint issue

---

packages/x-date-pickers/src/TimeClock/Clock.tsx
packages/x-date-pickers/src/TimeClock/tests/TimeClock.test.tsx

Closes [#9636](https://github.com/mui/mui-x/issues/9636)

[TimePicker] Handle `Space` and `Enter` on `TimeClock` component

---

packages/x-charts/src/internals/components/AxisSharedComponents.tsx

fixes https://github.com/mui/mui-x/pull/14313#discussion_r1734705995

[charts] Keep axis root classe usage explicit

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/frFR.ts

[l10n] Add missing translation (fr-FR)

---

.github/workflows/codspeed.yml

Fix https://github.com/mui/mui-x/security/code-scanning/37

[core] Reset permissions for codspeed GitHub Action

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/huHU.ts

This PR fixes a few typos of the Hungarian translation of the data grid component, and also provides the missing strings to make the translation complete.

[l10n] Improve Hungarian (hu-HU) locale

---

docs/data/data-grid/editing/FullFeaturedCrudGrid.js
docs/data/data-grid/editing/FullFeaturedCrudGrid.tsx

[DataGrid] Fix bug in CRUD example

---

packages/x-charts/src/ResponsiveChartContainer/useChartContainerDimensions.ts

https://github.com/mui/mui-public/issues/195

[core][charts] Remove dead code

---

packages/x-charts/src/ChartsTooltip/useAxisTooltip.tsx
packages/x-charts/src/ChartsTooltip/useItemTooltip.tsx

Fixes https://app.circleci.com/jobs/github/mui/mui-x/380830

[core] Fix failing CI on master

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/ptPT.ts

[l10n] Add missing Portuguese (pt-PT) translations

---

docs/data/migration/migration-tree-view-v6/migration-tree-view-v6.md

[docs] Fix typo in the Tree View migration guide to v7

---

packages/x-data-grid-pro/src/hooks/features/columnReorder/useGridColumnReorder.tsx

[DataGridPro] Fix dragging styles removal in Column ordering

---

docs/data/data-grid/master-detail/FullWidthDetailPanel.js
docs/data/data-grid/master-detail/FullWidthDetailPanel.tsx
docs/data/data-grid/master-detail/FullWidthDetailPanel.tsx.preview

This PR is created to address https://github.com/mui/mui-x/pull/14854#discussion_r1792398580
Unable to attach labels to the PR, please help with attaching the labels

[docs] Update default column pinning using initialState for "Disable detail panel content scroll" section

---

docs/pages/x/api/tree-view/tree-item.json
packages/x-tree-view/src/TreeItem/TreeItem.test.tsx
packages/x-tree-view/src/TreeItem/TreeItem.tsx
packages/x-tree-view/src/TreeItem/TreeItem.types.ts

[TreeItem] Deprecate the `ContentComponent` and `ContentProps` props

---

package.json

Fixes [Publish the documentation](https://github.com/mui/mui-x/blob/HEAD/scripts/README.md#publish-the-documentation) step

[core] Fix docs deploy command

---

docs/pages/x/api/data-grid/data-grid-premium.json
docs/pages/x/api/data-grid/data-grid-pro.json
docs/pages/x/api/data-grid/data-grid.json
docs/translations/api-docs/data-grid/data-grid-premium/data-grid-premium.json
docs/translations/api-docs/data-grid/data-grid-pro/data-grid-pro.json
docs/translations/api-docs/data-grid/data-grid/data-grid.json
packages/x-data-grid-pro/src/components/GridDataSourceTreeDataGroupingCell.tsx
packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderFilterIconButton.tsx
packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderSortIcon.tsx
packages/x-data-grid/src/components/toolbar/GridToolbar.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarFilterButton.tsx
packages/x-data-grid/src/hooks/features/columnMenu/useGridColumnMenuSlots.ts
packages/x-data-grid/src/joy/joySlots.tsx
packages/x-data-grid/src/material/index.ts
packages/x-data-grid/src/models/gridSlotsComponent.ts
packages/x-data-grid/src/models/gridSlotsComponentsProps.ts
scripts/x-data-grid-premium.exports.json
scripts/x-data-grid-pro.exports.json
scripts/x-data-grid.exports.json

Some work for the design-agnostic OKR, remove some `Box`, and add `rootProps.slots.baseBadge` to replace all `Badge`.

[DataGrid] Refactor: remove some Box & Badge

---

packages/x-data-grid/src/hooks/features/focus/useGridFocus.ts

Cherry-pick of https://github.com/mui/mui-x/pull/15061

[DataGrid] Focus next row when the focused row is deleted

---

packages/x-tree-view/src/TreeItem2DragAndDropOverlay/TreeItem2DragAndDropOverlay.tsx

Cherry-pick https://github.com/mui/mui-x/pull/15042.

[TreeView] Fix drag and drop color usage

---

packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx

Fixes #15086
Before: https://stackblitz.com/edit/react-h9qpvr
After: https://codesandbox.io/p/sandbox/shy-night-85y9zy

[DataGrid] Fix right column group header border

---

packages/x-data-grid/src/hooks/features/focus/useGridFocus.ts

Cherry-pick https://github.com/mui/mui-x/pull/15146

[DataGrid] Prevent error when deleting the last row

---

docs/data/data-grid/row-selection/KeepNonExistentRowsSelected.js
docs/data/data-grid/row-selection/KeepNonExistentRowsSelected.tsx
docs/data/data-grid/row-selection/KeepNonExistentRowsSelected.tsx.preview
docs/data/data-grid/row-selection/row-selection.md

[docs] Add section explaining how to keep the selection while filtering

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/plPL.ts

What was changed:
- ✅ Add missing translations to polish locale.
---

[I10n][DataGrid] Improve Polish (pl-PL) locale

---

packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts

Cherry-pick of #15184 and #15273

[DataGrid] Improve row selection propagation trigger

---

packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx

[DataGrid] Fix `null` reference error in `GridVirtualScrollbar` (#15009)

---

packages/x-data-grid-pro/src/hooks/features/treeData/useGridTreeData.tsx

Cherry-pick https://github.com/mui/mui-x/pull/15271

[DataGridPro] Should toggle row expansion with Enter key in Tree data

---

docs/data/data-grid/column-recipes/ColumnSizingPersistWidthOrder.js
docs/data/data-grid/column-recipes/ColumnSizingPersistWidthOrder.tsx
docs/data/data-grid/column-recipes/ColumnSizingPersistWidthOrder.tsx.preview
docs/data/data-grid/column-recipes/index.md
docs/data/pages.ts
docs/pages/x/react-data-grid/column-recipes.js

[DataGrid] Add a recipe to persist column width and order

---

CHANGELOG.md
changelogOld/CHANGELOG.v4.md
changelogOld/CHANGELOG.v5.md
changelogOld/CHANGELOG.v6.md
docs/data/data-grid/editing/editing.md
docs/data/data-grid/recipes-editing/recipes-editing.md
docs/data/data-grid/row-updates/row-updates.md
docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md

Fix a few to match https://www.notion.so/mui-org/Writing-style-guide-2a957a4168a54d47b14bae026d06a24b?pvs=4#128cbfe7b66080e4ad1fe0c0f359aa9e as I noticed this in https://mui.zendesk.com/agent/tickets/23253/.

[docs] Add () for updateRows method

---

scripts/README.md

Clarifies discussions like https://github.com/mui/mui-x/pull/15209/files#r1824092534

[core] Clarify release version bump strategy

---

docs/data/introduction/support/support.md

[docs/data/introduction/support/support.md](https://deploy-preview-15384--material-ui-x.netlify.app/x/introduction/support/#long-term-support-lts)

[docs] Add v8 to supported releases table

---

test/regressions/index.test.ts

Related to this error that is still happening: https://app.argos-ci.com/mui/mui-x/builds/26434/118865224

[code-infra] Tentative fix for Argos flaky screenshot tests - Take 2

---

docs/data/tree-view/rich-tree-view/selection/selection.md

https://deploy-preview-15390--material-ui-x.netlify.app/x/react-tree-view/rich-tree-view/selection/#automatic-parents-and-children-selection

[docs] Fix small Tree View typo

---

docs/data/tree-view/rich-tree-view/customization/customization.md
docs/data/tree-view/rich-tree-view/editing/editing.md
docs/data/tree-view/rich-tree-view/expansion/expansion.md
docs/data/tree-view/rich-tree-view/focus/focus.md
docs/data/tree-view/rich-tree-view/headless/headless.md
docs/data/tree-view/rich-tree-view/items/items.md
docs/data/tree-view/rich-tree-view/selection/selection.md

[core] Remove duplicate title header

---

CHANGELOG.md
docs/data/migration/migration-charts-v6/migration-charts-v6.md
docs/data/migration/migration-charts-v7/migration-charts-v7.md
docs/data/migration/migration-pickers-v6/migration-pickers-v6.md
docs/data/migration/migration-pickers-v7/migration-pickers-v7.md
docs/data/migration/migration-tree-view-v7/migration-tree-view-v7.md

Follow up on https://github.com/mui/mui-x/pull/15319#discussion_r1842166663.

[docs] Fix some migration typos

---

packages/x-charts/src/ChartsGrid/ChartsHorizontalGrid.tsx
packages/x-charts/src/ChartsGrid/ChartsVerticalGrid.tsx

[charts] Fix key generation for the ChartsGrid

---

.github/workflows/create-cherry-pick-pr.yml

Same as https://github.com/mui/mui-public/pull/245

[infra] Remove cherry-pick issue write permission

---

scripts/README.md

Cherry-pick of https://github.com/mui/mui-x/pull/15219

[core] Clarify release version bump strategy 

---

packages/x-tree-view/src/TreeItem/TreeItem.types.ts

[TreeItem] Correct the typing of `slotProps.groupTransition`

---

packages/x-internals/src/types/DefaultizedProps.ts
packages/x-internals/src/types/MakeOptional.ts
packages/x-internals/src/types/MakeRequired.ts
packages/x-internals/src/types/SlotComponentPropsFromProps.ts
packages/x-internals/src/types/index.ts

Added some documentation to internal types

[code-infra] Add documentation to internal types

---

docs/data/data-grid/master-detail/LazyLoadingDetailPanel.js
docs/data/data-grid/master-detail/LazyLoadingDetailPanel.tsx
docs/data/data-grid/master-detail/LazyLoadingDetailPanel.tsx.preview

Closes https://github.com/mui/mui-x/issues/15413

[docs] Add data caching to lazy loaded detail panel demo

---

docs/data/migration/migration-charts-v7/migration-charts-v7.md
docs/data/migration/migration-data-grid-v5/migration-data-grid-v5.md
docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md
docs/data/migration/migration-pickers-v5/migration-pickers-v5.md
docs/data/migration/migration-pickers-v6/migration-pickers-v6.md
docs/data/migration/migration-pickers-v7/migration-pickers-v7.md
docs/data/migration/migration-tree-view-v6/migration-tree-view-v6.md
docs/data/migration/migration-tree-view-v7/migration-tree-view-v7.md
packages/x-codemod/README.md
packages/x-date-pickers-pro/README.md
packages/x-date-pickers/README.md

It's wrong: https://phoenixnap.com/kb/bash-comment
Before https://next.mui.com/x/migration/migration-pickers-v7/#run-codemods
After https://deploy-preview-15571--material-ui-x.netlify.app/x/migration/migration-pickers-v7/#run-codemods

[docs] Fix bash comments

---

packages/x-tree-view-pro/src/RichTreeViewPro/RichTreeViewPro.types.ts
packages/x-tree-view-pro/src/internals/utils/releaseInfo.ts
packages/x-tree-view/src/RichTreeView/RichTreeView.types.ts
packages/x-tree-view/src/SimpleTreeView/SimpleTreeView.types.ts
packages/x-tree-view/src/TreeItem/TreeItem.types.ts
packages/x-tree-view/src/TreeItemDragAndDropOverlay/TreeItemDragAndDropOverlay.tsx
packages/x-tree-view/src/TreeItemIcon/TreeItemIcon.types.ts
packages/x-tree-view/src/internals/components/RichTreeViewItems.tsx
packages/x-tree-view/src/internals/models/itemPlugin.ts
packages/x-tree-view/src/internals/models/plugin.ts
packages/x-tree-view/src/internals/plugins/useTreeViewFocus/useTreeViewFocus.ts
packages/x-tree-view/src/internals/plugins/useTreeViewIcons/useTreeViewIcons.types.ts
packages/x-tree-view/src/internals/useTreeView/useTreeView.ts
packages/x-tree-view/src/internals/useTreeView/useTreeView.types.ts
packages/x-tree-view/src/useTreeItem/useTreeItem.ts

[tree-view] Flaten import from `@mui/utils` and `@mui/system`

---

docs/data/data-grid/pagination/pagination.md
docs/data/migration/migration-data-grid-v7/migration-data-grid-v7.md
packages/x-data-grid/src/components/GridPagination.tsx
packages/x-data-grid/src/tests/pagination.DataGrid.test.tsx

Extracted from
https://github.com/mui/mui-x/pull/13878
because of
https://github.com/mui/mui-x/pull/13878#discussion_r1860582982

[DataGrid] Make estimation label more accurate

---

packages/x-data-grid-pro/src/components/headerFiltering/GridHeaderFilterCell.tsx
packages/x-data-grid-pro/src/tests/filtering.DataGridPro.test.tsx
packages/x-data-grid/src/tests/filtering.DataGrid.test.tsx

Cherry-pick of #15528 
Forgot the label, so this one is manually created.

[DataGridPro] Fix header filtering with `boolean` column type (@k-rajat19)

---

docs/data/data-grid/list-view/list-view.md

| -------|------|
| <img width="853" src="https://github.com/user-attachments/assets/7880b909-8253-4bf1-81f1-172c24a87a48"> | <img width="853" src="https://github.com/user-attachments/assets/1c401da8-2b97-4aa0-b70d-4c4dfbd1366f"> |

[docs] Remove duplicated warning

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/trTR.ts

[l10n] Improve Turkish (tr-TR) locale #3211

[l10n] Improve Turkish (tr-TR) locale

---

CHANGELOG.md
package.json
packages/x-charts-pro/package.json
packages/x-charts/package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json

1. [x] Add changelog entry
2. [x] Clean changelog entry
3. [x] Update the root `package.json`'s version
4. [x] Update other `package.json`s ´version
5. [x] Open PR with changes and wait for review and green CI.
6. [ ] Announce a merge freeze.
7. [ ] Merge PR.
1. [ ] Checkout the last version of the working branch
2. [ ] Build release packages (`pnpm i && pnpm release:build`
3. [ ] Publish release on npm (`pnpm release:publish`)
4. [ ] Push the newly created tag (`pnpm release:tag`)
1. [ ] Publish the documentation
2. [ ] Publish GitHub release

[release] v7.23.1

---

CHANGELOG.md
package.json
packages/x-charts-pro/package.json
packages/x-charts-vendor/package.json
packages/x-charts/package.json
packages/x-codemod/package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json

1. [x] Add changelog entry
2. [x] Clean changelog entry
3. [x] Update the root `package.json`'s version
4. [x] Update other `package.json`s ´version
5. [x] Open PR with changes and wait for review and green CI.
6. [ ] Announce a merge freeze.
7. [ ] Merge PR.
1. [ ] Checkout the last version of the working branch
2. [ ] Build release packages (`pnpm i && pnpm release:build`
3. [ ] Publish release on npm (`pnpm release:publish`)
4. [ ] Push the newly created tag (`pnpm release:tag`)
1. [ ] Publish the documentation
2. [ ] Publish GitHub release

v8.0.0-alpha.3

---

docs/data/date-pickers/fields/fields.md

Created from: https://github.com/mui/mui-x/pull/15596#pullrequestreview-2481957113
Improve the description based on the merged PR from v8.

[docs] Improve Pickers accessible DOM structure description

---

packages/x-date-pickers-pro/src/internals/hooks/models/useRangePicker.ts
packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.types.ts
packages/x-date-pickers/src/internals/hooks/useMobilePicker/useMobilePicker.types.ts
packages/x-date-pickers/src/internals/hooks/usePicker/usePicker.ts
packages/x-date-pickers/src/internals/hooks/usePicker/usePicker.types.ts
packages/x-date-pickers/src/internals/hooks/usePicker/usePickerProvider.ts
packages/x-date-pickers/src/internals/hooks/usePicker/usePickerViews.ts
packages/x-date-pickers/src/internals/index.ts

Extracted from #15671
Small internal refacto to prepare for #15671

[pickers] Clean `usePicker` logic

---

packages/x-data-grid/src/components/cell/GridActionsCell.tsx

Fixes https://github.com/mui/mui-x/issues/15678

[DataGrid] Toggle menu on click in `GridActionsCell`

---

packages/x-data-grid/src/components/cell/GridActionsCell.tsx

Manual cherry-pick of https://github.com/mui/mui-x/pull/15867

[DataGrid] Toggle menu on click in `GridActionsCell` (@k-rajat19)

---

CHANGELOG.md
package.json
packages/x-charts-pro/package.json
packages/x-charts-vendor/package.json
packages/x-charts/package.json
packages/x-codemod/package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-data-grid/src/components/cell/GridActionsCell.tsx
packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts
packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
packages/x-data-grid/src/tests/layout.DataGrid.test.tsx
packages/x-data-grid/src/tests/rowSpanning.DataGrid.test.tsx
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-license/package.json
packages/x-tree-view-pro/package.json
packages/x-tree-view/package.json
scripts/releaseChangelog.mjs

Feel free to suggest highlights. 🙏

v8.0.0-alpha.4

---

packages/x-data-grid/src/components/columnSelection/GridCellCheckboxRenderer.tsx
packages/x-data-grid/src/components/columnSelection/GridHeaderCheckbox.tsx

Port back aria-label fix from #15522

[DataGrid] Fix `aria-label` value for group checkboxes

---

packages/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx

Update quick filter input variant and fix a few related styles.
https://deploy-preview-15909--material-ui-x.netlify.app/x/react-data-grid/filtering/quick-filter/
Part of #15486

[DataGrid] Update quick filter input variant

---

docs/next-env.d.ts

new changes to the comment in `next-env.d.ts` files 🫠

[code-infra] Add new `next-env.d.ts` changes

---

packages/x-data-grid-pro/src/components/headerFiltering/GridHeaderFilterCell.tsx
packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputValue.tsx

Manual cherry-pick of #15829
Excludes breaking changes

[DataGrid] Fix header filters showing clear button while empty (@k-rajat19)

---

scripts/README.md

Cherry pick #16012
CC @michelengelen Seems like the auto cherry-pick action is having some issues.

[core] Clarify the release strategy

---

packages/x-data-grid/src/components/columnSelection/GridHeaderCheckbox.tsx

Fixes #16008
- Before: https://codesandbox.io/p/sandbox/cocky-keller-gyjwyg
- After: https://codesandbox.io/p/sandbox/dreamy-yalow-pgtlsw

[DataGrid] Fix select all checkbox state reset with server side data

---

packages/x-data-grid-premium/src/tests/statePersistence.DataGridPremium.test.tsx
packages/x-data-grid/src/tests/rowSelection.DataGrid.test.tsx

Replicate changes done in https://github.com/mui/mui-x/pull/16048.
In particular: https://github.com/mui/mui-x/pull/16048/commits/9dbd4af4aa94edeee7c4b40f05bae520fdb513d4, https://github.com/mui/mui-x/pull/16048/commits/f878fb5aa53b9dc643c6a5b8377ed3b658732076.

[test] Stabilize flaky Data Grid tests

---

docs/src/modules/components/overview/DateLibraries.tsx

[docs] Fix non-existing "adapter" property of LocalizationProvider

---

docs/data/date-pickers/localization/data.json
packages/x-date-pickers/src/locales/nbNO.ts

Cherry-pick https://github.com/mui/mui-x/pull/16083.

[l10n] Improve Norwegian (nb-NO) locale (#16083) (@josteinjhauge)

---

docs/data/charts/axis/CustomDomainYAxis.js
docs/data/charts/axis/CustomDomainYAxis.tsx
docs/data/charts/styling/ColorTemplate.js
docs/data/charts/styling/ColorTemplate.tsx
docs/data/charts/styling/MuiColorTemplate.js
docs/data/charts/styling/MuiColorTemplate.tsx

Small fixes for removed props that were still being passed to the DOM

[charts][docs] Fix wrong props warnings

---

packages/x-data-grid/src/components/panel/GridPanelContent.tsx

[DataGrid] Refactor: remove missed theme

---

docs/data/charts/legend/legend.md

[docs] Remove broken links

---

.github/workflows/create-cherry-pick-pr.yml

[infra] Cherry-pick of #16184

---

test/regressions/index.test.ts

Fixes https://app.argos-ci.com/mui/mui-x/builds/29293/130934959

[test] Fix flaky screenshot

---

packages/x-data-grid-pro/src/tests/columns.DataGridPro.test.tsx
packages/x-data-grid/src/utils/domUtils.ts

Fixes https://github.com/mui/mui-x/issues/15755
Before: https://codesandbox.io/p/sandbox/infallible-noyce-lvq87k
After: https://codesandbox.io/p/sandbox/cool-currying-4vqwc8

[DataGridPro] Fix width of right-pinned column group during resize

---

packages/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx

Fixes https://app.circleci.com/pipelines/github/mui/mui-x/78308/workflows/7caa3cbf-0834-4886-807f-85f28d72e047/jobs/445882

[test] Fix flaky column pinning unit test

---

docs/data/data-grid/cell-selection/cell-selection.md
docs/pages/x/api/data-grid/grid-cell-selection-api.json
docs/translations/api-docs/data-grid/grid-api.json
packages/x-data-grid-premium/src/hooks/features/cellSelection/gridCellSelectionInterfaces.ts

Cherry-pick of https://github.com/mui/mui-x/pull/16099

[docs] Copyedit the Data Grid cell selection page (@samuelsycamore)

---

scripts/releaseChangelog.mjs

Addresses https://github.com/mui/mui-x/pull/16216#discussion_r1918931772
If the package has not been changed, but we still release it, there were some internal updates, e.g. changes in `package.json`.

[code-infra] Update changelog script

---

packages/x-license/package.json
pnpm-lock.yaml

[core] Make `@mui/x-internals` a dependency of `@mui/x-license`

---

docs/data/charts/line-demo/TinyLineChart.js
docs/data/charts/line-demo/TinyLineChart.tsx

[docs] Fix tiny line chart breaking change

---

packages/x-charts-pro/src/Heatmap/plugin.ts
packages/x-charts/src/BarChart/plugin.ts
packages/x-charts/src/LineChart/plugin.ts
packages/x-charts/src/PieChart/plugin.ts
packages/x-charts/src/ScatterChart/plugin.ts
packages/x-charts/src/hooks/useLegend.ts
packages/x-charts/src/internals/plugins/models/seriesConfig/seriesConfig.types.ts
pnpm-lock.yaml

@JCQuintas I started back the radar and thaught about what you said about it's hard to get the legend in pro because it's defined in the community package. That PR should solve this pain point

[charts] Move legend getter to series config

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/faIR.ts

[l10n] Improve Persian (fa-IR) locale (@mostafaRoosta74)

---

scripts/README.md

[docs] Improve release documentation

---

packages/x-data-grid/src/hooks/features/overlays/useGridOverlays.tsx

[DataGrid] Fix loading overlay not in sync with scroll

---

.circleci/config.yml

Manual cherry-pick of https://github.com/mui/mui-x/pull/16434

[core] Fix corepack and pnpm installation in CircleCI (@flaviendelangle)

---

packages/x-date-pickers-pro/src/MultiInputDateRangeField/MultiInputDateRangeField.tsx
packages/x-date-pickers-pro/src/MultiInputDateTimeRangeField/MultiInputDateTimeRangeField.tsx
packages/x-date-pickers-pro/src/MultiInputTimeRangeField/MultiInputTimeRangeField.tsx
packages/x-date-pickers/src/PickersTextField/PickersInputBase/PickersInputBase.tsx

Closes https://github.com/mui/mui-x/issues/15847

[DateRangePicker] Fix vertical alignment for multi input fields

---

CHANGELOG.md
packages/x-charts-pro/package.json
packages/x-charts/package.json
packages/x-codemod/package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-internals/package.json
packages/x-license/package.json
packages/x-tree-view-pro/package.json
packages/x-tree-view/package.json

v8.0.0-alpha.11

---

docs/data/data-grid/export/ExcelExportWithWebWorker.js
docs/data/data-grid/export/ExcelExportWithWebWorker.tsx
docs/data/data-grid/export/excelExportWorker.js
docs/data/data-grid/export/excelExportWorker.ts
docs/data/data-grid/export/export.md
docs/worker.ts
packages/x-data-grid-premium/src/hooks/features/export/index.ts
packages/x-data-grid-premium/src/hooks/features/export/serializer/excelSerializer.ts
packages/x-data-grid-premium/src/hooks/features/export/serializer/setupExcelExportWebWorker.ts
packages/x-data-grid-premium/src/hooks/features/export/serializer/utils.ts
packages/x-data-grid-premium/src/setupExcelExportWebWorker.ts

Cherry-pick of https://github.com/mui/mui-x/pull/16517

[DataGridPremium] Fix Excel export Web Worker demo not working in dev mode

---

packages/x-data-grid/src/material/index.tsx

Follow-up of https://github.com/mui/mui-x/pull/16394/files#r1951697262

[DataGrid] Fix: base Select onClose

---

packages/x-charts-pro/src/ChartContainerPro/ChartContainerPro.tsx
packages/x-charts-pro/src/ChartContainerPro/index.ts
packages/x-charts-pro/src/ChartDataProviderPro/index.ts
packages/x-charts-pro/src/Heatmap/index.ts
packages/x-charts-pro/src/index.ts

Same as https://github.com/mui/mui-x/pull/16579 but for v8
Fix #16573

[charts] Fix type overloads

---

packages/x-charts/src/context/AnimationProvider/useSkipAnimation.test.tsx
packages/x-charts/src/context/AnimationProvider/useSkipAnimation.ts
packages/x-charts/src/hooks/useSvgRef.ts
packages/x-charts/src/internals/store/useStore.ts

[charts] Fix typo in error message

---

packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/defaultizeAxis.ts

[charts] Make `defaultizeAxis` function type-safe

---

docs/data/data-grid/localization/data.json
docs/data/date-pickers/localization/data.json
packages/x-data-grid/src/locales/bnBD.ts
packages/x-data-grid/src/locales/index.ts
packages/x-date-pickers/src/locales/bnBD.ts
packages/x-date-pickers/src/locales/index.ts

[l10n] Added Bangla (bn-BD) locale

---

packages/x-data-grid/src/material/index.tsx

Performance improvement. See [comment](https://mui-org.slack.com/archives/C011VC970AW/p1739989866302639).

[DataGrid] Replace `sx` prop usage with `styled()` components

---

docs/data/data-grid/server-side-data/index.md
docs/data/pages.ts

Improve the navigation links as per `master`

[DataGrid] Make server-side data navigation consistent

---

scripts/releaseChangelog.mjs

Rephrased the acknowledgment message to better recognize community members' valuable contributions. This ensures a more inclusive and encouraging tone in the release changelog.

[infra] Update contributor acknowledgment wording

---

.eslintrc.js
packages/x-license/src/useLicenseVerifier/useLicenseVerifier.test.tsx
packages/x-license/src/verifyLicense/verifyLicense.test.ts
test/regressions/index.test.ts
test/utils/addChaiAssertions.ts
test/utils/checkMaterialVersion.ts
test/utils/skipIf.ts

These are improvements made during the [`vitest` PR ](https://github.com/mui/mui-x/pull/14508)
I'm moving the changes out so that PR is leaner.
There are no specially notable changes for these packages.

[code-infra] General packages changes for `vitest`

---

packages/x-charts/src/ChartDataProvider/ChartDataProvider.tsx

[charts] Fix composition docs link

---

packages/x-charts/src/ChartsTooltip/ChartsTooltipTable.ts

[charts] Fix missing  error in the tooltip

---

docs/data/tree-view/rich-tree-view/items/GetParentIdPublicAPI.js
docs/data/tree-view/rich-tree-view/items/GetParentIdPublicAPI.tsx
docs/data/tree-view/rich-tree-view/items/GetParentIdPublicAPI.tsx.preview
docs/data/tree-view/rich-tree-view/items/items.md

The method was added in https://github.com/mui/mui-x/pull/15308 but I forgot to document it 🙈

[TreeView] Document `getParentId` API method

---

packages/x-date-pickers/src/models/adapters.ts

[pickers] Fix typo in JSDoc

---

test/regressions/index.test.ts

Try addressing: https://github.com/mui/mui-x/pull/16847#issuecomment-2704332602
https://app.argos-ci.com/mui/mui-x/builds/32008/142829940

[test] Add timeout to flaky screenshot tests

---

docs/data/charts/legend/LegendCustomLabelMark.js
docs/data/charts/legend/LegendCustomLabelMark.tsx
docs/data/charts/pie-demo/PieChartWithCustomLegendAndTooltip.js
docs/data/charts/pie-demo/PieChartWithCustomLegendAndTooltip.tsx

Avoid spreading props in demos not to incentivize that behavior.

[charts] Avoid spreading props in demos

---

docs/data/charts/sparkline/ColorCustomization.js
docs/data/charts/sparkline/ColorCustomization.tsx
docs/data/charts/sparkline/ColorCustomizationMode.js
docs/data/charts/sparkline/ColorCustomizationMode.tsx
docs/data/charts/sparkline/ColorCustomizationMode.tsx.preview

[docs] Improve sparkline demo

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/zhCN.ts
packages/x-data-grid/src/locales/zhHK.ts
packages/x-data-grid/src/locales/zhTW.ts

[l10n] Improve Chinese (zh-CN), (zh-HK) and (zh-TW) locales

---

docs/data/date-pickers/base-concepts/ComponentExplorerNoSnap.js
docs/data/date-pickers/base-concepts/ComponentExplorerNoSnap.tsx
docs/data/date-pickers/validation/DateValidationDisableFuture.js
docs/data/date-pickers/validation/DateValidationDisableFuture.tsx
docs/data/date-pickers/validation/DateValidationDisablePast.js
docs/data/date-pickers/validation/DateValidationDisablePast.tsx
docs/data/date-pickers/validation/TimeValidationMaxTime.js
docs/data/date-pickers/validation/TimeValidationMaxTime.tsx
docs/data/date-pickers/validation/TimeValidationMaxTime.tsx.preview
docs/data/date-pickers/validation/TimeValidationMinTime.js
docs/data/date-pickers/validation/TimeValidationMinTime.tsx
docs/data/date-pickers/validation/TimeValidationMinTime.tsx.preview
docs/data/date-pickers/validation/TimeValidationShouldDisableTime.js
docs/data/date-pickers/validation/TimeValidationShouldDisableTime.tsx
docs/data/date-pickers/validation/validation.md
docs/pages/x/api/date-pickers/desktop-time-range-picker.json
docs/pages/x/api/date-pickers/index.md
docs/pages/x/api/date-pickers/mobile-time-range-picker.json
docs/pages/x/api/date-pickers/time-range-picker.json
scripts/releaseChangelog.mjs

Follow up on https://github.com/mui/mui-x/pull/9431.

[docs] Add `TimeRangePicker` to relevant validation demos

---

docs/pages/x/api/date-pickers/desktop-time-range-picker.json
docs/pages/x/api/date-pickers/mobile-time-range-picker.json
docs/pages/x/api/date-pickers/time-range-picker.json
docs/translations/api-docs/date-pickers/desktop-time-range-picker/desktop-time-range-picker.json
docs/translations/api-docs/date-pickers/mobile-time-range-picker/mobile-time-range-picker.json
docs/translations/api-docs/date-pickers/time-range-picker/time-range-picker.json
packages/x-date-pickers-pro/src/DesktopTimeRangePicker/DesktopTimeRangePicker.tsx
packages/x-date-pickers-pro/src/MobileTimeRangePicker/MobileTimeRangePicker.tsx
packages/x-date-pickers-pro/src/TimeRangePicker/TimeRangePicker.tsx

Fix https://app.circleci.com/pipelines/github/mui/mui-x/84567/workflows/e0a8d1ef-565d-4680-9fb6-4c3e969c5438/jobs/482818.

[core] Fix proptypes and API docs after merge

---

packages/x-data-grid/src/components/cell/GridCell.tsx
packages/x-data-grid/src/components/containers/GridRootStyles.ts
packages/x-data-grid/src/components/virtualization/GridBottomContainer.tsx
packages/x-data-grid/src/components/virtualization/GridTopContainer.tsx
packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx

[DataGrid] Fix visual issue with pinned columns and row spanning

---

.circleci/config.yml

[infra] Make tests on React 18 part of pipeline

---

docs/pages/x/api/charts/charts-grid.json
packages/x-charts/src/ChartsGrid/ChartsGrid.test.tsx
packages/x-charts/src/ChartsGrid/ChartsHorizontalGrid.tsx
packages/x-charts/src/ChartsGrid/ChartsVerticalGrid.tsx

[charts] Grid support time step bellow 1s

---

renovate.json

Create a group to allow combining bumps like these:
- https://github.com/mui/mui-x/pull/16984
- https://github.com/mui/mui-x/pull/16985

[code-infra] Create `Tanstack query` renovate group

---

packages/x-data-grid/src/constants/cssVariables.ts

CSS variable namespaces should be singular rather than plural

[DataGrid] Update CSS variable naming convention to singular

---

docs/data/data-grid/master-detail/CustomizeDetailPanelToggle.js
docs/data/data-grid/master-detail/CustomizeDetailPanelToggle.tsx

fix https://github.com/mui/mui-x/issues/16822

[docs] Fix custom detail panel toggle state update

---

docs/data/data-grid/list-view/ListViewAdvanced.js
docs/data/data-grid/list-view/ListViewAdvanced.tsx
docs/data/data-grid/list-view/components/Drawer.js
docs/data/data-grid/list-view/components/Drawer.tsx
docs/data/data-grid/list-view/components/RenameDialog.tsx

[docs] Fix Data Grid advanced list view demo

---

test/regressions/index.test.ts

[code-infra] Add more tests to slow screenshot tests

---

.circleci/config.yml

Address https://github.com/mui/mui-x/pull/16933#issuecomment-2746352490.

[code-infra] Remove `test_regressions` step from React 18 pipeline

---

docs/data/migration/migration-data-grid-v7/migration-data-grid-v7.md
packages/x-codemod/README.md
packages/x-codemod/src/v8.0.0/data-grid/preset-safe/actual.spec.tsx
packages/x-codemod/src/v8.0.0/data-grid/preset-safe/expected.spec.tsx
packages/x-codemod/src/v8.0.0/data-grid/preset-safe/index.ts
packages/x-codemod/src/v8.0.0/data-grid/reform-row-selection-model/actual.spec.js
packages/x-codemod/src/v8.0.0/data-grid/reform-row-selection-model/expected.spec.js
packages/x-codemod/src/v8.0.0/data-grid/reform-row-selection-model/index.ts
packages/x-codemod/src/v8.0.0/data-grid/reform-row-selection-model/reform-row-selection-model.test.ts
packages/x-codemod/src/v8.0.0/data-grid/reform-row-selection-model/ts-actual.spec.tsx
packages/x-codemod/src/v8.0.0/data-grid/reform-row-selection-model/ts-expected.spec.tsx
packages/x-codemod/src/v8.0.0/data-grid/remove-props/actual.spec.js
packages/x-codemod/src/v8.0.0/data-grid/remove-props/index.ts
packages/x-codemod/src/v8.0.0/data-grid/remove-props/ts-actual.spec.tsx
packages/x-codemod/src/v8.0.0/data-grid/rename-imports/actual.spec.js
packages/x-codemod/src/v8.0.0/data-grid/rename-imports/expected.spec.js
packages/x-codemod/src/v8.0.0/data-grid/rename-imports/index.ts
packages/x-codemod/src/v8.0.0/data-grid/rename-imports/rename-imports.test.ts
packages/x-codemod/src/v8.0.0/data-grid/rename-imports/ts-actual.spec.tsx
packages/x-codemod/src/v8.0.0/data-grid/rename-imports/ts-expected.spec.tsx
packages/x-codemod/src/v8.0.0/data-grid/rename-package/actual.spec.js
packages/x-codemod/src/v8.0.0/data-grid/rename-package/expected.spec.js
packages/x-codemod/src/v8.0.0/data-grid/rename-package/index.ts
packages/x-codemod/src/v8.0.0/data-grid/rename-package/rename-package.ts
packages/x-codemod/src/v8.0.0/data-grid/rename-props/actual.spec.js
packages/x-codemod/src/v8.0.0/data-grid/rename-props/expected.spec.js
packages/x-codemod/src/v8.0.0/data-grid/rename-props/index.ts
packages/x-codemod/src/v8.0.0/data-grid/rename-props/ts-actual.spec.tsx
packages/x-codemod/src/v8.0.0/data-grid/rename-props/ts-expected.spec.tsx

[codemod] Add a few Data Grid codemods

---

packages/x-data-grid-premium/src/components/GridDataSourceGroupingCriteriaCell.tsx
packages/x-data-grid-pro/src/components/GridDataSourceTreeDataGroupingCell.tsx

Fixes #17141
- After: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-938qmx

[DataGridPro] Data source: Allow expanding groups with unknown children

---

packages/x-data-grid/src/components/GridShadowScrollArea.tsx

Fixes #17142 
| --- | --- |
| <img width="900" alt="Screenshot 2025-03-27 at 08 40 41" src="https://github.com/user-attachments/assets/e7e76d6d-b878-470e-859a-99ad8aede805" /> | <img width="930" alt="Screenshot 2025-03-27 at 09 50 13" src="https://github.com/user-attachments/assets/5e6b1b91-e554-4330-9042-ceef8d36337e" /> |

[DataGrid] Fix crash when used with `@mui/styled-engine-sc`

---

packages/x-charts-pro/src/Heatmap/Heatmap.tsx
packages/x-charts/src/BarChart/useBarChartProps.ts
packages/x-charts/src/LineChart/useLineChartProps.ts
packages/x-charts/src/ScatterChart/useScatterChartProps.ts

While looking at #17137 I noticed the useEffect was frequently called for `series` update in `LineChart` and `BarChart`

[charts] Memoize axes and series with default

---

test/utils/pickers/describeRangeValidation/testDayViewRangeValidation.tsx

Fixes https://app.circleci.com/pipelines/github/mui/mui-x/86774/workflows/de290bfd-a743-4db5-bcf5-b4b2d90c0f98/jobs/498972

[code-infra] Fix pickers failing test after clock=fake removal

---

docs/pages/x/api/date-pickers/localization-provider.json
docs/src/modules/components/InstallationGrid.js
packages/x-date-pickers/src/LocalizationProvider/LocalizationProvider.tsx

[docs] Fix redirection getting-started

---

docs/data/migration/migration-data-grid-v7/migration-data-grid-v7.md
packages/x-codemod/README.md
packages/x-codemod/src/v8.0.0/data-grid/rename-props/actual.spec.js
packages/x-codemod/src/v8.0.0/data-grid/rename-props/expected.spec.js
packages/x-codemod/src/v8.0.0/data-grid/rename-props/index.ts
packages/x-codemod/src/v8.0.0/data-grid/rename-props/ts-actual.spec.tsx
packages/x-codemod/src/v8.0.0/data-grid/rename-props/ts-expected.spec.tsx

Codemod for change done in #17217 
Closes #15860

[codemod] Add `listView` prop rename codemod

---

docs/data/charts/legend/CustomLegend.js
docs/data/charts/legend/CustomLegend.tsx
docs/data/charts/legend/legend.md
packages/x-charts/src/ChartsLabel/index.ts
scripts/x-charts-pro.exports.json
scripts/x-charts.exports.json

Improvements based on suggestions/findings on https://github.com/mui/mui-x/issues/17219

[charts] Improve custom legend docs

---

packages/x-charts-pro/src/BarChartPro/BarChartPro.zoom.test.tsx
packages/x-charts-pro/src/LineChartPro/LineChartPro.zoom.test.tsx
packages/x-charts-pro/src/ScatterChartPro/ScatterChartPro.zoom.test.tsx
packages/x-charts-pro/src/hooks/useHeatmapSeries.test.tsx
packages/x-charts/src/BarChart/BarChart.test.tsx
packages/x-charts/src/hooks/useIsHydrated.ts

[code-infra] Charts `vitest` changes

---

docs/data/data-grid/row-spanning/row-spanning.md

A continuation of #15742, it's stable now.
Before: https://deploy-preview-17277--material-ui-x.netlify.app/x/react-data-grid/row-spanning/
After: https://deploy-preview-17278--material-ui-x.netlify.app/x/react-data-grid/row-spanning/

[data grid][docs] Fix row spanning lab icon

---

docs/data/charts/radar/radar.md
docs/data/charts/scatter/scatter.md
docs/data/charts/sparkline/sparkline.md

A few I noticed while browsing the docs.
https://www.notion.so/mui-org/Writing-style-guide-2a957a4168a54d47b14bae026d06a24b

[charts][docs] Fix header Sentence case consistency

---

docs/data/charts/funnel/funnel.md
docs/data/charts/radar/radar.md
docs/pages/x/api/charts/funnel-chart.json
docs/pages/x/api/charts/funnel-plot.json
docs/pages/x/api/charts/radar-axis-highlight.json
docs/pages/x/api/charts/radar-chart.json
docs/pages/x/api/charts/radar-data-provider.json
docs/pages/x/api/charts/radar-grid.json
docs/pages/x/api/charts/radar-metric-labels.json
docs/pages/x/api/charts/radar-series-area.json
docs/pages/x/api/charts/radar-series-marks.json
docs/pages/x/api/charts/radar-series-plot.json

For clarity
Preview: https://deploy-preview-17279--material-ui-x.netlify.app/x/react-charts/funnel/

[charts][docs] Flag experimental API

---

docs/data/data-grid/export/export.md

The issue was flagged in https://mui.zendesk.com/agent/tickets/26858
> PDF Download – We did not find any code sample for the PDF download, although **the documentation says** Excel, PDF and CSV downloads are supported.
so let's fix the root.
---
For the actual support, it's a feature request, pending in https://github.com/mui/mui-x/issues/12696

[data grid][docs] Fix incorrect mention of PDF export

---

packages/x-data-grid-pro/src/tests/dataSourceLazyLoader.DataGridPro.test.tsx

[code-infra] Tentative fix for datagrid flaky test

---

packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
packages/x-data-grid-premium/src/hooks/features/aggregation/gridAggregationSelectors.ts
packages/x-data-grid-premium/src/hooks/features/aggregation/index.ts
packages/x-data-grid-premium/src/hooks/features/aggregation/wrapColumnWithAggregation.tsx
packages/x-data-grid-premium/src/tests/aggregation.DataGridPremium.test.tsx
packages/x-data-grid-pro/src/DataGridPro/DataGridPro.tsx
packages/x-data-grid/src/DataGrid/DataGrid.tsx
packages/x-data-grid/src/components/cell/GridCell.tsx
packages/x-data-grid/src/internals/index.ts
packages/x-data-grid/src/models/configuration/gridConfiguration.ts

Fixes https://github.com/mui/mui-x/issues/16823
This bug is easy to reproduce in pivoting: https://github.com/mui/mui-x/pull/9877#discussion_r2029327652

[DataGridPremium] Fix stale aggregation results after filtering

---

docs/pages/x/api/data-grid/grid-toolbar-quick-filter.json
docs/translations/api-docs/data-grid/grid-toolbar-quick-filter/grid-toolbar-quick-filter.json
packages/x-data-grid/src/components/containers/GridToolbarContainer.tsx
packages/x-data-grid/src/components/toolbar/GridToolbar.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarColumnsButton.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarDensitySelector.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarExport.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarFilterButton.tsx
packages/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx

[DataGrid] Deprecate old toolbar components

---

packages/x-charts/src/Gauge/Gauge.tsx
packages/x-charts/src/Gauge/GaugeValueArc.tsx
packages/x-charts/src/hooks/animation/useAnimateGaugeValueArc.ts

Depends on
- https://github.com/mui/mui-x/pull/17299
Animate gauge chart. 
https://github.com/user-attachments/assets/f7e71564-66e7-45f0-9584-150de07f9017
- 🎁 Animate gauge chart

[charts] Animate gauge chart

---

packages/x-data-grid-premium/src/tests/dataSourceAggregation.DataGridPremium.test.tsx

_Hopefully_ fix [the flaky data source aggregation test](https://app.circleci.com/pipelines/github/mui/mui-x/88095/workflows/b4d46c18-40eb-4264-b738-29cec067a26e/jobs/508180). I can't reproduce it locally, so this is a shot in the dark.

[test] Fix flaky data source aggregation test

---

packages/x-telemetry/src/context.ts

I'm trying to make sense of what each value is about.

[core] Document TelemetryContextType

---

package.json

Prepare script for https://github.com/mui/material-ui/pull/45883

[code-infra] Prepare argos script call for required arg

---

packages/x-charts/src/internals/animation/useAnimate.test.tsx

Fix `useAnimate` test flakiness.

[charts] Fix useAnimate test flakiness

---

docs/data/migration/migration-charts-v7/migration-charts-v7.md

Fixes https://github.com/mui/mui-x/issues/17365.
Let me know if it makes sense to add a codemod.

[charts] Add `slotProps.legend.hidden` to migration docs

---

packages/x-data-grid-premium/src/hooks/features/aggregation/wrapColumnWithAggregation.tsx
packages/x-data-grid-premium/src/tests/aggregation.DataGridPremium.test.tsx

Cherry-pick of https://github.com/mui/mui-x/pull/17326

[DataGridPremium] Fix aggregated values sorting

---

packages/x-date-pickers/src/locales/csCZ.ts

Manual cherry pick of https://github.com/mui/mui-x/pull/17205 since GH action triggering seems to fail. 🙈 .

[l10n] Improve Czech (cs-CZ) locale (#17205) @lubka272

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/plPL.ts

Manual cherry-pick of https://github.com/mui/mui-x/pull/17336 since GH action triggering failed.

[l10n] Improve Polish (pl-PL) locale (#17336)

---

packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx

Fixes https://github.com/mui/mui-x/issues/17357

[DataGridPro] Fix row virtualization not working in list view

---

docs/src/modules/components/WhatsNewLayout.js

https://deploy-preview-17397--material-ui-x.netlify.app/x/whats-new/

[docs] Add whats-new section for MUI X v8

---

docs/data/introduction/support/support.md

[/x/introduction/support/#supported-versions](https://deploy-preview-17287--material-ui-x.netlify.app/x/introduction/support/#supported-versions)

[core] Update supported versions table

---

docs/translations/api-docs/date-pickers/date-field/date-field.json
docs/translations/api-docs/date-pickers/date-time-field/date-time-field.json
docs/translations/api-docs/date-pickers/single-input-date-range-field/single-input-date-range-field.json
docs/translations/api-docs/date-pickers/single-input-date-time-range-field/single-input-date-time-range-field.json
docs/translations/api-docs/date-pickers/single-input-time-range-field/single-input-time-range-field.json
docs/translations/api-docs/date-pickers/time-field/time-field.json
packages/x-date-pickers-pro/src/SingleInputDateRangeField/SingleInputDateRangeField.tsx
packages/x-date-pickers-pro/src/SingleInputDateTimeRangeField/SingleInputDateTimeRangeField.tsx
packages/x-date-pickers-pro/src/SingleInputTimeRangeField/SingleInputTimeRangeField.tsx
packages/x-date-pickers/src/DateField/DateField.tsx
packages/x-date-pickers/src/DateTimeField/DateTimeField.tsx
packages/x-date-pickers/src/TimeField/TimeField.tsx

`pnpm proptypes` & `pnpm docs:api` fail on master.

[pickers] Fix failing proptypes CI

---

docs/data/introduction/support/support.md

https://deploy-preview-17425--material-ui-x.netlify.app/x/introduction/support/#supported-versions

[core] Update support table 

---

.eslintignore
docs/data/migration/migration-charts-v7/migration-charts-v7.md
packages/x-codemod/src/v8.0.0/charts/preset-safe/actual.spec.tsx
packages/x-codemod/src/v8.0.0/charts/preset-safe/expected.spec.tsx
packages/x-codemod/src/v8.0.0/charts/preset-safe/index.ts
packages/x-codemod/src/v8.0.0/charts/replace-legend-hidden-slot-prop/actual.spec.tsx
packages/x-codemod/src/v8.0.0/charts/replace-legend-hidden-slot-prop/expected.spec.tsx
packages/x-codemod/src/v8.0.0/charts/replace-legend-hidden-slot-prop/index.ts
packages/x-codemod/src/v8.0.0/charts/replace-legend-hidden-slot-prop/replace-legend-hidden-slot-prop.test.ts

Follow-up to https://github.com/mui/mui-x/pull/17379.
Fixes https://github.com/mui/mui-x/issues/17365.

[charts] Add codemod for replacing legend's hidden slot prop

---

package.json
pnpm-lock.yaml

Follow-up on https://github.com/mui/mui-x/pull/17414.

[code-infra] Ditch `@babel/node`

---

docs/data/data-grid/row-recipes/DetailPanelOneExpandedRow.js
docs/data/data-grid/row-recipes/DetailPanelOneExpandedRow.tsx

Noticed while answering on https://github.com/mui/mui-x/issues/17449
More context https://github.com/mui/mui-x/issues/17449#issuecomment-2817779171

[docs] Fix DataGrid's master-detail demo for one expanded detail panel at a time

---

packages/x-charts-pro/src/internals/plugins/useChartProZoom/useChartProZoom.ts

Wrap the event handlers in `rafThrottle` instead of the `setZoomDataCallback`. 
Wrapping `setZoomDataCallback` in a `rafThrottle` has several problems:
1. It doesn't distinguish the caller, so if I do `apiRef.setZoomData({ start: 0, end: 10 })` and a wheel event handler calls `setZoomData({ start: 90, end: 100 })` within the same animation frame then only the last one will be applied. In reality, the last one should have been something like `apiRef.setZoomData({ start: 0.01, end: 10.01 })` because it should have used the previous state from the `apiRef` call;
2. This is also problematic when relying on the previous state, e.g., when calculating using deltas. For example, in the zoom brush I store the last `clientX` and use it to calculate the `deltaX` which is then converted into a …

[charts] rafThrottle event handlers instead of setter

---

docs/data/charts/radar/radar.md
docs/src/modules/components/ChartComponentsGrid.js

Preview: https://deploy-preview-17418--material-ui-x.netlify.app/x/react-charts/radar/

[charts] Move radar from under development to preview

---

docs/src/modules/components/overview/tree-view/TreeViewCommunityOrPro.tsx
docs/src/modules/components/overview/tree-view/TreeViewFeaturesHighlight.tsx

Fixes a few small typos in the Overview page, noticed in #17495

[tree view][docs] Copyedit the Tree View Overview page

---

package.json

[core] Fix root package 7.29.1

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/hyAM.ts

[l10n] Add Armenian (hy-AM) locale

---

packages/x-data-grid-pro/src/tests/events.DataGridPro.test.tsx
packages/x-data-grid/src/hooks/features/rows/useGridParamsApi.ts

closes https://github.com/mui/mui-x/issues/16866

[DataGrid] Fix apiRef not being passed on onCellClick params

---

docs/data/migration/migration-charts-v7/migration-charts-v7.md
docs/data/migration/migration-data-grid-v7/migration-data-grid-v7.md
docs/data/migration/migration-pickers-v7/migration-pickers-v7.md
docs/data/migration/migration-tree-view-v7/migration-tree-view-v7.md

Some issues I could spot on the migration pages: https://mui.com/x/migration/migration-data-grid-v7/
Preview: https://deploy-preview-17450--material-ui-x.netlify.app/x/migration/migration-data-grid-v7/

[docs] Fix migration guide format

---

docs/src/modules/components/ChartsInstallationInstructions.js
docs/src/modules/components/DataGridInstallationInstructions.js
docs/src/modules/components/PickersInstallationInstructions.js
docs/src/modules/components/TreeViewInstallationInstructions.js
packages/x-codemod/README.md

Noticed this when checking https://github.com/mui/mui-x/pull/17537.

[docs] Remove leftover `@next` usages

---

docs/data/data-grid/export/export.md

https://mui-org.slack.com/archives/C0757R0KW67/p1745577196732649
https://mui-org.slack.com/archives/C0757R0KW67/p1745577281832759

[docs] Improve data grid export docs

---

packages/x-charts/src/ChartsLabel/ChartsLabelMark.tsx

[charts] Use `<circle />` for circular legend mark

---

docs/package.json
packages/eslint-plugin-material-ui/package.json
test/package.json
test/performance-charts/package.json

Push #17582 even further. Those versions feel confusing, they are all outdated. Less is more.

[core] Remove unecessary versions

---

docs/translations/api-docs/charts/axis-config.json
packages/x-charts/src/models/axis.ts

Document axis ID uniqueness constraints.

[charts] Document axis ID uniqueness constraints

---

docs/data/charts/funnel/FunnelColor.js
docs/data/charts/funnel/FunnelColor.tsx.preview
docs/data/charts/funnel/FunnelCurves.js
docs/data/charts/funnel/FunnelCurves.tsx
docs/data/charts/funnel/FunnelGap.js
docs/data/charts/funnel/FunnelGap.tsx
docs/data/charts/funnel/FunnelGap.tsx.preview
docs/data/charts/funnel/FunnelStacked.js
docs/data/charts/funnel/FunnelStacked.tsx
docs/data/charts/funnel/FunnelStacked.tsx.preview
docs/data/charts/funnel/funnel.md
docs/pages/x/api/charts/funnel-chart.json
docs/pages/x/api/charts/funnel-plot.json
docs/translations/api-docs/charts/funnel-chart/funnel-chart.json
docs/translations/api-docs/charts/funnel-plot/funnel-plot.json
packages/x-charts-pro/src/FunnelChart/FunnelChart.tsx
packages/x-charts-pro/src/FunnelChart/FunnelPlot.tsx
packages/x-charts-pro/src/FunnelChart/curves/bump.ts
packages/x-charts-pro/src/FunnelChart/curves/curve.types.ts
packages/x-charts-pro/src/FunnelChart/curves/funnelStep.ts
packages/x-charts-pro/src/FunnelChart/curves/getFunnelCurve.ts
packages/x-charts-pro/src/FunnelChart/curves/index.ts
packages/x-charts-pro/src/FunnelChart/curves/linear.ts
packages/x-charts-pro/src/FunnelChart/funnel.types.ts
packages/x-charts-pro/src/FunnelChart/funnelBumpCurve.ts
packages/x-charts-pro/src/FunnelChart/funnelLinearCurve.ts
packages/x-charts-pro/src/FunnelChart/index.ts
packages/x-charts-pro/src/FunnelChart/useFunnelChartProps.ts

[charts-pro] Add `gap` option to `FunnelChart`

---

package.json
pnpm-lock.yaml

Supersedes and closes https://github.com/mui/mui-x/pull/17640.

Bump vite to ^6.3.4

---

docs/pages/x/api/charts/mark-element.json
docs/translations/api-docs/charts/mark-element/mark-element.json
packages/x-charts/src/LineChart/CircleMarkElement.tsx
packages/x-charts/src/LineChart/MarkElement.tsx
packages/x-charts/src/LineChart/MarkPlot.tsx

Part of https://github.com/mui/mui-x/issues/12960.
Cherry-picked from https://github.com/mui/mui-x/pull/17534.

[charts] Improve MarkElement perf

---

packages/x-charts-pro/src/ChartsToolbarPro/internal/ChartsToolbarZoomInButton.tsx
packages/x-charts-pro/src/ChartsToolbarPro/internal/ChartsToolbarZoomOutButton.tsx
packages/x-charts-pro/src/internals/material/index.ts
packages/x-charts/src/Toolbar/ToolbarButton.tsx
packages/x-charts/src/internals/material/index.ts

Related to [this comment](https://github.com/mui/mui-x/pull/17615#discussion_r2073766645).

[charts] Rename materialSlots internal constant

---

packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
packages/x-date-pickers/src/DesktopDateTimePicker/tests/DesktopDateTimePicker.test.tsx
packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClock.tsx
packages/x-date-pickers/src/internals/hooks/usePicker/usePicker.types.ts

Fixes https://github.com/mui/mui-x/issues/17506.

[DateTimePicker] Fix focus behavior on desktop variant

---

packages/x-data-grid/src/utils/css/context.tsx

Closes #17556
Use the `nonce` root prop.

[DataGrid] Fix: use CSS nonce

---

docs/data/charts/funnel/funnel.md
docs/data/charts/radar/radar.md
docs/data/charts/toolbar/toolbar.md
docs/data/charts/zoom-and-pan/zoom-and-pan.md
docs/data/pages.ts

Make preview messaging consistent across chart docs. 
Preview: https://deploy-preview-17744--material-ui-x.netlify.app/x/react-charts/radar/

[docs] Make preview messaging consistent in charts

---

CHANGELOG.md
package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json

The following steps must be proposed as a pull request.

[release] v7.29.3

---

package.json
pnpm-lock.yaml

See https://github.com/mui/mui-x/pull/17720#issuecomment-2866049210
Closes https://github.com/mui/mui-x/pull/17720.
Fixes https://github.com/mui/mui-x/issues/17587.

[code-infra] Fix dynamic import missing extensions

---

packages/x-data-grid/src/index.ts

Before: https://stackblitz.com/edit/ckimgzu9-4hje7e15?file=src%2FDemo.tsx
After: https://stackblitz.com/edit/ckimgzu9?file=src%2FDemo.tsx

[DataGrid] Fix material augmentation not working

---

packages/x-charts-pro/src/index.ts

Fixes https://github.com/mui/mui-x/issues/17772.
[Issue reproduction](https://stackblitz.com/edit/vitejs-vite-ahbkkf21?file=src%2FApp.tsx)
[Fixed StackBlitz](https://stackblitz.com/edit/vitejs-vite-tydrq11g?file=src%2FApp.tsx)

[charts-pro] Fix ESM build issue with vite

---

packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx

Fixes issue described in https://github.com/mui/mui-x/pull/17759#discussion_r2081595047

[DataGrid] Fix `renderContext` calculation loop

---

CHANGELOG.md
package.json
packages/x-charts-pro/package.json
packages/x-charts-vendor/package.json
packages/x-charts/package.json
packages/x-codemod/package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-internals/package.json
packages/x-license/package.json
packages/x-telemetry/package.json
packages/x-tree-view-pro/package.json
packages/x-tree-view/package.json
scripts/releaseChangelog.mjs

I've updated the release script because I noticed the Korean l10n PR was missing

 [release] v8.3.1

---

CONTRIBUTING.md
test/README.md

[code-infra] Document how to use `vitest` cli

---

docs/pages/x/api/data-grid/data-grid-premium.json
docs/translations/api-docs/data-grid/data-grid-premium/data-grid-premium.json
packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
packages/x-data-grid-premium/src/DataGridPremium/useDataGridPremiumProps.ts
packages/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts
packages/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts
packages/x-data-grid-premium/src/models/dataGridPremiumProps.ts

fix https://github.com/mui/mui-x/issues/16689

[DataGridPremium] Fix copy of a cell range that includes empty cells

---

docs/data/migration/migration-pickers-v7/migration-pickers-v7.md

[docs][pickers] Fix migration guide references to range fields

---

dangerfile.js

Ensure the scheduler docs changes resolve to an existing documentation link.

[infra] Ensure proper docs preview path resolution

---

packages/x-data-grid-pro/src/components/GridDetailPanelToggleCell.tsx

Closes #17082
- [✓] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

[DataGridPro] Add `aria-expanded` attribute to the Master detail toggle button

---

test/regressions/index.test.ts

Related https://github.com/mui/mui-x/issues/17862
not sure it fixes the issue, but if it does it is a quick win, since it doesn't always happen on CI

[code-infra] Increase charts export test timeout

---

docs/pages/x/api/tree-view/tree-item.json
docs/translations/api-docs/tree-view/tree-item/tree-item.json
packages/x-tree-view/src/TreeItem/TreeItem.tsx
packages/x-tree-view/src/TreeItem/TreeItem.types.ts

[TreeView] Add missing sx prop on the Tree Item component

---

packages/x-date-pickers/src/PickersTextField/PickersTextField.tsx

closes https://github.com/mui/mui-x/issues/17888

[pickers] Fix `PickersTextField` overflow

---

packages/x-data-grid/src/material/variables.ts
packages/x-data-grid/src/models/configuration/gridConfiguration.ts
packages/x-data-grid/src/utils/css/context.tsx

Fixes #17812 
Before: https://codesandbox.io/p/sandbox/elegant-brahmagupta-rf32c9
After: https://codesandbox.io/p/sandbox/silly-ully-36dkrv

[DataGrid] Fix disabled typography variants crashing grid

---

docs/data/charts/scatter/ScatterCustomShape.js
docs/data/charts/scatter/ScatterCustomShape.tsx

Fix scatter shape demo causing horizontal overflow
Before:
https://github.com/user-attachments/assets/516919ac-85d3-4f00-8ea3-d5c9e2d3ae72
After: 
https://github.com/user-attachments/assets/fcfdcb2e-9fff-47e2-bcfb-63ab683a30ac

[docs] Fix scatter shape demo causing horizontal overflow

---

scripts/releaseChangelog.mjs

Improve the typography in the generated changelog based on Grammarly suggestions.

[infra] Improve release changelog generation

---

packages/x-data-grid/src/tests/toolbar.DataGrid.test.tsx

[code-infra] Fix act warnings in DataGrid/toolbar

---

packages/x-charts/src/BarChart/seriesConfig/seriesProcessor.ts

[charts] Let line series propagate null from the dataset

---

packages/x-charts/src/ChartsGrid/ChartsGrid.test.tsx
packages/x-charts/src/ChartsGrid/ChartsHorizontalGrid.tsx
packages/x-charts/src/ChartsGrid/ChartsVerticalGrid.tsx

[charts] Fix grid with band scale

---

packages/x-data-grid/src/material/variables.ts

Fixes https://github.com/mui/mui-x/issues/18272
https://github.com/user-attachments/assets/381cf06d-3151-4fdf-a533-18b85d6a4dd5
https://github.com/user-attachments/assets/fcb9324a-701c-4c10-be62-5a5c4ddbed44

[DataGrid] Fix data grid palette when using CSS vars

---

packages/x-charts-pro/src/BarChartPro/BarChartPro.zoom.test.tsx
packages/x-charts-pro/src/LineChartPro/LineChartPro.zoom.test.tsx
packages/x-charts-pro/src/ScatterChartPro/ScatterChartPro.zoom.test.tsx
packages/x-charts/src/BarChart/BarChart.test.tsx
packages/x-charts/src/BarChart/checkClickEvent.test.tsx
packages/x-charts/src/ChartsTooltip/contentDisplayed.test.tsx
packages/x-charts/src/LineChart/checkClickEvent.test.tsx
packages/x-charts/src/PieChart/checkClickEvent.test.tsx
packages/x-charts/src/ScatterChart/checkClickEvent.test.tsx

[charts] Remove unnecessary style changes in tests

---

packages/x-date-pickers-pro/vitest.config.browser.mts
packages/x-date-pickers-pro/vitest.config.jsdom.mts
packages/x-date-pickers/vitest.config.browser.mts
packages/x-date-pickers/vitest.config.jsdom.mts
packages/x-internal-gestures/vitest.config.browser.mts
vitest.shared.mts

Address: https://github.com/mui/mui-x/pull/18228#pullrequestreview-2938468760.

[code-infra] Strengthen `URL` usage for test config

---

packages/x-charts-pro/src/internals/plugins/useChartProExport/print.ts

Before:
https://github.com/user-attachments/assets/af288166-90bc-41ac-94df-49e91b41135a
After:
https://github.com/user-attachments/assets/35bf16a9-404e-44d1-8e37-fdbe697e1d6a

[charts-pro] Fix iframe not being removed after print export

---

packages/x-charts/src/internals/plugins/featurePlugins/useChartPolarAxis/useChartPolarAxis.ts

Based on: https://github.com/mui/mui-x/pull/17480#discussion_r2166631831

[charts] Improve touch behavior for polar axis

---

CHANGELOG.md
package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json

[release] v7.29.7

---

.circleci/config.yml

Fixes the `test_package` failing in v7 due to the addition of bundle size reporting from [this PR](https://github.com/mui/mui-x/pull/17754).

[infra] Add  `test_package` to fix CI

---

packages/x-charts/src/ScatterChart/Scatter.tsx
packages/x-charts/src/ScatterChart/useScatterPlotData.ts
packages/x-charts/src/hooks/useInteractionItemProps.ts
packages/x-charts/src/internals/index.ts

Part of https://github.com/mui/mui-x/issues/15383. Cherry-picked from https://github.com/mui/mui-x/pull/18267.
Extract plot logic into separate files for reuse. In https://github.com/mui/mui-x/pull/18267, these hooks will also be used by the preview components.

[charts] Extract plot logic into separate files for reuse

---

docs/data/charts/localization/data.json
packages/x-charts/src/locales/elGR.ts
packages/x-charts/src/locales/index.ts

[l10n] Add Greek (el-GR) locale to charts

---

docs/data/migration/migration-pickers-v7/migration-pickers-v7.md

Address the following suggestion: https://github.com/mui/mui-x/issues/18606#issuecomment-3019346128

[docs][pickers] Add mention of theme augmentation in relevant migration section

---

docs/data/charts/pie/pie.md

Document pie center issue with composition #18538

[docs] Provide workaround for pie chart composition

---

docs/data/data-grid/localization/data.json
packages/x-data-grid/src/locales/idID.ts
packages/x-data-grid/src/locales/index.ts

[l10n] Add Indonesian (id-ID) locale

---

packages/x-scheduler/src/joy/day-view/DayView.tsx
packages/x-scheduler/src/joy/day-view/DayView.types.ts
packages/x-scheduler/src/joy/internals/components/day-time-grid/DayTimeGrid.css
packages/x-scheduler/src/joy/internals/components/day-time-grid/DayTimeGrid.tsx
packages/x-scheduler/src/joy/internals/components/day-time-grid/DayTimeGrid.types.ts
packages/x-scheduler/src/joy/internals/components/day-time-grid/index.ts
packages/x-scheduler/src/joy/internals/components/time-grid/index.ts
packages/x-scheduler/src/joy/month-view/MonthView.types.ts
packages/x-scheduler/src/joy/week-view/WeekView.tsx
packages/x-scheduler/src/joy/week-view/WeekView.types.ts

[scheduler] Rename `<TimeGrid />` `<DayTimeGrid />` to prepare for all-day events

---

renovate.json

[code-infra] Extend renovate preset from infra repo

---

packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts
packages/x-data-grid/src/tests/rowSelection.DataGrid.test.tsx

Fixes https://github.com/mui/mui-x/issues/17878#issuecomment-3084263294

[DataGrid] Fix row selection "exclude" model inconsistency

---

packages/x-data-grid-premium/src/hooks/features/rowGrouping/createGroupingColDef.tsx
packages/x-data-grid-premium/src/tests/rowGrouping.DataGridPremium.test.tsx

Before: https://stackblitz.com/edit/a1gcnnej?file=src%2FDemo.tsx
After: https://stackblitz.com/edit/a1gcnnej-tdyghmtf?file=src%2FDemo.tsx

[DataGridPremium] Fix empty nested group values caused by main criterial valueFormatter

---

packages/x-scheduler/src/primitives/time-grid/event-resize-handler/TimeGridEventResizeHandler.test.tsx

I forgot to add the conformance test when creating this part

[scheduler][primitives] Add missing conformance test to the `TimeGridEventResizeHandler` part

---

packages/x-charts/src/internals/plugins/featurePlugins/useChartVoronoi/useChartVoronoi.ts

Fix #18908
The issue came from a trick that works for static charts but not zoom ones.
To avoid having to manage coordinates all points outside of the drawing area were moved to a "trash coordinate" at (-drawing_width, -drawing_height) such that any moint inside the drawing area will be closer to the pointer than the trash coordinate.
Here is an illustration of the transformation where from the real data (the left chart) we move all points outside the drawing are (black rectangle) to the trash point (the red one) and give this representation to the delauney computation
If you have no data in the drawing area, the closer point is the trash point which contains all the scatter point. So Delauney retruns the first data point.
This PR effectively remove the data point that are outside of the …

[charts-pro] Fix voronoi interaction with zoom

---

docs/pages/x/api/data-grid/grid-aggregation-function.json
packages/x-data-grid-generator/src/hooks/serverUtils.ts
packages/x-data-grid-premium/src/hooks/features/aggregation/gridAggregationInterfaces.ts

Addresses https://github.com/mui/mui-x/issues/18899#issuecomment-3114725199

[DataGridPremium] Make `api` param for the aggregation function optional

---

packages/x-virtualizer/package.json
pnpm-lock.yaml

Closes #19007 
Add missing `@mui/utils`.

[virtualizer] Add missing dependency

---

docs/data/charts/heatmap/heatmap.md

[charts] Fix Heatmap docs duplicate text

---

packages/x-charts/src/ChartsTooltip/ChartsTooltipContainer.tsx

Before:
https://github.com/user-attachments/assets/9fbd5ca8-3c92-45b1-9761-a2d4f0d8b589
After:
https://github.com/user-attachments/assets/13f71ac7-c8f0-46b5-87be-e44f3fbd3b82

[charts] Prevent overflow on charts tooltip

---

docs/data/charts/animation/CSSAnimationCustomization.js
docs/data/charts/animation/CSSAnimationCustomization.tsx
docs/data/charts/animation/CSSAnimationCustomization.tsx.preview
docs/data/charts/animation/animation.md

Fixes https://github.com/mui/mui-x/pull/18990#discussion_r2252526893.

[charts] Update animation customization docs

---

packages/x-tree-view-pro/src/internals/plugins/useTreeViewLazyLoading/useTreeViewLazyLoading.ts
packages/x-tree-view/src/internals/index.ts
packages/x-tree-view/src/internals/plugins/useTreeViewExpansion/useTreeViewExpansion.ts
packages/x-tree-view/src/internals/plugins/useTreeViewExpansion/useTreeViewExpansion.types.ts

Part of https://github.com/mui/mui-x/issues/19022

[tree view] Fix root not loading from cache on remount

---

packages/x-data-grid/src/components/GridRow.tsx

[DataGrid] Fix no row with id error

---

scripts/changelogUtils.mjs

Implement https://www.notion.so/mui-org/Labeling-in-GitHub-1f1cbfe7b66081d8b18de652877d671e#209cbfe7b660809b9528ff22dfa4c1f1.

[internal] Rename core to internal

---

packages/x-tree-view/src/useTreeItem/useTreeItem.ts
packages/x-tree-view/src/useTreeItem/useTreeItem.types.ts

[tree view] Add aria-hidden to the Tree Item Checkbox

---

packages/x-data-grid/src/components/cell/GridActionsCell.tsx

Fixes https://github.com/mui/mui-x/issues/19333

[DataGrid] Do not add `menu` role to the empty actions menu

---

CHANGELOG.md

Fixes changelog issue described in https://github.com/mui/mui-x/issues/15912#issuecomment-3224907179

[internal] Update 8.10.1 changelog with missing changes

---

.github/workflows/publish.yml

It has been failing since yesterday https://github.com/mui/mui-x/actions/workflows/publish.yml

[infra] Fix publish workflow complaint

---

packages/x-scheduler/src/primitives/use-event-calendar/EventCalendarInstance.ts

Regression introduced in #19315

[scheduler] Fix store update when props change

---

.github/workflows/publish.yml

[code-infra] Turn off git checks on publish command

---

CHANGELOG.md
package.json
packages/x-charts-pro/package.json
packages/x-charts/package.json
packages/x-codemod/package.json
packages/x-data-grid-generator/package.json
packages/x-data-grid-premium/package.json
packages/x-data-grid-pro/package.json
packages/x-data-grid/package.json
packages/x-date-pickers-pro/package.json
packages/x-date-pickers/package.json
packages/x-internals/package.json
packages/x-license/package.json
packages/x-tree-view-pro/package.json
packages/x-tree-view/package.json
packages/x-virtualizer/package.json

[release] v8.11.1

---

.github/workflows/publish.yml

[infra] Remove wrong publish option

---

.github/workflows/publish.yml

https://github.com/mui/mui-x/actions/runs/17462628944/job/49590633598

[code-infra] Fix publish token

---

packages/x-charts/src/BarChart/BarChart.test.tsx
packages/x-charts/src/hooks/useInteractionItemProps.ts

[charts] Fix highlight regression

---

docs/data/charts/localization/data.json
packages/x-charts/src/locales/index.ts
packages/x-charts/src/locales/svSE.ts

[l10n][charts] Add svSE locale

---

.circleci/config.yml
vitest.config.mts

Trying to obtain more granular insights on tests
[test_browser](https://app.circleci.com/pipelines/github/mui/mui-x/102594/workflows/1f0fc956-2b9d-413c-9018-3f15d0755da7/jobs/619234/tests)
[test_unit](https://app.circleci.com/pipelines/github/mui/mui-x/102594/workflows/1f0fc956-2b9d-413c-9018-3f15d0755da7/jobs/619230/tests)

[code-infra] Store test results in CI

---

packages/x-scheduler/src/primitives/day-grid/event-placeholder/DayGridEventPlaceholder.tsx
packages/x-scheduler/src/primitives/time-grid/event-placeholder/TimeGridEventPlaceholder.tsx

[scheduler] Remove unused ref in event placeholders

---

packages/x-tree-view/src/internals/plugins/useTreeViewExpansion/useTreeViewExpansion.ts

[pickers] Fix `apiRef.current.isItemExpanded()` method

---

docs/data/charts/export/PrintChart.js
docs/data/charts/export/PrintChart.tsx
docs/data/charts/export/export.md
docs/pages/x/api/charts/sankey-chart.json
packages/x-charts-pro/src/SankeyChart/SankeyChart.plugins.ts
packages/x-charts-pro/src/SankeyChart/SankeyChart.tsx
packages/x-charts-pro/src/context/ChartProApi.ts

[charts-pro] Allow exporting `SankeyChart`

---

.github/CODEOWNERS

@prakhargupta1 This will mark you as a code owner of the charts docs.
What does it means? Each time a file in the `docs/data/charts` folder get modified by a PR, you will be added as a reviewer.
With that you should avoid PR that are just bug fixes, but get involved in all PR about DX/new features
This might be too much noise. So it's up to you to approve and merge this PR or not if you prefer being added manually as a reviewer
You have my approval to close this PR 😉

[infra][charts] Add Prakharas a codeowner of the docs

---

docs/data/charts/legend/legend.md
docs/data/charts/toolbar/toolbar.md
packages/x-charts/src/ChartsLegend/ContinuousColorLegend.tsx
packages/x-charts/src/ChartsLegend/PiecewiseColorLegend.tsx
packages/x-charts/src/ChartsWrapper/ChartsWrapper.tsx
packages/x-charts/src/Toolbar/Toolbar.tsx
test/regressions/charts/ToolbarLegendPosition.tsx

[charts] Fix horizontal layout and tooltip

---

CHANGELOG.md
package.json
packages/x-tree-view-pro/package.json
packages/x-tree-view/package.json

[release] v7.29.10

---

packages/x-scheduler/src/material/internals/components/day-time-grid/DayTimeGrid.tsx
packages/x-scheduler/src/material/internals/components/event/day-grid-event/DayGridEvent.tsx
packages/x-scheduler/src/material/internals/components/event/time-grid-event/TimeGridEvent.tsx
packages/x-scheduler/src/primitives/models/event.ts
packages/x-scheduler/src/primitives/use-event-calendar/EventCalendarStore.selectors.ts
packages/x-scheduler/src/primitives/utils/SchedulerStore/SchedulerStore.selectors.ts
packages/x-scheduler/src/primitives/utils/event-utils.ts

Based on https://github.com/mui/mui-x/pull/19580#discussion_r2367415026

[scheduler] Move all the `isEventResizable` and `isEventDraggable` logic inside selectors

---

.github/workflows/codspeed.yml

Fixes new version issue https://github.com/mui/mui-x/actions/runs/18041203036/job/51340292991?pr=19727

[code-infra] Change charts codspeed integration to use walltime

---

packages/x-data-grid/src/components/toolbarV8/GridToolbar.tsx

closes https://github.com/mui/mui-x/issues/19592
https://stackblitz.com/edit/d4dwyfkx-bssgzgmn
https://stackblitz.com/edit/8gkkdgki?file=src%2FDemo.tsx

[DataGrid] Fix toolbar slotProps not being applied

---

scripts/buildApiDocs/tsconfig.json
tsconfig.json

See https://github.com/mui/material-ui/pull/47044

[code-infra] Remove tsconfig `baseUrl`

---

docs/src/modules/components/DemoPropsForm.tsx

I had it in the wrong element before 😭

[charts][docs] Fix demo title knob keys
